backend/node_modules/@grpc/proto-loader/build/src/index.js File Reference
Functions
function isAnyExtension (obj)
function joinName (baseName, name)
function isHandledReflectionObject (obj)
function isNamespaceBase (obj)
function getAllHandledReflectionObjects (obj, parentName)
function createDeserializer (cls, options)
function createSerializer (cls)
function mapMethodOptions (options)
function createMethodDefinition (method, serviceName, options, fileDescriptors)
function createServiceDefinition (service, name, options, fileDescriptors)
function createMessageDefinition (message, fileDescriptors)
function createEnumDefinition (enumType, fileDescriptors)
function createDefinition (obj, name, options, fileDescriptors)
function createPackageDefinition (root, options)
function createPackageDefinitionFromDescriptorSet (decodedDescriptorSet, options)
function load (filename, options)
function loadSync (filename, options)
function fromJSON (json, options)
function loadFileDescriptorSetFromBuffer (descriptorSet, options)
function loadFileDescriptorSetFromObject (descriptorSet, options)
Variables
use strict
exports loadFileDescriptorSetFromObject = exports.loadFileDescriptorSetFromBuffer = exports.fromJSON = exports.loadSync = exports.load = exports.IdempotencyLevel = exports.isAnyExtension = exports.Long = void 0
const camelCase = require("lodash.camelcase")
const Protobuf = require("protobufjs")
const descriptor = require("protobufjs/ext/descriptor")
const util_1 = require("./util")
const Long = require("long")
exports isAnyExtension = isAnyExtension
var IdempotencyLevel
const descriptorOptions
exports load = load
exports loadSync = loadSync
exports fromJSON = fromJSON
exports loadFileDescriptorSetFromBuffer = loadFileDescriptorSetFromBuffer
Function Documentation
createDefinition()
function createDefinition (obj, name, options, fileDescriptors)
function createDefinition(obj: Protobuf.Service, name: string, options: Options): ServiceDefinition; function createDefinition(obj: Protobuf.Type, name: string, options: Options): MessageTypeDefinition; function createDefinition(obj: Protobuf.Enum, name: string, options: Options): EnumTypeDefinition;
References createEnumDefinition(), createMessageDefinition(), createServiceDefinition(), name, obj, and Protobuf.
createDeserializer()
function createDeserializer (cls, options)
createEnumDefinition()
function createEnumDefinition (enumType, fileDescriptors)
References descriptorOptions, format, and type.
createMessageDefinition()
function createMessageDefinition (message, fileDescriptors)
References descriptorOptions, format, message, and type.
createMethodDefinition()
function createMethodDefinition (method, serviceName, options, fileDescriptors)
References camelCase, createDeserializer(), createMessageDefinition(), createSerializer(), mapMethodOptions(), method, and path.
createPackageDefinition()
function createPackageDefinition (root, options)
References createDefinition(), descriptor, getAllHandledReflectionObjects(), name, obj, of, root, and value.
createPackageDefinitionFromDescriptorSet()
function createPackageDefinitionFromDescriptorSet (decodedDescriptorSet, options)
References createPackageDefinition(), Protobuf, and root.
createSerializer()
function createSerializer (cls)
References $, Array, expected, message, and serialize.
createServiceDefinition()
function createServiceDefinition (service, name, options, fileDescriptors)
References createMethodDefinition(), method, name, and of.
fromJSON()
function fromJSON (json, options)
References createPackageDefinition(), and Protobuf.
getAllHandledReflectionObjects()
function getAllHandledReflectionObjects (obj, parentName)
References getAllHandledReflectionObjects(), isHandledReflectionObject(), isNamespaceBase(), joinName(), name, obj, and reduce.
isAnyExtension()
function isAnyExtension (obj)
References obj.
isHandledReflectionObject()
function isHandledReflectionObject (obj)
References obj, and Protobuf.
isNamespaceBase()
function isNamespaceBase (obj)
References obj, and Protobuf.
joinName()
function joinName (baseName, name)
References name.
load()
function load (filename, options)
Load a .proto file with the specified options.
Parameters
filename One or multiple file paths to load. Can be an absolute path or relative to an include path.
options.keepCase Preserve field names. The default is to change them to camel case.
options.longs The type that should be used to represent long values. Valid options are Number and String. Defaults to a Long object type from a library.
options.enums The type that should be used to represent enum values. The only valid option is String. Defaults to the numeric value.
options.bytes The type that should be used to represent bytes values. Valid options are Array and String. The default is to use Buffer.
options.defaults Set default values on output objects. Defaults to false.
options.arrays Set empty arrays for missing array values even if defaults is false. Defaults to false.
options.objects Set empty objects for missing object values even if defaults is false. Defaults to false.
options.oneofs Set virtual oneof properties to the present field's name
options.json Represent Infinity and NaN as strings in float fields, and automatically decode google.protobuf.Any values.
options.includeDirs Paths to search for imported .proto files.
References createPackageDefinition(), filename, then, and util_1.
loadFileDescriptorSetFromBuffer()
function loadFileDescriptorSetFromBuffer (descriptorSet, options)
References createPackageDefinitionFromDescriptorSet(), and descriptor.
loadFileDescriptorSetFromObject()
function loadFileDescriptorSetFromObject (descriptorSet, options)
References createPackageDefinitionFromDescriptorSet(), and descriptor.
loadSync()
function loadSync (filename, options)
References createPackageDefinition(), filename, and util_1.
mapMethodOptions()
function mapMethodOptions (options)
References IdempotencyLevel, obj, of, and value.
Variable Documentation
camelCase
const camelCase = require("lodash.camelcase")
descriptor
const descriptor = require("protobufjs/ext/descriptor")
descriptorOptions
const descriptorOptions
Initial value:
= {
    longs: String,
    enums: String,
    bytes: String,
    defaults: true,
    oneofs: true,
    json: true,
}
fromJSON
exports fromJSON = fromJSON
IdempotencyLevel
function IdempotencyLevel
Initial value:
{
    IdempotencyLevel["IDEMPOTENCY_UNKNOWN"] = "IDEMPOTENCY_UNKNOWN"
isAnyExtension
exports isAnyExtension = isAnyExtension
load
exports load = load
loadFileDescriptorSetFromBuffer
exports loadFileDescriptorSetFromBuffer = loadFileDescriptorSetFromBuffer
loadFileDescriptorSetFromObject
exports loadFileDescriptorSetFromObject = exports.loadFileDescriptorSetFromBuffer = exports.fromJSON = exports.loadSync = exports.load = exports.IdempotencyLevel = exports.isAnyExtension = exports.Long = void 0
loadSync
exports loadSync = loadSync
Long
exports Long = require("long")
Protobuf
const Protobuf = require("protobufjs")
strict
use strict
util_1
const util_1 = require("./util")