backend/node_modules/@google-cloud/storage/node_modules/uuid/dist/esm-node/v35.js File Reference
Functions
function stringToBytes (str)
function default (name, version, hashfunc)
Variables
import stringify from stringify js
export const DNS = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
export const URL = '6ba7b811-9dad-11d1-80b4-00c04fd430c8'
Function Documentation
default()
function default (name, version, hashfunc)
References buf, bytes, DNS, i, length, name, stringify, stringToBytes(), Uint8Array, URL, value, and version.
stringToBytes()
function stringToBytes (str)
References bytes, i, str(), and unescape().
Variable Documentation
DNS
export const DNS = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
js
import parse from parse js
URL
export const URL = '6ba7b811-9dad-11d1-80b4-00c04fd430c8'