backend/node_modules/@google-cloud/firestore/build/src/util.js File Reference
Classes
class Deferred
Functions
function isObject (value)
function isPlainObject (input)
function isEmpty (value)
function isFunction (value)
function isPermanentRpcError (err, methodName)
function getServiceConfig (methodName)
function getRetryCodes (methodName)
function getTotalTimeout (methodName)
function getRetryParams (methodName)
function silencePromise (promise)
function wrapError (err, stack)
function mapToArray (obj, fn)
function isArrayEqual (left, right)
function isPrimitiveArrayEqual (left, right)
Variables
use strict
exports Deferred = void 0
exports autoId = autoId
exports requestTag = requestTag
exports isObject = isObject
exports isPlainObject = isPlainObject
exports isEmpty = isEmpty
exports isFunction = isFunction
exports isPermanentRpcError = isPermanentRpcError
exports getRetryCodes = getRetryCodes
exports getTotalTimeout = getTotalTimeout
exports getRetryParams = getRetryParams
exports silencePromise = silencePromise
exports wrapError = wrapError
exports tryGetPreferRestEnvironmentVariable = tryGetPreferRestEnvironmentVariable
exports mapToArray = mapToArray
exports isArrayEqual = isArrayEqual
exports isPrimitiveArrayEqual = isPrimitiveArrayEqual
const crypto_1 = require("crypto")
const gapicConfig = require("./v1/firestore_client_config.json")
let serviceConfig
Function Documentation
getRetryCodes()
function getRetryCodes (methodName) [private]
Returns the list of retryable error codes specified in the service configuration.
References _a, _b, _c, and getServiceConfig().
getRetryParams()
function getRetryParams (methodName) [private]
Returns the backoff setting from the service configuration.
References _a, _b, _c, createDefaultBackoffSettings, getServiceConfig(), and require().
getServiceConfig()
function getServiceConfig (methodName) [private]
Lazy-loads the service config when first accessed.
References gapicConfig, require(), and serviceConfig.
getTotalTimeout()
function getTotalTimeout (methodName) [private]
Gets the total timeout in milliseconds from the retry settings in the service config for the given RPC. If the total timeout is not set, then 0 is returned.
References _a, _b, _c, _d, and getServiceConfig().
isArrayEqual()
function isArrayEqual (left, right) [private]
Verifies equality for an array of objects using the isEqual interface.
References i, isEqual, left, and right.
isEmpty()
function isEmpty (value) [private]
Returns whether value has no custom properties.
References value.
isFunction()
function isFunction (value) [private]
Determines whether value is a JavaScript function.
References value.
isObject()
function isObject (value) [private]
Determines whether value is a JavaScript object.
References value.
isPermanentRpcError()
function isPermanentRpcError (err, methodName) [private]
Determines whether the provided error is considered permanent for the given RPC.
References getRetryCodes, and undefined.
isPlainObject()
function isPlainObject (input) [private]
Verifies that 'obj' is a plain JavaScript object that can be encoded as a 'Map' in Firestore.
References isObject.
isPrimitiveArrayEqual()
function isPrimitiveArrayEqual (left, right) [private]
Verifies equality for an array of primitives.
References i, left, and right.
mapToArray()
function mapToArray (obj, fn) [private]
Returns an array of values that are calculated by performing the given fn on all keys in the given obj dictionary.
References fn, obj, and result.
silencePromise()
function silencePromise (promise) [private]
Returns a promise with a void return type. The returned promise swallows all errors and never throws.
This is primarily used to wait for a promise to complete when the result of the promise will be discarded.
wrapError()
function wrapError (err, stack) [private]
Wraps the provided error in a new error that includes the provided stack.
Used to preserve stack traces across async calls.
Variable Documentation
autoId
function autoId () = autoId
Generate a unique client-side identifier.
Used for the creation of new documents.
crypto_1
const crypto_1 = require("crypto")
Deferred
exports Deferred = void 0
gapicConfig
const gapicConfig = require("./v1/firestore_client_config.json")
getRetryCodes
exports getRetryCodes = getRetryCodes
getRetryParams
exports getRetryParams = getRetryParams
getTotalTimeout
exports getTotalTimeout = getTotalTimeout
isArrayEqual
exports isArrayEqual = isArrayEqual
isEmpty
exports isEmpty = isEmpty
isFunction
exports isFunction = isFunction
isObject
exports isObject = isObject
isPermanentRpcError
exports isPermanentRpcError = isPermanentRpcError
isPlainObject
exports isPlainObject = isPlainObject
isPrimitiveArrayEqual
exports isPrimitiveArrayEqual = isPrimitiveArrayEqual
mapToArray
exports mapToArray = mapToArray
requestTag
function requestTag () = requestTag
Generate a short and semi-random client-side identifier.
Used for the creation of request tags.
serviceConfig
let serviceConfig
silencePromise
exports silencePromise = silencePromise
strict
use strict
tryGetPreferRestEnvironmentVariable
function tryGetPreferRestEnvironmentVariable () = tryGetPreferRestEnvironmentVariable
Parses the value of the environment variable FIRESTORE_PREFER_REST, and returns a value indicating if the environment variable enables or disables preferRest.
This function will warn to the console if the environment variable is set to an unsupported value.
Returns
true if the environment variable enables preferRest, false if the environment variable disables preferRest, or undefined if the environment variable is not set or is set to an unsupported value.
wrapError
exports wrapError = wrapError