backend/node_modules/@protobufjs/float/index.js File Reference
Functions
 util.float.readDoubleBE
Reads a 64 bit double from a buffer using big endian byte order.
@function
Parameters
{Uint8Array} buf Source buffer
{number} pos Source buffer offset
Returns
{number} Value read
function factory (exports)
function writeUintLE (val, buf, pos)
function writeUintBE (val, buf, pos)
function readUintLE (buf, pos)
function readUintBE (buf, pos)
Variables
use strict
module exports = factory(factory)
Function Documentation
factory()
function factory (exports)
References buf, e, exports, Float32Array, Float64Array, isNaN, le, readUintBE(), readUintLE(), sign, Uint8Array, writeUintBE(), and writeUintLE().
readUintBE()
function readUintBE (buf, pos)
References buf.
readUintLE()
function readUintLE (buf, pos)
References buf.
writeUintBE()
function writeUintBE (val, buf, pos)
References buf.
writeUintLE()
function writeUintLE (val, buf, pos)
References buf.
Variable Documentation
exports
module exports = factory(factory)
strict
use strict