backend/node_modules/lodash/fp/_baseConvert.js File Reference
Functions
function baseArity (func, n)
function baseAry (func, n)
function cloneArray (array)
function createCloner (func)
function flatSpread (func, start)
function wrapImmutable (func, cloner)
function baseConvert (util, name, func, options)
Variables
var mapping = require('./_mapping')
var fallbackHolder = require('./placeholder')
var push = Array.prototype.push
module exports = baseConvert
Function Documentation
baseArity()
function baseArity (func, n) [private]
Creates a function, with an arity of n, that invokes func with the arguments it receives.
Parameters
{Function} func The function to wrap.
{number} n The arity of the new function.
Returns
{Function} Returns the new function.
References a, b, func, n, and undefined.
baseAry()
function baseAry (func, n) [private]
Creates a function that invokes func, with up to n arguments, ignoring any additional arguments.
Parameters
{Function} func The function to cap arguments for.
{number} n The arity cap.
Returns
{Function} Returns the new function.
References a, b, func, and n.
baseConvert()
function baseConvert (util, name, func, options) [private]
The base implementation of convert which accepts a util object of methods required to perform conversions.
Parameters
{Object} util The util object.
{string} name The name of the function to convert.
{Function} func The function to convert.
{Object} [options] The options object.
{boolean} [options.cap=true] Specify capping iteratee arguments.
{boolean} [options.curry=true] Specify currying.
{boolean} [options.fixed=true] Specify fixed arity.
{boolean} [options.immutable=true] Specify immutable operations.
{boolean} [options.rearg=true] Specify rearranging arguments.
Returns
{Function|Object} Returns the converted function or object.
Casts func to a function with an arity capped iteratee if needed.
Parameters
{string} name The name of the function to inspect.
{Function} func The function to inspect.
Returns
{Function} Returns the cast function.
Casts func to a curried function if needed.
Parameters
{string} name The name of the function to inspect.
{Function} func The function to inspect.
{number} n The arity of func.
Returns
{Function} Returns the cast function.
Casts func to a fixed arity function if needed.
Parameters
{string} name The name of the function to inspect.
{Function} func The function to inspect.
{number} n The arity cap.
Returns
{Function} Returns the cast function.
Casts func to an rearged function if needed.
Parameters
{string} name The name of the function to inspect.
{Function} func The function to inspect.
{number} n The arity of func.
Returns
{Function} Returns the cast function.
Creates a clone of object by path.
Parameters
{Object} object The object to clone.
{Array|string} path The path to clone by.
Returns
{Object} Returns the cloned object.
Converts lodash to an immutable auto-curried iteratee-first data-last version with conversion options applied.
Parameters
{Object} [options] The options object. See baseConvert for more details.
Returns
{Function} Returns the converted lodash.
Create a converter function for func of name.
Parameters
{string} name The name of the function to convert.
{Function} func The function to convert.
Returns
{Function} Returns the new converter function.
Creates a function that wraps func to invoke its iteratee, with up to n arguments, ignoring any additional arguments.
Parameters
{Function} func The function to cap iteratee arguments for.
{number} n The arity cap.
Returns
{Function} Returns the new function.
Creates a function that wraps func to invoke its iteratee with arguments arranged according to the specified indexes where the argument value at the first index is provided as the first argument, the argument value at the second index is provided as the second argument, and so on.
Parameters
{Function} func The function to rearrange iteratee arguments for.
{number[]} indexes The arranged argument indexes.
Returns
{Function} Returns the new function.
Creates a function that invokes func with its first argument transformed.
Parameters
{Function} func The function to wrap.
{Function} transform The argument transform.
Returns
{Function} Returns the new function.
Creates a function that wraps func and applys the conversions rules by name.
Parameters
{string} name The name of the function to wrap.
{Function} func The function to wrap.
Returns
{Function} Returns the converted function.
References _, args, Array, ary, assign, baseArity(), baseAry(), baseConvert, castArray(), clone, cloneArray(), config, context, createCloner(), curry(), data, each, fallbackHolder, flatSpread(), func, index, isArray, isError, isFunction, isWeakMap(), iteratee, iterateeAry, iterateeRearg, keys, lastIndex, length, mapping, mixin, n, name, nthArg(), overArg, pairs, path, placeholder, rearg, result, source, start, toInteger, toPath(), transform, undefined, util, value, wrap, wrapImmutable(), and wrappers.
cloneArray()
function cloneArray (array) [private]
Creates a clone of array.
Parameters
{Array} array The array to clone.
Returns
{Array} Returns the cloned array.
References Array, length, and result.
createCloner()
function createCloner (func) [private]
Creates a function that clones a given object using the assignment func.
Parameters
{Function} func The assignment function.
Returns
{Function} Returns the new cloner function.
References func, and object.
flatSpread()
function flatSpread (func, start) [private]
A specialized version of _.spread which flattens the spread array into the arguments of the invoked func.
Parameters
{Function} func The function to spread arguments over.
{number} start The start position of the spread.
Returns
{Function} Returns the new function.
References args, Array, func, lastIndex, length, push, and start.
wrapImmutable()
function wrapImmutable (func, cloner) [private]
Creates a function that wraps func and uses cloner to clone the first argument it receives.
Parameters
{Function} func The function to wrap.
{Function} cloner The function to clone arguments.
Returns
{Function} Returns the new immutable function.
References args, Array, func, length, result, and undefined.
Variable Documentation
exports
module exports = baseConvert
fallbackHolder
var fallbackHolder = require('./placeholder')
mapping
var mapping = require('./_mapping')
push
var push = Array.prototype.push
Built-in value reference.