backend/node_modules/readable-stream/lib/_stream_writable.js File Reference
Functions
function WriteReq (chunk, encoding, cb)
function CorkedRequest (state)
function _uint8ArrayToBuffer (chunk)
function _isUint8Array (obj)
require ('inherits')(Writable
function nop ()
function WritableState (options, stream, isDuplex)
if (typeof Symbol==='function' &&Symbol.hasInstance &&typeof Function.prototype[Symbol.hasInstance]==='function')
function Writable (options)
function writeAfterEnd (stream, cb)
function validChunk (stream, state, chunk, cb)
function decodeChunk (state, chunk, encoding)
function writeOrBuffer (stream, state, isBuf, chunk, encoding, cb)
function doWrite (stream, state, writev, len, chunk, encoding, cb)
function onwriteError (stream, state, sync, er, cb)
function onwriteStateUpdate (state)
function onwrite (stream, er)
function afterWrite (stream, state, finished, cb)
function onwriteDrain (stream, state)
function clearBuffer (stream, state)
function needFinish (state)
function callFinal (stream, state)
function prefinish (stream, state)
function finishMaybe (stream, state)
function endWritable (stream, state, cb)
function onCorkedFinish (corkReq, state, err)
Variables
use strict
module exports = Writable
var Duplex
Writable WritableState = WritableState
var internalUtil
var Stream = require('./internal/streams/stream')
var Buffer = require('buffer').Buffer
var OurUint8Array = (typeof global !== 'undefined' ? global : typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : {}).Uint8Array || function () {}
var destroyImpl = require('./internal/streams/destroy')
var _require = require('./internal/streams/state')
var getHighWaterMark = _require.getHighWaterMark
var _require$codes = require('../errors').codes
var ERR_INVALID_ARG_TYPE = _require$codes.ERR_INVALID_ARG_TYPE
var ERR_METHOD_NOT_IMPLEMENTED = _require$codes.ERR_METHOD_NOT_IMPLEMENTED
var ERR_MULTIPLE_CALLBACK = _require$codes.ERR_MULTIPLE_CALLBACK
var ERR_STREAM_CANNOT_PIPE = _require$codes.ERR_STREAM_CANNOT_PIPE
var ERR_STREAM_DESTROYED = _require$codes.ERR_STREAM_DESTROYED
var ERR_STREAM_NULL_VALUES = _require$codes.ERR_STREAM_NULL_VALUES
var ERR_STREAM_WRITE_AFTER_END = _require$codes.ERR_STREAM_WRITE_AFTER_END
var ERR_UNKNOWN_ENCODING = _require$codes.ERR_UNKNOWN_ENCODING
var errorOrDestroy = destroyImpl.errorOrDestroy
WritableState prototype getBuffer
var realHasInstance
else
Writable prototype pipe
Writable prototype write
Writable prototype cork
Writable prototype uncork
Writable prototype setDefaultEncoding
Writable prototype _write
Writable prototype _writev = null
Writable prototype end
Writable prototype destroy = destroyImpl.destroy
Writable prototype _undestroy = destroyImpl.undestroy
Writable prototype _destroy
Function Documentation
_isUint8Array()
function _isUint8Array (obj)
References obj, and OurUint8Array.
_uint8ArrayToBuffer()
function _uint8ArrayToBuffer (chunk)
References chunk().
afterWrite()
function afterWrite (stream, state, finished, cb)
References finished, finishMaybe(), onwriteDrain(), state(), and stream.
callFinal()
function callFinal (stream, state)
References errorOrDestroy, finishMaybe(), state(), and stream.
clearBuffer()
function clearBuffer (stream, state)
References Array, buffer, chunk(), CorkedRequest(), count, doWrite(), encoding, l, state(), and stream.
CorkedRequest()
function CorkedRequest (state)
References finish, next(), onCorkedFinish(), and state().
decodeChunk()
function decodeChunk (state, chunk, encoding)
References chunk(), encoding, and state().
doWrite()
function doWrite (stream, state, writev, len, chunk, encoding, cb)
References chunk(), encoding, ERR_STREAM_DESTROYED, state(), and stream.
endWritable()
function endWritable (stream, state, cb)
References finishMaybe(), process, state(), and stream.
finishMaybe()
function finishMaybe (stream, state)
References needFinish(), prefinish(), state(), and stream.
if()
if (typeof Symbol = == 'function' && Symbol.hasInstance && typeof Function.prototype[Symbol.hasInstance] === 'function')
References realHasInstance, Symbol, and Writable.
needFinish()
function needFinish (state)
References state().
nop()
function nop ()
onCorkedFinish()
function onCorkedFinish (corkReq, state, err)
References state().
onwrite()
function onwrite (stream, er)
References afterWrite(), clearBuffer(), ERR_MULTIPLE_CALLBACK, finished, needFinish(), onwriteError(), onwriteStateUpdate(), process, state(), stream, and sync.
onwriteDrain()
function onwriteDrain (stream, state)
References state(), and stream.
onwriteError()
function onwriteError (stream, state, sync, er, cb)
References errorOrDestroy, finishMaybe(), process, state(), stream, and sync.
onwriteStateUpdate()
function onwriteStateUpdate (state)
References state().
prefinish()
function prefinish (stream, state)
References callFinal(), process, state(), and stream.
require()
require ('inherits')
validChunk()
function validChunk (stream, state, chunk, cb)
References chunk(), ERR_INVALID_ARG_TYPE, ERR_STREAM_NULL_VALUES, errorOrDestroy, process, state(), and stream.
Writable()
function Writable (options)
References _destroy, _write, _writev, Duplex, realHasInstance, require(), Stream, Writable, writable, and WritableState.
WritableState()
function WritableState (options, stream, isDuplex)
References CorkedRequest(), Duplex, finished, getHighWaterMark, length, objectMode, onwrite(), require(), stream, and sync.
writeAfterEnd()
function writeAfterEnd (stream, cb)
References ERR_STREAM_WRITE_AFTER_END, errorOrDestroy, process, and stream.
writeOrBuffer()
function writeOrBuffer (stream, state, isBuf, chunk, encoding, cb)
References callback, chunk(), decodeChunk(), doWrite(), encoding, last, next(), state(), and stream.
WriteReq()
function WriteReq (chunk, encoding, cb)
References callback, chunk(), encoding, and next().
Variable Documentation
_destroy
Writable prototype _destroy
Initial value:
= function (err, cb) {
  cb(err);
}
_require
var _require = require('./internal/streams/state')
_require$codes
var _require$codes = require('../errors').codes
_undestroy
Writable prototype _undestroy = destroyImpl.undestroy
_write
Writable prototype _write
Initial value:
= function (chunk, encoding, cb) {
  cb(new ERR_METHOD_NOT_IMPLEMENTED('_write()'));
}
_writev
Writable prototype _writev = null
Buffer
var Buffer = require('buffer').Buffer
cork
Writable prototype cork
Initial value:
= function () {
  this._writableState.corked++;
}
destroy
Writable prototype destroy = destroyImpl.destroy
destroyImpl
var destroyImpl = require('./internal/streams/destroy')
Duplex
var Duplex
else
else
Initial value:
{
  realHasInstance = function realHasInstance(object) {
    return object instanceof this;
  }
end
Writable prototype end
Initial value:
= function (chunk, encoding, cb) {
  var state = this._writableState;
  if (typeof chunk === 'function') {
    cb = chunk;
    chunk = null;
    encoding = null;
  } else if (typeof encoding === 'function') {
    cb = encoding;
    encoding = null;
  }
  if (chunk !== null && chunk !== undefined) this.write(chunk, encoding);
  
  if (state.corked) {
    state.corked = 1;
    this.uncork();
  }
  
  if (!state.ending) endWritable(this, state, cb);
  return this;
}
ERR_INVALID_ARG_TYPE
var ERR_INVALID_ARG_TYPE = _require$codes.ERR_INVALID_ARG_TYPE
ERR_METHOD_NOT_IMPLEMENTED
var ERR_METHOD_NOT_IMPLEMENTED = _require$codes.ERR_METHOD_NOT_IMPLEMENTED
ERR_MULTIPLE_CALLBACK
var ERR_MULTIPLE_CALLBACK = _require$codes.ERR_MULTIPLE_CALLBACK
ERR_STREAM_CANNOT_PIPE
var ERR_STREAM_CANNOT_PIPE = _require$codes.ERR_STREAM_CANNOT_PIPE
ERR_STREAM_DESTROYED
var ERR_STREAM_DESTROYED = _require$codes.ERR_STREAM_DESTROYED
ERR_STREAM_NULL_VALUES
var ERR_STREAM_NULL_VALUES = _require$codes.ERR_STREAM_NULL_VALUES
ERR_STREAM_WRITE_AFTER_END
var ERR_STREAM_WRITE_AFTER_END = _require$codes.ERR_STREAM_WRITE_AFTER_END
ERR_UNKNOWN_ENCODING
var ERR_UNKNOWN_ENCODING = _require$codes.ERR_UNKNOWN_ENCODING
errorOrDestroy
var errorOrDestroy = destroyImpl.errorOrDestroy
exports
module exports = Writable
getBuffer
WritableState prototype getBuffer
Initial value:
= function getBuffer() {
  var current = this.bufferedRequest;
  var out = [];
  while (current) {
    out.push(current);
    current = current.next;
  }
  return out;
}
getHighWaterMark
var getHighWaterMark = _require.getHighWaterMark
internalUtil
var internalUtil
Initial value:
= {
  deprecate: require('util-deprecate')
}
OurUint8Array
var OurUint8Array = (typeof global !== 'undefined' ? global : typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : {}).Uint8Array || function () {}
pipe
Writable prototype pipe
Initial value:
= function () {
  errorOrDestroy(this, new ERR_STREAM_CANNOT_PIPE());
}
realHasInstance
var realHasInstance
Initial value:
{
  try {
    Object.defineProperty(WritableState.prototype, 'buffer', {
      get: internalUtil.deprecate(function writableStateBufferGetter() {
        return this.getBuffer();
      }, '_writableState.buffer is deprecated. Use _writableState.getBuffer ' + 'instead.', 'DEP0003')
    });
  } catch (_) {}
})()
setDefaultEncoding
Writable prototype setDefaultEncoding
Initial value:
= function setDefaultEncoding(encoding) {
  
  if (typeof encoding === 'string') encoding = encoding.toLowerCase();
  if (!(['hex', 'utf8', 'utf-8', 'ascii', 'binary', 'base64', 'ucs2', 'ucs-2', 'utf16le', 'utf-16le', 'raw'].indexOf((encoding + '').toLowerCase()) > -1)) throw new ERR_UNKNOWN_ENCODING(encoding);
  this._writableState.defaultEncoding = encoding;
  return this;
}
Stream
Stream = require('./internal/streams/stream')
strict
use strict
uncork
Writable prototype uncork
Initial value:
= function () {
  var state = this._writableState;
  if (state.corked) {
    state.corked--;
    if (!state.writing && !state.corked && !state.bufferProcessing && state.bufferedRequest) clearBuffer(this, state);
  }
}
WritableState
Writable WritableState = WritableState
write
Writable prototype write
Initial value:
= function (chunk, encoding, cb) {
  var state = this._writableState;
  var ret = false;
  var isBuf = !state.objectMode && _isUint8Array(chunk);
  if (isBuf && !Buffer.isBuffer(chunk)) {
    chunk = _uint8ArrayToBuffer(chunk);
  }
  if (typeof encoding === 'function') {
    cb = encoding;
    encoding = null;
  }
  if (isBuf) encoding = 'buffer';else if (!encoding) encoding = state.defaultEncoding;
  if (typeof cb !== 'function') cb = nop;
  if (state.ending) writeAfterEnd(this, cb);else if (isBuf || validChunk(this, state, chunk, cb)) {
    state.pendingcb++;
    ret = writeOrBuffer(this, state, isBuf, chunk, encoding, cb);
  }
  return ret;
}