backend/node_modules/readable-stream/lib/_stream_readable.js File Reference
Functions
function _uint8ArrayToBuffer (chunk)
function _isUint8Array (obj)
if (debugUtil &&debugUtil.debuglog)
require ('inherits')(Readable
function prependListener (emitter, event, fn)
function ReadableState (options, stream, isDuplex)
function Readable (options)
function readableAddChunk (stream, chunk, encoding, addToFront, skipChunkCheck)
function addChunk (stream, state, chunk, addToFront)
function chunkInvalid (state, chunk)
function computeNewHighWaterMark (n)
function howMuchToRead (n, state)
function onEofChunk (stream, state)
function emitReadable (stream)
function emitReadable_ (stream)
function maybeReadMore (stream, state)
function maybeReadMore_ (stream, state)
function pipeOnDrain (src)
function updateReadableListening (self)
function nReadingNextTick (self)
function resume (stream, state)
function resume_ (stream, state)
function flow (stream)
if (typeof Symbol==='function')
function fromList (n, state)
function endReadable (stream)
function endReadableNT (state, stream)
function indexOf (xs, x)
Variables
use strict
module exports = Readable
var Duplex
Readable ReadableState = ReadableState
var EE = require('events').EventEmitter
var EElistenerCount
var Stream = require('./internal/streams/stream')
var Buffer = require('buffer').Buffer
var OurUint8Array = (typeof global !== 'undefined' ? global : typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : {}).Uint8Array || function () {}
var debugUtil = require('util')
var debug
else
var BufferList = require('./internal/streams/buffer_list')
var destroyImpl = require('./internal/streams/destroy')
var _require = require('./internal/streams/state')
var getHighWaterMark = _require.getHighWaterMark
var _require$codes = require('../errors').codes
var ERR_INVALID_ARG_TYPE = _require$codes.ERR_INVALID_ARG_TYPE
var ERR_STREAM_PUSH_AFTER_EOF = _require$codes.ERR_STREAM_PUSH_AFTER_EOF
var ERR_METHOD_NOT_IMPLEMENTED = _require$codes.ERR_METHOD_NOT_IMPLEMENTED
var ERR_STREAM_UNSHIFT_AFTER_END_EVENT = _require$codes.ERR_STREAM_UNSHIFT_AFTER_END_EVENT
var StringDecoder
var createReadableStreamAsyncIterator
var from
var errorOrDestroy = destroyImpl.errorOrDestroy
var kProxyEvents = ['error', 'close', 'destroy', 'pause', 'resume']
Readable prototype destroy = destroyImpl.destroy
Readable prototype _undestroy = destroyImpl.undestroy
Readable prototype _destroy
Readable prototype push
Readable prototype unshift
Readable prototype isPaused
Readable prototype setEncoding
var MAX_HWM = 0x40000000
Readable prototype read
Readable prototype _read
Readable prototype pipe
Readable prototype unpipe
Readable prototype on
Readable prototype addListener = Readable.prototype.on
Readable prototype removeListener
Readable prototype removeAllListeners
Readable prototype resume
Readable prototype pause
Readable prototype wrap
Readable _fromList = fromList
Function Documentation
_isUint8Array()
function _isUint8Array (obj)
References obj, and OurUint8Array.
_uint8ArrayToBuffer()
function _uint8ArrayToBuffer (chunk)
References chunk().
addChunk()
function addChunk (stream, state, chunk, addToFront)
References chunk(), emitReadable(), maybeReadMore(), state(), and stream.
chunkInvalid()
function chunkInvalid (state, chunk)
References _isUint8Array(), chunk(), ERR_INVALID_ARG_TYPE, state(), and undefined.
computeNewHighWaterMark()
function computeNewHighWaterMark (n)
References MAX_HWM, and n.
emitReadable()
function emitReadable (stream)
References debug, emitReadable_(), process, state(), and stream.
emitReadable_()
function emitReadable_ (stream)
References debug, flow, state(), and stream.
endReadable()
function endReadable (stream)
References debug, endReadableNT(), process, state(), and stream.
endReadableNT()
function endReadableNT (state, stream)
References debug, state(), and stream.
flow()
function flow (stream)
References debug, state(), and stream.
fromList()
function fromList (n, state)
References n, and state().
howMuchToRead()
function howMuchToRead (n, state)
References computeNewHighWaterMark(), n, and state().
if() [1/2]
if (debugUtil &&debugUtil. debuglog)
References debug, and debugUtil.
if() [2/2]
if (typeof Symbol = == 'function')
References createReadableStreamAsyncIterator, Readable, require(), Symbol, and undefined.
indexOf()
function indexOf (xs, x)
References i, l, and xs.
maybeReadMore()
function maybeReadMore (stream, state)
References maybeReadMore_(), process, state(), and stream.
maybeReadMore_()
function maybeReadMore_ (stream, state)
References debug, state(), and stream.
nReadingNextTick()
function nReadingNextTick (self)
References debug.
onEofChunk()
function onEofChunk (stream, state)
References chunk(), debug, emitReadable(), emitReadable_(), state(), and stream.
pipeOnDrain()
function pipeOnDrain (src)
References debug, EElistenerCount, flow, and state().
prependListener()
function prependListener (emitter, event, fn)
References Array, event, and fn.
Readable()
function Readable (options)
References _destroy, _read, Duplex, Readable, readable, ReadableState, require(), and Stream.
readableAddChunk()
function readableAddChunk (stream, chunk, encoding, addToFront, skipChunkCheck)
References _uint8ArrayToBuffer(), addChunk(), chunk(), chunkInvalid(), debug, encoding, ERR_STREAM_PUSH_AFTER_EOF, ERR_STREAM_UNSHIFT_AFTER_END_EVENT, errorOrDestroy, maybeReadMore(), onEofChunk(), state(), and stream.
ReadableState()
function ReadableState (options, stream, isDuplex)
References buffer, BufferList, decoder, Duplex, encoding, getHighWaterMark, length, objectMode, require(), stream, StringDecoder, and sync.
require()
require ('inherits')
resume()
function resume (stream, state)
References process, resume_(), state(), and stream.
resume_()
function resume_ (stream, state)
References debug, flow, state(), and stream.
updateReadableListening()
function updateReadableListening (self)
References state().
Variable Documentation
_destroy
Readable prototype _destroy
Initial value:
= function (err, cb) {
  cb(err);
}
_fromList
Readable _fromList = fromList
_read
Readable prototype _read
Initial value:
= function (n) {
  errorOrDestroy(this, new ERR_METHOD_NOT_IMPLEMENTED('_read()'));
}
_require
var _require = require('./internal/streams/state')
_require$codes
var _require$codes = require('../errors').codes
_undestroy
Readable prototype _undestroy = destroyImpl.undestroy
addListener
Readable prototype addListener = Readable.prototype.on
Buffer
var Buffer = require('buffer').Buffer
BufferList
var BufferList = require('./internal/streams/buffer_list')
createReadableStreamAsyncIterator
var createReadableStreamAsyncIterator
debug
var debug
debugUtil
var debugUtil = require('util')
destroy
Readable prototype destroy = destroyImpl.destroy
destroyImpl
var destroyImpl = require('./internal/streams/destroy')
Duplex
var Duplex
EE
var EE = require('events').EventEmitter
EElistenerCount
var EElistenerCount
Initial value:
= function EElistenerCount(emitter, type) {
  return emitter.listeners(type).length;
}
else
else
Initial value:
{
  debug = function debug() {}
ERR_INVALID_ARG_TYPE
var ERR_INVALID_ARG_TYPE = _require$codes.ERR_INVALID_ARG_TYPE
ERR_METHOD_NOT_IMPLEMENTED
var ERR_METHOD_NOT_IMPLEMENTED = _require$codes.ERR_METHOD_NOT_IMPLEMENTED
ERR_STREAM_PUSH_AFTER_EOF
var ERR_STREAM_PUSH_AFTER_EOF = _require$codes.ERR_STREAM_PUSH_AFTER_EOF
ERR_STREAM_UNSHIFT_AFTER_END_EVENT
var ERR_STREAM_UNSHIFT_AFTER_END_EVENT = _require$codes.ERR_STREAM_UNSHIFT_AFTER_END_EVENT
errorOrDestroy
var errorOrDestroy = destroyImpl.errorOrDestroy
exports
module exports = Readable
from
var from
getHighWaterMark
var getHighWaterMark = _require.getHighWaterMark
isPaused
Readable prototype isPaused
Initial value:
= function () {
  return this._readableState.flowing === false;
}
kProxyEvents
var kProxyEvents = ['error', 'close', 'destroy', 'pause', 'resume']
MAX_HWM
var MAX_HWM = 0x40000000
on
Readable prototype on
Initial value:
= function (ev, fn) {
  var res = Stream.prototype.on.call(this, ev, fn);
  var state = this._readableState;
  if (ev === 'data') {
    
    
    state.readableListening = this.listenerCount('readable') > 0;
    
    if (state.flowing !== false) this.resume();
  } else if (ev === 'readable') {
    if (!state.endEmitted && !state.readableListening) {
      state.readableListening = state.needReadable = true;
      state.flowing = false;
      state.emittedReadable = false;
      debug('on readable', state.length, state.reading);
      if (state.length) {
        emitReadable(this);
      } else if (!state.reading) {
        process.nextTick(nReadingNextTick, this);
      }
    }
  }
  return res;
}
OurUint8Array
var OurUint8Array = (typeof global !== 'undefined' ? global : typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : {}).Uint8Array || function () {}
pause
Readable prototype pause
Initial value:
= function () {
  debug('call pause flowing=%j', this._readableState.flowing);
  if (this._readableState.flowing !== false) {
    debug('pause');
    this._readableState.flowing = false;
    this.emit('pause');
  }
  this._readableState.paused = true;
  return this;
}
pipe
Readable prototype pipe
push
Readable prototype push
Initial value:
= function (chunk, encoding) {
  var state = this._readableState;
  var skipChunkCheck;
  if (!state.objectMode) {
    if (typeof chunk === 'string') {
      encoding = encoding || state.defaultEncoding;
      if (encoding !== state.encoding) {
        chunk = Buffer.from(chunk, encoding);
        encoding = '';
      }
      skipChunkCheck = true;
    }
  } else {
    skipChunkCheck = true;
  }
  return readableAddChunk(this, chunk, encoding, false, skipChunkCheck);
}
read
Readable prototype read
ReadableState
Readable ReadableState = ReadableState
removeAllListeners
Readable prototype removeAllListeners
Initial value:
= function (ev) {
  var res = Stream.prototype.removeAllListeners.apply(this, arguments);
  if (ev === 'readable' || ev === undefined) {
    
    
    
    
    
    
    process.nextTick(updateReadableListening, this);
  }
  return res;
}
removeListener
Readable prototype removeListener
Initial value:
= function (ev, fn) {
  var res = Stream.prototype.removeListener.call(this, ev, fn);
  if (ev === 'readable') {
    
    
    
    
    
    
    process.nextTick(updateReadableListening, this);
  }
  return res;
}
resume
Readable prototype resume
Initial value:
= function () {
  var state = this._readableState;
  if (!state.flowing) {
    debug('resume');
    
    
    
    state.flowing = !state.readableListening;
    resume(this, state);
  }
  state.paused = false;
  return this;
}
setEncoding
Readable prototype setEncoding
Initial value:
= function (enc) {
  if (!StringDecoder) StringDecoder = require('string_decoder/').StringDecoder;
  var decoder = new StringDecoder(enc);
  this._readableState.decoder = decoder;
  
  this._readableState.encoding = this._readableState.decoder.encoding;
  
  var p = this._readableState.buffer.head;
  var content = '';
  while (p !== null) {
    content += decoder.write(p.data);
    p = p.next;
  }
  this._readableState.buffer.clear();
  if (content !== '') this._readableState.buffer.push(content);
  this._readableState.length = content.length;
  return this;
}
Stream
Stream = require('./internal/streams/stream')
strict
use strict
StringDecoder
var StringDecoder
unpipe
Readable prototype unpipe
unshift
Readable prototype unshift
Initial value:
= function (chunk) {
  return readableAddChunk(this, chunk, null, true, false);
}
wrap
Readable prototype wrap