backend/node_modules/@grpc/grpc-js/build/src/channelz.js File Reference
Classes
class ChannelzTraceStub
class ChannelzTrace
class ChannelzChildrenTracker
class ChannelzChildrenTrackerStub
class ChannelzCallTracker
class ChannelzCallTrackerStub
Functions
function channelRefToMessage (ref)
function subchannelRefToMessage (ref)
function serverRefToMessage (ref)
function socketRefToMessage (ref)
function unregisterChannelzRef (ref)
function parseIPv6Section (addressSection)
function parseIPv6Chunk (addressChunk)
function ipAddressStringToBuffer (ipAddress)
function connectivityStateToMessage (state)
function dateToProtoTimestamp (date)
function getChannelMessage (channelEntry)
function GetChannel (call, callback)
function GetTopChannels (call, callback)
function getServerMessage (serverEntry)
function GetServer (call, callback)
function GetServers (call, callback)
function GetSubchannel (call, callback)
function subchannelAddressToAddressMessage (subchannelAddress)
function GetSocket (call, callback)
function GetServerSockets (call, callback)
Variables
use strict
exports setup = exports.getChannelzServiceDefinition = exports.getChannelzHandlers = exports.unregisterChannelzRef = exports.registerChannelzSocket = exports.registerChannelzServer = exports.registerChannelzSubchannel = exports.registerChannelzChannel = exports.ChannelzCallTrackerStub = exports.ChannelzCallTracker = exports.ChannelzChildrenTrackerStub = exports.ChannelzChildrenTracker = exports.ChannelzTrace = exports.ChannelzTraceStub = void 0
const net_1 = require("net")
const ordered_map_1 = require("@js-sdsl/ordered-map")
const connectivity_state_1 = require("./connectivity-state")
const constants_1 = require("./constants")
const subchannel_address_1 = require("./subchannel-address")
const admin_1 = require("./admin")
const make_client_1 = require("./make-client")
const TARGET_RETAINED_TRACES = 32
const DEFAULT_MAX_RESULTS = 100
exports ChannelzTraceStub = ChannelzTraceStub
exports ChannelzTrace = ChannelzTrace
exports ChannelzChildrenTracker = ChannelzChildrenTracker
exports ChannelzChildrenTrackerStub = ChannelzChildrenTrackerStub
exports ChannelzCallTracker = ChannelzCallTracker
exports ChannelzCallTrackerStub = ChannelzCallTrackerStub
const entityMaps
const generateRegisterFn
exports registerChannelzChannel = generateRegisterFn("channel")
exports registerChannelzSubchannel = generateRegisterFn("subchannel")
exports registerChannelzServer = generateRegisterFn("server")
exports registerChannelzSocket = generateRegisterFn("socket")
exports unregisterChannelzRef = unregisterChannelzRef
exports getChannelzHandlers = getChannelzHandlers
let loadedChannelzDefinition = null
exports getChannelzServiceDefinition = getChannelzServiceDefinition
Function Documentation
channelRefToMessage()
function channelRefToMessage (ref)
References name.
connectivityStateToMessage()
function connectivityStateToMessage (state)
References connectivity_state_1, and state().
dateToProtoTimestamp()
function dateToProtoTimestamp (date)
GetChannel()
function GetChannel (call, callback)
References call, callback, constants_1, entityMaps, getChannelMessage(), parseInt(), and undefined.
getChannelMessage()
function getChannelMessage (channelEntry)
References channelRefToMessage(), connectivityStateToMessage(), data, dateToProtoTimestamp(), state(), subchannelRefToMessage(), and trace.
GetServer()
function GetServer (call, callback)
References call, callback, constants_1, entityMaps, getServerMessage(), parseInt(), server, and undefined.
getServerMessage()
function getServerMessage (serverEntry)
References data, dateToProtoTimestamp(), serverRefToMessage(), socketRefToMessage(), and trace.
GetServers()
function GetServers (call, callback)
References call, callback, DEFAULT_MAX_RESULTS, end, entityMaps, getServerMessage(), i, parseInt(), and server.
GetServerSockets()
function GetServerSockets (call, callback)
References call, callback, constants_1, DEFAULT_MAX_RESULTS, end, entityMaps, i, parseInt(), socketRefToMessage(), and undefined.
GetSocket()
function GetSocket (call, callback)
References _a, _b, _c, _d, call, callback, constants_1, data, dateToProtoTimestamp(), entityMaps, parseInt(), socketRefToMessage(), subchannelAddressToAddressMessage(), tls, undefined, and value.
GetSubchannel()
function GetSubchannel (call, callback)
References call, callback, connectivityStateToMessage(), constants_1, data, dateToProtoTimestamp(), entityMaps, parseInt(), socketRefToMessage(), state(), subchannelRefToMessage(), trace, and undefined.
GetTopChannels()
function GetTopChannels (call, callback)
References call, callback, DEFAULT_MAX_RESULTS, end, entityMaps, getChannelMessage(), i, and parseInt().
ipAddressStringToBuffer()
function ipAddressStringToBuffer (ipAddress)
Converts an IPv4 or IPv6 address from string representation to binary representation
Parameters
ipAddress an IP address in standard IPv4 or IPv6 text format
Returns
References net_1, and parseIPv6Chunk().
parseIPv6Chunk()
function parseIPv6Chunk (addressChunk)
Parse a chunk of an IPv6 address string to some number of bytes
Parameters
addressChunk Some number of segments of up to 4 hexadecimal characters each, joined by colons.
Returns
The list of bytes representing this address chunk
References parseIPv6Section(), and result.
parseIPv6Section()
function parseIPv6Section (addressSection)
Parse a single section of an IPv6 address as two bytes
Parameters
addressSection A hexadecimal string of length up to 4
Returns
The pair of bytes representing this address section
serverRefToMessage()
function serverRefToMessage (ref)
socketRefToMessage()
function socketRefToMessage (ref)
References name.
subchannelAddressToAddressMessage()
function subchannelAddressToAddressMessage (subchannelAddress)
References _a, filename, ipAddressStringToBuffer(), subchannel_address_1, and undefined.
subchannelRefToMessage()
function subchannelRefToMessage (ref)
References name.
unregisterChannelzRef()
function unregisterChannelzRef (ref)
References entityMaps.
Variable Documentation
admin_1
const admin_1 = require("./admin")
ChannelzCallTracker
exports ChannelzCallTracker = ChannelzCallTracker
ChannelzCallTrackerStub
exports ChannelzCallTrackerStub = ChannelzCallTrackerStub
ChannelzChildrenTracker
exports ChannelzChildrenTracker = ChannelzChildrenTracker
ChannelzChildrenTrackerStub
exports ChannelzChildrenTrackerStub = ChannelzChildrenTrackerStub
ChannelzTrace
exports ChannelzTrace = ChannelzTrace
ChannelzTraceStub
exports ChannelzTraceStub = ChannelzTraceStub
connectivity_state_1
const connectivity_state_1 = require("./connectivity-state")
constants_1
const constants_1 = require("./constants")
DEFAULT_MAX_RESULTS
const DEFAULT_MAX_RESULTS = 100
Default number of sockets/servers/channels/subchannels to return
entityMaps
const entityMaps
Initial value:
= {
    ["channel" ]: new ordered_map_1.OrderedMap(),
    ["subchannel" ]: new ordered_map_1.OrderedMap(),
    ["server" ]: new ordered_map_1.OrderedMap(),
    ["socket" ]: new ordered_map_1.OrderedMap(),
}
generateRegisterFn
const generateRegisterFn
Initial value:
= (kind) => {
    let nextId = 1;
    function getNextId() {
        return nextId++;
    }
    const entityMap = entityMaps[kind];
    return (name, getInfo, channelzEnabled) => {
        const id = getNextId();
        const ref = { id, name, kind };
        if (channelzEnabled) {
            entityMap.setElement(id, { ref, getInfo });
        }
        return ref;
    };
}
getChannelzHandlers
function getChannelzHandlers = getChannelzHandlers
getChannelzServiceDefinition
function getChannelzServiceDefinition = getChannelzServiceDefinition
loadedChannelzDefinition
let loadedChannelzDefinition = null
make_client_1
const make_client_1 = require("./make-client")
net_1
const net_1 = require("net")
ordered_map_1
const ordered_map_1 = require("@js-sdsl/ordered-map")
registerChannelzChannel
exports registerChannelzChannel = generateRegisterFn("channel")
registerChannelzServer
exports registerChannelzServer = generateRegisterFn("server")
registerChannelzSocket
exports registerChannelzSocket = generateRegisterFn("socket")
registerChannelzSubchannel
exports registerChannelzSubchannel = generateRegisterFn("subchannel")
setup
exports setup = exports.getChannelzServiceDefinition = exports.getChannelzHandlers = exports.unregisterChannelzRef = exports.registerChannelzSocket = exports.registerChannelzServer = exports.registerChannelzSubchannel = exports.registerChannelzChannel = exports.ChannelzCallTrackerStub = exports.ChannelzCallTracker = exports.ChannelzChildrenTrackerStub = exports.ChannelzChildrenTracker = exports.ChannelzTrace = exports.ChannelzTraceStub = void 0
Set up the DNS resolver class by registering it as the handler for the "dns:" prefix and as the default resolver.
strict
use strict
subchannel_address_1
const subchannel_address_1 = require("./subchannel-address")
TARGET_RETAINED_TRACES
const TARGET_RETAINED_TRACES = 32
The loose upper bound on the number of events that should be retained in a trace. This may be exceeded by up to a factor of 2. Arbitrarily chosen as a number that should be large enough to contain the recent relevant information, but small enough to not use excessive memory.
unregisterChannelzRef
exports unregisterChannelzRef = unregisterChannelzRef