backend/node_modules/fast-xml-parser/src/xmlparser/DocTypeReader.js File Reference
Functions
function readDocType (xmlData, i)
function readEntityExp (xmlData, i)
function isComment (xmlData, i)
function isEntity (xmlData, i)
function isElement (xmlData, i)
function isAttlist (xmlData, i)
function isNotation (xmlData, i)
function validateEntityName (name)
Variables
const util = require('../util')
module exports = readDocType
Function Documentation
isAttlist()
function isAttlist (xmlData, i)
References i.
isComment()
function isComment (xmlData, i)
References i.
isElement()
function isElement (xmlData, i)
References i.
isEntity()
function isEntity (xmlData, i)
References i.
isNotation()
function isNotation (xmlData, i)
References i.
readDocType()
function readDocType (xmlData, i)
References $, entities, exp, i, isAttlist(), isComment(), isElement(), isEntity(), isNotation(), of, readEntityExp(), and validateEntityName().
readEntityExp()
function readEntityExp (xmlData, i)
References i.
validateEntityName()
function validateEntityName (name)
References $, name, and util.
Variable Documentation
exports
module exports = readDocType
util
const util = require('../util')