backend/node_modules/fast-xml-parser/src/v5/XmlPartReader.js File Reference
Functions
function readStopNode (xmlDoc, tagName, i)
function readClosingTagName (source)
function readTagExp (parser)
function readPiExp (parser)
function buildTagExpObj (exp, parser)
Variables
use strict
Function Documentation
buildTagExpObj()
function buildTagExpObj (exp, parser)
References exp, i, and parser.
readClosingTagName()
function readClosingTagName (source)
Read closing tag name
Parameters
{Source} source
Returns
tag name
References end, of, source, and text.
readPiExp()
function readPiExp (parser)
References buildTagExpObj(), exp, i, and parser.
readStopNode()
function readStopNode (xmlDoc, tagName, i)
find paired tag for a stop node
Parameters
{string} xmlDoc
{string} tagName
{number} i : start index
References $, i, is, not, readTagExp(), and startIndex().
readTagExp()
function readTagExp (parser)
Read XML tag and build attributes map This function can be used to read normal tag, pi tag. This function can't be used to read comment, CDATA, DOCTYPE. Eg <tag attr = ' some"' attr= ">" bool>
Parameters
{string} xmlDoc
{number} startIndex starting index
Returns
tag expression includes tag name & attribute string
References buildTagExpObj(), exp, i, and parser.
Variable Documentation
strict
use strict