backend/node_modules/node-forge/lib/aesCipherSuites.js File Reference
Functions
function initConnectionState (state, c, sp)
function encrypt_aes_cbc_sha1 (record, s)
function encrypt_aes_cbc_sha1_padding (blockSize, input, decrypt)
function decrypt_aes_cbc_sha1_padding (blockSize, output, decrypt)
function decrypt_aes_cbc_sha1 (record, s)
function compareMacs (key, mac1, mac2)
Variables
var forge = require('./forge')
var tls = module.exports = forge.tls
tls CipherSuites ['TLS_RSA_WITH_AES_128_CBC_SHA']
Function Documentation
compareMacs()
function compareMacs (key, mac1, mac2)
Safely compare two MACs. This function will compare two MACs in a way that protects against timing attacks.
TODO: Expose elsewhere as a utility API.
See: https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/
Parameters
key the MAC key to use.
mac1 as a binary-encoded string of bytes.
mac2 as a binary-encoded string of bytes.
Returns
true if the MACs are the same, false if not.
References forge, and hmac.
decrypt_aes_cbc_sha1()
function decrypt_aes_cbc_sha1 (record, s)
Decrypts a TLSCipherText record into a TLSCompressed record using AES in CBC mode.
Parameters
record the TLSCipherText record to decrypt.
s the ConnectionState to use.
Returns
true on success, false on failure.
References cipher, compareMacs(), decrypt_aes_cbc_sha1_padding(), forge, s, and tls.
decrypt_aes_cbc_sha1_padding()
function decrypt_aes_cbc_sha1_padding (blockSize, output, decrypt)
Handles padding for aes_cbc_sha1 in decrypt mode.
Parameters
blockSize the block size.
output the output buffer.
decrypt true in decrypt mode, false in encrypt mode.
Returns
true on success, false on failure.
References decrypt, and i.
encrypt_aes_cbc_sha1()
function encrypt_aes_cbc_sha1 (record, s)
Encrypts the TLSCompressed record into a TLSCipherText record using AES in CBC mode.
Parameters
record the TLSCompressed record to encrypt.
s the ConnectionState to use.
Returns
true on success, false on failure.
References cipher, encrypt_aes_cbc_sha1_padding(), forge, s, and tls.
encrypt_aes_cbc_sha1_padding()
function encrypt_aes_cbc_sha1_padding (blockSize, input, decrypt)
Handles padding for aes_cbc_sha1 in encrypt mode.
Parameters
blockSize the block size.
input the input buffer.
decrypt true in decrypt mode, false in encrypt mode.
Returns
true on success, false on failure.
References decrypt.
initConnectionState()
function initConnectionState (state, c, sp)
References c, cipher, client, decrypt_aes_cbc_sha1(), encrypt_aes_cbc_sha1(), forge, init, state(), and tls.
Variable Documentation
CipherSuites
tls CipherSuites
Initial value:
= {
  id: [0x00, 0x2f],
  name: 'TLS_RSA_WITH_AES_128_CBC_SHA',
  initSecurityParameters: function(sp) {
    sp.bulk_cipher_algorithm = tls.BulkCipherAlgorithm.aes;
    sp.cipher_type = tls.CipherType.block;
    sp.enc_key_length = 16;
    sp.block_length = 16;
    sp.fixed_iv_length = 16;
    sp.record_iv_length = 16;
    sp.mac_algorithm = tls.MACAlgorithm.hmac_sha1;
    sp.mac_length = 20;
    sp.mac_key_length = 20;
  },
  initConnectionState: initConnectionState
}
Supported cipher suites.
forge
var forge = require('./forge')
A Javascript implementation of AES Cipher Suites for TLS.
Author
Dave Longley
Copyright (c) 2009-2015 Digital Bazaar, Inc.
tls
var tls = module.exports = forge.tls