backend/node_modules/agent-base/node_modules/debug/src/common.js File Reference
Functions
function setup (env)
Variables
module exports = setup
Function Documentation
setup()
function setup (env)
This is the common logic for both the Node.js and web browser implementations of debug(). The currently active debug mode names, and names to skip.
Map of special "%n" handling functions, for the debug "format" argument.
Valid key names are a single, lower or upper-case letter, i.e. "n" and "N".
Selects a color for a debug namespace
Parameters
{String} namespace The namespace string for the debug instance to be colored
Returns
{Number|String} An ANSI color code for the given namespace @api private
Create a debugger with the given namespace.
Parameters
{String} namespace
Returns
{Function} @api public
Enables a debug mode by namespaces. This can include modes separated by a colon and wildcards.
Parameters
{String} namespaces @api public
Disable debug output.
Returns
{String} namespaces @api public
Returns true if the given mode name is enabled, false otherwise.
Parameters
{String} name
Returns
{Boolean} @api public
Convert regexp to namespace
Parameters
{RegExp} regxep
Returns
{String} namespace @api private
Coerce val.
Parameters
{Mixed} val
Returns
{Mixed} @api private
XXX DO NOT USE. This is a temporary stub function. XXX It WILL be removed in the next major release.
References $, a, args, charCodeAt, coerce, createDebug(), debug, destroy, disable, enable, enabled, env, extend, format, g, hash(), i, index, log, match, ms, name, prevTime, require(), s, selectColor(), split(), v, and Z().
Variable Documentation
exports
module exports = setup