backend/node_modules/firebase-admin/lib/utils/api-request.js File Reference
Classes
class DefaultRequestResponse
class MultipartRequestResponse
class RequestResponseError
class RequestClient
class HttpClient
class Http2Client
class AsyncRequestCall
class AsyncHttpCall
class AsyncHttp2Call
class BaseRequestConfigImpl
class HttpRequestConfigImpl
class Http2RequestConfigImpl
class AuthorizedHttpClient
class AuthorizedHttp2Client
class ApiSettings
class ExponentialBackoffPoller
class Http2SessionHandler
Functions
function validateRetryConfig (retry)
function parseHttpResponse (response, config)
hasEntity ()
isEntityEnclosingRequest ()
Variables
use strict
exports Http2SessionHandler = exports.ExponentialBackoffPoller = exports.ApiSettings = exports.AuthorizedHttp2Client = exports.AuthorizedHttpClient = exports.parseHttpResponse = exports.Http2Client = exports.HttpClient = exports.RequestClient = exports.defaultRetryConfig = exports.RequestResponseError = void 0
const error_1 = require("./error")
const validator = require("./validator")
const http = require("http")
const https = require("https")
const http2 = require("http2")
const url = require("url")
const events_1 = require("events")
exports RequestResponseError = RequestResponseError
exports defaultRetryConfig = defaultRetryConfig
exports RequestClient = RequestClient
exports HttpClient = HttpClient
exports Http2Client = Http2Client
exports parseHttpResponse = parseHttpResponse
exports AuthorizedHttpClient = AuthorizedHttpClient
exports AuthorizedHttp2Client = AuthorizedHttp2Client
exports ApiSettings = ApiSettings
exports ExponentialBackoffPoller = ExponentialBackoffPoller
Function Documentation
hasEntity()
hasEntity ()
References BaseRequestConfigImpl::data().
isEntityEnclosingRequest()
isEntityEnclosingRequest ()
References BaseRequestConfigImpl::method().
parseHttpResponse()
function parseHttpResponse (response, config)
Parses a full HTTP or HTTP/2 response message containing both a header and a body.
Parameters
response - The HTTP or HTTP/2 response to be parsed.
config - The request configuration that resulted in the HTTP or HTTP/2 response.
Returns
An object containing the response's parsed status, headers and the body.
References config, data, error_1, headers, name, parseInt(), request, response, s, status, validator, and value.
validateRetryConfig()
function validateRetryConfig (retry)
Ensures that the given RetryConfig object is valid.
Parameters
retry - The configuration to be validated.
References error_1, retry, and validator.
Variable Documentation
ApiSettings
exports ApiSettings = ApiSettings
AuthorizedHttp2Client
exports AuthorizedHttp2Client = AuthorizedHttp2Client
AuthorizedHttpClient
exports AuthorizedHttpClient = AuthorizedHttpClient
defaultRetryConfig
function defaultRetryConfig () = defaultRetryConfig
Default retry configuration for HTTP and HTTP/2 requests. Retries up to 4 times on connection reset and timeout errors as well as 503 errors. Exposed as a function to ensure that every RequestClient gets its own RetryConfig instance.
error_1
const error_1 = require("./error")
events_1
const events_1 = require("events")
ExponentialBackoffPoller
exports ExponentialBackoffPoller = ExponentialBackoffPoller
http
const http = require("http")
http2
const http2 = require("http2")
Http2Client
exports Http2Client = Http2Client
Http2SessionHandler
exports Http2SessionHandler = exports.ExponentialBackoffPoller = exports.ApiSettings = exports.AuthorizedHttp2Client = exports.AuthorizedHttpClient = exports.parseHttpResponse = exports.Http2Client = exports.HttpClient = exports.RequestClient = exports.defaultRetryConfig = exports.RequestResponseError = void 0
HttpClient
exports HttpClient = HttpClient
https
const https = require("https")
parseHttpResponse
exports parseHttpResponse = parseHttpResponse
RequestClient
exports RequestClient = RequestClient
RequestResponseError
exports RequestResponseError = RequestResponseError
strict
use strict
firebase-admin v12.7.0
url
const url = require("url")
validator
const validator = require("./validator")