backend/node_modules/yargs/build/lib/utils/apply-extends.js File Reference
Functions
function export applyExtends (config, cwd, mergeExtends, _shim)
function checkForCircularExtends (cfgPath)
function getPathToDefaultConfig (cwd, pathToExtend)
function mergeDeep (config1, config2)
Variables
import { YError } from '../yerror.js'
let previouslyVisitedConfigs = []
let shim
Function Documentation
applyExtends()
function export applyExtends (config, cwd, mergeExtends, _shim)
References applyExtends(), checkForCircularExtends(), config, cwd, getPathToDefaultConfig(), JSON, mergeDeep(), previouslyVisitedConfigs, require(), and shim.
checkForCircularExtends()
function checkForCircularExtends (cfgPath)
References previouslyVisitedConfigs.
getPathToDefaultConfig()
function getPathToDefaultConfig (cwd, pathToExtend)
References cwd, and shim.
mergeDeep()
function mergeDeep (config1, config2)
References Array, isObject, mergeDeep(), obj, and of.
Variable Documentation
import
import { YError } from '../yerror.js'
previouslyVisitedConfigs
let previouslyVisitedConfigs = []
shim
let shim