backend/node_modules/yargs/build/lib/argsert.js File Reference
Functions
function export argsert (arg1, arg2, arg3)
function guessType (arg)
function argumentTypeError (observedType, allowedTypes, position)
Variables
import { YError } from './yerror.js'
const positionName = ['first', 'second', 'third', 'fourth', 'fifth', 'sixth']
Function Documentation
argsert()
function export argsert (arg1, arg2, arg3)
References $, args, argumentTypeError(), guessType(), length, max, parseCommand(), type, and undefined.
argumentTypeError()
function argumentTypeError (observedType, allowedTypes, position)
References $, and positionName.
guessType()
function guessType (arg)
References Array.
Variable Documentation
import
import { YError } from './yerror.js'
positionName
const positionName = ['first', 'second', 'third', 'fourth', 'fifth', 'sixth']