backend/node_modules/readable-stream/lib/internal/streams/async_iterator.js File Reference
Functions
function _defineProperty (obj, key, value)
function _toPropertyKey (arg)
function _toPrimitive (input, hint)
function createIterResult (value, done)
function readAndResolve (iter)
function onReadable (iter)
function wrapForNext (lastPromise, iter)
Variables
use strict
var _Object$setPrototypeO
var finished = require('./end-of-stream')
var kLastResolve = Symbol('lastResolve')
var kLastReject = Symbol('lastReject')
var kError = Symbol('error')
var kEnded = Symbol('ended')
var kLastPromise = Symbol('lastPromise')
var kHandlePromise = Symbol('handlePromise')
var kStream = Symbol('stream')
var AsyncIteratorPrototype = Object.getPrototypeOf(function () {})
var ReadableStreamAsyncIteratorPrototype
var createReadableStreamAsyncIterator
module exports = createReadableStreamAsyncIterator
Function Documentation
_defineProperty()
function _defineProperty (obj, key, value)
References _toPropertyKey(), obj, value, and writable.
_toPrimitive()
function _toPrimitive (input, hint)
References res, Symbol, and undefined.
_toPropertyKey()
function _toPropertyKey (arg)
References _toPrimitive().
createIterResult()
function createIterResult (value, done)
References done, and value.
onReadable()
function onReadable (iter)
References process, and readAndResolve().
readAndResolve()
function readAndResolve (iter)
References createIterResult(), data, kLastPromise, kLastReject, kLastResolve, kStream, and resolve.
wrapForNext()
function wrapForNext (lastPromise, iter)
References createIterResult(), kEnded, kHandlePromise, reject(), resolve, and undefined.
Variable Documentation
_Object$setPrototypeO
var _Object$setPrototypeO
AsyncIteratorPrototype
var AsyncIteratorPrototype = Object.getPrototypeOf(function () {})
createReadableStreamAsyncIterator
var createReadableStreamAsyncIterator
exports
module exports = createReadableStreamAsyncIterator
finished
var finished = require('./end-of-stream')
kEnded
var kEnded = Symbol('ended')
kError
var kError = Symbol('error')
kHandlePromise
var kHandlePromise = Symbol('handlePromise')
kLastPromise
var kLastPromise = Symbol('lastPromise')
kLastReject
var kLastReject = Symbol('lastReject')
kLastResolve
var kLastResolve = Symbol('lastResolve')
kStream
var kStream = Symbol('stream')
ReadableStreamAsyncIteratorPrototype
var ReadableStreamAsyncIteratorPrototype
strict
use strict