backend/node_modules/bignumber.js/bignumber.js File Reference
Functions
function clone (configObject)
function bitFloor (n)
function coeffToString (a)
function compare (x, y)
function intCheck (n, min, max, name)
function isOdd (n)
function toExponential (str, e)
function toFixedPoint (str, e, z)
if (typeof define=='function' &&define.amd)
else if (typeof module !='undefined' &&module.exports)
Variables
function globalObject
var BigNumber = clone()
var isNumeric = /^-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i
var mathceil = Math.ceil
var mathfloor = Math.floor
var bignumberError = '[BigNumber Error] '
var tooManyDigits = bignumberError + 'Number primitive has more than 15 significant digits: '
var BASE = 1e14
var LOG_BASE = 14
var MAX_SAFE_INTEGER = 0x1fffffffffffff
var POWS_TEN = [1, 10, 100, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9, 1e10, 1e11, 1e12, 1e13]
var SQRT_BASE = 1e7
var MAX = 1E9
else
this
Function Documentation
bitFloor()
function bitFloor (n)
References i, and n.
clone()
function clone (configObject)
References $, a, abs, args, b, BASE, base, BigNumber, bignumberError, bitFloor(), c, clone, coeffToString(), compare, constructor, crypto, d, div, e, exp, format, g, i, intCheck(), isNaN, isNumeric, isOdd, j, k, length, LOG_BASE, m, mathceil, mathfloor, MAX, MAX_SAFE_INTEGER, md, multiply, n, ne, obj, ONE, P, p, POWS_TEN, prefix, q, r, rem, round, s, sign, SQRT_BASE, str(), subtract, sum(), t, test, times(), toExponential(), toFixedPoint(), tooManyDigits, toString, v, w, and y.
coeffToString()
function coeffToString (a)
References a, i, j, LOG_BASE, r, and s.
compare()
function compare (x, y)
References a, b, i, j, k, l, and y.
if() [1/2]
if (typeof define = = 'function' && define.amd)
References BigNumber, and define.
if() [2/2]
else if (typeof module ! = 'undefined' && module.exports)
intCheck()
function intCheck (n, min, max, name)
References bignumberError, mathfloor, max, n, and name.
isOdd()
function isOdd (n)
References bitFloor(), k, LOG_BASE, and n.
toExponential()
function toExponential (str, e)
References e, and str().
toFixedPoint()
function toFixedPoint (str, e, z)
References e, and str().
Variable Documentation
BASE
var BASE = 1e14
BigNumber
BigNumber[ 'default'] = clone()
bignumberError
var bignumberError = '[BigNumber Error] '
else
else
Initial value:
{
    if (!globalObject) {
      globalObject = typeof self != 'undefined' && self ? self : window;
    }
    globalObject.BigNumber = BigNumber
globalObject
function globalObject
Initial value:
{
  'use strict'
isNumeric
var isNumeric = /^-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i
LOG_BASE
var LOG_BASE = 14
mathceil
var mathceil = Math.ceil
mathfloor
var mathfloor = Math.floor
MAX
var MAX = 1E9
MAX_SAFE_INTEGER
var MAX_SAFE_INTEGER = 0x1fffffffffffff
POWS_TEN
var POWS_TEN = [1, 10, 100, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9, 1e10, 1e11, 1e12, 1e13]
SQRT_BASE
var SQRT_BASE = 1e7
this
this
tooManyDigits
var tooManyDigits = bignumberError + 'Number primitive has more than 15 significant digits: '