backend/node_modules/concurrently/dist/bin/concurrently.js File Reference
Functions
const yargs_1 default ((0, helpers_1.hideBin)(process.argv)) .parserConfiguration(
usage (' $0[options]< command ... >') .help('h') .alias('h'
help version (version) .alias('version'
help v alias ('version', 'V') .env('CONCURRENTLY') .options(
group (['m', 'n', 'name-separator', 's', 'r', 'no-color', 'hide', 'g', 'timings', 'P', 'teardown'], 'General') .group(['p'
Variables
use strict
var __createBinding
var __setModuleDefault
var __importStar
var __importDefault
const lodash_1 = __importDefault(require("lodash"))
const yargs_1 = __importDefault(require("yargs"))
const helpers_1 = require("yargs/helpers")
const index_1 = require("../src/index")
const read_package_1 = require("./read-package")
const version = String((0, read_package_1.readPackage)().version)
const epilogue = For documentation and more examples
const visit
c
l
t
pad prefix
pad Prefix styling kill others on fail
pad Prefix styling kill others on kill signal
const names = (args.names || '').split(args.nameSeparator)
const additionalArguments = lodash_1.default.castArray(args['--'] ?? []).map(String)
const commands = args.passthroughArguments ? args._ : args._.concat(additionalArguments)
 value
Executes the chain sequence to resolve the unwrapped value.
@memberOf _
Since
0.1.0 @alias toJSON, valueOf
const defaults = __importStar(require("../src/defaults"))
Function Documentation
alias()
help v alias ('version', 'V')
References alias(), defaults, describe(), group(), hide, names, prefix, raw, success, timings, and type.
default()
const yargs_1 default ((0, helpers_1.hideBin)(process.argv))
group()
pad Prefix styling group ('General')
usage()
usage (' $0< command ... >'[options])
version()
help version (version)
Variable Documentation
__createBinding
var __createBinding
Initial value:
= (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}))
__importDefault
var __importDefault
Initial value:
= (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
}
__importStar
var __importStar
Initial value:
= (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
}
__setModuleDefault
var __setModuleDefault
Initial value:
= (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
})
additionalArguments
const additionalArguments = lodash_1.default.castArray(args['--'] ?? []).map(String)
c
c
commands
const commands = args.passthroughArguments ? args._ : args._.concat(additionalArguments)
defaults
lodash defaults = __importStar(require("../src/defaults"))
epilogue
const epilogue = For documentation and more examples
fail
pad Prefix styling kill others on fail
helpers_1
const helpers_1 = require("yargs/helpers")
index_1
const index_1 = require("../src/index")
l
l
lodash_1
const lodash_1 = __importDefault(require("lodash"))
names
const names = (args.names || '').split(args.nameSeparator)
prefix
pad prefix
read_package_1
const read_package_1 = require("./read-package")
signal
pad Prefix styling kill others on kill signal
strict
use strict
t
t
version
const version = String((0, read_package_1.readPackage)().version)
visit
const visit
yargs_1
const yargs_1 = __importDefault(require("yargs"))