backend/node_modules/jose/dist/browser/runtime/pbes2kw.js File Reference
Functions
function getCryptoKey (key, alg)
function async deriveKey (p2s, alg, p2c, key)
Variables
import random from random js
import { p2s as concatSalt } from '../lib/buffer_utils.js'
import crypto
export const encrypt
export const decrypt
Function Documentation
deriveKey()
function async deriveKey (p2s, alg, p2c, key)
References $, checkP2s(), crypto, getCryptoKey(), hash(), length, name, p2s, parseInt(), and Uint8Array.
getCryptoKey()
function getCryptoKey (key, alg)
References checkEncCryptoKey, crypto, isCryptoKey, and types.
Variable Documentation
crypto
import crypto
decrypt
export const decrypt
Initial value:
= async (alg, key, encryptedKey, p2c, p2s) => {
    const derived = await deriveKey(p2s, alg, p2c, key);
    return unwrap(alg.slice(-6), derived, encryptedKey);
}
encrypt
export const encrypt
Initial value:
= async (alg, key, cek, p2c = 2048, p2s = random(new Uint8Array(16))) => {
    const derived = await deriveKey(p2s, alg, p2c, key);
    const encryptedKey = await wrap(alg.slice(-6), derived, cek);
    return { encryptedKey, p2c, p2s: base64url(p2s) };
}
import
import { p2s as concatSalt } from '../lib/buffer_utils.js'
js
import invalidKeyInput from lib invalid_key_input js