backend/node_modules/jose/dist/browser/lib/decrypt_key_management.js File Reference
Functions
function async decryptKeyManagement (alg, key, encryptedKey, joseHeader, options)
Variables
import { unwrap as aesKw } from '../runtime/aeskw.js'
import *as ECDH from runtime ecdhes js
export default decryptKeyManagement
Function Documentation
decryptKeyManagement()
function async decryptKeyManagement (alg, key, encryptedKey, joseHeader, options)
References _a, _b, _c, _d, base64url, checkKeyType, ECDH, importJWK, invalid(), is, isObject, JOSENotSupported, JWEInvalid, missing(), of, or, p2s, parseInt(), and undefined.
Variable Documentation
decryptKeyManagement
export default decryptKeyManagement
import
import { unwrap as aesKw } from '../runtime/aeskw.js'
js
import isObject from is_object js