backend/node_modules/readable-stream/lib/internal/streams/buffer_list.js File Reference
Functions
function ownKeys (object, enumerableOnly)
function _objectSpread (target)
function _defineProperty (obj, key, value)
function _classCallCheck (instance, Constructor)
function _defineProperties (target, props)
function _createClass (Constructor, protoProps, staticProps)
function _toPropertyKey (arg)
function _toPrimitive (input, hint)
function copyBuffer (src, target, offset)
Variables
use strict
var _require = require('buffer')
var Buffer = _require.Buffer
var _require2 = require('util')
var inspect = _require2.inspect
var custom = inspect && inspect.custom || 'inspect'
module exports
Function Documentation
_classCallCheck()
function _classCallCheck (instance, Constructor)
References instance.
_createClass()
function _createClass (Constructor, protoProps, staticProps)
References _defineProperties(), and writable.
_defineProperties()
function _defineProperties (target, props)
References _toPropertyKey(), descriptor, and i.
_defineProperty()
function _defineProperty (obj, key, value)
References _toPropertyKey(), obj, value, and writable.
_objectSpread()
function _objectSpread (target)
References _defineProperty(), i, ownKeys, and source.
_toPrimitive()
function _toPrimitive (input, hint)
References res, Symbol, and undefined.
_toPropertyKey()
function _toPropertyKey (arg)
References _toPrimitive().
copyBuffer()
function copyBuffer (src, target, offset)
ownKeys()
function ownKeys (object, enumerableOnly)
References keys.
Variable Documentation
_require
var _require = require('buffer')
_require2
var _require2 = require('util')
Buffer
var Buffer = _require.Buffer
custom
var custom = inspect && inspect.custom || 'inspect'
exports
module exports
inspect
var inspect = _require2.inspect
strict
use strict