backend/node_modules/chalk/node_modules/supports-color/index.js File Reference
Functions
if (hasFlag('no-color')||hasFlag('no-colors')||hasFlag('color=false')||hasFlag('color=never'))
if ('FORCE_COLOR' in env)
function translateLevel (level)
function supportsColor (haveStream, streamIsTTY)
function getSupportLevel (stream)
Variables
use strict
const os = require('os')
const tty = require('tty')
const hasFlag = require('has-flag')
const {env} = process
let forceColor
module exports
Function Documentation
getSupportLevel()
function getSupportLevel (stream)
References stream, supportsColor, and translateLevel().
if() [1/2]
if ('FORCE_COLOR' in env)
References env, forceColor, and parseInt().
if() [2/2]
if (hasFlag('no-color')||hasFlag('no-colors')||hasFlag('color=false')||hasFlag('color=never'))
References forceColor.
supportsColor()
function supportsColor (haveStream, streamIsTTY)
References $, ansi, d, env, forceColor, hasFlag, i, min, parseInt(), process, sign, some, undefined, and version.
translateLevel()
function translateLevel (level)
Variable Documentation
const
const {env} = process
exports
module exports
Initial value:
= {
    supportsColor: getSupportLevel,
    stdout: translateLevel(supportsColor(true, tty.isatty(1))),
    stderr: translateLevel(supportsColor(true, tty.isatty(2)))
}
forceColor
let forceColor
hasFlag
const hasFlag = require('has-flag')
os
const os = require('os')
strict
use strict
tty
const tty = require('tty')