backend/node_modules/negotiator/lib/charset.js File Reference
Functions
function parseAcceptCharset (accept)
function parseCharset (str, i)
function getCharsetPriority (charset, accepted, index)
function specify (charset, spec, index)
function preferredCharsets (accept, provided)
function compareSpecs (a, b)
function getFullCharset (spec)
function isQuality (spec)
Variables
use strict
module exports = preferredCharsets
module exports preferredCharsets = preferredCharsets
var simpleCharsetRegExp = /^\s*([^\s;]+)\s*(?:;(.*))?$/
Function Documentation
compareSpecs()
function compareSpecs (a, b) [private]
Compare two specs.
References a, and b.
getCharsetPriority()
function getCharsetPriority (charset, accepted, index) [private]
Get the priority of a charset.
References charset, i, index, o, q, s, and specify().
getFullCharset()
function getFullCharset (spec) [private]
Get full charset string. Here is the caller graph for this function:
isQuality()
function isQuality (spec) [private]
Check if a spec has any quality. Here is the caller graph for this function:
parseAcceptCharset()
function parseAcceptCharset (accept) [private]
Parse the Accept-Charset header.
References accepts, charset, i, j, parseCharset(), and trim().
parseCharset()
function parseCharset (str, i) [private]
Parse a charset from the Accept-Charset header.
References charset, i, j, match, p, q, simpleCharsetRegExp, and str().
preferredCharsets()
function preferredCharsets (accept, provided)
Get the preferred charsets from an Accept-Charset header.
References accepts, compareSpecs(), getCharsetPriority(), getFullCharset(), index, isQuality(), parseAcceptCharset(), type, and undefined.
specify()
function specify (charset, spec, index) [private]
Get the specificity of the charset.
References charset, i, index, o, q, and s.
Variable Documentation
exports
module exports = preferredCharsets
Module exports.
preferredCharsets
module exports preferredCharsets = preferredCharsets
simpleCharsetRegExp
var simpleCharsetRegExp = /^\s*([^\s;]+)\s*(?:;(.*))?$/ [private]
Module variables.
strict
use strict
negotiator Copyright(c) 2012 Isaac Z. Schlueter Copyright(c) 2014 Federico Romero Copyright(c) 2014-2015 Douglas Christopher Wilson MIT Licensed