backend/node_modules/rxjs/dist/cjs/internal/observable/fromEvent.js File Reference
Functions
function fromEvent (target, eventName, options, resultSelector)
function toCommonHandlerRegistry (target, eventName)
function isNodeStyleEventEmitter (target)
function isJQueryStyleEventEmitter (target)
function isEventTarget (target)
Variables
use strict
var __read
exports fromEvent = void 0
var innerFrom_1 = require("../observable/innerFrom")
var Observable_1 = require("../Observable")
var mergeMap_1 = require("../operators/mergeMap")
var isArrayLike_1 = require("../util/isArrayLike")
var isFunction_1 = require("../util/isFunction")
var mapOneOrManyArgs_1 = require("../util/mapOneOrManyArgs")
var nodeEventEmitterMethods = ['addListener', 'removeListener']
var eventTargetMethods = ['addEventListener', 'removeEventListener']
var jqueryMethods = ['on', 'off']
Function Documentation
fromEvent()
function fromEvent (target, eventName, options, resultSelector)
References __read, _a, add, args, eventTargetMethods, fromEvent, innerFrom_1, isArrayLike_1, isEventTarget(), isFunction_1, isJQueryStyleEventEmitter(), isNodeStyleEventEmitter(), jqueryMethods, mapOneOrManyArgs_1, mergeMap_1, nodeEventEmitterMethods, Observable_1, toCommonHandlerRegistry(), and undefined.
isEventTarget()
function isEventTarget (target)
References isFunction_1.
isJQueryStyleEventEmitter()
function isJQueryStyleEventEmitter (target)
References isFunction_1.
isNodeStyleEventEmitter()
function isNodeStyleEventEmitter (target)
References isFunction_1.
toCommonHandlerRegistry()
function toCommonHandlerRegistry (target, eventName)
Variable Documentation
__read
var __read
Initial value:
= (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
}
eventTargetMethods
var eventTargetMethods = ['addEventListener', 'removeEventListener']
fromEvent
exports fromEvent = void 0
innerFrom_1
var innerFrom_1 = require("../observable/innerFrom")
isArrayLike_1
var isArrayLike_1 = require("../util/isArrayLike")
isFunction_1
var isFunction_1 = require("../util/isFunction")
jqueryMethods
var jqueryMethods = ['on', 'off']
mapOneOrManyArgs_1
var mapOneOrManyArgs_1 = require("../util/mapOneOrManyArgs")
mergeMap_1
var mergeMap_1 = require("../operators/mergeMap")
nodeEventEmitterMethods
var nodeEventEmitterMethods = ['addListener', 'removeListener']
Observable_1
var Observable_1 = require("../Observable")
strict
use strict