backend/node_modules/rxjs/dist/cjs/internal/ajax/ajax.js File Reference
Functions
function ajaxGet (url, headers)
function ajaxPost (url, body, headers)
function ajaxDelete (url, headers)
function ajaxPut (url, body, headers)
function ajaxPatch (url, body, headers)
function ajaxGetJSON (url, headers)
function fromAjax (init)
function extractContentTypeAndMaybeSerializeBody (body, headers)
function toStringCheck (obj, name)
function isArrayBuffer (body)
function isFile (body)
function isBlob (body)
function isArrayBufferView (body)
function isFormData (body)
function isURLSearchParams (body)
function isReadableStream (body)
Variables
use strict
var __assign
exports fromAjax = exports.ajax = void 0
var map_1 = require("../operators/map")
var Observable_1 = require("../Observable")
var AjaxResponse_1 = require("./AjaxResponse")
var errors_1 = require("./errors")
var mapResponse = map_1.map(function (x) { return x.response; })
exports ajax
var UPLOAD = 'upload'
var DOWNLOAD = 'download'
var LOADSTART = 'loadstart'
var PROGRESS = 'progress'
var LOAD = 'load'
var _toString = Object.prototype.toString
Function Documentation
ajaxDelete()
function ajaxDelete (url, headers)
References exports, headers, method, and url.
ajaxGet()
function ajaxGet (url, headers)
References exports, headers, method, and url.
ajaxGetJSON()
function ajaxGetJSON (url, headers)
References exports, and mapResponse.
ajaxPatch()
function ajaxPatch (url, body, headers)
References exports, headers, method, and url.
ajaxPost()
function ajaxPost (url, body, headers)
References exports, headers, method, and url.
ajaxPut()
function ajaxPut (url, body, headers)
References exports, headers, method, and url.
extractContentTypeAndMaybeSerializeBody()
function extractContentTypeAndMaybeSerializeBody (body, headers)
References _a, headers, isArrayBuffer, isArrayBufferView, isBlob(), isFile(), isFormData(), isReadableStream(), isURLSearchParams(), and JSON.
fromAjax()
function fromAjax (init)
References __assign, _a, _b, _c, _d, AjaxResponse_1, async, config, DOWNLOAD, e, error, errors_1, event, extractContentTypeAndMaybeSerializeBody(), false, headers, init, LOAD, LOADSTART, method, msg, Observable_1, PROGRESS, response, status, timeout, type, UPLOAD, url, value, and xhr.
isArrayBuffer()
function isArrayBuffer (body)
References toStringCheck().
isArrayBufferView()
function isArrayBufferView (body)
isBlob()
function isBlob (body)
References toStringCheck().
isFile()
function isFile (body)
References toStringCheck().
isFormData()
function isFormData (body)
References FormData().
isReadableStream()
function isReadableStream (body)
isURLSearchParams()
function isURLSearchParams (body)
toStringCheck()
function toStringCheck (obj, name)
References _toString, name, and obj.
Variable Documentation
__assign
var __assign
Initial value:
= (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
}
_toString
var _toString = Object.prototype.toString
ajax
exports ajax
Initial value:
= (function () {
    var create = function (urlOrConfig) {
        var config = typeof urlOrConfig === 'string'
            ? {
                url: urlOrConfig,
            }
            : urlOrConfig;
        return fromAjax(config);
    };
    create.get = ajaxGet;
    create.post = ajaxPost;
    create.delete = ajaxDelete;
    create.put = ajaxPut;
    create.patch = ajaxPatch;
    create.getJSON = ajaxGetJSON;
    return create;
})()
AjaxResponse_1
var AjaxResponse_1 = require("./AjaxResponse")
DOWNLOAD
var DOWNLOAD = 'download'
errors_1
var errors_1 = require("./errors")
fromAjax
exports fromAjax = exports.ajax = void 0
LOAD
var LOAD = 'load'
LOADSTART
var LOADSTART = 'loadstart'
map_1
var map_1 = require("../operators/map")
mapResponse
var mapResponse = map_1.map(function (x) { return x.response; })
Observable_1
var Observable_1 = require("../Observable")
PROGRESS
var PROGRESS = 'progress'
strict
use strict
UPLOAD
var UPLOAD = 'upload'