backend/node_modules/rxjs/dist/cjs/internal/operators/share.js File Reference
Functions
function share (options)
function handleReset (reset, on)
Variables
use strict
var __read
var __spreadArray
exports share = void 0
var innerFrom_1 = require("../observable/innerFrom")
var Subject_1 = require("../Subject")
var Subscriber_1 = require("../Subscriber")
var lift_1 = require("../util/lift")
Function Documentation
handleReset()
function handleReset (reset, on)
References __read, __spreadArray, args, innerFrom_1, next(), on, reset, and Subscriber_1.
share()
function share (options)
References _a, _b, _c, _d, error, handleReset(), innerFrom_1, lift_1, next(), refCount, reset, source, Subject_1, Subscriber_1, undefined, and value.
Variable Documentation
__read
var __read
Initial value:
= (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
}
__spreadArray
var __spreadArray
Initial value:
= (this && this.__spreadArray) || function (to, from) {
    for (var i = 0, il = from.length, j = to.length; i < il; i++, j++)
        to[j] = from[i];
    return to;
}
innerFrom_1
var innerFrom_1 = require("../observable/innerFrom")
lift_1
var lift_1 = require("../util/lift")
share
exports share = void 0
strict
use strict
Subject_1
var Subject_1 = require("../Subject")
Subscriber_1
var Subscriber_1 = require("../Subscriber")