BaseSubchannelWrapper Class Reference
Public Member Functions
constructor (child)
updateHealthListeners ()
getConnectivityState ()
addConnectivityStateListener (listener)
removeConnectivityStateListener (listener)
startConnecting ()
getAddress ()
throttleKeepalive (newKeepaliveTime)
ref ()
unref ()
getChannelzRef ()
isHealthy ()
addHealthStateWatcher (listener)
removeHealthStateWatcher (listener)
setHealthy (healthy)
getRealSubchannel ()
realSubchannelEquals (other)
Member Function Documentation
addConnectivityStateListener()
BaseSubchannelWrapper::addConnectivityStateListener (listener) [inline]
addHealthStateWatcher()
BaseSubchannelWrapper::addHealthStateWatcher (listener) [inline]
constructor()
BaseSubchannelWrapper::constructor (child) [inline]
References Set, and updateHealthListeners().
getAddress()
BaseSubchannelWrapper::getAddress () [inline]
getChannelzRef()
BaseSubchannelWrapper::getChannelzRef () [inline]
getConnectivityState()
BaseSubchannelWrapper::getConnectivityState () [inline]
getRealSubchannel()
BaseSubchannelWrapper::getRealSubchannel () [inline]
isHealthy()
BaseSubchannelWrapper::isHealthy () [inline]
realSubchannelEquals()
BaseSubchannelWrapper::realSubchannelEquals (other) [inline]
References getRealSubchannel().
ref()
BaseSubchannelWrapper::ref () [inline]
removeConnectivityStateListener()
BaseSubchannelWrapper::removeConnectivityStateListener (listener) [inline]
removeHealthStateWatcher()
BaseSubchannelWrapper::removeHealthStateWatcher (listener) [inline]
setHealthy()
BaseSubchannelWrapper::setHealthy (healthy) [inline]
References updateHealthListeners().
startConnecting()
BaseSubchannelWrapper::startConnecting () [inline]
throttleKeepalive()
BaseSubchannelWrapper::throttleKeepalive (newKeepaliveTime) [inline]
unref()
BaseSubchannelWrapper::unref () [inline]
updateHealthListeners()
BaseSubchannelWrapper::updateHealthListeners () [inline]
References isHealthy(), and of.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/subchannel-interface.js