GrpcClient Class Reference
Public Member Functions
constructor (options={})
loadProto (jsonObject)
loadProtoJSON (json, ignoreCache=false)
constructSettings (serviceName, clientConfig, configOverrides, headers)
async createStub (service, opts, customServicePath)
constructor (options={})
loadFromProto (filename, options, ignoreCache=false)
loadProto (protoPath, filename, ignoreCache=false)
loadProtoJSON (json, ignoreCache=false)
metadataBuilder (headers)
constructSettings (serviceName, clientConfig, configOverrides, headers)
async createStub (CreateStub, options, customServicePath)
async _detectClientCertificate (opts, universeDomain)
_mtlsServicePath (servicePath, customServicePath, hasCertificate)
Static Public Member Functions
static clearProtoCache ()
static getServiceMethods (service)
static createByteLengthFunction (message)
static protoCacheKey (filename, options)
static clearProtoCache ()
static defaultOptions ()
static _resolveFile (protoPath, filename)
static createByteLengthFunction (message)
Private Member Functions
async _getCredentials (opts)
Member Function Documentation
_detectClientCertificate()
async GrpcClient::_detectClientCertificate (opts, universeDomain) [inline]
Detect mTLS client certificate based on logic described in https://google.aip.dev/auth/4114.
Parameters
{object} [options] - The configuration object.
Returns
{Promise} Resolves array of strings representing cert and key.
References _a, cert, execFileAsync(), JSON, path_1, process, readFileAsync(), s, and undefined.
_getCredentials()
async GrpcClient::_getCredentials (opts) [inline], [private]
Creates a gRPC credentials. It asks the auth data if necessary.
Parameters
{Object} opts - options values for configuring credentials.
{Object=} opts.sslCreds - when specified, this is used instead of default channel credentials.
Returns
{Promise} The promise which will be resolved to the gRPC credential.
References auth, client, credentials, and grpc.
_mtlsServicePath()
GrpcClient::_mtlsServicePath (servicePath, customServicePath, hasCertificate) [inline]
Return service path, taking into account mTLS logic. See: https://google.aip.dev/auth/4114
Parameters
{string|undefined} servicePath - The path of the service.
{string|undefined} customServicePath - Did the user provide a custom service URL.
{boolean} hasCertificate - Was a certificate found.
Returns
{string} The DNS address for this service.
References _a, _b, and process.
_resolveFile()
static GrpcClient::_resolveFile (protoPath, filename) [inline], [static]
References COMMON_PROTO_FILES, filename, fs, googleProtoFilesDir, and path.
clearProtoCache() [1/2]
static GrpcClient::clearProtoCache () [inline], [static]
In rare cases users might need to deallocate all memory consumed by loaded protos. This method will delete the proto cache content.
clearProtoCache() [2/2]
static GrpcClient::clearProtoCache () [inline], [static]
In rare cases users might need to deallocate all memory consumed by loaded protos. This method will delete the proto cache content.
constructor() [1/2]
GrpcClient::constructor (options = {}) [inline]
gRPC-fallback version of GrpcClient Implements GrpcClient API for a browser using grpc-fallback protocol (sends serialized protobuf to HTTP/1 $rpc endpoint).
Parameters
{Object=} options.auth - An instance of OAuth2Client to use in browser, or an instance of GoogleAuth from google-auth-library to use in Node.js. Required for browser, optional for Node.js. @constructor
constructor() [2/2]
GrpcClient::constructor (options = {}) [inline]
A class which keeps the context of gRPC and auth for the gRPC.
Parameters
{Object=} options - The optional parameters. It will be directly passed to google-auth-library library, so parameters like keyFile or credentials will be valid.
{Object=} options.auth - An instance of google-auth-library. When specified, this auth instance will be used instead of creating a new one.
{Object=} options.grpc - When specified, this will be used for the 'grpc' module in this context. By default, it will load the grpc module in the standard way. @constructor
constructSettings() [1/2]
GrpcClient::constructSettings (serviceName, clientConfig, configOverrides, headers) [inline]
gRPC-fallback version of constructSettings A wrapper of constructSettings function under the gRPC context.
Most of parameters are common among constructSettings, please take a look.
Parameters
{string} serviceName - The fullly-qualified name of the service.
{Object} clientConfig - A dictionary of the client config.
{Object} configOverrides - A dictionary of overriding configs.
{Object} headers - A dictionary of additional HTTP header name to its value.
Returns
{Object} A mapping of method names to CallSettings.
References $, add, Array, call, CLIENT_VERSION_HEADER, exports, gax, grpc, headers, not, split(), status_1, undefined, and value.
constructSettings() [2/2]
GrpcClient::constructSettings (serviceName, clientConfig, configOverrides, headers) [inline]
A wrapper of constructSettings function under the gRPC context.
Most of parameters are common among constructSettings, please take a look.
Parameters
{string} serviceName - The fullly-qualified name of the service.
{Object} clientConfig - A dictionary of the client config.
{Object} configOverrides - A dictionary of overriding configs.
{Object} headers - A dictionary of additional HTTP header name to its value.
Returns
{Object} A mapping of method names to CallSettings.
References gax, and grpc.
createByteLengthFunction() [1/2]
static GrpcClient::createByteLengthFunction (message) [inline], [static]
Creates a 'bytelength' function for a given proto message class.
See BundleDescriptor about the meaning of the return value.
Parameters
{function} message - a constructor function that is generated by protobuf.js. Assumes 'encoder' field in the message.
Returns
{function(Object):number} - a function to compute the byte length for an object.
References gax, and message.
createByteLengthFunction() [2/2]
static GrpcClient::createByteLengthFunction (message) [inline], [static]
Creates a 'bytelength' function for a given proto message class.
See BundleDescriptor about the meaning of the return value.
Parameters
{function} message - a constructor function that is generated by protobuf.js. Assumes 'encoder' field in the message.
Returns
{function(Object):number} - a function to compute the byte length for an object.
References gax, and message.
createStub() [1/2]
async GrpcClient::createStub (CreateStub, options, customServicePath) [inline]
Creates a gRPC stub with current gRPC and auth.
Parameters
{function} CreateStub - The constructor function of the stub.
{Object} options - The optional arguments to customize gRPC connection. This options will be passed to the constructor of gRPC client too.
{string} options.servicePath - The name of the server of the service.
{number} options.port - The port of the service.
{grpcTypes.ClientCredentials=} options.sslCreds - The credentials to be used to set up gRPC connection.
{string} defaultServicePath - The default service path.
Returns
{Promise} A promise which resolves to a gRPC stub instance.
References $, _detectClientCertificate(), _getCredentials(), _mtlsServicePath(), auth, cert, credentials, grpc, match, not, universe, and value.
createStub() [2/2]
async GrpcClient::createStub (service, opts, customServicePath) [inline]
gRPC-fallback version of createStub Creates a gRPC-fallback stub with authentication headers built from supplied OAuth2Client instance
Parameters
{function} CreateStub - The constructor function of the stub.
{Object} service - A protobufjs Service object (as returned by lookupService)
{Object} opts - Connection options, as described below.
{string} opts.servicePath - The hostname of the API endpoint service.
{number} opts.port - The port of the service.
Returns
{Promise} A promise which resolves to a gRPC-fallback service stub, which is a protobuf.js service stub instance modified to match the gRPC stub API
References $, API, auth, credentials, d, decoder, encoder, fallbackRest, fallbackServiceStub_1, getServiceMethods(), match, methods, not, parseInt(), path, and universe.
defaultOptions()
static GrpcClient::defaultOptions () [inline], [static]
References defaults, and INCLUDE_DIRS.
getServiceMethods()
static GrpcClient::getServiceMethods (service) [inline], [static]
References methods, of, and util_1.
loadFromProto()
GrpcClient::loadFromProto (filename, options, ignoreCache = false) [inline]
Loads the gRPC service from the proto file(s) at the given path and with the given options. Caches the loaded protos so the subsequent loads don't do any disk reads.
Parameters
filename The path to the proto file(s).
options Options for loading the proto file.
ignoreCache Defaults to false. Set it to true if the caching logic incorrectly decides that the options object is the same, or if you want to re-read the protos from disk for any other reason.
References filename, grpc, grpcProtoLoader, protoCacheKey(), and undefined.
loadProto() [1/2]
GrpcClient::loadProto (jsonObject) [inline]
gRPC-fallback version of loadProto Loads the protobuf root object from a JSON object created from a proto file
Parameters
{Object} jsonObject - A JSON version of a protofile created usin protobuf.js
Returns
{Object} Root namespace of proto JSON
References protobuf.
loadProto() [2/2]
GrpcClient::loadProto (protoPath, filename, ignoreCache = false) [inline]
Load gRPC proto service from a filename looking in googleapis common protos when necessary. Caches the loaded protos so the subsequent loads don't do any disk reads.
Parameters
{String} protoPath - The directory to search for the protofile.
{String|String[]} filename - The filename(s) of the proto(s) to be loaded. If omitted, protoPath will be treated as a file path to load.
ignoreCache Defaults to false. Set it to true if the caching logic incorrectly decides that the options object is the same, or if you want to re-read the protos from disk for any other reason.
Returns
{Object<string, *>} The gRPC loaded result (the toplevel namespace object).
References Array, defaultOptions(), filename, loadFromProto(), and path.
loadProtoJSON() [1/2]
GrpcClient::loadProtoJSON (json, ignoreCache = false) [inline]
References hash(), JSON, objectHash, protobuf, and root.
loadProtoJSON() [2/2]
GrpcClient::loadProtoJSON (json, ignoreCache = false) [inline]
References defaultOptions(), grpc, grpcProtoLoader, hash(), JSON, and objectHash.
metadataBuilder()
GrpcClient::metadataBuilder (headers) [inline]
References $, Array, grpc, headers, Metadata, v, and value.
protoCacheKey()
static GrpcClient::protoCacheKey (filename, options) [inline], [static]
Key for proto cache map. We are doing our best to make sure we respect the options, so if the same proto file is loaded with different set of options, the cache won't be used. Since some of the options are Functions (e.g. enums: String - see below in loadProto()), they will be omitted from the cache key. If the cache breaks anything for you, use the ignoreCache parameter of loadProto() to disable it.
References Array, filename, JSON, and undefined.
The documentation for this class was generated from the following files:
backend/node_modules/google-gax/build/src/fallback.js
backend/node_modules/google-gax/build/src/grpc.js