CRC32C Class Reference
Public Member Functions
constructor (initialValue=0)
update (data)
validate (input)
toBuffer ()
toJSON ()
toString ()
valueOf ()
constructor (initialValue=0)
update (data)
validate (input)
toBuffer ()
toJSON ()
toString ()
valueOf ()
Static Public Member Functions
static fromBuffer (value)
static async fromFile (file)
static fromString (value)
static fromNumber (value)
static from (value)
static fromBuffer (value)
static async fromFile (file)
static fromString (value)
static fromNumber (value)
static from (value)
Member Function Documentation
constructor() [1/2]
CRC32C::constructor (initialValue = 0) [inline]
Constructs a new CRC32C object.
Reconstruction is recommended via the CRC32C.from static method.
Parameters
initialValue An initial CRC32C value - a signed 32-bit integer.
Current CRC32C value
References __classPrivateFieldSet, and _CRC32C_crc32c.
constructor() [2/2]
CRC32C::constructor (initialValue = 0) [inline]
Constructs a new CRC32C object.
Reconstruction is recommended via the CRC32C.from static method.
Parameters
initialValue An initial CRC32C value - a signed 32-bit integer.
Current CRC32C value
References __classPrivateFieldSet, and _CRC32C_crc32c.
from() [1/2]
static CRC32C::from (value) [inline], [static]
Generates a CRC32C from a variety of compatable types. Note: strings are treated as input, not as file paths to read from.
Parameters
value A number, 4-byte ArrayBufferView/Buffer/TypedArray, or 4-byte base64-encoded data (string)
References fromBuffer(), fromNumber, fromString, and value.
from() [2/2]
static CRC32C::from (value) [inline], [static]
Generates a CRC32C from a variety of compatable types. Note: strings are treated as input, not as file paths to read from.
Parameters
value A number, 4-byte ArrayBufferView/Buffer/TypedArray, or 4-byte base64-encoded data (string)
References fromBuffer(), fromNumber, fromString, and value.
fromBuffer() [1/2]
static CRC32C::fromBuffer (value) [inline], [static]
Generates a CRC32C from a compatible buffer format.
Parameters
value 4-byte ArrayBufferView/Buffer/TypedArray
References buffer, CRC32C, CRC32C_EXCEPTION_MESSAGES, and value.
fromBuffer() [2/2]
static CRC32C::fromBuffer (value) [inline], [static]
Generates a CRC32C from a compatible buffer format.
Parameters
value 4-byte ArrayBufferView/Buffer/TypedArray
References buffer, CRC32C, CRC32C_EXCEPTION_MESSAGES, and value.
fromFile() [1/2]
static async CRC32C::fromFile (file) [inline], [static]
References CRC32C, d, file, fs_1, Promise, reject(), and resolve.
fromFile() [2/2]
static async CRC32C::fromFile (file) [inline], [static]
References CRC32C, d, file, Promise, reject(), and resolve.
fromNumber() [1/2]
static CRC32C::fromNumber (value) [inline], [static]
Generates a CRC32C from a safe, unsigned 32-bit integer.
Parameters
value an unsigned 32-bit integer
References CRC32C, CRC32C_EXCEPTION_MESSAGES, and value.
fromNumber() [2/2]
static CRC32C::fromNumber (value) [inline], [static]
Generates a CRC32C from a safe, unsigned 32-bit integer.
Parameters
value an unsigned 32-bit integer
References CRC32C, CRC32C_EXCEPTION_MESSAGES, and value.
fromString() [1/2]
static CRC32C::fromString (value) [inline], [static]
Generates a CRC32C from 4-byte base64-encoded data (string).
Parameters
value 4-byte base64-encoded data (string)
References buffer, CRC32C_EXCEPTION_MESSAGES, fromBuffer(), and value.
fromString() [2/2]
static CRC32C::fromString (value) [inline], [static]
Generates a CRC32C from 4-byte base64-encoded data (string).
Parameters
value 4-byte base64-encoded data (string)
References buffer, CRC32C_EXCEPTION_MESSAGES, fromBuffer(), and value.
toBuffer() [1/2]
CRC32C::toBuffer () [inline]
Returns a Buffer representation of the CRC32C value
References __classPrivateFieldGet, _CRC32C_crc32c, and buffer.
toBuffer() [2/2]
CRC32C::toBuffer () [inline]
Returns a Buffer representation of the CRC32C value
References __classPrivateFieldGet, _CRC32C_crc32c, and buffer.
toJSON() [1/2]
CRC32C::toJSON () [inline]
Returns a JSON-compatible, base64-encoded representation of the CRC32C value.
See JSON#stringify
References toString().
toJSON() [2/2]
CRC32C::toJSON () [inline]
Returns a JSON-compatible, base64-encoded representation of the CRC32C value.
See JSON#stringify
References toString().
toString() [1/2]
CRC32C::toString () [inline]
Returns a base64-encoded representation of the CRC32C value.
See Object#toString
References toBuffer().
toString() [2/2]
CRC32C::toString () [inline]
Returns a base64-encoded representation of the CRC32C value.
See Object#toString
References toBuffer().
update() [1/2]
CRC32C::update (data) [inline]
Calculates a CRC32C from a provided buffer.
Implementation inspired from:
github.com/google/crc32c
github.com/googleapis/python-crc32c
github.com/googleapis/java-storage
Parameters
data The Buffer to generate the CRC32C from
References __classPrivateFieldGet, __classPrivateFieldSet, _CRC32C_crc32c, d, data, and of.
update() [2/2]
CRC32C::update (data) [inline]
Calculates a CRC32C from a provided buffer.
Implementation inspired from:
github.com/google/crc32c
github.com/googleapis/python-crc32c
github.com/googleapis/java-storage
Parameters
data The Buffer to generate the CRC32C from
References __classPrivateFieldGet, __classPrivateFieldSet, _CRC32C_crc32c, d, data, and of.
validate() [1/2]
CRC32C::validate (input) [inline]
Validates a provided input to the current CRC32C value.
Parameters
input A Buffer, CRC32C-compatible object, base64-encoded data (string), or signed 32-bit integer
References __classPrivateFieldGet, _CRC32C_crc32c, toBuffer(), and toString().
validate() [2/2]
CRC32C::validate (input) [inline]
Validates a provided input to the current CRC32C value.
Parameters
input A Buffer, CRC32C-compatible object, base64-encoded data (string), or signed 32-bit integer
References __classPrivateFieldGet, _CRC32C_crc32c, toBuffer(), and toString().
valueOf() [1/2]
CRC32C::valueOf () [inline]
Returns the number representation of the CRC32C value as a signed 32-bit integer
See Object#valueOf
References __classPrivateFieldGet.
valueOf() [2/2]
CRC32C::valueOf () [inline]
Returns the number representation of the CRC32C value as a signed 32-bit integer
See Object#valueOf
References __classPrivateFieldGet.
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/crc32c.js
backend/node_modules/@google-cloud/storage/build/esm/src/crc32c.js