SyncTree Class Reference
Public Member Functions
constructor (listenProvider_)
constructor (listenProvider_)
constructor (listenProvider_)
Detailed Description
SyncTree is the central class for managing event callback registration, data caching, views (query processing), and event generation. There are typically two SyncTree instances for each Repo, one for the normal Firebase data, and one for the .info data.
It has a number of responsibilities, including:
Tracking all user event callbacks (registered via addEventRegistration() and removeEventRegistration()).
Applying and caching data changes for user set(), transaction(), and update() calls (applyUserOverwrite(), applyUserMerge()).
Applying and caching data changes for server data changes (applyServerOverwrite(), applyServerMerge()).
Generating user-facing events for server and user changes (all of the apply* methods return the set of events that need to be raised as a result).
Maintaining the appropriate set of server listens to ensure we are always subscribed to the correct set of paths and queries to satisfy the current set of user event callbacks (listens are started/stopped using the provided listenProvider).
NOTE: Although SyncTree tracks event callbacks and calculates events to raise, the actual events are returned to the caller rather than raised synchronously.
Member Function Documentation
constructor() [1/3]
SyncTree::constructor (listenProvider_) [inline]
Parameters
listenProvider_ - Used by SyncTree to start / stop listening to server data.
Tree of SyncPoints. There's a SyncPoint at any location that has 1 or more views.
A tree of all pending user writes (user-initiated set()'s, transaction()'s, update()'s, etc.).
References Map, and newWriteTree().
constructor() [2/3]
SyncTree::constructor (listenProvider_) [inline]
Parameters
listenProvider_ - Used by SyncTree to start / stop listening to server data.
Tree of SyncPoints. There's a SyncPoint at any location that has 1 or more views.
A tree of all pending user writes (user-initiated set()'s, transaction()'s, update()'s, etc.).
References Map, and newWriteTree().
constructor() [3/3]
SyncTree::constructor (listenProvider_) [inline]
Parameters
listenProvider_ - Used by SyncTree to start / stop listening to server data.
Tree of SyncPoints. There's a SyncPoint at any location that has 1 or more views.
A tree of all pending user writes (user-initiated set()'s, transaction()'s, update()'s, etc.).
References Map, and newWriteTree().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js