ServiceAccountCredential Class Reference
Public Member Functions
constructor (serviceAccountPathOrObject, httpAgent, implicit=false)
getAccessToken ()
createAuthJwt_ ()
Detailed Description
Implementation of Credential that uses a service account.
Member Function Documentation
constructor()
ServiceAccountCredential::constructor (serviceAccountPathOrObject, httpAgent, implicit = false) [inline]
Creates a new ServiceAccountCredential from the given parameters.
Parameters
serviceAccountPathOrObject - Service account json object or path to a service account json file.
httpAgent - Optional http.Agent to use when calling the remote token server.
implicit - An optinal boolean indicating whether this credential was implicitly discovered from the environment, as opposed to being explicitly specified by the developer.
@constructor
References api_request_1, and ServiceAccount::fromPath().
createAuthJwt_()
ServiceAccountCredential::createAuthJwt_ () [inline]
References GOOGLE_TOKEN_AUDIENCE, jwt, JWT_ALGORITHM, ONE_HOUR_IN_SECONDS, and require().
getAccessToken()
ServiceAccountCredential::getAccessToken () [inline]
References createAuthJwt_(), data, headers, https, method, request, requestAccessToken(), token, and url.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/app/credential-internal.js