JWT Class Reference
Public Member Functions
constructor (optionsOrEmail, keyFile, key, scopes, subject, keyId)
createScoped (scopes)
async getRequestMetadataAsync (url)
async fetchIdToken (targetAudience)
hasUserScopes ()
hasAnyScopes ()
authorize (callback)
async authorizeAsync ()
createGToken ()
fromJSON (json)
fromStream (inputStream, callback)
fromStreamAsync (inputStream)
fromAPIKey (apiKey)
async getCredentials ()
Private Member Functions
async refreshTokenNoCache (refreshToken)
Member Function Documentation
authorize()
JWT::authorize (callback) [inline]
References authorizeAsync(), callback, and r.
authorizeAsync()
async JWT::authorizeAsync () [inline]
References credentials, refreshToken, and result.
constructor()
JWT::constructor (optionsOrEmail, keyFile, key, scopes, subject, keyId) [inline]
References credentials.
createGToken()
JWT::createGToken () [inline]
Create a gToken if it doesn't already exist.
References gtoken_1, and sub.
createScoped()
JWT::createScoped (scopes) [inline]
Creates a copy of the credential with the specified scopes.
Parameters
scopes List of requested scopes or a single scope.
Returns
The cloned instance.
References JWT, and jwt.
fetchIdToken()
async JWT::fetchIdToken (targetAudience) [inline]
Fetches an ID token.
Parameters
targetAudience the audience for the fetched ID token.
References gtoken_1, and sub.
fromAPIKey()
JWT::fromAPIKey (apiKey) [inline]
Creates a JWT credentials instance using an API Key for authentication.
Parameters
apiKey The API Key in string form.
fromJSON()
JWT::fromJSON (json) [inline]
Create a JWT credentials instance using the given input options.
Parameters
json The input object.
fromStream()
JWT::fromStream (inputStream, callback) [inline]
References callback, and fromStreamAsync().
fromStreamAsync()
JWT::fromStreamAsync (inputStream) [inline]
References chunk(), data, e, fromJSON, JSON, Promise, reject(), resolve, and s.
getCredentials()
async JWT::getCredentials () [inline]
Using the key or keyFile on the JWT client, obtain an object that contains the key and the client email.
References createGToken().
getRequestMetadataAsync()
async JWT::getRequestMetadataAsync (url) [inline]
Obtains the metadata to be sent with the request.
Parameters
url the URI being authorized.
References $, authclient_1, credential, hasAnyScopes(), hasUserScopes(), headers, https, is, jwtaccess_1, not, refreshToken, tokens, undefined, and url.
hasAnyScopes()
JWT::hasAnyScopes () [inline]
Are there any default or user scopes defined. Here is the caller graph for this function:
hasUserScopes()
JWT::hasUserScopes () [inline]
Determine if there are currently scopes available. Here is the caller graph for this function:
refreshTokenNoCache()
async JWT::refreshTokenNoCache (refreshToken) [inline], [private]
Refreshes the access token.
Parameters
refreshToken ignored
References createGToken(), emit, res, token, and tokens.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/jwtclient.js