ValueIndex Class Reference
Public Member Functions
compare (a, b)
isDefinedOn (node)
indexedValueChanged (oldNode, newNode)
minPost ()
maxPost ()
makePost (indexValue, name)
toString ()
compare (a, b)
isDefinedOn (node)
indexedValueChanged (oldNode, newNode)
minPost ()
maxPost ()
makePost (indexValue, name)
toString ()
compare (a, b)
isDefinedOn (node)
indexedValueChanged (oldNode, newNode)
minPost ()
maxPost ()
makePost (indexValue, name)
toString ()
getCompare ()
getCompare ()
getCompare ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Member Function Documentation
compare() [1/3]
ValueIndex::compare (a, b) [inline]
References a, b, and nameCompare.
compare() [2/3]
ValueIndex::compare (a, b) [inline]
References a, b, and nameCompare.
compare() [3/3]
ValueIndex::compare (a, b) [inline]
References a, b, and nameCompare.
getCompare() [1/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
getCompare() [2/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
getCompare() [3/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
indexedValueChanged() [1/3]
ValueIndex::indexedValueChanged (oldNode, newNode) [inline]
indexedValueChanged() [2/3]
ValueIndex::indexedValueChanged (oldNode, newNode) [inline]
indexedValueChanged() [3/3]
ValueIndex::indexedValueChanged (oldNode, newNode) [inline]
isDefinedOn() [1/3]
ValueIndex::isDefinedOn (node) [inline]
isDefinedOn() [2/3]
ValueIndex::isDefinedOn (node) [inline]
isDefinedOn() [3/3]
ValueIndex::isDefinedOn (node) [inline]
makePost() [1/3]
ValueIndex::makePost (indexValue, name) [inline]
References name, and nodeFromJSON().
makePost() [2/3]
ValueIndex::makePost (indexValue, name) [inline]
References name, and nodeFromJSON().
makePost() [3/3]
ValueIndex::makePost (indexValue, name) [inline]
References name, and nodeFromJSON().
maxPost() [1/3]
ValueIndex::maxPost () [inline]
maxPost() [2/3]
ValueIndex::maxPost () [inline]
maxPost() [3/3]
ValueIndex::maxPost () [inline]
minPost() [1/3]
ValueIndex::minPost () [inline]
minPost() [2/3]
ValueIndex::minPost () [inline]
minPost() [3/3]
ValueIndex::minPost () [inline]
toString() [1/3]
ValueIndex::toString () [inline]
Returns
String representation for inclusion in a query spec
toString() [2/3]
ValueIndex::toString () [inline]
Returns
String representation for inclusion in a query spec
toString() [3/3]
ValueIndex::toString () [inline]
Returns
String representation for inclusion in a query spec
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js