PageDescriptor Class Reference
Public Member Functions
constructor (requestPageTokenField, responsePageTokenField, resourceField)
createStream (apiCall, request, options)
asyncIterate (apiCall, request, options)
createIterator (apiCall, request, options)
getApiCaller (settings)
Detailed Description
A descriptor for methods that support pagination.
Member Function Documentation
asyncIterate()
PageDescriptor::asyncIterate (apiCall, request, options) [inline]
Create an async iterable which can be recursively called for data on-demand.
References createIterator(), and request.
constructor()
PageDescriptor::constructor (requestPageTokenField, responsePageTokenField, resourceField) [inline]
createIterator()
PageDescriptor::createIterator (apiCall, request, options) [inline]
References Array, async, attempts, done, maxAttemptsEmptyResponse, next(), of, Promise, request, result, Symbol, undefined, and value.
createStream()
PageDescriptor::createStream (apiCall, request, options) [inline]
Creates a new object Stream which emits the resource on 'data' event.
References callback, i, next(), objectMode, request, setImmediate, stream, and stream_1.
getApiCaller()
PageDescriptor::getApiCaller (settings) [inline]
References normalApiCaller_1, and pagedApiCaller_1.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/paginationCalls/pageDescriptor.js