FunctionsApiClient Class Reference
Public Member Functions
constructor (app)
async delete (id, functionName, extensionId)
async enqueue (data, functionName, extensionId, opts)
getUrl (resourceName, urlFormat)
getProjectId ()
getServiceAccount ()
validateTaskOptions (data, resources, opts)
async updateTaskPayload (task, resources, extensionId)
toFirebaseError (err)
Detailed Description
Class that facilitates sending requests to the Firebase Functions backend API.
Member Function Documentation
constructor()
FunctionsApiClient::constructor (app) [inline]
References api_request_1, app, FirebaseFunctionsError, and validator.
delete()
async FunctionsApiClient::delete (id, functionName, extensionId) [inline]
Deletes a task from a queue.
Parameters
id - The ID of the task to delete.
functionName - The function name of the queue.
extensionId - Optional canonical ID of the extension.
References $, api_request_1, CLOUD_TASKS_API_URL_FORMAT, DEFAULT_LOCATION, ext, FIREBASE_FUNCTIONS_CONFIG_HEADERS, FirebaseFunctionsError, getProjectId(), getUrl(), headers, method, request, tasksEmulatorUrl(), toFirebaseError(), url, utils, and validator.
enqueue()
async FunctionsApiClient::enqueue (data, functionName, extensionId, opts) [inline]
Creates a task and adds it to a queue.
Parameters
data - The data payload of the task.
functionName - The functionName of the queue.
extensionId - Optional canonical ID of the extension.
opts - Optional options when enqueuing a new task.
References $, api_request_1, CLOUD_TASKS_API_URL_FORMAT, data, DEFAULT_LOCATION, ext, FIREBASE_FUNCTIONS_CONFIG_HEADERS, FirebaseFunctionsError, getProjectId(), getUrl(), headers, method, request, tasksEmulatorUrl(), toFirebaseError(), updateTaskPayload(), url, utils, validateTaskOptions(), and validator.
getProjectId()
FunctionsApiClient::getProjectId () [inline]
References app, FirebaseFunctionsError, Promise, utils, and validator.
getServiceAccount()
FunctionsApiClient::getServiceAccount () [inline]
References app, FirebaseFunctionsError, Promise, utils, and validator.
getUrl()
FunctionsApiClient::getUrl (resourceName, urlFormat) [inline]
References DEFAULT_LOCATION, getProjectId(), Promise, then, utils, and validator.
toFirebaseError()
FunctionsApiClient::toFirebaseError (err) [inline]
References $, and, error, error_1, exports, FirebaseFunctionsError, message, response, server, and status.
updateTaskPayload()
async FunctionsApiClient::updateTaskPayload (task, resources, extensionId) [inline]
References $, app, credential_internal_1, e, exports, getServiceAccount(), getUrl(), process, and validator.
validateTaskOptions()
FunctionsApiClient::validateTaskOptions (data, resources, opts) [inline]
References $, CLOUD_TASKS_API_RESOURCE_PATH, FirebaseFunctionsError, headers, JSON, s, url, utils, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/functions/functions-api-client-internal.js