SugaredTracer Class Reference
Public Member Functions
constructor (tracer)
withActiveSpan (name, arg2, arg3, arg4)
withSpan (name, arg2, arg3, arg4)
constructor (tracer)
withActiveSpan (name, arg2, arg3, arg4)
withSpan (name, arg2, arg3, arg4)
Member Function Documentation
constructor() [1/2]
SugaredTracer::constructor (tracer) [inline]
constructor() [2/2]
SugaredTracer::constructor (tracer) [inline]
withActiveSpan() [1/2]
SugaredTracer::withActiveSpan (name, arg2, arg3, arg4) [inline]
References fn, handleFn(), massageParams(), and name.
withActiveSpan() [2/2]
SugaredTracer::withActiveSpan (name, arg2, arg3, arg4) [inline]
References fn, handleFn(), massageParams(), and name.
withSpan() [1/2]
SugaredTracer::withSpan (name, arg2, arg3, arg4) [inline]
References fn, handleFn(), massageParams(), and name.
withSpan() [2/2]
SugaredTracer::withSpan (name, arg2, arg3, arg4) [inline]
References fn, handleFn(), massageParams(), and name.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/experimental/trace/SugaredTracer.js
backend/node_modules/@opentelemetry/api/build/src/experimental/trace/SugaredTracer.js