ProjectManagement Class Reference
Public Member Functions
constructor (app)
listAndroidApps ()
listIosApps ()
androidApp (appId)
iosApp (appId)
shaCertificate (shaHash)
createAndroidApp (packageName, displayName)
createIosApp (bundleId, displayName)
listAppMetadata ()
setDisplayName (newDisplayName)
transformResponseToAppMetadata (responseData, projectId)
getResourceName ()
getProjectId ()
listPlatformApps (platform, callerName)
assertListAppsResponseData (responseData, callerName)
Detailed Description
The Firebase ProjectManagement service interface.
Member Function Documentation
androidApp()
ProjectManagement::androidApp (appId) [inline]
Creates an AndroidApp object, referencing the specified Android app within this Firebase project.
This method does not perform an RPC.
Parameters
appId - The appId of the Android app to reference.
Returns
An AndroidApp object that references the specified Firebase Android app.
References android_app_1.
assertListAppsResponseData()
ProjectManagement::assertListAppsResponseData (responseData, callerName) [inline]
References $, project_management_api_request_internal_1, and validator.
constructor()
ProjectManagement::constructor (app) [inline]
Parameters
app - The app for this ProjectManagement service. @constructor
References app, error_1, project_management_api_request_internal_1, and validator.
createAndroidApp()
ProjectManagement::createAndroidApp (packageName, displayName) [inline]
Creates a new Firebase Android app associated with this Firebase project.
Parameters
packageName - The canonical package name of the Android App, as would appear in the Google Play Developer Console.
displayName - An optional user-assigned display name for this new app.
Returns
A promise that resolves to the newly created Android app.
References android_app_1, getResourceName(), project_management_api_request_internal_1, then, and validator.
createIosApp()
ProjectManagement::createIosApp (bundleId, displayName) [inline]
Creates a new Firebase iOS app associated with this Firebase project.
Parameters
bundleId - The iOS app bundle ID to use for this new app.
displayName - An optional user-assigned display name for this new app.
Returns
A promise that resolves to the newly created iOS app.
References getResourceName(), ios_app_1, project_management_api_request_internal_1, then, and validator.
getProjectId()
ProjectManagement::getProjectId () [inline]
References app, error_1, Promise, utils, and validator.
getResourceName()
ProjectManagement::getResourceName () [inline]
References $, and getProjectId().
iosApp()
ProjectManagement::iosApp (appId) [inline]
Creates an iOSApp object, referencing the specified iOS app within this Firebase project.
This method does not perform an RPC.
Parameters
appId - The appId of the iOS app to reference.
Returns
An iOSApp object that references the specified Firebase iOS app.
References ios_app_1.
listAndroidApps()
ProjectManagement::listAndroidApps () [inline]
Lists up to 100 Firebase Android apps associated with this Firebase project.
Returns
The list of Android apps.
References listPlatformApps().
listAppMetadata()
ProjectManagement::listAppMetadata () [inline]
Lists up to 100 Firebase apps associated with this Firebase project.
Returns
A promise that resolves to the metadata list of the apps.
References getProjectId(), getResourceName(), then, and transformResponseToAppMetadata().
listIosApps()
ProjectManagement::listIosApps () [inline]
Lists up to 100 Firebase iOS apps associated with this Firebase project.
Returns
The list of iOS apps.
References listPlatformApps().
listPlatformApps()
ProjectManagement::listPlatformApps (platform, callerName) [inline]
Lists up to 100 Firebase apps for a specified platform, associated with this Firebase project.
References $, android_app_1, assertListAppsResponseData(), data, getResourceName(), ios_app_1, project_management_api_request_internal_1, response, then, and validator.
setDisplayName()
ProjectManagement::setDisplayName (newDisplayName) [inline]
Update the display name of this Firebase project.
Parameters
newDisplayName - The new display name to be updated.
Returns
A promise that resolves when the project display name has been updated.
References getResourceName().
shaCertificate()
ProjectManagement::shaCertificate (shaHash) [inline]
Creates a ShaCertificate object.
This method does not perform an RPC.
Parameters
shaHash - The SHA-1 or SHA-256 hash for this certificate.
Returns
A ShaCertificate object contains the specified SHA hash.
References android_app_1.
transformResponseToAppMetadata()
ProjectManagement::transformResponseToAppMetadata (responseData, projectId) [inline]
References app_metadata_1, assertListAppsResponseData(), project_management_api_request_internal_1, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/project-management/project-management.js