LogTimings Class Reference
Public Member Functions
constructor ({ logger, timestampFormat=defaults.timestampFormat, })
printExitInfoTimingTable (exitInfos)
handle (commands)
Static Public Member Functions
static mapCloseEventToTimingInfo ({ command, timings, killed, exitCode, })
Public Attributes
logger
dateFormatter
Detailed Description
Logs timing information about commands as they start/stop and then a summary when all commands finish.
Member Function Documentation
constructor()
LogTimings::constructor ({ logger, timestampFormat=defaults.timestampFormat, }) [inline]
References defaults, logger, and timestampFormat.
handle()
LogTimings::handle (commands) [inline]
References $, after(), at, command(), commands, dateFormatter, finished, logger, ms, operators_1, printExitInfoTimingTable(), and Rx.
mapCloseEventToTimingInfo()
static LogTimings::mapCloseEventToTimingInfo ({ command, timings, killed, exitCode, }) [inline], [static]
References command(), and timings.
printExitInfoTimingTable()
LogTimings::printExitInfoTimingTable (exitInfos) [inline]
References assert, lodash_1, logger, mapCloseEventToTimingInfo(), reverse, and timings.
Member Data Documentation
dateFormatter
LogTimings::dateFormatter
logger
LogTimings::logger
The documentation for this class was generated from the following file:
backend/node_modules/concurrently/dist/src/flow-control/log-timings.js