Reference Class Reference
Public Member Functions
constructor (database, _delegate)
getKey ()
child (pathString)
getParent ()
getRoot ()
set (newVal, onComplete)
update (values, onComplete)
setWithPriority (newVal, newPriority, onComplete)
remove (onComplete)
transaction (transactionUpdate, onComplete, applyLocally)
setPriority (priority, onComplete)
push (value, onComplete)
onDisconnect ()
get key ()
get parent ()
get root ()
constructor (database, _delegate)
getKey ()
child (pathString)
getParent ()
getRoot ()
set (newVal, onComplete)
update (values, onComplete)
setWithPriority (newVal, newPriority, onComplete)
remove (onComplete)
transaction (transactionUpdate, onComplete, applyLocally)
setPriority (priority, onComplete)
push (value, onComplete)
onDisconnect ()
get key ()
get parent ()
get root ()
on (eventType, callback, cancelCallbackOrContext, context)
on (eventType, callback, cancelCallbackOrContext, context)
off (eventType, callback, context)
off (eventType, callback, context)
get ()
get ()
once (eventType, callback, failureCallbackOrContext, context)
once (eventType, callback, failureCallbackOrContext, context)
limitToFirst (limit)
limitToFirst (limit)
limitToLast (limit)
limitToLast (limit)
orderByChild (path)
orderByChild (path)
orderByKey ()
orderByKey ()
orderByPriority ()
orderByPriority ()
orderByValue ()
orderByValue ()
startAt (value=null, name)
startAt (value=null, name)
startAfter (value=null, name)
startAfter (value=null, name)
endAt (value=null, name)
endAt (value=null, name)
endBefore (value=null, name)
endBefore (value=null, name)
equalTo (value, name)
equalTo (value, name)
toString ()
toString ()
toJSON ()
toJSON ()
isEqual (other)
isEqual (other)
get ref ()
get ref ()
Static Public Member Functions
static getCancelAndContextArgs_ (fnName, cancelOrContext, context)
static getCancelAndContextArgs_ (fnName, cancelOrContext, context)
Static Private Member Functions
static _extractFieldValues (documentSnapshot, fieldOrders)
Query#firestore
The [Firestore]Firestore instance for the Firestore database (useful for performing transactions, etc.).
@type {Firestore}
@readonly
async get ()
limitToLast (limit)
startAt (...fieldValuesOrDocumentSnapshot)
startAfter (...fieldValuesOrDocumentSnapshot)
endAt (...fieldValuesOrDocumentSnapshot)
endBefore (...fieldValuesOrDocumentSnapshot)
isEqual (other)
get firestore ()
where (fieldPathOrFilter, opStr, value)
_parseFilter (filter)
_parseFieldFilter (fieldFilterData)
_parseCompositeFilter (compositeFilterData)
select (...fieldPaths)
orderBy (fieldPath, directionStr)
limit (limit)
offset (offset)
count ()
aggregate (aggregateSpec)
findNearest (vectorFieldOrOptions, queryVector, options)
_findNearest (options)
getInequalityFilterFields ()
async explain (options)
_getResponse (transactionOrReadTime, explainOptions)
stream ()
explainStream (explainOptions)
toStructuredQuery ()
_isPermanentRpcError (err, methodName)
_hasRetryTimedOut (methodName, startTime)
onSnapshot (onNext, onError)
withConverter (converter)
createImplicitOrderBy (cursorValuesOrDocumentSnapshot)
createCursor (fieldOrders, cursorValuesOrDocumentSnapshot, before)
validateReference (val)
async _get (transactionOrReadTime)
toCursor (cursor)
toProto (transactionOrReadTime, explainOptions)
_toBundledQuery ()
_stream (transactionOrReadTime, explainOptions)
comparator ()
_createSnapshot (readTime, size, docs, changes)
Member Function Documentation
_createSnapshot()
Query::_createSnapshot (readTime, size, docs, changes) [inline], [private], [inherited]
Construct the resulting snapshot for this query with given documents.
_extractFieldValues()
static Query::_extractFieldValues (documentSnapshot, fieldOrders) [inline], [static], [private], [inherited]
Extracts field values from the DocumentSnapshot based on the provided field order.
References Field, fieldValue, index_1, is, missing(), of, and undefined.
_findNearest()
Query::_findNearest (options) [inline], [inherited]
_get()
async Query::_get (transactionOrReadTime) [inline], [private], [inherited]
Internal get() method that accepts an optional transaction options, and returns a query snapshot with transaction and explain metadata.
_getResponse()
Query::_getResponse (transactionOrReadTime, explainOptions) [inline], [inherited]
_hasRetryTimedOut()
Query::_hasRetryTimedOut (methodName, startTime) [inline], [inherited]
_isPermanentRpcError()
Query::_isPermanentRpcError (err, methodName) [inline], [inherited]
_parseCompositeFilter()
Query::_parseCompositeFilter (compositeFilterData) [inline], [inherited]
_parseFieldFilter()
Query::_parseFieldFilter (fieldFilterData) [inline], [inherited]
References $, FieldPath::documentId(), helpers_1, index_1, not, on, path, path_1, and value.
_parseFilter()
Query::_parseFilter (filter) [inline], [inherited]
References Query::_parseCompositeFilter(), Query::_parseFieldFilter(), filter, and filter_1.
_stream()
Query::_stream (transactionOrReadTime, explainOptions) [inline], [private], [inherited]
Internal streaming method that accepts an optional transaction ID.
BEWARE: If transactionOrReadTime is ITransactionOptions, then the first response in the stream will be a transaction response.
Parameters
transactionOrReadTime A transaction ID, options to start a new transaction, or timestamp to use as read time.
explainOptions Options to use for explaining the query (if any).
_toBundledQuery()
Query::_toBundledQuery () [inline], [private], [inherited]
Converts current Query to an IBundledQuery.
aggregate()
Query::aggregate (aggregateSpec) [inline], [inherited]
child() [1/2]
Reference::child (pathString) [inline]
References child(), database, Reference, and validateArgCount.
child() [2/2]
Reference::child (pathString) [inline]
References child(), database, Reference, and validateArgCount.
comparator()
Query::comparator () [inline], [private], [inherited]
Returns a function that can be used to sort QueryDocumentSnapshots according to the sort criteria of this query.
constructor() [1/2]
Reference::constructor (database, _delegate) [inline]
Call options: new Reference(Repo, Path) or new Reference(url: string, string|RepoManager)
Externally - this is the firebase.database.Reference type.
References database.
constructor() [2/2]
Reference::constructor (database, _delegate) [inline]
Call options: new Reference(Repo, Path) or new Reference(url: string, string|RepoManager)
Externally - this is the firebase.database.Reference type.
References database.
count()
Query::count () [inline], [inherited]
Returns a query that counts the documents in the result set of this query.
The returned query, when executed, counts the documents in the result set of this query without actually downloading the documents.
Using the returned query to count the documents is efficient because only the final count, not the documents' data, is downloaded. The returned query can count the documents in cases where the result set is prohibitively large to download entirely (thousands of documents).
Returns
a query that counts the documents in the result set of this query. The count can be retrieved from snapshot.data().count, where snapshot is the AggregateQuerySnapshot resulting from running the returned query.
createCursor()
Query::createCursor (fieldOrders, cursorValuesOrDocumentSnapshot, before) [inline], [private], [inherited]
Builds a Firestore 'Position' proto message.
createImplicitOrderBy()
Query::createImplicitOrderBy (cursorValuesOrDocumentSnapshot) [inline], [private], [inherited]
Computes the backend ordering semantics for DocumentSnapshot cursors. The order of the implicit ordering always matches the last explicit order by.
Any inequality fields not explicitly ordered should be implicitly ordered in a lexicographical order. When there are multiple inequality filters on the same field, the field should be added only once. Note: getInequalityFilterFields function sorts the key field before other fields. However, we want the key field to be sorted last.
endAt() [1/3]
Query::endAt (...) [inline], [inherited]
endAt() [2/3]
Query::endAt (value = null, name) [inline], [inherited]
References database, Query::endAt(), name, Query, query, validateArgCount, and value.
endAt() [3/3]
Query::endAt (value = null, name) [inline], [inherited]
References database, Query::endAt(), name, Query, query, validateArgCount, and value.
endBefore() [1/3]
Query::endBefore (...) [inline], [inherited]
endBefore() [2/3]
Query::endBefore (value = null, name) [inline], [inherited]
References database, Query::endBefore(), name, Query, query, validateArgCount, and value.
endBefore() [3/3]
Query::endBefore (value = null, name) [inline], [inherited]
References database, Query::endBefore(), name, Query, query, validateArgCount, and value.
equalTo() [1/2]
Query::equalTo (value, name) [inline], [inherited]
Load the selection of children with exactly the specified value, and, optionally, the specified name.
References database, Query::equalTo(), name, Query, query, validateArgCount, and value.
equalTo() [2/2]
Query::equalTo (value, name) [inline], [inherited]
Load the selection of children with exactly the specified value, and, optionally, the specified name.
References database, Query::equalTo(), name, Query, query, validateArgCount, and value.
explain()
async Query::explain (options) [inline], [inherited]
Plans and optionally executes this query. Returns a Promise that will be resolved with the planner information, statistics from the query execution (if any), and the query results (if any).
Returns
A Promise that will be resolved with the planner information, statistics from the query execution (if any), and the query results (if any).
explainStream()
Query::explainStream (explainOptions) [inline], [inherited]
findNearest()
Query::findNearest (vectorFieldOrOptions, queryVector, options) [inline], [inherited]
firestore()
get Query::firestore () [inline], [inherited]
References _firestore.
get() [1/3]
Query::get () [inline], [inherited]
Get the server-value for this query, or return a cached value if not connected.
References database, DataSnapshot, and then.
get() [2/3]
Query::get () [inline], [inherited]
Get the server-value for this query, or return a cached value if not connected.
References database, DataSnapshot, and then.
get() [3/3]
async Query::get () [inline], [inherited]
getCancelAndContextArgs_() [1/2]
static Query::getCancelAndContextArgs_ (fnName, cancelOrContext, context) [inline], [static], [inherited]
Helper used by .on and .once to extract the context and or cancel arguments.
Parameters
fnName - The function name (on or once)
References context, errorPrefix, undefined, validateCallback, and validateContextObject.
getCancelAndContextArgs_() [2/2]
static Query::getCancelAndContextArgs_ (fnName, cancelOrContext, context) [inline], [static], [inherited]
Helper used by .on and .once to extract the context and or cancel arguments.
Parameters
fnName - The function name (on or once)
References context, errorPrefix, undefined, validateCallback, and validateContextObject.
getInequalityFilterFields()
Query::getInequalityFilterFields () [inline], [inherited]
Returns the sorted array of inequality filter fields used in this query.
Returns
An array of inequality filter fields sorted lexicographically by FieldPath.
getKey() [1/2]
Reference::getKey () [inline]
Returns
{?string}
References validateArgCount.
getKey() [2/2]
Reference::getKey () [inline]
Returns
{?string}
References validateArgCount.
getParent() [1/2]
Reference::getParent () [inline]
Returns
{?Reference}
References database, parent(), Reference, and validateArgCount.
getParent() [2/2]
Reference::getParent () [inline]
Returns
{?Reference}
References database, parent(), Reference, and validateArgCount.
getRoot() [1/2]
Reference::getRoot () [inline]
Returns
{!Reference}
References database, Reference, and validateArgCount.
getRoot() [2/2]
Reference::getRoot () [inline]
Returns
{!Reference}
References database, Reference, and validateArgCount.
isEqual() [1/3]
Query::isEqual (other) [inline], [inherited]
Return true if this query and the provided query are equivalent; otherwise, return false.
References error, and validateArgCount.
isEqual() [2/3]
Query::isEqual (other) [inline], [inherited]
Return true if this query and the provided query are equivalent; otherwise, return false.
References error, and validateArgCount.
isEqual() [3/3]
Query::isEqual (other) [inline], [inherited]
Returns true if this Query is equal to the provided value.
Parameters
{*} other The value to compare against.
Returns
{boolean} true if this Query is equal to the provided value.
key() [1/2]
get Reference::key () [inline]
References getKey().
key() [2/2]
get Reference::key () [inline]
References getKey().
limit()
Query::limit (limit) [inline], [inherited]
limitToFirst() [1/2]
Query::limitToFirst (limit) [inline], [inherited]
Set a limit and anchor it to the start of the window.
References database, limit, Query::limitToFirst(), Query, query, and validateArgCount.
limitToFirst() [2/2]
Query::limitToFirst (limit) [inline], [inherited]
Set a limit and anchor it to the start of the window.
References database, limit, Query::limitToFirst(), Query, query, and validateArgCount.
limitToLast() [1/3]
Query::limitToLast (limit) [inline], [inherited]
Set a limit and anchor it to the end of the window.
References database, limit, Query::limitToLast(), Query, query, and validateArgCount.
limitToLast() [2/3]
Query::limitToLast (limit) [inline], [inherited]
Set a limit and anchor it to the end of the window.
References database, limit, Query::limitToLast(), Query, query, and validateArgCount.
limitToLast() [3/3]
Query::limitToLast (limit) [inline], [inherited]
off() [1/2]
Query::off (eventType, callback, context) [inline], [inherited]
References callback, context, off, validateArgCount, validateCallback, validateContextObject, and validateEventType.
off() [2/2]
Query::off (eventType, callback, context) [inline], [inherited]
References callback, context, off, validateArgCount, validateCallback, validateContextObject, and validateEventType.
offset()
Query::offset (offset) [inline], [inherited]
on() [1/2]
Query::on (eventType, callback, cancelCallbackOrContext, context) [inline], [inherited]
References _a, callback, context, database, errorPrefix, Query::getCancelAndContextArgs_(), validateArgCount, and validateCallback.
on() [2/2]
Query::on (eventType, callback, cancelCallbackOrContext, context) [inline], [inherited]
References _a, callback, context, database, errorPrefix, Query::getCancelAndContextArgs_(), validateArgCount, and validateCallback.
once() [1/2]
Query::once (eventType, callback, failureCallbackOrContext, context) [inline], [inherited]
Attaches a listener, waits for the first event, and then removes the listener
References callback, context, database, DataSnapshot, Deferred, deferred, error, errorPrefix, Query::getCancelAndContextArgs_(), result, validateArgCount, and validateCallback.
once() [2/2]
Query::once (eventType, callback, failureCallbackOrContext, context) [inline], [inherited]
Attaches a listener, waits for the first event, and then removes the listener
References callback, context, database, DataSnapshot, Deferred, deferred, error, errorPrefix, Query::getCancelAndContextArgs_(), result, validateArgCount, and validateCallback.
onDisconnect() [1/2]
Reference::onDisconnect () [inline]
References OnDisconnect.
onDisconnect() [2/2]
Reference::onDisconnect () [inline]
References OnDisconnect.
onSnapshot()
Query::onSnapshot (onNext, onError) [inline], [inherited]
orderBy()
Query::orderBy (fieldPath, directionStr) [inline], [inherited]
orderByChild() [1/2]
Query::orderByChild (path) [inline], [inherited]
Given a child path, return a new query ordered by the specified grandchild path.
References database, Query::orderByChild(), path, Query, query, and validateArgCount.
orderByChild() [2/2]
Query::orderByChild (path) [inline], [inherited]
Given a child path, return a new query ordered by the specified grandchild path.
References database, Query::orderByChild(), path, Query, query, and validateArgCount.
orderByKey() [1/2]
Query::orderByKey () [inline], [inherited]
Return a new query ordered by the KeyIndex
References database, Query::orderByKey(), Query, query, and validateArgCount.
orderByKey() [2/2]
Query::orderByKey () [inline], [inherited]
Return a new query ordered by the KeyIndex
References database, Query::orderByKey(), Query, query, and validateArgCount.
orderByPriority() [1/2]
Query::orderByPriority () [inline], [inherited]
Return a new query ordered by the PriorityIndex
References database, Query::orderByPriority(), Query, query, and validateArgCount.
orderByPriority() [2/2]
Query::orderByPriority () [inline], [inherited]
Return a new query ordered by the PriorityIndex
References database, Query::orderByPriority(), Query, query, and validateArgCount.
orderByValue() [1/2]
Query::orderByValue () [inline], [inherited]
Return a new query ordered by the ValueIndex
References database, Query::orderByValue(), Query, query, and validateArgCount.
orderByValue() [2/2]
Query::orderByValue () [inline], [inherited]
Return a new query ordered by the ValueIndex
References database, Query::orderByValue(), Query, query, and validateArgCount.
parent() [1/2]
get Reference::parent () [inline]
References getParent().
parent() [2/2]
get Reference::parent () [inline]
References getParent().
push() [1/2]
Reference::push (value, onComplete) [inline]
References database, error, push, Reference, result, undefined, validateArgCount, validateCallback, and value.
push() [2/2]
Reference::push (value, onComplete) [inline]
References database, error, push, Reference, result, undefined, validateArgCount, validateCallback, and value.
ref() [1/2]
get Query::ref () [inline], [inherited]
References database, and Reference.
ref() [2/2]
get Query::ref () [inline], [inherited]
References database, and Reference.
remove() [1/2]
Reference::remove (onComplete) [inline]
References error, result, validateArgCount, and validateCallback.
remove() [2/2]
Reference::remove (onComplete) [inline]
References error, result, validateArgCount, and validateCallback.
root() [1/2]
get Reference::root () [inline]
References getRoot().
root() [2/2]
get Reference::root () [inline]
References getRoot().
select()
Query::select (...) [inline], [inherited]
set() [1/2]
Reference::set (newVal, onComplete) [inline]
References error, result, validateArgCount, and validateCallback.
set() [2/2]
Reference::set (newVal, onComplete) [inline]
References error, result, validateArgCount, and validateCallback.
setPriority() [1/2]
Reference::setPriority (priority, onComplete) [inline]
References error, result, setPriority(), validateArgCount, and validateCallback.
setPriority() [2/2]
Reference::setPriority (priority, onComplete) [inline]
References error, result, setPriority(), validateArgCount, and validateCallback.
setWithPriority() [1/2]
Reference::setWithPriority (newVal, newPriority, onComplete) [inline]
References error, result, setWithPriority(), validateArgCount, and validateCallback.
setWithPriority() [2/2]
Reference::setWithPriority (newVal, newPriority, onComplete) [inline]
References error, result, setWithPriority(), validateArgCount, and validateCallback.
startAfter() [1/3]
Query::startAfter (...) [inline], [inherited]
startAfter() [2/3]
Query::startAfter (value = null, name) [inline], [inherited]
References database, name, Query, query, Query::startAfter(), validateArgCount, and value.
startAfter() [3/3]
Query::startAfter (value = null, name) [inline], [inherited]
References database, name, Query, query, Query::startAfter(), validateArgCount, and value.
startAt() [1/3]
Query::startAt (...) [inline], [inherited]
startAt() [2/3]
Query::startAt (value = null, name) [inline], [inherited]
References database, name, Query, query, Query::startAt(), validateArgCount, and value.
startAt() [3/3]
Query::startAt (value = null, name) [inline], [inherited]
References database, name, Query, query, Query::startAt(), validateArgCount, and value.
stream()
Query::stream () [inline], [inherited]
toCursor()
Query::toCursor (cursor) [inline], [private], [inherited]
Converts a QueryCursor to its proto representation.
Parameters
cursor The original cursor value
toJSON() [1/2]
Query::toJSON () [inline], [inherited]
References validateArgCount.
toJSON() [2/2]
Query::toJSON () [inline], [inherited]
References validateArgCount.
toProto()
Query::toProto (transactionOrReadTime, explainOptions) [inline], [private], [inherited]
Internal method for serializing a query to its RunQuery proto representation with an optional transaction id or read time.
Parameters
transactionOrReadTime A transaction ID, options to start a new transaction, or timestamp to use as read time.
explainOptions Options to use for explaining the query (if any).
toString() [1/2]
Query::toString () [inline], [inherited]
Returns
URL for this location.
References validateArgCount.
toString() [2/2]
Query::toString () [inline], [inherited]
Returns
URL for this location.
References validateArgCount.
toStructuredQuery()
Query::toStructuredQuery () [inline], [inherited]
transaction() [1/2]
Reference::transaction (transactionUpdate, onComplete, applyLocally) [inline]
References database, error, result, then, TransactionResult, validateArgCount, validateBoolean, and validateCallback.
transaction() [2/2]
Reference::transaction (transactionUpdate, onComplete, applyLocally) [inline]
References database, error, result, then, TransactionResult, validateArgCount, validateBoolean, and validateCallback.
update() [1/2]
Reference::update (values, onComplete) [inline]
References Array, error, i, result, update, validateArgCount, validateCallback, values, and warn.
update() [2/2]
Reference::update (values, onComplete) [inline]
References Array, error, i, result, update, validateArgCount, validateCallback, values, and warn.
validateReference()
Query::validateReference (val) [inline], [private], [inherited]
Validates that a value used with FieldValue.documentId() is either a string or a DocumentReference that is part of the querys result set. Throws a validation error or returns a DocumentReference that can directly be used in the Query.
Parameters
val The value to validate.
Exceptions
If the value cannot be used for this query.
Returns
If valid, returns a DocumentReference that can be used with the query.
where()
Query::where (fieldPathOrFilter, opStr, value) [inline], [inherited]
References _firestore, Query::_parseFilter(), filter, index_1, Query, and value.
withConverter()
Query::withConverter (converter) [inline], [inherited]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database-compat/dist/index.esm2017.js
backend/node_modules/@firebase/database-compat/dist/node-esm/index.js