GeneralSign Class Reference
Public Member Functions
constructor (payload)
addSignature (key, options)
async sign ()
constructor (payload)
addSignature (key, options)
async sign ()
constructor (payload)
addSignature (key, options)
async sign ()
Member Function Documentation
addSignature() [1/3]
GeneralSign::addSignature (key, options) [inline]
References signature.
addSignature() [2/3]
GeneralSign::addSignature (key, options) [inline]
References signature.
addSignature() [3/3]
GeneralSign::addSignature (key, options) [inline]
References signature.
constructor() [1/3]
GeneralSign::constructor (payload) [inline]
constructor() [2/3]
GeneralSign::constructor (payload) [inline]
constructor() [3/3]
GeneralSign::constructor (payload) [inline]
sign() [1/3]
async GeneralSign::sign () [inline]
References FlattenedSign, i, jws, JWSInvalid, rest(), and signature.
sign() [2/3]
async GeneralSign::sign () [inline]
References errors_js_1, i, jws, rest(), sign_js_1, and signature.
sign() [3/3]
async GeneralSign::sign () [inline]
References FlattenedSign, i, jws, JWSInvalid, rest(), and signature.
The documentation for this class was generated from the following files:
backend/node_modules/jose/dist/browser/jws/general/sign.js
backend/node_modules/jose/dist/node/cjs/jws/general/sign.js
backend/node_modules/jose/dist/node/esm/jws/general/sign.js