StreamProxy Class Reference
Public Member Functions
shouldRetryRequest (error, retry)
cancel ()
retry (stream, retry)
throwIfMaxRetriesOrTotalTimeoutExceeded (deadline, maxRetries, totalTimeoutMillis)
streamHandoffErrorHandler (stream, retry, error)
streamHandoffHelper (stream, retry)
eventForwardHelper (stream)
statusMetadataHelper (stream)
forwardEvents (stream)
defaultShouldRetry (error, retry)
forwardEventsWithRetries (stream, retry)
resetStreams (requestStream)
setStream (apiCall, argument, retryRequestOptions={}, retry)
Private Member Functions
constructor (type, callback, rest, gaxServerStreamingRetries)
Member Function Documentation
cancel()
StreamProxy::cancel () [inline]
References stream.
constructor()
StreamProxy::constructor (type, callback, rest, gaxServerStreamingRetries) [inline], [private]
StreamProxy is a proxy to gRPC-streaming method.
@constructor
Parameters
{StreamType} type - the type of gRPC stream.
{ApiCallback} callback - the callback for further API call.
References callback, objectMode, readable, rest(), StreamType, type, undefined, and writable.
defaultShouldRetry()
StreamProxy::defaultShouldRetry (error, retry) [inline]
References error, and retry.
eventForwardHelper()
StreamProxy::eventForwardHelper (stream) [inline]
References emit, event, and stream.
forwardEvents()
StreamProxy::forwardEvents (stream) [inline]
Forward events from an API request stream to the user's stream.
Parameters
{Stream} stream - The API request stream.
{RetryOptions} retry - Configures the exceptions upon which the function should retry, and the parameters to the exponential backoff retry algorithm.
References error, eventForwardHelper(), googleError_1, statusMetadataHelper(), and stream.
forwardEventsWithRetries()
StreamProxy::forwardEventsWithRetries (stream, retry) [inline]
Forward events from an API request stream to the user's stream.
Parameters
{Stream} stream - The API request stream.
{RetryOptions} retry - Configures the exceptions upon which the function eshould retry, and the parameters to the exponential backoff retry algorithm.
References destroy, e, emit, error, eventForwardHelper(), googleError_1, newError, retry, shouldRetryRequest(), status_1, statusMetadataHelper(), stream, and timeout.
resetStreams()
StreamProxy::resetStreams (requestStream) [inline]
Resets the target stream as part of the retry process
Parameters
{CancellableStream} requestStream - the stream to end
retry()
StreamProxy::retry (stream, retry) [inline]
References resetStreams(), retry, stream, streamHandoffHelper(), and undefined.
setStream()
StreamProxy::setStream (apiCall, argument, retryRequestOptions = {}, retry) [inline]
Specifies the target stream.
Parameters
{ApiCall} apiCall - the API function to be called.
{Object} argument - the argument to be passed to the apiCall.
{RetryOptions} retry - Configures the exceptions upon which the function should retry, and the parameters to the exponential backoff retry algorithm.
shouldRetryRequest()
StreamProxy::shouldRetryRequest (error, retry) [inline]
References defaultShouldRetry(), e, error, googleError_1, and retry.
statusMetadataHelper()
StreamProxy::statusMetadataHelper (stream) [inline]
References message, and stream.
streamHandoffErrorHandler()
StreamProxy::streamHandoffErrorHandler (stream, retry, error) [inline]
Error handler for server streaming retries
Parameters
{CancellableStream} stream - the stream being retried
{RetryOptions} retry - Configures the exceptions upon which the function should retry, and the parameters to the exponential backoff retry algorithm.
{Error} error - error to handle
References delay, destroy, e, emit, error, googleError_1, now, retry, shouldRetryRequest(), stream, throwIfMaxRetriesOrTotalTimeoutExceeded(), and timeout.
streamHandoffHelper()
StreamProxy::streamHandoffHelper (stream, retry) [inline]
Used during server streaming retries to handle event forwarding, errors, and/or stream closure
Parameters
{CancellableStream} stream - the stream that we're doing the retry on
{RetryOptions} retry - Configures the exceptions upon which the function should retry, and the parameters to the exponential backoff retry algorithm.
References cancel(), data, emit, error, eventForwardHelper(), retry, stream, and streamHandoffErrorHandler().
throwIfMaxRetriesOrTotalTimeoutExceeded()
StreamProxy::throwIfMaxRetriesOrTotalTimeoutExceeded (deadline, maxRetries, totalTimeoutMillis) [inline]
Helper function to handle total timeout + max retry check for server streaming retries
Parameters
{number} deadline - the current retry deadline
{number} maxRetries - maximum total number of retries
{number} totalTimeoutMillis - total timeout in milliseconds
References $, API, before, destroy, emit, error, googleError_1, now, of, response, status_1, timeout, and undefined.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/streamingCalls/streaming.js