ComponentContainer Class Reference
Public Member Functions
constructor (name)
addComponent (component)
addOrOverwriteComponent (component)
getProvider (name)
getProviders ()
Detailed Description
@license Copyright 2019 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. ComponentContainer that provides Providers for service name T, e.g. auth, auth-internal
Member Function Documentation
addComponent()
ComponentContainer::addComponent (component) [inline]
Parameters
component Component being added
overwrite When a component with the same name has already been registered, if overwrite is true: overwrite the existing component with the new component and create a new provider with the new component. It can be useful in tests where you want to use different mocks for different tests. if overwrite is false: throw an exception
References $, component, getProvider(), has, and name.
addOrOverwriteComponent()
ComponentContainer::addOrOverwriteComponent (component) [inline]
References addComponent(), component, and getProvider().
constructor()
ComponentContainer::constructor (name) [inline]
References Map, and name.
getProvider()
ComponentContainer::getProvider (name) [inline]
getProvider provides a type safe interface where it can only be called with a field name present in NameServiceMapping interface.
Firebase SDKs providing services should extend NameServiceMapping interface to register themselves.
References name, and Provider.
getProviders()
ComponentContainer::getProviders () [inline]
References Array.
The documentation for this class was generated from the following file:
backend/node_modules/@firebase/component/dist/esm/index.esm2017.js