DatabaseRulesClient Class Reference
Public Member Functions
constructor (app, dbUrl)
getRules ()
getRulesJSON ()
setRules (source)
handleError (err)
getErrorMessage (err)
Detailed Description
A helper client for managing RTDB security rules.
Member Function Documentation
constructor()
DatabaseRulesClient::constructor (app, dbUrl) [inline]
References api_request_1, app, emulatorHost(), http, path, process, RULES_URL_PATH, and url_1.
getErrorMessage()
DatabaseRulesClient::getErrorMessage (err) [inline]
References $.
getRules()
DatabaseRulesClient::getRules () [inline]
Gets the currently applied security rules as a string. The return value consists of the rules source including comments.
Returns
A promise fulfilled with the rules as a raw string.
References error_1, handleError(), method, req, and url.
getRulesJSON()
DatabaseRulesClient::getRulesJSON () [inline]
Gets the currently applied security rules as a parsed JSON object. Any comments in the original source are stripped away.
Returns
{Promise<object>} A promise fulfilled with the parsed rules source.
References data, format, handleError(), method, req, and url.
handleError()
DatabaseRulesClient::handleError (err) [inline]
References api_request_1, error_1, getErrorMessage, and message.
setRules()
DatabaseRulesClient::setRules (source) [inline]
Sets the specified rules on the Firebase Database instance. If the rules source is specified as a string or a Buffer, it may include comments.
Parameters
{string|Buffer|object} source Source of the rules to apply. Must not be null or empty.
Returns
{Promise<void>} Resolves when the rules are set on the Database.
References data, error, error_1, handleError(), headers, message, method, Promise, req, source, url, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/database/database.js