ServerInterceptingCall Class Reference
Public Member Functions
constructor (nextCall, responder)
processPendingMessage ()
processPendingStatus ()
start (listener)
sendMetadata (metadata)
sendMessage (message, callback)
sendStatus (status)
startRead ()
getPeer ()
getDeadline ()
getHost ()
Member Function Documentation
constructor()
ServerInterceptingCall::constructor (nextCall, responder) [inline]
References _a, _b, _c, _d, defaultResponder, sendMessage(), sendMetadata(), sendStatus, and start.
getDeadline()
ServerInterceptingCall::getDeadline () [inline]
getHost()
ServerInterceptingCall::getHost () [inline]
getPeer()
ServerInterceptingCall::getPeer () [inline]
processPendingMessage()
ServerInterceptingCall::processPendingMessage () [inline]
processPendingStatus()
ServerInterceptingCall::processPendingStatus () [inline]
sendMessage()
ServerInterceptingCall::sendMessage (message, callback) [inline]
References callback, and message.
sendMetadata()
ServerInterceptingCall::sendMetadata (metadata) [inline]
References processPendingMessage(), and processPendingStatus().
sendStatus()
ServerInterceptingCall::sendStatus (status) [inline]
References status.
start()
ServerInterceptingCall::start (listener) [inline]
References _a, _b, _c, _d, and defaultServerListener.
startRead()
ServerInterceptingCall::startRead () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/server-interceptors.js