NoopTracer Class Reference
Public Member Functions
startSpan (name, options, context=contextApi.active())
startActiveSpan (name, arg2, arg3, arg4)
startSpan (name, options, context=contextApi.active())
startActiveSpan (name, arg2, arg3, arg4)
Detailed Description
No-op implementations of Tracer.
Member Function Documentation
startActiveSpan() [1/2]
NoopTracer::startActiveSpan (name, arg2, arg3, arg4) [inline]
References contextApi, fn, name, setSpan, startSpan(), and undefined.
startActiveSpan() [2/2]
NoopTracer::startActiveSpan (name, arg2, arg3, arg4) [inline]
References context_utils_1, contextApi, fn, name, startSpan(), and undefined.
startSpan() [1/2]
NoopTracer::startSpan (name, options, context = contextApi.active()) [inline]
References context, getSpanContext, isSpanContext(), isSpanContextValid, NonRecordingSpan, and root.
startSpan() [2/2]
NoopTracer::startSpan (name, options, context = contextApi.active()) [inline]
References context, context_utils_1, isSpanContext(), NonRecordingSpan_1, root, and spancontext_utils_1.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/trace/NoopTracer.js
backend/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js