Deferred Class Reference
Public Member Functions
constructor ()
wrapCallback (callback)
constructor ()
wrapCallback (callback)
constructor ()
wrapCallback (callback)
constructor ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
A Promise implementation that supports deferred resolution.
Member Function Documentation
constructor() [1/4]
Deferred::constructor () [inline]
References Promise, reject(), and resolve.
constructor() [2/4]
Deferred::constructor () [inline]
References Promise, reject(), and resolve.
constructor() [3/4]
Deferred::constructor () [inline]
References Promise, reject(), and resolve.
constructor() [4/4]
Deferred::constructor () [inline]
References Promise, reject(), and resolve.
wrapCallback() [1/3]
Deferred::wrapCallback (callback) [inline]
Our API internals are not promisified and cannot because our callback APIs have subtle expectations around invoking promises inline, which Promises are forbidden to do. This method accepts an optional node-style callback and returns a node-style callback which will resolve or reject the Deferred's promise.
References callback, error, reject(), resolve, and value.
wrapCallback() [2/3]
Deferred::wrapCallback (callback) [inline]
Our API internals are not promisified and cannot because our callback APIs have subtle expectations around invoking promises inline, which Promises are forbidden to do. This method accepts an optional node-style callback and returns a node-style callback which will resolve or reject the Deferred's promise.
References callback, error, reject(), resolve, and value.
wrapCallback() [3/3]
Deferred::wrapCallback (callback) [inline]
Our API internals are not promisified and cannot because our callback APIs have subtle expectations around invoking promises inline, which Promises are forbidden to do. This method accepts an optional node-style callback and returns a node-style callback which will resolve or reject the Deferred's promise.
References callback, error, reject(), resolve, and value.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/util/dist/index.cjs.js
backend/node_modules/@firebase/util/dist/index.esm2017.js
backend/node_modules/@firebase/util/dist/node-esm/index.node.esm.js
backend/node_modules/@google-cloud/firestore/build/src/util.js