ReplaySubject Class Reference
Public Member Functions
constructor (_bufferSize=Infinity, _windowTime=Infinity, _timestampProvider=dateTimestampProvider)
next (value)
_subscribe (subscriber)
_trimBuffer ()
constructor ()
constructor (subscribe)
lift (operator)
_throwIfClosed ()
error (err)
complete ()
unsubscribe ()
get observed ()
_trySubscribe (subscriber)
_innerSubscribe (subscriber)
_checkFinalizedStatuses (subscriber)
asObservable ()
subscribe (observerOrNext, error, complete)
forEach (next, promiseCtor)
pipe (...operations)
toPromise (promiseCtor)
Member Function Documentation
_checkFinalizedStatuses()
Subject::_checkFinalizedStatuses (subscriber) [inline], [inherited]
References isStopped().
_innerSubscribe()
Subject::_innerSubscribe (subscriber) [inline], [inherited]
References arrRemove, EMPTY_SUBSCRIPTION, isStopped(), and Subscription.
_subscribe()
ReplaySubject::_subscribe (subscriber) [inline]
References Subject::_checkFinalizedStatuses(), Subject::_innerSubscribe(), Subject::_throwIfClosed(), _trimBuffer(), copy, and i.
_throwIfClosed()
Subject::_throwIfClosed () [inline], [inherited]
References ObjectUnsubscribedError.
_trimBuffer()
ReplaySubject::_trimBuffer () [inline]
References i, last, and now.
_trySubscribe()
Subject::_trySubscribe (subscriber) [inline], [inherited]
References Subject::_throwIfClosed().
asObservable()
Subject::asObservable () [inline], [inherited]
References Observable, and observable.
complete()
Subject::complete () [inline], [inherited]
References Subject::_throwIfClosed(), errorContext, and isStopped().
constructor() [1/3]
Observable::constructor (subscribe) [inline], [inherited]
References Observable::_subscribe(), and Observable::subscribe().
constructor() [2/3]
ReplaySubject::constructor (_bufferSize = Infinity, _windowTime = Infinity, _timestampProvider = dateTimestampProvider) [inline]
constructor() [3/3]
Subject::constructor () [inline], [inherited]
References isStopped().
error()
Subject::error (err) [inline], [inherited]
References Subject::_throwIfClosed(), errorContext, and isStopped().
forEach()
Observable::forEach (next, promiseCtor) [inline], [inherited]
References error, getPromiseCtor(), next(), reject(), resolve, SafeSubscriber, Observable::subscribe(), and value.
lift()
Subject::lift (operator) [inline], [inherited]
References AnonymousSubject.
next()
ReplaySubject::next (value) [inline]
References _trimBuffer(), isStopped(), and value.
observed()
get Subject::observed () [inline], [inherited]
References _a.
pipe()
Observable::pipe (...) [inline], [inherited]
References pipeFromArray.
subscribe()
Observable::subscribe (observerOrNext, error, complete) [inline], [inherited]
References Observable::_subscribe(), Observable::_trySubscribe(), call, error, errorContext, isSubscriber(), SafeSubscriber, and source.
toPromise()
Observable::toPromise (promiseCtor) [inline], [inherited]
References getPromiseCtor(), reject(), resolve, Observable::subscribe(), and value.
unsubscribe()
Subject::unsubscribe () [inline], [inherited]
References isStopped().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/ReplaySubject.js