AuthRequestHandler Class Reference
Public Member Functions
constructor (app)
newAuthUrlBuilder ()
newProjectConfigUrlBuilder ()
getProjectConfig ()
updateProjectConfig (options)
getTenant (tenantId)
listTenants (maxResults=MAX_LIST_TENANT_PAGE_SIZE, pageToken)
deleteTenant (tenantId)
createTenant (tenantOptions)
updateTenant (tenantId, tenantOptions)
createSessionCookie (idToken, expiresIn)
getAccountInfoByUid (uid)
getAccountInfoByEmail (email)
getAccountInfoByPhoneNumber (phoneNumber)
getAccountInfoByFederatedUid (providerId, rawId)
getAccountInfoByIdentifiers (identifiers)
downloadAccount (maxResults=MAX_DOWNLOAD_ACCOUNT_PAGE_SIZE, pageToken)
uploadAccount (users, options)
deleteAccount (uid)
deleteAccounts (uids, force)
setCustomUserClaims (uid, customUserClaims)
updateExistingAccount (uid, properties)
revokeRefreshTokens (uid)
createNewAccount (properties)
getEmailActionLink (requestType, email, actionCodeSettings, newEmail)
getOAuthIdpConfig (providerId)
listOAuthIdpConfigs (maxResults=MAX_LIST_PROVIDER_CONFIGURATION_PAGE_SIZE, pageToken)
deleteOAuthIdpConfig (providerId)
createOAuthIdpConfig (options)
updateOAuthIdpConfig (providerId, options)
getInboundSamlConfig (providerId)
listInboundSamlConfigs (maxResults=MAX_LIST_PROVIDER_CONFIGURATION_PAGE_SIZE, pageToken)
deleteInboundSamlConfig (providerId)
createInboundSamlConfig (options)
updateInboundSamlConfig (providerId, options)
invokeRequestHandler (urlBuilder, apiSettings, requestData, additionalResourceParams)
getAuthUrlBuilder ()
getProjectConfigUrlBuilder ()
Static Public Member Functions
static getErrorCode (response)
static addUidToRequest (id, request)
static addEmailToRequest (id, request)
static addPhoneToRequest (id, request)
static addProviderToRequest (id, request)
Detailed Description
Utility for sending requests to Auth server that are Auth instance related. This includes user, tenant, and project config management related APIs. This extends the BaseFirebaseAuthRequestHandler class and defines additional tenant management related APIs.
Member Function Documentation
addEmailToRequest()
static AbstractAuthRequestHandler::addEmailToRequest (id, request) [inline], [static], [inherited]
References error_1, request, and validator.
addPhoneToRequest()
static AbstractAuthRequestHandler::addPhoneToRequest (id, request) [inline], [static], [inherited]
References error_1, request, and validator.
addProviderToRequest()
static AbstractAuthRequestHandler::addProviderToRequest (id, request) [inline], [static], [inherited]
References error_1, request, and validator.
addUidToRequest()
static AbstractAuthRequestHandler::addUidToRequest (id, request) [inline], [static], [inherited]
References error_1, request, and validator.
constructor()
AuthRequestHandler::constructor (app) [inline]
The FirebaseAuthRequestHandler constructor used to initialize an instance using a FirebaseApp.
Parameters
app - The app used to fetch access tokens to sign API requests. @constructor
References app.
createInboundSamlConfig()
AbstractAuthRequestHandler::createInboundSamlConfig (options) [inline], [inherited]
Creates a new SAML provider configuration with the properties provided.
Parameters
options - The properties to set on the new SAML provider configuration to be created.
Returns
A promise that resolves with the newly created SAML configuration.
References auth_config_1, CREATE_INBOUND_SAML_CONFIG, e, error_1, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, and then.
createNewAccount()
AbstractAuthRequestHandler::createNewAccount (properties) [inline], [inherited]
Create a new user with the properties supplied.
Parameters
properties - The properties to set on the user.
Returns
A promise that resolves when the operation completes with the user id that was created.
References deep_copy_1, e, error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, user_import_builder_1, and validator.
createOAuthIdpConfig()
AbstractAuthRequestHandler::createOAuthIdpConfig (options) [inline], [inherited]
Creates a new OIDC provider configuration with the properties provided.
Parameters
options - The properties to set on the new OIDC provider configuration to be created.
Returns
A promise that resolves with the newly created OIDC configuration.
References auth_config_1, CREATE_OAUTH_IDP_CONFIG, e, error_1, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, and then.
createSessionCookie()
AbstractAuthRequestHandler::createSessionCookie (idToken, expiresIn) [inline], [inherited]
Creates a new Firebase session cookie with the specified duration that can be used for session management (set as a server side session cookie with custom cookie policy). The session cookie JWT will have the same payload claims as the provided ID token.
Parameters
idToken - The Firebase ID token to exchange for a session cookie.
expiresIn - The session cookie duration in milliseconds.
Returns
A promise that resolves on success with the created session cookie.
References exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), request, and response.
createTenant()
AuthRequestHandler::createTenant (tenantOptions) [inline]
Creates a new tenant with the properties provided.
Parameters
tenantOptions - The properties to set on the new tenant to be created.
Returns
A promise that resolves with the newly created tenant object.
References CREATE_TENANT, e, AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, and tenant_1.
deleteAccount()
AbstractAuthRequestHandler::deleteAccount (uid) [inline], [inherited]
Deletes an account identified by a uid.
Parameters
uid - The uid of the user to delete.
Returns
A promise that resolves when the user is deleted.
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, and validator.
deleteAccounts()
AbstractAuthRequestHandler::deleteAccounts (uids, force) [inline], [inherited]
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), MAX_DELETE_ACCOUNTS_BATCH_SIZE, Promise, request, and validator.
deleteInboundSamlConfig()
AbstractAuthRequestHandler::deleteInboundSamlConfig (providerId) [inline], [inherited]
Deletes a SAML configuration identified by a providerId.
Parameters
providerId - The identifier of the SAML configuration to delete.
Returns
A promise that resolves when the SAML provider is deleted.
References auth_config_1, DELETE_INBOUND_SAML_CONFIG, error_1, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, and then.
deleteOAuthIdpConfig()
AbstractAuthRequestHandler::deleteOAuthIdpConfig (providerId) [inline], [inherited]
Deletes an OIDC configuration identified by a providerId.
Parameters
providerId - The identifier of the OIDC configuration to delete.
Returns
A promise that resolves when the OIDC provider is deleted.
References auth_config_1, DELETE_OAUTH_IDP_CONFIG, error_1, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, and then.
deleteTenant()
AuthRequestHandler::deleteTenant (tenantId) [inline]
Deletes a tenant identified by a tenantId.
Parameters
tenantId - The identifier of the tenant to delete.
Returns
A promise that resolves when the tenant is deleted.
References DELETE_TENANT, error_1, AbstractAuthRequestHandler::invokeRequestHandler(), Promise, then, undefined, and validator.
downloadAccount()
AbstractAuthRequestHandler::downloadAccount (maxResults = MAX_DOWNLOAD_ACCOUNT_PAGE_SIZE, pageToken) [inline], [inherited]
Exports the users (single batch only) with a size of maxResults and starting from the offset as specified by pageToken.
Parameters
maxResults - The page size, 1000 if undefined. This is also the maximum allowed limit.
pageToken - The next page token. If not specified, returns users starting without any offset. Users are returned in the order they were created from oldest to newest, relative to the page token offset.
Returns
A promise that resolves with the current batch of downloaded users and the next page token if available. For the last page, an empty list of users and no page token are returned.
References exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), request, and response.
getAccountInfoByEmail()
AbstractAuthRequestHandler::getAccountInfoByEmail (email) [inline], [inherited]
Looks up a user by email.
Parameters
email - The email of the user to lookup.
Returns
A promise that resolves with the user information.
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, and validator.
getAccountInfoByFederatedUid()
AbstractAuthRequestHandler::getAccountInfoByFederatedUid (providerId, rawId) [inline], [inherited]
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), request, and validator.
getAccountInfoByIdentifiers()
AbstractAuthRequestHandler::getAccountInfoByIdentifiers (identifiers) [inline], [inherited]
Looks up multiple users by their identifiers (uid, email, etc).
Parameters
identifiers - The identifiers indicating the users to be looked up. Must have <= 100 entries.
A - promise that resolves with the set of successfully looked up users. Possibly empty if no users were looked up.
References AbstractAuthRequestHandler::addEmailToRequest(), AbstractAuthRequestHandler::addPhoneToRequest(), AbstractAuthRequestHandler::addProviderToRequest(), AbstractAuthRequestHandler::addUidToRequest(), error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), identifier_1, AbstractAuthRequestHandler::invokeRequestHandler(), MAX_GET_ACCOUNTS_BATCH_SIZE, of, Promise, and request.
getAccountInfoByPhoneNumber()
AbstractAuthRequestHandler::getAccountInfoByPhoneNumber (phoneNumber) [inline], [inherited]
Looks up a user by phone number.
Parameters
phoneNumber - The phone number of the user to lookup.
Returns
A promise that resolves with the user information.
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, and validator.
getAccountInfoByUid()
AbstractAuthRequestHandler::getAccountInfoByUid (uid) [inline], [inherited]
Looks up a user by uid.
Parameters
uid - The uid of the user to lookup.
Returns
A promise that resolves with the user information.
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, and validator.
getAuthUrlBuilder()
AbstractAuthRequestHandler::getAuthUrlBuilder () [inline], [inherited]
Returns
The current Auth user management resource URL builder.
getEmailActionLink()
AbstractAuthRequestHandler::getEmailActionLink (requestType, email, actionCodeSettings, newEmail) [inline], [inherited]
Generates the out of band email action link for the email specified using the action code settings provided. Returns a promise that resolves with the generated link.
Parameters
requestType - The request type. This could be either used for password reset, email verification, email link sign-in.
email - The email of the user the link is being sent to.
actionCodeSettings - The optional action code setings which defines whether the link is to be handled by a mobile app and the additional state information to be passed in the deep link, etc. Required when requestType === 'EMAIL_SIGNIN'
newEmail - The email address the account is being updated to. Required only for VERIFY_AND_CHANGE_EMAIL requests.
Returns
A promise that resolves with the email action link.
References action_code_settings_builder_1, deep_copy_1, e, error_1, FIREBASE_AUTH_GET_OOB_CODE, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, and response.
getErrorCode()
static AbstractAuthRequestHandler::getErrorCode (response) [inline], [static], [inherited]
Parameters
response - The response to check for errors.
Returns
The error code if present; null otherwise.
References response, and validator.
getInboundSamlConfig()
AbstractAuthRequestHandler::getInboundSamlConfig (providerId) [inline], [inherited]
Looks up an SAML provider configuration by provider ID.
Parameters
providerId - The provider identifier of the configuration to lookup.
Returns
A promise that resolves with the provider configuration information.
References auth_config_1, error_1, GET_INBOUND_SAML_CONFIG, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), and Promise.
getOAuthIdpConfig()
AbstractAuthRequestHandler::getOAuthIdpConfig (providerId) [inline], [inherited]
Looks up an OIDC provider configuration by provider ID.
Parameters
providerId - The provider identifier of the configuration to lookup.
Returns
A promise that resolves with the provider configuration information.
References auth_config_1, error_1, GET_OAUTH_IDP_CONFIG, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), and Promise.
getProjectConfig()
AuthRequestHandler::getProjectConfig () [inline]
Get the current project's config
Returns
A promise that resolves with the project config information.
References GET_PROJECT_CONFIG, AbstractAuthRequestHandler::invokeRequestHandler(), response, and then.
getProjectConfigUrlBuilder()
AbstractAuthRequestHandler::getProjectConfigUrlBuilder () [inline], [inherited]
Returns
The current project config resource URL builder.
getTenant()
AuthRequestHandler::getTenant (tenantId) [inline]
Looks up a tenant by tenant ID.
Parameters
tenantId - The tenant identifier of the tenant to lookup.
Returns
A promise that resolves with the tenant information.
References error_1, GET_TENANT, AbstractAuthRequestHandler::invokeRequestHandler(), Promise, response, then, and validator.
invokeRequestHandler()
AbstractAuthRequestHandler::invokeRequestHandler (urlBuilder, apiSettings, requestData, additionalResourceParams) [inline], [inherited]
Invokes the request handler based on the API settings object passed.
Parameters
urlBuilder - The URL builder for Auth endpoints.
apiSettings - The API endpoint settings to apply to request and response.
requestData - The request data.
additionalResourceParams - Additional resource related params if needed.
Returns
A promise that resolves with the response.
References api_request_1, data, error, error_1, FIREBASE_AUTH_HEADERS, FIREBASE_AUTH_TIMEOUT, AbstractAuthRequestHandler::getErrorCode(), headers, method, req, response, then, timeout, undefined, and url.
listInboundSamlConfigs()
AbstractAuthRequestHandler::listInboundSamlConfigs (maxResults = MAX_LIST_PROVIDER_CONFIGURATION_PAGE_SIZE, pageToken) [inline], [inherited]
Lists the SAML configurations (single batch only) with a size of maxResults and starting from the offset as specified by pageToken.
Parameters
maxResults - The page size, 100 if undefined. This is also the maximum allowed limit.
pageToken - The next page token. If not specified, returns SAML configurations starting without any offset. Configurations are returned in the order they were created from oldest to newest, relative to the page token offset.
Returns
A promise that resolves with the current batch of downloaded SAML configurations and the next page token if available. For the last page, an empty list of provider configuration and no page token are returned.
References AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), LIST_INBOUND_SAML_CONFIGS, request, and response.
listOAuthIdpConfigs()
AbstractAuthRequestHandler::listOAuthIdpConfigs (maxResults = MAX_LIST_PROVIDER_CONFIGURATION_PAGE_SIZE, pageToken) [inline], [inherited]
Lists the OIDC configurations (single batch only) with a size of maxResults and starting from the offset as specified by pageToken.
Parameters
maxResults - The page size, 100 if undefined. This is also the maximum allowed limit.
pageToken - The next page token. If not specified, returns OIDC configurations without any offset. Configurations are returned in the order they were created from oldest to newest, relative to the page token offset.
Returns
A promise that resolves with the current batch of downloaded OIDC configurations and the next page token if available. For the last page, an empty list of provider configuration and no page token are returned.
References AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), LIST_OAUTH_IDP_CONFIGS, request, and response.
listTenants()
AuthRequestHandler::listTenants (maxResults = MAX_LIST_TENANT_PAGE_SIZE, pageToken) [inline]
Exports the tenants (single batch only) with a size of maxResults and starting from the offset as specified by pageToken.
Parameters
maxResults - The page size, 1000 if undefined. This is also the maximum allowed limit.
pageToken - The next page token. If not specified, returns tenants starting without any offset. Tenants are returned in the order they were created from oldest to newest, relative to the page token offset.
Returns
A promise that resolves with the current batch of downloaded tenants and the next page token if available. For the last page, an empty list of tenants and no page token are returned.
References AbstractAuthRequestHandler::invokeRequestHandler(), LIST_TENANTS, request, and response.
newAuthUrlBuilder()
AuthRequestHandler::newAuthUrlBuilder () [inline]
Returns
A new Auth user management resource URL builder instance.
References app.
newProjectConfigUrlBuilder()
AuthRequestHandler::newProjectConfigUrlBuilder () [inline]
Returns
A new project config resource URL builder instance.
References app.
revokeRefreshTokens()
AbstractAuthRequestHandler::revokeRefreshTokens (uid) [inline], [inherited]
Revokes all refresh tokens for the specified user identified by the uid provided. In addition to revoking all refresh tokens for a user, all ID tokens issued before revocation will also be revoked on the Auth backend. Any request with an ID token generated before revocation will be rejected with a token expired error. Note that due to the fact that the timestamp is stored in seconds, any tokens minted in the same second as the revocation will still be valid. If there is a chance that a token was minted in the last second, delay for 1 second before revoking.
Parameters
uid - The user whose tokens are to be revoked.
Returns
A promise that resolves when the operation completes successfully with the user id of the corresponding user.
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, and validator.
setCustomUserClaims()
AbstractAuthRequestHandler::setCustomUserClaims (uid, customUserClaims) [inline], [inherited]
Sets additional developer claims on an existing user identified by provided UID.
Parameters
uid - The user to edit.
customUserClaims - The developer claims to set.
Returns
A promise that resolves when the operation completes with the user id that was edited.
References error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), JSON, Promise, request, response, and validator.
updateExistingAccount()
AbstractAuthRequestHandler::updateExistingAccount (uid, properties) [inline], [inherited]
Edits an existing user.
Parameters
uid - The user to edit.
properties - The properties to set on the user.
Returns
A promise that resolves when the operation completes with the user id that was edited.
References deep_copy_1, e, error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, user_import_builder_1, and validator.
updateInboundSamlConfig()
AbstractAuthRequestHandler::updateInboundSamlConfig (providerId, options) [inline], [inherited]
Updates an existing SAML provider configuration with the properties provided.
Parameters
providerId - The provider identifier of the SAML configuration to update.
options - The properties to update on the existing configuration.
Returns
A promise that resolves with the modified provider configuration.
References auth_config_1, e, error_1, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, then, UPDATE_INBOUND_SAML_CONFIG, and utils.
updateOAuthIdpConfig()
AbstractAuthRequestHandler::updateOAuthIdpConfig (providerId, options) [inline], [inherited]
Updates an existing OIDC provider configuration with the properties provided.
Parameters
providerId - The provider identifier of the OIDC configuration to update.
options - The properties to update on the existing configuration.
Returns
A promise that resolves with the modified provider configuration.
References auth_config_1, e, error_1, AbstractAuthRequestHandler::getProjectConfigUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, then, UPDATE_OAUTH_IDP_CONFIG, and utils.
updateProjectConfig()
AuthRequestHandler::updateProjectConfig (options) [inline]
Update the current project's config.
Returns
A promise that resolves with the project config information.
References e, AbstractAuthRequestHandler::invokeRequestHandler(), project_config_1, Promise, request, response, then, UPDATE_PROJECT_CONFIG, and utils.
updateTenant()
AuthRequestHandler::updateTenant (tenantId, tenantOptions) [inline]
Updates an existing tenant with the properties provided.
Parameters
tenantId - The tenant identifier of the tenant to update.
tenantOptions - The properties to update on the existing tenant.
Returns
A promise that resolves with the modified tenant object.
References e, error_1, AbstractAuthRequestHandler::invokeRequestHandler(), Promise, request, response, tenant_1, then, UPDATE_TENANT, utils, and validator.
uploadAccount()
AbstractAuthRequestHandler::uploadAccount (users, options) [inline], [inherited]
Imports the list of users provided to Firebase Auth. This is useful when migrating from an external authentication system without having to use the Firebase CLI SDK. At most, 1000 users are allowed to be imported one at a time. When importing a list of password users, UserImportOptions are required to be specified.
Parameters
users - The list of user records to import to Firebase Auth.
options - The user import options, required when the users provided include password credentials.
Returns
A promise that resolves when the operation completes with the result of the import. This includes the number of successful imports, the number of failed uploads and their corresponding errors.
References $, at, error_1, exports, AbstractAuthRequestHandler::getAuthUrlBuilder(), AbstractAuthRequestHandler::invokeRequestHandler(), MAX_UPLOAD_ACCOUNT_BATCH_SIZE, of, once, Promise, request, response, user_import_builder_1, validateCreateEditRequest(), validator, and WriteOperationType.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/auth-api-request.js