LimitedFilter Class Reference
Public Member Functions
constructor (params)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
fullLimitUpdateChild_ (snap, childKey, childSnap, source, changeAccumulator)
constructor (params)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
fullLimitUpdateChild_ (snap, childKey, childSnap, source, changeAccumulator)
constructor (params)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
fullLimitUpdateChild_ (snap, childKey, childSnap, source, changeAccumulator)
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Applies a limit and a range to a node and uses RangedFilter to do the heavy lifting where possible
Member Function Documentation
constructor() [1/3]
LimitedFilter::constructor (params) [inline]
References node.
constructor() [2/3]
LimitedFilter::constructor (params) [inline]
References node.
constructor() [3/3]
LimitedFilter::constructor (params) [inline]
References node.
filtersNodes() [1/3]
LimitedFilter::filtersNodes () [inline]
filtersNodes() [2/3]
LimitedFilter::filtersNodes () [inline]
filtersNodes() [3/3]
LimitedFilter::filtersNodes () [inline]
fullLimitUpdateChild_() [1/3]
LimitedFilter::fullLimitUpdateChild_ (snap, childKey, childSnap, source, changeAccumulator) [inline]
References a, b, changeChildAdded(), changeChildChanged(), changeChildRemoved(), ChildrenNode::EMPTY_NODE(), inRange(), source, and util.
fullLimitUpdateChild_() [2/3]
LimitedFilter::fullLimitUpdateChild_ (snap, childKey, childSnap, source, changeAccumulator) [inline]
References a, assert, b, changeChildAdded(), changeChildChanged(), changeChildRemoved(), ChildrenNode::EMPTY_NODE(), inRange(), and source.
fullLimitUpdateChild_() [3/3]
LimitedFilter::fullLimitUpdateChild_ (snap, childKey, childSnap, source, changeAccumulator) [inline]
References a, assert, b, changeChildAdded(), changeChildChanged(), changeChildRemoved(), ChildrenNode::EMPTY_NODE(), inRange(), and source.
getIndex() [1/3]
LimitedFilter::getIndex () [inline]
getIndex() [2/3]
LimitedFilter::getIndex () [inline]
getIndex() [3/3]
LimitedFilter::getIndex () [inline]
getIndexedFilter() [1/3]
LimitedFilter::getIndexedFilter () [inline]
getIndexedFilter() [2/3]
LimitedFilter::getIndexedFilter () [inline]
getIndexedFilter() [3/3]
LimitedFilter::getIndexedFilter () [inline]
updateChild() [1/3]
LimitedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), fullLimitUpdateChild_(), and source.
updateChild() [2/3]
LimitedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), fullLimitUpdateChild_(), and source.
updateChild() [3/3]
LimitedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), fullLimitUpdateChild_(), and source.
updateFullNode() [1/3]
LimitedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References count, ChildrenNode::EMPTY_NODE(), inRange(), iterator, and next().
updateFullNode() [2/3]
LimitedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References count, ChildrenNode::EMPTY_NODE(), inRange(), iterator, and next().
updateFullNode() [3/3]
LimitedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References count, ChildrenNode::EMPTY_NODE(), inRange(), iterator, and next().
updatePriority() [1/3]
LimitedFilter::updatePriority (oldSnap, newPriority) [inline]
updatePriority() [2/3]
LimitedFilter::updatePriority (oldSnap, newPriority) [inline]
updatePriority() [3/3]
LimitedFilter::updatePriority (oldSnap, newPriority) [inline]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js