TraceAPI Class Reference
Public Member Functions
constructor ()
setGlobalTracerProvider (provider)
getTracerProvider ()
getTracer (name, version)
disable ()
constructor ()
setGlobalTracerProvider (provider)
getTracerProvider ()
getTracer (name, version)
disable ()
Static Public Member Functions
static getInstance ()
static getInstance ()
Detailed Description
Singleton object which represents the entry point to the OpenTelemetry Tracing API
Member Function Documentation
constructor() [1/2]
TraceAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
References deleteSpan, getActiveSpan, getSpan, getSpanContext, isSpanContextValid, ProxyTracerProvider, setSpan, setSpanContext, and wrapSpanContext.
constructor() [2/2]
TraceAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
References context_utils_1, deleteSpan, getActiveSpan, getSpan, getSpanContext, isSpanContextValid, ProxyTracerProvider_1, setSpan, setSpanContext, spancontext_utils_1, and wrapSpanContext.
disable() [1/2]
TraceAPI::disable () [inline]
Remove the global tracer provider
References API_NAME, DiagAPI::instance(), ProxyTracerProvider, and unregisterGlobal.
disable() [2/2]
TraceAPI::disable () [inline]
Remove the global tracer provider
References API_NAME, diag_1, global_utils_1, and ProxyTracerProvider_1.
getInstance() [1/2]
static TraceAPI::getInstance () [inline], [static]
Get the singleton instance of the Trace API
References TraceAPI.
getInstance() [2/2]
static TraceAPI::getInstance () [inline], [static]
Get the singleton instance of the Trace API
References TraceAPI.
getTracer() [1/2]
TraceAPI::getTracer (name, version) [inline]
Returns a tracer from the global tracer provider.
References getTracerProvider(), name, and version.
getTracer() [2/2]
TraceAPI::getTracer (name, version) [inline]
Returns a tracer from the global tracer provider.
References getTracerProvider(), name, and version.
getTracerProvider() [1/2]
TraceAPI::getTracerProvider () [inline]
Returns the global tracer provider.
References API_NAME, and getGlobal.
getTracerProvider() [2/2]
TraceAPI::getTracerProvider () [inline]
Returns the global tracer provider.
References API_NAME, and global_utils_1.
setGlobalTracerProvider() [1/2]
TraceAPI::setGlobalTracerProvider (provider) [inline]
Set the current global tracer.
Returns
true if the tracer provider was successfully registered, else false
References API_NAME, DiagAPI::instance(), registerGlobal, and success.
setGlobalTracerProvider() [2/2]
TraceAPI::setGlobalTracerProvider (provider) [inline]
Set the current global tracer.
Returns
true if the tracer provider was successfully registered, else false
References API_NAME, diag_1, global_utils_1, and success.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/api/trace.js
backend/node_modules/@opentelemetry/api/build/src/api/trace.js