AggregateQuery Class Reference
Public Member Functions
constructor (_query, _aggregates)
get query ()
async get ()
isEqual (other)
async explain (options)
Private Member Functions
async _get (transactionOrReadTime)
_getResponse (transactionOrReadTime, explainOptions)
_stream (transactionOrReadTime, explainOptions)
decodeResult (proto)
toProto (transactionOrReadTime, explainOptions)
Detailed Description
A query that calculates aggregations over an underlying query.
Member Function Documentation
_get()
async AggregateQuery::_get (transactionOrReadTime) [inline], [private]
Internal get() method that accepts an optional transaction options and returns a snapshot with transaction and explain metadata.
References _getResponse(), and response.
_getResponse()
AggregateQuery::_getResponse (transactionOrReadTime, explainOptions) [inline], [private]
Internal get() method that accepts an optional transaction id, and returns transaction metadata.
References _stream(), data, Promise, reject(), resolve, stream, and util_1.
_stream()
AggregateQuery::_stream (transactionOrReadTime, explainOptions) [inline], [private]
Internal streaming method that accepts an optional transaction ID.
BEWARE: If transactionOrReadTime is ITransactionOptions, then the first response in the stream will be a transaction response.
References $, _a, aggregate_query_snapshot_1, async, callback, data, decodeResult(), e, firestore, logger_1, objectMode, proto, query_profile_1, request, stream, stream_1, timestamp_1, toProto(), trace_util_1, transform, undefined, and util_1.
constructor()
AggregateQuery::constructor (_query, _aggregates) [inline]
decodeResult()
AggregateQuery::decodeResult (proto) [inline], [private]
Internal method to decode values within result.
References $, alias(), assert, client, data, mapping, not, of, prop, proto, result, serializer, server, and undefined.
explain()
async AggregateQuery::explain (options) [inline]
Plans and optionally executes this query. Returns a Promise that will be resolved with the planner information, statistics from the query execution (if any), and the query results (if any).
Returns
A Promise that will be resolved with the planner information, statistics from the query execution (if any), and the query results (if any).
References _getResponse(), query_profile_1, result, and undefined.
get()
async AggregateQuery::get () [inline]
Executes this query.
Returns
A promise that will be resolved with the results of the query.
References _get(), async, result, and trace_util_1.
isEqual()
AggregateQuery::isEqual (other) [inline]
Compares this object with the given object for equality.
This object is considered "equal" to the other object if and only if other performs the same aggregations as this AggregateQuery and the underlying Query of other compares equal to that of this object using Query.isEqual().
Parameters
other The object to compare to this object for equality.
Returns
true if this object is "equal" to the given object, as defined above, or false otherwise.
References deepEqual, and query().
query()
get AggregateQuery::query () [inline]
The query whose aggregations will be calculated by this object. Here is the caller graph for this function:
toProto()
AggregateQuery::toProto (transactionOrReadTime, explainOptions) [inline], [private]
Internal method for serializing a query to its RunAggregationQuery proto representation with an optional transaction id.
References aggregate_1, alias(), assert, client, mapping, not, parent, server, timestamp_1, undefined, and util_1.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/reference/aggregate-query.js