BackoffTimeout Class Reference
Public Member Functions
constructor (callback, options)
runTimer (delay)
runOnce ()
stop ()
reset ()
isRunning ()
ref ()
unref ()
getEndTime ()
Member Function Documentation
constructor()
BackoffTimeout::constructor (callback, options) [inline]
The delay time at the start, and after each reset.
The exponential backoff multiplier.
The maximum delay time
The maximum fraction by which the delay time can randomly vary after applying the multiplier.
Indicates whether the timer is currently running.
Indicates whether the timer should keep the Node process running if no other async operation is doing so.
The time that the currently running timer was started. Only valid if running is true.
The approximate time that the currently running timer will end. Only valid if running is true.
References BACKOFF_JITTER, BACKOFF_MULTIPLIER, callback, INITIAL_BACKOFF_MS, and MAX_BACKOFF_MS.
getEndTime()
BackoffTimeout::getEndTime () [inline]
Get the approximate timestamp of when the timer will fire. Only valid if this.isRunning() is true.
isRunning()
BackoffTimeout::isRunning () [inline]
Check whether the timer is currently running.
ref()
BackoffTimeout::ref () [inline]
Set that while the timer is running, it should keep the Node process running.
References _a, and _b.
reset()
BackoffTimeout::reset () [inline]
Reset the delay time to its initial value. If the timer is still running, retroactively apply that reset to the current timer.
References now, and runTimer().
runOnce()
BackoffTimeout::runOnce () [inline]
Call the callback after the current amount of delay time
References runTimer(), and uniformRandom().
runTimer()
BackoffTimeout::runTimer (delay) [inline]
References _a, _b, callback, and delay.
stop()
BackoffTimeout::stop () [inline]
Stop the timer. The callback will not be called until runOnce is called again.
unref()
BackoffTimeout::unref () [inline]
Set that while the timer is running, it should not keep the Node process running.
References _a, and _b.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/backoff-timeout.js