HmacKey Class Reference
Public Member Functions
setMetadata (metadata, optionsOrCallback, cb)
setMetadata (metadata, optionsOrCallback, cb)
constructor (config)
constructor (config)
create (optionsOrCallback, callback)
create (optionsOrCallback, callback)
delete (optionsOrCallback, cb)
delete (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
get (optionsOrCallback, cb)
get (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getRequestInterceptors ()
getRequestInterceptors ()
request_ (reqOpts, callback)
request_ (reqOpts, callback)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
on (eventType, callback, context)
on (eventType, callback, context)
on (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
validateEventType_ (eventType)
validateEventType_ (eventType)
Detailed Description
An HmacKey object contains metadata of an HMAC key created from a service account through the Storage client using Storage#createHmacKey.
See HMAC keys documentation
Member Function Documentation
constructor() [1/2]
ServiceObject::constructor (config) [inline], [inherited]
References config, forEach, ServiceObject::getRequestInterceptors(), methods, parent, request, test, and undefined.
constructor() [2/2]
ServiceObject::constructor (config) [inline], [inherited]
References config, forEach, ServiceObject::getRequestInterceptors(), methods, parent, request, test, and undefined.
create() [1/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
create() [2/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
delete() [1/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util_js_1.
delete() [2/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util.
exists() [1/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util_js_1.
exists() [2/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util.
get() [1/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util_js_1.
get() [2/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util.
getMetadata() [1/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util_js_1.
getMetadata() [2/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util.
getRequestInterceptors() [1/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
getRequestInterceptors() [2/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
off() [1/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [2/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [3/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
on() [1/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [2/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [3/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
request_() [1/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
request_() [2/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
setMetadata() [1/2]
HmacKey::setMetadata (metadata, optionsOrCallback, cb) [inline]
References storage, and storage_js_1.
setMetadata() [2/2]
HmacKey::setMetadata (metadata, optionsOrCallback, cb) [inline]
References IdempotencyStrategy, and storage.
trigger() [1/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [2/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [3/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
validateEventType_() [1/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References et, and util.
validateEventType_() [2/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
validateEventType_() [3/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/hmacKey.js
backend/node_modules/@google-cloud/storage/build/esm/src/hmacKey.js