AsyncSubject Class Reference
Public Member Functions
constructor ()
_checkFinalizedStatuses (subscriber)
next (value)
complete ()
constructor (subscribe)
lift (operator)
_throwIfClosed ()
error (err)
unsubscribe ()
get observed ()
_trySubscribe (subscriber)
_subscribe (subscriber)
_innerSubscribe (subscriber)
asObservable ()
subscribe (observerOrNext, error, complete)
forEach (next, promiseCtor)
pipe (...operations)
toPromise (promiseCtor)
Member Function Documentation
_checkFinalizedStatuses()
AsyncSubject::_checkFinalizedStatuses (subscriber) [inline]
References isStopped().
_innerSubscribe()
Subject::_innerSubscribe (subscriber) [inline], [inherited]
References arrRemove, EMPTY_SUBSCRIPTION, isStopped(), and Subscription.
_subscribe()
Subject::_subscribe (subscriber) [inline], [inherited]
References Subject::_checkFinalizedStatuses(), Subject::_innerSubscribe(), and Subject::_throwIfClosed().
_throwIfClosed()
Subject::_throwIfClosed () [inline], [inherited]
References ObjectUnsubscribedError.
_trySubscribe()
Subject::_trySubscribe (subscriber) [inline], [inherited]
References Subject::_throwIfClosed().
asObservable()
Subject::asObservable () [inline], [inherited]
References Observable, and observable.
complete()
AsyncSubject::complete () [inline]
constructor() [1/2]
AsyncSubject::constructor () [inline]
constructor() [2/2]
Observable::constructor (subscribe) [inline], [inherited]
References Observable::_subscribe(), and Observable::subscribe().
error()
Subject::error (err) [inline], [inherited]
References Subject::_throwIfClosed(), errorContext, and isStopped().
forEach()
Observable::forEach (next, promiseCtor) [inline], [inherited]
References error, getPromiseCtor(), next(), reject(), resolve, SafeSubscriber, Observable::subscribe(), and value.
lift()
Subject::lift (operator) [inline], [inherited]
References AnonymousSubject.
next()
AsyncSubject::next (value) [inline]
References isStopped(), and value.
observed()
get Subject::observed () [inline], [inherited]
References _a.
pipe()
Observable::pipe (...) [inline], [inherited]
References pipeFromArray.
subscribe()
Observable::subscribe (observerOrNext, error, complete) [inline], [inherited]
References Observable::_subscribe(), Observable::_trySubscribe(), call, error, errorContext, isSubscriber(), SafeSubscriber, and source.
toPromise()
Observable::toPromise (promiseCtor) [inline], [inherited]
References getPromiseCtor(), reject(), resolve, Observable::subscribe(), and value.
unsubscribe()
Subject::unsubscribe () [inline], [inherited]
References isStopped().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/AsyncSubject.js