Subchannel Class Reference
Public Member Functions
constructor (channelTarget, subchannelAddress, options, credentials, connector)
getChannelzInfo ()
trace (text)
refTrace (text)
handleBackoffTimer ()
startBackoff ()
stopBackoff ()
startConnectingInternal ()
transitionToState (oldStates, newState, errorMessage)
ref ()
unref ()
unrefIfOneRef ()
createCall (metadata, host, method, listener)
startConnecting ()
getConnectivityState ()
addConnectivityStateListener (listener)
removeConnectivityStateListener (listener)
resetBackoff ()
getAddress ()
getChannelzRef ()
isHealthy ()
addHealthStateWatcher (listener)
removeHealthStateWatcher (listener)
getRealSubchannel ()
realSubchannelEquals (other)
throttleKeepalive (newKeepaliveTime)
Member Function Documentation
addConnectivityStateListener()
Subchannel::addConnectivityStateListener (listener) [inline]
Add a listener function to be called whenever the subchannel's connectivity state changes.
Parameters
listener
addHealthStateWatcher()
Subchannel::addHealthStateWatcher (listener) [inline]
constructor()
Subchannel::constructor (channelTarget, subchannelAddress, options, credentials, connector) [inline]
A class representing a connection to a single backend.
Parameters
channelTarget The target string for the channel as a whole
subchannelAddress The address for the backend that this subchannel will connect to
options The channel options, plus any specific subchannel options for this subchannel
credentials The channel credentials used to establish this connection
The subchannel's current connectivity state. Invariant: session === null if and only if connectivityState is IDLE or TRANSIENT_FAILURE.
The underlying http2 session used to make requests.
Indicates that the subchannel should transition from TRANSIENT_FAILURE to CONNECTING instead of IDLE when the backoff timeout ends.
A list of listener functions that will be called whenever the connectivity state changes. Will be modified by addConnectivityStateListener and removeConnectivityStateListener
Tracks channels and subchannel pools with references to this subchannel
References _a, backoff_timeout_1, channelz_1, connectivity_state_1, credentials, getChannelzInfo(), handleBackoffTimer(), JSON, Set, subchannel_address_1, trace, and undefined.
createCall()
Subchannel::createCall (metadata, host, method, listener) [inline]
References constants_1, method, and status.
getAddress()
Subchannel::getAddress () [inline]
getChannelzInfo()
Subchannel::getChannelzInfo () [inline]
References state(), and trace.
getChannelzRef()
Subchannel::getChannelzRef () [inline]
getConnectivityState()
Subchannel::getConnectivityState () [inline]
Get the subchannel's current connectivity state.
getRealSubchannel()
Subchannel::getRealSubchannel () [inline]
handleBackoffTimer()
Subchannel::handleBackoffTimer () [inline]
References connectivity_state_1, and transitionToState().
isHealthy()
Subchannel::isHealthy () [inline]
realSubchannelEquals()
Subchannel::realSubchannelEquals (other) [inline]
ref()
Subchannel::ref () [inline]
References refTrace().
refTrace()
Subchannel::refTrace (text) [inline]
References constants_1, logging, and text.
removeConnectivityStateListener()
Subchannel::removeConnectivityStateListener (listener) [inline]
Remove a listener previously added with addConnectivityStateListener
Parameters
listener A reference to a function previously passed to addConnectivityStateListener
removeHealthStateWatcher()
Subchannel::removeHealthStateWatcher (listener) [inline]
resetBackoff()
Subchannel::resetBackoff () [inline]
Reset the backoff timeout, and immediately start connecting if in backoff.
References connectivity_state_1, process, and transitionToState().
startBackoff()
Subchannel::startBackoff () [inline]
Start a backoff timer with the current nextBackoff timeout Here is the caller graph for this function:
startConnecting()
Subchannel::startConnecting () [inline]
If the subchannel is currently IDLE, start connecting and switch to the CONNECTING state. If the subchannel is current in TRANSIENT_FAILURE, the next time it would transition to IDLE, start connecting again instead. Otherwise, do nothing.
References connectivity_state_1, process, and transitionToState().
startConnectingInternal()
Subchannel::startConnectingInternal () [inline]
References $, at, connectivity_state_1, constants_1, credentials, error, interval, KEEPALIVE_MAX_TIME_MS, logging, ms, of, server, and transitionToState().
stopBackoff()
Subchannel::stopBackoff () [inline]
throttleKeepalive()
Subchannel::throttleKeepalive (newKeepaliveTime) [inline]
trace()
Subchannel::trace (text) [inline]
References constants_1, logging, text, and TRACER_NAME.
transitionToState()
Subchannel::transitionToState (oldStates, newState, errorMessage) [inline]
Initiate a state transition from any element of oldStates to the new state. If the current connectivityState is not in oldStates, do nothing.
Parameters
oldStates The set of states to transition from
newState The state to transition to
Returns
True if the state changed, false otherwise
References $, _a, _b, connectivity_state_1, ConnectivityState, handleBackoffTimer(), of, process, startBackoff(), startConnectingInternal(), state(), stopBackoff(), and trace.
unref()
Subchannel::unref () [inline]
References channelz_1, connectivity_state_1, credentials, process, refTrace(), and transitionToState().
unrefIfOneRef()
Subchannel::unrefIfOneRef () [inline]
References unref().
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/subchannel.js