ProxyTracer Class Reference
Public Member Functions
constructor (_provider, name, version, options)
startSpan (name, options, context)
startActiveSpan (_name, _options, _context, _fn)
_getTracer ()
constructor (_provider, name, version, options)
startSpan (name, options, context)
startActiveSpan (_name, _options, _context, _fn)
_getTracer ()
Detailed Description
Proxy tracer provided by the proxy tracer provider
Member Function Documentation
_getTracer() [1/2]
ProxyTracer::_getTracer () [inline]
Try to get a tracer from the proxy tracer provider. If the proxy tracer provider has no delegate, return a noop tracer.
References name, NOOP_TRACER, and version.
_getTracer() [2/2]
ProxyTracer::_getTracer () [inline]
Try to get a tracer from the proxy tracer provider. If the proxy tracer provider has no delegate, return a noop tracer.
References name, NOOP_TRACER, and version.
constructor() [1/2]
ProxyTracer::constructor (_provider, name, version, options) [inline]
References name, and version.
constructor() [2/2]
ProxyTracer::constructor (_provider, name, version, options) [inline]
References name, and version.
startActiveSpan() [1/2]
ProxyTracer::startActiveSpan (_name, _options, _context, _fn) [inline]
References _getTracer().
startActiveSpan() [2/2]
ProxyTracer::startActiveSpan (_name, _options, _context, _fn) [inline]
References _getTracer().
startSpan() [1/2]
ProxyTracer::startSpan (name, options, context) [inline]
References _getTracer(), context, and name.
startSpan() [2/2]
ProxyTracer::startSpan (name, options, context) [inline]
References _getTracer(), context, and name.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/trace/ProxyTracer.js
backend/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js