BehaviorSubject Class Reference
Public Member Functions
constructor (_value)
get value ()
_subscribe (subscriber)
getValue ()
next (value)
constructor ()
lift (operator)
_throwIfClosed ()
error (err)
complete ()
unsubscribe ()
get observed ()
_trySubscribe (subscriber)
_innerSubscribe (subscriber)
_checkFinalizedStatuses (subscriber)
asObservable ()
subscribe (observerOrNext, error, complete)
forEach (next, promiseCtor)
pipe (...operations)
toPromise (promiseCtor)
Member Function Documentation
_checkFinalizedStatuses()
Subject::_checkFinalizedStatuses (subscriber) [inline], [inherited]
References isStopped().
_innerSubscribe()
Subject::_innerSubscribe (subscriber) [inline], [inherited]
References arrRemove, EMPTY_SUBSCRIPTION, isStopped(), and Subscription.
_subscribe()
BehaviorSubject::_subscribe (subscriber) [inline]
_throwIfClosed()
Subject::_throwIfClosed () [inline], [inherited]
References ObjectUnsubscribedError.
_trySubscribe()
Subject::_trySubscribe (subscriber) [inline], [inherited]
References Subject::_throwIfClosed().
asObservable()
Subject::asObservable () [inline], [inherited]
References Observable, and observable.
complete()
Subject::complete () [inline], [inherited]
References Subject::_throwIfClosed(), errorContext, and isStopped().
constructor() [1/2]
BehaviorSubject::constructor (_value) [inline]
constructor() [2/2]
Subject::constructor () [inline], [inherited]
References isStopped().
error()
Subject::error (err) [inline], [inherited]
References Subject::_throwIfClosed(), errorContext, and isStopped().
forEach()
Observable::forEach (next, promiseCtor) [inline], [inherited]
References error, getPromiseCtor(), next(), reject(), resolve, SafeSubscriber, Observable::subscribe(), and value.
getValue()
BehaviorSubject::getValue () [inline]
References Subject::_throwIfClosed().
lift()
Subject::lift (operator) [inline], [inherited]
References AnonymousSubject.
next()
BehaviorSubject::next (value) [inline]
References value().
observed()
get Subject::observed () [inline], [inherited]
References _a.
pipe()
Observable::pipe (...) [inline], [inherited]
References pipeFromArray.
subscribe()
Observable::subscribe (observerOrNext, error, complete) [inline], [inherited]
References Observable::_subscribe(), Observable::_trySubscribe(), call, error, errorContext, isSubscriber(), SafeSubscriber, and source.
toPromise()
Observable::toPromise (promiseCtor) [inline], [inherited]
References getPromiseCtor(), reject(), resolve, Observable::subscribe(), and value.
unsubscribe()
Subject::unsubscribe () [inline], [inherited]
References isStopped().
value()
get BehaviorSubject::value () [inline]
References getValue().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/BehaviorSubject.js