GoogleAuth Class Reference
Public Member Functions
get isGCE ()
setGapicJWTValues (client)
getProjectId (callback)
async getProjectIdOptional ()
async findAndCacheProjectId ()
async getProjectIdAsync ()
async getUniverseDomainFromMetadataServer ()
async getUniverseDomain ()
getAnyScopes ()
getApplicationDefault (optionsOrCallback={}, callback)
async getApplicationDefaultAsync (options={})
async _checkIsGCE ()
async _tryGetApplicationCredentialsFromEnvironmentVariable (options)
async _tryGetApplicationCredentialsFromWellKnownFile (options)
async _getApplicationCredentialsFromFilePath (filePath, options={})
fromImpersonatedJSON (json)
fromJSON (json, options={})
_cacheClientFromJSON (json, options)
fromStream (inputStream, optionsOrCallback={}, callback)
fromStreamAsync (inputStream, options)
fromAPIKey (apiKey, options={})
_isWindows ()
async getDefaultServiceProjectId ()
getProductionProjectId ()
async getFileProjectId ()
async getExternalAccountClientProjectId ()
async getGCEProjectId ()
getCredentials (callback)
async getCredentialsAsync ()
async getClient ()
async getIdTokenClient (targetAudience)
async getAccessToken ()
async getRequestHeaders (url)
async authorizeRequest (opts)
async request (opts)
getEnv ()
async sign (data, endpoint)
async signBlob (crypto, emailOrUniqueId, data, endpoint)
Private Member Functions
constructor (opts={})
Member Function Documentation
_cacheClientFromJSON()
GoogleAuth::_cacheClientFromJSON (json, options) [inline]
Return a JWT or UserRefreshClient from JavaScript object, caching both the object used to instantiate and the client.
Parameters
json The input object.
options The JWT or UserRefresh options for the client
Returns
JWT or UserRefresh Client with data
References client, fromJSON, and json.
_checkIsGCE()
async GoogleAuth::_checkIsGCE () [inline]
Determines whether the auth layer is running on Google Compute Engine. Checks for GCP Residency, then fallback to checking if metadata server is available.
Returns
A promise that resolves with the boolean. @api private
References gcpMetadata, and undefined.
_getApplicationCredentialsFromFilePath()
async GoogleAuth::_getApplicationCredentialsFromFilePath (filePath, options = {}) [inline]
Attempts to load default credentials from a file at the given path..
Parameters
filePath The path to the file to read.
Returns
Promise that resolves with the OAuth2Client @api private
_isWindows()
GoogleAuth::_isWindows () [inline]
Determines whether the current operating system is Windows. @api private Here is the caller graph for this function:
_tryGetApplicationCredentialsFromEnvironmentVariable()
async GoogleAuth::_tryGetApplicationCredentialsFromEnvironmentVariable (options) [inline]
Attempts to load default credentials from the environment variable path..
Returns
Promise that resolves with the OAuth2Client or null. @api private
References $, _getApplicationCredentialsFromFilePath(), credential, e, file, process, and read.
_tryGetApplicationCredentialsFromWellKnownFile()
async GoogleAuth::_tryGetApplicationCredentialsFromWellKnownFile (options) [inline]
Attempts to load default credentials from a well-known file location
Returns
Promise that resolves with the OAuth2Client or null. @api private
References _getApplicationCredentialsFromFilePath(), _isWindows(), client, fs, location, path, and process.
authorizeRequest()
async GoogleAuth::authorizeRequest (opts) [inline]
Obtain credentials for a request, then attach the appropriate headers to the request options.
Parameters
opts Axios or Request options on which to attach the headers
References client, getClient(), headers, and url.
constructor()
GoogleAuth::constructor (opts = {}) [inline], [private]
Configuration is resolved in the following order of precedence:
credentials
keyFilename
keyFile
clientOptions are passed to the AuthClients.
Parameters
opts
Caches a value indicating whether the auth layer is running on Google Compute Engine.
A pending AuthClient. Used for concurrent GoogleAuth.getClient calls.
findAndCacheProjectId()
async GoogleAuth::findAndCacheProjectId () [inline]
References exports, getDefaultServiceProjectId(), getExternalAccountClientProjectId(), getFileProjectId(), getGCEProjectId(), and getProductionProjectId().
fromAPIKey()
GoogleAuth::fromAPIKey (apiKey, options = {}) [inline]
Create a credentials instance using the given API key string. The created client is not cached. In order to create and cache it use the getClient method after first providing an apiKey.
Parameters
apiKey The API key string
options An optional options object.
Returns
A JWT loaded from the key
fromImpersonatedJSON()
GoogleAuth::fromImpersonatedJSON (json) [inline]
Create a credentials instance using a given impersonated input options.
Parameters
json The impersonated input object.
Returns
JWT or UserRefresh Client with data
Prevents DOS attacks.
See also
https://github.com/googleapis/google-auth-library-nodejs/security/code-scanning/85
References $, _a, _b, _c, _d, Array, client, getAnyScopes(), impersonated_1, incoming, is, JSON, not, refreshclient_1, and type.
fromJSON()
GoogleAuth::fromJSON (json, options = {}) [inline]
Create a credentials instance using the given input options.
Parameters
json The input object.
options The JWT or UserRefresh options for the client
Returns
JWT or UserRefresh Client with data
fromStream()
GoogleAuth::fromStream (inputStream, optionsOrCallback = {}, callback) [inline]
fromStreamAsync()
GoogleAuth::fromStreamAsync (inputStream, options) [inline]
References _cacheClientFromJSON(), chunk(), client, data, JSON, jwtclient_1, Promise, r, reject(), resolve, and setGapicJWTValues().
getAccessToken()
async GoogleAuth::getAccessToken () [inline]
Automatically obtain application default credentials, and return an access token for making requests.
References client, and getClient().
getAnyScopes()
GoogleAuth::getAnyScopes () [inline]
Returns
Any scopes (user-specified or default scopes specified by the client library) that need to be set on the current Auth client.
getApplicationDefault()
GoogleAuth::getApplicationDefault (optionsOrCallback = {}, callback) [inline]
getApplicationDefaultAsync()
async GoogleAuth::getApplicationDefaultAsync (options = {}) [inline]
getClient()
async GoogleAuth::getClient () [inline]
Automatically obtain an AuthClient based on the provided configuration. If no options were passed, use Application Default Credentials.
References __classPrivateFieldGet, __classPrivateFieldSet, _GoogleAuth_determineClient, _GoogleAuth_instances, _GoogleAuth_pendingAuthClient, and call.
getCredentials()
GoogleAuth::getCredentials (callback) [inline]
References callback, getCredentialsAsync(), and r.
getCredentialsAsync()
async GoogleAuth::getCredentialsAsync () [inline]
References _checkIsGCE(), baseexternalclient_1, client, exports, gcpMetadata, getClient(), impersonated_1, and Promise.
getDefaultServiceProjectId()
async GoogleAuth::getDefaultServiceProjectId () [inline]
Run the Google Cloud SDK command that prints the default project ID
References child_process_1, e, JSON, Promise, and resolve.
getEnv()
GoogleAuth::getEnv () [inline]
Determine the compute environment in which the code is running.
References envDetect_1.
getExternalAccountClientProjectId()
async GoogleAuth::getExternalAccountClientProjectId () [inline]
Gets the project ID from external account client if available.
References baseexternalclient_1, and getClient().
getFileProjectId()
async GoogleAuth::getFileProjectId () [inline]
Loads the project id from the GOOGLE_APPLICATION_CREDENTIALS json file. @api private
References _tryGetApplicationCredentialsFromEnvironmentVariable(), getClient(), and r.
getGCEProjectId()
async GoogleAuth::getGCEProjectId () [inline]
Gets the Compute Engine project ID if it can be inferred.
References e, gcpMetadata, and r.
getIdTokenClient()
async GoogleAuth::getIdTokenClient (targetAudience) [inline]
Creates a client which will fetch an ID token for authorization.
Parameters
targetAudience the audience for the fetched ID token.
Returns
IdTokenClient for making HTTP calls authenticated with ID tokens.
References client, getClient(), and idtokenclient_1.
getProductionProjectId()
GoogleAuth::getProductionProjectId () [inline]
Loads the project id from environment variables. @api private
References process.
getProjectId()
GoogleAuth::getProjectId (callback) [inline]
References callback, getProjectIdAsync(), and r.
getProjectIdAsync()
async GoogleAuth::getProjectIdAsync () [inline]
References findAndCacheProjectId().
getProjectIdOptional()
async GoogleAuth::getProjectIdOptional () [inline]
A temporary method for internal getProjectId usages where null is acceptable. In a future major release, getProjectId should return null (as the Promise<string | null> base signature describes) and this private method should be removed.
Returns
Promise that resolves with project id (or null)
References e, exports, and getProjectId().
getRequestHeaders()
async GoogleAuth::getRequestHeaders (url) [inline]
Obtain the HTTP headers that will provide authorization for a given request.
References client, getClient(), and url.
getUniverseDomain()
async GoogleAuth::getUniverseDomain () [inline]
Retrieves, caches, and returns the universe domain in the following order of precedence:
The universe domain in GoogleAuth.clientOptions
An existing or ADC AuthClient's universe domain
gcpMetadata.universe, if Compute client
Returns
The universe domain
References _a, authclient_1, getClient(), and util_1.
getUniverseDomainFromMetadataServer()
async GoogleAuth::getUniverseDomainFromMetadataServer () [inline]
Retrieves a universe domain from the metadata server via gcpMetadata.universe.
Returns
a universe domain
References _a, authclient_1, e, and gcpMetadata.
isGCE()
get GoogleAuth::isGCE () [inline]
request()
async GoogleAuth::request (opts) [inline]
Automatically obtain application default credentials, and make an HTTP request using the given options.
Parameters
opts Axios request options for the HTTP request.
References client, and getClient().
setGapicJWTValues()
GoogleAuth::setGapicJWTValues (client) [inline]
References client.
sign()
async GoogleAuth::sign (data, endpoint) [inline]
References client, crypto, crypto_1, data, getClient(), getCredentials(), getUniverseDomain(), https, impersonated_1, jwtclient_1, sign, signBlob(), and universe.
signBlob()
async GoogleAuth::signBlob (crypto, emailOrUniqueId, data, endpoint) [inline]
References $, crypto, data, method, request, res, retry, signBlob(), URL, and url.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/googleauth.js