Http2Client Class Reference
Public Member Functions
constructor (retry=defaultRetryConfig())
send (config)
sendWithRetry (config, retryAttempts=0)
createRequestResponse (resp)
waitForRetry (delayMillis)
getRetryDelayMillis (retryAttempts, err)
isRetryEligible (retryAttempts, err)
parseRetryAfterIntoMillis (retryAfter)
backOffDelayMillis (retryAttempts)
Member Function Documentation
backOffDelayMillis()
RequestClient::backOffDelayMillis (retryAttempts) [inline], [inherited]
References error_1, and retry.
constructor()
Http2Client::constructor (retry = defaultRetryConfig()) [inline]
References retry.
createRequestResponse()
RequestClient::createRequestResponse (resp) [inline], [inherited]
getRetryDelayMillis()
RequestClient::getRetryDelayMillis (retryAttempts, err) [inline], [inherited]
Checks if a failed request is eligible for a retry, and if so returns the duration to wait before initiating the retry.
Parameters
retryAttempts - Number of retries completed up to now.
err - The last encountered error.
Returns
A 2-tuple where the 1st element is the duration to wait before another retry, and the 2nd element is a boolean indicating whether the request is eligible for a retry or not.
References RequestClient::backOffDelayMillis(), RequestClient::isRetryEligible(), RequestClient::parseRetryAfterIntoMillis(), and response.
isRetryEligible()
RequestClient::isRetryEligible (retryAttempts, err) [inline], [inherited]
References retry.
parseRetryAfterIntoMillis()
RequestClient::parseRetryAfterIntoMillis (retryAfter) [inline], [inherited]
??? Parses the Retry-After header as a milliseconds value. Return value is negative if the Retry-After header contains an expired timestamp or otherwise malformed.
References isNaN, and parseInt().
send()
Http2Client::send (config) [inline]
Sends an HTTP/2 request to a remote server. If the server responds with a successful response (2xx), the returned promise resolves with an RequestResponse. If the server responds with an error (3xx, 4xx, 5xx), the promise rejects with an RequestResponseError. In case of all other errors, the promise rejects with a FirebaseAppError. If a request fails due to a low-level network error, the client transparently retries the request once before rejecting the promise.
If the request data is specified as an object, it will be serialized into a JSON string. The application/json content-type header will also be automatically set in this case. For all other payload types, the content-type header should be explicitly set by the caller. To send a JSON leaf value (e.g. "foo", 5), parse it into JSON, and pass as a string or a Buffer along with the appropriate content-type header.
Parameters
config - HTTP/2 request to be sent.
Returns
A promise that resolves with the response details.
References config, and sendWithRetry().
sendWithRetry()
Http2Client::sendWithRetry (config, retryAttempts = 0) [inline]
Sends an HTTP/2 request. In the event of an error, retries the HTTP/2 request according to the RetryConfig set on the Http2Client.
Parameters
config - HTTP/2 request to be sent.
retryAttempts - Number of retries performed up to now.
Returns
A promise that resolves with the response details.
References $, config, RequestClient::createRequestResponse(), error_1, RequestClient::getRetryDelayMillis(), AsyncHttp2Call::invoke(), request, RequestResponseError, retry, sendWithRetry(), and RequestClient::waitForRetry().
waitForRetry()
RequestClient::waitForRetry (delayMillis) [inline], [inherited]
References Promise, and resolve.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js