Transaction Class Reference
Public Member Functions
get (refOrQuery)
getAll (...documentRefsOrReadOptions)
create (documentRef, data)
set (documentRef, data, options)
update (documentRef, dataOrField,...preconditionOrValues)
delete (documentRef, precondition)
withLazyStartedTransaction (param, resultFn)
async getSingleFn (document, opts)
async getBatchFn ({ documents, fieldMask, }, opts)
async getQueryFn (query, opts)
Private Member Functions
constructor (firestore, requestTag, transactionOptions)
async commit ()
async rollback ()
async runTransaction (updateFunction)
async runTransactionOnce (updateFunction)
Detailed Description
A reference to a transaction.
The Transaction object passed to a transaction's updateFunction provides the methods to read and write data within the transaction context. See [runTransaction()]Firestore#runTransaction.
Member Function Documentation
commit()
async Transaction::commit () [inline], [private]
Commits all queued-up changes in this transaction and releases all locks.
References _a, _firestore, async, READ_ONLY_WRITE_ERROR_MSG, requestTag, trace_util_1, and undefined.
constructor()
Transaction::constructor (firestore, requestTag, transactionOptions) [inline], [private]
Parameters
firestore The Firestore Database client.
requestTag A unique client-assigned identifier for the scope of this transaction.
transactionOptions The user-defined options for this transaction.
References _firestore, backoff_1, firestore, index_1, and requestTag.
create()
Transaction::create (documentRef, data) [inline]
References data, and READ_ONLY_WRITE_ERROR_MSG.
delete()
Transaction::delete (documentRef, precondition) [inline]
References READ_ONLY_WRITE_ERROR_MSG.
get()
Transaction::get (refOrQuery) [inline]
References _firestore, aggregate_query_1, document_reference_1, query_1, READ_AFTER_WRITE_ERROR_MSG, and trace_util_1.
getAll()
Transaction::getAll (...) [inline]
References getBatchFn(), parseGetAllArguments, READ_AFTER_WRITE_ERROR_MSG, validate_1, and withLazyStartedTransaction().
getBatchFn()
async Transaction::getBatchFn ({ documents, fieldMask, }, opts) [inline]
getQueryFn()
async Transaction::getQueryFn (query, opts) [inline]
References query.
getSingleFn()
async Transaction::getSingleFn (document, opts) [inline]
References _firestore, document_reader_1, result, and undefined.
rollback()
async Transaction::rollback () [inline], [private]
Releases all locks and rolls back this transaction. The rollback process is completed asynchronously and this function resolves before the operation is completed.
References _a, _firestore, async, database, logger_1, request, trace_util_1, and undefined.
runTransaction()
async Transaction::runTransaction (updateFunction) [inline], [private]
Executes updateFunction() and commits the transaction with retry.
References _firestore, async, attempt, isRetryableTransactionError(), logger_1, maybeBackoff(), Promise, runTransactionOnce(), trace_util_1, and undefined.
runTransactionOnce()
async Transaction::runTransactionOnce (updateFunction) [inline], [private]
Make single attempt to execute updateFunction() and commit the transaction. Will rollback upon error.
References commit(), logger_1, Promise, result, and rollback().
set()
Transaction::set (documentRef, data, options) [inline]
References data, and READ_ONLY_WRITE_ERROR_MSG.
update()
Transaction::update (documentRef, dataOrField, ...) [inline]
References READ_ONLY_WRITE_ERROR_MSG, and validate_1.
withLazyStartedTransaction()
Transaction::withLazyStartedTransaction (param, resultFn) [inline]
Given a function that performs a read operation, ensures that the first one is provided with new transaction options and all subsequent ones are queued upon the resulting transaction ID.
References param, and r.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/transaction.js