StatsReporter Class Reference
Public Member Functions
constructor (collection, server_)
reportStats_ ()
constructor (collection, server_)
reportStats_ ()
constructor (collection, server_)
reportStats_ ()
Member Function Documentation
constructor() [1/3]
StatsReporter::constructor (collection, server_) [inline]
References FIRST_STATS_MAX_TIME, FIRST_STATS_MIN_TIME, reportStats_(), setTimeoutNonBlocking, and timeout.
constructor() [2/3]
StatsReporter::constructor (collection, server_) [inline]
References FIRST_STATS_MAX_TIME, FIRST_STATS_MIN_TIME, reportStats_(), setTimeoutNonBlocking, and timeout.
constructor() [3/3]
StatsReporter::constructor (collection, server_) [inline]
References FIRST_STATS_MAX_TIME, FIRST_STATS_MIN_TIME, reportStats_(), setTimeoutNonBlocking, and timeout.
reportStats_() [1/3]
StatsReporter::reportStats_ () [inline]
References each, REPORT_STATS_INTERVAL, reportStats_(), setTimeoutNonBlocking, stats, util, and value.
reportStats_() [2/3]
StatsReporter::reportStats_ () [inline]
References contains, each, REPORT_STATS_INTERVAL, reportStats_(), setTimeoutNonBlocking, stats, and value.
reportStats_() [3/3]
StatsReporter::reportStats_ () [inline]
References contains, each, REPORT_STATS_INTERVAL, reportStats_(), setTimeoutNonBlocking, stats, and value.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js