ValidationPath Class Reference
Public Member Functions
constructor (path, errorPrefix_)
constructor (path, errorPrefix_)
constructor (path, errorPrefix_)
Detailed Description
Dynamic (mutable) path used to count path lengths.
This class is used to efficiently check paths for valid length (in UTF8 bytes) and depth (used in path validation).
Throws Error exception if path is ever invalid.
The definition of a path always begins with '/'.
Member Function Documentation
constructor() [1/3]
ValidationPath::constructor (path, errorPrefix_) [inline]
Parameters
path - Initial Path.
errorPrefix_ - Prefix for any error messages.
Initialize to number of '/' chars needed in path.
References i, path, pathSlice(), util, and validationPathCheckValid().
constructor() [2/3]
ValidationPath::constructor (path, errorPrefix_) [inline]
Parameters
path - Initial Path.
errorPrefix_ - Prefix for any error messages.
Initialize to number of '/' chars needed in path.
References i, path, pathSlice(), stringLength, and validationPathCheckValid().
constructor() [3/3]
ValidationPath::constructor (path, errorPrefix_) [inline]
Parameters
path - Initial Path.
errorPrefix_ - Prefix for any error messages.
Initialize to number of '/' chars needed in path.
References i, path, pathSlice(), stringLength, and validationPathCheckValid().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js