MachineLearning Class Reference
Public Member Functions
constructor (app)
get app ()
createModel (model)
updateModel (modelId, model)
publishModel (modelId)
unpublishModel (modelId)
getModel (modelId)
listModels (options={})
deleteModel (modelId)
setPublishStatus (modelId, publish)
signUrlIfPresent (options)
signUrl (unsignedUrl)
Detailed Description
The Firebase MachineLearning service interface.
Member Function Documentation
app()
get MachineLearning::app () [inline]
The firebase-admin.app#App associated with the current MachineLearning service instance. Here is the caller graph for this function:
constructor()
MachineLearning::constructor (app) [inline]
Parameters
app - The app for this ML service. @constructor
References app(), client, error_1, machine_learning_api_client_1, message, and validator.
createModel()
MachineLearning::createModel (model) [inline]
Creates a model in the current Firebase project.
Parameters
model - The model to create.
Returns
A Promise fulfilled with the created model.
References client, Model, operation, and signUrlIfPresent().
deleteModel()
MachineLearning::deleteModel (modelId) [inline]
Deletes a model from the current project.
Parameters
modelId - The ID of the model to delete.
References client.
getModel()
MachineLearning::getModel (modelId) [inline]
Gets the model specified by the given ID.
Parameters
modelId - The ID of the model to get.
Returns
A Promise fulfilled with the model object.
References client, and Model.
listModels()
MachineLearning::listModels (options = {}) [inline]
Lists the current project's models.
Parameters
options - The listing options.
Returns
A promise that resolves with the current (filtered) list of models and the next page token. For the last page, an empty list of models and no page token are returned.
publishModel()
MachineLearning::publishModel (modelId) [inline]
Publishes a Firebase ML model.
A published model can be downloaded to client apps.
Parameters
modelId - The ID of the model to publish.
Returns
A Promise fulfilled with the published model.
References setPublishStatus().
setPublishStatus()
MachineLearning::setPublishStatus (modelId, publish) [inline]
References client, Model, operation, publish, and state().
signUrl()
MachineLearning::signUrl (unsignedUrl) [inline]
References $, _, a, app(), index_1, machine_learning_utils_1, matches, signUrl(), then, and url.
signUrlIfPresent()
MachineLearning::signUrlIfPresent (options) [inline]
References $, deep_copy_1, machine_learning_api_client_1, machine_learning_utils_1, Promise, signUrl(), upload, and url.
unpublishModel()
MachineLearning::unpublishModel (modelId) [inline]
Unpublishes a Firebase ML model.
Parameters
modelId - The ID of the model to unpublish.
Returns
A Promise fulfilled with the unpublished model.
References setPublishStatus().
updateModel()
MachineLearning::updateModel (modelId, model) [inline]
Updates a model's metadata or model file.
Parameters
modelId - The ID of the model to update.
model - The model fields to update.
Returns
A Promise fulfilled with the updated model.
References client, Model, operation, signUrlIfPresent(), and utils.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/machine-learning/machine-learning.js