InterceptingServerListenerImpl Class Reference
Public Member Functions
constructor (listener, nextListener)
processPendingMessage ()
processPendingHalfClose ()
onReceiveMetadata (metadata)
onReceiveMessage (message)
onReceiveHalfClose ()
onCancel ()
Member Function Documentation
constructor()
InterceptingServerListenerImpl::constructor (listener, nextListener) [inline]
Once the call is cancelled, ignore all other events.
onCancel()
InterceptingServerListenerImpl::onCancel () [inline]
onReceiveHalfClose()
InterceptingServerListenerImpl::onReceiveHalfClose () [inline]
onReceiveMessage()
InterceptingServerListenerImpl::onReceiveMessage (message) [inline]
References message, msg, and processPendingHalfClose().
onReceiveMetadata()
InterceptingServerListenerImpl::onReceiveMetadata (metadata) [inline]
References processPendingHalfClose(), and processPendingMessage().
processPendingHalfClose()
InterceptingServerListenerImpl::processPendingHalfClose () [inline]
processPendingMessage()
InterceptingServerListenerImpl::processPendingMessage () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/server-interceptors.js