EndpointMap Class Reference
Public Member Functions
constructor ()
get size ()
getForSubchannelAddress (address)
deleteMissing (endpoints)
get (endpoint)
set (endpoint, mapEntry)
delete (endpoint)
has (endpoint)
clear ()
* keys ()
* values ()
* entries ()
Member Function Documentation
clear()
EndpointMap::clear () [inline]
References map.
constructor()
EndpointMap::constructor () [inline]
References map, and Set.
delete()
EndpointMap::delete (endpoint) [inline]
References endpointEqualUnordered(), map, and of.
deleteMissing()
EndpointMap::deleteMissing (endpoints) [inline]
Delete any entries in this map with keys that are not in endpoints
Parameters
endpoints
References endpointEqualUnordered(), map, and of.
entries()
* EndpointMap::entries () [inline]
References map, and of.
get()
EndpointMap::get (endpoint) [inline]
References endpointEqualUnordered(), map, of, and undefined.
getForSubchannelAddress()
EndpointMap::getForSubchannelAddress (address) [inline]
References endpointHasAddress, map, of, and undefined.
has()
EndpointMap::has (endpoint) [inline]
References endpointEqualUnordered(), map, and of.
keys()
* EndpointMap::keys () [inline]
References map, and of.
set()
EndpointMap::set (endpoint, mapEntry) [inline]
References endpointEqualUnordered(), map, of, and value.
size()
get EndpointMap::size () [inline]
References map.
values()
* EndpointMap::values () [inline]
References map, and of.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/subchannel-address.js