TestScheduler Class Reference
Public Member Functions
constructor (assertDeepEqual)
createTime (marbles)
createColdObservable (marbles, values, error)
createHotObservable (marbles, values, error)
materializeInnerObservable (observable, outerFrame)
expectObservable (observable, subscriptionMarbles=null)
expectSubscriptions (actualSubscriptionLogs)
flush ()
createAnimator ()
createDelegates ()
run (callback)
constructor (schedulerActionCtor=VirtualAction, maxFrames=Infinity)
flush (action)
schedule (work, delay=0, state)
Static Public Member Functions
static parseMarblesAsSubscriptions (marbles, runMode=false)
static parseMarbles (marbles, values, errorValue, materializeInnerObservables=false, runMode=false)
Member Function Documentation
constructor() [1/2]
TestScheduler::constructor (assertDeepEqual) [inline]
References defaultMaxFrame.
constructor() [2/2]
VirtualTimeScheduler::constructor (schedulerActionCtor = VirtualAction, maxFrames = Infinity) [inline], [inherited]
References frame, and index.
createAnimator()
TestScheduler::createAnimator () [inline]
References Array, callback, handle, Map, map, message, now, of, parseMarbles(), Scheduler::schedule(), test, and undefined.
createColdObservable()
TestScheduler::createColdObservable (marbles, values, error) [inline]
References ColdObservable, error, parseMarbles(), undefined, and values.
createDelegates()
TestScheduler::createDelegates () [inline]
References Array, clearImmediate, handle, interval, Map, now, run(), Scheduler::schedule(), setImmediate, timeout, type, and value.
createHotObservable()
TestScheduler::createHotObservable (marbles, values, error) [inline]
References error, HotObservable, parseMarbles(), undefined, and values.
createTime()
TestScheduler::createTime (marbles) [inline]
References indexOf.
expectObservable()
TestScheduler::expectObservable (observable, subscriptionMarbles = null) [inline]
References COMPLETE_NOTIFICATION, error, errorNotification, frame, materializeInnerObservable(), next(), nextNotification, parseMarbles(), parseMarblesAsSubscriptions(), Scheduler::schedule(), value, and values.
expectSubscriptions()
TestScheduler::expectSubscriptions (actualSubscriptionLogs) [inline]
References parseMarblesAsSubscriptions().
flush() [1/2]
AsyncScheduler::flush (action) [inline], [inherited]
References error.
flush() [2/2]
TestScheduler::flush () [inline]
References test.
materializeInnerObservable()
TestScheduler::materializeInnerObservable (observable, outerFrame) [inline]
References COMPLETE_NOTIFICATION, error, errorNotification, frame, next(), nextNotification, and value.
parseMarbles()
static TestScheduler::parseMarbles (marbles, values, errorValue, materializeInnerObservables = false, runMode = false) [inline], [static]
References $, buffer, c, COMPLETE_NOTIFICATION, count, errorNotification, frame, frameTimeFactor, getValue, i, m, match, ms, nextNotification, s, and values.
parseMarblesAsSubscriptions()
static TestScheduler::parseMarblesAsSubscriptions (marbles, runMode = false) [inline], [static]
References $, buffer, c, count, frame, frameTimeFactor, i, m, match, ms, s, and SubscriptionLog.
run()
TestScheduler::run (callback) [inline]
References animationFrameProvider, callback, createAnimator(), createColdObservable(), createDelegates(), createHotObservable(), createTime(), dateTimestampProvider, expectObservable(), expectSubscriptions(), flush(), immediateProvider, intervalProvider, performanceTimestampProvider, timeoutProvider, and undefined.
schedule()
Scheduler::schedule (work, delay = 0, state) [inline], [inherited]
References delay, and state().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/testing/TestScheduler.js