ComposedCallCredentials Class Reference
Public Member Functions
constructor (creds)
async generateMetadata (options)
compose (other)
_equals (other)
Static Public Member Functions
static createFromMetadataGenerator (metadataGenerator)
static createFromGoogleCredential (googleCredentials)
static createEmpty ()
Member Function Documentation
_equals()
ComposedCallCredentials::_equals (other) [inline]
References index, and value.
compose()
ComposedCallCredentials::compose (other) [inline]
constructor()
ComposedCallCredentials::constructor (creds) [inline]
createEmpty()
static CallCredentials::createEmpty () [inline], [static], [inherited]
createFromGoogleCredential()
static CallCredentials::createFromGoogleCredential (googleCredentials) [inline], [static], [inherited]
Create a gRPC credential from a Google credential object.
Parameters
googleCredentials The authentication client to use.
Returns
The resulting CallCredentials object.
References callback, CallCredentials::createFromMetadataGenerator(), getHeaders, headers, if(), isCurrentOauth2Client(), metadata_1, of, Promise, reject(), and resolve.
createFromMetadataGenerator()
static CallCredentials::createFromMetadataGenerator (metadataGenerator) [inline], [static], [inherited]
Creates a new CallCredentials object from a given function that generates Metadata objects.
Parameters
metadataGenerator A function that accepts a set of options, and generates a Metadata object based on these options, which is passed back to the caller via a supplied (err, metadata) callback.
generateMetadata()
async ComposedCallCredentials::generateMetadata (options) [inline]
References base, metadata_1, of, and Promise.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/call-credentials.js