NodeCrypto Class Reference
Public Member Functions
async sha256DigestBase64 (str)
randomBytesBase64 (count)
async verify (pubkey, data, signature)
async sign (privateKey, data)
decodeBase64StringUtf8 (base64)
encodeBase64StringUtf8 (text)
async sha256DigestHex (str)
async signWithHmacSha256 (key, msg)
Member Function Documentation
decodeBase64StringUtf8()
NodeCrypto::decodeBase64StringUtf8 (base64) [inline]
References base64.
encodeBase64StringUtf8()
NodeCrypto::encodeBase64StringUtf8 (text) [inline]
References text.
randomBytesBase64()
NodeCrypto::randomBytesBase64 (count) [inline]
References count, and crypto.
sha256DigestBase64()
async NodeCrypto::sha256DigestBase64 (str) [inline]
References crypto, and str().
sha256DigestHex()
async NodeCrypto::sha256DigestHex (str) [inline]
Computes the SHA-256 hash of the provided string.
Parameters
str The plain text string to hash.
Returns
A promise that resolves with the SHA-256 hash of the provided string in hexadecimal encoding.
References crypto, and str().
sign()
async NodeCrypto::sign (privateKey, data) [inline]
References crypto, and data.
signWithHmacSha256()
async NodeCrypto::signWithHmacSha256 (key, msg) [inline]
Computes the HMAC hash of a message using the provided crypto key and the SHA-256 algorithm.
Parameters
key The secret crypto key in utf-8 or ArrayBuffer format.
msg The plain text message.
Returns
A promise that resolves with the HMAC-SHA256 hash in ArrayBuffer format.
References crypto, msg, toArrayBuffer(), and toBuffer.
verify()
async NodeCrypto::verify (pubkey, data, signature) [inline]
References crypto, data, signature, and verifier.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/crypto/node/crypto.js