AbortController Class Reference
Public Member Functions
constructor ()
get signal ()
abort ()
Detailed Description
The AbortController.
See also
 https://dom.spec.whatwg.org/#abortcontroller
Member Function Documentation
abort()
AbortController::abort () [inline]
Abort and signal to any observers that the associated activity is to be aborted.
References abortSignal(), and getSignal().
constructor()
AbortController::constructor () [inline]
Initialize this controller.
References createAbortSignal(), and signals.
signal()
get AbortController::signal () [inline]
Returns the AbortSignal object associated with this object.
References getSignal().
The documentation for this class was generated from the following file:
backend/node_modules/abort-controller/dist/abort-controller.js