VectorQuery Class Reference
Public Member Functions
get query ()
async explain (options)
async get ()
_getResponse (explainOptions)
isEqual (other)
Private Member Functions
constructor (_query, _options)
get _rawVectorField ()
get _rawDistanceResultField ()
get _rawQueryVector ()
_stream (transactionId)
toProto (transactionOrReadTime, explainOptions)
_createSnapshot (readTime, size, docs, changes)
startAfter (...fieldValuesOrDocumentSnapshot)
Detailed Description
A query that finds the documents whose vector fields are closest to a certain query vector. Create an instance of VectorQuery with Query.findNearest.
Member Function Documentation
_createSnapshot()
VectorQuery::_createSnapshot (readTime, size, docs, changes) [inline], [private]
Construct the resulting vector snapshot for this query with given documents.
References size, and vector_query_snapshot_1.
_getResponse()
VectorQuery::_getResponse (explainOptions) [inline]
References undefined.
_rawDistanceResultField()
get VectorQuery::_rawDistanceResultField () [inline], [private]
References _options.
_rawQueryVector()
get VectorQuery::_rawQueryVector () [inline], [private]
References _options, and Array.
_rawVectorField()
get VectorQuery::_rawVectorField () [inline], [private]
References _options.
_stream()
VectorQuery::_stream (transactionId) [inline], [private]
Internal streaming method that accepts an optional transaction ID.
Parameters
transactionId - A transaction ID.
constructor()
VectorQuery::constructor (_query, _options) [inline], [private]
References _options, and query_util_1.
explain()
async VectorQuery::explain (options) [inline]
Plans and optionally executes this vector search query. Returns a Promise that will be resolved with the planner information, statistics from the query execution (if any), and the query results (if any).
Returns
A Promise that will be resolved with the planner information, statistics from the query execution (if any), and the query results (if any).
References _getResponse(), query_profile_1, result, and undefined.
get()
async VectorQuery::get () [inline]
Executes this vector search query.
Returns
A promise that will be resolved with the results of the query.
References _getResponse(), and result.
isEqual()
VectorQuery::isEqual (other) [inline]
Compares this object with the given object for equality.
This object is considered "equal" to the other object if and only if other performs the same vector distance search as this VectorQuery and the underlying Query of other compares equal to that of this object using Query.isEqual().
Parameters
other - The object to compare to this object for equality.
Returns
true if this object is "equal" to the given object, as defined above, or false otherwise.
References _rawVectorField(), query(), and util_1.
query()
get VectorQuery::query () [inline]
The query whose results participants in the vector search. Filtering performed by the query will apply before the vector search. Here is the caller graph for this function:
startAfter()
VectorQuery::startAfter (...) [inline], [private]
Construct a new vector query whose result will start after To support stream(). This now throws an exception because cursors are not supported from the backend for vector queries yet.
toProto()
VectorQuery::toProto (transactionOrReadTime, explainOptions) [inline], [private]
Internal method for serializing a query to its proto representation with an optional transaction id.
References _a, _b, _c, _options, Array, field_value_1, limit, path_1, undefined, and value.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/reference/vector-query.js