ResolvingLoadBalancer Class Reference
Public Member Functions
constructor (target, channelControlHelper, credentials, channelOptions, onSuccessfulResolution, onFailedResolution)
updateResolution ()
updateState (connectivityState, picker)
handleResolutionFailure (error)
exitIdle ()
updateAddressList (endpointList, lbConfig)
resetBackoff ()
destroy ()
getTypeName ()
Member Function Documentation
constructor()
ResolvingLoadBalancer::constructor (target, channelControlHelper, credentials, channelOptions, onSuccessfulResolution, onFailedResolution) [inline]
Wrapper class that behaves like a LoadBalancer and also handles name resolution internally.
Parameters
target The address of the backend to connect to.
channelControlHelper ChannelControlHelper instance provided by this load balancer's owner.
defaultServiceConfig The default service configuration to be used if none is provided by the name resolver. A null value indicates that the default behavior should be the default unconfigured behavior. In practice, that means using the "pick first" load balancer implmentation
This resolving load balancer's current connectivity state.
The service config object from the last successful resolution, if available. A value of null indicates that we have not yet received a valid service config from the resolver.
Indicates whether we should attempt to resolve again after the backoff timer runs out.
References _a, backoff_timeout_1, connectivity_state_1, constants_1, credentials, error, getDefaultConfigSelector(), handleResolutionFailure(), JSON, load_balancer_1, load_balancer_child_handler_1, metadata_1, picker_1, resolver_1, service_config_1, serviceConfig, trace, updateResolution(), and updateState().
destroy()
ResolvingLoadBalancer::destroy () [inline]
References connectivity_state_1, and picker_1.
exitIdle()
ResolvingLoadBalancer::exitIdle () [inline]
References connectivity_state_1, and updateResolution().
getTypeName()
ResolvingLoadBalancer::getTypeName () [inline]
handleResolutionFailure()
ResolvingLoadBalancer::handleResolutionFailure (error) [inline]
References connectivity_state_1, error, picker_1, and updateState().
resetBackoff()
ResolvingLoadBalancer::resetBackoff () [inline]
updateAddressList()
ResolvingLoadBalancer::updateAddressList (endpointList, lbConfig) [inline]
updateResolution()
ResolvingLoadBalancer::updateResolution () [inline]
References connectivity_state_1, and updateState().
updateState()
ResolvingLoadBalancer::updateState (connectivityState, picker) [inline]
References connectivity_state_1, picker_1, trace, and uri_parser_1.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/resolving-load-balancer.js