OperatorSubscriber Class Reference
Public Member Functions
constructor (destination, onNext, onComplete, onError, onFinalize, shouldUnsubscribe)
unsubscribe ()
constructor (destination)
next (value)
error (err)
complete ()
_next (value)
_error (err)
_complete ()
add (teardown)
_hasParent (parent)
_addParent (parent)
_removeParent (parent)
remove (teardown)
Static Public Member Functions
static create (next, error, complete)
Member Function Documentation
_addParent()
Subscription::_addParent (parent) [inline], [inherited]
References Array, and parent.
_complete()
Subscriber::_complete () [inline], [inherited]
References Subscriber::unsubscribe().
_error()
Subscriber::_error (err) [inline], [inherited]
References Subscriber::unsubscribe().
_hasParent()
Subscription::_hasParent (parent) [inline], [inherited]
References Array, and parent.
_next()
Subscriber::_next (value) [inline], [inherited]
References value.
_removeParent()
Subscription::_removeParent (parent) [inline], [inherited]
References Array, arrRemove, and parent.
add()
Subscription::add (teardown) [inline], [inherited]
References _a, execFinalizer(), and push.
complete()
Subscriber::complete () [inline], [inherited]
References Subscriber::_complete(), COMPLETE_NOTIFICATION, handleStoppedNotification(), and isStopped().
constructor() [1/2]
OperatorSubscriber::constructor (destination, onNext, onComplete, onError, onFinalize, shouldUnsubscribe) [inline]
References Subscriber::_complete(), _error, Subscriber::_next(), unsubscribe(), and value.
constructor() [2/2]
Subscriber::constructor (destination) [inline], [inherited]
References EMPTY_OBSERVER, isStopped(), and isSubscription.
create()
static Subscriber::create (next, error, complete) [inline], [static], [inherited]
References Subscriber::complete(), error, next(), and SafeSubscriber.
error()
Subscriber::error (err) [inline], [inherited]
References _error, errorNotification, handleStoppedNotification(), and isStopped().
next()
Subscriber::next (value) [inline], [inherited]
References Subscriber::_next(), handleStoppedNotification(), isStopped(), nextNotification, and value.
remove()
Subscription::remove (teardown) [inline], [inherited]
References arrRemove.
unsubscribe()
OperatorSubscriber::unsubscribe () [inline]
References _a.
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/operators/OperatorSubscriber.js