UserRefreshClient Class Reference
Public Member Functions
constructor (optionsOrClientId, clientSecret, refreshToken, eagerRefreshThresholdMillis, forceRefreshOnFailure)
async refreshTokenNoCache (refreshToken)
async fetchIdToken (targetAudience)
fromJSON (json)
fromStream (inputStream, callback)
async fromStreamAsync (inputStream)
Member Function Documentation
constructor()
UserRefreshClient::constructor (optionsOrClientId, clientSecret, refreshToken, eagerRefreshThresholdMillis, forceRefreshOnFailure) [inline]
References credentials, and refreshToken.
fetchIdToken()
async UserRefreshClient::fetchIdToken (targetAudience) [inline]
References data, headers, method, querystring_1, res, and url.
fromJSON()
UserRefreshClient::fromJSON (json) [inline]
Create a UserRefreshClient credentials instance using the given input options.
Parameters
json The input object.
References credentials.
fromStream()
UserRefreshClient::fromStream (inputStream, callback) [inline]
References callback, and fromStreamAsync().
fromStreamAsync()
async UserRefreshClient::fromStreamAsync (inputStream) [inline]
References chunk(), data, fromJSON, JSON, Promise, reject(), resolve, and s.
refreshTokenNoCache()
async UserRefreshClient::refreshTokenNoCache (refreshToken) [inline]
Refreshes the access token.
Parameters
refreshToken An ignored refreshToken..
callback Optional callback.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/refreshclient.js