Asn1SequenceDecoder Class Reference
Public Member Functions
constructor (buffer)
decodeLength ()
unsignedInteger ()
end ()
constructor (buffer)
decodeLength ()
unsignedInteger ()
end ()
Member Function Documentation
constructor() [1/2]
Asn1SequenceDecoder::constructor (buffer) [inline]
References buffer, decodeLength(), and tagSequence.
constructor() [2/2]
Asn1SequenceDecoder::constructor (buffer) [inline]
References buffer, decodeLength(), and tagSequence.
decodeLength() [1/2]
Asn1SequenceDecoder::decodeLength () [inline]
References buffer, i, and length.
decodeLength() [2/2]
Asn1SequenceDecoder::decodeLength () [inline]
References buffer, i, and length.
end() [1/2]
Asn1SequenceDecoder::end () [inline]
References buffer.
end() [2/2]
Asn1SequenceDecoder::end () [inline]
References buffer.
unsignedInteger() [1/2]
Asn1SequenceDecoder::unsignedInteger () [inline]
References buffer, decodeLength(), length, result, and tagInteger.
unsignedInteger() [2/2]
Asn1SequenceDecoder::unsignedInteger () [inline]
References buffer, decodeLength(), length, result, and tagInteger.
The documentation for this class was generated from the following files:
backend/node_modules/jose/dist/node/cjs/runtime/asn1_sequence_decoder.js
backend/node_modules/jose/dist/node/esm/runtime/asn1_sequence_decoder.js