Y18N Class Reference
Public Member Functions
constructor (opts)
__ (...args)
__n ()
setLocale (locale)
getLocale ()
updateLocale (obj)
_taggedLiteral (parts,...args)
_enqueueWrite (work)
_processWriteQueue ()
_readLocaleFile ()
_resolveLocaleFile (directory, locale)
_fileExistsSync (file)
Member Function Documentation
__()
Y18N::__ (...) [inline]
References _enqueueWrite(), _readLocaleFile(), _taggedLiteral(), args, locale, shim, and str().
__n()
Y18N::__n () [inline]
References _enqueueWrite(), _readLocaleFile(), args, Array, locale, plural(), shim, str(), and values.
_enqueueWrite()
Y18N::_enqueueWrite (work) [inline]
References _processWriteQueue().
_fileExistsSync()
Y18N::_fileExistsSync (file) [inline]
References file, and shim.
_processWriteQueue()
Y18N::_processWriteQueue () [inline]
References _resolveLocaleFile(), JSON, locale, and shim.
_readLocaleFile()
Y18N::_readLocaleFile () [inline]
References _resolveLocaleFile(), JSON, locale, and shim.
_resolveLocaleFile()
Y18N::_resolveLocaleFile (directory, locale) [inline]
References _fileExistsSync(), file, locale, and shim.
_taggedLiteral()
Y18N::_taggedLiteral (parts, ...) [inline]
References __, args, concat, i, slice, and str().
constructor()
Y18N::constructor (opts) [inline]
References locale.
getLocale()
Y18N::getLocale () [inline]
References locale.
setLocale()
Y18N::setLocale (locale) [inline]
References locale.
updateLocale()
Y18N::updateLocale (obj) [inline]
References _readLocaleFile(), locale, and obj.
The documentation for this class was generated from the following file:
backend/node_modules/y18n/build/lib/index.js