DnsResolver Class Reference
Public Member Functions
constructor (target, listener, channelOptions)
startResolution ()
async lookup (hostname)
async resolveTxt (hostname)
startNextResolutionTimer ()
stopNextResolutionTimer ()
startResolutionWithBackoff ()
updateResolution ()
destroy ()
Static Public Member Functions
static getDefaultAuthority (target)
Detailed Description
Resolver implementation that handles DNS names and IP addresses.
Member Function Documentation
constructor()
DnsResolver::constructor (target, listener, channelOptions) [inline]
References $, _a, _b, _c, backoff_timeout_1, constants_1, DEFAULT_MIN_TIME_BETWEEN_RESOLUTIONS_MS, dns_1, exports, metadata_1, net_1, startResolutionWithBackoff(), trace, and uri_parser_1.
destroy()
DnsResolver::destroy () [inline]
Reset the resolver to the same state it had when it was created. In-flight DNS requests cannot be cancelled, but they are discarded and their results will be ignored.
References stopNextResolutionTimer().
getDefaultAuthority()
static DnsResolver::getDefaultAuthority (target) [inline], [static]
Get the default authority for the given target. For IP targets, that is the IP address. For DNS targets, it is the hostname.
Parameters
target
lookup()
async DnsResolver::lookup (hostname) [inline]
References all, dns_1, environment_1, map, Promise, reason, result, and trace.
resolveTxt()
async DnsResolver::resolveTxt (hostname) [inline]
References dns_1, environment_1, and trace.
startNextResolutionTimer()
DnsResolver::startNextResolutionTimer () [inline]
References _a, _b, startResolutionWithBackoff(), and stopNextResolutionTimer().
startResolution()
DnsResolver::startResolution () [inline]
If the target is an IP address, just provide that address as a result. Otherwise, initiate A, AAAA, and TXT lookups
References $, config, constants_1, DNS, error, lookup, metadata_1, parse, resolveTxt(), service_config_1, setImmediate, stopNextResolutionTimer(), trace, and uri_parser_1.
startResolutionWithBackoff()
DnsResolver::startResolutionWithBackoff () [inline]
References startNextResolutionTimer(), and startResolution().
stopNextResolutionTimer()
DnsResolver::stopNextResolutionTimer () [inline]
updateResolution()
DnsResolver::updateResolution () [inline]
References startResolutionWithBackoff(), and trace.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/resolver-dns.js