RemoteConfigApiClient Class Reference
Public Member Functions
constructor (app)
getTemplate ()
getTemplateAtVersion (versionNumber)
validateTemplate (template)
publishTemplate (template, options)
rollback (versionNumber)
listVersions (options)
getServerTemplate ()
sendPutRequest (template, etag, validateOnly)
getUrl ()
getProjectIdPrefix ()
toFirebaseError (err)
toRemoteConfigTemplate (resp, customEtag)
toRemoteConfigServerTemplate (resp, customEtag)
validateInputRemoteConfigTemplate (template)
validateVersionNumber (versionNumber, propertyName='versionNumber')
validateEtag (etag)
validateListVersionsOptions (options)
Detailed Description
Class that facilitates sending requests to the Firebase Remote Config backend API.
Member Function Documentation
constructor()
RemoteConfigApiClient::constructor (app) [inline]
References api_request_1, app, FirebaseRemoteConfigError, and validator.
getProjectIdPrefix()
RemoteConfigApiClient::getProjectIdPrefix () [inline]
References $, app, FirebaseRemoteConfigError, Promise, utils, and validator.
getServerTemplate()
RemoteConfigApiClient::getServerTemplate () [inline]
References $, firebase, getUrl(), headers, method, request, server, then, toFirebaseError(), toRemoteConfigServerTemplate(), and url.
getTemplate()
RemoteConfigApiClient::getTemplate () [inline]
References $, getUrl(), headers, method, request, then, toFirebaseError(), toRemoteConfigTemplate(), and url.
getTemplateAtVersion()
RemoteConfigApiClient::getTemplateAtVersion (versionNumber) [inline]
References $, data, getUrl(), headers, method, request, then, toFirebaseError(), toRemoteConfigTemplate(), url, and validateVersionNumber().
getUrl()
RemoteConfigApiClient::getUrl () [inline]
References $, FIREBASE_REMOTE_CONFIG_URL_BASE, getProjectIdPrefix(), and v1.
listVersions()
RemoteConfigApiClient::listVersions (options) [inline]
References $, data, getUrl(), headers, listVersions(), method, request, then, toFirebaseError(), url, and validateListVersionsOptions().
publishTemplate()
RemoteConfigApiClient::publishTemplate (template, options) [inline]
References sendPutRequest(), toFirebaseError(), toRemoteConfigTemplate(), and validateInputRemoteConfigTemplate().
rollback()
RemoteConfigApiClient::rollback (versionNumber) [inline]
References $, data, getUrl(), headers, method, request, rollback(), then, toFirebaseError(), toRemoteConfigTemplate(), url, and validateVersionNumber().
sendPutRequest()
RemoteConfigApiClient::sendPutRequest (template, etag, validateOnly) [inline]
References $, data, etag, getUrl(), headers, method, path, request, url, validateOnly, and version.
toFirebaseError()
RemoteConfigApiClient::toFirebaseError (err) [inline]
References $, and, error, error_1, ERROR_CODE_MAPPING, FirebaseRemoteConfigError, message, response, server, and status.
toRemoteConfigServerTemplate()
RemoteConfigApiClient::toRemoteConfigServerTemplate (resp, customEtag) [inline]
Creates a RemoteConfigServerTemplate from the API response. If provided, customEtag is used instead of the etag returned in the API response.
Parameters
{HttpResponse} resp API response object.
{string} customEtag A custom etag to replace the etag fom the API response (Optional).
References etag, validateEtag(), and version.
toRemoteConfigTemplate()
RemoteConfigApiClient::toRemoteConfigTemplate (resp, customEtag) [inline]
Creates a RemoteConfigTemplate from the API response. If provided, customEtag is used instead of the etag returned in the API response.
Parameters
{HttpResponse} resp API response object.
{string} customEtag A custom etag to replace the etag fom the API response (Optional).
References etag, validateEtag(), and version.
validateEtag()
RemoteConfigApiClient::validateEtag (etag) [inline]
References etag, FirebaseRemoteConfigError, and validator.
validateInputRemoteConfigTemplate()
RemoteConfigApiClient::validateInputRemoteConfigTemplate (template) [inline]
Checks if the given RemoteConfigTemplate object is valid. The object must have valid parameters, parameter groups, conditions, and an etag. Removes output only properties from version metadata.
Parameters
{RemoteConfigTemplate} template A RemoteConfigTemplate object to be validated.
Returns
{RemoteConfigTemplate} The validated RemoteConfigTemplate object.
References $, deep_copy_1, FirebaseRemoteConfigError, JSON, and validator.
validateListVersionsOptions()
RemoteConfigApiClient::validateListVersionsOptions (options) [inline]
Checks if a given ListVersionsOptions object is valid. If successful, creates a copy of the options object and convert startTime and endTime to RFC3339 UTC "Zulu" format, if present.
Parameters
{ListVersionsOptions} options An options object to be validated.
Returns
{ListVersionsOptions} A copy of the provided options object with timestamps converted to UTC Zulu format.
References deep_copy_1, FirebaseRemoteConfigError, validateVersionNumber(), and validator.
validateTemplate()
RemoteConfigApiClient::validateTemplate (template) [inline]
References etag, sendPutRequest(), toFirebaseError(), toRemoteConfigTemplate(), validateEtag(), and validateInputRemoteConfigTemplate().
validateVersionNumber()
RemoteConfigApiClient::validateVersionNumber (versionNumber, propertyName = 'versionNumber') [inline]
Checks if a given version number is valid. A version number must be an integer or a string in int64 format. If valid, returns the string representation of the provided version number.
Parameters
{string|number} versionNumber A version number to be validated.
Returns
{string} The validated version number as a string.
References $, a, an, empty, FirebaseRemoteConfigError, format, int64, or, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/remote-config/remote-config-api-client-internal.js