PropagationAPI Class Reference
Public Member Functions
constructor ()
setGlobalPropagator (propagator)
inject (context, carrier, setter=defaultTextMapSetter)
extract (context, carrier, getter=defaultTextMapGetter)
fields ()
disable ()
_getGlobalPropagator ()
constructor ()
setGlobalPropagator (propagator)
inject (context, carrier, setter=TextMapPropagator_1.defaultTextMapSetter)
extract (context, carrier, getter=TextMapPropagator_1.defaultTextMapGetter)
fields ()
disable ()
_getGlobalPropagator ()
Static Public Member Functions
static getInstance ()
static getInstance ()
Detailed Description
Singleton object which represents the entry point to the OpenTelemetry Propagation API
Member Function Documentation
_getGlobalPropagator() [1/2]
PropagationAPI::_getGlobalPropagator () [inline]
References API_NAME, getGlobal, and NOOP_TEXT_MAP_PROPAGATOR.
_getGlobalPropagator() [2/2]
PropagationAPI::_getGlobalPropagator () [inline]
References API_NAME, global_utils_1, and NOOP_TEXT_MAP_PROPAGATOR.
constructor() [1/2]
PropagationAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
References createBaggage, deleteBaggage, getActiveBaggage, getBaggage, and setBaggage.
constructor() [2/2]
PropagationAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
References context_helpers_1, createBaggage, deleteBaggage, getActiveBaggage, getBaggage, setBaggage, and utils_1.
disable() [1/2]
PropagationAPI::disable () [inline]
Remove the global propagator
References API_NAME, DiagAPI::instance(), and unregisterGlobal.
disable() [2/2]
PropagationAPI::disable () [inline]
Remove the global propagator
References API_NAME, diag_1, and global_utils_1.
extract() [1/2]
PropagationAPI::extract (context, carrier, getter = defaultTextMapGetter) [inline]
Extract context from a carrier
Parameters
context Context which the newly created context will inherit from
carrier Carrier to extract context from
getter Function used to extract keys from a carrier
References _getGlobalPropagator(), and context.
extract() [2/2]
PropagationAPI::extract (context, carrier, getter = TextMapPropagator_1.defaultTextMapGetter) [inline]
Extract context from a carrier
Parameters
context Context which the newly created context will inherit from
carrier Carrier to extract context from
getter Function used to extract keys from a carrier
References _getGlobalPropagator(), and context.
fields() [1/2]
PropagationAPI::fields () [inline]
Return a list of all fields which may be used by the propagator.
References _getGlobalPropagator().
fields() [2/2]
PropagationAPI::fields () [inline]
Return a list of all fields which may be used by the propagator.
References _getGlobalPropagator().
getInstance() [1/2]
static PropagationAPI::getInstance () [inline], [static]
Get the singleton instance of the Propagator API
References PropagationAPI.
getInstance() [2/2]
static PropagationAPI::getInstance () [inline], [static]
Get the singleton instance of the Propagator API
References PropagationAPI.
inject() [1/2]
PropagationAPI::inject (context, carrier, setter = defaultTextMapSetter) [inline]
Inject context into a carrier to be propagated inter-process
Parameters
context Context carrying tracing data to inject
carrier carrier to inject context into
setter Function used to set values on the carrier
References _getGlobalPropagator(), and context.
inject() [2/2]
PropagationAPI::inject (context, carrier, setter = TextMapPropagator_1.defaultTextMapSetter) [inline]
Inject context into a carrier to be propagated inter-process
Parameters
context Context carrying tracing data to inject
carrier carrier to inject context into
setter Function used to set values on the carrier
References _getGlobalPropagator(), and context.
setGlobalPropagator() [1/2]
PropagationAPI::setGlobalPropagator (propagator) [inline]
Set the current propagator.
Returns
true if the propagator was successfully registered, else false
References API_NAME, DiagAPI::instance(), and registerGlobal.
setGlobalPropagator() [2/2]
PropagationAPI::setGlobalPropagator (propagator) [inline]
Set the current propagator.
Returns
true if the propagator was successfully registered, else false
References API_NAME, diag_1, and global_utils_1.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/api/propagation.js
backend/node_modules/@opentelemetry/api/build/src/api/propagation.js