TraceStateImpl Class Reference
Public Member Functions
constructor (rawTraceState)
set (key, value)
unset (key)
get (key)
serialize ()
_parse (rawTraceState)
_keys ()
_clone ()
constructor (rawTraceState)
set (key, value)
unset (key)
get (key)
serialize ()
_parse (rawTraceState)
_keys ()
_clone ()
Detailed Description
TraceState must be a class and not a simple object type because of the spec requirement (https://www.w3.org/TR/trace-context/#tracestate-field).
Here is the list of allowed mutations:
New key-value pair should be added into the beginning of the list
The value of any key can be updated. Modified keys MUST be moved to the beginning of the list.
Member Function Documentation
_clone() [1/2]
TraceStateImpl::_clone () [inline]
References Map, and TraceStateImpl.
_clone() [2/2]
TraceStateImpl::_clone () [inline]
References Map, and TraceStateImpl.
_keys() [1/2]
TraceStateImpl::_keys () [inline]
References Array.
_keys() [2/2]
TraceStateImpl::_keys () [inline]
References Array.
_parse() [1/2]
TraceStateImpl::_parse (rawTraceState) [inline]
References Array, i, LIST_MEMBER_KEY_VALUE_SPLITTER, LIST_MEMBERS_SEPARATOR, Map, MAX_TRACE_STATE_ITEMS, MAX_TRACE_STATE_LEN, validateKey, validateValue, and value.
_parse() [2/2]
TraceStateImpl::_parse (rawTraceState) [inline]
References Array, i, LIST_MEMBER_KEY_VALUE_SPLITTER, LIST_MEMBERS_SEPARATOR, Map, MAX_TRACE_STATE_ITEMS, MAX_TRACE_STATE_LEN, tracestate_validators_1, and value.
constructor() [1/2]
TraceStateImpl::constructor (rawTraceState) [inline]
References _parse, and Map.
constructor() [2/2]
TraceStateImpl::constructor (rawTraceState) [inline]
References _parse, and Map.
get() [1/2]
TraceStateImpl::get (key) [inline]
get() [2/2]
TraceStateImpl::get (key) [inline]
serialize() [1/2]
TraceStateImpl::serialize () [inline]
References _keys(), join, LIST_MEMBER_KEY_VALUE_SPLITTER, and LIST_MEMBERS_SEPARATOR.
serialize() [2/2]
TraceStateImpl::serialize () [inline]
References _keys(), join, LIST_MEMBER_KEY_VALUE_SPLITTER, and LIST_MEMBERS_SEPARATOR.
set() [1/2]
TraceStateImpl::set (key, value) [inline]
References _clone(), and value.
set() [2/2]
TraceStateImpl::set (key, value) [inline]
References _clone(), and value.
unset() [1/2]
TraceStateImpl::unset (key) [inline]
References _clone().
unset() [2/2]
TraceStateImpl::unset (key) [inline]
References _clone().
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/trace/internal/tracestate-impl.js
backend/node_modules/@opentelemetry/api/build/src/trace/internal/tracestate-impl.js