Channel Class Reference
Public Member Functions
constructor (storage, id, resourceId)
stop (callback)
constructor (storage, id, resourceId)
stop (callback)
constructor (eventarc, name, allowedEventTypes)
get eventarc ()
get name ()
publish (events)
constructor (config)
create (optionsOrCallback, callback)
create (optionsOrCallback, callback)
delete (optionsOrCallback, cb)
delete (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
get (optionsOrCallback, cb)
get (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getRequestInterceptors ()
getRequestInterceptors ()
setMetadata (metadata, optionsOrCallback, cb)
setMetadata (metadata, optionsOrCallback, cb)
request_ (reqOpts, callback)
request_ (reqOpts, callback)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
on (eventType, callback, context)
on (eventType, callback, context)
on (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
validateEventType_ (eventType)
validateEventType_ (eventType)
Detailed Description
Eventarc Channel.
Member Function Documentation
constructor() [1/4]
Channel::constructor (eventarc, name, allowedEventTypes) [inline]
References client, eventarc(), eventarc_client_internal_1, eventarc_utils_1, name(), and validator.
constructor() [2/4]
Channel::constructor (storage, id, resourceId) [inline]
References config, methods, parent, and storage.
constructor() [3/4]
Channel::constructor (storage, id, resourceId) [inline]
References config, methods, parent, and storage.
constructor() [4/4]
ServiceObject::constructor (config) [inline], [inherited]
References config, forEach, ServiceObject::getRequestInterceptors(), methods, parent, request, test, and undefined.
create() [1/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
create() [2/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
delete() [1/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util_js_1.
delete() [2/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util.
eventarc()
get Channel::eventarc () [inline]
exists() [1/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util_js_1.
exists() [2/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util.
get() [1/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util_js_1.
get() [2/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util.
getMetadata() [1/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util_js_1.
getMetadata() [2/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util.
getRequestInterceptors() [1/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
getRequestInterceptors() [2/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
name()
get Channel::name () [inline]
The channel name as provided during channel creation. If it was not specifed, the default channel name is returned ('locations/us-central1/channels/firebase'). Here is the caller graph for this function:
off() [1/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [2/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [3/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
on() [1/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [2/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [3/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
publish()
Channel::publish (events) [inline]
Publishes provided events to this channel. If channel was created with allowedEventTypes and event type is not on that list, the event is ignored.
Parameters
events - CloudEvent to publish to the channel.
References client.
request_() [1/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
request_() [2/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
setMetadata() [1/2]
ServiceObject::setMetadata (metadata, optionsOrCallback, cb) [inline], [inherited]
References _a, _b, callback, json, method, methods, qs, res, and util_js_1.
setMetadata() [2/2]
ServiceObject::setMetadata (metadata, optionsOrCallback, cb) [inline], [inherited]
References _a, _b, callback, json, method, methods, qs, res, and util.
stop() [1/2]
Channel::stop (callback) [inline]
References callback, index_js_1, json, method, and request.
stop() [2/2]
Channel::stop (callback) [inline]
References callback, json, method, request, and util.
trigger() [1/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [2/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [3/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
validateEventType_() [1/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References et, and util.
validateEventType_() [2/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
validateEventType_() [3/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/channel.js
backend/node_modules/@google-cloud/storage/build/esm/src/channel.js
backend/node_modules/firebase-admin/lib/eventarc/eventarc.js