Notification Class Reference
Public Member Functions
constructor (kind, value, error)
observe (observer)
do (nextHandler, errorHandler, completeHandler)
accept (nextOrObserver, error, complete)
toObservable ()
constructor (config)
create (optionsOrCallback, callback)
create (optionsOrCallback, callback)
delete (optionsOrCallback, cb)
delete (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
get (optionsOrCallback, cb)
get (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getRequestInterceptors ()
getRequestInterceptors ()
setMetadata (metadata, optionsOrCallback, cb)
setMetadata (metadata, optionsOrCallback, cb)
request_ (reqOpts, callback)
request_ (reqOpts, callback)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
on (eventType, callback, context)
on (eventType, callback, context)
on (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
validateEventType_ (eventType)
validateEventType_ (eventType)
Static Public Member Functions
static createNext (value)
static createError (err)
static createComplete ()
Member Function Documentation
accept()
Notification::accept (nextOrObserver, error, complete) [inline]
References _a, error, isFunction, and observe().
constructor() [1/2]
Notification::constructor (kind, value, error) [inline]
References error, and value.
constructor() [2/2]
ServiceObject::constructor (config) [inline], [inherited]
References config, forEach, ServiceObject::getRequestInterceptors(), methods, parent, request, test, and undefined.
create() [1/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
create() [2/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
createComplete()
static Notification::createComplete () [inline], [static]
createError()
static Notification::createError (err) [inline], [static]
References Notification, and undefined.
createNext()
static Notification::createNext (value) [inline], [static]
References Notification, and value.
delete() [1/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util_js_1.
delete() [2/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util.
do()
Notification::do (nextHandler, errorHandler, completeHandler) [inline]
References error, and value.
exists() [1/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util_js_1.
exists() [2/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util.
get() [1/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util_js_1.
get() [2/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util.
getMetadata() [1/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util_js_1.
getMetadata() [2/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util.
getRequestInterceptors() [1/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
getRequestInterceptors() [2/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
observe()
Notification::observe (observer) [inline]
References observeNotification.
off() [1/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [2/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [3/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
on() [1/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [2/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [3/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
request_() [1/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
request_() [2/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
setMetadata() [1/2]
ServiceObject::setMetadata (metadata, optionsOrCallback, cb) [inline], [inherited]
References _a, _b, callback, json, method, methods, qs, res, and util_js_1.
setMetadata() [2/2]
ServiceObject::setMetadata (metadata, optionsOrCallback, cb) [inline], [inherited]
References _a, _b, callback, json, method, methods, qs, res, and util.
toObservable()
Notification::toObservable () [inline]
References $, EMPTY, error, of, result, throwError, and value.
trigger() [1/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [2/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [3/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
validateEventType_() [1/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References et, and util.
validateEventType_() [2/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
validateEventType_() [3/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/notification.js
backend/node_modules/rxjs/dist/esm/internal/Notification.js