QueryDocumentSnapshot Class Reference
Public Member Functions
 QueryDocumentSnapshot#createTime
The time the document was created.
@type {Timestamp}
@readonly @override
get createTime ()
 QueryDocumentSnapshot#updateTime
The time the document was last updated (at the time the snapshot was generated).
@type {Timestamp}
@readonly @override
get updateTime ()
data ()
 DocumentSnapshot#exists
True if the document exists.
@type {boolean}
@readonly
get exists ()
 DocumentSnapshot#ref
A [DocumentReference]DocumentReference for the document stored in this snapshot.
@type {DocumentReference}
@readonly
get ref ()
 DocumentSnapshot#id
The ID of the document for which this DocumentSnapshot contains data.
@type {string}
@readonly
get id ()
Private Member Functions
constructor (ref, _fieldsProto, readTime, createTime, updateTime)
Static Private Member Functions
static fromObject (ref, obj)
static fromUpdateMap (ref, data)
DocumentSnapshot#readTime
The time this snapshot was read.
@type {Timestamp}
@readonly
get readTime ()
get (field)
isEqual (other)
protoField (field)
toWriteProto ()
toDocumentProto ()
Detailed Description
A QueryDocumentSnapshot contains data read from a document in your Firestore database as part of a query. The document is guaranteed to exist and its data can be extracted with [data()]QueryDocumentSnapshot#data or [get()]DocumentSnapshot#get to get a specific field.
A QueryDocumentSnapshot offers the same API surface as a DocumentSnapshot. Since query results contain only existing documents, the [exists]DocumentSnapshot#exists property will always be true and [data()]QueryDocumentSnapshot#data will never return 'undefined'.
Member Function Documentation
constructor()
DocumentSnapshot::constructor (ref, _fieldsProto, readTime, createTime, updateTime) [inline], [private], [inherited]
References DocumentSnapshot::createTime(), DocumentSnapshot::readTime(), DocumentSnapshot::ref(), and DocumentSnapshot::updateTime().
createTime()
get QueryDocumentSnapshot::createTime () [inline]
data()
QueryDocumentSnapshot::data () [inline]
References data().
exists()
get DocumentSnapshot::exists () [inline], [inherited]
References undefined.
fromObject()
static DocumentSnapshot::fromObject (ref, obj) [inline], [static], [private], [inherited]
Creates a DocumentSnapshot from an object.
References DocumentSnapshot, obj, DocumentSnapshot::ref(), and serializer.
fromUpdateMap()
static DocumentSnapshot::fromUpdateMap (ref, data) [inline], [static], [private], [inherited]
Creates a DocumentSnapshot from an UpdateMap.
This methods expands the top-level field paths in a JavaScript map and turns { foo.bar : foobar } into { foo { bar : foobar }} Merges 'value' at the field path specified by the path array into 'target'.
References assert, DocumentSnapshot::data(), DocumentSnapshot, field_value_1, merge, of, path, DocumentSnapshot::ref(), res, serializer, undefined, util_1, and value.
get()
DocumentSnapshot::get (field) [inline], [inherited]
References path_1, DocumentSnapshot::protoField(), and undefined.
id()
get DocumentSnapshot::id () [inline], [inherited]
isEqual()
DocumentSnapshot::isEqual (other) [inline], [inherited]
Returns true if the document's data and path in this DocumentSnapshot is equal to the provided value.
Parameters
{*} other The value to compare against.
Returns
{boolean} true if this DocumentSnapshot is equal to the provided value.
References deepEqual, and DocumentSnapshot::isEqual().
protoField()
DocumentSnapshot::protoField (field) [inline], [private], [inherited]
Retrieves the field specified by 'fieldPath' in its Protobuf JS representation.
References path_1, and undefined.
readTime()
get DocumentSnapshot::readTime () [inline], [inherited]
References undefined.
ref()
get DocumentSnapshot::ref () [inline], [inherited]
toDocumentProto()
DocumentSnapshot::toDocumentProto () [inline], [private], [inherited]
Convert a document snapshot to the Firestore 'Document' proto.
References _a, _b, DocumentSnapshot::createTime(), name, and DocumentSnapshot::updateTime().
toWriteProto()
DocumentSnapshot::toWriteProto () [inline], [private], [inherited]
Convert a document snapshot to the Firestore 'Write' proto.
References name, and update.
updateTime()
get QueryDocumentSnapshot::updateTime () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/document.js