ReadonlyRestClient Class Reference
Public Member Functions
reportStats (stats)
listen (query, currentHashFn, tag, onComplete)
unlisten (query, tag)
get (query)
refreshAuthToken (token)
restRequest_ (pathString, queryStringParameters={}, callback)
reportStats (stats)
listen (query, currentHashFn, tag, onComplete)
unlisten (query, tag)
get (query)
refreshAuthToken (token)
restRequest_ (pathString, queryStringParameters={}, callback)
reportStats (stats)
listen (query, currentHashFn, tag, onComplete)
unlisten (query, tag)
get (query)
refreshAuthToken (token)
restRequest_ (pathString, queryStringParameters={}, callback)
put (pathString, data, onComplete, hash)
put (pathString, data, onComplete, hash)
put (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
refreshAppCheckToken (token)
refreshAppCheckToken (token)
refreshAppCheckToken (token)
onDisconnectPut (pathString, data, onComplete)
onDisconnectPut (pathString, data, onComplete)
onDisconnectPut (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectCancel (pathString, onComplete)
onDisconnectCancel (pathString, onComplete)
onDisconnectCancel (pathString, onComplete)
Static Public Member Functions
static getListenId_ (query, tag)
static getListenId_ (query, tag)
static getListenId_ (query, tag)
Private Member Functions
constructor (repoInfo_, onDataUpdate_, authTokenProvider_, appCheckTokenProvider_)
constructor (repoInfo_, onDataUpdate_, authTokenProvider_, appCheckTokenProvider_)
constructor (repoInfo_, onDataUpdate_, authTokenProvider_, appCheckTokenProvider_)
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. An implementation of ServerActions that communicates with the server via REST requests. This is mostly useful for compatibility with crawlers, where we don't want to spin up a full persistent connection (using WebSockets or long-polling)
Member Function Documentation
constructor() [1/3]
ReadonlyRestClient::constructor (repoInfo_, onDataUpdate_, authTokenProvider_, appCheckTokenProvider_) [inline], [private]
Parameters
repoInfo_ - Data about the namespace we are connecting to
onDataUpdate_ - A callback for new data from the server
{function(...[*])}
We don't actually need to track listens, except to prevent us calling an onComplete for a listen that's been removed. :-/
References logWrapper.
constructor() [2/3]
ReadonlyRestClient::constructor (repoInfo_, onDataUpdate_, authTokenProvider_, appCheckTokenProvider_) [inline], [private]
Parameters
repoInfo_ - Data about the namespace we are connecting to
onDataUpdate_ - A callback for new data from the server
{function(...[*])}
We don't actually need to track listens, except to prevent us calling an onComplete for a listen that's been removed. :-/
References logWrapper.
constructor() [3/3]
ReadonlyRestClient::constructor (repoInfo_, onDataUpdate_, authTokenProvider_, appCheckTokenProvider_) [inline], [private]
Parameters
repoInfo_ - Data about the namespace we are connecting to
onDataUpdate_ - A callback for new data from the server
{function(...[*])}
We don't actually need to track listens, except to prevent us calling an onComplete for a listen that's been removed. :-/
References logWrapper.
get() [1/3]
ReadonlyRestClient::get (query) [inline]
References data, deferred, error, query, queryParamsToRestQueryStringParameters(), restRequest_(), result, and util.
get() [2/3]
ReadonlyRestClient::get (query) [inline]
References data, Deferred, deferred, error, query, queryParamsToRestQueryStringParameters(), restRequest_(), and result.
get() [3/3]
ReadonlyRestClient::get (query) [inline]
References data, Deferred, deferred, error, query, queryParamsToRestQueryStringParameters(), restRequest_(), and result.
getListenId_() [1/3]
static ReadonlyRestClient::getListenId_ (query, tag) [inline], [static]
References query, undefined, and util.
getListenId_() [2/3]
static ReadonlyRestClient::getListenId_ (query, tag) [inline], [static]
References assert, query, and undefined.
getListenId_() [3/3]
static ReadonlyRestClient::getListenId_ (query, tag) [inline], [static]
References assert, query, and undefined.
listen() [1/3]
ReadonlyRestClient::listen (query, currentHashFn, tag, onComplete) [inline]
@inheritDoc
References data, error, getListenId_(), query, queryParamsToRestQueryStringParameters(), restRequest_(), result, status, and util.
listen() [2/3]
ReadonlyRestClient::listen (query, currentHashFn, tag, onComplete) [inline]
@inheritDoc
References data, error, getListenId_(), query, queryParamsToRestQueryStringParameters(), restRequest_(), result, safeGet, and status.
listen() [3/3]
ReadonlyRestClient::listen (query, currentHashFn, tag, onComplete) [inline]
@inheritDoc
References data, error, getListenId_(), query, queryParamsToRestQueryStringParameters(), restRequest_(), result, safeGet, and status.
merge() [1/3]
ServerActions::merge (pathString, data, onComplete, hash) [inline], [inherited]
merge() [2/3]
ServerActions::merge (pathString, data, onComplete, hash) [inline], [inherited]
merge() [3/3]
ServerActions::merge (pathString, data, onComplete, hash) [inline], [inherited]
onDisconnectCancel() [1/3]
ServerActions::onDisconnectCancel (pathString, onComplete) [inline], [inherited]
onDisconnectCancel() [2/3]
ServerActions::onDisconnectCancel (pathString, onComplete) [inline], [inherited]
onDisconnectCancel() [3/3]
ServerActions::onDisconnectCancel (pathString, onComplete) [inline], [inherited]
onDisconnectMerge() [1/3]
ServerActions::onDisconnectMerge (pathString, data, onComplete) [inline], [inherited]
onDisconnectMerge() [2/3]
ServerActions::onDisconnectMerge (pathString, data, onComplete) [inline], [inherited]
onDisconnectMerge() [3/3]
ServerActions::onDisconnectMerge (pathString, data, onComplete) [inline], [inherited]
onDisconnectPut() [1/3]
ServerActions::onDisconnectPut (pathString, data, onComplete) [inline], [inherited]
onDisconnectPut() [2/3]
ServerActions::onDisconnectPut (pathString, data, onComplete) [inline], [inherited]
onDisconnectPut() [3/3]
ServerActions::onDisconnectPut (pathString, data, onComplete) [inline], [inherited]
put() [1/3]
ServerActions::put (pathString, data, onComplete, hash) [inline], [inherited]
put() [2/3]
ServerActions::put (pathString, data, onComplete, hash) [inline], [inherited]
put() [3/3]
ServerActions::put (pathString, data, onComplete, hash) [inline], [inherited]
refreshAppCheckToken() [1/3]
ServerActions::refreshAppCheckToken (token) [inline], [inherited]
Refreshes the app check token for the current connection.
Parameters
token The app check token
refreshAppCheckToken() [2/3]
ServerActions::refreshAppCheckToken (token) [inline], [inherited]
Refreshes the app check token for the current connection.
Parameters
token The app check token
refreshAppCheckToken() [3/3]
ServerActions::refreshAppCheckToken (token) [inline], [inherited]
Refreshes the app check token for the current connection.
Parameters
token The app check token
refreshAuthToken() [1/3]
ReadonlyRestClient::refreshAuthToken (token) [inline]
@inheritDoc
refreshAuthToken() [2/3]
ReadonlyRestClient::refreshAuthToken (token) [inline]
@inheritDoc
refreshAuthToken() [3/3]
ReadonlyRestClient::refreshAuthToken (token) [inline]
@inheritDoc
reportStats() [1/3]
ReadonlyRestClient::reportStats (stats) [inline]
reportStats() [2/3]
ReadonlyRestClient::reportStats (stats) [inline]
reportStats() [3/3]
ReadonlyRestClient::reportStats (stats) [inline]
restRequest_() [1/3]
ReadonlyRestClient::restRequest_ (pathString, queryStringParameters = {}, callback) [inline]
Performs a REST request to the given path, with the provided query string parameters, and any auth credentials we have. Here is the caller graph for this function:
restRequest_() [2/3]
ReadonlyRestClient::restRequest_ (pathString, queryStringParameters = {}, callback) [inline]
Performs a REST request to the given path, with the provided query string parameters, and any auth credentials we have.
restRequest_() [3/3]
ReadonlyRestClient::restRequest_ (pathString, queryStringParameters = {}, callback) [inline]
Performs a REST request to the given path, with the provided query string parameters, and any auth credentials we have.
unlisten() [1/3]
ReadonlyRestClient::unlisten (query, tag) [inline]
@inheritDoc
References getListenId_(), and query.
unlisten() [2/3]
ReadonlyRestClient::unlisten (query, tag) [inline]
@inheritDoc
References getListenId_(), and query.
unlisten() [3/3]
ReadonlyRestClient::unlisten (query, tag) [inline]
@inheritDoc
References getListenId_(), and query.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js