OAuth2Client Class Reference
Public Member Functions
constructor (optionsOrClientId, clientSecret, redirectUri)
generateAuthUrl (opts={})
generateCodeVerifier ()
async generateCodeVerifierAsync ()
getToken (codeOrOptions, callback)
async getTokenAsync (options)
async refreshTokenNoCache (refreshToken)
refreshAccessToken (callback)
async refreshAccessTokenAsync ()
getAccessToken (callback)
async getAccessTokenAsync ()
async getRequestHeaders (url)
async getRequestMetadataAsync (url)
getRevokeTokenURL (token)
revokeToken (token, callback)
revokeCredentials (callback)
async revokeCredentialsAsync ()
request (opts, callback)
async requestAsync (opts, reAuthRetried=false)
verifyIdToken (options, callback)
async verifyIdTokenAsync (options)
async getTokenInfo (accessToken)
getFederatedSignonCerts (callback)
async getFederatedSignonCertsAsync ()
getIapPublicKeys (callback)
async getIapPublicKeysAsync ()
verifySignedJwtWithCerts ()
async verifySignedJwtWithCertsAsync (jwt, certs, requiredAudience, issuers, maxExpiry)
async processAndValidateRefreshHandler ()
isTokenExpiring ()
Static Public Member Functions
static getRevokeTokenUrl (token)
Private Member Functions
async refreshToken (refreshToken)
Member Function Documentation
constructor()
OAuth2Client::constructor (optionsOrClientId, clientSecret, redirectUri) [inline]
References CertificateFormat, ClientAuthentication, and Map.
generateAuthUrl()
OAuth2Client::generateAuthUrl (opts = {}) [inline]
Generates URL for consent page landing.
Parameters
opts Options.
Returns
URL to consent page.
generateCodeVerifier()
OAuth2Client::generateCodeVerifier () [inline]
generateCodeVerifierAsync()
async OAuth2Client::generateCodeVerifierAsync () [inline]
Convenience method to automatically generate a code_verifier, and its resulting SHA256. If used, this must be paired with a S256 code_challenge_method.
For a full example see: https://github.com/googleapis/google-auth-library-nodejs/blob/main/samples/oauth2-codeVerifier.js
References crypto, crypto_1, and g.
getAccessToken()
OAuth2Client::getAccessToken (callback) [inline]
References callback, getAccessTokenAsync(), and r.
getAccessTokenAsync()
async OAuth2Client::getAccessTokenAsync () [inline]
References credentials, isTokenExpiring(), processAndValidateRefreshHandler(), r, refreshAccessTokenAsync(), res, and token.
getFederatedSignonCerts()
OAuth2Client::getFederatedSignonCerts (callback) [inline]
References callback, getFederatedSignonCertsAsync(), and r.
getFederatedSignonCertsAsync()
async OAuth2Client::getFederatedSignonCertsAsync () [inline]
References $, CertificateFormat, crypto_1, e, format, now, of, res, undefined, and url.
getIapPublicKeys()
OAuth2Client::getIapPublicKeys (callback) [inline]
References callback, getIapPublicKeysAsync(), and r.
getIapPublicKeysAsync()
async OAuth2Client::getIapPublicKeysAsync () [inline]
References $, e, res, and url.
getRequestHeaders()
async OAuth2Client::getRequestHeaders (url) [inline]
The main authentication interface. It takes an optional url which when present is the endpoint being accessed, and returns a Promise which resolves with authorization header fields.
In OAuth2Client, the result has the form: { Authorization: 'Bearer <access_token_value>' }
Parameters
url The optional url being authorized
References getRequestMetadataAsync(), headers, and url.
getRequestMetadataAsync()
async OAuth2Client::getRequestMetadataAsync (url) [inline]
References $, credentials, e, headers, not, processAndValidateRefreshHandler(), r, refreshToken, res, token, and tokens.
getRevokeTokenURL()
OAuth2Client::getRevokeTokenURL (token) [inline]
Generates a URL to revoke the given token.
Parameters
token The existing token to be revoked.
References token, URL, and url.
getRevokeTokenUrl()
static OAuth2Client::getRevokeTokenUrl (token) [inline], [static]
Generates an URL to revoke the given token.
Parameters
token The existing token to be revoked.
Deprecated
Deprecated use instance method OAuth2Client.getRevokeTokenURL
References OAuth2Client, and token.
getToken()
OAuth2Client::getToken (codeOrOptions, callback) [inline]
References callback, e, getTokenAsync(), and r.
getTokenAsync()
async OAuth2Client::getTokenAsync (options) [inline]
References $, basic, ClientAuthentication, data, emit, headers, method, querystring, res, tokens, url, and values.
getTokenInfo()
async OAuth2Client::getTokenInfo (accessToken) [inline]
Obtains information about the provisioned access token. Especially useful if you want to check the scopes that were provisioned to a given token.
Parameters
accessToken Required. The Access Token for which you want to get user info.
References $, data, headers, method, and url.
isTokenExpiring()
OAuth2Client::isTokenExpiring () [inline]
Returns true if a token is expired or will expire within eagerRefreshThresholdMillismilliseconds. If there is no expiry time, assumes the token is not expired or expiring.
References credentials.
processAndValidateRefreshHandler()
async OAuth2Client::processAndValidateRefreshHandler () [inline]
Returns a promise that resolves with AccessTokenResponse type if refreshHandler is defined. If not, nothing is returned. Here is the caller graph for this function:
refreshAccessToken()
OAuth2Client::refreshAccessToken (callback) [inline]
References callback, r, and refreshAccessTokenAsync().
refreshAccessTokenAsync()
async OAuth2Client::refreshAccessTokenAsync () [inline]
References credentials, r, refreshToken, res, and tokens.
refreshToken()
async OAuth2Client::refreshToken (refreshToken) [inline], [private]
Refreshes the access token.
Parameters
refresh_token Existing refresh token.
References e, p, r, refreshToken, and refreshTokenNoCache().
refreshTokenNoCache()
async OAuth2Client::refreshTokenNoCache (refreshToken) [inline]
References _a, data, e, emit, gaxios_1, headers, i, JSON, method, querystring, refreshToken, res, tokens, and url.
request()
OAuth2Client::request (opts, callback) [inline]
References callback, e, r, and requestAsync().
requestAsync()
async OAuth2Client::requestAsync (opts, reAuthRetried = false) [inline]
References credentials, e, getRequestMetadataAsync(), isReadableStream(), processAndValidateRefreshHandler(), r, refreshAccessTokenAsync(), requestAsync(), res, and stream.
revokeCredentials()
OAuth2Client::revokeCredentials (callback) [inline]
References callback, res, and revokeCredentialsAsync().
revokeCredentialsAsync()
async OAuth2Client::revokeCredentialsAsync () [inline]
References credentials, revokeToken(), and token.
revokeToken()
OAuth2Client::revokeToken (token, callback) [inline]
References callback, getRevokeTokenURL(), method, r, token, and url.
verifyIdToken()
OAuth2Client::verifyIdToken (options, callback) [inline]
References callback, r, and verifyIdTokenAsync().
verifyIdTokenAsync()
async OAuth2Client::verifyIdTokenAsync (options) [inline]
References getFederatedSignonCertsAsync(), response, and verifySignedJwtWithCertsAsync().
verifySignedJwtWithCerts()
OAuth2Client::verifySignedJwtWithCerts () [inline]
verifySignedJwtWithCertsAsync()
async OAuth2Client::verifySignedJwtWithCertsAsync (jwt, certs, requiredAudience, issuers, maxExpiry) [inline]
Verify the id token is signed with the correct certificate and is from the correct audience.
Parameters
jwt The jwt to verify (The ID Token in this case).
certs The array of certs to test the jwt against.
requiredAudience The audience to test the jwt against.
issuers The allowed issuers of the jwt (Optional).
maxExpiry The max expiry the certificate can be (Optional).
Returns
Returns a promise resolving to LoginTicket on verification.
References $, Array, cert, crypto, crypto_1, exp, formatEcdsa, isNaN, JSON, jwt, loginticket_1, now, and signature.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/oauth2client.js