ComputeEngineCredential Class Reference
Public Member Functions
constructor (httpAgent)
getAccessToken ()
getIDToken (audience)
getProjectId ()
getServiceAccountEmail ()
buildRequest (urlPath)
Detailed Description
Implementation of Credential that gets access tokens from the metadata service available in the Google Cloud Platform. This authenticates the process as the default service account of an App Engine instance or Google Compute Engine machine.
Member Function Documentation
buildRequest()
ComputeEngineCredential::buildRequest (urlPath) [inline]
References headers, http, method, and url.
constructor()
ComputeEngineCredential::constructor (httpAgent) [inline]
References api_request_1.
getAccessToken()
ComputeEngineCredential::getAccessToken () [inline]
References buildRequest(), GOOGLE_METADATA_SERVICE_TOKEN_PATH, request, and requestAccessToken().
getIDToken()
ComputeEngineCredential::getIDToken (audience) [inline]
getIDToken returns a OIDC token from the compute metadata service that can be used to make authenticated calls to audience
Parameters
audience the URL the returned ID token will be used to call.
References $, buildRequest(), GOOGLE_METADATA_SERVICE_IDENTITY_PATH, request, and requestIDToken().
getProjectId()
ComputeEngineCredential::getProjectId () [inline]
References $, api_request_1, buildRequest(), error_1, getDetailFromResponse(), GOOGLE_METADATA_SERVICE_PROJECT_ID_PATH, project, Promise, and request.
getServiceAccountEmail()
ComputeEngineCredential::getServiceAccountEmail () [inline]
References $, api_request_1, buildRequest(), error_1, getDetailFromResponse(), GOOGLE_METADATA_SERVICE_ACCOUNT_ID_PATH, Promise, and request.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/app/credential-internal.js