CertificateProviderServerCredentials Class Reference
Public Member Functions
constructor (identityCertificateProvider, caCertificateProvider, requireClientCertificate)
_addWatcher (watcher)
_removeWatcher (watcher)
_isSecure ()
_equals (other)
calculateSecureContextOptions ()
finalizeUpdate ()
handleCaCertificateUpdate (update)
handleIdentityCertitificateUpdate (update)
constructor ()
getWatcherCount ()
updateSecureContextOptions (options)
_getSettings ()
_getInterceptors ()
Static Public Member Functions
static createInsecure ()
static createSsl (rootCerts, keyCertPairs, checkClientCertificate=false)
Member Function Documentation
_addWatcher()
CertificateProviderServerCredentials::_addWatcher (watcher) [inline]
References _a, and ServerCredentials::getWatcherCount().
_equals()
CertificateProviderServerCredentials::_equals (other) [inline]
_getInterceptors()
ServerCredentials::_getInterceptors () [inline], [inherited]
_getSettings()
ServerCredentials::_getSettings () [inline], [inherited]
_isSecure()
CertificateProviderServerCredentials::_isSecure () [inline]
_removeWatcher()
CertificateProviderServerCredentials::_removeWatcher (watcher) [inline]
References _a, and ServerCredentials::getWatcherCount().
calculateSecureContextOptions()
CertificateProviderServerCredentials::calculateSecureContextOptions () [inline]
References _a, and cert.
constructor() [1/2]
CertificateProviderServerCredentials::constructor (identityCertificateProvider, caCertificateProvider, requireClientCertificate) [inline]
References handleCaCertificateUpdate(), and handleIdentityCertitificateUpdate().
constructor() [2/2]
ServerCredentials::constructor () [inline], [inherited]
References Set.
createInsecure()
static ServerCredentials::createInsecure () [inline], [static], [inherited]
createSsl()
static ServerCredentials::createSsl (rootCerts, keyCertPairs, checkClientCertificate = false) [inline], [static], [inherited]
References $, _a, a, an, Array, cert, ciphers, i, tls_helpers_1, and undefined.
finalizeUpdate()
CertificateProviderServerCredentials::finalizeUpdate () [inline]
References calculateSecureContextOptions(), and ServerCredentials::updateSecureContextOptions().
getWatcherCount()
ServerCredentials::getWatcherCount () [inline], [inherited]
handleCaCertificateUpdate()
CertificateProviderServerCredentials::handleCaCertificateUpdate (update) [inline]
References finalizeUpdate(), and update.
handleIdentityCertitificateUpdate()
CertificateProviderServerCredentials::handleIdentityCertitificateUpdate (update) [inline]
References finalizeUpdate(), and update.
updateSecureContextOptions()
ServerCredentials::updateSecureContextOptions (options) [inline], [inherited]
References of.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/server-credentials.js