FirebaseIFrameScriptHolder Class Reference
Public Member Functions
constructor (commandCB, onMessageCB, onDisconnect, urlFn)
close ()
startLongPoll (id, pw)
newRequest_ ()
enqueueSegment (segnum, totalsegs, data)
addLongPollTag_ (url, serial)
addTag (url, loadCB)
constructor (commandCB, onMessageCB, onDisconnect, urlFn)
close ()
startLongPoll (id, pw)
newRequest_ ()
enqueueSegment (segnum, totalsegs, data)
addLongPollTag_ (url, serial)
addTag (url, loadCB)
constructor (commandCB, onMessageCB, onDisconnect, urlFn)
close ()
startLongPoll (id, pw)
newRequest_ ()
enqueueSegment (segnum, totalsegs, data)
addLongPollTag_ (url, serial)
addTag (url, loadCB)
Static Public Member Functions
static createIFrame_ ()
static createIFrame_ ()
static createIFrame_ ()
Member Function Documentation
addLongPollTag_() [1/3]
FirebaseIFrameScriptHolder::addLongPollTag_ (url, serial) [inline]
Add a script tag for a regular long-poll request.
Parameters
url - The URL of the script tag.
serial - The serial number of the request.
References addTag(), KEEPALIVE_REQUEST_INTERVAL, newRequest_(), serial, and url.
addLongPollTag_() [2/3]
FirebaseIFrameScriptHolder::addLongPollTag_ (url, serial) [inline]
Add a script tag for a regular long-poll request.
Parameters
url - The URL of the script tag.
serial - The serial number of the request.
References addTag(), KEEPALIVE_REQUEST_INTERVAL, newRequest_(), serial, and url.
addLongPollTag_() [3/3]
FirebaseIFrameScriptHolder::addLongPollTag_ (url, serial) [inline]
Add a script tag for a regular long-poll request.
Parameters
url - The URL of the script tag.
serial - The serial number of the request.
References addTag(), KEEPALIVE_REQUEST_INTERVAL, newRequest_(), serial, and url.
addTag() [1/3]
FirebaseIFrameScriptHolder::addTag (url, loadCB) [inline]
Add an arbitrary script tag to the iframe.
Parameters
url - The URL for the script tag source.
loadCB - A callback to be triggered once the script has loaded.
References close(), e, log, url, and util.
addTag() [2/3]
FirebaseIFrameScriptHolder::addTag (url, loadCB) [inline]
Add an arbitrary script tag to the iframe.
Parameters
url - The URL for the script tag source.
loadCB - A callback to be triggered once the script has loaded.
References close(), e, isNodeSdk, log, and url.
addTag() [3/3]
FirebaseIFrameScriptHolder::addTag (url, loadCB) [inline]
Add an arbitrary script tag to the iframe.
Parameters
url - The URL for the script tag source.
loadCB - A callback to be triggered once the script has loaded.
References close(), e, isNodeSdk, log, and url.
close() [1/3]
FirebaseIFrameScriptHolder::close () [inline]
Cancel all outstanding queries and remove the frame. Here is the caller graph for this function:
close() [2/3]
FirebaseIFrameScriptHolder::close () [inline]
Cancel all outstanding queries and remove the frame.
close() [3/3]
FirebaseIFrameScriptHolder::close () [inline]
Cancel all outstanding queries and remove the frame.
constructor() [1/3]
FirebaseIFrameScriptHolder::constructor (commandCB, onMessageCB, onDisconnect, urlFn) [inline]
Parameters
commandCB - The callback to be called when control commands are received from the server.
onMessageCB - The callback to be triggered when responses arrive from the server.
onDisconnect - The callback to be triggered when this tag holder is closed
urlFn - A function that provides the URL of the endpoint to send data to.
References createIFrame_(), e, FIREBASE_LONGPOLL_COMMAND_CB_NAME, FIREBASE_LONGPOLL_DATA_CB_NAME, log, LUIDGenerator, Set, util, and window.
constructor() [2/3]
FirebaseIFrameScriptHolder::constructor (commandCB, onMessageCB, onDisconnect, urlFn) [inline]
Parameters
commandCB - The callback to be called when control commands are received from the server.
onMessageCB - The callback to be triggered when responses arrive from the server.
onDisconnect - The callback to be triggered when this tag holder is closed
urlFn - A function that provides the URL of the endpoint to send data to.
References createIFrame_(), e, FIREBASE_LONGPOLL_COMMAND_CB_NAME, FIREBASE_LONGPOLL_DATA_CB_NAME, isNodeSdk, log, LUIDGenerator, Set, and window.
constructor() [3/3]
FirebaseIFrameScriptHolder::constructor (commandCB, onMessageCB, onDisconnect, urlFn) [inline]
Parameters
commandCB - The callback to be called when control commands are received from the server.
onMessageCB - The callback to be triggered when responses arrive from the server.
onDisconnect - The callback to be triggered when this tag holder is closed
urlFn - A function that provides the URL of the endpoint to send data to.
References createIFrame_(), e, FIREBASE_LONGPOLL_COMMAND_CB_NAME, FIREBASE_LONGPOLL_DATA_CB_NAME, isNodeSdk, log, LUIDGenerator, Set, and window.
createIFrame_() [1/3]
static FirebaseIFrameScriptHolder::createIFrame_ () [inline], [static]
Each browser has its own funny way to handle iframes. Here we mush them all together into one object that I can actually use.
References a, e, and log.
createIFrame_() [2/3]
static FirebaseIFrameScriptHolder::createIFrame_ () [inline], [static]
Each browser has its own funny way to handle iframes. Here we mush them all together into one object that I can actually use.
References a, e, and log.
createIFrame_() [3/3]
static FirebaseIFrameScriptHolder::createIFrame_ () [inline], [static]
Each browser has its own funny way to handle iframes. Here we mush them all together into one object that I can actually use.
References a, e, and log.
enqueueSegment() [1/3]
FirebaseIFrameScriptHolder::enqueueSegment (segnum, totalsegs, data) [inline]
Queue a packet for transmission to the server.
Parameters
segnum - A sequential id for this packet segment used for reassembly
totalsegs - The total number of segments in this packet
data - The data for this segment.
References d, data, and newRequest_().
enqueueSegment() [2/3]
FirebaseIFrameScriptHolder::enqueueSegment (segnum, totalsegs, data) [inline]
Queue a packet for transmission to the server.
Parameters
segnum - A sequential id for this packet segment used for reassembly
totalsegs - The total number of segments in this packet
data - The data for this segment.
References d, data, and newRequest_().
enqueueSegment() [3/3]
FirebaseIFrameScriptHolder::enqueueSegment (segnum, totalsegs, data) [inline]
Queue a packet for transmission to the server.
Parameters
segnum - A sequential id for this packet segment used for reassembly
totalsegs - The total number of segments in this packet
data - The data for this segment.
References d, data, and newRequest_().
newRequest_() [1/3]
FirebaseIFrameScriptHolder::newRequest_ () [inline]
This is called any time someone might want a script tag to be added. It adds a script tag when there aren't too many outstanding requests and we are still alive.
If there are outstanding packet segments to send, it sends one. If there aren't, it sends a long-poll anyways if needed.
References addLongPollTag_(), FIREBASE_LONGPOLL_DATA_PARAM, FIREBASE_LONGPOLL_ID_PARAM, FIREBASE_LONGPOLL_PW_PARAM, FIREBASE_LONGPOLL_SEGMENT_NUM_PARAM, FIREBASE_LONGPOLL_SEGMENTS_IN_PACKET, FIREBASE_LONGPOLL_SERIAL_PARAM, i, MAX_URL_DATA_SIZE, and SEG_HEADER_SIZE.
newRequest_() [2/3]
FirebaseIFrameScriptHolder::newRequest_ () [inline]
This is called any time someone might want a script tag to be added. It adds a script tag when there aren't too many outstanding requests and we are still alive.
If there are outstanding packet segments to send, it sends one. If there aren't, it sends a long-poll anyways if needed.
References addLongPollTag_(), FIREBASE_LONGPOLL_DATA_PARAM, FIREBASE_LONGPOLL_ID_PARAM, FIREBASE_LONGPOLL_PW_PARAM, FIREBASE_LONGPOLL_SEGMENT_NUM_PARAM, FIREBASE_LONGPOLL_SEGMENTS_IN_PACKET, FIREBASE_LONGPOLL_SERIAL_PARAM, i, MAX_URL_DATA_SIZE, and SEG_HEADER_SIZE.
newRequest_() [3/3]
FirebaseIFrameScriptHolder::newRequest_ () [inline]
This is called any time someone might want a script tag to be added. It adds a script tag when there aren't too many outstanding requests and we are still alive.
If there are outstanding packet segments to send, it sends one. If there aren't, it sends a long-poll anyways if needed.
References addLongPollTag_(), FIREBASE_LONGPOLL_DATA_PARAM, FIREBASE_LONGPOLL_ID_PARAM, FIREBASE_LONGPOLL_PW_PARAM, FIREBASE_LONGPOLL_SEGMENT_NUM_PARAM, FIREBASE_LONGPOLL_SEGMENTS_IN_PACKET, FIREBASE_LONGPOLL_SERIAL_PARAM, i, MAX_URL_DATA_SIZE, and SEG_HEADER_SIZE.
startLongPoll() [1/3]
FirebaseIFrameScriptHolder::startLongPoll (id, pw) [inline]
Actually start the long-polling session by adding the first script tag(s) to the iframe.
Parameters
id - The ID of this connection
pw - The password for this connection
References newRequest_().
startLongPoll() [2/3]
FirebaseIFrameScriptHolder::startLongPoll (id, pw) [inline]
Actually start the long-polling session by adding the first script tag(s) to the iframe.
Parameters
id - The ID of this connection
pw - The password for this connection
References newRequest_().
startLongPoll() [3/3]
FirebaseIFrameScriptHolder::startLongPoll (id, pw) [inline]
Actually start the long-polling session by adding the first script tag(s) to the iframe.
Parameters
id - The ID of this connection
pw - The password for this connection
References newRequest_().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js