SecurityRulesApiClient Class Reference
Public Member Functions
constructor (app)
getRuleset (name)
createRuleset (ruleset)
deleteRuleset (name)
listRulesets (pageSize=100, pageToken)
getRelease (name)
updateOrCreateRelease (name, rulesetName)
updateRelease (name, rulesetName)
createRelease (name, rulesetName)
getUrl ()
getProjectIdPrefix ()
getResource (name)
getReleaseDescription (name, rulesetName)
getRulesetName (name)
sendRequest (request)
toFirebaseError (err)
Detailed Description
Class that facilitates sending requests to the Firebase security rules backend API.
Member Function Documentation
constructor()
SecurityRulesApiClient::constructor (app) [inline]
References api_request_1, app, security_rules_internal_1, and validator.
createRelease()
SecurityRulesApiClient::createRelease (name, rulesetName) [inline]
References $, data, getReleaseDescription(), getUrl(), method, name, release, request, sendRequest(), and url.
createRuleset()
SecurityRulesApiClient::createRuleset (ruleset) [inline]
References $, data, file, getUrl(), JSON, method, of, Promise, request, security_rules_internal_1, sendRequest(), url, and validator.
deleteRuleset()
SecurityRulesApiClient::deleteRuleset (name) [inline]
References $, getRulesetName(), getUrl(), method, name, request, sendRequest(), and url.
getProjectIdPrefix()
SecurityRulesApiClient::getProjectIdPrefix () [inline]
References $, app, Promise, security_rules_internal_1, utils, and validator.
getRelease()
SecurityRulesApiClient::getRelease (name) [inline]
References $, getResource(), and name.
getReleaseDescription()
SecurityRulesApiClient::getReleaseDescription (name, rulesetName) [inline]
References $, getProjectIdPrefix(), getRulesetName(), and name.
getResource()
SecurityRulesApiClient::getResource (name) [inline]
Gets the specified resource from the rules API. Resource names must be the short names without project ID prefix (e.g. rulesets/ruleset-name).
Parameters
{string} name Full qualified name of the resource to get.
Returns
{Promise<T>} A promise that fulfills with the resource.
References $, getUrl(), method, name, request, sendRequest(), and url.
getRuleset()
SecurityRulesApiClient::getRuleset (name) [inline]
References getResource(), getRulesetName(), name, Promise, and then.
getRulesetName()
SecurityRulesApiClient::getRulesetName (name) [inline]
References $, name, security_rules_internal_1, and validator.
getUrl()
SecurityRulesApiClient::getUrl () [inline]
References $, getProjectIdPrefix(), and RULES_V1_API.
listRulesets()
SecurityRulesApiClient::listRulesets (pageSize = 100, pageToken) [inline]
References $, data, getUrl(), method, Promise, request, security_rules_internal_1, sendRequest(), url, and validator.
sendRequest()
SecurityRulesApiClient::sendRequest (request) [inline]
References request, and toFirebaseError().
toFirebaseError()
SecurityRulesApiClient::toFirebaseError (err) [inline]
References $, and, error, error_1, ERROR_CODE_MAPPING, message, response, security_rules_internal_1, server, and status.
updateOrCreateRelease()
SecurityRulesApiClient::updateOrCreateRelease (name, rulesetName) [inline]
References $, createRelease(), error, name, and updateRelease().
updateRelease()
SecurityRulesApiClient::updateRelease (name, rulesetName) [inline]
References $, data, getReleaseDescription(), getUrl(), method, name, release, request, sendRequest(), and url.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/security-rules/security-rules-api-client-internal.js