BaseServerInterceptingCall Class Reference
Public Member Functions
constructor (stream, headers, callEventTracker, handler, options)
handleTimeoutHeader (timeoutHeader)
checkCancelled ()
notifyOnCancel ()
maybeSendMetadata ()
serializeMessage (value)
decompressMessage (message, encoding)
async decompressAndMaybePush (queueEntry)
maybePushNextMessage ()
handleDataFrame (data)
handleEndEvent ()
start (listener)
sendMetadata (metadata)
sendMessage (message, callback)
sendStatus (status)
startRead ()
getPeer ()
getDeadline ()
getHost ()
Member Function Documentation
checkCancelled()
BaseServerInterceptingCall::checkCancelled () [inline]
References notifyOnCancel(), and stream.
constructor()
BaseServerInterceptingCall::constructor (stream, headers, callEventTracker, handler, options) [inline]
References _a, constants_1, data, decoder, GRPC_ACCEPT_ENCODING_HEADER, GRPC_ENCODING_HEADER, GRPC_TIMEOUT_HEADER, handleDataFrame(), handleEndEvent(), handleTimeoutHeader(), headers, http2, JSON, logging, metadata_1, notifyOnCancel(), stream, stream_decoder_1, trace, and TRACER_NAME.
decompressAndMaybePush()
async BaseServerInterceptingCall::decompressAndMaybePush (queueEntry) [inline]
References $, constants_1, decompressMessage(), maybePushNextMessage(), queue, request, sendStatus, and type.
decompressMessage()
BaseServerInterceptingCall::decompressMessage (message, encoding) [inline]
References $, a, chunk(), constants_1, encoding, message, Promise, reject(), resolve, size, and zlib.
getDeadline()
BaseServerInterceptingCall::getDeadline () [inline]
getHost()
BaseServerInterceptingCall::getHost () [inline]
getPeer()
BaseServerInterceptingCall::getPeer () [inline]
References $, _a, and stream.
handleDataFrame()
BaseServerInterceptingCall::handleDataFrame (data) [inline]
References _a, checkCancelled(), constants_1, data, decoder, decompressAndMaybePush(), e, of, sendStatus, stream, trace, and type.
handleEndEvent()
BaseServerInterceptingCall::handleEndEvent () [inline]
References maybePushNextMessage(), and type.
handleTimeoutHeader()
BaseServerInterceptingCall::handleTimeoutHeader (timeoutHeader) [inline]
References $, constants_1, DEADLINE_REGEX, deadlineUnitsToMs, GRPC_TIMEOUT_HEADER, match, now, process, sendStatus, status, timeout, and value.
maybePushNextMessage()
BaseServerInterceptingCall::maybePushNextMessage () [inline]
maybeSendMetadata()
BaseServerInterceptingCall::maybeSendMetadata () [inline]
A server handler can start sending messages without explicitly sending metadata. In that case, we need to send headers before sending any messages. This function does that if necessary.
References metadata_1, and sendMetadata().
notifyOnCancel()
BaseServerInterceptingCall::notifyOnCancel () [inline]
References _a, process, and stream.
sendMessage()
BaseServerInterceptingCall::sendMessage (message, callback) [inline]
References $, _a, callback, checkCancelled(), constants_1, e, error, error_1, max, maybeSendMetadata(), message, response, sendStatus, serializeMessage(), stream, and trace.
sendMetadata()
BaseServerInterceptingCall::sendMetadata (metadata) [inline]
References checkCancelled(), custom, defaultCompressionHeaders, defaultResponseHeaders, defaultResponseOptions, headers, and stream.
sendStatus()
BaseServerInterceptingCall::sendStatus (status) [inline]
References _a, _b, checkCancelled(), constants_1, defaultResponseHeaders, encodeURI, GRPC_MESSAGE_HEADER, GRPC_STATUS_HEADER, notifyOnCancel(), status, stream, and trace.
serializeMessage()
BaseServerInterceptingCall::serializeMessage (value) [inline]
Serialize a message to a length-delimited byte string.
Parameters
value
Returns
References value.
start()
BaseServerInterceptingCall::start (listener) [inline]
References checkCancelled(), and trace.
startRead()
BaseServerInterceptingCall::startRead () [inline]
References checkCancelled(), maybePushNextMessage(), stream, and trace.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/server-interceptors.js