MultiFactorAuthConfig Class Reference
Public Member Functions
constructor (response)
toJSON ()
Static Public Member Functions
static buildServerRequest (options)
static validate (options)
Detailed Description
Defines the multi-factor config class used to convert client side MultiFactorConfig to a format that is understood by the Auth server.
Member Function Documentation
buildServerRequest()
static MultiFactorAuthConfig::buildServerRequest (options) [inline], [static]
Static method to convert a client side request to a MultiFactorAuthServerConfig. Throws an error if validation fails.
Parameters
options - The options object to convert to a server request.
Returns
The resulting server request.
References AUTH_FACTOR_CLIENT_TO_SERVER_TYPE, forEach, request, and validate().
constructor()
MultiFactorAuthConfig::constructor (response) [inline]
The MultiFactorAuthConfig constructor.
Parameters
response - The server side response used to initialize the MultiFactorAuthConfig object. @constructor
References AUTH_FACTOR_SERVER_TO_CLIENT_TYPE, error_1, forEach, response, and state().
toJSON()
MultiFactorAuthConfig::toJSON () [inline]
Converts MultiFactorConfig to JSON object
Returns
The plain object representation of the multi-factor config instance.
References state().
validate()
static MultiFactorAuthConfig::validate (options) [inline], [static]
Validates the MultiFactorConfig options object. Throws an error on failure.
Parameters
options - The options object to validate.
References a, AUTH_FACTOR_CLIENT_TO_SERVER_TYPE, error_1, is, not, state(), type, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/auth-config.js