CompressionFilter Class Reference
Public Member Functions
constructor (channelOptions, sharedFilterConfig)
async sendMetadata (metadata)
receiveMetadata (metadata)
async sendMessage (message)
async receiveMessage (message)
Member Function Documentation
constructor()
CompressionFilter::constructor (channelOptions, sharedFilterConfig) [inline]
There are two possible situations here: 1) We don't have any info yet from the server about what compression it supports In that case we should just use what the client tells us to use 2) We've previously received a response from the server including a grpc-accept-encoding header In that case we only want to use the encoding chosen by the client if the server supports it
References $, _a, _b, _c, compression_algorithms_1, constants_1, getCompressionHandler(), grpc, isCompressionAlgorithmKey, logging, undefined, and value.
receiveMessage()
async CompressionFilter::receiveMessage (message) [inline]
References message.
receiveMetadata()
CompressionFilter::receiveMetadata (metadata) [inline]
References encoding, and getCompressionHandler().
sendMessage()
async CompressionFilter::sendMessage (message) [inline]
References $, _a, a, compress(), constants_1, message, send, and size.
sendMetadata()
async CompressionFilter::sendMetadata (metadata) [inline]
References headers.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/compression-filter.js