BundleExecutor Class Reference
Public Member Functions
constructor (bundleOptions, bundleDescriptor)
schedule (apiCall, request, callback)
Private Member Functions
_maybeClearTimeout (bundleId)
_cancel (id)
_runNow (bundleId)
Detailed Description
BundleExecutor stores several timers for each bundle (calls are bundled based on the options passed, each bundle has unique ID that is calculated based on field values). Each timer fires and sends a call after certain amount of time, and if a new request comes to the same bundle, the timer can be restarted.
Member Function Documentation
_cancel()
BundleExecutor::_cancel (id) [inline], [private]
Cancels an event.
Parameters
{String} id - The id for the event in the task.
References _maybeClearTimeout().
_maybeClearTimeout()
BundleExecutor::_maybeClearTimeout (bundleId) [inline], [private]
Clears scheduled timeout if it exists.
Parameters
{String} bundleId - the id for the task whose timeout needs to be cleared.
_runNow()
BundleExecutor::_runNow (bundleId) [inline], [private]
Invokes a task.
Parameters
{String} bundleId - The id for the task.
References $, _maybeClearTimeout(), and warnings_1.
constructor()
BundleExecutor::constructor (bundleOptions, bundleDescriptor) [inline]
Organizes requests for an api service that requires to bundle them.
Parameters
{BundleOptions} bundleOptions - configures strategy this instance uses when executing bundled functions.
{BundleDescriptor} bundleDescriptor - the description of the bundling. @constructor
References _options.
schedule()
BundleExecutor::schedule (apiCall, request, callback) [inline]
Schedule a method call.
Parameters
{function} apiCall - the function for an API call.
{Object} request - the request object to be bundled with others.
{APICallback} callback - the callback to be called when the method finished.
Returns
{function()} - the function to cancel the scheduled invocation.
References $, _options, _runNow(), bundlingUtils_1, callback, error, googleError_1, JSON, message, noop(), not, obj, Request, request, status_1, task_1, undefined, and warnings_1.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js