FirestoreClient Class Reference
Public Member Functions
constructor (opts, gaxInstance)
initialize ()
get apiEndpoint ()
get universeDomain ()
getProjectId (callback)
getDocument (request, optionsOrCallback, callback)
updateDocument (request, optionsOrCallback, callback)
deleteDocument (request, optionsOrCallback, callback)
beginTransaction (request, optionsOrCallback, callback)
commit (request, optionsOrCallback, callback)
rollback (request, optionsOrCallback, callback)
batchWrite (request, optionsOrCallback, callback)
createDocument (request, optionsOrCallback, callback)
batchGetDocuments (request, options)
runQuery (request, options)
runAggregationQuery (request, options)
write (options)
listen (options)
listDocuments (request, optionsOrCallback, callback)
listDocumentsStream (request, options)
listDocumentsAsync (request, options)
partitionQuery (request, optionsOrCallback, callback)
partitionQueryStream (request, options)
partitionQueryAsync (request, options)
listCollectionIds (request, optionsOrCallback, callback)
listCollectionIdsStream (request, options)
listCollectionIdsAsync (request, options)
getLocation (request, options, callback)
listLocationsAsync (request, options)
close ()
constructor (opts, gaxInstance)
initialize ()
get apiEndpoint ()
get universeDomain ()
getProjectId (callback)
getDocument (request, optionsOrCallback, callback)
updateDocument (request, optionsOrCallback, callback)
deleteDocument (request, optionsOrCallback, callback)
beginTransaction (request, optionsOrCallback, callback)
commit (request, optionsOrCallback, callback)
rollback (request, optionsOrCallback, callback)
batchWrite (request, optionsOrCallback, callback)
createDocument (request, optionsOrCallback, callback)
batchGetDocuments (request, options)
runQuery (request, options)
write (options)
listen (options)
listDocuments (request, optionsOrCallback, callback)
listDocumentsStream (request, options)
listDocumentsAsync (request, options)
partitionQuery (request, optionsOrCallback, callback)
partitionQueryStream (request, options)
partitionQueryAsync (request, options)
listCollectionIds (request, optionsOrCallback, callback)
listCollectionIdsStream (request, options)
listCollectionIdsAsync (request, options)
close ()
Static Public Member Functions
static get servicePath ()
static get apiEndpoint ()
static get port ()
static get scopes ()
static get servicePath ()
static get apiEndpoint ()
static get port ()
static get scopes ()
Detailed Description
The Cloud Firestore service.
Cloud Firestore is a fast, fully managed, serverless, cloud-native NoSQL document database that simplifies storing, syncing, and querying data for your mobile, web, and IoT apps at global scale. Its client libraries provide live synchronization and offline support, while its security features and integrations with Firebase and Google Cloud Platform accelerate building truly serverless apps.
The Cloud Firestore service.
Cloud Firestore is a fast, fully managed, serverless, cloud-native NoSQL document database that simplifies storing, syncing, and querying data for your mobile, web, and IoT apps at global scale. Its client libraries provide live synchronization and offline support, while its security features and integrations with Firebase and Google Cloud Platform (GCP) accelerate building truly serverless apps.
Deprecated
Deprecated Use v1/firestore_client instead.
Member Function Documentation
apiEndpoint() [1/4]
static get FirestoreClient::apiEndpoint () [inline], [static]
The DNS address for this API service - same as servicePath.
Deprecated
Deprecated Use the apiEndpoint method of the client instance.
Returns
{string} The DNS address for this service.
References process.
apiEndpoint() [2/4]
get FirestoreClient::apiEndpoint () [inline]
The DNS address for this API service.
Returns
{string} The DNS address for this service.
apiEndpoint() [3/4]
static get FirestoreClient::apiEndpoint () [inline], [static]
The DNS address for this API service - same as servicePath.
Deprecated
Deprecated Use the apiEndpoint method of the client instance.
Returns
{string} The DNS address for this service.
References process.
apiEndpoint() [4/4]
get FirestoreClient::apiEndpoint () [inline]
The DNS address for this API service.
Returns
{string} The DNS address for this service.
batchGetDocuments() [1/2]
FirestoreClient::batchGetDocuments (request, options) [inline]
References _a, database, initialize(), and request.
batchGetDocuments() [2/2]
FirestoreClient::batchGetDocuments (request, options) [inline]
References _a, database, initialize(), and request.
batchWrite() [1/2]
FirestoreClient::batchWrite (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
batchWrite() [2/2]
FirestoreClient::batchWrite (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
beginTransaction() [1/2]
FirestoreClient::beginTransaction (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
beginTransaction() [2/2]
FirestoreClient::beginTransaction (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
close() [1/2]
FirestoreClient::close () [inline]
Terminate the gRPC channel and close the client.
The client will no longer be usable and all future behavior is undefined.
Returns
{Promise} A promise that resolves when the client is closed.
References Promise.
close() [2/2]
FirestoreClient::close () [inline]
Terminate the gRPC channel and close the client.
The client will no longer be usable and all future behavior is undefined.
Returns
{Promise} A promise that resolves when the client is closed.
References Promise.
commit() [1/2]
FirestoreClient::commit (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
commit() [2/2]
FirestoreClient::commit (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
constructor() [1/2]
FirestoreClient::constructor (opts, gaxInstance) [inline]
Construct an instance of FirestoreClient.
Parameters
{object} [options] - The configuration object. The options accepted by the constructor are described in detail in this document. The common options are:
{object} [options.credentials] - Credentials object.
{string} [options.credentials.client_email]
{string} [options.credentials.private_key]
{string} [options.email] - Account email address. Required when using a .pem or .p12 keyFilename.
{string} [options.keyFilename] - Full path to the a .json, .pem, or .p12 key downloaded from the Google Developers Console. If you provide a path to a JSON file, the projectId option below is not necessary. NOTE: .pem and .p12 require you to specify options.email as well.
{number} [options.port] - The port on which to connect to the remote host.
{string} [options.projectId] - The project ID from the Google Developer's Console, e.g. 'grape-spaceship-123'. We will also check the environment variable GCLOUD_PROJECT for your project ID. If your app is running in an environment which supports Application Default Credentials, your project ID will be detected automatically.
{string} [options.apiEndpoint] - The domain name of the API remote host.
{gax.ClientConfig} [options.clientConfig] - Client configuration override. Follows the structure of gapicConfig.
{boolean} [options.fallback] - Use HTTP/1.1 REST mode. For more information, please check the documentation.
{gax} [gaxInstance]: loaded instance of google-gax. Useful if you need to avoid loading the default gRPC version and want to use the fallback HTTP implementation. Load only fallback version and pass it to the constructor: const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC const client = new FirestoreClient({fallback: true}, gax);
References $, _a, _b, _c, _d, auth, batchGetDocuments(), constructor, fallback, gapicConfig, gax, grpc, jsonProtos, listCollectionIds(), listDocuments(), listen, node, partitionQuery(), port(), process, require(), rest(), runAggregationQuery(), runQuery(), servicePath(), stream, undefined, version, warn, window, and write.
constructor() [2/2]
FirestoreClient::constructor (opts, gaxInstance) [inline]
Construct an instance of FirestoreClient.
Parameters
{object} [options] - The configuration object. The options accepted by the constructor are described in detail in this document. The common options are:
{object} [options.credentials] - Credentials object.
{string} [options.credentials.client_email]
{string} [options.credentials.private_key]
{string} [options.email] - Account email address. Required when using a .pem or .p12 keyFilename.
{string} [options.keyFilename] - Full path to the a .json, .pem, or .p12 key downloaded from the Google Developers Console. If you provide a path to a JSON file, the projectId option below is not necessary. NOTE: .pem and .p12 require you to specify options.email as well.
{number} [options.port] - The port on which to connect to the remote host.
{string} [options.projectId] - The project ID from the Google Developer's Console, e.g. 'grape-spaceship-123'. We will also check the environment variable GCLOUD_PROJECT for your project ID. If your app is running in an environment which supports Application Default Credentials, your project ID will be detected automatically.
{string} [options.apiEndpoint] - The domain name of the API remote host.
{gax.ClientConfig} [options.clientConfig] - Client configuration override. Follows the structure of gapicConfig.
{boolean} [options.fallback] - Use HTTP/1.1 REST mode. For more information, please check the documentation.
{gax} [gaxInstance]: loaded instance of google-gax. Useful if you need to avoid loading the default gRPC version and want to use the fallback HTTP implementation. Load only fallback version and pass it to the constructor: const gax = require('google-gax/build/src/fallback'); // avoids loading google-gax with gRPC const client = new FirestoreClient({fallback: true}, gax);
References $, _a, _b, _c, _d, auth, batchGetDocuments(), constructor, fallback, gapicConfig, gax, grpc, jsonProtos, listCollectionIds(), listDocuments(), listen, node, partitionQuery(), port(), process, require(), rest(), runQuery(), servicePath(), stream, undefined, version, warn, window, and write.
createDocument() [1/2]
FirestoreClient::createDocument (request, optionsOrCallback, callback) [inline]
References _a, _b, callback, initialize(), parent, request, and undefined.
createDocument() [2/2]
FirestoreClient::createDocument (request, optionsOrCallback, callback) [inline]
References _a, _b, callback, initialize(), parent, request, and undefined.
deleteDocument() [1/2]
FirestoreClient::deleteDocument (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), name, request, and undefined.
deleteDocument() [2/2]
FirestoreClient::deleteDocument (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), name, request, and undefined.
getDocument() [1/2]
FirestoreClient::getDocument (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), name, request, and undefined.
getDocument() [2/2]
FirestoreClient::getDocument (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), name, request, and undefined.
getLocation()
FirestoreClient::getLocation (request, options, callback) [inline]
References callback, and request.
getProjectId() [1/2]
FirestoreClient::getProjectId (callback) [inline]
Return the project ID used by this class.
Returns
{Promise} A promise that resolves to string containing the project ID.
References auth, and callback.
getProjectId() [2/2]
FirestoreClient::getProjectId (callback) [inline]
Return the project ID used by this class.
Returns
{Promise} A promise that resolves to string containing the project ID.
References auth, and callback.
initialize() [1/2]
FirestoreClient::initialize () [inline]
Initialize the client. Performs asynchronous operations (such as authentication) and prepares the client. This function will be called automatically when any class method is called for the first time, but if you need to initialize it before calling an actual method, feel free to call initialize() directly.
You can await on this method if you want to make sure the client is initialized.
Returns
{Promise} A promise that resolves to an authenticated service stub.
References args, descriptor, func, of, Promise, setImmediate, stream, stream_1, and undefined.
initialize() [2/2]
FirestoreClient::initialize () [inline]
Initialize the client. Performs asynchronous operations (such as authentication) and prepares the client. This function will be called automatically when any class method is called for the first time, but if you need to initialize it before calling an actual method, feel free to call initialize() directly.
You can await on this method if you want to make sure the client is initialized.
Returns
{Promise} A promise that resolves to an authenticated service stub.
References args, descriptor, func, of, Promise, setImmediate, stream, stream_1, and undefined.
listCollectionIds() [1/2]
FirestoreClient::listCollectionIds (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), parent, request, and undefined.
listCollectionIds() [2/2]
FirestoreClient::listCollectionIds (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), parent, request, and undefined.
listCollectionIdsAsync() [1/2]
FirestoreClient::listCollectionIdsAsync (request, options) [inline]
References _a, initialize(), parent, and request.
listCollectionIdsAsync() [2/2]
FirestoreClient::listCollectionIdsAsync (request, options) [inline]
References _a, initialize(), parent, and request.
listCollectionIdsStream() [1/2]
FirestoreClient::listCollectionIdsStream (request, options) [inline]
Equivalent to method.name.toCamelCase(), but returns a NodeJS Stream object.
Parameters
{Object} request The request object that will be sent.
{string} request.parent Required. The parent document. In the format: projects/{project_id}/databases/{database_id}/documents/{document_path}. For example: projects/my-project/databases/my-database/documents/chatrooms/my-chatroom
{number} request.pageSize The maximum number of results to return.
{string} request.pageToken A page token. Must be a value from protos.google.firestore.v1.ListCollectionIdsResponse|ListCollectionIdsResponse.
{google.protobuf.Timestamp} request.readTime Reads documents as they were at the given time.
This must be a microsecond precision timestamp within the past one hour, or if Point-in-Time Recovery is enabled, can additionally be a whole minute timestamp within the past 7 days.
Parameters
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Stream} An object stream which emits an object representing string on 'data' event. The client library will perform auto-pagination by default: it will call the API as many times as needed. Note that it can affect your quota. We recommend using listCollectionIdsAsync() method described below for async iteration which you can stop as needed. Please see the | documentation for more details and examples.
References _a, initialize(), parent, and request.
listCollectionIdsStream() [2/2]
FirestoreClient::listCollectionIdsStream (request, options) [inline]
Equivalent to method.name.toCamelCase(), but returns a NodeJS Stream object.
Parameters
{Object} request The request object that will be sent.
{string} request.parent Required. The parent document. In the format: projects/{project_id}/databases/{database_id}/documents/{document_path}. For example: projects/my-project/databases/my-database/documents/chatrooms/my-chatroom
{number} request.pageSize The maximum number of results to return.
{string} request.pageToken A page token. Must be a value from protos.google.firestore.v1beta1.ListCollectionIdsResponse|ListCollectionIdsResponse.
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Stream} An object stream which emits an object representing string on 'data' event. The client library will perform auto-pagination by default: it will call the API as many times as needed. Note that it can affect your quota. We recommend using listCollectionIdsAsync() method described below for async iteration which you can stop as needed. Please see the | documentation for more details and examples.
References _a, initialize(), parent, and request.
listDocuments() [1/2]
FirestoreClient::listDocuments (request, optionsOrCallback, callback) [inline]
References _a, _b, callback, initialize(), parent, request, and undefined.
listDocuments() [2/2]
FirestoreClient::listDocuments (request, optionsOrCallback, callback) [inline]
References _a, _b, callback, initialize(), parent, request, and undefined.
listDocumentsAsync() [1/2]
FirestoreClient::listDocumentsAsync (request, options) [inline]
References _a, _b, initialize(), parent, and request.
listDocumentsAsync() [2/2]
FirestoreClient::listDocumentsAsync (request, options) [inline]
References _a, _b, initialize(), parent, and request.
listDocumentsStream() [1/2]
FirestoreClient::listDocumentsStream (request, options) [inline]
Equivalent to method.name.toCamelCase(), but returns a NodeJS Stream object.
Parameters
{Object} request The request object that will be sent.
{string} request.parent Required. The parent resource name. In the format: projects/{project_id}/databases/{database_id}/documents or projects/{project_id}/databases/{database_id}/documents/{document_path}.
For example: projects/my-project/databases/my-database/documents or projects/my-project/databases/my-database/documents/chatrooms/my-chatroom
Parameters
{string} [request.collectionId] Optional. The collection ID, relative to parent, to list.
For example: chatrooms or messages.
This is optional, and when not provided, Firestore will list documents from all collections under the provided parent.
Parameters
{number} [request.pageSize] Optional. The maximum number of documents to return in a single response.
Firestore may return fewer than this value.
Parameters
{string} [request.pageToken] Optional. A page token, received from a previous ListDocuments response.
Provide this to retrieve the subsequent page. When paginating, all other parameters (with the exception of page_size) must match the values set in the request that generated the page token.
Parameters
{string} [request.orderBy] Optional. The optional ordering of the documents to return.
For example: priority desc, __name__ desc.
This mirrors the ORDER BY used in Firestore queries but in a string representation. When absent, documents are ordered based on __name__ ASC.
Parameters
{google.firestore.v1.DocumentMask} [request.mask] Optional. The fields to return. If not set, returns all fields.
If a document has a field that is not present in this mask, that field will not be returned in the response.
Parameters
{Buffer} request.transaction Perform the read as part of an already active transaction.
{google.protobuf.Timestamp} request.readTime Perform the read at the provided time.
This must be a microsecond precision timestamp within the past one hour, or if Point-in-Time Recovery is enabled, can additionally be a whole minute timestamp within the past 7 days.
Parameters
{boolean} request.showMissing If the list should show missing documents.
A document is missing if it does not exist, but there are sub-documents nested underneath it. When true, such missing documents will be returned with a key but will not have fields, create_time, or update_time set.
Requests with show_missing may not specify where or order_by.
Parameters
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Stream} An object stream which emits an object representing protos.google.firestore.v1.Document|Document on 'data' event. The client library will perform auto-pagination by default: it will call the API as many times as needed. Note that it can affect your quota. We recommend using listDocumentsAsync() method described below for async iteration which you can stop as needed. Please see the | documentation for more details and examples.
References _a, _b, initialize(), parent, and request.
listDocumentsStream() [2/2]
FirestoreClient::listDocumentsStream (request, options) [inline]
Equivalent to method.name.toCamelCase(), but returns a NodeJS Stream object.
Parameters
{Object} request The request object that will be sent.
{string} request.parent Required. The parent resource name. In the format: projects/{project_id}/databases/{database_id}/documents or projects/{project_id}/databases/{database_id}/documents/{document_path}. For example: projects/my-project/databases/my-database/documents or projects/my-project/databases/my-database/documents/chatrooms/my-chatroom
{string} request.collectionId Required. The collection ID, relative to parent, to list. For example: chatrooms or messages.
{number} request.pageSize The maximum number of documents to return.
{string} request.pageToken The next_page_token value returned from a previous List request, if any.
{string} request.orderBy The order to sort results by. For example: priority desc, name.
{google.firestore.v1beta1.DocumentMask} request.mask The fields to return. If not set, returns all fields.
If a document has a field that is not present in this mask, that field will not be returned in the response.
Parameters
{Buffer} request.transaction Reads documents in a transaction.
{google.protobuf.Timestamp} request.readTime Reads documents as they were at the given time. This may not be older than 270 seconds.
{boolean} request.showMissing If the list should show missing documents. A missing document is a document that does not exist but has sub-documents. These documents will be returned with a key but will not have fields, protos.google.firestore.v1beta1.Document.create_time|Document.create_time, or protos.google.firestore.v1beta1.Document.update_time|Document.update_time set.
Requests with show_missing may not specify where or order_by.
Parameters
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Stream} An object stream which emits an object representing protos.google.firestore.v1beta1.Document|Document on 'data' event. The client library will perform auto-pagination by default: it will call the API as many times as needed. Note that it can affect your quota. We recommend using listDocumentsAsync() method described below for async iteration which you can stop as needed. Please see the | documentation for more details and examples.
References _a, _b, initialize(), parent, and request.
listen() [1/2]
FirestoreClient::listen (options) [inline]
References initialize().
listen() [2/2]
FirestoreClient::listen (options) [inline]
References initialize().
listLocationsAsync()
FirestoreClient::listLocationsAsync (request, options) [inline]
References request.
partitionQuery() [1/2]
FirestoreClient::partitionQuery (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), parent, request, and undefined.
partitionQuery() [2/2]
FirestoreClient::partitionQuery (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), parent, request, and undefined.
partitionQueryAsync() [1/2]
FirestoreClient::partitionQueryAsync (request, options) [inline]
References _a, initialize(), parent, and request.
partitionQueryAsync() [2/2]
FirestoreClient::partitionQueryAsync (request, options) [inline]
References _a, initialize(), parent, and request.
partitionQueryStream() [1/2]
FirestoreClient::partitionQueryStream (request, options) [inline]
Equivalent to method.name.toCamelCase(), but returns a NodeJS Stream object.
Parameters
{Object} request The request object that will be sent.
{string} request.parent Required. The parent resource name. In the format: projects/{project_id}/databases/{database_id}/documents. Document resource names are not supported; only database resource names can be specified.
{google.firestore.v1.StructuredQuery} request.structuredQuery A structured query. Query must specify collection with all descendants and be ordered by name ascending. Other filters, order bys, limits, offsets, and start/end cursors are not supported.
{number} request.partitionCount The desired maximum number of partition points. The partitions may be returned across multiple pages of results. The number must be positive. The actual number of partitions returned may be fewer.
For example, this may be set to one fewer than the number of parallel queries to be run, or in running a data pipeline job, one fewer than the number of workers or compute instances available.
Parameters
{string} request.pageToken The next_page_token value returned from a previous call to PartitionQuery that may be used to get an additional set of results. There are no ordering guarantees between sets of results. Thus, using multiple sets of results will require merging the different result sets.
For example, two subsequent calls using a page_token may return:
cursor B, cursor M, cursor Q
cursor A, cursor U, cursor W
To obtain a complete result set ordered with respect to the results of the query supplied to PartitionQuery, the results sets should be merged: cursor A, cursor B, cursor M, cursor Q, cursor U, cursor W
Parameters
{number} request.pageSize The maximum number of partitions to return in this call, subject to partition_count.
For example, if partition_count = 10 and page_size = 8, the first call to PartitionQuery will return up to 8 partitions and a next_page_token if more results exist. A second call to PartitionQuery will return up to 2 partitions, to complete the total of 10 specified in partition_count.
Parameters
{google.protobuf.Timestamp} request.readTime Reads documents as they were at the given time.
This must be a microsecond precision timestamp within the past one hour, or if Point-in-Time Recovery is enabled, can additionally be a whole minute timestamp within the past 7 days.
Parameters
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Stream} An object stream which emits an object representing protos.google.firestore.v1.Cursor|Cursor on 'data' event. The client library will perform auto-pagination by default: it will call the API as many times as needed. Note that it can affect your quota. We recommend using partitionQueryAsync() method described below for async iteration which you can stop as needed. Please see the | documentation for more details and examples.
References _a, initialize(), parent, and request.
partitionQueryStream() [2/2]
FirestoreClient::partitionQueryStream (request, options) [inline]
Equivalent to method.name.toCamelCase(), but returns a NodeJS Stream object.
Parameters
{Object} request The request object that will be sent.
{string} request.parent Required. The parent resource name. In the format: projects/{project_id}/databases/{database_id}/documents. Document resource names are not supported; only database resource names can be specified.
{google.firestore.v1beta1.StructuredQuery} request.structuredQuery A structured query. Query must specify collection with all descendants and be ordered by name ascending. Other filters, order bys, limits, offsets, and start/end cursors are not supported.
{number} request.partitionCount The desired maximum number of partition points. The partitions may be returned across multiple pages of results. The number must be positive. The actual number of partitions returned may be fewer.
For example, this may be set to one fewer than the number of parallel queries to be run, or in running a data pipeline job, one fewer than the number of workers or compute instances available.
Parameters
{string} request.pageToken The next_page_token value returned from a previous call to PartitionQuery that may be used to get an additional set of results. There are no ordering guarantees between sets of results. Thus, using multiple sets of results will require merging the different result sets.
For example, two subsequent calls using a page_token may return:
cursor B, cursor M, cursor Q
cursor A, cursor U, cursor W
To obtain a complete result set ordered with respect to the results of the query supplied to PartitionQuery, the results sets should be merged: cursor A, cursor B, cursor M, cursor Q, cursor U, cursor W
Parameters
{number} request.pageSize The maximum number of partitions to return in this call, subject to partition_count.
For example, if partition_count = 10 and page_size = 8, the first call to PartitionQuery will return up to 8 partitions and a next_page_token if more results exist. A second call to PartitionQuery will return up to 2 partitions, to complete the total of 10 specified in partition_count.
Parameters
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Stream} An object stream which emits an object representing protos.google.firestore.v1beta1.Cursor|Cursor on 'data' event. The client library will perform auto-pagination by default: it will call the API as many times as needed. Note that it can affect your quota. We recommend using partitionQueryAsync() method described below for async iteration which you can stop as needed. Please see the | documentation for more details and examples.
References _a, initialize(), parent, and request.
port() [1/2]
static get FirestoreClient::port () [inline], [static]
The port for this API service.
Returns
{number} The default port for this service.
port() [2/2]
static get FirestoreClient::port () [inline], [static]
The port for this API service.
Returns
{number} The default port for this service.
rollback() [1/2]
FirestoreClient::rollback (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
rollback() [2/2]
FirestoreClient::rollback (request, optionsOrCallback, callback) [inline]
References _a, callback, database, initialize(), request, and undefined.
runAggregationQuery()
FirestoreClient::runAggregationQuery (request, options) [inline]
References _a, initialize(), parent, and request.
runQuery() [1/2]
FirestoreClient::runQuery (request, options) [inline]
References _a, initialize(), parent, and request.
runQuery() [2/2]
FirestoreClient::runQuery (request, options) [inline]
References _a, initialize(), parent, and request.
scopes() [1/2]
static get FirestoreClient::scopes () [inline], [static]
The scopes needed to make gRPC calls for every method defined in this service.
Returns
{string[]} List of default scopes.
scopes() [2/2]
static get FirestoreClient::scopes () [inline], [static]
The scopes needed to make gRPC calls for every method defined in this service.
Returns
{string[]} List of default scopes.
servicePath() [1/2]
static get FirestoreClient::servicePath () [inline], [static]
The DNS address for this API service.
Deprecated
Deprecated Use the apiEndpoint method of the client instance.
Returns
{string} The DNS address for this service.
References process.
servicePath() [2/2]
static get FirestoreClient::servicePath () [inline], [static]
The DNS address for this API service.
Deprecated
Deprecated Use the apiEndpoint method of the client instance.
Returns
{string} The DNS address for this service.
References process.
universeDomain() [1/2]
get FirestoreClient::universeDomain () [inline]
universeDomain() [2/2]
get FirestoreClient::universeDomain () [inline]
updateDocument() [1/2]
FirestoreClient::updateDocument (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), request, and undefined.
updateDocument() [2/2]
FirestoreClient::updateDocument (request, optionsOrCallback, callback) [inline]
References _a, callback, initialize(), request, and undefined.
write() [1/2]
FirestoreClient::write (options) [inline]
References initialize().
write() [2/2]
FirestoreClient::write (options) [inline]
References initialize().
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js
backend/node_modules/@google-cloud/firestore/build/src/v1beta1/firestore_client.js