BaseExternalAccountClient Class Reference
Public Member Functions
constructor (options, additionalOptions)
getServiceAccountEmail ()
setCredentials (credentials)
async getAccessToken ()
async getRequestHeaders ()
request (opts, callback)
async getProjectId ()
async requestAsync (opts, reAuthRetried=false)
async refreshAccessTokenAsync ()
getProjectNumber (audience)
async getImpersonatedAccessToken (token)
isExpired (accessToken)
getScopesArray ()
getMetricsHeaderValue ()
Detailed Description
Base external account client. This is used to instantiate AuthClients for exchanging external account credentials for GCP access token and authorizing requests to GCP APIs. The base class implements common logic for exchanging various type of external credentials for GCP access token. The logic of determining and retrieving the external credential based on the environment and credential_source will be left for the subclasses.
Member Function Documentation
constructor()
BaseExternalAccountClient::constructor (options, additionalOptions) [inline]
Instantiate a BaseExternalAccountClient instance using the provided JSON object loaded from an external account credentials file.
Parameters
options The external account options object typically loaded from the external account JSON credential file. The camelCased options are aliases for the snake_cased options.
additionalOptions DEPRECATED, all options are available in the options parameter. Optional additional behavior customization options. These currently customize expiration threshold time and whether to retry on 401/403 API request errors.
A pending access token request. Used for concurrent calls.
References _a, _BaseExternalAccountClient_instances, _BaseExternalAccountClient_pendingAccessToken, DEFAULT_OAUTH_SCOPE, DEFAULT_TOKEN_URL, exports, getProjectNumber(), https, if(), sts, type, URL, and util_1.
getAccessToken()
async BaseExternalAccountClient::getAccessToken () [inline]
Returns
A promise that resolves with the current GCP access token response. If the current credential is expired, a new one is retrieved.
References isExpired(), refreshAccessTokenAsync(), res, and token.
getImpersonatedAccessToken()
async BaseExternalAccountClient::getImpersonatedAccessToken (token) [inline]
Exchanges an external account GCP access token for a service account impersonated access token using iamcredentials GenerateAccessToken API.
Parameters
token The access token to exchange for a service account access token.
Returns
A promise that resolves with the service account impersonated credentials response.
References $, data, getScopesArray(), headers, method, res, response, token, and url.
getMetricsHeaderValue()
BaseExternalAccountClient::getMetricsHeaderValue () [inline]
References $, auth, config, node, nodeVersion, pkg, process, source, undefined, and v.
getProjectId()
async BaseExternalAccountClient::getProjectId () [inline]
Returns
A promise that resolves with the project ID corresponding to the current workload identity pool or current workforce pool if determinable. For workforce pool credential, it returns the project ID corresponding to the workforcePoolUserProject. This is introduced to match the current pattern of using the Auth library: const projectId = await auth.getProjectId(); const url = https://dns.googleapis.com/dns/v1/projects/${projectId}; const res = await client.request({ url }); The resource may not have permission (resourcemanager.projects.get) to call this API or the required scopes may not be selected: https://cloud.google.com/resource-manager/reference/rest/v1/projects/get#authorization-scopes
References $, getRequestHeaders(), headers, response, and url.
getProjectNumber()
BaseExternalAccountClient::getProjectNumber (audience) [inline]
Returns the workload identity pool project number if it is determinable from the audience resource name.
Parameters
audience The STS audience used to determine the project number.
Returns
The project number associated with the workload identity pool, if this can be determined from the STS audience field. Otherwise, null is returned.
References match.
getRequestHeaders()
async BaseExternalAccountClient::getRequestHeaders () [inline]
The main authentication interface. It takes an optional url which when present is the endpoint being accessed, and returns a Promise which resolves with authorization header fields.
The result has the form: { Authorization: 'Bearer <access_token_value>' }
References $, getAccessToken(), and headers.
getScopesArray()
BaseExternalAccountClient::getScopesArray () [inline]
Returns
The list of scopes for the requested GCP access token.
References DEFAULT_OAUTH_SCOPE.
getServiceAccountEmail()
BaseExternalAccountClient::getServiceAccountEmail () [inline]
The service account email to be impersonated, if available. Prevents DOS attacks.
See also
https://github.com/googleapis/google-auth-library-nodejs/security/code-scanning/84
References $, _a, is, re, result, and URL.
isExpired()
BaseExternalAccountClient::isExpired (accessToken) [inline]
Returns whether the provided credentials are expired or not. If there is no expiry time, assumes the token is not expired or expiring.
Parameters
accessToken The credentials to check for expiration.
Returns
Whether the credentials are expired or not.
References now.
refreshAccessTokenAsync()
async BaseExternalAccountClient::refreshAccessTokenAsync () [inline]
Forces token refresh, even if unexpired tokens are currently cached. External credentials are exchanged for GCP access tokens via the token exchange endpoint and other settings provided in the client options object. If the service_account_impersonation_url is provided, an additional step to exchange the external account GCP access token for a service account impersonated token is performed.
Returns
A promise that resolves with the fresh GCP access tokens.
References __classPrivateFieldGet, __classPrivateFieldSet, _BaseExternalAccountClient_instances, _BaseExternalAccountClient_internalRefreshAccessTokenAsync, _BaseExternalAccountClient_pendingAccessToken, and call.
request()
BaseExternalAccountClient::request (opts, callback) [inline]
References callback, e, r, and requestAsync().
requestAsync()
async BaseExternalAccountClient::requestAsync (opts, reAuthRetried = false) [inline]
Authenticates the provided HTTP request, processes it and resolves with the returned response.
Parameters
opts The HTTP request options.
reAuthRetried Whether the current attempt is a retry after a failed attempt due to an auth failure.
Returns
A promise that resolves with the successful response.
References e, getRequestHeaders(), isReadableStream(), refreshAccessTokenAsync(), requestAsync(), res, response, and stream.
setCredentials()
BaseExternalAccountClient::setCredentials (credentials) [inline]
Provides a mechanism to inject GCP access tokens directly. When the provided credential expires, a new credential, using the external account options, is retrieved.
Parameters
credentials The Credentials object to set on the current client.
References credentials.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/baseexternalclient.js