OnlineMonitor Class Reference
Public Member Functions
constructor ()
getInitialEvent (eventType)
currentlyOnline ()
constructor ()
getInitialEvent (eventType)
currentlyOnline ()
constructor ()
getInitialEvent (eventType)
currentlyOnline ()
constructor (allowedEvents_)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
on (eventType, callback, context)
on (eventType, callback, context)
on (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
validateEventType_ (eventType)
validateEventType_ (eventType)
Static Public Member Functions
static getInstance ()
static getInstance ()
static getInstance ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Monitors online state (as reported by window.online/offline events).
The expectation is that this could have many false positives (thinks we are online when we're not), but no false negatives. So we can safely use it to determine when we definitely cannot reach the internet.
Member Function Documentation
constructor() [1/4]
EventEmitter::constructor (allowedEvents_) [inline], [inherited]
References Array, and util.
constructor() [2/4]
OnlineMonitor::constructor () [inline]
References EventEmitter::trigger(), util, and window.
constructor() [3/4]
OnlineMonitor::constructor () [inline]
References isMobileCordova, EventEmitter::trigger(), and window.
constructor() [4/4]
OnlineMonitor::constructor () [inline]
References isMobileCordova, EventEmitter::trigger(), and window.
currentlyOnline() [1/3]
OnlineMonitor::currentlyOnline () [inline]
currentlyOnline() [2/3]
OnlineMonitor::currentlyOnline () [inline]
currentlyOnline() [3/3]
OnlineMonitor::currentlyOnline () [inline]
getInitialEvent() [1/3]
OnlineMonitor::getInitialEvent (eventType) [inline]
References util.
getInitialEvent() [2/3]
OnlineMonitor::getInitialEvent (eventType) [inline]
References assert.
getInitialEvent() [3/3]
OnlineMonitor::getInitialEvent (eventType) [inline]
References assert.
getInstance() [1/3]
static OnlineMonitor::getInstance () [inline], [static]
getInstance() [2/3]
static OnlineMonitor::getInstance () [inline], [static]
getInstance() [3/3]
static OnlineMonitor::getInstance () [inline], [static]
off() [1/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [2/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [3/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
on() [1/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [2/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [3/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
trigger() [1/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [2/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [3/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
validateEventType_() [1/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References et, and util.
validateEventType_() [2/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
validateEventType_() [3/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js