SecurityRules Class Reference
Public Member Functions
constructor (app)
getRuleset (name)
getFirestoreRuleset ()
releaseFirestoreRulesetFromSource (source)
releaseFirestoreRuleset (ruleset)
getStorageRuleset (bucket)
releaseStorageRulesetFromSource (source, bucket)
releaseStorageRuleset (ruleset, bucket)
createRulesFileFromSource (name, source)
createRuleset (file)
deleteRuleset (name)
listRulesetMetadata (pageSize=100, nextPageToken)
getRulesetForRelease (releaseName)
releaseRuleset (ruleset, releaseName)
getBucketName (bucket)
Detailed Description
The Firebase SecurityRules service interface.
Member Function Documentation
constructor()
SecurityRules::constructor (app) [inline]
Parameters
app - The app for this SecurityRules service. @constructor
References app, client, and security_rules_api_client_internal_1.
createRuleset()
SecurityRules::createRuleset (file) [inline]
Creates a new Ruleset from the given RulesFile.
Parameters
file - Rules file to include in the new Ruleset.
Returns
A promise that fulfills with the newly created Ruleset.
References client, file, Ruleset, and source.
createRulesFileFromSource()
SecurityRules::createRulesFileFromSource (name, source) [inline]
References name, security_rules_internal_1, source, and validator.
deleteRuleset()
SecurityRules::deleteRuleset (name) [inline]
Deletes the Ruleset identified by the given name. The input name should be the short name string without the project ID prefix. For example, to delete the projects/project-id/rulesets/my-ruleset, pass the short name "my-ruleset". Rejects with a not-found error if the specified Ruleset cannot be found.
Parameters
name - Name of the Ruleset to delete.
Returns
A promise that fulfills when the Ruleset is deleted.
References client, and name.
getBucketName()
SecurityRules::getBucketName (bucket) [inline]
References app, security_rules_internal_1, and validator.
getFirestoreRuleset()
SecurityRules::getFirestoreRuleset () [inline]
Gets the Ruleset currently applied to Cloud Firestore. Rejects with a not-found error if no ruleset is applied on Firestore.
Returns
A promise that fulfills with the Firestore ruleset.
References getRulesetForRelease().
getRuleset()
SecurityRules::getRuleset (name) [inline]
Gets the Ruleset identified by the given name. The input name should be the short name string without the project ID prefix. For example, to retrieve the projects/project-id/rulesets/my-ruleset, pass the short name "my-ruleset". Rejects with a not-found error if the specified Ruleset cannot be found.
Parameters
name - Name of the Ruleset to retrieve.
Returns
A promise that fulfills with the specified Ruleset.
References client, name, and Ruleset.
getRulesetForRelease()
SecurityRules::getRulesetForRelease (releaseName) [inline]
References $, client, getRuleset(), name, not, release, security_rules_internal_1, stripProjectIdPrefix(), and validator.
getStorageRuleset()
SecurityRules::getStorageRuleset (bucket) [inline]
Gets the Ruleset currently applied to a Cloud Storage bucket. Rejects with a not-found error if no ruleset is applied on the bucket.
Parameters
bucket - Optional name of the Cloud Storage bucket to be retrieved. If not specified, retrieves the ruleset applied on the default bucket configured via AppOptions.
Returns
A promise that fulfills with the Cloud Storage ruleset.
References $, getBucketName(), getRulesetForRelease(), Promise, and then.
listRulesetMetadata()
SecurityRules::listRulesetMetadata (pageSize = 100, nextPageToken) [inline]
Retrieves a page of ruleset metadata.
Parameters
pageSize - The page size, 100 if undefined. This is also the maximum allowed limit.
nextPageToken - The next page token. If not specified, returns rulesets starting without any offset.
Returns
A promise that fulfills with a page of rulesets.
References client, response, and RulesetMetadataList.
releaseFirestoreRuleset()
SecurityRules::releaseFirestoreRuleset (ruleset) [inline]
Applies the specified Ruleset ruleset to Cloud Firestore.
Parameters
ruleset - Name of the ruleset to apply or a RulesetMetadata object containing the name.
Returns
A promise that fulfills when the ruleset is released.
References releaseRuleset().
releaseFirestoreRulesetFromSource()
SecurityRules::releaseFirestoreRulesetFromSource (source) [inline]
Creates a new Ruleset from the given source, and applies it to Cloud Firestore.
Parameters
source - Rules source to apply.
Returns
A promise that fulfills when the ruleset is created and released.
References createRuleset(), createRulesFileFromSource(), Promise, releaseFirestoreRuleset(), source, and then.
releaseRuleset()
SecurityRules::releaseRuleset (ruleset, releaseName) [inline]
References client, Promise, security_rules_internal_1, and validator.
releaseStorageRuleset()
SecurityRules::releaseStorageRuleset (ruleset, bucket) [inline]
Applies the specified Ruleset ruleset to a Cloud Storage bucket.
Parameters
ruleset - Name of the ruleset to apply or a RulesetMetadata object containing the name.
bucket - Optional name of the Cloud Storage bucket to apply the rules on. If not specified, applies the ruleset on the default bucket configured via firebase-admin.app#AppOptions.
Returns
A promise that fulfills when the ruleset is released.
References $, getBucketName(), Promise, releaseRuleset(), and then.
releaseStorageRulesetFromSource()
SecurityRules::releaseStorageRulesetFromSource (source, bucket) [inline]
Creates a new Ruleset from the given source, and applies it to a Cloud Storage bucket.
Parameters
source - Rules source to apply.
bucket - Optional name of the Cloud Storage bucket to apply the rules on. If not specified, applies the ruleset on the default bucket configured via firebase-admin.app#AppOptions.
Returns
A promise that fulfills when the ruleset is created and released.
References createRuleset(), createRulesFileFromSource(), getBucketName(), Promise, releaseStorageRuleset(), source, and then.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/security-rules/security-rules.js