EventarcApiClient Class Reference
Public Member Functions
constructor (app, channel)
getProjectId ()
async publish (events)
async publishToEventarcApi (channel, events)
sendRequest (request)
toFirebaseError (err)
resolveChannelName (name)
async resolveChannelNameProjectId (location, channelId)
getEventarcHost ()
Detailed Description
Class that facilitates sending requests to the Eventarc backend API.
Member Function Documentation
constructor()
EventarcApiClient::constructor (app, channel) [inline]
References api_request_1, app, eventarc_utils_1, resolveChannelName(), and validator.
getEventarcHost()
EventarcApiClient::getEventarcHost () [inline]
References EVENTARC_API, and process.
getProjectId()
EventarcApiClient::getProjectId () [inline]
References app, eventarc_utils_1, Promise, utils, and validator.
publish()
async EventarcApiClient::publish (events) [inline]
Publishes provided events to this channel. If channel was created with allowedEventsTypes and event type is not on that list, the event is ignored.
The following CloudEvent fields are auto-populated if not set:
specversion - 1.0
id - uuidv4()
source - populated with process.env.EVENTARC_CLOUD_EVENT_SOURCE and if not set an error is thrown.
Parameters
events - CloudEvent to publish to the channel.
References Array, e, eventarc_utils_1, filter, and publishToEventarcApi().
publishToEventarcApi()
async EventarcApiClient::publishToEventarcApi (channel, events) [inline]
References $, data, getEventarcHost(), JSON, method, request, sendRequest(), and url.
resolveChannelName()
EventarcApiClient::resolveChannelName (name) [inline]
References $, CHANNEL_NAME_REGEX, DEFAULT_CHANNEL_REGION, eventarc_utils_1, location, match, name, Promise, resolveChannelNameProjectId(), and validator.
resolveChannelNameProjectId()
async EventarcApiClient::resolveChannelNameProjectId (location, channelId) [inline]
References $, getProjectId(), and location.
sendRequest()
EventarcApiClient::sendRequest (request) [inline]
References request, toFirebaseError(), and undefined.
toFirebaseError()
EventarcApiClient::toFirebaseError (err) [inline]
References $, and, error_1, eventarc_utils_1, response, and status.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/eventarc/eventarc-client-internal.js