GeoPoint Class Reference
Public Member Functions
constructor (latitude, longitude)
 GeoPoint#latitude
The latitude as a number between -90 and 90.
@type {number}
@readonly
get latitude ()
GeoPoint#longitude
The longitude as a number between -180 and 180.
@type {number}
@readonly
get longitude ()
isEqual (other)
toProto ()
static fromProto (proto)
Detailed Description
An immutable object representing a geographic location in Firestore. The location is represented as a latitude/longitude pair.
Member Function Documentation
constructor()
GeoPoint::constructor (latitude, longitude) [inline]
References latitude(), longitude(), and validate_1.
fromProto()
static GeoPoint::fromProto (proto) [inline], [static], [private]
Converts a google.type.LatLng proto to its GeoPoint representation.
References GeoPoint, and proto.
isEqual()
GeoPoint::isEqual (other) [inline]
Returns true if this GeoPoint is equal to the provided value.
Parameters
{*} other The value to compare against.
Returns
{boolean} true if this GeoPoint is equal to the provided value.
References latitude().
latitude()
get GeoPoint::latitude () [inline]
longitude()
get GeoPoint::longitude () [inline]
toProto()
GeoPoint::toProto () [inline], [private]
Converts the GeoPoint to a google.type.LatLng proto.
References latitude(), and longitude().
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/geo-point.js