BaseAuth Class Reference
Public Member Functions
constructor (app, authRequestHandler, tokenGenerator)
createCustomToken (uid, developerClaims)
verifyIdToken (idToken, checkRevoked=false)
getUser (uid)
getUserByEmail (email)
getUserByPhoneNumber (phoneNumber)
getUserByProviderUid (providerId, uid)
getUsers (identifiers)
listUsers (maxResults, pageToken)
createUser (properties)
deleteUser (uid)
deleteUsers (uids)
updateUser (uid, properties)
setCustomUserClaims (uid, customUserClaims)
revokeRefreshTokens (uid)
importUsers (users, options)
createSessionCookie (idToken, sessionCookieOptions)
verifySessionCookie (sessionCookie, checkRevoked=false)
generatePasswordResetLink (email, actionCodeSettings)
generateEmailVerificationLink (email, actionCodeSettings)
generateVerifyAndChangeEmailLink (email, newEmail, actionCodeSettings)
generateSignInWithEmailLink (email, actionCodeSettings)
listProviderConfigs (options)
getProviderConfig (providerId)
deleteProviderConfig (providerId)
updateProviderConfig (providerId, updatedConfig)
createProviderConfig (config)
_verifyAuthBlockingToken (token, audience)
verifyDecodedJWTNotRevokedOrDisabled (decodedIdToken, revocationErrorInfo)
Detailed Description
Common parent interface for both Auth and TenantAwareAuth APIs.
Member Function Documentation
_verifyAuthBlockingToken()
BaseAuth::_verifyAuthBlockingToken (token, audience) [inline]
@alpha
References auth_api_request_1, and token.
constructor()
BaseAuth::constructor (app, authRequestHandler, tokenGenerator) [inline]
The BaseAuth class constructor.
Parameters
app - The FirebaseApp to associate with this Auth instance.
authRequestHandler - The RPC request handler for this instance.
tokenGenerator - Optional token generator. If not specified, a (non-tenant-aware) instance will be created. Use this paramter to specify a tenant-aware tokenGenerator. @constructor
References app, createFirebaseTokenGenerator, and token_verifier_1.
createCustomToken()
BaseAuth::createCustomToken (uid, developerClaims) [inline]
Creates a new Firebase custom token (JWT) that can be sent back to a client device to use to sign in with the client SDKs' signInWithCustomToken() methods. (Tenant-aware instances will also embed the tenant ID in the token.)
See | Create Custom Tokens for code samples and detailed documentation.
Parameters
uid - The uid to use as the custom token's subject.
developerClaims - Optional additional claims to include in the custom token's payload.
Returns
A promise fulfilled with a custom token for the provided uid and payload.
createProviderConfig()
BaseAuth::createProviderConfig (config) [inline]
Returns a promise that resolves with the newly created AuthProviderConfig when the new provider configuration is created.
SAML and OIDC provider support requires Google Cloud's Identity Platform (GCIP). To learn more about GCIP, including pricing and features, see the | GCIP documentation.
Parameters
config - The provider configuration to create.
Returns
A promise that resolves with the created provider configuration.
References auth_config_1, config, error_1, Promise, response, and validator.
createSessionCookie()
BaseAuth::createSessionCookie (idToken, sessionCookieOptions) [inline]
Creates a new Firebase session cookie with the specified options. The created JWT string can be set as a server-side session cookie with a custom cookie policy, and be used for session management. The session cookie JWT will have the same payload claims as the provided ID token.
See | Manage Session Cookies for code samples and detailed documentation.
Parameters
idToken - The Firebase ID token to exchange for a session cookie.
sessionCookieOptions - The session cookie options which includes custom session duration.
Returns
A promise that resolves on success with the created session cookie.
References error_1, Promise, and validator.
createUser()
BaseAuth::createUser (properties) [inline]
Creates a new user.
See | Create a user for code samples and detailed documentation.
Parameters
properties - The properties to set on the new user record to be created.
Returns
A promise fulfilled with the user data corresponding to the newly created user.
References error, error_1, and getUser().
deleteProviderConfig()
BaseAuth::deleteProviderConfig (providerId) [inline]
Deletes the provider configuration corresponding to the provider ID passed. If the specified ID does not exist, an auth/configuration-not-found error is thrown.
SAML and OIDC provider support requires Google Cloud's Identity Platform (GCIP). To learn more about GCIP, including pricing and features, see the | GCIP documentation.
Parameters
providerId - The provider ID corresponding to the provider config to delete.
Returns
A promise that resolves on completion.
References auth_config_1, error_1, and Promise.
deleteUser()
BaseAuth::deleteUser (uid) [inline]
Deletes an existing user.
See | Delete a user for code samples and detailed documentation.
Parameters
uid - The uid corresponding to the user to delete.
Returns
An empty promise fulfilled once the user has been deleted.
deleteUsers()
BaseAuth::deleteUsers (uids) [inline]
Deletes the users specified by the given uids.
Deleting a non-existing user won't generate an error (i.e. this method is idempotent.) Non-existing users are considered to be successfully deleted, and are therefore counted in the DeleteUsersResult.successCount value.
Only a maximum of 1000 identifiers may be supplied. If more than 1000 identifiers are supplied, this method throws a FirebaseAuthError.
This API is currently rate limited at the server to 1 QPS. If you exceed this, you may get a quota exceeded error. Therefore, if you want to delete more than 1000 users, you may need to add a delay to ensure you don't go over this limit.
Parameters
uids - The uids corresponding to the users to delete.
Returns
A Promise that resolves to the total number of successful/failed deletions, as well as the array of errors that corresponds to the failed deletions.
References error, error_1, errors, index, msg, result, undefined, and validator.
generateEmailVerificationLink()
BaseAuth::generateEmailVerificationLink (email, actionCodeSettings) [inline]
generatePasswordResetLink()
BaseAuth::generatePasswordResetLink (email, actionCodeSettings) [inline]
generateSignInWithEmailLink()
BaseAuth::generateSignInWithEmailLink (email, actionCodeSettings) [inline]
generateVerifyAndChangeEmailLink()
BaseAuth::generateVerifyAndChangeEmailLink (email, newEmail, actionCodeSettings) [inline]
Generates an out-of-band email action link to verify the user's ownership of the specified email. The ActionCodeSettings object provided as an argument to this method defines whether the link is to be handled by a mobile app or browser along with additional state information to be passed in the deep link, etc.
Parameters
email - The current email account.
newEmail - The email address the account is being updated to.
actionCodeSettings - The action code settings. If specified, the state/continue URL is set as the "continueUrl" parameter in the email verification link. The default email verification landing page will use this to display a link to go back to the app if it is installed. If the actionCodeSettings is not specified, no URL is appended to the action URL. The state URL provided must belong to a domain that is authorized in the console, or an error will be thrown. Mobile app redirects are only applicable if the developer configures and accepts the Firebase Dynamic Links terms of service. The Android package name and iOS bundle ID are respected only if they are configured in the same Firebase Auth project.
Returns
A promise that resolves with the generated link.
getProviderConfig()
BaseAuth::getProviderConfig (providerId) [inline]
Looks up an Auth provider configuration by the provided ID. Returns a promise that resolves with the provider configuration corresponding to the provider ID specified. If the specified ID does not exist, an auth/configuration-not-found error is thrown.
SAML and OIDC provider support requires Google Cloud's Identity Platform (GCIP). To learn more about GCIP, including pricing and features, see the | GCIP documentation.
Parameters
providerId - The provider ID corresponding to the provider config to return.
Returns
A promise that resolves with the configuration corresponding to the provided ID.
References auth_config_1, error_1, Promise, and response.
getUser()
BaseAuth::getUser (uid) [inline]
Gets the user data for the user corresponding to a given uid.
See | Retrieve user data for code samples and detailed documentation.
Parameters
uid - The uid corresponding to the user whose data to fetch.
Returns
A promise fulfilled with the user data corresponding to the provided uid.
References response, and user_record_1.
getUserByEmail()
BaseAuth::getUserByEmail (email) [inline]
Gets the user data for the user corresponding to a given email.
See | Retrieve user data for code samples and detailed documentation.
Parameters
email - The email corresponding to the user whose data to fetch.
Returns
A promise fulfilled with the user data corresponding to the provided email.
References response, and user_record_1.
getUserByPhoneNumber()
BaseAuth::getUserByPhoneNumber (phoneNumber) [inline]
Gets the user data for the user corresponding to a given phone number. The phone number has to conform to the E.164 specification.
See | Retrieve user data for code samples and detailed documentation.
Parameters
phoneNumber - The phone number corresponding to the user whose data to fetch.
Returns
A promise fulfilled with the user data corresponding to the provided phone number.
References response, and user_record_1.
getUserByProviderUid()
BaseAuth::getUserByProviderUid (providerId, uid) [inline]
Gets the user data for the user corresponding to a given provider id.
See | Retrieve user data for code samples and detailed documentation.
Parameters
providerId - The provider ID, for example, "google.com" for the Google provider.
uid - The user identifier for the given provider.
Returns
A promise fulfilled with the user data corresponding to the given provider id.
References getUserByEmail(), getUserByPhoneNumber(), response, and user_record_1.
getUsers()
BaseAuth::getUsers (identifiers) [inline]
Gets the user data corresponding to the specified identifiers.
There are no ordering guarantees; in particular, the nth entry in the result list is not guaranteed to correspond to the nth entry in the input parameters list.
Only a maximum of 100 identifiers may be supplied. If more than 100 identifiers are supplied, this method throws a FirebaseAuthError.
Parameters
identifiers - The identifiers used to indicate which user records should be returned. Must not have more than 100 entries.
Returns
A promise that resolves to the corresponding user records.
Exceptions
FirebaseAuthError If any of the identifiers are invalid or if more than 100 identifiers are specified.
Checks if the specified identifier is within the list of UserRecords.
References error_1, identifier_1, response, user_record_1, and validator.
importUsers()
BaseAuth::importUsers (users, options) [inline]
Imports the provided list of users into Firebase Auth. A maximum of 1000 users are allowed to be imported one at a time. When importing users with passwords, UserImportOptions are required to be specified. This operation is optimized for bulk imports and will ignore checks on uid, email and other identifier uniqueness which could result in duplications.
Parameters
users - The list of user records to import to Firebase Auth.
options - The user import options, required when the users provided include password credentials.
Returns
A promise that resolves when the operation completes with the result of the import. This includes the number of successful imports, the number of failed imports and their corresponding errors.
listProviderConfigs()
BaseAuth::listProviderConfigs (options) [inline]
Returns the list of existing provider configurations matching the filter provided. At most, 100 provider configs can be listed at a time.
SAML and OIDC provider support requires Google Cloud's Identity Platform (GCIP). To learn more about GCIP, including pricing and features, see the | GCIP documentation.
Parameters
options - The provider config filter to apply.
Returns
A promise that resolves with the list of provider configs meeting the filter requirements.
References auth_config_1, error_1, Promise, response, and result.
listUsers()
BaseAuth::listUsers (maxResults, pageToken) [inline]
Retrieves a list of users (single batch only) with a size of maxResults starting from the offset as specified by pageToken. This is used to retrieve all the users of a specified project in batches.
See | List all users for code samples and detailed documentation.
Parameters
maxResults - The page size, 1000 if undefined. This is also the maximum allowed limit.
pageToken - The next page token. If not specified, returns users starting without any offset.
Returns
A promise that resolves with the current batch of downloaded users and the next page token.
References response, result, and user_record_1.
revokeRefreshTokens()
BaseAuth::revokeRefreshTokens (uid) [inline]
Revokes all refresh tokens for an existing user.
This API will update the user's UserRecord.tokensValidAfterTime to the current UTC. It is important that the server on which this is called has its clock set correctly and synchronized.
While this will revoke all sessions for a specified user and disable any new ID tokens for existing sessions from getting minted, existing ID tokens may remain active until their natural expiration (one hour). To verify that ID tokens are revoked, use BaseAuth.verifyIdToken where checkRevoked is set to true.
Parameters
uid - The uid corresponding to the user whose refresh tokens are to be revoked.
Returns
An empty promise fulfilled once the user's refresh tokens have been revoked.
setCustomUserClaims()
BaseAuth::setCustomUserClaims (uid, customUserClaims) [inline]
Sets additional developer claims on an existing user identified by the provided uid, typically used to define user roles and levels of access. These claims should propagate to all devices where the user is already signed in (after token expiration or when token refresh is forced) and the next time the user signs in. If a reserved OIDC claim name is used (sub, iat, iss, etc), an error is thrown. They are set on the authenticated user's ID token JWT.
See | Defining user roles and access levels for code samples and detailed documentation.
Parameters
uid - The uid of the user to edit.
customUserClaims - The developer claims to set. If null is passed, existing custom claims are deleted. Passing a custom claims payload larger than 1000 bytes will throw an error. Custom claims are added to the user's ID token which is transmitted on every authenticated request. For profile non-access related user attributes, use database or other separate storage systems.
Returns
A promise that resolves when the operation completes successfully.
updateProviderConfig()
BaseAuth::updateProviderConfig (providerId, updatedConfig) [inline]
Returns a promise that resolves with the updated AuthProviderConfig corresponding to the provider ID specified. If the specified ID does not exist, an auth/configuration-not-found error is thrown.
SAML and OIDC provider support requires Google Cloud's Identity Platform (GCIP). To learn more about GCIP, including pricing and features, see the | GCIP documentation.
Parameters
providerId - The provider ID corresponding to the provider config to update.
updatedConfig - The updated configuration.
Returns
A promise that resolves with the updated provider configuration.
References auth_config_1, error_1, Promise, response, and validator.
updateUser()
BaseAuth::updateUser (uid, properties) [inline]
Updates an existing user.
See | Update a user for code samples and detailed documentation.
Parameters
uid - The uid corresponding to the user to update.
properties - The properties to update on the provided user.
Returns
A promise fulfilled with the updated user data.
References deep_copy_1, error_1, and getUser().
verifyDecodedJWTNotRevokedOrDisabled()
BaseAuth::verifyDecodedJWTNotRevokedOrDisabled (decodedIdToken, revocationErrorInfo) [inline]
Verifies the decoded Firebase issued JWT is not revoked or disabled. Returns a promise that resolves with the decoded claims on success. Rejects the promise with revocation error if revoked or user disabled.
Parameters
decodedIdToken - The JWT's decoded claims.
revocationErrorInfo - The revocation error info to throw on revocation detection.
Returns
A promise that will be fulfilled after a successful verification.
References error_1, and getUser().
verifyIdToken()
BaseAuth::verifyIdToken (idToken, checkRevoked = false) [inline]
Verifies a Firebase ID token (JWT). If the token is valid, the promise is fulfilled with the token's decoded claims; otherwise, the promise is rejected.
If checkRevoked is set to true, first verifies whether the corresponding user is disabled. If yes, an auth/user-disabled error is thrown. If no, verifies if the session corresponding to the ID token was revoked. If the corresponding user's session was invalidated, an auth/id-token-revoked error is thrown. If not specified the check is not applied.
See | Verify ID Tokens for code samples and detailed documentation.
Parameters
idToken - The ID token to verify.
checkRevoked - Whether to check if the ID token was revoked. This requires an extra request to the Firebase Auth backend to check the tokensValidAfterTime time for the corresponding user. When not specified, this additional check is not applied.
Returns
A promise fulfilled with the token's decoded claims if the ID token is valid; otherwise, a rejected promise.
References auth_api_request_1, error_1, and verifyDecodedJWTNotRevokedOrDisabled().
verifySessionCookie()
BaseAuth::verifySessionCookie (sessionCookie, checkRevoked = false) [inline]
Verifies a Firebase session cookie. Returns a Promise with the cookie claims. Rejects the promise if the cookie could not be verified.
If checkRevoked is set to true, first verifies whether the corresponding user is disabled: If yes, an auth/user-disabled error is thrown. If no, verifies if the session corresponding to the session cookie was revoked. If the corresponding user's session was invalidated, an auth/session-cookie-revoked error is thrown. If not specified the check is not performed.
See | Verify Session Cookies for code samples and detailed documentation
Parameters
sessionCookie - The session cookie to verify.
checkForRevocation - Whether to check if the session cookie was revoked. This requires an extra request to the Firebase Auth backend to check the tokensValidAfterTime time for the corresponding user. When not specified, this additional check is not performed.
Returns
A promise fulfilled with the session cookie's decoded claims if the session cookie is valid; otherwise, a rejected promise.
References auth_api_request_1, error_1, and verifyDecodedJWTNotRevokedOrDisabled().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/base-auth.js