Command Class Reference
Public Member Functions
constructor ({ index, name, command, prefixColor, env, cwd, ipc }, spawnOpts, spawn, killProcess)
start ()
maybeSetupIPC (child)
send (message, handle, options)
kill (code)
cleanUp ()
Static Public Member Functions
static canKill (command)
Public Attributes
killProcess
spawn
spawnOpts
index
name
command
prefixColor
env
cwd
ipc
close = new Rx.Subject()
error = new Rx.Subject()
stdout = new Rx.Subject()
stderr = new Rx.Subject()
timer = new Rx.Subject()
messages
process
subscriptions = []
stdin
pid
killed = false
exited = false
state = 'stopped'
Member Function Documentation
canKill()
static Command::canKill (command) [inline], [static]
Detects whether a command can be killed.
Also works as a type guard on the input command.
References command().
cleanUp()
Command::cleanUp () [inline]
References process, Rx, sub, and undefined.
constructor()
Command::constructor ({ index, name, command, prefixColor, env, cwd, ipc }, spawnOpts, spawn, killProcess) [inline]
References command, cwd, env, index, ipc, name, and prefixColor.
kill()
Command::kill (code) [inline]
Kills this command, optionally specifying a signal to send to it.
References canKill().
maybeSetupIPC()
Command::maybeSetupIPC (child) [inline]
References event, ipc, pipeTo(), and Rx.
send()
Command::send (message, handle, options) [inline]
Sends a message to the underlying process once it starts.
Exceptions
If the command doesn't have an IPC channel enabled
Returns
Promise that resolves when the message is sent, or rejects if it fails to deliver the message.
References error, handle, message, Promise, reject(), and resolve.
start()
Command::start () [inline]
Starts this command, piping output, error and close events onto the corresponding observables.
References cleanUp(), close, command, error, event, index, killed, pid, pipeTo(), process, Rx, signal, spawn, spawnOpts, state, stdin, subscriptions, timer, timings, and undefined.
Member Data Documentation
close
Command::close = new Rx.Subject()
command
Command::command
cwd
Command::cwd
env
Command::env
error
Command::error = new Rx.Subject()
exited
Command::exited = false
index
Command::index
ipc
Command::ipc
killed
Command::killed = false
killProcess
Command::killProcess
messages
Command::messages
Initial value:
= {
        incoming: new Rx.Subject(),
        outgoing: new Rx.ReplaySubject(),
    }
name
Command::name
pid
Command::pid
prefixColor
Command::prefixColor
process
Command::process
spawn
Command::spawn
spawnOpts
Command::spawnOpts
state
Command::state = 'stopped'
stderr
Command::stderr = new Rx.Subject()
stdin
Command::stdin
stdout
Command::stdout = new Rx.Subject()
subscriptions
Command::subscriptions = []
timer
Command::timer = new Rx.Subject()
The documentation for this class was generated from the following file:
backend/node_modules/concurrently/dist/src/command.js