QueryParams Class Reference
Public Member Functions
constructor ()
hasStart ()
isViewFromLeft ()
getIndexStartValue ()
getIndexStartName ()
hasEnd ()
getIndexEndValue ()
getIndexEndName ()
hasLimit ()
hasAnchoredLimit ()
getLimit ()
getIndex ()
loadsAllData ()
isDefault ()
copy ()
constructor ()
hasStart ()
isViewFromLeft ()
getIndexStartValue ()
getIndexStartName ()
hasEnd ()
getIndexEndValue ()
getIndexEndName ()
hasLimit ()
hasAnchoredLimit ()
getLimit ()
getIndex ()
loadsAllData ()
isDefault ()
copy ()
constructor ()
hasStart ()
isViewFromLeft ()
getIndexStartValue ()
getIndexStartName ()
hasEnd ()
getIndexEndValue ()
getIndexEndName ()
hasLimit ()
hasAnchoredLimit ()
getLimit ()
getIndex ()
loadsAllData ()
isDefault ()
copy ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. This class is an immutable-from-the-public-api struct containing a set of query parameters defining a range to be returned for a particular location. It is assumed that validation of parameters is done at the user-facing API level, so it is not done here.
Member Function Documentation
constructor() [1/3]
QueryParams::constructor () [inline]
References PRIORITY_INDEX.
constructor() [2/3]
QueryParams::constructor () [inline]
References PRIORITY_INDEX.
constructor() [3/3]
QueryParams::constructor () [inline]
References PRIORITY_INDEX.
copy() [1/3]
QueryParams::copy () [inline]
References copy().
copy() [2/3]
QueryParams::copy () [inline]
References copy().
copy() [3/3]
QueryParams::copy () [inline]
References copy().
getIndex() [1/3]
QueryParams::getIndex () [inline]
getIndex() [2/3]
QueryParams::getIndex () [inline]
getIndex() [3/3]
QueryParams::getIndex () [inline]
getIndexEndName() [1/3]
QueryParams::getIndexEndName () [inline]
Only valid to call if hasEnd() returns true. Returns the end key name for the range defined by these query parameters
References MAX_NAME, and util.
getIndexEndName() [2/3]
QueryParams::getIndexEndName () [inline]
Only valid to call if hasEnd() returns true. Returns the end key name for the range defined by these query parameters
References assert, and MAX_NAME.
getIndexEndName() [3/3]
QueryParams::getIndexEndName () [inline]
Only valid to call if hasEnd() returns true. Returns the end key name for the range defined by these query parameters
References assert, and MAX_NAME.
getIndexEndValue() [1/3]
QueryParams::getIndexEndValue () [inline]
Only valid to call if hasEnd() returns true.
References util.
getIndexEndValue() [2/3]
QueryParams::getIndexEndValue () [inline]
Only valid to call if hasEnd() returns true.
References assert.
getIndexEndValue() [3/3]
QueryParams::getIndexEndValue () [inline]
Only valid to call if hasEnd() returns true.
References assert.
getIndexStartName() [1/3]
QueryParams::getIndexStartName () [inline]
Only valid to call if hasStart() returns true. Returns the starting key name for the range defined by these query parameters
References MIN_NAME, and util.
getIndexStartName() [2/3]
QueryParams::getIndexStartName () [inline]
Only valid to call if hasStart() returns true. Returns the starting key name for the range defined by these query parameters
References assert, and MIN_NAME.
getIndexStartName() [3/3]
QueryParams::getIndexStartName () [inline]
Only valid to call if hasStart() returns true. Returns the starting key name for the range defined by these query parameters
References assert, and MIN_NAME.
getIndexStartValue() [1/3]
QueryParams::getIndexStartValue () [inline]
Only valid to call if hasStart() returns true
References util.
getIndexStartValue() [2/3]
QueryParams::getIndexStartValue () [inline]
Only valid to call if hasStart() returns true
References assert.
getIndexStartValue() [3/3]
QueryParams::getIndexStartValue () [inline]
Only valid to call if hasStart() returns true
References assert.
getLimit() [1/3]
QueryParams::getLimit () [inline]
Only valid to call if hasLimit() returns true
References util.
getLimit() [2/3]
QueryParams::getLimit () [inline]
Only valid to call if hasLimit() returns true
References assert.
getLimit() [3/3]
QueryParams::getLimit () [inline]
Only valid to call if hasLimit() returns true
References assert.
hasAnchoredLimit() [1/3]
QueryParams::hasAnchoredLimit () [inline]
Returns
True if a limit has been set and it has been explicitly anchored
hasAnchoredLimit() [2/3]
QueryParams::hasAnchoredLimit () [inline]
Returns
True if a limit has been set and it has been explicitly anchored
hasAnchoredLimit() [3/3]
QueryParams::hasAnchoredLimit () [inline]
Returns
True if a limit has been set and it has been explicitly anchored
hasEnd() [1/3]
QueryParams::hasEnd () [inline]
hasEnd() [2/3]
QueryParams::hasEnd () [inline]
hasEnd() [3/3]
QueryParams::hasEnd () [inline]
hasLimit() [1/3]
QueryParams::hasLimit () [inline]
hasLimit() [2/3]
QueryParams::hasLimit () [inline]
hasLimit() [3/3]
QueryParams::hasLimit () [inline]
hasStart() [1/3]
QueryParams::hasStart () [inline]
hasStart() [2/3]
QueryParams::hasStart () [inline]
hasStart() [3/3]
QueryParams::hasStart () [inline]
isDefault() [1/3]
QueryParams::isDefault () [inline]
References loadsAllData(), and PRIORITY_INDEX.
isDefault() [2/3]
QueryParams::isDefault () [inline]
References loadsAllData(), and PRIORITY_INDEX.
isDefault() [3/3]
QueryParams::isDefault () [inline]
References loadsAllData(), and PRIORITY_INDEX.
isViewFromLeft() [1/3]
QueryParams::isViewFromLeft () [inline]
Returns
True if it would return from left.
isViewFromLeft() [2/3]
QueryParams::isViewFromLeft () [inline]
Returns
True if it would return from left.
isViewFromLeft() [3/3]
QueryParams::isViewFromLeft () [inline]
Returns
True if it would return from left.
loadsAllData() [1/3]
QueryParams::loadsAllData () [inline]
loadsAllData() [2/3]
QueryParams::loadsAllData () [inline]
loadsAllData() [3/3]
QueryParams::loadsAllData () [inline]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js