RangedFilter Class Reference
Public Member Functions
constructor (params)
getStartPost ()
getEndPost ()
matches (node)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
constructor (params)
getStartPost ()
getEndPost ()
matches (node)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
constructor (params)
getStartPost ()
getEndPost ()
matches (node)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
Static Public Member Functions
static getStartPost_ (params)
static getEndPost_ (params)
static getStartPost_ (params)
static getEndPost_ (params)
static getStartPost_ (params)
static getEndPost_ (params)
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Filters nodes by range and uses an IndexFilter to track any changes after filtering the node
Member Function Documentation
constructor() [1/3]
RangedFilter::constructor (params) [inline]
References getEndPost_(), and getStartPost_().
constructor() [2/3]
RangedFilter::constructor (params) [inline]
References getEndPost_(), and getStartPost_().
constructor() [3/3]
RangedFilter::constructor (params) [inline]
References getEndPost_(), and getStartPost_().
filtersNodes() [1/3]
RangedFilter::filtersNodes () [inline]
filtersNodes() [2/3]
RangedFilter::filtersNodes () [inline]
filtersNodes() [3/3]
RangedFilter::filtersNodes () [inline]
getEndPost() [1/3]
RangedFilter::getEndPost () [inline]
getEndPost() [2/3]
RangedFilter::getEndPost () [inline]
getEndPost() [3/3]
RangedFilter::getEndPost () [inline]
getEndPost_() [1/3]
static RangedFilter::getEndPost_ (params) [inline], [static]
getEndPost_() [2/3]
static RangedFilter::getEndPost_ (params) [inline], [static]
getEndPost_() [3/3]
static RangedFilter::getEndPost_ (params) [inline], [static]
getIndex() [1/3]
RangedFilter::getIndex () [inline]
getIndex() [2/3]
RangedFilter::getIndex () [inline]
getIndex() [3/3]
RangedFilter::getIndex () [inline]
getIndexedFilter() [1/3]
RangedFilter::getIndexedFilter () [inline]
getIndexedFilter() [2/3]
RangedFilter::getIndexedFilter () [inline]
getIndexedFilter() [3/3]
RangedFilter::getIndexedFilter () [inline]
getStartPost() [1/3]
RangedFilter::getStartPost () [inline]
getStartPost() [2/3]
RangedFilter::getStartPost () [inline]
getStartPost() [3/3]
RangedFilter::getStartPost () [inline]
getStartPost_() [1/3]
static RangedFilter::getStartPost_ (params) [inline], [static]
getStartPost_() [2/3]
static RangedFilter::getStartPost_ (params) [inline], [static]
getStartPost_() [3/3]
static RangedFilter::getStartPost_ (params) [inline], [static]
matches() [1/3]
RangedFilter::matches (node) [inline]
References getEndPost(), getStartPost(), and node.
matches() [2/3]
RangedFilter::matches (node) [inline]
References getEndPost(), getStartPost(), and node.
matches() [3/3]
RangedFilter::matches (node) [inline]
References getEndPost(), getStartPost(), and node.
updateChild() [1/3]
RangedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), matches, and source.
updateChild() [2/3]
RangedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), matches, and source.
updateChild() [3/3]
RangedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), matches, and source.
updateFullNode() [1/3]
RangedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), matches, and PRIORITY_INDEX.
updateFullNode() [2/3]
RangedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), matches, and PRIORITY_INDEX.
updateFullNode() [3/3]
RangedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References ChildrenNode::EMPTY_NODE(), matches, and PRIORITY_INDEX.
updatePriority() [1/3]
RangedFilter::updatePriority (oldSnap, newPriority) [inline]
updatePriority() [2/3]
RangedFilter::updatePriority (oldSnap, newPriority) [inline]
updatePriority() [3/3]
RangedFilter::updatePriority (oldSnap, newPriority) [inline]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js