RateLimiter Class Reference
Public Member Functions
constructor (initialCapacity, multiplier, multiplierMillis, maximumCapacity, startTimeMillis=Date.now())
Private Member Functions
tryMakeRequest (numOperations, requestTimeMillis=Date.now())
getNextRequestDelayMs (numOperations, requestTimeMillis=Date.now())
refillTokens (requestTimeMillis)
calculateCapacity (requestTimeMillis)
Detailed Description
A helper that uses the Token Bucket algorithm to rate limit the number of operations that can be made in a second.
Before a given request containing a number of operations can proceed, RateLimiter determines doing so stays under the provided rate limits. It can also determine how much time is required before a request can be made.
RateLimiter can also implement a gradually increasing rate limit. This is used to enforce the 500/50/5 rule (https://firebase.google.com/docs/firestore/best-practices#ramping_up_traffic).
Member Function Documentation
calculateCapacity()
RateLimiter::calculateCapacity (requestTimeMillis) [inline], [private]
Calculates the maximum capacity based on the provided date.
References $, assert, logger_1, and request.
constructor()
RateLimiter::constructor (initialCapacity, multiplier, multiplierMillis, maximumCapacity, startTimeMillis = Date.now()) [inline]
Parameters
initialCapacity Initial maximum number of operations per second.
multiplier Rate by which to increase the capacity.
multiplierMillis How often the capacity should increase in milliseconds.
maximumCapacity Maximum number of allowed operations per second. The number of tokens added per second will never exceed this number.
startTimeMillis The starting time in epoch milliseconds that the rate limit is based on. Used for testing the limiter.
getNextRequestDelayMs()
RateLimiter::getNextRequestDelayMs (numOperations, requestTimeMillis = Date.now()) [inline], [private]
Returns the number of ms needed to make a request with the provided number of operations. Returns 0 if the request can be made with the existing capacity. Returns -1 if the request is not possible with the current capacity.
Parameters
requestTimeMillis The time used to calculate the number of available tokens. Used for testing the limiter.
References calculateCapacity(), and refillTokens().
refillTokens()
RateLimiter::refillTokens (requestTimeMillis) [inline], [private]
Refills the number of available tokens based on how much time has elapsed since the last time the tokens were refilled.
Parameters
requestTimeMillis The time used to calculate the number of available tokens. Used for testing the limiter.
References calculateCapacity().
tryMakeRequest()
RateLimiter::tryMakeRequest (numOperations, requestTimeMillis = Date.now()) [inline], [private]
Tries to make the number of operations. Returns true if the request succeeded and false otherwise.
Parameters
requestTimeMillis The time used to calculate the number of available tokens. Used for testing the limiter.
References refillTokens().
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/rate-limiter.js