FirebaseError Class Reference
Public Member Functions
constructor (code, message, customData)
constructor (code, message, customData)
constructor (code, message, customData)
constructor (errorInfo)
get code ()
get message ()
toJSON ()
Detailed Description
Firebase error code structure. This extends Error.
Member Function Documentation
code()
get FirebaseError::code () [inline]
Returns
The error code.
constructor() [1/4]
FirebaseError::constructor (code, message, customData) [inline]
The custom name for all FirebaseErrors.
Parameters
code The error code for this error.
customData Custom data for this error.
References code(), ErrorFactory::create(), ERROR_NAME, message(), and name.
constructor() [2/4]
FirebaseError::constructor (code, message, customData) [inline]
The custom name for all FirebaseErrors.
Parameters
code The error code for this error.
customData Custom data for this error.
References code(), ErrorFactory::create(), ERROR_NAME, message(), and name.
constructor() [3/4]
FirebaseError::constructor (code, message, customData) [inline]
The custom name for all FirebaseErrors.
Parameters
code The error code for this error.
customData Custom data for this error.
References code(), ErrorFactory::create(), ERROR_NAME, message(), and name.
constructor() [4/4]
FirebaseError::constructor (errorInfo) [inline]
Parameters
errorInfo - The error information (code and message). @constructor
message()
get FirebaseError::message () [inline]
Returns
The error message.
toJSON()
FirebaseError::toJSON () [inline]
Returns
The object representation of the error.
References code(), and message().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/util/dist/index.cjs.js
backend/node_modules/@firebase/util/dist/index.esm2017.js
backend/node_modules/@firebase/util/dist/node-esm/index.node.esm.js
backend/node_modules/firebase-admin/lib/utils/error.js