SortedMap Class Reference
Public Member Functions
constructor (comparator_, root_=SortedMap.EMPTY_NODE)
insert (key, value)
remove (key)
get (key)
getPredecessorKey (key)
isEmpty ()
count ()
minKey ()
maxKey ()
inorderTraversal (action)
reverseTraversal (action)
getIterator (resultGenerator)
getIteratorFrom (key, resultGenerator)
getReverseIteratorFrom (key, resultGenerator)
getReverseIterator (resultGenerator)
constructor (comparator_, root_=SortedMap.EMPTY_NODE)
insert (key, value)
remove (key)
get (key)
getPredecessorKey (key)
isEmpty ()
count ()
minKey ()
maxKey ()
inorderTraversal (action)
reverseTraversal (action)
getIterator (resultGenerator)
getIteratorFrom (key, resultGenerator)
getReverseIteratorFrom (key, resultGenerator)
getReverseIterator (resultGenerator)
constructor (comparator_, root_=SortedMap.EMPTY_NODE)
insert (key, value)
remove (key)
get (key)
getPredecessorKey (key)
isEmpty ()
count ()
minKey ()
maxKey ()
inorderTraversal (action)
reverseTraversal (action)
getIterator (resultGenerator)
getIteratorFrom (key, resultGenerator)
getReverseIteratorFrom (key, resultGenerator)
getReverseIterator (resultGenerator)
Detailed Description
An immutable sorted map implementation, based on a Left-leaning Red-Black tree.
Member Function Documentation
constructor() [1/3]
SortedMap::constructor (comparator_, root_ = SortedMap.EMPTY_NODE) [inline]
Parameters
comparator_ - Key comparator.
root_ - Optional root node for the map.
constructor() [2/3]
SortedMap::constructor (comparator_, root_ = SortedMap.EMPTY_NODE) [inline]
Parameters
comparator_ - Key comparator.
root_ - Optional root node for the map.
constructor() [3/3]
SortedMap::constructor (comparator_, root_ = SortedMap.EMPTY_NODE) [inline]
Parameters
comparator_ - Key comparator.
root_ - Optional root node for the map.
count() [1/3]
SortedMap::count () [inline]
Returns
The total number of nodes in the map.
count() [2/3]
SortedMap::count () [inline]
Returns
The total number of nodes in the map.
count() [3/3]
SortedMap::count () [inline]
Returns
The total number of nodes in the map.
get() [1/3]
SortedMap::get (key) [inline]
Returns the value of the node with the given key, or null.
Parameters
key - The key to look up.
Returns
The value of the node with the given key, or null if the key doesn't exist.
References node.
get() [2/3]
SortedMap::get (key) [inline]
Returns the value of the node with the given key, or null.
Parameters
key - The key to look up.
Returns
The value of the node with the given key, or null if the key doesn't exist.
References node.
get() [3/3]
SortedMap::get (key) [inline]
Returns the value of the node with the given key, or null.
Parameters
key - The key to look up.
Returns
The value of the node with the given key, or null if the key doesn't exist.
References node.
getIterator() [1/3]
SortedMap::getIterator (resultGenerator) [inline]
Returns an iterator over the SortedMap.
Returns
The iterator.
getIterator() [2/3]
SortedMap::getIterator (resultGenerator) [inline]
Returns an iterator over the SortedMap.
Returns
The iterator.
getIterator() [3/3]
SortedMap::getIterator (resultGenerator) [inline]
Returns an iterator over the SortedMap.
Returns
The iterator.
getIteratorFrom() [1/3]
SortedMap::getIteratorFrom (key, resultGenerator) [inline]
getIteratorFrom() [2/3]
SortedMap::getIteratorFrom (key, resultGenerator) [inline]
getIteratorFrom() [3/3]
SortedMap::getIteratorFrom (key, resultGenerator) [inline]
getPredecessorKey() [1/3]
SortedMap::getPredecessorKey (key) [inline]
Returns the key of the item before the specified key, or null if key is the first item.
Parameters
key - The key to find the predecessor of
Returns
The predecessor key.
References node.
getPredecessorKey() [2/3]
SortedMap::getPredecessorKey (key) [inline]
Returns the key of the item before the specified key, or null if key is the first item.
Parameters
key - The key to find the predecessor of
Returns
The predecessor key.
References node.
getPredecessorKey() [3/3]
SortedMap::getPredecessorKey (key) [inline]
Returns the key of the item before the specified key, or null if key is the first item.
Parameters
key - The key to find the predecessor of
Returns
The predecessor key.
References node.
getReverseIterator() [1/3]
SortedMap::getReverseIterator (resultGenerator) [inline]
getReverseIterator() [2/3]
SortedMap::getReverseIterator (resultGenerator) [inline]
getReverseIterator() [3/3]
SortedMap::getReverseIterator (resultGenerator) [inline]
getReverseIteratorFrom() [1/3]
SortedMap::getReverseIteratorFrom (key, resultGenerator) [inline]
getReverseIteratorFrom() [2/3]
SortedMap::getReverseIteratorFrom (key, resultGenerator) [inline]
getReverseIteratorFrom() [3/3]
SortedMap::getReverseIteratorFrom (key, resultGenerator) [inline]
inorderTraversal() [1/3]
SortedMap::inorderTraversal (action) [inline]
Traverses the map in key order and calls the specified action function for each key/value pair.
Parameters
action - Callback function to be called for each key/value pair. If action returns true, traversal is aborted.
Returns
The first truthy value returned by action, or the last falsey value returned by action
inorderTraversal() [2/3]
SortedMap::inorderTraversal (action) [inline]
Traverses the map in key order and calls the specified action function for each key/value pair.
Parameters
action - Callback function to be called for each key/value pair. If action returns true, traversal is aborted.
Returns
The first truthy value returned by action, or the last falsey value returned by action
inorderTraversal() [3/3]
SortedMap::inorderTraversal (action) [inline]
Traverses the map in key order and calls the specified action function for each key/value pair.
Parameters
action - Callback function to be called for each key/value pair. If action returns true, traversal is aborted.
Returns
The first truthy value returned by action, or the last falsey value returned by action
insert() [1/3]
SortedMap::insert (key, value) [inline]
Returns a copy of the map, with the specified key/value added or replaced. (TODO: We should perhaps rename this method to 'put')
Parameters
key - Key to be added.
value - Value to be added.
Returns
New map, with item added.
References copy, insert(), and value.
insert() [2/3]
SortedMap::insert (key, value) [inline]
Returns a copy of the map, with the specified key/value added or replaced. (TODO: We should perhaps rename this method to 'put')
Parameters
key - Key to be added.
value - Value to be added.
Returns
New map, with item added.
References copy, insert(), and value.
insert() [3/3]
SortedMap::insert (key, value) [inline]
Returns a copy of the map, with the specified key/value added or replaced. (TODO: We should perhaps rename this method to 'put')
Parameters
key - Key to be added.
value - Value to be added.
Returns
New map, with item added.
References copy, insert(), and value.
isEmpty() [1/3]
SortedMap::isEmpty () [inline]
Returns
True if the map is empty.
isEmpty() [2/3]
SortedMap::isEmpty () [inline]
Returns
True if the map is empty.
isEmpty() [3/3]
SortedMap::isEmpty () [inline]
Returns
True if the map is empty.
maxKey() [1/3]
SortedMap::maxKey () [inline]
Returns
The maximum key in the map.
maxKey() [2/3]
SortedMap::maxKey () [inline]
Returns
The maximum key in the map.
maxKey() [3/3]
SortedMap::maxKey () [inline]
Returns
The maximum key in the map.
minKey() [1/3]
SortedMap::minKey () [inline]
Returns
The minimum key in the map.
minKey() [2/3]
SortedMap::minKey () [inline]
Returns
The minimum key in the map.
minKey() [3/3]
SortedMap::minKey () [inline]
Returns
The minimum key in the map.
remove() [1/3]
SortedMap::remove (key) [inline]
Returns a copy of the map, with the specified key removed.
Parameters
key - The key to remove.
Returns
New map, with item removed.
References copy.
remove() [2/3]
SortedMap::remove (key) [inline]
Returns a copy of the map, with the specified key removed.
Parameters
key - The key to remove.
Returns
New map, with item removed.
References copy.
remove() [3/3]
SortedMap::remove (key) [inline]
Returns a copy of the map, with the specified key removed.
Parameters
key - The key to remove.
Returns
New map, with item removed.
References copy.
reverseTraversal() [1/3]
SortedMap::reverseTraversal (action) [inline]
Traverses the map in reverse key order and calls the specified action function for each key/value pair.
Parameters
action - Callback function to be called for each key/value pair. If action returns true, traversal is aborted.
Returns
True if the traversal was aborted.
reverseTraversal() [2/3]
SortedMap::reverseTraversal (action) [inline]
Traverses the map in reverse key order and calls the specified action function for each key/value pair.
Parameters
action - Callback function to be called for each key/value pair. If action returns true, traversal is aborted.
Returns
True if the traversal was aborted.
reverseTraversal() [3/3]
SortedMap::reverseTraversal (action) [inline]
Traverses the map in reverse key order and calls the specified action function for each key/value pair.
Parameters
action - Callback function to be called for each key/value pair. If action returns true, traversal is aborted.
Returns
True if the traversal was aborted.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js