Storage Class Reference
Public Member Functions
getBucketsStream ()
getHmacKeysStream ()
getBucketsStream ()
getHmacKeysStream ()
constructor (app)
catch (err)
if (credential instanceof credential_internal_1.ServiceAccountCredential)
else if ((0, credential_internal_1.isApplicationDefault)(app.options.credential))
bucket (name)
get app ()
constructor (config, options={})
getRequestInterceptors ()
getRequestInterceptors ()
getProjectId (callback)
getProjectId (callback)
async getProjectIdAsync ()
async getProjectIdAsync ()
request_ (reqOpts, callback)
request_ (reqOpts, callback)
Public Attributes
let storage
try
const projectId = utils.getExplicitProjectId(app)
const credential = app.options.credential
else
this appInternal = app
Storage#acl
bucket (name, options)
channel (id, resourceId)
createBucket (name, metadataOrCallback, callback)
createHmacKey (serviceAccountEmail, optionsOrCb, cb)
getBuckets (optionsOrCallback, cb)
getHmacKeys (optionsOrCb, cb)
getServiceAccount (optionsOrCallback, cb)
hmacKey (accessId, options)
bucket (name, options)
channel (id, resourceId)
createBucket (name, metadataOrCallback, callback)
createHmacKey (serviceAccountEmail, optionsOrCb, cb)
getBuckets (optionsOrCallback, cb)
getHmacKeys (optionsOrCb, cb)
getServiceAccount (optionsOrCallback, cb)
hmacKey (accessId, options)
static sanitizeEndpoint (url)
static sanitizeEndpoint (url)
Detailed Description
ACLs
Cloud Storage uses access control lists (ACLs) to manage object and bucket access. ACLs are the mechanism you use to share files with other users and allow other users to access your buckets and files.
To learn more about ACLs, read this overview on Access Control.
See Cloud Storage overview See Access Control
The default Storage service if no app is provided or the Storage service associated with the provided app.
Examples
/Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/cjs/src/channel.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/cjs/src/hmacKey.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/cjs/src/iam.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/cjs/src/notification.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/cjs/src/storage.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/cjs/src/transfer-manager.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/esm/src/channel.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/esm/src/hmacKey.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/esm/src/iam.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/esm/src/notification.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/esm/src/storage.js, and /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/storage/build/esm/src/transfer-manager.js.
Member Function Documentation
app()
get Storage::app () [inline]
Optional app whose Storage service to return. If not provided, the default Storage service will be returned. Here is the caller graph for this function:
bucket() [1/3]
Storage::bucket (name) [inline]
Gets a reference to a Cloud Storage bucket.
Parameters
name - Optional name of the bucket to be retrieved. If name is not specified, retrieves a reference to the default bucket.
Returns
A | Bucket instance as defined in the @google-cloud/storage package.
References error_1, message, name, and validator.
bucket() [2/3]
Storage::bucket (name, options) [inline]
References bucket_js_1, name, and StorageExceptionMessages.
bucket() [3/3]
Storage::bucket (name, options) [inline]
References Bucket, name, and StorageExceptionMessages.
catch()
Storage::catch (err) [inline]
References $, error, error_1, and message.
channel() [1/2]
Storage::channel (id, resourceId) [inline]
References channel_js_1.
channel() [2/2]
Storage::channel (id, resourceId) [inline]
References Channel.
constructor() [1/2]
Service::constructor (config, options = {}) [inline], [inherited]
Service is a base class, meant to be inherited from by a "service," like BigQuery or Storage.
This handles making authenticated requests by exposing a makeReq_ function.
@constructor @alias module:common/service
Parameters
{object} config - Configuration object.
{string} config.baseUrl - The base URL to make API requests to.
{string[]} config.scopes - The scopes required for the request.
{object=} options - Configuration object.
constructor() [2/2]
Storage::constructor (app) [inline]
Parameters
app - The app for this Storage service. @constructor
References app(), error_1, http, https, message, process, and validator.
createBucket() [1/2]
Storage::createBucket (name, metadataOrCallback, callback) [inline]
References $, and, bucket(), callback, json, method, name, of, project, projectId, qs, query, request, and StorageExceptionMessages.
createBucket() [2/2]
Storage::createBucket (name, metadataOrCallback, callback) [inline]
References $, and, bucket(), callback, json, method, name, of, project, projectId, qs, query, request, and StorageExceptionMessages.
createHmacKey() [1/2]
Storage::createHmacKey (serviceAccountEmail, optionsOrCb, cb) [inline]
References $, callback, hmacKey(), method, projectId, qs, query, request, StorageExceptionMessages, and util_js_1.
createHmacKey() [2/2]
Storage::createHmacKey (serviceAccountEmail, optionsOrCb, cb) [inline]
References $, callback, hmacKey(), method, normalize, projectId, qs, query, request, and StorageExceptionMessages.
getBuckets() [1/2]
Storage::getBuckets (optionsOrCallback, cb) [inline]
References bucket(), callback, projectId, qs, request, and util_js_1.
getBuckets() [2/2]
Storage::getBuckets (optionsOrCallback, cb) [inline]
References bucket(), callback, normalize, projectId, qs, and request.
getBucketsStream() [1/2]
Storage::getBucketsStream () [inline]
References stream_1.
getBucketsStream() [2/2]
Storage::getBucketsStream () [inline]
References Readable.
getHmacKeys() [1/2]
Storage::getHmacKeys (optionsOrCb, cb) [inline]
References $, callback, hmacKey(), projectId, qs, query, request, and util_js_1.
getHmacKeys() [2/2]
Storage::getHmacKeys (optionsOrCb, cb) [inline]
References $, callback, hmacKey(), normalize, projectId, qs, query, and request.
getHmacKeysStream() [1/2]
Storage::getHmacKeysStream () [inline]
References stream_1.
getHmacKeysStream() [2/2]
Storage::getHmacKeysStream () [inline]
References Readable.
getProjectId() [1/2]
Service::getProjectId (callback) [inline], [inherited]
References callback, Service::getProjectIdAsync(), and p.
getProjectId() [2/2]
Service::getProjectId (callback) [inline], [inherited]
References callback, Service::getProjectIdAsync(), and p.
getProjectIdAsync() [1/2]
async Service::getProjectIdAsync () [inline], [inherited]
References exports.
getProjectIdAsync() [2/2]
async Service::getProjectIdAsync () [inline], [inherited]
References DEFAULT_PROJECT_ID_TOKEN.
getRequestInterceptors() [1/2]
Service::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
getRequestInterceptors() [2/2]
Service::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
getServiceAccount() [1/2]
Storage::getServiceAccount (optionsOrCallback, cb) [inline]
References $, _, callback, g, match, projectId, prop, qs, request, util_js_1, and w.
getServiceAccount() [2/2]
Storage::getServiceAccount (optionsOrCallback, cb) [inline]
References $, _, callback, g, match, normalize, projectId, prop, qs, request, and w.
hmacKey() [1/2]
Storage::hmacKey (accessId, options) [inline]
References hmacKey_js_1, and StorageExceptionMessages.
hmacKey() [2/2]
Storage::hmacKey (accessId, options) [inline]
References HmacKey, and StorageExceptionMessages.
if() [1/2]
else Storage::if ((0, credential_internal_1.isApplicationDefault)(app.options.credential)) [inline]
References storage.
if() [2/2]
Storage::if (credential instanceof credential_internal_1. ServiceAccountCredential) [inline]
request_() [1/2]
Service::request_ (reqOpts, callback) [inline], [inherited]
Make an authenticated API request.
Parameters
{object} reqOpts - Request options that are passed to request.
{string} reqOpts.uri - A URI relative to the baseUrl.
References timeout.
request_() [2/2]
Service::request_ (reqOpts, callback) [inline], [inherited]
Make an authenticated API request.
Parameters
{object} reqOpts - Request options that are passed to request.
{string} reqOpts.uri - A URI relative to the baseUrl.
References timeout.
sanitizeEndpoint() [1/2]
static Storage::sanitizeEndpoint (url) [inline], [static]
References $, exports, https, and url.
sanitizeEndpoint() [2/2]
static Storage::sanitizeEndpoint (url) [inline], [static]
References $, https, and url.
Member Data Documentation
appInternal
this Storage::appInternal = app
credential
const Storage::credential = app.options.credential
else
Storage::else
Initial value:
{
            throw new error_1.FirebaseError({
                code: 'storage/invalid-credential',
                message: 'Failed to initialize Google Cloud Storage client with the available credential. ' +
                    'Must initialize the SDK with a certificate credential or application default credentials ' +
                    'to use Cloud Storage API.',
            })
projectId
const Storage::projectId = utils.getExplicitProjectId(app)
storage
let Storage::storage
try
Storage::try
Initial value:
{
            storage = require('@google-cloud/storage').Storage
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/storage.js
backend/node_modules/firebase-admin/lib/storage/storage.js
backend/node_modules/@google-cloud/storage/build/esm/src/storage.js