InterceptingListenerImpl Class Reference
Public Member Functions
constructor (listener, nextListener)
processPendingMessage ()
processPendingStatus ()
onReceiveMetadata (metadata)
onReceiveMessage (message)
onReceiveStatus (status)
Member Function Documentation
constructor()
InterceptingListenerImpl::constructor (listener, nextListener) [inline]
onReceiveMessage()
InterceptingListenerImpl::onReceiveMessage (message) [inline]
References message, msg, and processPendingStatus().
onReceiveMetadata()
InterceptingListenerImpl::onReceiveMetadata (metadata) [inline]
References processPendingMessage(), and processPendingStatus().
onReceiveStatus()
InterceptingListenerImpl::onReceiveStatus (status) [inline]
References status.
processPendingMessage()
InterceptingListenerImpl::processPendingMessage () [inline]
processPendingStatus()
InterceptingListenerImpl::processPendingStatus () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/call-interface.js