WriteTreeCompleteChildSource Class Reference
Public Member Functions
constructor (writes_, viewCache_, optCompleteServerCache_=null)
getCompleteChild (childKey)
getChildAfterChild (index, child, reverse)
constructor (writes_, viewCache_, optCompleteServerCache_=null)
getCompleteChild (childKey)
getChildAfterChild (index, child, reverse)
constructor (writes_, viewCache_, optCompleteServerCache_=null)
getCompleteChild (childKey)
getChildAfterChild (index, child, reverse)
Detailed Description
An implementation of CompleteChildSource that uses a WriteTree in addition to any other server data or old event caches available to calculate complete children.
Member Function Documentation
constructor() [1/3]
WriteTreeCompleteChildSource::constructor (writes_, viewCache_, optCompleteServerCache_ = null) [inline]
constructor() [2/3]
WriteTreeCompleteChildSource::constructor (writes_, viewCache_, optCompleteServerCache_ = null) [inline]
constructor() [3/3]
WriteTreeCompleteChildSource::constructor (writes_, viewCache_, optCompleteServerCache_ = null) [inline]
getChildAfterChild() [1/3]
WriteTreeCompleteChildSource::getChildAfterChild (index, child, reverse) [inline]
References index, reverse, viewCacheGetCompleteServerSnap(), and writeTreeRefCalcIndexedSlice().
getChildAfterChild() [2/3]
WriteTreeCompleteChildSource::getChildAfterChild (index, child, reverse) [inline]
References index, reverse, viewCacheGetCompleteServerSnap(), and writeTreeRefCalcIndexedSlice().
getChildAfterChild() [3/3]
WriteTreeCompleteChildSource::getChildAfterChild (index, child, reverse) [inline]
References index, reverse, viewCacheGetCompleteServerSnap(), and writeTreeRefCalcIndexedSlice().
getCompleteChild() [1/3]
WriteTreeCompleteChildSource::getCompleteChild (childKey) [inline]
References node, and writeTreeRefCalcCompleteChild().
getCompleteChild() [2/3]
WriteTreeCompleteChildSource::getCompleteChild (childKey) [inline]
References node, and writeTreeRefCalcCompleteChild().
getCompleteChild() [3/3]
WriteTreeCompleteChildSource::getCompleteChild (childKey) [inline]
References node, and writeTreeRefCalcCompleteChild().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js