UserImportBuilder Class Reference
Public Member Functions
constructor (users, options, userRequestValidator)
buildRequest ()
buildResponse (failedUploads)
populateOptions (options, requiresHashOptions)
populateUsers (users, userValidator)
Detailed Description
Class that provides a helper for building/validating uploadAccount requests and UserImportResult responses.
Member Function Documentation
buildRequest()
UserImportBuilder::buildRequest () [inline]
Returns the corresponding constructed uploadAccount request.
Returns
{UploadAccountRequest} The constructed uploadAccount request.
References deep_copy_1.
buildResponse()
UserImportBuilder::buildResponse (failedUploads) [inline]
Populates the UserImportResult using the client side detected errors and the server side returned errors.
Returns
{UserImportResult} The user import result based on the returned failed uploadAccount response.
References a, b, deep_copy_1, error, error_1, errors, and index.
constructor()
UserImportBuilder::constructor (users, options, userRequestValidator) [inline]
Parameters
{UserImportRecord[]} users The list of user records to import.
{UserImportOptions=} options The import options which includes hashing algorithm details.
{ValidatorFunction=} userRequestValidator The user request validator function. @constructor
References populateOptions(), and populateUsers().
populateOptions()
UserImportBuilder::populateOptions (options, requiresHashOptions) [inline]
Validates and returns the hashing options of the uploadAccount request. Throws an error whenever an invalid or missing options is detected.
Parameters
{UserImportOptions} options The UserImportOptions.
{boolean} requiresHashOptions Whether to require hash options.
Returns
{UploadAccountOptions} The populated UploadAccount options.
References $, and, error_1, getNumberField(), hash(), isNaN, utils, and validator.
populateUsers()
UserImportBuilder::populateUsers (users, userValidator) [inline]
Validates and returns the users list of the uploadAccount request. Whenever a user with an error is detected, the error is cached and will later be merged into the user import result. This allows the processing of valid users without failing early on the first error detected.
Parameters
{UserImportRecord[]} users The UserImportRecords to convert to UnploadAccountUser objects.
{ValidatorFunction=} userValidator The user validator function.
Returns
{UploadAccountUser[]} The populated uploadAccount users.
References error, index, populateUploadAccountUser(), and result.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/user-import-builder.js