PathTemplate Class Reference
Public Member Functions
constructor (data)
match (path)
Member Function Documentation
constructor()
PathTemplate::constructor (data) [inline]
Parameters
{String} data the of the template
@constructor
References data, and size.
match()
PathTemplate::match (path) [inline]
Matches a fully-qualified path template string.
Parameters
{String} path a fully-qualified path template string
Returns
{Object} contains const names matched to binding values
Exceptions
{TypeError} if path can't be matched to this template
Renders a path template using the provided bindings.
Parameters
{Object} bindings a mapping of const names to binding strings
Returns
{String} a rendered representation of the path template
Exceptions
{TypeError} if a key is missing, or if a sub-template cannot be parsed
Renders the path template.
Returns
{string} contains const names matched to binding values
Parse the path template.
Returns
{string[]} return segments of the input path. For example: 'buckets/{hello}'' will give back ['buckets', {hello=*}]
References $, a, and, data, for(), g, includes, index, is, match, matches, not, of, path, processing(), str(), v, and value.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/pathTemplate.js