OrderedMapIterator Class Reference
Public Member Functions
constructor (t, e, s, i)
get pointer ()
copy ()
constructor (t, e, s)
constructor (t=0)
get index ()
isAccessible ()
equals (t)
Member Function Documentation
constructor() [1/3]
ContainerIterator::constructor (t = 0) [inline], [inherited]
References t.
constructor() [2/3]
OrderedMapIterator::constructor (t, e, s, i) [inline]
References e, i, s, and t.
constructor() [3/3]
TreeIterator::constructor (t, e, s) [inline], [inherited]
References C, e, next(), s, T, t, and throwIteratorAccessError().
copy()
OrderedMapIterator::copy () [inline]
References C, OrderedMapIterator, and T.
equals()
ContainerIterator::equals (t) [inline], [inherited]
References T, and t.
index()
get TreeIterator::index () [inline], [inherited]
References C, e, s, T, and t.
isAccessible()
TreeIterator::isAccessible () [inline], [inherited]
References C, and T.
pointer()
get OrderedMapIterator::pointer () [inline]
References C, e, i, Proxy, s, T, t, and throwIteratorAccessError().
The documentation for this class was generated from the following file:
backend/node_modules/@js-sdsl/ordered-map/dist/cjs/index.js