LoadBalancingCall Class Reference
Public Member Functions
constructor (channel, callConfig, methodName, host, credentials, deadline, callNumber)
getDeadlineInfo ()
trace (text)
outputStatus (status, progress)
doPick ()
cancelWithStatus (status, details)
getPeer ()
start (metadata, listener)
sendMessageWithContext (context, message)
startRead ()
halfClose ()
setCredentials (credentials)
getCallNumber ()
Member Function Documentation
cancelWithStatus()
LoadBalancingCall::cancelWithStatus (status, details) [inline]
References _a, metadata_1, outputStatus(), status, and trace.
constructor()
LoadBalancingCall::constructor (channel, callConfig, methodName, host, credentials, deadline, callNumber) [inline]
References _a, _b, credentials, https, and uri_parser_1.
doPick()
LoadBalancingCall::doPick () [inline]
References $, _a, _b, _c, connectivity_state_1, constants_1, control_plane_status_1, credentials, deadline_1, doPick(), error, http2, message, metadata_1, outputStatus(), picker_1, setImmediate, status, then, and trace.
getCallNumber()
LoadBalancingCall::getCallNumber () [inline]
getDeadlineInfo()
LoadBalancingCall::getDeadlineInfo () [inline]
References $, _a, _b, deadline_1, and pick.
getPeer()
LoadBalancingCall::getPeer () [inline]
References _a, and _b.
halfClose()
LoadBalancingCall::halfClose () [inline]
References trace.
outputStatus()
LoadBalancingCall::outputStatus (status, progress) [inline]
References _a, _b, status, and trace.
sendMessageWithContext()
LoadBalancingCall::sendMessageWithContext (context, message) [inline]
References context, message, and trace.
setCredentials()
LoadBalancingCall::setCredentials (credentials) [inline]
start()
LoadBalancingCall::start (metadata, listener) [inline]
References doPick(), and trace.
startRead()
LoadBalancingCall::startRead () [inline]
References trace.
trace()
LoadBalancingCall::trace (text) [inline]
References constants_1, logging, text, and TRACER_NAME.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/load-balancing-call.js