IndexMap Class Reference
Public Member Functions
constructor (indexes_, indexSet_)
get (indexKey)
hasIndex (indexDefinition)
addIndex (indexDefinition, existingChildren)
addToIndexes (namedNode, existingChildren)
removeFromIndexes (namedNode, existingChildren)
constructor (indexes_, indexSet_)
get (indexKey)
hasIndex (indexDefinition)
addIndex (indexDefinition, existingChildren)
addToIndexes (namedNode, existingChildren)
removeFromIndexes (namedNode, existingChildren)
constructor (indexes_, indexSet_)
get (indexKey)
hasIndex (indexDefinition)
addIndex (indexDefinition, existingChildren)
addToIndexes (namedNode, existingChildren)
removeFromIndexes (namedNode, existingChildren)
Static Public Member Functions
static get Default ()
static get Default ()
static get Default ()
Member Function Documentation
addIndex() [1/3]
IndexMap::addIndex (indexDefinition, existingChildren) [inline]
References buildChildSet, fallbackObject, KEY_INDEX, next(), util, and NamedNode::Wrap().
addIndex() [2/3]
IndexMap::addIndex (indexDefinition, existingChildren) [inline]
References assert, buildChildSet, fallbackObject, KEY_INDEX, next(), and NamedNode::Wrap().
addIndex() [3/3]
IndexMap::addIndex (indexDefinition, existingChildren) [inline]
References assert, buildChildSet, fallbackObject, KEY_INDEX, next(), and NamedNode::Wrap().
addToIndexes() [1/3]
IndexMap::addToIndexes (namedNode, existingChildren) [inline]
Ensure that this node is properly tracked in any indexes that we're maintaining
References buildChildSet, fallbackObject, index, next(), util, and NamedNode::Wrap().
addToIndexes() [2/3]
IndexMap::addToIndexes (namedNode, existingChildren) [inline]
Ensure that this node is properly tracked in any indexes that we're maintaining
References assert, buildChildSet, fallbackObject, index, map, next(), safeGet, and NamedNode::Wrap().
addToIndexes() [3/3]
IndexMap::addToIndexes (namedNode, existingChildren) [inline]
Ensure that this node is properly tracked in any indexes that we're maintaining
References assert, buildChildSet, fallbackObject, index, map, next(), safeGet, and NamedNode::Wrap().
constructor() [1/3]
IndexMap::constructor (indexes_, indexSet_) [inline]
constructor() [2/3]
IndexMap::constructor (indexes_, indexSet_) [inline]
constructor() [3/3]
IndexMap::constructor (indexes_, indexSet_) [inline]
Default() [1/3]
static get IndexMap::Default () [inline], [static]
The default IndexMap for nodes without a priority
References _defaultIndexMap, fallbackObject, PRIORITY_INDEX, and util.
Default() [2/3]
static get IndexMap::Default () [inline], [static]
The default IndexMap for nodes without a priority
References _defaultIndexMap, assert, fallbackObject, and PRIORITY_INDEX.
Default() [3/3]
static get IndexMap::Default () [inline], [static]
The default IndexMap for nodes without a priority
References _defaultIndexMap, assert, fallbackObject, and PRIORITY_INDEX.
get() [1/3]
IndexMap::get (indexKey) [inline]
References util.
get() [2/3]
IndexMap::get (indexKey) [inline]
References safeGet.
get() [3/3]
IndexMap::get (indexKey) [inline]
References safeGet.
hasIndex() [1/3]
IndexMap::hasIndex (indexDefinition) [inline]
References util.
hasIndex() [2/3]
IndexMap::hasIndex (indexDefinition) [inline]
References contains.
hasIndex() [3/3]
IndexMap::hasIndex (indexDefinition) [inline]
References contains.
removeFromIndexes() [1/3]
IndexMap::removeFromIndexes (namedNode, existingChildren) [inline]
Create a new IndexMap instance with the given value removed
References fallbackObject, and util.
removeFromIndexes() [2/3]
IndexMap::removeFromIndexes (namedNode, existingChildren) [inline]
Create a new IndexMap instance with the given value removed
References fallbackObject, and map.
removeFromIndexes() [3/3]
IndexMap::removeFromIndexes (namedNode, existingChildren) [inline]
Create a new IndexMap instance with the given value removed
References fallbackObject, and map.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js