ErrorFactory Class Reference
Public Member Functions
constructor (service, serviceName, errors)
create (code,...data)
constructor (service, serviceName, errors)
create (code,...data)
constructor (service, serviceName, errors)
create (code,...data)
Member Function Documentation
constructor() [1/3]
ErrorFactory::constructor (service, serviceName, errors) [inline]
References errors.
constructor() [2/3]
ErrorFactory::constructor (service, serviceName, errors) [inline]
References errors.
constructor() [3/3]
ErrorFactory::constructor (service, serviceName, errors) [inline]
References errors.
create() [1/3]
ErrorFactory::create (code, ...) [inline]
References $, data, error, errors, FirebaseError, message, and replaceTemplate().
create() [2/3]
ErrorFactory::create (code, ...) [inline]
References $, data, error, errors, FirebaseError, message, and replaceTemplate().
create() [3/3]
ErrorFactory::create (code, ...) [inline]
References $, data, error, errors, FirebaseError, message, and replaceTemplate().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/util/dist/index.cjs.js
backend/node_modules/@firebase/util/dist/index.esm2017.js
backend/node_modules/@firebase/util/dist/node-esm/index.node.esm.js