FileWatcherCertificateProvider Class Reference
Public Member Functions
constructor (config)
updateCertificates ()
maybeStartWatchingFiles ()
maybeStopWatchingFiles ()
addCaCertificateListener (listener)
removeCaCertificateListener (listener)
addIdentityCertificateListener (listener)
removeIdentityCertificateListener (listener)
Member Function Documentation
addCaCertificateListener()
FileWatcherCertificateProvider::addCaCertificateListener (listener) [inline]
References maybeStartWatchingFiles(), and process.
addIdentityCertificateListener()
FileWatcherCertificateProvider::addIdentityCertificateListener (listener) [inline]
References maybeStartWatchingFiles(), and process.
constructor()
FileWatcherCertificateProvider::constructor (config) [inline]
References config, JSON, Set, trace, and undefined.
maybeStartWatchingFiles()
FileWatcherCertificateProvider::maybeStartWatchingFiles () [inline]
References config, trace, and updateCertificates().
maybeStopWatchingFiles()
FileWatcherCertificateProvider::maybeStopWatchingFiles () [inline]
removeCaCertificateListener()
FileWatcherCertificateProvider::removeCaCertificateListener (listener) [inline]
References maybeStopWatchingFiles().
removeIdentityCertificateListener()
FileWatcherCertificateProvider::removeIdentityCertificateListener (listener) [inline]
References maybeStopWatchingFiles().
updateCertificates()
FileWatcherCertificateProvider::updateCertificates () [inline]
References config, of, Promise, readFilePromise, and trace.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/certificate-provider.js