AsyncHttpCall Class Reference
Public Member Functions
constructor (config)
execute ()
handleResponse (res, req)
uncompressResponse (res)
getMultipartBoundary (headers)
handleMultipartResponse (response, respStream, boundary)
handleRegularResponse (response, respStream)
finalizeResponse (response)
rejectWithError (message, code, request, response)
enhanceAndReject (error, code, request, response)
enhanceError (error, code, request, response)
Static Public Member Functions
static invoke (config)
Detailed Description
A helper class for sending HTTP requests over the wire. This is a wrapper around the standard http and https packages of Node.js, providing content processing, timeouts and error handling. It also wraps the callback API of the Node.js standard library in a more flexible Promise API.
Member Function Documentation
constructor()
AsyncHttpCall::constructor (config) [inline]
References config, AsyncRequestCall::enhanceError(), execute(), Promise, reject(), and resolve.
enhanceAndReject()
AsyncRequestCall::enhanceAndReject (error, code, request, response) [inline], [inherited]
References AsyncRequestCall::enhanceError(), error, reject(), request, and response.
enhanceError()
AsyncRequestCall::enhanceError (error, code, request, response) [inline], [inherited]
Enhances the given error by adding more information to it. Specifically, the request config, the underlying request and response will be attached to the error.
References error, request, and response.
execute()
AsyncHttpCall::execute () [inline]
References $, AsyncRequestCall::enhanceAndReject(), handleResponse(), http, https, ms, of, AsyncRequestCall::rejectWithError(), req, res, and timeout.
finalizeResponse()
AsyncRequestCall::finalizeResponse (response) [inline], [inherited]
Finalizes the current request call in-flight by either resolving or rejecting the associated promise. In the event of an error, adds additional useful information to the returned error.
References AsyncRequestCall::rejectWithError(), resolve, and response.
getMultipartBoundary()
AsyncRequestCall::getMultipartBoundary (headers) [inline], [inherited]
Extracts multipart boundary from the HTTP header. The content-type header of a multipart response has the form 'multipart/subtype; boundary=string'.
If the content-type header does not exist, or does not start with 'multipart/', then null will be returned.
References contentType, emptyObject, and headers.
handleMultipartResponse()
AsyncRequestCall::handleMultipartResponse (response, respStream, boundary) [inline], [inherited]
References AsyncRequestCall::finalizeResponse(), require(), response, and undefined.
handleRegularResponse()
AsyncRequestCall::handleRegularResponse (response, respStream) [inline], [inherited]
References chunk(), AsyncRequestCall::enhanceAndReject(), AsyncRequestCall::finalizeResponse(), req, and response.
handleResponse()
AsyncHttpCall::handleResponse (res, req) [inline]
References config, data, error_1, AsyncRequestCall::getMultipartBoundary(), AsyncRequestCall::handleMultipartResponse(), AsyncRequestCall::handleRegularResponse(), headers, req, request, res, response, status, uncompressResponse(), and undefined.
invoke()
static AsyncHttpCall::invoke (config) [inline], [static]
Sends an HTTP request based on the provided configuration.
References config.
rejectWithError()
AsyncRequestCall::rejectWithError (message, code, request, response) [inline], [inherited]
Creates a new error from the given message, and enhances it with other information available. Then the promise associated with this request call is rejected with the resulting error.
References AsyncRequestCall::enhanceAndReject(), error, message, request, and response.
uncompressResponse()
AsyncHttpCall::uncompressResponse (res) [inline]
References encodings, require(), res, and zlib.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js