DiagComponentLogger Class Reference
Public Member Functions
constructor (props)
debug (...args)
error (...args)
info (...args)
warn (...args)
verbose (...args)
constructor (props)
debug (...args)
error (...args)
info (...args)
warn (...args)
verbose (...args)
Member Function Documentation
constructor() [1/2]
DiagComponentLogger::constructor (props) [inline]
constructor() [2/2]
DiagComponentLogger::constructor (props) [inline]
debug() [1/2]
DiagComponentLogger::debug (...) [inline]
References args, and logProxy().
debug() [2/2]
DiagComponentLogger::debug (...) [inline]
References args, and logProxy().
error() [1/2]
DiagComponentLogger::error (...) [inline]
References args, and logProxy().
error() [2/2]
DiagComponentLogger::error (...) [inline]
References args, and logProxy().
info() [1/2]
DiagComponentLogger::info (...) [inline]
References args, and logProxy().
info() [2/2]
DiagComponentLogger::info (...) [inline]
References args, and logProxy().
verbose() [1/2]
DiagComponentLogger::verbose (...) [inline]
References args, and logProxy().
verbose() [2/2]
DiagComponentLogger::verbose (...) [inline]
References args, and logProxy().
warn() [1/2]
DiagComponentLogger::warn (...) [inline]
References args, and logProxy().
warn() [2/2]
DiagComponentLogger::warn (...) [inline]
References args, and logProxy().
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/diag/ComponentLogger.js
backend/node_modules/@opentelemetry/api/build/src/diag/ComponentLogger.js