ImmutableTree Class Reference
Public Member Functions
constructor (value, children=EmptyChildren())
isEmpty ()
findRootMostMatchingPathAndValue (relativePath, predicate)
findRootMostValueAndPath (relativePath)
subtree (relativePath)
set (relativePath, toSet)
remove (relativePath)
get (relativePath)
setTree (relativePath, newTree)
fold (fn)
fold_ (pathSoFar, fn)
findOnPath (path, f)
findOnPath_ (pathToFollow, pathSoFar, f)
foreachOnPath (path, f)
foreachOnPath_ (pathToFollow, currentRelativePath, f)
foreach (f)
foreach_ (currentRelativePath, f)
foreachChild (f)
constructor (value, children=EmptyChildren())
isEmpty ()
findRootMostMatchingPathAndValue (relativePath, predicate)
findRootMostValueAndPath (relativePath)
subtree (relativePath)
set (relativePath, toSet)
remove (relativePath)
get (relativePath)
setTree (relativePath, newTree)
fold (fn)
fold_ (pathSoFar, fn)
findOnPath (path, f)
findOnPath_ (pathToFollow, pathSoFar, f)
foreachOnPath (path, f)
foreachOnPath_ (pathToFollow, currentRelativePath, f)
foreach (f)
foreach_ (currentRelativePath, f)
foreachChild (f)
constructor (value, children=EmptyChildren())
isEmpty ()
findRootMostMatchingPathAndValue (relativePath, predicate)
findRootMostValueAndPath (relativePath)
subtree (relativePath)
set (relativePath, toSet)
remove (relativePath)
get (relativePath)
setTree (relativePath, newTree)
fold (fn)
fold_ (pathSoFar, fn)
findOnPath (path, f)
findOnPath_ (pathToFollow, pathSoFar, f)
foreachOnPath (path, f)
foreachOnPath_ (pathToFollow, currentRelativePath, f)
foreach (f)
foreach_ (currentRelativePath, f)
foreachChild (f)
Static Public Member Functions
static fromObject (obj)
static fromObject (obj)
static fromObject (obj)
Detailed Description
A tree with immutable elements.
Member Function Documentation
constructor() [1/3]
ImmutableTree::constructor (value, children = EmptyChildren()) [inline]
References value.
constructor() [2/3]
ImmutableTree::constructor (value, children = EmptyChildren()) [inline]
References value.
constructor() [3/3]
ImmutableTree::constructor (value, children = EmptyChildren()) [inline]
References value.
findOnPath() [1/3]
ImmutableTree::findOnPath (path, f) [inline]
Find the first matching value on the given path. Return the result of applying f to it.
References f, findOnPath_(), newEmptyPath(), and path.
findOnPath() [2/3]
ImmutableTree::findOnPath (path, f) [inline]
Find the first matching value on the given path. Return the result of applying f to it.
References f, findOnPath_(), newEmptyPath(), and path.
findOnPath() [3/3]
ImmutableTree::findOnPath (path, f) [inline]
Find the first matching value on the given path. Return the result of applying f to it.
References f, findOnPath_(), newEmptyPath(), and path.
findOnPath_() [1/3]
ImmutableTree::findOnPath_ (pathToFollow, pathSoFar, f) [inline]
References f, front, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), result, and value.
findOnPath_() [2/3]
ImmutableTree::findOnPath_ (pathToFollow, pathSoFar, f) [inline]
References f, front, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), result, and value.
findOnPath_() [3/3]
ImmutableTree::findOnPath_ (pathToFollow, pathSoFar, f) [inline]
References f, front, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), result, and value.
findRootMostMatchingPathAndValue() [1/3]
ImmutableTree::findRootMostMatchingPathAndValue (relativePath, predicate) [inline]
Given a path and predicate, return the first node and the path to that node where the predicate returns true.
TODO Do a perf test -- If we're creating a bunch of {path: value:} objects on the way back out, it may be better to pass down a pathSoFar obj.
Parameters
relativePath - The remainder of the path
predicate - The predicate to satisfy to return a node
References front, newEmptyPath(), path, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
findRootMostMatchingPathAndValue() [2/3]
ImmutableTree::findRootMostMatchingPathAndValue (relativePath, predicate) [inline]
Given a path and predicate, return the first node and the path to that node where the predicate returns true.
TODO Do a perf test -- If we're creating a bunch of {path: value:} objects on the way back out, it may be better to pass down a pathSoFar obj.
Parameters
relativePath - The remainder of the path
predicate - The predicate to satisfy to return a node
References front, newEmptyPath(), path, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
findRootMostMatchingPathAndValue() [3/3]
ImmutableTree::findRootMostMatchingPathAndValue (relativePath, predicate) [inline]
Given a path and predicate, return the first node and the path to that node where the predicate returns true.
TODO Do a perf test -- If we're creating a bunch of {path: value:} objects on the way back out, it may be better to pass down a pathSoFar obj.
Parameters
relativePath - The remainder of the path
predicate - The predicate to satisfy to return a node
References front, newEmptyPath(), path, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
findRootMostValueAndPath() [1/3]
ImmutableTree::findRootMostValueAndPath (relativePath) [inline]
Find, if it exists, the shortest subpath of the given path that points a defined value in the tree
References findRootMostMatchingPathAndValue().
findRootMostValueAndPath() [2/3]
ImmutableTree::findRootMostValueAndPath (relativePath) [inline]
Find, if it exists, the shortest subpath of the given path that points a defined value in the tree
References findRootMostMatchingPathAndValue().
findRootMostValueAndPath() [3/3]
ImmutableTree::findRootMostValueAndPath (relativePath) [inline]
Find, if it exists, the shortest subpath of the given path that points a defined value in the tree
References findRootMostMatchingPathAndValue().
fold() [1/3]
ImmutableTree::fold (fn) [inline]
Performs a depth first fold on this tree. Transforms a tree into a single value, given a function that operates on the path to a node, an optional current value, and a map of child names to folded subtrees
References fn, fold_(), and newEmptyPath().
fold() [2/3]
ImmutableTree::fold (fn) [inline]
Performs a depth first fold on this tree. Transforms a tree into a single value, given a function that operates on the path to a node, an optional current value, and a map of child names to folded subtrees
References fn, fold_(), and newEmptyPath().
fold() [3/3]
ImmutableTree::fold (fn) [inline]
Performs a depth first fold on this tree. Transforms a tree into a single value, given a function that operates on the path to a node, an optional current value, and a map of child names to folded subtrees
References fn, fold_(), and newEmptyPath().
fold_() [1/3]
ImmutableTree::fold_ (pathSoFar, fn) [inline]
Recursive helper for public-facing fold() method
References fn, pathChild(), and value.
fold_() [2/3]
ImmutableTree::fold_ (pathSoFar, fn) [inline]
Recursive helper for public-facing fold() method
References fn, pathChild(), and value.
fold_() [3/3]
ImmutableTree::fold_ (pathSoFar, fn) [inline]
Recursive helper for public-facing fold() method
References fn, pathChild(), and value.
foreach() [1/3]
ImmutableTree::foreach (f) [inline]
Calls the given function for each node in the tree that has a value.
Parameters
f - A function to be called with the path from the root of the tree to a node, and the value at that node. Called in depth-first order.
References f, foreach_(), and newEmptyPath().
foreach() [2/3]
ImmutableTree::foreach (f) [inline]
Calls the given function for each node in the tree that has a value.
Parameters
f - A function to be called with the path from the root of the tree to a node, and the value at that node. Called in depth-first order.
References f, foreach_(), and newEmptyPath().
foreach() [3/3]
ImmutableTree::foreach (f) [inline]
Calls the given function for each node in the tree that has a value.
Parameters
f - A function to be called with the path from the root of the tree to a node, and the value at that node. Called in depth-first order.
References f, foreach_(), and newEmptyPath().
foreach_() [1/3]
ImmutableTree::foreach_ (currentRelativePath, f) [inline]
References f, pathChild(), and value.
foreach_() [2/3]
ImmutableTree::foreach_ (currentRelativePath, f) [inline]
References f, pathChild(), and value.
foreach_() [3/3]
ImmutableTree::foreach_ (currentRelativePath, f) [inline]
References f, pathChild(), and value.
foreachChild() [1/3]
ImmutableTree::foreachChild (f) [inline]
References f.
foreachChild() [2/3]
ImmutableTree::foreachChild (f) [inline]
References f.
foreachChild() [3/3]
ImmutableTree::foreachChild (f) [inline]
References f.
foreachOnPath() [1/3]
ImmutableTree::foreachOnPath (path, f) [inline]
References f, foreachOnPath_(), newEmptyPath(), and path.
foreachOnPath() [2/3]
ImmutableTree::foreachOnPath (path, f) [inline]
References f, foreachOnPath_(), newEmptyPath(), and path.
foreachOnPath() [3/3]
ImmutableTree::foreachOnPath (path, f) [inline]
References f, foreachOnPath_(), newEmptyPath(), and path.
foreachOnPath_() [1/3]
ImmutableTree::foreachOnPath_ (pathToFollow, currentRelativePath, f) [inline]
References f, front, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
foreachOnPath_() [2/3]
ImmutableTree::foreachOnPath_ (pathToFollow, currentRelativePath, f) [inline]
References f, front, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
foreachOnPath_() [3/3]
ImmutableTree::foreachOnPath_ (pathToFollow, currentRelativePath, f) [inline]
References f, front, pathChild(), pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
fromObject() [1/3]
static ImmutableTree::fromObject (obj) [inline], [static]
References each, and obj.
fromObject() [2/3]
static ImmutableTree::fromObject (obj) [inline], [static]
References each, and obj.
fromObject() [3/3]
static ImmutableTree::fromObject (obj) [inline], [static]
References each, and obj.
get() [1/3]
ImmutableTree::get (relativePath) [inline]
Gets a value from the tree.
Parameters
relativePath - Path to get value for.
Returns
Value at path, or null.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
get() [2/3]
ImmutableTree::get (relativePath) [inline]
Gets a value from the tree.
Parameters
relativePath - Path to get value for.
Returns
Value at path, or null.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
get() [3/3]
ImmutableTree::get (relativePath) [inline]
Gets a value from the tree.
Parameters
relativePath - Path to get value for.
Returns
Value at path, or null.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
isEmpty() [1/3]
ImmutableTree::isEmpty () [inline]
True if the value is empty and there are no children
References value.
isEmpty() [2/3]
ImmutableTree::isEmpty () [inline]
True if the value is empty and there are no children
References value.
isEmpty() [3/3]
ImmutableTree::isEmpty () [inline]
True if the value is empty and there are no children
References value.
remove() [1/3]
ImmutableTree::remove (relativePath) [inline]
Removes the value at the specified path.
Parameters
relativePath - Path to value to remove.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
remove() [2/3]
ImmutableTree::remove (relativePath) [inline]
Removes the value at the specified path.
Parameters
relativePath - Path to value to remove.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
remove() [3/3]
ImmutableTree::remove (relativePath) [inline]
Removes the value at the specified path.
Parameters
relativePath - Path to value to remove.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
set() [1/3]
ImmutableTree::set (relativePath, toSet) [inline]
Sets a value at the specified path.
Parameters
relativePath - Path to set value at.
toSet - Value to set.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
set() [2/3]
ImmutableTree::set (relativePath, toSet) [inline]
Sets a value at the specified path.
Parameters
relativePath - Path to set value at.
toSet - Value to set.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
set() [3/3]
ImmutableTree::set (relativePath, toSet) [inline]
Sets a value at the specified path.
Parameters
relativePath - Path to set value at.
toSet - Value to set.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
setTree() [1/3]
ImmutableTree::setTree (relativePath, newTree) [inline]
Replace the subtree at the specified path with the given new tree.
Parameters
relativePath - Path to replace subtree for.
newTree - New tree.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
setTree() [2/3]
ImmutableTree::setTree (relativePath, newTree) [inline]
Replace the subtree at the specified path with the given new tree.
Parameters
relativePath - Path to replace subtree for.
newTree - New tree.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
setTree() [3/3]
ImmutableTree::setTree (relativePath, newTree) [inline]
Replace the subtree at the specified path with the given new tree.
Parameters
relativePath - Path to replace subtree for.
newTree - New tree.
Returns
Resulting tree.
References front, pathGetFront(), pathIsEmpty(), pathPopFront(), and value.
subtree() [1/3]
ImmutableTree::subtree (relativePath) [inline]
Returns
The subtree at the given path
References front, pathGetFront(), pathIsEmpty(), and pathPopFront().
subtree() [2/3]
ImmutableTree::subtree (relativePath) [inline]
Returns
The subtree at the given path
References front, pathGetFront(), pathIsEmpty(), and pathPopFront().
subtree() [3/3]
ImmutableTree::subtree (relativePath) [inline]
Returns
The subtree at the given path
References front, pathGetFront(), pathIsEmpty(), and pathPopFront().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js