LocationsClient Class Reference
Public Member Functions
constructor (gaxGrpc, opts)
initialize ()
getProjectId (callback)
getLocation (request, optionsOrCallback, callback)
listLocations (request, optionsOrCallback, callback)
listLocationsAsync (request, options)
close ()
Static Public Member Functions
static get servicePath ()
static get apiEndpoint ()
static get port ()
static get scopes ()
Detailed Description
Google Cloud Locations Client. This is manually written for providing methods [listLocations, getLocations] to the generated client.
Member Function Documentation
apiEndpoint()
static get LocationsClient::apiEndpoint () [inline], [static]
The DNS address for this API service - same as servicePath(), exists for compatibility reasons.
Returns
{string} The DNS address for this service.
close()
LocationsClient::close () [inline]
Terminate the gRPC channel and close the client.
The client will no longer be usable and all future behavior is undefined.
Returns
{Promise} A promise that resolves when the client is closed.
References initialize(), and Promise.
constructor()
LocationsClient::constructor (gaxGrpc, opts) [inline]
Construct an instance of LocationsClient.
Parameters
{object} [options] - The configuration object. The options accepted by the constructor are described in detail in this document. The common options are:
{object} [options.credentials] - Credentials object.
{string} [options.credentials.client_email]
{string} [options.credentials.private_key]
{string} [options.email] - Account email address. Required when using a .pem or .p12 keyFilename.
{string} [options.keyFilename] - Full path to the a .json, .pem, or .p12 key downloaded from the Google Developers Console. If you provide a path to a JSON file, the projectId option below is not necessary. NOTE: .pem and .p12 require you to specify options.email as well.
{number} [options.port] - The port on which to connect to the remote host.
{string} [options.projectId] - The project ID from the Google Developer's Console, e.g. 'grape-spaceship-123'. We will also check the environment variable GCLOUD_PROJECT for your project ID. If your app is running in an environment which supports Application Default Credentials, your project ID will be detected automatically.
{string} [options.apiEndpoint] - The domain name of the API remote host.
{gax.ClientConfig} [options.clientConfig] - Client configuration override. Follows the structure of gapicConfig.
{boolean} [options.fallback] - Use HTTP fallback mode. In fallback mode, a special browser-compatible transport implementation is used instead of gRPC transport. In browser context (if the window object is defined) the fallback mode is enabled automatically; set options.fallback to false if you need to override this behavior.
References $, _a, _b, auth, constructor, fallback, gapicConfig, gax, grpc, jsonProtos, listLocations(), node, pageDescriptor_1, port(), process, rest(), servicePath(), stream, version, warn, warnings_1, and window.
getLocation()
LocationsClient::getLocation (request, optionsOrCallback, callback) [inline]
References callback, initialize(), name, request, routingHeader, and undefined.
getProjectId()
LocationsClient::getProjectId (callback) [inline]
References auth, and callback.
initialize()
LocationsClient::initialize () [inline]
Initialize the client. Performs asynchronous operations (such as authentication) and prepares the client. This function will be called automatically when any class method is called for the first time, but if you need to initialize it before calling an actual method, feel free to call initialize() directly.
You can await on this method if you want to make sure the client is initialized.
Returns
{Promise} A promise that resolves to an authenticated service stub.
References args, createApiCall_1, descriptor, func, of, Promise, and undefined.
listLocations()
LocationsClient::listLocations (request, optionsOrCallback, callback) [inline]
Lists information about the supported locations for this service.
Parameters
{Object} request The request object that will be sent.
{string} request.name The resource that owns the locations collection, if applicable.
{string} request.filter The standard list filter.
{number} request.pageSize The standard list page size.
{string} request.pageToken The standard list page token.
{object} [options] Call options. See https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions for more details.
Returns
{Promise} - The promise which resolves to an array. The first element of the array is Array of [Location]google.cloud.location.Location. The client library will perform auto-pagination by default: it will call the API as many times as needed and will merge results from all the pages into this array. Note that it can affect your quota. We recommend using listLocationsAsync() method described below for async iteration which you can stop as needed. Please see the documentation for more details and examples.
References callback, initialize(), name, request, routingHeader, and undefined.
listLocationsAsync()
LocationsClient::listLocationsAsync (request, options) [inline]
References gax, initialize(), name, request, and routingHeader.
port()
static get LocationsClient::port () [inline], [static]
The port for this API service.
Returns
{number} The default port for this service.
scopes()
static get LocationsClient::scopes () [inline], [static]
The scopes needed to make gRPC calls for every method defined in this service.
Returns
{string[]} List of default scopes.
servicePath()
static get LocationsClient::servicePath () [inline], [static]
The DNS address for this API service.
Returns
{string} The DNS address for this service.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/locationService.js