CompletionListener Class Reference
Public Member Functions
constructor ({ successCondition='all', scheduler, })
isSuccess (events)
listen (commands, abortSignal)
emitWithScheduler (input)
Public Attributes
successCondition
scheduler
Detailed Description
Provides logic to determine whether lists of commands ran successfully.
Member Function Documentation
constructor()
CompletionListener::constructor ({ successCondition='all', scheduler, }) [inline]
References scheduler, and successCondition.
emitWithScheduler()
CompletionListener::emitWithScheduler (input) [inline]
References Rx, and scheduler.
isSuccess()
CompletionListener::isSuccess (events) [inline]
References $, command(), event, index, and successCondition.
listen()
CompletionListener::listen (commands, abortSignal) [inline]
Given a list of commands, wait for all of them to exit and then evaluate their exit codes.
Returns
A Promise that resolves if the success condition is met, or rejects otherwise. In either case, the value is a list of close events for commands that spawned. Commands that didn't spawn are filtered out.
References abort, abortSignal(), command(), commands, event, first, once, operators_1, pipe, Rx, and undefined.
Member Data Documentation
scheduler
CompletionListener::scheduler
successCondition
CompletionListener::successCondition
The documentation for this class was generated from the following file:
backend/node_modules/concurrently/dist/src/completion-listener.js