CacheNode Class Reference
Public Member Functions
constructor (node_, fullyInitialized_, filtered_)
isFullyInitialized ()
isFiltered ()
isCompleteForPath (path)
isCompleteForChild (key)
getNode ()
constructor (node_, fullyInitialized_, filtered_)
isFullyInitialized ()
isFiltered ()
isCompleteForPath (path)
isCompleteForChild (key)
getNode ()
constructor (node_, fullyInitialized_, filtered_)
isFullyInitialized ()
isFiltered ()
isCompleteForPath (path)
isCompleteForChild (key)
getNode ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. A cache node only stores complete children. Additionally it holds a flag whether the node can be considered fully initialized in the sense that we know at one point in time this represented a valid state of the world, e.g. initialized with data from the server, or a complete overwrite by the client. The filtered flag also tracks whether a node potentially had children removed due to a filter.
Member Function Documentation
constructor() [1/3]
CacheNode::constructor (node_, fullyInitialized_, filtered_) [inline]
constructor() [2/3]
CacheNode::constructor (node_, fullyInitialized_, filtered_) [inline]
constructor() [3/3]
CacheNode::constructor (node_, fullyInitialized_, filtered_) [inline]
getNode() [1/3]
CacheNode::getNode () [inline]
getNode() [2/3]
CacheNode::getNode () [inline]
getNode() [3/3]
CacheNode::getNode () [inline]
isCompleteForChild() [1/3]
CacheNode::isCompleteForChild (key) [inline]
References isFullyInitialized().
isCompleteForChild() [2/3]
CacheNode::isCompleteForChild (key) [inline]
References isFullyInitialized().
isCompleteForChild() [3/3]
CacheNode::isCompleteForChild (key) [inline]
References isFullyInitialized().
isCompleteForPath() [1/3]
CacheNode::isCompleteForPath (path) [inline]
References isCompleteForChild(), isFullyInitialized(), path, pathGetFront(), and pathIsEmpty().
isCompleteForPath() [2/3]
CacheNode::isCompleteForPath (path) [inline]
References isCompleteForChild(), isFullyInitialized(), path, pathGetFront(), and pathIsEmpty().
isCompleteForPath() [3/3]
CacheNode::isCompleteForPath (path) [inline]
References isCompleteForChild(), isFullyInitialized(), path, pathGetFront(), and pathIsEmpty().
isFiltered() [1/3]
CacheNode::isFiltered () [inline]
Returns whether this node is potentially missing children due to a filter applied to the node
isFiltered() [2/3]
CacheNode::isFiltered () [inline]
Returns whether this node is potentially missing children due to a filter applied to the node
isFiltered() [3/3]
CacheNode::isFiltered () [inline]
Returns whether this node is potentially missing children due to a filter applied to the node
isFullyInitialized() [1/3]
CacheNode::isFullyInitialized () [inline]
Returns whether this node was fully initialized with either server data or a complete overwrite by the client Here is the caller graph for this function:
isFullyInitialized() [2/3]
CacheNode::isFullyInitialized () [inline]
Returns whether this node was fully initialized with either server data or a complete overwrite by the client
isFullyInitialized() [3/3]
CacheNode::isFullyInitialized () [inline]
Returns whether this node was fully initialized with either server data or a complete overwrite by the client
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js