JsObjBuilder Class Reference
Public Member Functions
constructor (parserOptions, builderOptions, registeredParsers)
addTag (tag)
closeTag ()
_addChild (key, val)
_addChildTo (key, val, node)
addValue (text)
addPi (name)
getOutput ()
constructor ()
addAttribute (name, value)
addDeclaration ()
Public Attributes
parseValue
Member Function Documentation
_addChild()
JsObjBuilder::_addChild (key, val) [inline]
References _addChildTo(), and value.
_addChildTo()
JsObjBuilder::_addChildTo (key, val, node) [inline]
References Array, and node.
addAttribute()
BaseOutputBuilder::addAttribute (name, value) [inline], [inherited]
References name, BaseOutputBuilder::parseValue, v, and value.
addDeclaration()
BaseOutputBuilder::addDeclaration () [inline], [inherited]
addPi()
JsObjBuilder::addPi (name) [inline]
References _addChild(), isEmpty, name, and value.
addTag()
JsObjBuilder::addTag (tag) [inline]
References isEmpty, and value.
addValue()
JsObjBuilder::addValue (text) [inline]
Add text value child node
Parameters
{string} text
References text.
closeTag()
JsObjBuilder::closeTag () [inline]
Check if the node should be added by checking user's preference
Parameters
{Node} node
Returns
boolean: true if the node should not be added
References _addChildTo(), Array, node, BaseOutputBuilder::parseValue, TagPathMatcher, undefined, and value.
constructor() [1/2]
BaseOutputBuilder::constructor () [inline], [inherited]
constructor() [2/2]
JsObjBuilder::constructor (parserOptions, builderOptions, registeredParsers) [inline]
References parent, root, rootName, and value.
getOutput()
JsObjBuilder::getOutput () [inline]
References value.
Member Data Documentation
parseValue
BaseOutputBuilder::parseValue [inherited]
parse value by chain of parsers
Parameters
{string} val
Returns
{any} parsed value if matching parser found
The documentation for this class was generated from the following file:
backend/node_modules/fast-xml-parser/src/v5/OutputBuilders/JsObjBuilder.js