LocalJWKSet Class Reference
Public Member Functions
constructor (jwks)
async getKey (protectedHeader, token)
constructor (jwks)
async getKey (protectedHeader, token)
constructor (jwks)
async getKey (protectedHeader, token)
Member Function Documentation
constructor() [1/3]
LocalJWKSet::constructor (jwks) [inline]
References clone, isJWKSLike, jwks, JWKSInvalid, and WeakMap.
constructor() [2/3]
LocalJWKSet::constructor (jwks) [inline]
References clone, errors_js_1, isJWKSLike, jwks, and WeakMap.
constructor() [3/3]
LocalJWKSet::constructor (jwks) [inline]
References clone, isJWKSLike, jwks, JWKSInvalid, and WeakMap.
getKey() [1/3]
async LocalJWKSet::getKey (protectedHeader, token) [inline]
References _a, Array, async, error, getKtyFromAlg(), importWithAlgCache(), JWKSMultipleMatchingKeys, JWKSNoMatchingKey, length, of, Symbol, and token.
getKey() [2/3]
async LocalJWKSet::getKey (protectedHeader, token) [inline]
References Array, async, error, errors_js_1, getKtyFromAlg(), importWithAlgCache(), length, of, Symbol, and token.
getKey() [3/3]
async LocalJWKSet::getKey (protectedHeader, token) [inline]
References Array, async, error, getKtyFromAlg(), importWithAlgCache(), JWKSMultipleMatchingKeys, JWKSNoMatchingKey, length, of, Symbol, and token.
The documentation for this class was generated from the following files:
backend/node_modules/jose/dist/browser/jwks/local.js
backend/node_modules/jose/dist/node/cjs/jwks/local.js
backend/node_modules/jose/dist/node/esm/jwks/local.js