PublicKeySignatureVerifier Class Reference
Public Member Functions
constructor (keyFetcher)
verify (token)
verifyWithoutKid (token)
verifyWithAllKeys (token, keys)
Static Public Member Functions
static withCertificateUrl (clientCertUrl, httpAgent)
static withJwksUrl (jwksUrl, httpAgent)
Detailed Description
Class for verifying JWT signature with a public key.
Member Function Documentation
constructor()
PublicKeySignatureVerifier::constructor (keyFetcher) [inline]
References validator.
verify()
PublicKeySignatureVerifier::verify (token) [inline]
References algorithms, error, exports, getKeyCallback(), JwtError, JwtErrorCode, Promise, token, validator, verifyJwtSignature, and verifyWithoutKid().
verifyWithAllKeys()
PublicKeySignatureVerifier::verifyWithAllKeys (token, keys) [inline]
References error, JwtError, JwtErrorCode, keys, Promise, r, result, token, and verifyJwtSignature.
verifyWithoutKid()
PublicKeySignatureVerifier::verifyWithoutKid (token) [inline]
References token, and verifyWithAllKeys().
withCertificateUrl()
static PublicKeySignatureVerifier::withCertificateUrl (clientCertUrl, httpAgent) [inline], [static]
References PublicKeySignatureVerifier, and UrlKeyFetcher.
withJwksUrl()
static PublicKeySignatureVerifier::withJwksUrl (jwksUrl, httpAgent) [inline], [static]
References JwksFetcher, and PublicKeySignatureVerifier.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/jwt.js