DataConnectApiClient Class Reference
Public Member Functions
constructor (connectorConfig, app)
async executeGraphql (query, options)
async executeGraphqlRead (query, options)
async executeGraphqlHelper (query, endpoint, options)
async getUrl (host, locationId, serviceId, endpointId)
getProjectId ()
toFirebaseError (err)
Detailed Description
Class that facilitates sending requests to the Firebase Data Connect backend API.
Member Function Documentation
constructor()
DataConnectApiClient::constructor (connectorConfig, app) [inline]
References api_request_1, app, exports, FirebaseDataConnectError, and validator.
executeGraphql()
async DataConnectApiClient::executeGraphql (query, options) [inline]
Execute arbitrary GraphQL, including both read and write queries
Parameters
query - The GraphQL string to be executed.
options - GraphQL Options
Returns
A promise that fulfills with a ExecuteGraphqlResponse.
References EXECUTE_GRAPH_QL_ENDPOINT, executeGraphqlHelper(), and query.
executeGraphqlHelper()
async DataConnectApiClient::executeGraphqlHelper (query, endpoint, options) [inline]
References async, data, DATA_CONNECT_CONFIG_HEADERS, DATA_CONNECT_HOST, error, exports, FirebaseDataConnectError, getUrl(), headers, method, process, Promise, query, request, then, toFirebaseError(), url, and validator.
executeGraphqlRead()
async DataConnectApiClient::executeGraphqlRead (query, options) [inline]
Execute arbitrary read-only GraphQL queries
Parameters
query - The GraphQL (read-only) string to be executed.
options - GraphQL Options
Returns
A promise that fulfills with a ExecuteGraphqlResponse.
Exceptions
FirebaseDataConnectError
References EXECUTE_GRAPH_QL_READ_ENDPOINT, executeGraphqlHelper(), and query.
getProjectId()
DataConnectApiClient::getProjectId () [inline]
References app, exports, FirebaseDataConnectError, Promise, utils, and validator.
getUrl()
async DataConnectApiClient::getUrl (host, locationId, serviceId, endpointId) [inline]
References getProjectId(), and utils.
toFirebaseError()
DataConnectApiClient::toFirebaseError (err) [inline]
References $, and, error, error_1, exports, FirebaseDataConnectError, message, response, server, and status.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/data-connect/data-connect-api-client-internal.js