ClientPool Class Reference
Public Member Functions
constructor (concurrentOperationLimit, maxIdleClients, clientFactory, clientDestructor=()=> Promise.resolve())
async terminate ()
Private Member Functions
acquire (requestTag, requiresGrpc)
async release (requestTag, client)
shouldGarbageCollectClient (client)
get size ()
get opCount ()
get _activeClients ()
run (requestTag, requiresGrpc, op)
Detailed Description
An auto-resizing pool that distributes concurrent operations over multiple clients of type T.
ClientPool is used within Firestore to manage a pool of GAPIC clients and automatically initializes multiple clients if we issue more than 100 concurrent operations.
Member Function Documentation
_activeClients()
get ClientPool::_activeClients () [inline], [private]
The currently active clients.
Returns
The currently active clients.
acquire()
ClientPool::acquire (requestTag, requiresGrpc) [inline], [private]
Returns an already existing client if it has less than the maximum number of concurrent operations or initializes and returns a new client.
References assert, client, logger_1, of, and requestTag.
constructor()
ClientPool::constructor (concurrentOperationLimit, maxIdleClients, clientFactory, clientDestructor = () =, Promise. resolve()) [inline]
Parameters
concurrentOperationLimit The number of operations that each client can handle.
maxIdleClients The maximum number of idle clients to keep before garbage collecting.
clientFactory A factory function called as needed when new clients are required.
clientDestructor A cleanup function that is called when a client is disposed of.
Stores each active clients and how many operations it has outstanding.
A set of clients that have seen RST_STREAM errors (see https://github.com/googleapis/nodejs-firestore/issues/1023) and should no longer be used.
Whether the Firestore instance has been terminated. Once terminated, the ClientPool can longer schedule new operations.
Deferred promise that is resolved when there are no active operations on the client pool after terminate() has been called.
References Map, Set, and util_1.
opCount()
get ClientPool::opCount () [inline], [private]
The number of currently active operations.
Returns
Number of currently active operations.
release()
async ClientPool::release (requestTag, client) [inline], [private]
Reduces the number of operations for the provided client, potentially removing it from the pool of active clients.
References assert, client, logger_1, opCount(), requestTag, and shouldGarbageCollectClient().
run()
ClientPool::run (requestTag, requiresGrpc, op) [inline], [private]
Runs the provided operation in this pool. This function may create an additional client if all existing clients already operate at the concurrent operation limit.
Parameters
requestTag A unique client-assigned identifier for this operation.
op A callback function that returns a Promise. The client T will be returned to the pool when callback finishes.
Returns
A Promise that resolves with the result of op.
References _a, acquire(), async, client, exports, Promise, release, requestTag, res, and then.
shouldGarbageCollectClient()
ClientPool::shouldGarbageCollectClient (client) [inline], [private]
Given the current operation counts, determines if the given client should be garbage collected.
References client, and of.
size()
get ClientPool::size () [inline], [private]
The number of currently registered clients.
Returns
Number of currently registered clients.
terminate()
async ClientPool::terminate () [inline]
References client, logger_1, of, and opCount().
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/pool.js