ColdObservable Class Reference
Public Member Functions
constructor (messages, scheduler)
scheduleMessages (subscriber)
constructor (subscribe)
lift (operator)
subscribe (observerOrNext, error, complete)
_trySubscribe (sink)
forEach (next, promiseCtor)
_subscribe (subscriber)
pipe (...operations)
toPromise (promiseCtor)
Member Function Documentation
_subscribe()
Observable::_subscribe (subscriber) [inline], [inherited]
References _a, and source.
_trySubscribe()
Observable::_trySubscribe (sink) [inline], [inherited]
References Observable::_subscribe().
constructor() [1/2]
ColdObservable::constructor (messages, scheduler) [inline]
References index, and Subscription.
constructor() [2/2]
Observable::constructor (subscribe) [inline], [inherited]
References Observable::_subscribe(), and Observable::subscribe().
forEach()
Observable::forEach (next, promiseCtor) [inline], [inherited]
References error, getPromiseCtor(), next(), reject(), resolve, SafeSubscriber, Observable::subscribe(), and value.
lift()
Observable::lift (operator) [inline], [inherited]
References Observable, and observable.
pipe()
Observable::pipe (...) [inline], [inherited]
References pipeFromArray.
scheduleMessages()
ColdObservable::scheduleMessages (subscriber) [inline]
References i, message, observeNotification, and state().
subscribe()
Observable::subscribe (observerOrNext, error, complete) [inline], [inherited]
References Observable::_subscribe(), Observable::_trySubscribe(), call, error, errorContext, isSubscriber(), SafeSubscriber, and source.
toPromise()
Observable::toPromise (promiseCtor) [inline], [inherited]
References getPromiseCtor(), reject(), resolve, Observable::subscribe(), and value.
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/testing/ColdObservable.js