DocumentReference Class Reference
Public Member Functions
 DocumentReference#firestore
The [Firestore]Firestore instance for the Firestore database (useful for performing transactions, etc.).
@type {Firestore}
@readonly
get firestore ()
 DocumentReference#path
A string representing the path of the referenced document (relative to the root of the database).
@type {string}
@readonly
get path ()
Private Member Functions
constructor (_firestore, _path, _converter=(0, types_1.defaultConverter)())
get formattedName ()
DocumentReference#id
The last path element of the referenced document.
@type {string}
@readonly
get _resourcePath ()
get id ()
DocumentReference#parent
A reference to the collection to which this DocumentReference belongs.
@type {CollectionReference} @readonly
toProto ()
get parent ()
get ()
collection (collectionPath)
listCollections ()
create (data)
delete (precondition)
set (data, options)
update (dataOrField,...preconditionOrValues)
onSnapshot (onNext, onError)
isEqual (other)
withConverter (converter)
Detailed Description
A DocumentReference refers to a document location in a Firestore database and can be used to write, read, or listen to the location. The document at the referenced location may or may not exist. A DocumentReference can also be used to create a [CollectionReference]CollectionReference to a subcollection.
Member Function Documentation
_resourcePath()
get DocumentReference::_resourcePath () [inline], [private]
Returns a resource path for this document.
collection()
DocumentReference::collection (collectionPath) [inline]
References _firestore, a, an, collection(), collection_reference_1, not, of, path(), and path_1.
constructor()
DocumentReference::constructor (_firestore, _path, _converter = (0, types_1.defaultConverter)()) [inline], [private]
References _firestore.
create()
DocumentReference::create (data) [inline]
References _firestore, and trace_util_1.
delete()
DocumentReference::delete (precondition) [inline]
References _firestore, and trace_util_1.
firestore()
get DocumentReference::firestore () [inline]
References _firestore.
formattedName()
get DocumentReference::formattedName () [inline], [private]
The string representation of the DocumentReference's location.
References firestore().
get()
DocumentReference::get () [inline]
References _firestore, and trace_util_1.
id()
get DocumentReference::id () [inline]
isEqual()
DocumentReference::isEqual (other) [inline]
Returns true if this DocumentReference is equal to the provided value.
Parameters
{*} other The value to compare against.
Returns
{boolean} true if this DocumentReference is equal to the provided value.
References _firestore, and isEqual().
listCollections()
DocumentReference::listCollections () [inline]
References _firestore, and trace_util_1.
onSnapshot()
DocumentReference::onSnapshot (onNext, onError) [inline]
References _firestore, document_1, DocumentReference, firestore, of, require(), size, and validate_1.
parent()
get DocumentReference::parent () [inline]
References _firestore, and collection_reference_1.
path()
get DocumentReference::path () [inline]
set()
DocumentReference::set (data, options) [inline]
References _firestore, and trace_util_1.
toProto()
DocumentReference::toProto () [inline], [private]
Converts this DocumentReference to the Firestore Proto representation.
update()
DocumentReference::update (dataOrField, ...) [inline]
References _firestore, and trace_util_1.
withConverter()
DocumentReference::withConverter (converter) [inline]
References converter, DocumentReference, firestore, and types_1.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/reference/document-reference.js