Metadata Class Reference
Public Member Functions
constructor (options={})
set (key, value)
add (key, value)
remove (key)
get (key)
getMap ()
clone ()
merge (other)
setOptions (options)
getOptions ()
toHttp2Headers ()
toJSON ()
Static Public Member Functions
static fromHttp2Headers (headers)
Detailed Description
A class for storing metadata. Keys are normalized to lowercase ASCII.
Member Function Documentation
add()
Metadata::add (key, value) [inline]
Adds the given value for the given key by appending to a list of previous values associated with that key. Normalizes the key.
Parameters
key The key for which a new value should be appended.
value The value to add. Must be a buffer if and only if the normalized key ends with '-bin'.
References normalizeKey(), undefined, validate, and value.
clone()
Metadata::clone () [inline]
Clones the metadata object.
Returns
The newly cloned object.
References Metadata, of, v, and value.
constructor()
Metadata::constructor (options = {}) [inline]
fromHttp2Headers()
static Metadata::fromHttp2Headers (headers) [inline], [static]
Returns a new Metadata object based fields in a given IncomingHttpHeaders object.
Parameters
headers An IncomingHttpHeaders object.
References $, add, Array, constants_1, error, error_1, headers, https, isBinaryKey(), isCustomMetadata(), logging_1, message, Metadata, of, result, undefined, v, value, and values.
get()
Metadata::get (key) [inline]
Gets a list of all values associated with the key. Normalizes the key.
Parameters
key The key whose value should be retrieved.
Returns
A list of values associated with the given key.
References normalizeKey().
getMap()
Metadata::getMap () [inline]
Gets a plain object mapping each key to the first value associated with it. This reflects the most common way that people will want to see metadata.
Returns
A key/value mapping of the metadata.
References of, result, v, and values.
getOptions()
Metadata::getOptions () [inline]
merge()
Metadata::merge (other) [inline]
Merges all key-value pairs from a given Metadata object into this one. If both this object and the given object have values in the same key, values from the other Metadata object will be appended to this object's values.
Parameters
other A Metadata object.
References of, and values.
remove()
Metadata::remove (key) [inline]
Removes the given key and any associated values. Normalizes the key.
Parameters
key The key whose values should be removed.
References normalizeKey().
set()
Metadata::set (key, value) [inline]
Sets the given value for the given key by replacing any other values associated with that key. Normalizes the key.
Parameters
key The key to whose value should be set.
value The value to set. Must be a buffer if and only if the normalized key ends with '-bin'.
References normalizeKey(), validate, and value.
setOptions()
Metadata::setOptions (options) [inline]
toHttp2Headers()
Metadata::toHttp2Headers () [inline]
Creates an OutgoingHttpHeaders object that can be used with the http2 API.
References bufToString, of, result, and values.
toJSON()
Metadata::toJSON () [inline]
This modifies the behavior of JSON.stringify to show an object representation of the metadata map.
References of, result, and values.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/metadata.js