DocumentMask Class Reference
Private Member Functions
constructor (fieldPaths)
get isEmpty ()
removeFields (fieldPaths)
contains (fieldPath)
applyTo (data)
toProto ()
Static Private Member Functions
static fromUpdateMap (data)
static fromFieldMask (fieldMask)
static fromObject (data)
static removeFromSortedArray (input, values)
Detailed Description
A Firestore Document Mask contains the field paths affected by an update.
Member Function Documentation
applyTo()
DocumentMask::applyTo (data) [inline], [private]
Removes all properties from 'data' that are not contained in this document mask. Applies this DocumentMask to 'data' and computes the list of field paths that were specified in the mask but are not present in 'data'.
References contains, data, is, missing(), path_1, removeFromSortedArray(), result, and util_1.
constructor()
DocumentMask::constructor (fieldPaths) [inline], [private]
References a, and b.
contains()
DocumentMask::contains (fieldPath) [inline], [private]
Returns whether this document mask contains 'fieldPath'.
References of.
fromFieldMask()
static DocumentMask::fromFieldMask (fieldMask) [inline], [static], [private]
Creates a document mask from an array of field paths.
References DocumentMask, of, and path_1.
fromObject()
static DocumentMask::fromObject (data) [inline], [static], [private]
Creates a document mask with the field names of a document.
References data, DocumentMask, field_value_1, isEmpty(), of, path_1, undefined, util_1, and value.
fromUpdateMap()
static DocumentMask::fromUpdateMap (data) [inline], [static], [private]
Creates a document mask with the field paths of a document.
References data, DocumentMask, field_value_1, path_1, and value.
isEmpty()
get DocumentMask::isEmpty () [inline], [private]
Returns true if this document mask contains no fields. Here is the caller graph for this function:
removeFields()
DocumentMask::removeFields (fieldPaths) [inline], [private]
Removes the field path specified in 'fieldPaths' from this document mask.
References removeFromSortedArray().
removeFromSortedArray()
static DocumentMask::removeFromSortedArray (input, values) [inline], [static], [private]
Removes the specified values from a sorted field path array.
References i, isEqual, of, and values.
toProto()
DocumentMask::toProto () [inline], [private]
Converts a document mask to the Firestore 'DocumentMask' Proto.
References isEmpty(), and of.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/document.js