PathIndex Class Reference
Public Member Functions
constructor (indexPath_)
extractChild (snap)
isDefinedOn (node)
compare (a, b)
makePost (indexValue, name)
maxPost ()
toString ()
constructor (indexPath_)
extractChild (snap)
isDefinedOn (node)
compare (a, b)
makePost (indexValue, name)
maxPost ()
toString ()
constructor (indexPath_)
extractChild (snap)
isDefinedOn (node)
compare (a, b)
makePost (indexValue, name)
maxPost ()
toString ()
getCompare ()
getCompare ()
getCompare ()
indexedValueChanged (oldNode, newNode)
indexedValueChanged (oldNode, newNode)
indexedValueChanged (oldNode, newNode)
minPost ()
minPost ()
minPost ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Member Function Documentation
compare() [1/3]
PathIndex::compare (a, b) [inline]
References a, b, extractChild(), and nameCompare.
compare() [2/3]
PathIndex::compare (a, b) [inline]
References a, b, extractChild(), and nameCompare.
compare() [3/3]
PathIndex::compare (a, b) [inline]
References a, b, extractChild(), and nameCompare.
constructor() [1/3]
PathIndex::constructor (indexPath_) [inline]
References pathGetFront(), pathIsEmpty(), and util.
constructor() [2/3]
PathIndex::constructor (indexPath_) [inline]
References assert, pathGetFront(), and pathIsEmpty().
constructor() [3/3]
PathIndex::constructor (indexPath_) [inline]
References assert, pathGetFront(), and pathIsEmpty().
extractChild() [1/3]
PathIndex::extractChild (snap) [inline]
extractChild() [2/3]
PathIndex::extractChild (snap) [inline]
extractChild() [3/3]
PathIndex::extractChild (snap) [inline]
getCompare() [1/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
getCompare() [2/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
getCompare() [3/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
indexedValueChanged() [1/3]
Index::indexedValueChanged (oldNode, newNode) [inline], [inherited]
Given a before and after value for a node, determine if the indexed value has changed. Even if they are different, it's possible that the changes are isolated to parts of the snapshot that are not indexed.
Returns
True if the portion of the snapshot being indexed changed between oldNode and newNode
References compare, and MIN_NAME.
indexedValueChanged() [2/3]
Index::indexedValueChanged (oldNode, newNode) [inline], [inherited]
Given a before and after value for a node, determine if the indexed value has changed. Even if they are different, it's possible that the changes are isolated to parts of the snapshot that are not indexed.
Returns
True if the portion of the snapshot being indexed changed between oldNode and newNode
References compare, and MIN_NAME.
indexedValueChanged() [3/3]
Index::indexedValueChanged (oldNode, newNode) [inline], [inherited]
Given a before and after value for a node, determine if the indexed value has changed. Even if they are different, it's possible that the changes are isolated to parts of the snapshot that are not indexed.
Returns
True if the portion of the snapshot being indexed changed between oldNode and newNode
References compare, and MIN_NAME.
isDefinedOn() [1/3]
PathIndex::isDefinedOn (node) [inline]
References node.
isDefinedOn() [2/3]
PathIndex::isDefinedOn (node) [inline]
References node.
isDefinedOn() [3/3]
PathIndex::isDefinedOn (node) [inline]
References node.
makePost() [1/3]
PathIndex::makePost (indexValue, name) [inline]
References ChildrenNode::EMPTY_NODE(), name, node, and nodeFromJSON().
makePost() [2/3]
PathIndex::makePost (indexValue, name) [inline]
References ChildrenNode::EMPTY_NODE(), name, node, and nodeFromJSON().
makePost() [3/3]
PathIndex::makePost (indexValue, name) [inline]
References ChildrenNode::EMPTY_NODE(), name, node, and nodeFromJSON().
maxPost() [1/3]
PathIndex::maxPost () [inline]
References ChildrenNode::EMPTY_NODE(), MAX_NAME, MAX_NODE, and node.
maxPost() [2/3]
PathIndex::maxPost () [inline]
References ChildrenNode::EMPTY_NODE(), MAX_NAME, MAX_NODE, and node.
maxPost() [3/3]
PathIndex::maxPost () [inline]
References ChildrenNode::EMPTY_NODE(), MAX_NAME, MAX_NODE, and node.
minPost() [1/3]
Index::minPost () [inline], [inherited]
Returns
a node wrapper that will sort equal to or less than any other node wrapper, using this index
minPost() [2/3]
Index::minPost () [inline], [inherited]
Returns
a node wrapper that will sort equal to or less than any other node wrapper, using this index
minPost() [3/3]
Index::minPost () [inline], [inherited]
Returns
a node wrapper that will sort equal to or less than any other node wrapper, using this index
toString() [1/3]
PathIndex::toString () [inline]
References pathSlice().
toString() [2/3]
PathIndex::toString () [inline]
References pathSlice().
toString() [3/3]
PathIndex::toString () [inline]
References pathSlice().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js