Blob Class Reference
Public Member Functions
constructor ()
get size ()
get type ()
text ()
arrayBuffer ()
stream ()
toString ()
slice ()
constructor ()
get size ()
get type ()
text ()
arrayBuffer ()
stream ()
toString ()
slice ()
Member Function Documentation
arrayBuffer() [1/2]
Blob::arrayBuffer () [inline]
References buf, BUFFER, and Promise.
arrayBuffer() [2/2]
Blob::arrayBuffer () [inline]
References buf, BUFFER, and Promise.
constructor() [1/2]
Blob::constructor () [inline]
References a, BUFFER, buffer, i, length, size(), test, TYPE, type(), and undefined.
constructor() [2/2]
Blob::constructor () [inline]
References a, BUFFER, buffer, i, length, size(), test, TYPE, type(), and undefined.
size() [1/2]
get Blob::size () [inline]
References BUFFER.
size() [2/2]
get Blob::size () [inline]
References BUFFER.
slice() [1/2]
Blob::slice () [inline]
References BUFFER, buffer, end, size(), start, type(), and undefined.
slice() [2/2]
Blob::slice () [inline]
References BUFFER, buffer, end, size(), start, type(), and undefined.
stream() [1/2]
Blob::stream () [inline]
References BUFFER, Readable, and readable.
stream() [2/2]
Blob::stream () [inline]
References BUFFER, Readable, and readable.
text() [1/2]
Blob::text () [inline]
References BUFFER, Promise, and toString().
text() [2/2]
Blob::text () [inline]
References BUFFER, Promise, and toString().
toString() [1/2]
Blob::toString () [inline]
toString() [2/2]
Blob::toString () [inline]
type() [1/2]
get Blob::type () [inline]
References TYPE.
type() [2/2]
get Blob::type () [inline]
References TYPE.
The documentation for this class was generated from the following files:
backend/node_modules/node-fetch/lib/index.es.js
backend/node_modules/node-fetch/lib/index.js