CallCredentials Class Reference
Static Public Member Functions
static createFromMetadataGenerator (metadataGenerator)
static createFromGoogleCredential (googleCredentials)
static createEmpty ()
Detailed Description
A class that represents a generic method of adding authentication-related metadata on a per-request basis.
Member Function Documentation
createEmpty()
static CallCredentials::createEmpty () [inline], [static]
createFromGoogleCredential()
static CallCredentials::createFromGoogleCredential (googleCredentials) [inline], [static]
Create a gRPC credential from a Google credential object.
Parameters
googleCredentials The authentication client to use.
Returns
The resulting CallCredentials object.
References callback, createFromMetadataGenerator(), getHeaders, headers, if(), isCurrentOauth2Client(), metadata_1, of, Promise, reject(), and resolve.
createFromMetadataGenerator()
static CallCredentials::createFromMetadataGenerator (metadataGenerator) [inline], [static]
Creates a new CallCredentials object from a given function that generates Metadata objects.
Parameters
metadataGenerator A function that accepts a set of options, and generates a Metadata object based on these options, which is passed back to the caller via a supplied (err, metadata) callback.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/call-credentials.js