Http2SubchannelCall Class Reference
Public Member Functions
constructor (http2Stream, callEventTracker, listener, transport, callId)
getDeadlineInfo ()
onDisconnect ()
outputStatus ()
trace (text)
endCall (status)
maybeOutputStatus ()
push (message)
tryPush (messageBytes)
handleTrailers (headers)
destroyHttp2Stream ()
cancelWithStatus (status, details)
getStatus ()
getPeer ()
getCallNumber ()
startRead ()
sendMessageWithContext (context, message)
halfClose ()
Member Function Documentation
cancelWithStatus()
Http2SubchannelCall::cancelWithStatus (status, details) [inline]
References endCall(), metadata_1, status, and trace.
constructor()
Http2SubchannelCall::constructor (http2Stream, callEventTracker, listener, transport, callId) [inline]
Indicates that an 'end' event has come from the http2 stream, so there will be no more data events.
References $, _a, cancelWithStatus(), client, constants_1, data, decoder, e, endCall(), error, getSystemErrorName(), handleTrailers(), headers, http2, mapHttpStatusCode(), maybeOutputStatus(), message, metadata_1, of, process, server, status, stream_decoder_1, trace, tryPush(), and without.
destroyHttp2Stream()
Http2SubchannelCall::destroyHttp2Stream () [inline]
References _a, constants_1, http2, and trace.
endCall()
Http2SubchannelCall::endCall (status) [inline]
On first call, emits a 'status' event with the given StatusObject. Subsequent calls are no-ops.
Parameters
status The status of the call.
References constants_1, destroyHttp2Stream(), maybeOutputStatus(), and status.
getCallNumber()
Http2SubchannelCall::getCallNumber () [inline]
getDeadlineInfo()
Http2SubchannelCall::getDeadlineInfo () [inline]
References $, and getPeer().
getPeer()
Http2SubchannelCall::getPeer () [inline]
getStatus()
Http2SubchannelCall::getStatus () [inline]
halfClose()
Http2SubchannelCall::halfClose () [inline]
References trace.
handleTrailers()
Http2SubchannelCall::handleTrailers (headers) [inline]
References constants_1, e, endCall(), headers, mapHttpStatusCode(), metadata_1, of, status, and trace.
maybeOutputStatus()
Http2SubchannelCall::maybeOutputStatus () [inline]
References constants_1, and outputStatus().
onDisconnect()
Http2SubchannelCall::onDisconnect () [inline]
References constants_1, endCall(), and metadata_1.
outputStatus()
Http2SubchannelCall::outputStatus () [inline]
References process, and trace.
push()
Http2SubchannelCall::push (message) [inline]
References maybeOutputStatus(), message, process, and trace.
sendMessageWithContext()
Http2SubchannelCall::sendMessageWithContext (context, message) [inline]
References $, _a, cancelWithStatus(), constants_1, context, endCall(), error, message, metadata_1, process, and trace.
startRead()
Http2SubchannelCall::startRead () [inline]
References constants_1, maybeOutputStatus(), and push.
trace()
Http2SubchannelCall::trace (text) [inline]
References constants_2, logging, text, and TRACER_NAME.
tryPush()
Http2SubchannelCall::tryPush (messageBytes) [inline]
References push, and trace.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/subchannel-call.js