RetryingCall Class Reference
Public Member Functions
constructor (channel, callConfig, methodName, host, credentials, deadline, callNumber, bufferTracker, retryThrottler)
getDeadlineInfo ()
getCallNumber ()
trace (text)
reportStatus (statusObject)
cancelWithStatus (status, details)
getPeer ()
getBufferEntry (messageIndex)
getNextBufferIndex ()
clearSentMessages ()
commitCall (index)
commitCallWithMostMessages ()
isStatusCodeInList (list, code)
getNextRetryBackoffMs ()
maybeRetryCall (pushback, callback)
countActiveCalls ()
handleProcessedStatus (status, callIndex, pushback)
getPushback (metadata)
handleChildStatus (status, callIndex)
maybeStartHedgingAttempt ()
maybeStartHedgingTimer ()
startNewAttempt ()
start (metadata, listener)
handleChildWriteCompleted (childIndex)
sendNextChildMessage (childIndex)
sendMessageWithContext (context, message)
startRead ()
halfClose ()
setCredentials (newCredentials)
getMethod ()
getHost ()
Member Function Documentation
cancelWithStatus()
RetryingCall::cancelWithStatus (status, details) [inline]
References call, metadata_1, of, reportStatus(), status, and trace.
clearSentMessages()
RetryingCall::clearSentMessages () [inline]
References getBufferEntry(), and state().
commitCall()
RetryingCall::commitCall (index) [inline]
References call, clearSentMessages(), constants_1, i, index, state(), and trace.
commitCallWithMostMessages()
RetryingCall::commitCallWithMostMessages () [inline]
References commitCall(), index, of, and state().
constructor()
RetryingCall::constructor (channel, callConfig, methodName, host, credentials, deadline, callNumber, bufferTracker, retryThrottler) [inline]
The offset of message indices in the writeBuffer. For example, if writeBufferOffset is 10, message 10 is in writeBuffer[0] and message 15 is in writeBuffer[5].
Tracks whether a read has been started, so that we know whether to start reads on new child calls. This only matters for the first read, because once a message comes in the child call becomes committed and there will be no new child calls.
Number of attempts so far
References _a, attempts, credentials, DEFAULT_MAX_ATTEMPTS_LIMIT, and state().
countActiveCalls()
RetryingCall::countActiveCalls () [inline]
References call, count, and of.
getBufferEntry()
RetryingCall::getBufferEntry (messageIndex) [inline]
References _a.
getCallNumber()
RetryingCall::getCallNumber () [inline]
getDeadlineInfo()
RetryingCall::getDeadlineInfo () [inline]
References $, attempt, attempts, deadline_1, and start.
getHost()
RetryingCall::getHost () [inline]
getMethod()
RetryingCall::getMethod () [inline]
getNextBufferIndex()
RetryingCall::getNextBufferIndex () [inline]
getNextRetryBackoffMs()
RetryingCall::getNextRetryBackoffMs () [inline]
References _a.
getPeer()
RetryingCall::getPeer () [inline]
getPushback()
RetryingCall::getPushback (metadata) [inline]
References e, and parseInt().
halfClose()
RetryingCall::halfClose () [inline]
References call, getNextBufferIndex(), of, and trace.
handleChildStatus()
RetryingCall::handleChildStatus (status, callIndex) [inline]
References _a, commitCall(), constants_1, getPushback(), handleProcessedStatus(), reportStatus(), startNewAttempt(), state(), status, and trace.
handleChildWriteCompleted()
RetryingCall::handleChildWriteCompleted (childIndex) [inline]
References _a, _b, clearSentMessages(), getBufferEntry(), and sendNextChildMessage().
handleProcessedStatus()
RetryingCall::handleProcessedStatus (status, callIndex, pushback) [inline]
References _a, _b, _c, commitCall(), countActiveCalls(), isStatusCodeInList(), maybeRetryCall(), maybeStartHedgingAttempt(), reportStatus(), state(), and status.
isStatusCodeInList()
RetryingCall::isStatusCodeInList (list, code) [inline]
References _a, constants_1, and value.
maybeRetryCall()
RetryingCall::maybeRetryCall (pushback, callback) [inline]
References _a, _b, attempts, callback, getNextRetryBackoffMs(), startNewAttempt(), and state().
maybeStartHedgingAttempt()
RetryingCall::maybeStartHedgingAttempt () [inline]
References attempts, maybeStartHedgingTimer(), startNewAttempt(), and state().
maybeStartHedgingTimer()
RetryingCall::maybeStartHedgingTimer () [inline]
References _a, _b, _c, attempts, maybeStartHedgingAttempt(), and state().
reportStatus()
RetryingCall::reportStatus (statusObject) [inline]
References _a, process, and trace.
sendMessageWithContext()
RetryingCall::sendMessageWithContext (context, message) [inline]
References _a, call, callback, commitCallWithMostMessages(), context, error, getNextBufferIndex(), handleChildWriteCompleted(), message, of, and trace.
sendNextChildMessage()
RetryingCall::sendNextChildMessage (childIndex) [inline]
References callback, error, getBufferEntry(), and handleChildWriteCompleted().
setCredentials()
RetryingCall::setCredentials (newCredentials) [inline]
start()
RetryingCall::start (metadata, listener) [inline]
References attempts, maybeStartHedgingTimer(), startNewAttempt(), and trace.
startNewAttempt()
RetryingCall::startNewAttempt () [inline]
References $, attempts, call, commitCall(), credentials, handleChildStatus(), index, message, PREVIONS_RPC_ATTEMPTS_METADATA_KEY, sendNextChildMessage(), state(), status, and trace.
startRead()
RetryingCall::startRead () [inline]
References of, and trace.
trace()
RetryingCall::trace (text) [inline]
References constants_1, logging, text, and TRACER_NAME.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/retrying-call.js