OrderedMap Class Reference
Public Member Functions
constructor (t=[], e, s)
begin ()
end ()
rBegin ()
rEnd ()
front ()
back ()
lowerBound (t)
upperBound (t)
reverseLowerBound (t)
reverseUpperBound (t)
forEach (t)
setElement (t, e, s)
getElementByPos (t)
find (t)
getElementByKey (t)
union (t)
for (let s=0;s< t;++s)
constructor (t=function(t, e) { if(t< e) return -1;if(t > e) return 1;return 0;}, e=false)
constructor ()
R (t, e)
K (t, e)
L (t, e)
k (t, e)
P (t)
S (t)
U (t)
j (t)
q (t, e, s)
H (t, e)
clear ()
updateKeyByIterator (t, e)
eraseElementByPos (t)
eraseElementByKey (t)
eraseElementByIterator (t)
getHeight ()
get length ()
size ()
empty ()
Public Attributes
*const e = this.U()
Member Function Documentation
back()
OrderedMap::back () [inline]
References C, m, and t.
begin()
OrderedMap::begin () [inline]
References C, and OrderedMapIterator.
clear()
TreeContainer::clear () [inline], [inherited]
References C, m, undefined, and v.
constructor() [1/3]
Base::constructor () [inline], [inherited]
References m.
constructor() [2/3]
OrderedMap::constructor (t = [], e, s) [inline]
References e, i, s, and t.
constructor() [3/3]
TreeContainer::constructor (t = function(t, e) { if (t < e) return -1; if (t > e) return 1; return 0; }, e = false) [inline], [inherited]
References e, and t.
empty()
Base::empty () [inline], [inherited]
References m.
end()
OrderedMap::end () [inline]
References C, and OrderedMapIterator.
eraseElementByIterator()
TreeContainer::eraseElementByIterator (t) [inline], [inherited]
References C, e, i, S, s, t, throwIteratorAccessError(), and undefined.
eraseElementByKey()
TreeContainer::eraseElementByKey (t) [inline], [inherited]
References C, e, TreeContainer::H(), m, S, t, and v.
eraseElementByPos()
TreeContainer::eraseElementByPos (t) [inline], [inherited]
References e, m, S, t, and U.
find()
OrderedMap::find (t) [inline]
References C, e, TreeContainer::H(), OrderedMapIterator, t, and v.
for()
OrderedMap::for () [inline]
References e, s, and t.
forEach()
OrderedMap::forEach (t) [inline]
References e, i, s, t, and U.
front()
OrderedMap::front () [inline]
References C, m, and t.
getElementByKey()
OrderedMap::getElementByKey (t) [inline]
References e, TreeContainer::H(), t, and v.
getElementByPos()
OrderedMap::getElementByPos (t) [inline]
References e, m, t, and U.
getHeight()
TreeContainer::getHeight () [inline], [inherited]
References m, t, and v.
H()
TreeContainer::H (t, e) [inline], [inherited]
References A(), C, e, s, and t.
j()
TreeContainer::j (t) [inline], [inherited]
References C, e, i, s, t, and v.
K()
TreeContainer::K (t, e) [inline], [inherited]
References A(), C, e, i, s, and t.
k()
TreeContainer::k (t, e) [inline], [inherited]
References A(), C, e, i, s, and t.
L()
TreeContainer::L (t, e) [inline], [inherited]
References A(), C, e, i, s, and t.
length()
get Base::length () [inline], [inherited]
References m.
lowerBound()
OrderedMap::lowerBound (t) [inline]
References C, e, OrderedMapIterator, R, t, and v.
P()
TreeContainer::P (t) [inline], [inherited]
References C, e, s, t, and v.
q()
TreeContainer::q (t, e, s) [inline], [inherited]
References A(), C, e, i, j, m, n, r, s, t, undefined, and v.
R()
TreeContainer::R (t, e) [inline], [inherited]
References A(), C, e, i, s, and t.
rBegin()
OrderedMap::rBegin () [inline]
References C, and OrderedMapIterator.
rEnd()
OrderedMap::rEnd () [inline]
References C, and OrderedMapIterator.
reverseLowerBound()
OrderedMap::reverseLowerBound (t) [inline]
References C, e, L, OrderedMapIterator, t, and v.
reverseUpperBound()
OrderedMap::reverseUpperBound (t) [inline]
References C, e, k, OrderedMapIterator, t, and v.
S()
TreeContainer::S (t) [inline], [inherited]
References C, TreeContainer::clear(), e, i, m, P, s, t, undefined, and v.
setElement()
OrderedMap::setElement (t, e, s) [inline]
References e, q, s, and t.
size()
Base::size () [inline], [inherited]
References m.
U()
TreeContainer::U (t) [inline], [inherited]
References e, h, i, n, r, s, t, undefined, and v.
union()
OrderedMap::union (t) [inline]
References e, m, and t.
updateKeyByIterator()
TreeContainer::updateKeyByIterator (t, e) [inline], [inherited]
References A(), C, e, i, m, r, s, t, and throwIteratorAccessError().
upperBound()
OrderedMap::upperBound (t) [inline]
References C, e, TreeContainer::K(), OrderedMapIterator, t, and v.
Member Data Documentation
e
* const OrderedMap::e = this.U()
The documentation for this class was generated from the following file:
backend/node_modules/@js-sdsl/ordered-map/dist/cjs/index.js