AsyncAction Class Reference
Public Member Functions
constructor (scheduler, work)
schedule (state, delay=0)
requestAsyncId (scheduler, _id, delay=0)
recycleAsyncId (_scheduler, id, delay=0)
execute (state, delay)
_execute (state, _delay)
unsubscribe ()
constructor (initialTeardown)
add (teardown)
_hasParent (parent)
_addParent (parent)
_removeParent (parent)
remove (teardown)
Member Function Documentation
_addParent()
Subscription::_addParent (parent) [inline], [inherited]
References Array, and parent.
_execute()
AsyncAction::_execute (state, _delay) [inline]
References e, state(), and unsubscribe().
_hasParent()
Subscription::_hasParent (parent) [inline], [inherited]
References Array, and parent.
_removeParent()
Subscription::_removeParent (parent) [inline], [inherited]
References Array, arrRemove, and parent.
add()
Subscription::add (teardown) [inline], [inherited]
References _a, execFinalizer(), and push.
constructor() [1/2]
AsyncAction::constructor (scheduler, work) [inline]
References pending.
constructor() [2/2]
Subscription::constructor (initialTeardown) [inline], [inherited]
execute()
AsyncAction::execute (state, delay) [inline]
References _execute(), delay, error, pending, recycleAsyncId(), and state().
recycleAsyncId()
AsyncAction::recycleAsyncId (_scheduler, id, delay = 0) [inline]
References delay, intervalProvider, pending, and undefined.
remove()
Subscription::remove (teardown) [inline], [inherited]
References arrRemove.
requestAsyncId()
AsyncAction::requestAsyncId (scheduler, _id, delay = 0) [inline]
References delay, and intervalProvider.
schedule()
AsyncAction::schedule (state, delay = 0) [inline]
References _a, delay, pending, recycleAsyncId(), requestAsyncId(), and state().
unsubscribe()
AsyncAction::unsubscribe () [inline]
References arrRemove, delay, pending, recycleAsyncId(), and state().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/scheduler/AsyncAction.js