AsapAction Class Reference
Public Member Functions
constructor (scheduler, work)
requestAsyncId (scheduler, id, delay=0)
recycleAsyncId (scheduler, id, delay=0)
constructor (initialTeardown)
schedule (state, delay=0)
execute (state, delay)
_execute (state, _delay)
unsubscribe ()
add (teardown)
_hasParent (parent)
_addParent (parent)
_removeParent (parent)
remove (teardown)
Member Function Documentation
_addParent()
Subscription::_addParent (parent) [inline], [inherited]
References Array, and parent.
_execute()
AsyncAction::_execute (state, _delay) [inline], [inherited]
References e, state(), and AsyncAction::unsubscribe().
_hasParent()
Subscription::_hasParent (parent) [inline], [inherited]
References Array, and parent.
_removeParent()
Subscription::_removeParent (parent) [inline], [inherited]
References Array, arrRemove, and parent.
add()
Subscription::add (teardown) [inline], [inherited]
References _a, execFinalizer(), and push.
constructor() [1/2]
AsapAction::constructor (scheduler, work) [inline]
constructor() [2/2]
Subscription::constructor (initialTeardown) [inline], [inherited]
execute()
AsyncAction::execute (state, delay) [inline], [inherited]
References AsyncAction::_execute(), delay, error, pending, AsyncAction::recycleAsyncId(), and state().
recycleAsyncId()
AsapAction::recycleAsyncId (scheduler, id, delay = 0) [inline]
References _a, delay, immediateProvider, and undefined.
remove()
Subscription::remove (teardown) [inline], [inherited]
References arrRemove.
requestAsyncId()
AsapAction::requestAsyncId (scheduler, id, delay = 0) [inline]
References delay, immediateProvider, and undefined.
schedule()
AsyncAction::schedule (state, delay = 0) [inline], [inherited]
References _a, delay, pending, AsyncAction::recycleAsyncId(), AsyncAction::requestAsyncId(), and state().
unsubscribe()
AsyncAction::unsubscribe () [inline], [inherited]
References arrRemove, delay, pending, AsyncAction::recycleAsyncId(), and state().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/scheduler/AsapAction.js