IamClient Class Reference
Public Member Functions
constructor (gaxGrpc, options)
initialize ()
getProjectId (callback)
getIamPolicy (request, optionsOrCallback, callback)
setIamPolicy (request, optionsOrCallback, callback)
testIamPermissions (request, optionsOrCallback, callback)
close ()
Static Public Member Functions
static get servicePath ()
static get apiEndpoint ()
static get port ()
static get scopes ()
Detailed Description
Google Cloud IAM Client. This is manually written for providing methods [setIamPolicy, getIamPolicy, testIamPerssion] to the generated client.
Member Function Documentation
apiEndpoint()
static get IamClient::apiEndpoint () [inline], [static]
The DNS address for this API service - same as servicePath(), exists for compatibility reasons. Here is the caller graph for this function:
close()
IamClient::close () [inline]
Terminate the GRPC channel and close the client.
The client will no longer be usable and all future behavior is undefined.
References initialize(), and Promise.
constructor()
IamClient::constructor (gaxGrpc, options) [inline]
References $, apiEndpoint(), auth, constructor, fallback, gapicConfig, gax, grpc, jsonProtos, node, port(), process, servicePath(), stream, and version.
getIamPolicy()
IamClient::getIamPolicy (request, optionsOrCallback, callback) [inline]
References callback, initialize(), request, routingHeader, and undefined.
getProjectId()
IamClient::getProjectId (callback) [inline]
References auth, callback, and Promise.
initialize()
IamClient::initialize () [inline]
Initialize the client. Performs asynchronous operations (such as authentication) and prepares the client. This function will be called automatically when any class method is called for the first time, but if you need to initialize it before calling an actual method, feel free to call initialize() directly.
You can await on this method if you want to make sure the client is initialized.
Returns
{Promise} A promise that resolves to an authenticated service stub.
References args, createApiCall_1, func, of, and Promise.
port()
static get IamClient::port () [inline], [static]
The port for this API service. Here is the caller graph for this function:
scopes()
static get IamClient::scopes () [inline], [static]
The scopes needed to make gRPC calls for every method defined in this service.
servicePath()
static get IamClient::servicePath () [inline], [static]
The DNS address for this API service. Here is the caller graph for this function:
setIamPolicy()
IamClient::setIamPolicy (request, optionsOrCallback, callback) [inline]
References callback, initialize(), request, routingHeader, and undefined.
testIamPermissions()
IamClient::testIamPermissions (request, optionsOrCallback, callback) [inline]
References callback, initialize(), request, routingHeader, and undefined.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/iamService.js