Http2RequestConfigImpl Class Reference
Public Member Functions
constructor (http2Config)
get http2SessionHandler ()
buildRequestOptions ()
get method ()
get url ()
get headers ()
get data ()
get timeout ()
buildEntity (headers)
buildUrl ()
urlWithProtocol ()
Detailed Description
An adapter class for extracting options and entity data from an Http2RequestConfig.
Member Function Documentation
buildEntity()
BaseRequestConfigImpl::buildEntity (headers) [inline], [inherited]
References BaseRequestConfigImpl::data(), hasEntity(), BaseRequestConfigImpl::headers(), isEntityEnclosingRequest(), JSON, and validator.
buildRequestOptions()
Http2RequestConfigImpl::buildRequestOptions () [inline]
References BaseRequestConfigImpl::buildUrl(), BaseRequestConfigImpl::headers(), BaseRequestConfigImpl::method(), and path.
buildUrl()
BaseRequestConfigImpl::buildUrl () [inline], [inherited]
References $, a, BaseRequestConfigImpl::data(), hasEntity(), isEntityEnclosingRequest(), BaseRequestConfigImpl::method(), BaseRequestConfigImpl::url(), BaseRequestConfigImpl::urlWithProtocol(), and validator.
constructor()
Http2RequestConfigImpl::constructor (http2Config) [inline]
data()
get BaseRequestConfigImpl::data () [inline], [inherited]
References config.
headers()
get BaseRequestConfigImpl::headers () [inline], [inherited]
References config.
http2SessionHandler()
get Http2RequestConfigImpl::http2SessionHandler () [inline]
method()
get BaseRequestConfigImpl::method () [inline], [inherited]
References config.
timeout()
get BaseRequestConfigImpl::timeout () [inline], [inherited]
References config.
url()
get BaseRequestConfigImpl::url () [inline], [inherited]
References config.
urlWithProtocol()
BaseRequestConfigImpl::urlWithProtocol () [inline], [inherited]
References https, and BaseRequestConfigImpl::url().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js