GoogleErrorDecoder Class Reference
Public Member Functions
constructor ()
decodeProtobufAny (anyValue)
decodeRpcStatus (buffer)
callErrorFromStatus (status)
decodeErrorFromBuffer (buffer)
decodeGRPCStatusDetails (bufferArr)
decodeHTTPError (json)
decodeHttpStatusDetails (rawDetails)
Member Function Documentation
callErrorFromStatus()
GoogleErrorDecoder::callErrorFromStatus (status) [inline]
References $, GoogleError, status, and status_1.
constructor()
GoogleErrorDecoder::constructor () [inline]
References protobuf, require(), and root.
decodeErrorFromBuffer()
GoogleErrorDecoder::decodeErrorFromBuffer (buffer) [inline]
References buffer, callErrorFromStatus, and decodeRpcStatus().
decodeGRPCStatusDetails()
GoogleErrorDecoder::decodeGRPCStatusDetails (bufferArr) [inline]
References buffer, decodeProtobufAny(), of, result, and Uint8Array.
decodeHTTPError()
GoogleErrorDecoder::decodeHTTPError (json) [inline]
References $, error, fallback_1, message, serialize, and serializer.
decodeHttpStatusDetails()
GoogleErrorDecoder::decodeHttpStatusDetails (rawDetails) [inline]
References decodeProtobufAny(), and of.
decodeProtobufAny()
GoogleErrorDecoder::decodeProtobufAny (anyValue) [inline]
References $, lookup, match, root, and type.
decodeRpcStatus()
GoogleErrorDecoder::decodeRpcStatus (buffer) [inline]
References buffer, decodeProtobufAny(), message, of, reason, result, status, and Uint8Array.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/googleError.js