MaxNode Class Reference
Public Member Functions
constructor ()
compareTo (other)
equals (other)
getPriority ()
getImmediateChild (childName)
isEmpty ()
constructor ()
compareTo (other)
equals (other)
getPriority ()
getImmediateChild (childName)
isEmpty ()
constructor ()
compareTo (other)
equals (other)
getPriority ()
getImmediateChild (childName)
isEmpty ()
constructor (children_, priorityNode_, indexMap_)
isLeafNode ()
isLeafNode ()
isLeafNode ()
updatePriority (newPriorityNode)
updatePriority (newPriorityNode)
updatePriority (newPriorityNode)
getChild (path)
getChild (path)
getChild (path)
hasChild (childName)
hasChild (childName)
hasChild (childName)
updateImmediateChild (childName, newChildNode)
updateImmediateChild (childName, newChildNode)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
updateChild (path, newChildNode)
updateChild (path, newChildNode)
numChildren ()
numChildren ()
numChildren ()
val (exportFormat)
val (exportFormat)
val (exportFormat)
hash ()
hash ()
hash ()
getPredecessorChildName (childName, childNode, index)
getPredecessorChildName (childName, childNode, index)
getPredecessorChildName (childName, childNode, index)
getFirstChildName (indexDefinition)
getFirstChildName (indexDefinition)
getFirstChildName (indexDefinition)
getFirstChild (indexDefinition)
getFirstChild (indexDefinition)
getFirstChild (indexDefinition)
getLastChildName (indexDefinition)
getLastChildName (indexDefinition)
getLastChildName (indexDefinition)
getLastChild (indexDefinition)
getLastChild (indexDefinition)
getLastChild (indexDefinition)
forEachChild (index, action)
forEachChild (index, action)
forEachChild (index, action)
getIterator (indexDefinition)
getIterator (indexDefinition)
getIterator (indexDefinition)
getIteratorFrom (startPost, indexDefinition)
getIteratorFrom (startPost, indexDefinition)
getIteratorFrom (startPost, indexDefinition)
getReverseIterator (indexDefinition)
getReverseIterator (indexDefinition)
getReverseIterator (indexDefinition)
getReverseIteratorFrom (endPost, indexDefinition)
getReverseIteratorFrom (endPost, indexDefinition)
getReverseIteratorFrom (endPost, indexDefinition)
withIndex (indexDefinition)
withIndex (indexDefinition)
withIndex (indexDefinition)
isIndexed (index)
isIndexed (index)
isIndexed (index)
resolveIndex_ (indexDefinition)
resolveIndex_ (indexDefinition)
resolveIndex_ (indexDefinition)
Static Public Member Functions
static get EMPTY_NODE ()
static get EMPTY_NODE ()
static get EMPTY_NODE ()
Member Function Documentation
compareTo() [1/3]
MaxNode::compareTo (other) [inline]
compareTo() [2/3]
MaxNode::compareTo (other) [inline]
compareTo() [3/3]
MaxNode::compareTo (other) [inline]
constructor() [1/4]
ChildrenNode::constructor (children_, priorityNode_, indexMap_) [inline], [inherited]
Parameters
children_ - List of children of this node..
priorityNode_ - The priority of this node (as a snapshot node).
Note: The only reason we allow null priority is for EMPTY_NODE, since we can't use EMPTY_NODE as the priority of EMPTY_NODE. We might want to consider making EMPTY_NODE its own class instead of an empty ChildrenNode.
References util, and validatePriorityNode.
constructor() [2/4]
MaxNode::constructor () [inline]
References IndexMap::Default(), ChildrenNode::EMPTY_NODE(), and NAME_COMPARATOR().
constructor() [3/4]
MaxNode::constructor () [inline]
References IndexMap::Default(), ChildrenNode::EMPTY_NODE(), and NAME_COMPARATOR().
constructor() [4/4]
MaxNode::constructor () [inline]
References IndexMap::Default(), ChildrenNode::EMPTY_NODE(), and NAME_COMPARATOR().
EMPTY_NODE() [1/3]
static get ChildrenNode::EMPTY_NODE () [inline], [static], [inherited]
References IndexMap::Default(), ChildrenNode::EMPTY_NODE(), and NAME_COMPARATOR().
EMPTY_NODE() [2/3]
static get ChildrenNode::EMPTY_NODE () [inline], [static], [inherited]
References IndexMap::Default(), ChildrenNode::EMPTY_NODE(), and NAME_COMPARATOR().
EMPTY_NODE() [3/3]
static get ChildrenNode::EMPTY_NODE () [inline], [static], [inherited]
References IndexMap::Default(), ChildrenNode::EMPTY_NODE(), and NAME_COMPARATOR().
equals() [1/3]
MaxNode::equals (other) [inline]
equals() [2/3]
MaxNode::equals (other) [inline]
equals() [3/3]
MaxNode::equals (other) [inline]
forEachChild() [1/3]
ChildrenNode::forEachChild (index, action) [inline], [inherited]
References index, and ChildrenNode::resolveIndex_().
forEachChild() [2/3]
ChildrenNode::forEachChild (index, action) [inline], [inherited]
References index, and ChildrenNode::resolveIndex_().
forEachChild() [3/3]
ChildrenNode::forEachChild (index, action) [inline], [inherited]
References index, and ChildrenNode::resolveIndex_().
getChild() [1/3]
ChildrenNode::getChild (path) [inline], [inherited]
@inheritDoc
References front, ChildrenNode::getImmediateChild(), path, pathGetFront(), and pathPopFront().
getChild() [2/3]
ChildrenNode::getChild (path) [inline], [inherited]
@inheritDoc
References front, ChildrenNode::getImmediateChild(), path, pathGetFront(), and pathPopFront().
getChild() [3/3]
ChildrenNode::getChild (path) [inline], [inherited]
@inheritDoc
References front, ChildrenNode::getImmediateChild(), path, pathGetFront(), and pathPopFront().
getFirstChild() [1/3]
ChildrenNode::getFirstChild (indexDefinition) [inline], [inherited]
References ChildrenNode::getFirstChildName().
getFirstChild() [2/3]
ChildrenNode::getFirstChild (indexDefinition) [inline], [inherited]
References ChildrenNode::getFirstChildName().
getFirstChild() [3/3]
ChildrenNode::getFirstChild (indexDefinition) [inline], [inherited]
References ChildrenNode::getFirstChildName().
getFirstChildName() [1/3]
ChildrenNode::getFirstChildName (indexDefinition) [inline], [inherited]
References ChildrenNode::resolveIndex_().
getFirstChildName() [2/3]
ChildrenNode::getFirstChildName (indexDefinition) [inline], [inherited]
References ChildrenNode::resolveIndex_().
getFirstChildName() [3/3]
ChildrenNode::getFirstChildName (indexDefinition) [inline], [inherited]
References ChildrenNode::resolveIndex_().
getImmediateChild() [1/3]
MaxNode::getImmediateChild (childName) [inline]
References ChildrenNode::EMPTY_NODE().
getImmediateChild() [2/3]
MaxNode::getImmediateChild (childName) [inline]
References ChildrenNode::EMPTY_NODE().
getImmediateChild() [3/3]
MaxNode::getImmediateChild (childName) [inline]
References ChildrenNode::EMPTY_NODE().
getIterator() [1/3]
ChildrenNode::getIterator (indexDefinition) [inline], [inherited]
References ChildrenNode::getIteratorFrom().
getIterator() [2/3]
ChildrenNode::getIterator (indexDefinition) [inline], [inherited]
References ChildrenNode::getIteratorFrom().
getIterator() [3/3]
ChildrenNode::getIterator (indexDefinition) [inline], [inherited]
References ChildrenNode::getIteratorFrom().
getIteratorFrom() [1/3]
ChildrenNode::getIteratorFrom (startPost, indexDefinition) [inline], [inherited]
References iterator, next(), ChildrenNode::resolveIndex_(), and NamedNode::Wrap().
getIteratorFrom() [2/3]
ChildrenNode::getIteratorFrom (startPost, indexDefinition) [inline], [inherited]
References iterator, next(), ChildrenNode::resolveIndex_(), and NamedNode::Wrap().
getIteratorFrom() [3/3]
ChildrenNode::getIteratorFrom (startPost, indexDefinition) [inline], [inherited]
References iterator, next(), ChildrenNode::resolveIndex_(), and NamedNode::Wrap().
getLastChild() [1/3]
ChildrenNode::getLastChild (indexDefinition) [inline], [inherited]
References ChildrenNode::getLastChildName().
getLastChild() [2/3]
ChildrenNode::getLastChild (indexDefinition) [inline], [inherited]
References ChildrenNode::getLastChildName().
getLastChild() [3/3]
ChildrenNode::getLastChild (indexDefinition) [inline], [inherited]
References ChildrenNode::getLastChildName().
getLastChildName() [1/3]
ChildrenNode::getLastChildName (indexDefinition) [inline], [inherited]
Given an index, return the key name of the largest value we have, according to that index
References ChildrenNode::resolveIndex_().
getLastChildName() [2/3]
ChildrenNode::getLastChildName (indexDefinition) [inline], [inherited]
Given an index, return the key name of the largest value we have, according to that index
References ChildrenNode::resolveIndex_().
getLastChildName() [3/3]
ChildrenNode::getLastChildName (indexDefinition) [inline], [inherited]
Given an index, return the key name of the largest value we have, according to that index
References ChildrenNode::resolveIndex_().
getPredecessorChildName() [1/3]
ChildrenNode::getPredecessorChildName (childName, childNode, index) [inline], [inherited]
@inheritDoc
References index, and ChildrenNode::resolveIndex_().
getPredecessorChildName() [2/3]
ChildrenNode::getPredecessorChildName (childName, childNode, index) [inline], [inherited]
@inheritDoc
References index, and ChildrenNode::resolveIndex_().
getPredecessorChildName() [3/3]
ChildrenNode::getPredecessorChildName (childName, childNode, index) [inline], [inherited]
@inheritDoc
References index, and ChildrenNode::resolveIndex_().
getPriority() [1/3]
MaxNode::getPriority () [inline]
getPriority() [2/3]
MaxNode::getPriority () [inline]
getPriority() [3/3]
MaxNode::getPriority () [inline]
getReverseIterator() [1/3]
ChildrenNode::getReverseIterator (indexDefinition) [inline], [inherited]
References ChildrenNode::getReverseIteratorFrom().
getReverseIterator() [2/3]
ChildrenNode::getReverseIterator (indexDefinition) [inline], [inherited]
References ChildrenNode::getReverseIteratorFrom().
getReverseIterator() [3/3]
ChildrenNode::getReverseIterator (indexDefinition) [inline], [inherited]
References ChildrenNode::getReverseIteratorFrom().
getReverseIteratorFrom() [1/3]
ChildrenNode::getReverseIteratorFrom (endPost, indexDefinition) [inline], [inherited]
References iterator, next(), ChildrenNode::resolveIndex_(), and NamedNode::Wrap().
getReverseIteratorFrom() [2/3]
ChildrenNode::getReverseIteratorFrom (endPost, indexDefinition) [inline], [inherited]
References iterator, next(), ChildrenNode::resolveIndex_(), and NamedNode::Wrap().
getReverseIteratorFrom() [3/3]
ChildrenNode::getReverseIteratorFrom (endPost, indexDefinition) [inline], [inherited]
References iterator, next(), ChildrenNode::resolveIndex_(), and NamedNode::Wrap().
hasChild() [1/3]
ChildrenNode::hasChild (childName) [inline], [inherited]
@inheritDoc
hasChild() [2/3]
ChildrenNode::hasChild (childName) [inline], [inherited]
@inheritDoc
hasChild() [3/3]
ChildrenNode::hasChild (childName) [inline], [inherited]
@inheritDoc
hash() [1/3]
ChildrenNode::hash () [inline], [inherited]
@inheritDoc
References ChildrenNode::forEachChild(), ChildrenNode::getPriority(), ChildrenNode::isEmpty(), PRIORITY_INDEX, priorityHashText, sha1, toHash, and ChildrenNode::val().
hash() [2/3]
ChildrenNode::hash () [inline], [inherited]
@inheritDoc
References ChildrenNode::forEachChild(), ChildrenNode::getPriority(), ChildrenNode::isEmpty(), PRIORITY_INDEX, priorityHashText, sha1, toHash, and ChildrenNode::val().
hash() [3/3]
ChildrenNode::hash () [inline], [inherited]
@inheritDoc
References ChildrenNode::forEachChild(), ChildrenNode::getPriority(), ChildrenNode::isEmpty(), PRIORITY_INDEX, priorityHashText, sha1, toHash, and ChildrenNode::val().
isEmpty() [1/3]
MaxNode::isEmpty () [inline]
isEmpty() [2/3]
MaxNode::isEmpty () [inline]
isEmpty() [3/3]
MaxNode::isEmpty () [inline]
isIndexed() [1/3]
ChildrenNode::isIndexed (index) [inline], [inherited]
References index, and KEY_INDEX.
isIndexed() [2/3]
ChildrenNode::isIndexed (index) [inline], [inherited]
References index, and KEY_INDEX.
isIndexed() [3/3]
ChildrenNode::isIndexed (index) [inline], [inherited]
References index, and KEY_INDEX.
isLeafNode() [1/3]
ChildrenNode::isLeafNode () [inline], [inherited]
@inheritDoc
isLeafNode() [2/3]
ChildrenNode::isLeafNode () [inline], [inherited]
@inheritDoc
isLeafNode() [3/3]
ChildrenNode::isLeafNode () [inline], [inherited]
@inheritDoc
numChildren() [1/3]
ChildrenNode::numChildren () [inline], [inherited]
@inheritDoc
numChildren() [2/3]
ChildrenNode::numChildren () [inline], [inherited]
@inheritDoc
numChildren() [3/3]
ChildrenNode::numChildren () [inline], [inherited]
@inheritDoc
resolveIndex_() [1/3]
ChildrenNode::resolveIndex_ (indexDefinition) [inline], [inherited]
Returns a SortedMap ordered by index, or null if the default (by-key) ordering can be used instead.
References KEY_INDEX.
resolveIndex_() [2/3]
ChildrenNode::resolveIndex_ (indexDefinition) [inline], [inherited]
Returns a SortedMap ordered by index, or null if the default (by-key) ordering can be used instead.
References KEY_INDEX.
resolveIndex_() [3/3]
ChildrenNode::resolveIndex_ (indexDefinition) [inline], [inherited]
Returns a SortedMap ordered by index, or null if the default (by-key) ordering can be used instead.
References KEY_INDEX.
updateChild() [1/3]
ChildrenNode::updateChild (path, newChildNode) [inline], [inherited]
@inheritDoc
References front, ChildrenNode::getImmediateChild(), path, pathGetFront(), pathGetLength(), pathPopFront(), ChildrenNode::updateImmediateChild(), and util.
updateChild() [2/3]
ChildrenNode::updateChild (path, newChildNode) [inline], [inherited]
@inheritDoc
References assert, front, ChildrenNode::getImmediateChild(), path, pathGetFront(), pathGetLength(), pathPopFront(), and ChildrenNode::updateImmediateChild().
updateChild() [3/3]
ChildrenNode::updateChild (path, newChildNode) [inline], [inherited]
@inheritDoc
References assert, front, ChildrenNode::getImmediateChild(), path, pathGetFront(), pathGetLength(), pathPopFront(), and ChildrenNode::updateImmediateChild().
updateImmediateChild() [1/3]
ChildrenNode::updateImmediateChild (childName, newChildNode) [inline], [inherited]
@inheritDoc
References ChildrenNode::EMPTY_NODE(), ChildrenNode::updatePriority(), and util.
updateImmediateChild() [2/3]
ChildrenNode::updateImmediateChild (childName, newChildNode) [inline], [inherited]
@inheritDoc
References assert, ChildrenNode::EMPTY_NODE(), and ChildrenNode::updatePriority().
updateImmediateChild() [3/3]
ChildrenNode::updateImmediateChild (childName, newChildNode) [inline], [inherited]
@inheritDoc
References assert, ChildrenNode::EMPTY_NODE(), and ChildrenNode::updatePriority().
updatePriority() [1/3]
ChildrenNode::updatePriority (newPriorityNode) [inline], [inherited]
@inheritDoc Here is the caller graph for this function:
updatePriority() [2/3]
ChildrenNode::updatePriority (newPriorityNode) [inline], [inherited]
@inheritDoc
updatePriority() [3/3]
ChildrenNode::updatePriority (newPriorityNode) [inline], [inherited]
@inheritDoc
val() [1/3]
ChildrenNode::val (exportFormat) [inline], [inherited]
@inheritDoc
References ChildrenNode::forEachChild(), ChildrenNode::getPriority(), ChildrenNode::isEmpty(), obj, and PRIORITY_INDEX.
val() [2/3]
ChildrenNode::val (exportFormat) [inline], [inherited]
@inheritDoc
References ChildrenNode::forEachChild(), ChildrenNode::getPriority(), ChildrenNode::isEmpty(), obj, and PRIORITY_INDEX.
val() [3/3]
ChildrenNode::val (exportFormat) [inline], [inherited]
@inheritDoc
References ChildrenNode::forEachChild(), ChildrenNode::getPriority(), ChildrenNode::isEmpty(), obj, and PRIORITY_INDEX.
withIndex() [1/3]
ChildrenNode::withIndex (indexDefinition) [inline], [inherited]
References KEY_INDEX.
withIndex() [2/3]
ChildrenNode::withIndex (indexDefinition) [inline], [inherited]
References KEY_INDEX.
withIndex() [3/3]
ChildrenNode::withIndex (indexDefinition) [inline], [inherited]
References KEY_INDEX.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js