Model Class Reference
Public Member Functions
constructor (model, client)
get modelId ()
get displayName ()
get tags ()
get createTime ()
get updateTime ()
get validationError ()
get published ()
get etag ()
get modelHash ()
get tfliteModel ()
get locked ()
toJSON ()
waitForUnlocked (maxTimeMillis)
Static Public Member Functions
static validateAndClone (model)
Detailed Description
A Firebase ML Model output object.
Member Function Documentation
constructor()
Model::constructor (model, client) [inline]
References client, and validateAndClone().
createTime()
get Model::createTime () [inline]
The timestamp of the model's creation. Here is the caller graph for this function:
displayName()
get Model::displayName () [inline]
The model's name. This is the name you use from your app to load the model. Here is the caller graph for this function:
etag()
get Model::etag () [inline]
The ETag identifier of the current version of the model. This value changes whenever you update any of the model's properties. Here is the caller graph for this function:
locked()
get Model::locked () [inline]
True if the model is locked by a server-side operation. You can't make changes to a locked model. See Model.waitForUnlocked. Here is the caller graph for this function:
modelHash()
get Model::modelHash () [inline]
The hash of the model's tflite file. This value changes only when you upload a new TensorFlow Lite model. Here is the caller graph for this function:
modelId()
get Model::modelId () [inline]
The ID of the model.
References extractModelId().
published()
get Model::published () [inline]
True if the model is published. Here is the caller graph for this function:
tags()
get Model::tags () [inline]
The model's tags, which can be used to group or filter models in list operations. Here is the caller graph for this function:
tfliteModel()
get Model::tfliteModel () [inline]
Metadata about the model's TensorFlow Lite model file.
References deep_copy_1.
toJSON()
Model::toJSON () [inline]
Return the model as a JSON object.
References createTime(), displayName(), etag(), locked(), modelHash(), modelId(), published(), tags(), tfliteModel(), updateTime(), and validationError().
updateTime()
get Model::updateTime () [inline]
The timestamp of the model's most recent update. Here is the caller graph for this function:
validateAndClone()
static Model::validateAndClone (model) [inline], [static]
References $, deep_copy_1, JSON, machine_learning_utils_1, response, and validator.
validationError()
get Model::validationError () [inline]
Error message when model validation fails. Here is the caller graph for this function:
waitForUnlocked()
Model::waitForUnlocked (maxTimeMillis) [inline]
Wait for the model to be unlocked.
Parameters
maxTimeMillis - The maximum time in milliseconds to wait. If not specified, a default maximum of 2 minutes is used.
Returns
A promise that resolves when the model is unlocked or the maximum wait time has passed.
References client, Promise, and validateAndClone().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/machine-learning/machine-learning.js