Http2Transport Class Reference
Public Member Functions
constructor (session, subchannelAddress, options, remoteName)
getChannelzInfo ()
trace (text)
keepaliveTrace (text)
flowControlTrace (text)
internalsTrace (text)
reportDisconnectToOwner (tooManyPings)
handleDisconnect ()
addDisconnectListener (listener)
canSendPing ()
maybeSendPing ()
maybeStartKeepalivePingTimer ()
clearKeepaliveTimeout ()
removeActiveCall (call)
addActiveCall (call)
createCall (metadata, host, method, listener, subchannelCallStatsTracker)
getChannelzRef ()
getPeerName ()
getOptions ()
shutdown ()
Member Function Documentation
addActiveCall()
Http2Transport::addActiveCall (call) [inline]
References call, maybeStartKeepalivePingTimer(), and session.
addDisconnectListener()
Http2Transport::addDisconnectListener (listener) [inline]
canSendPing()
Http2Transport::canSendPing () [inline]
References session.
clearKeepaliveTimeout()
Http2Transport::clearKeepaliveTimeout () [inline]
Clears whichever keepalive timeout is currently active, if any. Here is the caller graph for this function:
constructor()
Http2Transport::constructor (session, subchannelAddress, options, remoteName) [inline]
Timer reference indicating when to send the next ping or when the most recent ping will be considered lost.
Indicates that the keepalive timer ran out while there were no active calls, and a ping should be sent the next time a call starts.
Parameters
remoteName Name of the remote server, if it is not the same as the subchannel address, i.e. if connecting through an HTTP CONNECT proxy.
References $, channelz_1, clientVersion, e, error, getChannelzInfo(), grpc, handleDisconnect(), http2, js, JSON, KEEPALIVE_TIMEOUT_MS, logging, maybeStartKeepalivePingTimer(), node, reportDisconnectToOwner(), session, Set, subchannel_address_1, tooManyPingsData, trace, and TRACER_NAME.
createCall()
Http2Transport::createCall (metadata, host, method, listener, subchannelCallStatsTracker) [inline]
References _a, addActiveCall(), call, call_number_1, e, flowControlTrace(), handleDisconnect(), headers, internalsTrace(), method, removeActiveCall(), session, status, subchannel_call_1, and success.
flowControlTrace()
Http2Transport::flowControlTrace (text) [inline]
References constants_1, FLOW_CONTROL_TRACER_NAME, logging, and text.
getChannelzInfo()
Http2Transport::getChannelzInfo () [inline]
References _a, _b, _c, session, and subchannel_address_1.
getChannelzRef()
Http2Transport::getChannelzRef () [inline]
getOptions()
Http2Transport::getOptions () [inline]
getPeerName()
Http2Transport::getPeerName () [inline]
handleDisconnect()
Http2Transport::handleDisconnect () [inline]
Handle connection drops, but not GOAWAYs.
References call, clearKeepaliveTimeout(), of, reportDisconnectToOwner(), session, and setImmediate.
internalsTrace()
Http2Transport::internalsTrace (text) [inline]
References constants_1, logging, and text.
keepaliveTrace()
Http2Transport::keepaliveTrace (text) [inline]
References constants_1, logging, and text.
maybeSendPing()
Http2Transport::maybeSendPing () [inline]
References _a, _b, canSendPing(), clearKeepaliveTimeout(), e, handleDisconnect(), keepaliveTrace(), maybeStartKeepalivePingTimer(), and session.
maybeStartKeepalivePingTimer()
Http2Transport::maybeStartKeepalivePingTimer () [inline]
Starts the keepalive ping timer if appropriate. If the timer already ran out while there were no active requests, instead send a ping immediately. If the ping timer is already running or a ping is currently in flight, instead do nothing and wait for them to resolve.
References _a, _b, canSendPing(), keepaliveTrace(), and maybeSendPing().
removeActiveCall()
Http2Transport::removeActiveCall (call) [inline]
References call, and session.
reportDisconnectToOwner()
Http2Transport::reportDisconnectToOwner (tooManyPings) [inline]
Indicate to the owner of this object that this transport should no longer be used. That happens if the connection drops, or if the server sends a GOAWAY.
Parameters
tooManyPings If true, this was triggered by a GOAWAY with data indicating that the session was closed becaues the client sent too many pings.
Returns
shutdown()
Http2Transport::shutdown () [inline]
References channelz_1, and session.
trace()
Http2Transport::trace (text) [inline]
References constants_1, logging, text, and TRACER_NAME.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/transport.js