AppCheckApiClient Class Reference
Public Member Functions
constructor (app)
exchangeToken (customToken, appId)
verifyReplayProtection (token)
getUrl (appId)
getVerifyTokenUrl ()
getProjectId ()
toFirebaseError (err)
toAppCheckToken (resp)
stringToMilliseconds (duration)
Detailed Description
Class that facilitates sending requests to the Firebase App Check backend API.
Member Function Documentation
constructor()
AppCheckApiClient::constructor (app) [inline]
References api_request_1, app, FirebaseAppCheckError, and validator.
exchangeToken()
AppCheckApiClient::exchangeToken (customToken, appId) [inline]
Exchange a signed custom token to App Check token
Parameters
customToken - The custom token to be exchanged.
appId - The mobile App ID.
Returns
A promise that fulfills with a AppCheckToken.
References data, FirebaseAppCheckError, getUrl(), headers, method, request, then, toAppCheckToken(), toFirebaseError(), url, and validator.
getProjectId()
AppCheckApiClient::getProjectId () [inline]
References app, FirebaseAppCheckError, Promise, utils, and validator.
getUrl()
AppCheckApiClient::getUrl (appId) [inline]
References FIREBASE_APP_CHECK_V1_API_URL_FORMAT, getProjectId(), and utils.
getVerifyTokenUrl()
AppCheckApiClient::getVerifyTokenUrl () [inline]
References getProjectId(), and utils.
stringToMilliseconds()
AppCheckApiClient::stringToMilliseconds (duration) [inline]
Converts a duration string with the suffix s to milliseconds.
Parameters
duration - The duration as a string with the suffix "s" preceded by the number of seconds, with fractional seconds. For example, 3 seconds with 0 nanoseconds is expressed as "3s", while 3 seconds and 1 nanosecond is expressed as "3.000000001s", and 3 seconds and 1 microsecond is expressed as "3.000001s".
Returns
The duration in milliseconds.
References FirebaseAppCheckError, and validator.
toAppCheckToken()
AppCheckApiClient::toAppCheckToken (resp) [inline]
Creates an AppCheckToken from the API response.
Parameters
resp - API response object.
Returns
An AppCheckToken instance.
References stringToMilliseconds(), and token.
toFirebaseError()
AppCheckApiClient::toFirebaseError (err) [inline]
References $, and, error, error_1, exports, FirebaseAppCheckError, message, response, server, and status.
verifyReplayProtection()
AppCheckApiClient::verifyReplayProtection (token) [inline]
References data, FirebaseAppCheckError, getVerifyTokenUrl(), headers, method, request, then, toFirebaseError(), token, url, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/app-check/app-check-api-client-internal.js