FirestoreService Class Reference
Public Member Functions
constructor (app)
initializeDatabase (databaseId, settings)
getDatabase (databaseId)
checkIfSameSettings (settingsA, settingsB)
get app ()
Member Function Documentation
app()
get FirestoreService::app () [inline]
Returns the app associated with this Storage instance.
Returns
The app associated with this Storage instance.
checkIfSameSettings()
FirestoreService::checkIfSameSettings (settingsA, settingsB) [inline]
References a, and b.
constructor()
FirestoreService::constructor (app) [inline]
References app(), and Map.
getDatabase()
FirestoreService::getDatabase (databaseId) [inline]
References app(), database, initFirestore(), and undefined.
initializeDatabase()
FirestoreService::initializeDatabase (databaseId, settings) [inline]
References app(), checkIfSameSettings(), error_1, initFirestore(), and message.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/firestore/firestore-internal.js