LLRBNode Class Reference
Public Member Functions
constructor (key, value, color, left, right)
copy (key, value, color, left, right)
count ()
isEmpty ()
inorderTraversal (action)
reverseTraversal (action)
min_ ()
minKey ()
maxKey ()
insert (key, value, comparator)
removeMin_ ()
remove (key, comparator)
isRed_ ()
fixUp_ ()
moveRedLeft_ ()
moveRedRight_ ()
rotateLeft_ ()
rotateRight_ ()
colorFlip_ ()
checkMaxDepth_ ()
check_ ()
constructor (key, value, color, left, right)
copy (key, value, color, left, right)
count ()
isEmpty ()
inorderTraversal (action)
reverseTraversal (action)
min_ ()
minKey ()
maxKey ()
insert (key, value, comparator)
removeMin_ ()
remove (key, comparator)
isRed_ ()
fixUp_ ()
moveRedLeft_ ()
moveRedRight_ ()
rotateLeft_ ()
rotateRight_ ()
colorFlip_ ()
checkMaxDepth_ ()
check_ ()
constructor (key, value, color, left, right)
copy (key, value, color, left, right)
count ()
isEmpty ()
inorderTraversal (action)
reverseTraversal (action)
min_ ()
minKey ()
maxKey ()
insert (key, value, comparator)
removeMin_ ()
remove (key, comparator)
isRed_ ()
fixUp_ ()
moveRedLeft_ ()
moveRedRight_ ()
rotateLeft_ ()
rotateRight_ ()
colorFlip_ ()
checkMaxDepth_ ()
check_ ()
Detailed Description
Represents a node in a Left-leaning Red-Black tree.
Member Function Documentation
check_() [1/3]
LLRBNode::check_ () [inline]
References isRed_(), left, right, and value.
check_() [2/3]
LLRBNode::check_ () [inline]
References isRed_(), left, right, and value.
check_() [3/3]
LLRBNode::check_ () [inline]
References isRed_(), left, right, and value.
checkMaxDepth_() [1/3]
LLRBNode::checkMaxDepth_ () [inline]
For testing.
Returns
True if all is well.
References check_(), and count().
checkMaxDepth_() [2/3]
LLRBNode::checkMaxDepth_ () [inline]
For testing.
Returns
True if all is well.
References check_(), and count().
checkMaxDepth_() [3/3]
LLRBNode::checkMaxDepth_ () [inline]
For testing.
Returns
True if all is well.
References check_(), and count().
colorFlip_() [1/3]
LLRBNode::colorFlip_ () [inline]
Returns
Newt ree, after colorFlip.
References copy, left, and right.
colorFlip_() [2/3]
LLRBNode::colorFlip_ () [inline]
Returns
Newt ree, after colorFlip.
References copy, left, and right.
colorFlip_() [3/3]
LLRBNode::colorFlip_ () [inline]
Returns
Newt ree, after colorFlip.
References copy, left, and right.
constructor() [1/3]
LLRBNode::constructor (key, value, color, left, right) [inline]
Parameters
key - Key associated with this node.
value - Value associated with this node.
color - Whether this node is red.
left - Left child.
right - Right child.
References left, right, and value.
constructor() [2/3]
LLRBNode::constructor (key, value, color, left, right) [inline]
Parameters
key - Key associated with this node.
value - Value associated with this node.
color - Whether this node is red.
left - Left child.
right - Right child.
References left, right, and value.
constructor() [3/3]
LLRBNode::constructor (key, value, color, left, right) [inline]
Parameters
key - Key associated with this node.
value - Value associated with this node.
color - Whether this node is red.
left - Left child.
right - Right child.
References left, right, and value.
copy() [1/3]
LLRBNode::copy (key, value, color, left, right) [inline]
Returns a copy of the current node, optionally replacing pieces of it.
Parameters
key - New key for the node, or null.
value - New value for the node, or null.
color - New color for the node, or null.
left - New left child for the node, or null.
right - New right child for the node, or null.
Returns
The node copy.
References left, right, and value.
copy() [2/3]
LLRBNode::copy (key, value, color, left, right) [inline]
Returns a copy of the current node, optionally replacing pieces of it.
Parameters
key - New key for the node, or null.
value - New value for the node, or null.
color - New color for the node, or null.
left - New left child for the node, or null.
right - New right child for the node, or null.
Returns
The node copy.
References left, right, and value.
copy() [3/3]
LLRBNode::copy (key, value, color, left, right) [inline]
Returns a copy of the current node, optionally replacing pieces of it.
Parameters
key - New key for the node, or null.
value - New value for the node, or null.
color - New color for the node, or null.
left - New left child for the node, or null.
right - New right child for the node, or null.
Returns
The node copy.
References left, right, and value.
count() [1/3]
LLRBNode::count () [inline]
Returns
The total number of nodes in the tree.
References left, and right.
count() [2/3]
LLRBNode::count () [inline]
Returns
The total number of nodes in the tree.
References left, and right.
count() [3/3]
LLRBNode::count () [inline]
Returns
The total number of nodes in the tree.
References left, and right.
fixUp_() [1/3]
LLRBNode::fixUp_ () [inline]
Returns
New tree after performing any needed rotations.
References n.
fixUp_() [2/3]
LLRBNode::fixUp_ () [inline]
Returns
New tree after performing any needed rotations.
References n.
fixUp_() [3/3]
LLRBNode::fixUp_ () [inline]
Returns
New tree after performing any needed rotations.
References n.
inorderTraversal() [1/3]
LLRBNode::inorderTraversal (action) [inline]
Traverses the tree in key order and calls the specified action function for each node.
Parameters
action - Callback function to be called for each node. If it returns true, traversal is aborted.
Returns
The first truthy value returned by action, or the last falsey value returned by action
References left, right, and value.
inorderTraversal() [2/3]
LLRBNode::inorderTraversal (action) [inline]
Traverses the tree in key order and calls the specified action function for each node.
Parameters
action - Callback function to be called for each node. If it returns true, traversal is aborted.
Returns
The first truthy value returned by action, or the last falsey value returned by action
References left, right, and value.
inorderTraversal() [3/3]
LLRBNode::inorderTraversal (action) [inline]
Traverses the tree in key order and calls the specified action function for each node.
Parameters
action - Callback function to be called for each node. If it returns true, traversal is aborted.
Returns
The first truthy value returned by action, or the last falsey value returned by action
References left, right, and value.
insert() [1/3]
LLRBNode::insert (key, value, comparator) [inline]
Parameters
key - Key to insert.
value - Value to insert.
comparator - Comparator.
Returns
New tree, with the key/value added.
References n, and value.
insert() [2/3]
LLRBNode::insert (key, value, comparator) [inline]
Parameters
key - Key to insert.
value - Value to insert.
comparator - Comparator.
Returns
New tree, with the key/value added.
References n, and value.
insert() [3/3]
LLRBNode::insert (key, value, comparator) [inline]
Parameters
key - Key to insert.
value - Value to insert.
comparator - Comparator.
Returns
New tree, with the key/value added.
References n, and value.
isEmpty() [1/3]
LLRBNode::isEmpty () [inline]
Returns
True if the tree is empty.
isEmpty() [2/3]
LLRBNode::isEmpty () [inline]
Returns
True if the tree is empty.
isEmpty() [3/3]
LLRBNode::isEmpty () [inline]
Returns
True if the tree is empty.
isRed_() [1/3]
LLRBNode::isRed_ () [inline]
Returns
Whether this is a RED node.
isRed_() [2/3]
LLRBNode::isRed_ () [inline]
Returns
Whether this is a RED node.
isRed_() [3/3]
LLRBNode::isRed_ () [inline]
Returns
Whether this is a RED node.
maxKey() [1/3]
LLRBNode::maxKey () [inline]
Returns
The maximum key in the tree.
References right.
maxKey() [2/3]
LLRBNode::maxKey () [inline]
Returns
The maximum key in the tree.
References right.
maxKey() [3/3]
LLRBNode::maxKey () [inline]
Returns
The maximum key in the tree.
References right.
min_() [1/3]
LLRBNode::min_ () [inline]
Returns
The minimum node in the tree.
References left.
min_() [2/3]
LLRBNode::min_ () [inline]
Returns
The minimum node in the tree.
References left.
min_() [3/3]
LLRBNode::min_ () [inline]
Returns
The minimum node in the tree.
References left.
minKey() [1/3]
LLRBNode::minKey () [inline]
Returns
The maximum key in the tree.
References min_().
minKey() [2/3]
LLRBNode::minKey () [inline]
Returns
The maximum key in the tree.
References min_().
minKey() [3/3]
LLRBNode::minKey () [inline]
Returns
The maximum key in the tree.
References min_().
moveRedLeft_() [1/3]
LLRBNode::moveRedLeft_ () [inline]
Returns
New tree, after moveRedLeft.
References colorFlip_(), and n.
moveRedLeft_() [2/3]
LLRBNode::moveRedLeft_ () [inline]
Returns
New tree, after moveRedLeft.
References colorFlip_(), and n.
moveRedLeft_() [3/3]
LLRBNode::moveRedLeft_ () [inline]
Returns
New tree, after moveRedLeft.
References colorFlip_(), and n.
moveRedRight_() [1/3]
LLRBNode::moveRedRight_ () [inline]
Returns
New tree, after moveRedRight.
References colorFlip_(), and n.
moveRedRight_() [2/3]
LLRBNode::moveRedRight_ () [inline]
Returns
New tree, after moveRedRight.
References colorFlip_(), and n.
moveRedRight_() [3/3]
LLRBNode::moveRedRight_ () [inline]
Returns
New tree, after moveRedRight.
References colorFlip_(), and n.
remove() [1/3]
LLRBNode::remove (key, comparator) [inline]
Parameters
key - The key of the item to remove.
comparator - Comparator.
Returns
New tree, with the specified item removed.
References n.
remove() [2/3]
LLRBNode::remove (key, comparator) [inline]
Parameters
key - The key of the item to remove.
comparator - Comparator.
Returns
New tree, with the specified item removed.
References n.
remove() [3/3]
LLRBNode::remove (key, comparator) [inline]
Parameters
key - The key of the item to remove.
comparator - Comparator.
Returns
New tree, with the specified item removed.
References n.
removeMin_() [1/3]
LLRBNode::removeMin_ () [inline]
Returns
New tree, with the minimum key removed.
References left, and n.
removeMin_() [2/3]
LLRBNode::removeMin_ () [inline]
Returns
New tree, with the minimum key removed.
References left, and n.
removeMin_() [3/3]
LLRBNode::removeMin_ () [inline]
Returns
New tree, with the minimum key removed.
References left, and n.
reverseTraversal() [1/3]
LLRBNode::reverseTraversal (action) [inline]
Traverses the tree in reverse key order and calls the specified action function for each node.
Parameters
action - Callback function to be called for each node. If it returns true, traversal is aborted.
Returns
True if traversal was aborted.
References left, right, and value.
reverseTraversal() [2/3]
LLRBNode::reverseTraversal (action) [inline]
Traverses the tree in reverse key order and calls the specified action function for each node.
Parameters
action - Callback function to be called for each node. If it returns true, traversal is aborted.
Returns
True if traversal was aborted.
References left, right, and value.
reverseTraversal() [3/3]
LLRBNode::reverseTraversal (action) [inline]
Traverses the tree in reverse key order and calls the specified action function for each node.
Parameters
action - Callback function to be called for each node. If it returns true, traversal is aborted.
Returns
True if traversal was aborted.
References left, right, and value.
rotateLeft_() [1/3]
LLRBNode::rotateLeft_ () [inline]
Returns
New tree, after rotateLeft.
References copy, and right.
rotateLeft_() [2/3]
LLRBNode::rotateLeft_ () [inline]
Returns
New tree, after rotateLeft.
References copy, and right.
rotateLeft_() [3/3]
LLRBNode::rotateLeft_ () [inline]
Returns
New tree, after rotateLeft.
References copy, and right.
rotateRight_() [1/3]
LLRBNode::rotateRight_ () [inline]
Returns
New tree, after rotateRight.
References copy, and left.
rotateRight_() [2/3]
LLRBNode::rotateRight_ () [inline]
Returns
New tree, after rotateRight.
References copy, and left.
rotateRight_() [3/3]
LLRBNode::rotateRight_ () [inline]
Returns
New tree, after rotateRight.
References copy, and left.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js