View Class Reference
Public Member Functions
constructor (query_, initialViewCache)
get query ()
constructor (query_, initialViewCache)
get query ()
constructor (query_, initialViewCache)
get query ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. A view represents a specific location and query that has 1 or more event registrations.
It does several things:
Maintains the list of event registrations for this location/query.
Maintains a cache of the data visible for this location/query.
Applies new operations (via applyOperation), updates the cache, and based on the event registrations returns the set of events to be raised.
Member Function Documentation
constructor() [1/3]
View::constructor (query_, initialViewCache) [inline]
References ChildrenNode::EMPTY_NODE(), filter, newViewCache(), newViewProcessor(), and queryParamsGetNodeFilter().
constructor() [2/3]
View::constructor (query_, initialViewCache) [inline]
References ChildrenNode::EMPTY_NODE(), filter, newViewCache(), newViewProcessor(), and queryParamsGetNodeFilter().
constructor() [3/3]
View::constructor (query_, initialViewCache) [inline]
References ChildrenNode::EMPTY_NODE(), filter, newViewCache(), newViewProcessor(), and queryParamsGetNodeFilter().
query() [1/3]
get View::query () [inline]
query() [2/3]
get View::query () [inline]
query() [3/3]
get View::query () [inline]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js