RemoteJWKSet Class Reference
Public Member Functions
constructor (url, options)
coolingDown ()
fresh ()
async getKey (protectedHeader, token)
async reload ()
constructor (url, options)
coolingDown ()
fresh ()
async getKey (protectedHeader, token)
async reload ()
constructor (url, options)
coolingDown ()
fresh ()
async getKey (protectedHeader, token)
async reload ()
constructor (jwks)
Member Function Documentation
constructor() [1/4]
LocalJWKSet::constructor (jwks) [inline], [inherited]
References clone, isJWKSLike, jwks, JWKSInvalid, and WeakMap.
constructor() [2/4]
RemoteJWKSet::constructor (url, options) [inline]
References _options, headers, keys, undefined, URL, and url.
constructor() [3/4]
RemoteJWKSet::constructor (url, options) [inline]
References _options, headers, keys, undefined, URL, and url.
constructor() [4/4]
RemoteJWKSet::constructor (url, options) [inline]
References _options, headers, keys, undefined, URL, and url.
coolingDown() [1/3]
RemoteJWKSet::coolingDown () [inline]
coolingDown() [2/3]
RemoteJWKSet::coolingDown () [inline]
coolingDown() [3/3]
RemoteJWKSet::coolingDown () [inline]
fresh() [1/3]
RemoteJWKSet::fresh () [inline]
fresh() [2/3]
RemoteJWKSet::fresh () [inline]
fresh() [3/3]
RemoteJWKSet::fresh () [inline]
getKey() [1/3]
async RemoteJWKSet::getKey (protectedHeader, token) [inline]
References coolingDown(), fresh(), reload(), and token.
getKey() [2/3]
async RemoteJWKSet::getKey (protectedHeader, token) [inline]
References coolingDown(), errors_js_1, fresh(), reload(), and token.
getKey() [3/3]
async RemoteJWKSet::getKey (protectedHeader, token) [inline]
References coolingDown(), fresh(), reload(), and token.
reload() [1/3]
async RemoteJWKSet::reload () [inline]
References _options, fetchJwks, isCloudflareWorkers(), isJWKSLike, JWKSInvalid, keys, and undefined.
reload() [2/3]
async RemoteJWKSet::reload () [inline]
References _options, errors_js_1, fetch_jwks_js_1, isCloudflareWorkers(), keys, local_js_1, and undefined.
reload() [3/3]
async RemoteJWKSet::reload () [inline]
References _options, fetchJwks, isCloudflareWorkers(), isJWKSLike, JWKSInvalid, keys, and undefined.
The documentation for this class was generated from the following files:
backend/node_modules/jose/dist/browser/jwks/remote.js
backend/node_modules/jose/dist/node/cjs/jwks/remote.js
backend/node_modules/jose/dist/node/esm/jwks/remote.js