Base12Num Class Reference
Public Member Functions
constructor (length)
nextBitIsOne ()
constructor (length)
nextBitIsOne ()
constructor (length)
nextBitIsOne ()
Member Function Documentation
constructor() [1/3]
Base12Num::constructor (length) [inline]
References Array, count, join, length, LOG_2, mask, and parseInt().
constructor() [2/3]
Base12Num::constructor (length) [inline]
References Array, count, join, length, LOG_2, mask, and parseInt().
constructor() [3/3]
Base12Num::constructor (length) [inline]
References Array, count, join, length, LOG_2, mask, and parseInt().
nextBitIsOne() [1/3]
Base12Num::nextBitIsOne () [inline]
References result.
nextBitIsOne() [2/3]
Base12Num::nextBitIsOne () [inline]
References result.
nextBitIsOne() [3/3]
Base12Num::nextBitIsOne () [inline]
References result.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js