LeafNode Class Reference
Public Member Functions
constructor (value_, priorityNode_=LeafNode.__childrenNodeConstructor.EMPTY_NODE)
isLeafNode ()
getPriority ()
updatePriority (newPriorityNode)
getImmediateChild (childName)
getChild (path)
hasChild ()
getPredecessorChildName (childName, childNode)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
isEmpty ()
numChildren ()
forEachChild (index, action)
val (exportFormat)
hash ()
getValue ()
compareTo (other)
compareToLeafNode_ (otherLeaf)
withIndex ()
isIndexed ()
equals (other)
constructor (value_, priorityNode_=LeafNode.__childrenNodeConstructor.EMPTY_NODE)
isLeafNode ()
getPriority ()
updatePriority (newPriorityNode)
getImmediateChild (childName)
getChild (path)
hasChild ()
getPredecessorChildName (childName, childNode)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
isEmpty ()
numChildren ()
forEachChild (index, action)
val (exportFormat)
hash ()
getValue ()
compareTo (other)
compareToLeafNode_ (otherLeaf)
withIndex ()
isIndexed ()
equals (other)
constructor (value_, priorityNode_=LeafNode.__childrenNodeConstructor.EMPTY_NODE)
isLeafNode ()
getPriority ()
updatePriority (newPriorityNode)
getImmediateChild (childName)
getChild (path)
hasChild ()
getPredecessorChildName (childName, childNode)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
isEmpty ()
numChildren ()
forEachChild (index, action)
val (exportFormat)
hash ()
getValue ()
compareTo (other)
compareToLeafNode_ (otherLeaf)
withIndex ()
isIndexed ()
equals (other)
Static Public Member Functions
static set __childrenNodeConstructor (val)
static get __childrenNodeConstructor ()
static set __childrenNodeConstructor (val)
static get __childrenNodeConstructor ()
static set __childrenNodeConstructor (val)
static get __childrenNodeConstructor ()
Detailed Description
LeafNode is a class for storing leaf nodes in a DataSnapshot. It implements Node and stores the value of the node (a string, number, or boolean) accessible via getValue().
Member Function Documentation
__childrenNodeConstructor() [1/6]
static get LeafNode::__childrenNodeConstructor () [inline], [static]
References __childrenNodeConstructor().
__childrenNodeConstructor() [2/6]
static get LeafNode::__childrenNodeConstructor () [inline], [static]
References __childrenNodeConstructor().
__childrenNodeConstructor() [3/6]
static get LeafNode::__childrenNodeConstructor () [inline], [static]
References __childrenNodeConstructor().
__childrenNodeConstructor() [4/6]
static set LeafNode::__childrenNodeConstructor (val) [inline], [static]
References __childrenNodeConstructor(), and val().
__childrenNodeConstructor() [5/6]
static set LeafNode::__childrenNodeConstructor (val) [inline], [static]
References __childrenNodeConstructor(), and val().
__childrenNodeConstructor() [6/6]
static set LeafNode::__childrenNodeConstructor (val) [inline], [static]
References __childrenNodeConstructor(), and val().
compareTo() [1/3]
LeafNode::compareTo (other) [inline]
References __childrenNodeConstructor(), compareToLeafNode_(), and util.
compareTo() [2/3]
LeafNode::compareTo (other) [inline]
References __childrenNodeConstructor(), assert, and compareToLeafNode_().
compareTo() [3/3]
LeafNode::compareTo (other) [inline]
References __childrenNodeConstructor(), assert, and compareToLeafNode_().
compareToLeafNode_() [1/3]
LeafNode::compareToLeafNode_ (otherLeaf) [inline]
Comparison specifically for two leaf nodes
References util.
compareToLeafNode_() [2/3]
LeafNode::compareToLeafNode_ (otherLeaf) [inline]
Comparison specifically for two leaf nodes
References assert.
compareToLeafNode_() [3/3]
LeafNode::compareToLeafNode_ (otherLeaf) [inline]
Comparison specifically for two leaf nodes
References assert.
constructor() [1/3]
LeafNode::constructor (value_, priorityNode_ = LeafNode.__childrenNodeConstructor.EMPTY_NODE) [inline]
Parameters
value_ - The value to store in this leaf node. The object type is possible in the event of a deferred value
priorityNode_ - The priority of this node.
References undefined, util, and validatePriorityNode.
constructor() [2/3]
LeafNode::constructor (value_, priorityNode_ = LeafNode.__childrenNodeConstructor.EMPTY_NODE) [inline]
Parameters
value_ - The value to store in this leaf node. The object type is possible in the event of a deferred value
priorityNode_ - The priority of this node.
References assert, undefined, and validatePriorityNode.
constructor() [3/3]
LeafNode::constructor (value_, priorityNode_ = LeafNode.__childrenNodeConstructor.EMPTY_NODE) [inline]
Parameters
value_ - The value to store in this leaf node. The object type is possible in the event of a deferred value
priorityNode_ - The priority of this node.
References assert, undefined, and validatePriorityNode.
equals() [1/3]
LeafNode::equals (other) [inline]
equals() [2/3]
LeafNode::equals (other) [inline]
equals() [3/3]
LeafNode::equals (other) [inline]
forEachChild() [1/3]
LeafNode::forEachChild (index, action) [inline]
@inheritDoc
forEachChild() [2/3]
LeafNode::forEachChild (index, action) [inline]
@inheritDoc
forEachChild() [3/3]
LeafNode::forEachChild (index, action) [inline]
@inheritDoc
getChild() [1/3]
LeafNode::getChild (path) [inline]
@inheritDoc
References __childrenNodeConstructor(), path, pathGetFront(), and pathIsEmpty().
getChild() [2/3]
LeafNode::getChild (path) [inline]
@inheritDoc
References __childrenNodeConstructor(), path, pathGetFront(), and pathIsEmpty().
getChild() [3/3]
LeafNode::getChild (path) [inline]
@inheritDoc
References __childrenNodeConstructor(), path, pathGetFront(), and pathIsEmpty().
getImmediateChild() [1/3]
LeafNode::getImmediateChild (childName) [inline]
@inheritDoc
References __childrenNodeConstructor().
getImmediateChild() [2/3]
LeafNode::getImmediateChild (childName) [inline]
@inheritDoc
References __childrenNodeConstructor().
getImmediateChild() [3/3]
LeafNode::getImmediateChild (childName) [inline]
@inheritDoc
References __childrenNodeConstructor().
getPredecessorChildName() [1/3]
LeafNode::getPredecessorChildName (childName, childNode) [inline]
@inheritDoc
getPredecessorChildName() [2/3]
LeafNode::getPredecessorChildName (childName, childNode) [inline]
@inheritDoc
getPredecessorChildName() [3/3]
LeafNode::getPredecessorChildName (childName, childNode) [inline]
@inheritDoc
getPriority() [1/3]
LeafNode::getPriority () [inline]
@inheritDoc Here is the caller graph for this function:
getPriority() [2/3]
LeafNode::getPriority () [inline]
@inheritDoc
getPriority() [3/3]
LeafNode::getPriority () [inline]
@inheritDoc
getValue() [1/3]
LeafNode::getValue () [inline]
Returns the value of the leaf node.
Returns
The value of the node.
getValue() [2/3]
LeafNode::getValue () [inline]
Returns the value of the leaf node.
Returns
The value of the node.
getValue() [3/3]
LeafNode::getValue () [inline]
Returns the value of the leaf node.
Returns
The value of the node.
hasChild() [1/3]
LeafNode::hasChild () [inline]
hasChild() [2/3]
LeafNode::hasChild () [inline]
hasChild() [3/3]
LeafNode::hasChild () [inline]
hash() [1/3]
LeafNode::hash () [inline]
@inheritDoc
References doubleToIEEE754String, priorityHashText, sha1, toHash, and type.
hash() [2/3]
LeafNode::hash () [inline]
@inheritDoc
References doubleToIEEE754String, priorityHashText, sha1, toHash, and type.
hash() [3/3]
LeafNode::hash () [inline]
@inheritDoc
References doubleToIEEE754String, priorityHashText, sha1, toHash, and type.
isEmpty() [1/3]
LeafNode::isEmpty () [inline]
@inheritDoc Here is the caller graph for this function:
isEmpty() [2/3]
LeafNode::isEmpty () [inline]
@inheritDoc
isEmpty() [3/3]
LeafNode::isEmpty () [inline]
@inheritDoc
isIndexed() [1/3]
LeafNode::isIndexed () [inline]
isIndexed() [2/3]
LeafNode::isIndexed () [inline]
isIndexed() [3/3]
LeafNode::isIndexed () [inline]
isLeafNode() [1/3]
LeafNode::isLeafNode () [inline]
@inheritDoc
isLeafNode() [2/3]
LeafNode::isLeafNode () [inline]
@inheritDoc
isLeafNode() [3/3]
LeafNode::isLeafNode () [inline]
@inheritDoc
numChildren() [1/3]
LeafNode::numChildren () [inline]
@inheritDoc
numChildren() [2/3]
LeafNode::numChildren () [inline]
@inheritDoc
numChildren() [3/3]
LeafNode::numChildren () [inline]
@inheritDoc
updateChild() [1/3]
LeafNode::updateChild (path, newChildNode) [inline]
@inheritDoc
References __childrenNodeConstructor(), front, path, pathGetFront(), pathGetLength(), pathPopFront(), updateImmediateChild(), and util.
updateChild() [2/3]
LeafNode::updateChild (path, newChildNode) [inline]
@inheritDoc
References __childrenNodeConstructor(), assert, front, path, pathGetFront(), pathGetLength(), pathPopFront(), and updateImmediateChild().
updateChild() [3/3]
LeafNode::updateChild (path, newChildNode) [inline]
@inheritDoc
References __childrenNodeConstructor(), assert, front, path, pathGetFront(), pathGetLength(), pathPopFront(), and updateImmediateChild().
updateImmediateChild() [1/3]
LeafNode::updateImmediateChild (childName, newChildNode) [inline]
@inheritDoc
References __childrenNodeConstructor(), and updatePriority().
updateImmediateChild() [2/3]
LeafNode::updateImmediateChild (childName, newChildNode) [inline]
@inheritDoc
References __childrenNodeConstructor(), and updatePriority().
updateImmediateChild() [3/3]
LeafNode::updateImmediateChild (childName, newChildNode) [inline]
@inheritDoc
References __childrenNodeConstructor(), and updatePriority().
updatePriority() [1/3]
LeafNode::updatePriority (newPriorityNode) [inline]
@inheritDoc Here is the caller graph for this function:
updatePriority() [2/3]
LeafNode::updatePriority (newPriorityNode) [inline]
@inheritDoc
updatePriority() [3/3]
LeafNode::updatePriority (newPriorityNode) [inline]
@inheritDoc
val() [1/3]
LeafNode::val (exportFormat) [inline]
References getPriority(), getValue(), and isEmpty().
val() [2/3]
LeafNode::val (exportFormat) [inline]
References getPriority(), getValue(), and isEmpty().
val() [3/3]
LeafNode::val (exportFormat) [inline]
References getPriority(), getValue(), and isEmpty().
withIndex() [1/3]
LeafNode::withIndex () [inline]
withIndex() [2/3]
LeafNode::withIndex () [inline]
withIndex() [3/3]
LeafNode::withIndex () [inline]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js