Bucket Class Reference
Public Member Functions
getFilesStream (query)
get cloudStorageURI ()
addLifecycleRule (rule, optionsOrCallback, callback)
combine (sources, destination, optionsOrCallback, callback)
createChannel (id, config, optionsOrCallback, callback)
createNotification (topic, optionsOrCallback, callback)
deleteFiles (queryOrCallback, callback)
deleteLabels (labelsOrCallbackOrOptions, optionsOrCallback, callback)
disableRequesterPays (optionsOrCallback, callback)
enableLogging (config, callback)
enableRequesterPays (optionsOrCallback, cb)
file (name, options)
getFiles (queryOrCallback, callback)
getLabels (optionsOrCallback, callback)
getNotifications (optionsOrCallback, callback)
getSignedUrl (cfg, callback)
lock (metageneration, callback)
makePrivate (optionsOrCallback, callback)
makePublic (optionsOrCallback, callback)
notification (id)
removeRetentionPeriod (optionsOrCallback, callback)
setLabels (labels, optionsOrCallback, callback)
setMetadata (metadata, optionsOrCallback, cb)
setRetentionPeriod (duration, optionsOrCallback, callback)
setCorsConfiguration (corsConfiguration, optionsOrCallback, callback)
setStorageClass (storageClass, optionsOrCallback, callback)
setUserProject (userProject)
upload (pathString, optionsOrCallback, callback)
getId ()
disableAutoRetryConditionallyIdempotent_ (coreOpts, methodType, localPreconditionOptions)
getFilesStream (query)
get cloudStorageURI ()
addLifecycleRule (rule, optionsOrCallback, callback)
combine (sources, destination, optionsOrCallback, callback)
createChannel (id, config, optionsOrCallback, callback)
createNotification (topic, optionsOrCallback, callback)
deleteFiles (queryOrCallback, callback)
deleteLabels (labelsOrCallbackOrOptions, optionsOrCallback, callback)
disableRequesterPays (optionsOrCallback, callback)
enableLogging (config, callback)
enableRequesterPays (optionsOrCallback, cb)
file (name, options)
getFiles (queryOrCallback, callback)
getLabels (optionsOrCallback, callback)
getNotifications (optionsOrCallback, callback)
getSignedUrl (cfg, callback)
lock (metageneration, callback)
makePrivate (optionsOrCallback, callback)
makePublic (optionsOrCallback, callback)
notification (id)
removeRetentionPeriod (optionsOrCallback, callback)
setLabels (labels, optionsOrCallback, callback)
setMetadata (metadata, optionsOrCallback, cb)
setRetentionPeriod (duration, optionsOrCallback, callback)
setCorsConfiguration (corsConfiguration, optionsOrCallback, callback)
setStorageClass (storageClass, optionsOrCallback, callback)
setUserProject (userProject)
upload (pathString, optionsOrCallback, callback)
getId ()
disableAutoRetryConditionallyIdempotent_ (coreOpts, methodType, localPreconditionOptions)
constructor (config)
constructor (config)
create (optionsOrCallback, callback)
create (optionsOrCallback, callback)
delete (optionsOrCallback, cb)
delete (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
exists (optionsOrCallback, cb)
get (optionsOrCallback, cb)
get (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getMetadata (optionsOrCallback, cb)
getRequestInterceptors ()
getRequestInterceptors ()
request_ (reqOpts, callback)
request_ (reqOpts, callback)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
trigger (eventType,...varArgs)
on (eventType, callback, context)
on (eventType, callback, context)
on (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
validateEventType_ (eventType)
validateEventType_ (eventType)
Private Member Functions
request (reqOpts, callback)
makeAllFilesPublicPrivate_ (optionsOrCallback, callback)
request (reqOpts, callback)
makeAllFilesPublicPrivate_ (optionsOrCallback, callback)
Member Function Documentation
addLifecycleRule() [1/2]
Bucket::addLifecycleRule (rule, optionsOrCallback, callback) [inline]
References $, _a, _b, Array, callback, ServiceObject::getMetadata(), of, setMetadata(), and T.
addLifecycleRule() [2/2]
Bucket::addLifecycleRule (rule, optionsOrCallback, callback) [inline]
References $, _a, _b, Array, callback, ServiceObject::getMetadata(), of, setMetadata(), and T.
cloudStorageURI() [1/2]
get Bucket::cloudStorageURI () [inline]
References name, and url_1.
cloudStorageURI() [2/2]
get Bucket::cloudStorageURI () [inline]
References name, and URL.
combine() [1/2]
Bucket::combine (sources, destination, optionsOrCallback, callback) [inline]
References _a, Array, BucketExceptionMessages, callback, contentType, disableAutoRetryConditionallyIdempotent_(), file, file_js_1, index_js_1, json, method, methods, mime_1, name, parseInt(), qs, source, storage, storage_js_1, and undefined.
combine() [2/2]
Bucket::combine (sources, destination, optionsOrCallback, callback) [inline]
References _a, Array, BucketExceptionMessages, callback, contentType, disableAutoRetryConditionallyIdempotent_(), File, file, IdempotencyStrategy, json, method, methods, mime, name, parseInt(), qs, source, storage, undefined, and util.
constructor() [1/2]
ServiceObject::constructor (config) [inline], [inherited]
References config, forEach, ServiceObject::getRequestInterceptors(), methods, parent, request, test, and undefined.
constructor() [2/2]
ServiceObject::constructor (config) [inline], [inherited]
References config, forEach, ServiceObject::getRequestInterceptors(), methods, parent, request, test, and undefined.
create() [1/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
create() [2/2]
ServiceObject::create (optionsOrCallback, callback) [inline], [inherited]
References args, callback, and instance.
createChannel() [1/2]
Bucket::createChannel (id, config, optionsOrCallback, callback) [inline]
References BucketExceptionMessages, callback, config, json, method, qs, request, storage, and type.
createChannel() [2/2]
Bucket::createChannel (id, config, optionsOrCallback, callback) [inline]
References BucketExceptionMessages, callback, config, json, method, qs, request, storage, and type.
createNotification() [1/2]
Bucket::createNotification (topic, optionsOrCallback, callback) [inline]
References BucketExceptionMessages, callback, index_js_1, json, method, notification(), qs, query, request, and util_js_1.
createNotification() [2/2]
Bucket::createNotification (topic, optionsOrCallback, callback) [inline]
References BucketExceptionMessages, callback, convertObjKeysToSnakeCase, json, method, notification(), qs, query, request, and util.
delete() [1/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util_js_1.
delete() [2/2]
ServiceObject::delete (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, method, methods, qs, res, and util.
deleteFiles() [1/2]
Bucket::deleteFiles (queryOrCallback, callback) [inline]
References async, callback, e, errors, file, getFilesStream(), limit, of, p_limit_1, Promise, and query.
deleteFiles() [2/2]
Bucket::deleteFiles (queryOrCallback, callback) [inline]
References async, callback, e, errors, file, getFilesStream(), limit, of, pLimit, Promise, and query.
deleteLabels() [1/2]
Bucket::deleteLabels (labelsOrCallbackOrOptions, optionsOrCallback, callback) [inline]
References Array, callback, deleteLabels(), getLabels(), setLabels(), and undefined.
deleteLabels() [2/2]
Bucket::deleteLabels (labelsOrCallbackOrOptions, optionsOrCallback, callback) [inline]
References Array, callback, deleteLabels(), getLabels(), setLabels(), and undefined.
disableAutoRetryConditionallyIdempotent_() [1/2]
Bucket::disableAutoRetryConditionallyIdempotent_ (coreOpts, methodType, localPreconditionOptions) [inline]
References _a, _b, AvailableServiceObjectMethods, storage, storage_js_1, and undefined.
disableAutoRetryConditionallyIdempotent_() [2/2]
Bucket::disableAutoRetryConditionallyIdempotent_ (coreOpts, methodType, localPreconditionOptions) [inline]
References _a, _b, AvailableServiceObjectMethods, IdempotencyStrategy, storage, and undefined.
disableRequesterPays() [1/2]
Bucket::disableRequesterPays (optionsOrCallback, callback) [inline]
References callback, and setMetadata().
disableRequesterPays() [2/2]
Bucket::disableRequesterPays (optionsOrCallback, callback) [inline]
References callback, and setMetadata().
enableLogging() [1/2]
Bucket::enableLogging (config, callback) [inline]
References async, BucketExceptionMessages, callback, config, e, logging, and setMetadata().
enableLogging() [2/2]
Bucket::enableLogging (config, callback) [inline]
References async, BucketExceptionMessages, callback, config, e, logging, and setMetadata().
enableRequesterPays() [1/2]
Bucket::enableRequesterPays (optionsOrCallback, cb) [inline]
References setMetadata().
enableRequesterPays() [2/2]
Bucket::enableRequesterPays (optionsOrCallback, cb) [inline]
References setMetadata().
exists() [1/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util_js_1.
exists() [2/2]
ServiceObject::exists (optionsOrCallback, cb) [inline], [inherited]
References callback, and util.
file() [1/2]
Bucket::file (name, options) [inline]
References BucketExceptionMessages, file_js_1, and name.
file() [2/2]
Bucket::file (name, options) [inline]
References BucketExceptionMessages, File, and name.
get() [1/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util_js_1.
get() [2/2]
ServiceObject::get (optionsOrCallback, cb) [inline], [inherited]
References args, callback, create, ServiceObject::getMetadata(), instance, and util.
getFiles() [1/2]
Bucket::getFiles (queryOrCallback, callback) [inline]
References callback, file, qs, query, and request.
getFiles() [2/2]
Bucket::getFiles (queryOrCallback, callback) [inline]
References callback, file, qs, query, and request.
getFilesStream() [1/2]
Bucket::getFilesStream (query) [inline]
References stream_1.
getFilesStream() [2/2]
Bucket::getFilesStream (query) [inline]
References Readable.
getId() [1/2]
Bucket::getId () [inline]
getId() [2/2]
Bucket::getId () [inline]
getLabels() [1/2]
Bucket::getLabels (optionsOrCallback, callback) [inline]
References callback, and ServiceObject::getMetadata().
getLabels() [2/2]
Bucket::getLabels (optionsOrCallback, callback) [inline]
References callback, and ServiceObject::getMetadata().
getMetadata() [1/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util_js_1.
getMetadata() [2/2]
ServiceObject::getMetadata (optionsOrCallback, cb) [inline], [inherited]
References _a, callback, methods, qs, res, and util.
getNotifications() [1/2]
Bucket::getNotifications (optionsOrCallback, callback) [inline]
References callback, notification(), qs, and request.
getNotifications() [2/2]
Bucket::getNotifications (optionsOrCallback, callback) [inline]
References callback, notification(), qs, and request.
getRequestInterceptors() [1/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
getRequestInterceptors() [2/2]
ServiceObject::getRequestInterceptors () [inline], [inherited]
Return the user's custom request interceptors.
References parent.
getSignedUrl() [1/2]
Bucket::getSignedUrl (cfg, callback) [inline]
References BucketActionToHTTPMethod, callback, method, signer_js_1, storage, undefined, and version.
getSignedUrl() [2/2]
Bucket::getSignedUrl (cfg, callback) [inline]
References BucketActionToHTTPMethod, callback, method, storage, undefined, and version.
lock() [1/2]
Bucket::lock (metageneration, callback) [inline]
References BucketExceptionMessages, callback, method, qs, and request.
lock() [2/2]
Bucket::lock (metageneration, callback) [inline]
References BucketExceptionMessages, callback, method, qs, and request.
makeAllFilesPublicPrivate_() [1/2]
Bucket::makeAllFilesPublicPrivate_ (optionsOrCallback, callback) [inline], [private]
Iterate over all of a bucket's files, calling file.makePublic() (public) or file.makePrivate() (private) on each.
Operations are performed in parallel, up to 10 at once. The first error breaks the loop, and will execute the provided callback with it. Specify { force: true } to suppress the errors.
Parameters
{MakeAllFilesPublicPrivateOptions} [options] Configuration options.
{boolean} [options.force] Suppress errors until all files have been processed.
{boolean} [options.private] Make files private.
{boolean} [options.public] Make files public.
{string} [options.userProject] The ID of the project which will be billed for the request.
{MakeAllFilesPublicPrivateCallback} callback Callback function.
Returns
{Promise<MakeAllFilesPublicPrivateResponse>}
References async, callback, e, errors, file, getFiles(), limit, p_limit_1, Promise, and then.
makeAllFilesPublicPrivate_() [2/2]
Bucket::makeAllFilesPublicPrivate_ (optionsOrCallback, callback) [inline], [private]
Iterate over all of a bucket's files, calling file.makePublic() (public) or file.makePrivate() (private) on each.
Operations are performed in parallel, up to 10 at once. The first error breaks the loop, and will execute the provided callback with it. Specify { force: true } to suppress the errors.
Parameters
{MakeAllFilesPublicPrivateOptions} [options] Configuration options.
{boolean} [options.force] Suppress errors until all files have been processed.
{boolean} [options.private] Make files private.
{boolean} [options.public] Make files public.
{string} [options.userProject] The ID of the project which will be billed for the request.
{MakeAllFilesPublicPrivateCallback} callback Callback function.
Returns
{Promise<MakeAllFilesPublicPrivateResponse>}
References async, callback, e, errors, file, getFiles(), limit, pLimit, Promise, and then.
makePrivate() [1/2]
Bucket::makePrivate (optionsOrCallback, callback) [inline]
References _a, _b, _c, _d, acl, call, callback, makeAllFilesPublicPrivate_(), Promise, query, setMetadata(), and util_1.
makePrivate() [2/2]
Bucket::makePrivate (optionsOrCallback, callback) [inline]
References _a, _b, _c, _d, acl, callback, makeAllFilesPublicPrivate_(), Promise, promisify, query, and setMetadata().
makePublic() [1/2]
Bucket::makePublic (optionsOrCallback, callback) [inline]
References acl, call, callback, makeAllFilesPublicPrivate_(), req, then, and util_1.
makePublic() [2/2]
Bucket::makePublic (optionsOrCallback, callback) [inline]
References acl, callback, makeAllFilesPublicPrivate_(), promisify, req, and then.
notification() [1/2]
Bucket::notification (id) [inline]
References BucketExceptionMessages, and notification_js_1.
notification() [2/2]
Bucket::notification (id) [inline]
References BucketExceptionMessages, and Notification.
off() [1/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [2/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
off() [3/3]
EventEmitter::off (eventType, callback, context) [inline], [inherited]
References callback, context, i, and EventEmitter::validateEventType_().
on() [1/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [2/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
on() [3/3]
EventEmitter::on (eventType, callback, context) [inline], [inherited]
References callback, context, and EventEmitter::validateEventType_().
removeRetentionPeriod() [1/2]
Bucket::removeRetentionPeriod (optionsOrCallback, callback) [inline]
References callback, and setMetadata().
removeRetentionPeriod() [2/2]
Bucket::removeRetentionPeriod (optionsOrCallback, callback) [inline]
References callback, and setMetadata().
request() [1/2]
Bucket::request (reqOpts, callback) [inline], [private]
Makes request and applies userProject query parameter if necessary.
Parameters
{object} reqOpts - The request options.
{function} callback - The callback function.
References callback.
request() [2/2]
Bucket::request (reqOpts, callback) [inline], [private]
Makes request and applies userProject query parameter if necessary.
Parameters
{object} reqOpts - The request options.
{function} callback - The callback function.
References callback.
request_() [1/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
request_() [2/2]
ServiceObject::request_ (reqOpts, callback) [inline], [inherited]
setCorsConfiguration() [1/2]
Bucket::setCorsConfiguration (corsConfiguration, optionsOrCallback, callback) [inline]
References callback, cors, and setMetadata().
setCorsConfiguration() [2/2]
Bucket::setCorsConfiguration (corsConfiguration, optionsOrCallback, callback) [inline]
References callback, cors, and setMetadata().
setLabels() [1/2]
Bucket::setLabels (labels, optionsOrCallback, callback) [inline]
References callback, index_js_1, and setMetadata().
setLabels() [2/2]
Bucket::setLabels (labels, optionsOrCallback, callback) [inline]
References callback, setMetadata(), and util.
setMetadata() [1/2]
Bucket::setMetadata (metadata, optionsOrCallback, cb) [inline]
References disableAutoRetryConditionallyIdempotent_(), methods, and storage.
setMetadata() [2/2]
Bucket::setMetadata (metadata, optionsOrCallback, cb) [inline]
References disableAutoRetryConditionallyIdempotent_(), methods, and storage.
setRetentionPeriod() [1/2]
Bucket::setRetentionPeriod (duration, optionsOrCallback, callback) [inline]
References callback, and setMetadata().
setRetentionPeriod() [2/2]
Bucket::setRetentionPeriod (duration, optionsOrCallback, callback) [inline]
References callback, and setMetadata().
setStorageClass() [1/2]
Bucket::setStorageClass (storageClass, optionsOrCallback, callback) [inline]
References _, a, callback, g, setMetadata(), and Z().
setStorageClass() [2/2]
Bucket::setStorageClass (storageClass, optionsOrCallback, callback) [inline]
References _, a, callback, g, setMetadata(), and Z().
setUserProject() [1/2]
Bucket::setUserProject (userProject) [inline]
References method, methods, and qs.
setUserProject() [2/2]
Bucket::setUserProject (userProject) [inline]
References method, methods, and qs.
trigger() [1/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [2/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [3/3]
EventEmitter::trigger (eventType, ...) [inline], [inherited]
To be called by derived classes to trigger events.
References Array, context, and i.
upload() [1/2]
Bucket::upload (pathString, optionsOrCallback, callback) [inline]
References _a, _b, async, async_retry_1, callback, file, file_js_1, fs, global, on, path, Promise, reject(), resolve, storage, storage_js_1, undefined, upload, and writable.
upload() [2/2]
Bucket::upload (pathString, optionsOrCallback, callback) [inline]
References _a, _b, async, callback, File, file, fs, global, IdempotencyStrategy, on, path, Promise, reject(), resolve, storage, undefined, upload, and writable.
validateEventType_() [1/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References et, and util.
validateEventType_() [2/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
validateEventType_() [3/3]
EventEmitter::validateEventType_ (eventType) [inline], [inherited]
References assert, and et.
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/bucket.js
backend/node_modules/@google-cloud/storage/build/esm/src/bucket.js