Serializer Class Reference
Public Member Functions
constructor (firestore)
Private Member Functions
encodeFields (obj)
encodeValue (val)
encodeVector (rawVector)
decodeValue (proto)
decodeGoogleProtobufValue (proto)
decodeGoogleProtobufList (proto)
decodeGoogleProtobufStruct (proto)
Detailed Description
Serializer that is used to convert between JavaScript types and their Firestore Protobuf representation.
Member Function Documentation
constructor()
Serializer::constructor (firestore) [inline]
References firestore, n, and path.
decodeGoogleProtobufList()
Serializer::decodeGoogleProtobufList (proto) [inline], [private]
Decodes a google.protobuf.ListValue
References Array, decodeGoogleProtobufValue(), of, proto, result, and value.
decodeGoogleProtobufStruct()
Serializer::decodeGoogleProtobufStruct (proto) [inline], [private]
Decodes a google.protobuf.Struct
References decodeGoogleProtobufValue(), of, prop, proto, and result.
decodeGoogleProtobufValue()
Serializer::decodeGoogleProtobufValue (proto) [inline], [private]
Decodes a google.protobuf.Value
References convert_1, decodeGoogleProtobufList(), decodeGoogleProtobufStruct(), JSON, and proto.
decodeValue()
Serializer::decodeValue (proto) [inline], [private]
Decodes a single Firestore 'Value' Protobuf.
References Array, convert_1, decodeValue(), field_value_1, geo_point_1, JSON, map_type_1, obj, of, path_1, prop, proto, timestamp_1, and value.
encodeFields()
Serializer::encodeFields (obj) [inline], [private]
Encodes a JavaScript object into the Firestore 'Fields' representation.
References encodeValue(), obj, of, and prop.
encodeValue()
Serializer::encodeValue (val) [inline], [private]
Encodes a JavaScript value into the Firestore 'Value' representation.
References $, Array, encode, encodeFields(), encodeValue(), field_value_1, i, isMomentJsType(), map, timestamp, timestamp_1, undefined, util_1, and value.
encodeVector()
Serializer::encodeVector (rawVector) [inline], [private]
References map_type_1, value, and values.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/serializer.js