AuthorizedHttpClient Class Reference
Public Member Functions
constructor (app)
send (request)
getToken ()
sendWithRetry (config, retryAttempts=0)
createRequestResponse (resp)
waitForRetry (delayMillis)
getRetryDelayMillis (retryAttempts, err)
isRetryEligible (retryAttempts, err)
parseRetryAfterIntoMillis (retryAfter)
backOffDelayMillis (retryAttempts)
Member Function Documentation
backOffDelayMillis()
RequestClient::backOffDelayMillis (retryAttempts) [inline], [inherited]
References error_1, and retry.
constructor()
AuthorizedHttpClient::constructor (app) [inline]
References app.
createRequestResponse()
RequestClient::createRequestResponse (resp) [inline], [inherited]
getRetryDelayMillis()
RequestClient::getRetryDelayMillis (retryAttempts, err) [inline], [inherited]
Checks if a failed request is eligible for a retry, and if so returns the duration to wait before initiating the retry.
Parameters
retryAttempts - Number of retries completed up to now.
err - The last encountered error.
Returns
A 2-tuple where the 1st element is the duration to wait before another retry, and the 2nd element is a boolean indicating whether the request is eligible for a retry or not.
References RequestClient::backOffDelayMillis(), RequestClient::isRetryEligible(), RequestClient::parseRetryAfterIntoMillis(), and response.
getToken()
AuthorizedHttpClient::getToken () [inline]
References app.
isRetryEligible()
RequestClient::isRetryEligible (retryAttempts, err) [inline], [inherited]
References retry.
parseRetryAfterIntoMillis()
RequestClient::parseRetryAfterIntoMillis (retryAfter) [inline], [inherited]
??? Parses the Retry-After header as a milliseconds value. Return value is negative if the Retry-After header contains an expired timestamp or otherwise malformed.
References isNaN, and parseInt().
send()
AuthorizedHttpClient::send (request) [inline]
References $, app, getToken(), request, and token.
sendWithRetry()
HttpClient::sendWithRetry (config, retryAttempts = 0) [inline], [inherited]
Sends an HTTP request. In the event of an error, retries the HTTP request according to the RetryConfig set on the HttpClient.
Parameters
config - HTTP request to be sent.
retryAttempts - Number of retries performed up to now.
Returns
A promise that resolves with the response details.
References $, config, RequestClient::createRequestResponse(), error_1, RequestClient::getRetryDelayMillis(), AsyncHttpCall::invoke(), request, RequestResponseError, retry, HttpClient::sendWithRetry(), and RequestClient::waitForRetry().
waitForRetry()
RequestClient::waitForRetry (delayMillis) [inline], [inherited]
References Promise, and resolve.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js