ChildrenNode Class Reference
Public Member Functions
constructor (children_, priorityNode_, indexMap_)
isLeafNode ()
getPriority ()
updatePriority (newPriorityNode)
getImmediateChild (childName)
getChild (path)
hasChild (childName)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
isEmpty ()
numChildren ()
val (exportFormat)
hash ()
getPredecessorChildName (childName, childNode, index)
getFirstChildName (indexDefinition)
getFirstChild (indexDefinition)
getLastChildName (indexDefinition)
getLastChild (indexDefinition)
forEachChild (index, action)
getIterator (indexDefinition)
getIteratorFrom (startPost, indexDefinition)
getReverseIterator (indexDefinition)
getReverseIteratorFrom (endPost, indexDefinition)
compareTo (other)
withIndex (indexDefinition)
isIndexed (index)
equals (other)
resolveIndex_ (indexDefinition)
constructor (children_, priorityNode_, indexMap_)
isLeafNode ()
getPriority ()
updatePriority (newPriorityNode)
getImmediateChild (childName)
getChild (path)
hasChild (childName)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
isEmpty ()
numChildren ()
val (exportFormat)
hash ()
getPredecessorChildName (childName, childNode, index)
getFirstChildName (indexDefinition)
getFirstChild (indexDefinition)
getLastChildName (indexDefinition)
getLastChild (indexDefinition)
forEachChild (index, action)
getIterator (indexDefinition)
getIteratorFrom (startPost, indexDefinition)
getReverseIterator (indexDefinition)
getReverseIteratorFrom (endPost, indexDefinition)
compareTo (other)
withIndex (indexDefinition)
isIndexed (index)
equals (other)
resolveIndex_ (indexDefinition)
constructor (children_, priorityNode_, indexMap_)
isLeafNode ()
getPriority ()
updatePriority (newPriorityNode)
getImmediateChild (childName)
getChild (path)
hasChild (childName)
updateImmediateChild (childName, newChildNode)
updateChild (path, newChildNode)
isEmpty ()
numChildren ()
val (exportFormat)
hash ()
getPredecessorChildName (childName, childNode, index)
getFirstChildName (indexDefinition)
getFirstChild (indexDefinition)
getLastChildName (indexDefinition)
getLastChild (indexDefinition)
forEachChild (index, action)
getIterator (indexDefinition)
getIteratorFrom (startPost, indexDefinition)
getReverseIterator (indexDefinition)
getReverseIteratorFrom (endPost, indexDefinition)
compareTo (other)
withIndex (indexDefinition)
isIndexed (index)
equals (other)
resolveIndex_ (indexDefinition)
Static Public Member Functions
static get EMPTY_NODE ()
static get EMPTY_NODE ()
static get EMPTY_NODE ()
Detailed Description
ChildrenNode is a class for storing internal nodes in a DataSnapshot (i.e. nodes with children). It implements Node and stores the list of children in the children property, sorted by child name.
Member Function Documentation
compareTo() [1/3]
ChildrenNode::compareTo (other) [inline]
References isEmpty(), and MAX_NODE.
compareTo() [2/3]
ChildrenNode::compareTo (other) [inline]
References isEmpty(), and MAX_NODE.
compareTo() [3/3]
ChildrenNode::compareTo (other) [inline]
References isEmpty(), and MAX_NODE.
constructor() [1/3]
ChildrenNode::constructor (children_, priorityNode_, indexMap_) [inline]
Parameters
children_ - List of children of this node..
priorityNode_ - The priority of this node (as a snapshot node).
Note: The only reason we allow null priority is for EMPTY_NODE, since we can't use EMPTY_NODE as the priority of EMPTY_NODE. We might want to consider making EMPTY_NODE its own class instead of an empty ChildrenNode.
References util, and validatePriorityNode.
constructor() [2/3]
ChildrenNode::constructor (children_, priorityNode_, indexMap_) [inline]
Parameters
children_ - List of children of this node..
priorityNode_ - The priority of this node (as a snapshot node).
Note: The only reason we allow null priority is for EMPTY_NODE, since we can't use EMPTY_NODE as the priority of EMPTY_NODE. We might want to consider making EMPTY_NODE its own class instead of an empty ChildrenNode.
References assert, and validatePriorityNode.
constructor() [3/3]
ChildrenNode::constructor (children_, priorityNode_, indexMap_) [inline]
Parameters
children_ - List of children of this node..
priorityNode_ - The priority of this node (as a snapshot node).
Note: The only reason we allow null priority is for EMPTY_NODE, since we can't use EMPTY_NODE as the priority of EMPTY_NODE. We might want to consider making EMPTY_NODE its own class instead of an empty ChildrenNode.
References assert, and validatePriorityNode.
EMPTY_NODE() [1/3]
static get ChildrenNode::EMPTY_NODE () [inline], [static]
References IndexMap::Default(), EMPTY_NODE(), and NAME_COMPARATOR().
EMPTY_NODE() [2/3]
static get ChildrenNode::EMPTY_NODE () [inline], [static]
References IndexMap::Default(), EMPTY_NODE(), and NAME_COMPARATOR().
EMPTY_NODE() [3/3]
static get ChildrenNode::EMPTY_NODE () [inline], [static]
References IndexMap::Default(), EMPTY_NODE(), and NAME_COMPARATOR().
equals() [1/3]
ChildrenNode::equals (other) [inline]
References equals, getIterator(), getPriority(), and PRIORITY_INDEX.
equals() [2/3]
ChildrenNode::equals (other) [inline]
References equals, getIterator(), getPriority(), and PRIORITY_INDEX.
equals() [3/3]
ChildrenNode::equals (other) [inline]
References equals, getIterator(), getPriority(), and PRIORITY_INDEX.
forEachChild() [1/3]
ChildrenNode::forEachChild (index, action) [inline]
References index, and resolveIndex_().
forEachChild() [2/3]
ChildrenNode::forEachChild (index, action) [inline]
References index, and resolveIndex_().
forEachChild() [3/3]
ChildrenNode::forEachChild (index, action) [inline]
References index, and resolveIndex_().
getChild() [1/3]
ChildrenNode::getChild (path) [inline]
@inheritDoc
References front, getImmediateChild(), path, pathGetFront(), and pathPopFront().
getChild() [2/3]
ChildrenNode::getChild (path) [inline]
@inheritDoc
References front, getImmediateChild(), path, pathGetFront(), and pathPopFront().
getChild() [3/3]
ChildrenNode::getChild (path) [inline]
@inheritDoc
References front, getImmediateChild(), path, pathGetFront(), and pathPopFront().
getFirstChild() [1/3]
ChildrenNode::getFirstChild (indexDefinition) [inline]
References getFirstChildName().
getFirstChild() [2/3]
ChildrenNode::getFirstChild (indexDefinition) [inline]
References getFirstChildName().
getFirstChild() [3/3]
ChildrenNode::getFirstChild (indexDefinition) [inline]
References getFirstChildName().
getFirstChildName() [1/3]
ChildrenNode::getFirstChildName (indexDefinition) [inline]
References resolveIndex_().
getFirstChildName() [2/3]
ChildrenNode::getFirstChildName (indexDefinition) [inline]
References resolveIndex_().
getFirstChildName() [3/3]
ChildrenNode::getFirstChildName (indexDefinition) [inline]
References resolveIndex_().
getImmediateChild() [1/3]
ChildrenNode::getImmediateChild (childName) [inline]
@inheritDoc
References EMPTY_NODE(), and getPriority().
getImmediateChild() [2/3]
ChildrenNode::getImmediateChild (childName) [inline]
@inheritDoc
References EMPTY_NODE(), and getPriority().
getImmediateChild() [3/3]
ChildrenNode::getImmediateChild (childName) [inline]
@inheritDoc
References EMPTY_NODE(), and getPriority().
getIterator() [1/3]
ChildrenNode::getIterator (indexDefinition) [inline]
References getIteratorFrom().
getIterator() [2/3]
ChildrenNode::getIterator (indexDefinition) [inline]
References getIteratorFrom().
getIterator() [3/3]
ChildrenNode::getIterator (indexDefinition) [inline]
References getIteratorFrom().
getIteratorFrom() [1/3]
ChildrenNode::getIteratorFrom (startPost, indexDefinition) [inline]
References iterator, next(), resolveIndex_(), and NamedNode::Wrap().
getIteratorFrom() [2/3]
ChildrenNode::getIteratorFrom (startPost, indexDefinition) [inline]
References iterator, next(), resolveIndex_(), and NamedNode::Wrap().
getIteratorFrom() [3/3]
ChildrenNode::getIteratorFrom (startPost, indexDefinition) [inline]
References iterator, next(), resolveIndex_(), and NamedNode::Wrap().
getLastChild() [1/3]
ChildrenNode::getLastChild (indexDefinition) [inline]
References getLastChildName().
getLastChild() [2/3]
ChildrenNode::getLastChild (indexDefinition) [inline]
References getLastChildName().
getLastChild() [3/3]
ChildrenNode::getLastChild (indexDefinition) [inline]
References getLastChildName().
getLastChildName() [1/3]
ChildrenNode::getLastChildName (indexDefinition) [inline]
Given an index, return the key name of the largest value we have, according to that index
References resolveIndex_().
getLastChildName() [2/3]
ChildrenNode::getLastChildName (indexDefinition) [inline]
Given an index, return the key name of the largest value we have, according to that index
References resolveIndex_().
getLastChildName() [3/3]
ChildrenNode::getLastChildName (indexDefinition) [inline]
Given an index, return the key name of the largest value we have, according to that index
References resolveIndex_().
getPredecessorChildName() [1/3]
ChildrenNode::getPredecessorChildName (childName, childNode, index) [inline]
@inheritDoc
References index, and resolveIndex_().
getPredecessorChildName() [2/3]
ChildrenNode::getPredecessorChildName (childName, childNode, index) [inline]
@inheritDoc
References index, and resolveIndex_().
getPredecessorChildName() [3/3]
ChildrenNode::getPredecessorChildName (childName, childNode, index) [inline]
@inheritDoc
References index, and resolveIndex_().
getPriority() [1/3]
ChildrenNode::getPriority () [inline]
@inheritDoc
References EMPTY_NODE().
getPriority() [2/3]
ChildrenNode::getPriority () [inline]
@inheritDoc
References EMPTY_NODE().
getPriority() [3/3]
ChildrenNode::getPriority () [inline]
@inheritDoc
References EMPTY_NODE().
getReverseIterator() [1/3]
ChildrenNode::getReverseIterator (indexDefinition) [inline]
References getReverseIteratorFrom().
getReverseIterator() [2/3]
ChildrenNode::getReverseIterator (indexDefinition) [inline]
References getReverseIteratorFrom().
getReverseIterator() [3/3]
ChildrenNode::getReverseIterator (indexDefinition) [inline]
References getReverseIteratorFrom().
getReverseIteratorFrom() [1/3]
ChildrenNode::getReverseIteratorFrom (endPost, indexDefinition) [inline]
References iterator, next(), resolveIndex_(), and NamedNode::Wrap().
getReverseIteratorFrom() [2/3]
ChildrenNode::getReverseIteratorFrom (endPost, indexDefinition) [inline]
References iterator, next(), resolveIndex_(), and NamedNode::Wrap().
getReverseIteratorFrom() [3/3]
ChildrenNode::getReverseIteratorFrom (endPost, indexDefinition) [inline]
References iterator, next(), resolveIndex_(), and NamedNode::Wrap().
hasChild() [1/3]
ChildrenNode::hasChild (childName) [inline]
@inheritDoc
hasChild() [2/3]
ChildrenNode::hasChild (childName) [inline]
@inheritDoc
hasChild() [3/3]
ChildrenNode::hasChild (childName) [inline]
@inheritDoc
hash() [1/3]
ChildrenNode::hash () [inline]
@inheritDoc
References forEachChild(), getPriority(), isEmpty(), PRIORITY_INDEX, priorityHashText, sha1, toHash, and val().
hash() [2/3]
ChildrenNode::hash () [inline]
@inheritDoc
References forEachChild(), getPriority(), isEmpty(), PRIORITY_INDEX, priorityHashText, sha1, toHash, and val().
hash() [3/3]
ChildrenNode::hash () [inline]
@inheritDoc
References forEachChild(), getPriority(), isEmpty(), PRIORITY_INDEX, priorityHashText, sha1, toHash, and val().
isEmpty() [1/3]
ChildrenNode::isEmpty () [inline]
@inheritDoc Here is the caller graph for this function:
isEmpty() [2/3]
ChildrenNode::isEmpty () [inline]
@inheritDoc
isEmpty() [3/3]
ChildrenNode::isEmpty () [inline]
@inheritDoc
isIndexed() [1/3]
ChildrenNode::isIndexed (index) [inline]
References index, and KEY_INDEX.
isIndexed() [2/3]
ChildrenNode::isIndexed (index) [inline]
References index, and KEY_INDEX.
isIndexed() [3/3]
ChildrenNode::isIndexed (index) [inline]
References index, and KEY_INDEX.
isLeafNode() [1/3]
ChildrenNode::isLeafNode () [inline]
@inheritDoc
isLeafNode() [2/3]
ChildrenNode::isLeafNode () [inline]
@inheritDoc
isLeafNode() [3/3]
ChildrenNode::isLeafNode () [inline]
@inheritDoc
numChildren() [1/3]
ChildrenNode::numChildren () [inline]
@inheritDoc
numChildren() [2/3]
ChildrenNode::numChildren () [inline]
@inheritDoc
numChildren() [3/3]
ChildrenNode::numChildren () [inline]
@inheritDoc
resolveIndex_() [1/3]
ChildrenNode::resolveIndex_ (indexDefinition) [inline]
Returns a SortedMap ordered by index, or null if the default (by-key) ordering can be used instead.
References KEY_INDEX.
resolveIndex_() [2/3]
ChildrenNode::resolveIndex_ (indexDefinition) [inline]
Returns a SortedMap ordered by index, or null if the default (by-key) ordering can be used instead.
References KEY_INDEX.
resolveIndex_() [3/3]
ChildrenNode::resolveIndex_ (indexDefinition) [inline]
Returns a SortedMap ordered by index, or null if the default (by-key) ordering can be used instead.
References KEY_INDEX.
updateChild() [1/3]
ChildrenNode::updateChild (path, newChildNode) [inline]
@inheritDoc
References front, getImmediateChild(), path, pathGetFront(), pathGetLength(), pathPopFront(), updateImmediateChild(), and util.
updateChild() [2/3]
ChildrenNode::updateChild (path, newChildNode) [inline]
@inheritDoc
References assert, front, getImmediateChild(), path, pathGetFront(), pathGetLength(), pathPopFront(), and updateImmediateChild().
updateChild() [3/3]
ChildrenNode::updateChild (path, newChildNode) [inline]
@inheritDoc
References assert, front, getImmediateChild(), path, pathGetFront(), pathGetLength(), pathPopFront(), and updateImmediateChild().
updateImmediateChild() [1/3]
ChildrenNode::updateImmediateChild (childName, newChildNode) [inline]
@inheritDoc
References EMPTY_NODE(), updatePriority(), and util.
updateImmediateChild() [2/3]
ChildrenNode::updateImmediateChild (childName, newChildNode) [inline]
@inheritDoc
References assert, EMPTY_NODE(), and updatePriority().
updateImmediateChild() [3/3]
ChildrenNode::updateImmediateChild (childName, newChildNode) [inline]
@inheritDoc
References assert, EMPTY_NODE(), and updatePriority().
updatePriority() [1/3]
ChildrenNode::updatePriority (newPriorityNode) [inline]
@inheritDoc Here is the caller graph for this function:
updatePriority() [2/3]
ChildrenNode::updatePriority (newPriorityNode) [inline]
@inheritDoc
updatePriority() [3/3]
ChildrenNode::updatePriority (newPriorityNode) [inline]
@inheritDoc
val() [1/3]
ChildrenNode::val (exportFormat) [inline]
@inheritDoc
References forEachChild(), getPriority(), isEmpty(), obj, and PRIORITY_INDEX.
val() [2/3]
ChildrenNode::val (exportFormat) [inline]
@inheritDoc
References forEachChild(), getPriority(), isEmpty(), obj, and PRIORITY_INDEX.
val() [3/3]
ChildrenNode::val (exportFormat) [inline]
@inheritDoc
References forEachChild(), getPriority(), isEmpty(), obj, and PRIORITY_INDEX.
withIndex() [1/3]
ChildrenNode::withIndex (indexDefinition) [inline]
References KEY_INDEX.
withIndex() [2/3]
ChildrenNode::withIndex (indexDefinition) [inline]
References KEY_INDEX.
withIndex() [3/3]
ChildrenNode::withIndex (indexDefinition) [inline]
References KEY_INDEX.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js