XMLMultiPartUploadHelper Class Reference
Public Member Functions
constructor (bucket, fileName, uploadId, partsMap)
async initiateUpload (headers={})
async uploadPart (partNumber, chunk, validation)
async completeUpload ()
async abortUpload ()
constructor (bucket, fileName, uploadId, partsMap)
async initiateUpload (headers={})
async uploadPart (partNumber, chunk, validation)
async completeUpload ()
async abortUpload ()
Detailed Description
Class representing an implementation of MPU in the XML API. This class is not meant for public usage.
Member Function Documentation
abortUpload() [1/2]
async XMLMultiPartUploadHelper::abortUpload () [inline]
Aborts an multipart upload that is in progress. Once aborted, any parts in the process of being uploaded fail, and future requests using the upload ID fail.
Returns
{Promise<void>}
References $, __classPrivateFieldGet, _XMLMultiPartUploadHelper_handleErrorResponse, _XMLMultiPartUploadHelper_instances, async, async_retry_1, e, method, res, and url.
abortUpload() [2/2]
async XMLMultiPartUploadHelper::abortUpload () [inline]
Aborts an multipart upload that is in progress. Once aborted, any parts in the process of being uploaded fail, and future requests using the upload ID fail.
Returns
{Promise<void>}
References $, __classPrivateFieldGet, _XMLMultiPartUploadHelper_handleErrorResponse, _XMLMultiPartUploadHelper_instances, async, e, method, res, and url.
completeUpload() [1/2]
async XMLMultiPartUploadHelper::completeUpload () [inline]
Sends the final request of the MPU to tell GCS the upload is now complete.
Returns
{Promise<void>}
References $, __classPrivateFieldGet, _XMLMultiPartUploadHelper_handleErrorResponse, _XMLMultiPartUploadHelper_instances, _XMLMultiPartUploadHelper_setGoogApiClientHeaders, a, async, async_retry_1, b, e, headers, Map, method, of, res, and url.
completeUpload() [2/2]
async XMLMultiPartUploadHelper::completeUpload () [inline]
Sends the final request of the MPU to tell GCS the upload is now complete.
Returns
{Promise<void>}
References $, __classPrivateFieldGet, _XMLMultiPartUploadHelper_handleErrorResponse, _XMLMultiPartUploadHelper_instances, _XMLMultiPartUploadHelper_setGoogApiClientHeaders, a, async, b, e, headers, Map, method, of, res, and url.
constructor() [1/2]
XMLMultiPartUploadHelper::constructor (bucket, fileName, uploadId, partsMap) [inline]
References _XMLMultiPartUploadHelper_instances, fast_xml_parser_1, fileName, google_auth_library_1, https, and Map.
constructor() [2/2]
XMLMultiPartUploadHelper::constructor (bucket, fileName, uploadId, partsMap) [inline]
References _XMLMultiPartUploadHelper_instances, fileName, GoogleAuth, https, Map, XMLBuilder, and XMLParser.
initiateUpload() [1/2]
async XMLMultiPartUploadHelper::initiateUpload (headers = {}) [inline]
Initiates a multipart upload (MPU) to the XML API and stores the resultant upload id.
Returns
{Promise<void>}
initiateUpload() [2/2]
async XMLMultiPartUploadHelper::initiateUpload (headers = {}) [inline]
Initiates a multipart upload (MPU) to the XML API and stores the resultant upload id.
Returns
{Promise<void>}
uploadPart() [1/2]
async XMLMultiPartUploadHelper::uploadPart (partNumber, chunk, validation) [inline]
Uploads the provided chunk of data to the XML API using the previously created upload id.
Parameters
{number} partNumber the sequence number of this chunk.
{Buffer} chunk the chunk of data to be uploaded.
{string | false} validation whether or not to include the md5 hash in the headers to cause the server to validate the chunk was not corrupted.
Returns
{Promise<void>}
References $, __classPrivateFieldGet, _XMLMultiPartUploadHelper_handleErrorResponse, _XMLMultiPartUploadHelper_instances, _XMLMultiPartUploadHelper_setGoogApiClientHeaders, async, async_retry_1, chunk(), crypto_1, e, hash(), headers, method, res, url, and validation().
uploadPart() [2/2]
async XMLMultiPartUploadHelper::uploadPart (partNumber, chunk, validation) [inline]
Uploads the provided chunk of data to the XML API using the previously created upload id.
Parameters
{number} partNumber the sequence number of this chunk.
{Buffer} chunk the chunk of data to be uploaded.
{string | false} validation whether or not to include the md5 hash in the headers to cause the server to validate the chunk was not corrupted.
Returns
{Promise<void>}
References $, __classPrivateFieldGet, _XMLMultiPartUploadHelper_handleErrorResponse, _XMLMultiPartUploadHelper_instances, _XMLMultiPartUploadHelper_setGoogApiClientHeaders, async, chunk(), e, hash(), headers, method, res, url, and validation().
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/transfer-manager.js
backend/node_modules/@google-cloud/storage/build/esm/src/transfer-manager.js