JWTAccess Class Reference
Public Member Functions
constructor (email, key, keyId, eagerRefreshThresholdMillis)
getCachedKey (url, scopes)
getRequestHeaders (url, additionalClaims, scopes)
fromJSON (json)
fromStream (inputStream, callback)
fromStreamAsync (inputStream)
Static Public Member Functions
static getExpirationTime (iat)
Member Function Documentation
constructor()
JWTAccess::constructor (email, key, keyId, eagerRefreshThresholdMillis) [inline]
JWTAccess service account credentials.
Create a new access token by using the credential to create a new JWT token that's recognized as the access token.
Parameters
email the service account email address.
key the private key that will be used to sign the token.
keyId the ID of the private key used to sign the token.
References util_1.
fromJSON()
JWTAccess::fromJSON (json) [inline]
Create a JWTAccess credentials instance using the given input options.
Parameters
json The input object.
fromStream()
JWTAccess::fromStream (inputStream, callback) [inline]
References callback, and fromStreamAsync().
fromStreamAsync()
JWTAccess::fromStreamAsync (inputStream) [inline]
References chunk(), data, fromJSON, JSON, Promise, reject(), resolve, and s.
getCachedKey()
JWTAccess::getCachedKey (url, scopes) [inline]
Ensures that we're caching a key appropriately, giving precedence to scopes vs. url
Parameters
url The URI being authorized.
scopes The scope or scopes being authorized
Returns
A string that returns the cached key.
References $, Array, and url.
getExpirationTime()
static JWTAccess::getExpirationTime (iat) [inline], [static]
Returns an expiration time for the JWT token.
Parameters
iat The issued at time for the JWT.
Returns
An expiration time for the JWT.
References exp.
getRequestHeaders()
JWTAccess::getRequestHeaders (url, additionalClaims, scopes) [inline]
Get a non-expired access token, after refreshing if necessary.
Parameters
url The URI being authorized.
additionalClaims An object with a set of additional claims to include in the payload.
Returns
An object that includes the authorization header.
References $, Array, DEFAULT_HEADER, exp, getCachedKey(), getExpirationTime(), headers, is, jws, not, now, property, sub, and url.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/jwtaccess.js