DeflateHandler Class Reference
Public Member Functions
constructor (maxRecvMessageLength)
compressMessage (message)
decompressMessage (message)
async writeMessage (message, compress)
async readMessage (data)
Member Function Documentation
compressMessage()
DeflateHandler::compressMessage (message) [inline]
References message, Promise, reject(), resolve, and zlib.
constructor()
DeflateHandler::constructor (maxRecvMessageLength) [inline]
decompressMessage()
DeflateHandler::decompressMessage (message) [inline]
References $, a, chunk(), constants_1, message, Promise, reject(), resolve, size, and zlib.
readMessage()
async CompressionHandler::readMessage (data) [inline], [inherited]
Parameters
data Framed message, possibly compressed
Returns
Uncompressed message
References data.
writeMessage()
async CompressionHandler::writeMessage (message, compress) [inline], [inherited]
Parameters
message Raw uncompressed message bytes
compress Indicates whether the message should be compressed
Returns
Framed message, compressed if applicable
References compress(), and message.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/compression-filter.js