MetricsAPI Class Reference
Public Member Functions
constructor ()
setGlobalMeterProvider (provider)
getMeterProvider ()
getMeter (name, version, options)
disable ()
constructor ()
setGlobalMeterProvider (provider)
getMeterProvider ()
getMeter (name, version, options)
disable ()
Static Public Member Functions
static getInstance ()
static getInstance ()
Detailed Description
Singleton object which represents the entry point to the OpenTelemetry Metrics API
Member Function Documentation
constructor() [1/2]
MetricsAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
constructor() [2/2]
MetricsAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
disable() [1/2]
MetricsAPI::disable () [inline]
Remove the global meter provider
References API_NAME, DiagAPI::instance(), and unregisterGlobal.
disable() [2/2]
MetricsAPI::disable () [inline]
Remove the global meter provider
References API_NAME, diag_1, and global_utils_1.
getInstance() [1/2]
static MetricsAPI::getInstance () [inline], [static]
Get the singleton instance of the Metrics API
References MetricsAPI.
getInstance() [2/2]
static MetricsAPI::getInstance () [inline], [static]
Get the singleton instance of the Metrics API
References MetricsAPI.
getMeter() [1/2]
MetricsAPI::getMeter (name, version, options) [inline]
Returns a meter from the global meter provider.
References getMeterProvider(), name, and version.
getMeter() [2/2]
MetricsAPI::getMeter (name, version, options) [inline]
Returns a meter from the global meter provider.
References getMeterProvider(), name, and version.
getMeterProvider() [1/2]
MetricsAPI::getMeterProvider () [inline]
Returns the global meter provider.
References API_NAME, getGlobal, and NOOP_METER_PROVIDER.
getMeterProvider() [2/2]
MetricsAPI::getMeterProvider () [inline]
Returns the global meter provider.
References API_NAME, global_utils_1, and NoopMeterProvider_1.
setGlobalMeterProvider() [1/2]
MetricsAPI::setGlobalMeterProvider (provider) [inline]
Set the current global meter provider. Returns true if the meter provider was successfully registered, else false.
References API_NAME, DiagAPI::instance(), and registerGlobal.
setGlobalMeterProvider() [2/2]
MetricsAPI::setGlobalMeterProvider (provider) [inline]
Set the current global meter provider. Returns true if the meter provider was successfully registered, else false.
References API_NAME, diag_1, and global_utils_1.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/api/metrics.js
backend/node_modules/@opentelemetry/api/build/src/api/metrics.js