DocumentReader Class Reference
Public Member Functions
constructor (firestore, allDocuments, fieldMask, transactionOrReadTime)
async get (requestTag)
async _get (requestTag)
async fetchDocuments (requestTag)
Detailed Description
A wrapper around BatchGetDocumentsRequest that retries request upon stream failure and returns ordered results.
Member Function Documentation
_get()
async DocumentReader::_get (requestTag) [inline]
Invokes the BatchGetDocuments RPC and returns the results with transaction metadata.
Parameters
requestTag A unique client-assigned identifier for this request.
References document_1, fetchDocuments(), not, of, requestTag, result, and undefined.
constructor()
DocumentReader::constructor (firestore, allDocuments, fieldMask, transactionOrReadTime) [inline]
Creates a new DocumentReader that fetches the provided documents (via get()).
Parameters
firestore The Firestore instance to use.
allDocuments The documents to get.
fieldMask An optional field mask to apply to this read
transactionOrReadTime An optional transaction ID to use for this read or options for beginning a new transaction with this read
References firestore, Map, of, and Set.
fetchDocuments()
async DocumentReader::fetchDocuments (requestTag) [inline]
References _a, Array, database, error, fetchDocuments(), firestore, logger_1, of, path, request, requestTag, response, stream, timestamp_1, undefined, and util_1.
get()
async DocumentReader::get (requestTag) [inline]
Invokes the BatchGetDocuments RPC and returns the results as an array of documents.
Parameters
requestTag A unique client-assigned identifier for this request.
References _get(), requestTag, and result.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/document-reader.js