FirebaseNamespace Class Reference
Public Member Functions
constructor (appStore)
get auth ()
get database ()
get messaging ()
get storage ()
get firestore ()
get machineLearning ()
get installations ()
get instanceId ()
get projectManagement ()
get securityRules ()
get remoteConfig ()
get appCheck ()
initializeApp (options, appName)
app (appName)
get apps ()
ensureApp (app)
Detailed Description
Global Firebase context object.
Member Function Documentation
app()
FirebaseNamespace::app (appName) [inline]
Returns the FirebaseApp instance with the provided name (or the default FirebaseApp instance if no name is provided).
Parameters
appName - Optional name of the FirebaseApp instance to return.
Returns
The FirebaseApp instance which has the provided name.
References INTERNAL.
appCheck()
get FirebaseNamespace::appCheck () [inline]
Gets the AppCheck service namespace. The returned namespace can be used to get the AppCheck service for the default app or an explicitly specified app.
References app, AppCheck, appCheck(), ensureApp(), fn, and require().
apps()
get FirebaseNamespace::apps () [inline]
References INTERNAL.
auth()
get FirebaseNamespace::auth () [inline]
Gets the Auth service namespace. The returned namespace can be used to get the Auth service for the default app or an explicitly specified app.
References app, Auth, auth(), ensureApp(), fn, and require().
constructor()
FirebaseNamespace::constructor (appStore) [inline]
References credential, firebaseCredential, FirebaseNamespaceInternals, index_1, INTERNAL, lifecycle_1, Promise, and SDK_VERSION.
database()
get FirebaseNamespace::database () [inline]
Gets the Database service namespace. The returned namespace can be used to get the Database service for the default app or an explicitly specified app.
References app, ensureApp(), fn, and require().
ensureApp()
FirebaseNamespace::ensureApp (app) [inline]
References app.
firestore()
get FirebaseNamespace::firestore () [inline]
Gets the Firestore service namespace. The returned namespace can be used to get the Firestore service for the default app or an explicitly specified app.
References app, ensureApp(), firestore(), fn, and require().
initializeApp()
FirebaseNamespace::initializeApp (options, appName) [inline]
Initializes the FirebaseApp instance.
Parameters
options - Optional options for the FirebaseApp instance. If none present will try to initialize from the FIREBASE_CONFIG environment variable. If the environment variable contains a string that starts with '{' it will be parsed as JSON, otherwise it will be assumed to be pointing to a file.
appName - Optional name of the FirebaseApp instance.
Returns
A new FirebaseApp instance.
References INTERNAL.
installations()
get FirebaseNamespace::installations () [inline]
Gets the Installations service namespace. The returned namespace can be used to get the Installations service for the default app or an explicitly specified app.
References app, ensureApp(), fn, Installations, installations(), and require().
instanceId()
get FirebaseNamespace::instanceId () [inline]
Gets the InstanceId service namespace. The returned namespace can be used to get the Instance service for the default app or an explicitly specified app.
References app, ensureApp(), fn, InstanceId, instanceId(), and require().
machineLearning()
get FirebaseNamespace::machineLearning () [inline]
Gets the MachineLearning service namespace. The returned namespace can be used to get the MachineLearning service for the default app or an explicityly specified app.
References app, ensureApp(), fn, MachineLearning, machineLearning(), and require().
messaging()
get FirebaseNamespace::messaging () [inline]
Gets the Messaging service namespace. The returned namespace can be used to get the Messaging service for the default app or an explicitly specified app.
References app, ensureApp(), fn, Messaging, messaging(), and require().
projectManagement()
get FirebaseNamespace::projectManagement () [inline]
Gets the ProjectManagement service namespace. The returned namespace can be used to get the ProjectManagement service for the default app or an explicitly specified app.
References app, ensureApp(), fn, ProjectManagement, projectManagement(), and require().
remoteConfig()
get FirebaseNamespace::remoteConfig () [inline]
Gets the RemoteConfig service namespace. The returned namespace can be used to get the RemoteConfig service for the default app or an explicitly specified app.
References app, ensureApp(), fn, RemoteConfig, remoteConfig(), and require().
securityRules()
get FirebaseNamespace::securityRules () [inline]
Gets the SecurityRules service namespace. The returned namespace can be used to get the SecurityRules service for the default app or an explicitly specified app.
References app, ensureApp(), fn, require(), SecurityRules, and securityRules().
storage()
get FirebaseNamespace::storage () [inline]
Gets the Storage service namespace. The returned namespace can be used to get the Storage service for the default app or an explicitly specified app.
References app, ensureApp(), fn, require(), Storage, and storage().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/app/firebase-namespace.js