RepoInfo Class Reference
Public Member Functions
constructor (host, secure, namespace, webSocketOnly, nodeAdmin=false, persistenceKey='', includeNamespaceInQueryParams=false, isUsingEmulator=false)
isCacheableHost ()
isCustomHost ()
get host ()
set host (newHost)
toString ()
toURLString ()
constructor (host, secure, namespace, webSocketOnly, nodeAdmin=false, persistenceKey='', includeNamespaceInQueryParams=false, isUsingEmulator=false)
isCacheableHost ()
isCustomHost ()
get host ()
set host (newHost)
toString ()
toURLString ()
constructor (host, secure, namespace, webSocketOnly, nodeAdmin=false, persistenceKey='', includeNamespaceInQueryParams=false, isUsingEmulator=false)
isCacheableHost ()
isCustomHost ()
get host ()
set host (newHost)
toString ()
toURLString ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. A class that holds metadata about a Repo object
Member Function Documentation
constructor() [1/3]
RepoInfo::constructor (host, secure, namespace, webSocketOnly, nodeAdmin = false, persistenceKey = '', includeNamespaceInQueryParams = false, isUsingEmulator = false) [inline]
Parameters
host - Hostname portion of the url for the repo
secure - Whether or not this repo is accessed over ssl
namespace - The namespace represented by the repo
webSocketOnly - Whether to prefer websockets over all other transports (used by Nest).
nodeAdmin - Whether this instance uses Admin SDK credentials
persistenceKey - Override the default session persistence storage key
References host(), and PersistentStorage.
constructor() [2/3]
RepoInfo::constructor (host, secure, namespace, webSocketOnly, nodeAdmin = false, persistenceKey = '', includeNamespaceInQueryParams = false, isUsingEmulator = false) [inline]
Parameters
host - Hostname portion of the url for the repo
secure - Whether or not this repo is accessed over ssl
namespace - The namespace represented by the repo
webSocketOnly - Whether to prefer websockets over all other transports (used by Nest).
nodeAdmin - Whether this instance uses Admin SDK credentials
persistenceKey - Override the default session persistence storage key
References host(), and PersistentStorage.
constructor() [3/3]
RepoInfo::constructor (host, secure, namespace, webSocketOnly, nodeAdmin = false, persistenceKey = '', includeNamespaceInQueryParams = false, isUsingEmulator = false) [inline]
Parameters
host - Hostname portion of the url for the repo
secure - Whether or not this repo is accessed over ssl
namespace - The namespace represented by the repo
webSocketOnly - Whether to prefer websockets over all other transports (used by Nest).
nodeAdmin - Whether this instance uses Admin SDK credentials
persistenceKey - Override the default session persistence storage key
References host(), and PersistentStorage.
host() [1/6]
get RepoInfo::host () [inline]
host() [2/6]
get RepoInfo::host () [inline]
host() [3/6]
get RepoInfo::host () [inline]
host() [4/6]
set RepoInfo::host (newHost) [inline]
References isCacheableHost(), and PersistentStorage.
host() [5/6]
set RepoInfo::host (newHost) [inline]
References isCacheableHost(), and PersistentStorage.
host() [6/6]
set RepoInfo::host (newHost) [inline]
References isCacheableHost(), and PersistentStorage.
isCacheableHost() [1/3]
RepoInfo::isCacheableHost () [inline]
isCacheableHost() [2/3]
RepoInfo::isCacheableHost () [inline]
isCacheableHost() [3/3]
RepoInfo::isCacheableHost () [inline]
isCustomHost() [1/3]
RepoInfo::isCustomHost () [inline]
isCustomHost() [2/3]
RepoInfo::isCustomHost () [inline]
isCustomHost() [3/3]
RepoInfo::isCustomHost () [inline]
toString() [1/3]
RepoInfo::toString () [inline]
References str(), and toURLString().
toString() [2/3]
RepoInfo::toString () [inline]
References str(), and toURLString().
toString() [3/3]
RepoInfo::toString () [inline]
References str(), and toURLString().
toURLString() [1/3]
RepoInfo::toURLString () [inline]
References $, host(), and query.
toURLString() [2/3]
RepoInfo::toURLString () [inline]
References $, host(), and query.
toURLString() [3/3]
RepoInfo::toURLString () [inline]
References $, host(), and query.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js