VirtualAction Class Reference
Public Member Functions
constructor (scheduler, work, index=(scheduler.index+=1))
schedule (state, delay=0)
requestAsyncId (scheduler, id, delay=0)
recycleAsyncId (scheduler, id, delay=0)
_execute (state, delay)
constructor (scheduler, work)
constructor (initialTeardown)
execute (state, delay)
unsubscribe ()
add (teardown)
_hasParent (parent)
_addParent (parent)
_removeParent (parent)
remove (teardown)
Static Public Member Functions
static sortActions (a, b)
Member Function Documentation
_addParent()
Subscription::_addParent (parent) [inline], [inherited]
References Array, and parent.
_execute()
VirtualAction::_execute (state, delay) [inline]
References delay, and state().
_hasParent()
Subscription::_hasParent (parent) [inline], [inherited]
References Array, and parent.
_removeParent()
Subscription::_removeParent (parent) [inline], [inherited]
References Array, arrRemove, and parent.
add()
Subscription::add (teardown) [inline], [inherited]
References _a, execFinalizer(), and push.
constructor() [1/3]
AsyncAction::constructor (scheduler, work) [inline], [inherited]
References pending.
constructor() [2/3]
Subscription::constructor (initialTeardown) [inline], [inherited]
constructor() [3/3]
VirtualAction::constructor (scheduler, work, index = (scheduler.index += 1)) [inline]
References index.
execute()
AsyncAction::execute (state, delay) [inline], [inherited]
References AsyncAction::_execute(), delay, error, pending, AsyncAction::recycleAsyncId(), and state().
recycleAsyncId()
VirtualAction::recycleAsyncId (scheduler, id, delay = 0) [inline]
References undefined.
remove()
Subscription::remove (teardown) [inline], [inherited]
References arrRemove.
requestAsyncId()
VirtualAction::requestAsyncId (scheduler, id, delay = 0) [inline]
References delay, and sortActions().
schedule()
VirtualAction::schedule (state, delay = 0) [inline]
References add, delay, state(), and VirtualAction.
sortActions()
static VirtualAction::sortActions (a, b) [inline], [static]
References a, and b.
unsubscribe()
AsyncAction::unsubscribe () [inline], [inherited]
References arrRemove, delay, pending, AsyncAction::recycleAsyncId(), and state().
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/scheduler/VirtualTimeScheduler.js