TransportManager Class Reference
Public Member Functions
constructor (repoInfo)
initTransports_ (repoInfo)
initialTransport ()
upgradeTransport ()
constructor (repoInfo)
initTransports_ (repoInfo)
initialTransport ()
upgradeTransport ()
constructor (repoInfo)
initTransports_ (repoInfo)
initialTransport ()
upgradeTransport ()
Static Public Member Functions
static get ALL_TRANSPORTS ()
static get IS_TRANSPORT_INITIALIZED ()
static get ALL_TRANSPORTS ()
static get IS_TRANSPORT_INITIALIZED ()
static get ALL_TRANSPORTS ()
static get IS_TRANSPORT_INITIALIZED ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Currently simplistic, this class manages what transport a Connection should use at various stages of its lifecycle.
It starts with longpolling in a browser, and httppolling on node. It then upgrades to websockets if they are available.
Member Function Documentation
ALL_TRANSPORTS() [1/3]
static get TransportManager::ALL_TRANSPORTS () [inline], [static]
References BrowserPollConnection.
ALL_TRANSPORTS() [2/3]
static get TransportManager::ALL_TRANSPORTS () [inline], [static]
References BrowserPollConnection.
ALL_TRANSPORTS() [3/3]
static get TransportManager::ALL_TRANSPORTS () [inline], [static]
References BrowserPollConnection.
constructor() [1/3]
TransportManager::constructor (repoInfo) [inline]
Parameters
repoInfo - Metadata around the namespace we're connecting to
References initTransports_().
constructor() [2/3]
TransportManager::constructor (repoInfo) [inline]
Parameters
repoInfo - Metadata around the namespace we're connecting to
References initTransports_().
constructor() [3/3]
TransportManager::constructor (repoInfo) [inline]
Parameters
repoInfo - Metadata around the namespace we're connecting to
References initTransports_().
initialTransport() [1/3]
TransportManager::initialTransport () [inline]
Returns
The constructor for the initial transport to use
initialTransport() [2/3]
TransportManager::initialTransport () [inline]
Returns
The constructor for the initial transport to use
initialTransport() [3/3]
TransportManager::initialTransport () [inline]
Returns
The constructor for the initial transport to use
initTransports_() [1/3]
TransportManager::initTransports_ (repoInfo) [inline]
References ALL_TRANSPORTS(), of, WebSocketConnection::previouslyFailed(), and warn.
initTransports_() [2/3]
TransportManager::initTransports_ (repoInfo) [inline]
References ALL_TRANSPORTS(), of, WebSocketConnection::previouslyFailed(), and warn.
initTransports_() [3/3]
TransportManager::initTransports_ (repoInfo) [inline]
References ALL_TRANSPORTS(), of, WebSocketConnection::previouslyFailed(), and warn.
IS_TRANSPORT_INITIALIZED() [1/3]
static get TransportManager::IS_TRANSPORT_INITIALIZED () [inline], [static]
Returns whether transport has been selected to ensure WebSocketConnection or BrowserPollConnection are not called after TransportManager has already set up transports_
References globalTransportInitialized_.
IS_TRANSPORT_INITIALIZED() [2/3]
static get TransportManager::IS_TRANSPORT_INITIALIZED () [inline], [static]
Returns whether transport has been selected to ensure WebSocketConnection or BrowserPollConnection are not called after TransportManager has already set up transports_
References globalTransportInitialized_.
IS_TRANSPORT_INITIALIZED() [3/3]
static get TransportManager::IS_TRANSPORT_INITIALIZED () [inline], [static]
Returns whether transport has been selected to ensure WebSocketConnection or BrowserPollConnection are not called after TransportManager has already set up transports_
References globalTransportInitialized_.
upgradeTransport() [1/3]
TransportManager::upgradeTransport () [inline]
Returns
The constructor for the next transport, or null
upgradeTransport() [2/3]
TransportManager::upgradeTransport () [inline]
Returns
The constructor for the next transport, or null
upgradeTransport() [3/3]
TransportManager::upgradeTransport () [inline]
Returns
The constructor for the next transport, or null
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js