Watch Class Reference
Public Member Functions
shutdown ()
Private Member Functions
constructor (firestore, _converter=(0, types_1.defaultConverter)())
onSnapshot (onNext, onError)
currentSize ()
extractCurrentChanges (readTime)
resetDocs ()
closeStream (err)
maybeReopenStream (err)
resetIdleTimeout ()
resetStream ()
initStream ()
onData (proto)
affectsTarget (targetIds, currentId)
pushSnapshot (readTime, nextResumeToken)
deleteDoc (name)
addDoc (newDocument)
modifyDoc (newDocument)
computeSnapshot (readTime)
isPermanentWatchError (error)
isResourceExhaustedError (error)
Detailed Description
Watch provides listen functionality and exposes the 'onSnapshot' observer. It can be used with a valid Firestore Listen target.
Member Function Documentation
addDoc()
Watch::addDoc (newDocument) [inline], [private]
Applies a document add to the document tree and the document map. Returns the corresponding DocumentChange event.
References assert, ChangeType, document_change_1, and name.
affectsTarget()
Watch::affectsTarget (targetIds, currentId) [inline], [private]
Checks if the current target id is included in the list of target ids. If no targetIds are provided, returns true.
References of, and undefined.
closeStream()
Watch::closeStream (err) [inline], [private]
Closes the stream and calls onError() if the stream is still active.
References logger_1, requestTag, and shutdown().
computeSnapshot()
Watch::computeSnapshot (readTime) [inline], [private]
Applies the mutations in changeMap to both the document tree and the document lookup map. Modified docMap in-place and returns the updated state.
References addDoc(), assert, deleteDoc(), extractCurrentChanges(), modifyDoc(), and name.
constructor()
Watch::constructor (firestore, _converter = (0, types_1.defaultConverter)()) [inline], [private]
Indicates whether we are interested in data from the stream. Set to false in the 'unsubscribe()' callback.
The current stream to the backend.
The server assigns and updates the resume token.
A map of document names to QueryDocumentSnapshots for the last sent snapshot.
The accumulated map of document changes (keyed by document name) for the current snapshot.
The current state of the query results. *
We need this to track whether we've pushed an initial set of changes, since we should push those even when there are no changes, if there aren't docs.
References backoff_1, EMPTY_FUNCTION, firestore, Map, requestTag, undefined, and util_1.
currentSize()
Watch::currentSize () [inline], [private]
Returns the current count of all documents, including the changes from the current changeMap.
References extractCurrentChanges(), and timestamp_1.
deleteDoc()
Watch::deleteDoc (name) [inline], [private]
Applies a document delete to the document tree and the document map. Returns the corresponding DocumentChange event.
References assert, ChangeType, document_change_1, and name.
extractCurrentChanges()
Watch::extractCurrentChanges (readTime) [inline], [private]
Splits up document changes into removals, additions, and updates.
References name, REMOVED, and value.
initStream()
Watch::initStream () [inline], [private]
Initializes a new stream to the backend with backoff.
References async, closeStream(), firestore, google_gax_1, logger_1, maybeReopenStream(), on, onData(), proto, request, requestTag, and resetIdleTimeout().
isPermanentWatchError()
Watch::isPermanentWatchError (error) [inline], [private]
Determines whether a watch error is considered permanent and should not be retried. Errors that don't provide a GRPC error code are always considered transient in this context.
References error, google_gax_1, logger_1, requestTag, and undefined.
isResourceExhaustedError()
Watch::isResourceExhaustedError (error) [inline], [private]
Determines whether we need to initiate a longer backoff due to system overload.
References error, and google_gax_1.
maybeReopenStream()
Watch::maybeReopenStream (err) [inline], [private]
Re-opens the stream unless the specified error is considered permanent. Clears the change map.
References closeStream(), initStream(), isPermanentWatchError(), isResourceExhaustedError(), logger_1, and requestTag.
modifyDoc()
Watch::modifyDoc (newDocument) [inline], [private]
Applies a document modification to the document tree and the document map. Returns the DocumentChange event for successful modifications.
References addDoc(), assert, ChangeType, deleteDoc(), document_change_1, and name.
onData()
Watch::onData (proto) [inline], [private]
Handles 'data' events and closes the stream if the response type is invalid.
References closeStream(), document_1, firestore, google_gax_1, i, JSON, logger_1, message, name, path_1, proto, pushSnapshot(), REMOVED, requestTag, resetDocs(), resetStream(), timestamp_1, and WATCH_TARGET_ID.
onSnapshot()
Watch::onSnapshot (onNext, onError) [inline], [private]
Starts a watch and attaches a listener for document change events.
References assert, EMPTY_FUNCTION, firestore, initStream(), logger_1, rbtree, requestTag, shutdown(), and undefined.
pushSnapshot()
Watch::pushSnapshot (readTime, nextResumeToken) [inline], [private]
Assembles a new snapshot from the current set of changes and invokes the user's callback. Clears the current changes on completion.
References computeSnapshot(), logger_1, and requestTag.
resetDocs()
Watch::resetDocs () [inline], [private]
Helper to clear the docs on RESET or filter mismatch.
References logger_1, REMOVED, requestTag, and undefined.
resetIdleTimeout()
Watch::resetIdleTimeout () [inline], [private]
Cancels the current idle timeout and reschedules a new timer.
References _a, backoff_1, error, exports, google_gax_1, logger_1, maybeReopenStream(), and requestTag.
resetStream()
Watch::resetStream () [inline], [private]
Helper to restart the outgoing stream to the backend.
References initStream(), logger_1, and requestTag.
shutdown()
Watch::shutdown () [inline]
Closes the stream and clears all timeouts.
References _a, firestore, and undefined.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/watch.js