HttpsProxyAgent Class Reference
Public Member Functions
constructor (proxy, opts)
async connect (req, opts)
constructor (_opts)
callback (req, opts)
Detailed Description
The HttpsProxyAgent implements an HTTP Agent subclass that connects to the specified "HTTP(s) proxy server" in order to proxy HTTPS requests.
Outgoing HTTP requests are first tunneled through the proxy server using the CONNECT HTTP request method to establish a connection to the proxy server, and then the proxy server connects to the destination target and issues the HTTP request from the proxy server.
https: requests have their socket connection upgraded to TLS once the connection to the proxy server has been established.
The HttpsProxyAgent implements an HTTP Agent subclass that connects to the specified "HTTP(s) proxy server" in order to proxy HTTPS requests.
Outgoing HTTP requests are first tunneled through the proxy server using the CONNECT HTTP request method to establish a connection to the proxy server, and then the proxy server connects to the destination target and issues the HTTP request from the proxy server.
https: requests have their socket connection upgraded to TLS once the connection to the proxy server has been established.
@api public
Member Function Documentation
callback()
HttpsProxyAgent::callback (req, opts) [inline]
Called when the node-core HTTP client library is creating a new HTTP request.
@api protected
References $, __awaiter, assert_1, debug, headers, isDefaultPort(), name, net_1, of, omit, parse_proxy_response_1, proxy, req, resume, s, tls_1, and writable.
connect()
async HttpsProxyAgent::connect (req, opts) [inline]
Called when the node-core HTTP client library is creating a new HTTP request.
References $, assert_1, auth, connect, debug, emit, headers, name, net, of, parse_proxy_response_1, proxy, req, resume, s, tls, and writable.
constructor() [1/2]
HttpsProxyAgent::constructor (_opts) [inline]
References debug, isHTTPS(), parseInt(), proxy, and url_1.
constructor() [2/2]
HttpsProxyAgent::constructor (proxy, opts) [inline]
References $, debug, g, omit, parseInt(), path, proxy, replace, undefined, and url_1.
The documentation for this class was generated from the following files:
backend/node_modules/https-proxy-agent/dist/index.js
backend/node_modules/teeny-request/node_modules/https-proxy-agent/dist/agent.js