FirebaseNamespaceInternals Class Reference
Public Member Functions
constructor (appStore)
initializeApp (options, appName)
app (appName)
get apps ()
Detailed Description
Internals of a FirebaseNamespace instance.
Member Function Documentation
app()
FirebaseNamespaceInternals::app (appName) [inline]
Returns the App instance with the provided name (or the default App instance if no name is provided).
Parameters
appName - Optional name of the FirebaseApp instance to return.
Returns
The App instance which has the provided name.
References app, and extendApp().
apps()
get FirebaseNamespaceInternals::apps () [inline]
References app, and extendApp().
constructor()
FirebaseNamespaceInternals::constructor (appStore) [inline]
initializeApp()
FirebaseNamespaceInternals::initializeApp (options, appName) [inline]
Initializes the App instance.
Parameters
options - Optional options for the App instance. If none present will try to initialize from the FIREBASE_CONFIG environment variable. If the environment variable contains a string that starts with '{' it will be parsed as JSON, otherwise it will be assumed to be pointing to a file.
appName - Optional name of the FirebaseApp instance.
Returns
A new App instance.
References app, and extendApp().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/app/firebase-namespace.js