LoginTicket Class Reference
Public Member Functions
constructor (env, pay)
getEnvelope ()
getPayload ()
getUserId ()
getAttributes ()
Member Function Documentation
constructor()
LoginTicket::constructor (env, pay) [inline]
Create a simple class to extract user ID from an ID Token
Parameters
{string} env Envelope of the jwt
{TokenPayload} pay Payload of the jwt @constructor
References env.
getAttributes()
LoginTicket::getAttributes () [inline]
Returns attributes from the login ticket. This can contain various information about the user session.
Returns
The envelope and payload
References getEnvelope(), and getPayload().
getEnvelope()
LoginTicket::getEnvelope () [inline]
getPayload()
LoginTicket::getPayload () [inline]
getUserId()
LoginTicket::getUserId () [inline]
Create a simple class to extract user ID from an ID Token
Returns
The user ID
References getPayload().
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/loginticket.js