EntitiesParser Class Reference
Public Member Functions
constructor (replaceHtmlEntities)
addExternalEntities (externalEntities)
addExternalEntity (key, val)
addDocTypeEntities (entities)
parse (val)
replaceEntitiesValue (val)
constructor (replaceHtmlEntities)
addExternalEntities (externalEntities)
addExternalEntity (key, val)
addDocTypeEntities (entities)
parse (val)
replaceEntitiesValue (val)
Member Function Documentation
addDocTypeEntities() [1/2]
EntitiesParser::addDocTypeEntities (entities) [inline]
References entities, and i.
addDocTypeEntities() [2/2]
EntitiesParser::addDocTypeEntities (entities) [inline]
References entities, and i.
addExternalEntities() [1/2]
EntitiesParser::addExternalEntities (externalEntities) [inline]
References addExternalEntity(), and i.
addExternalEntities() [2/2]
EntitiesParser::addExternalEntities (externalEntities) [inline]
References addExternalEntity(), and i.
addExternalEntity() [1/2]
EntitiesParser::addExternalEntity (key, val) [inline]
References $, is, not, validateEntityName(), and value.
addExternalEntity() [2/2]
EntitiesParser::addExternalEntity (key, val) [inline]
References $, is, not, validateEntityName(), and value.
constructor() [1/2]
EntitiesParser::constructor (replaceHtmlEntities) [inline]
References g, gt, and lt.
constructor() [2/2]
EntitiesParser::constructor (replaceHtmlEntities) [inline]
References g, gt, and lt.
parse() [1/2]
EntitiesParser::parse (val) [inline]
References replaceEntitiesValue().
parse() [2/2]
EntitiesParser::parse (val) [inline]
References replaceEntitiesValue().
replaceEntitiesValue() [1/2]
EntitiesParser::replaceEntitiesValue (val) [inline]
Replace DOCTYPE entities
Replace external entities
Replace HTML entities if asked
Parameters
{string} val
References ampEntity, and htmlEntities.
replaceEntitiesValue() [2/2]
EntitiesParser::replaceEntitiesValue (val) [inline]
Replace DOCTYPE entities
Replace external entities
Replace HTML entities if asked
Parameters
{string} val
References ampEntity, and htmlEntities.
The documentation for this class was generated from the following files:
backend/node_modules/fast-xml-parser/src/v5/EntitiesParser.js
backend/node_modules/fast-xml-parser/src/v5/valueParsers/EntitiesParser.js