Tenant Class Reference
Public Member Functions
constructor (response)
get emailSignInConfig ()
get multiFactorConfig ()
get recaptchaConfig ()
toJSON ()
Static Public Member Functions
static buildServerRequest (tenantOptions, createRequest)
static getTenantIdFromResourceName (resourceName)
static validate (request, createRequest)
Detailed Description
Represents a tenant configuration.
Multi-tenancy support requires Google Cloud's Identity Platform (GCIP). To learn more about GCIP, including pricing and features, see the | GCIP documentation.
Before multi-tenancy can be used on a Google Cloud Identity Platform project, tenants must be allowed on that project via the Cloud Console UI.
A tenant configuration provides information such as the display name, tenant identifier and email authentication configuration. For OIDC/SAML provider configuration management, TenantAwareAuth instances should be used instead of a Tenant to retrieve the list of configured IdPs on a tenant. When configuring these providers, note that tenants will inherit whitelisted domains and authenticated redirect URIs of their parent project.
All other settings of a tenant will also be inherited. These will need to be managed from the Cloud Console UI.
Member Function Documentation
buildServerRequest()
static Tenant::buildServerRequest (tenantOptions, createRequest) [inline], [static]
Builds the corresponding server request for a TenantOptions object.
Parameters
tenantOptions - The properties to convert to a server request.
createRequest - Whether this is a create request.
Returns
The equivalent server request.
References auth_config_1, request, and validate().
constructor()
Tenant::constructor (response) [inline]
The Tenant object constructor.
Parameters
response - The server side response used to initialize the Tenant object. @constructor
References auth_config_1, deep_copy_1, e, error_1, getTenantIdFromResourceName(), and response.
emailSignInConfig()
get Tenant::emailSignInConfig () [inline]
The email sign in provider configuration. Here is the caller graph for this function:
getTenantIdFromResourceName()
static Tenant::getTenantIdFromResourceName (resourceName) [inline], [static]
Returns the tenant ID corresponding to the resource name if available.
Parameters
resourceName - The server side resource name
Returns
The tenant ID corresponding to the resource, null otherwise.
References $.
multiFactorConfig()
get Tenant::multiFactorConfig () [inline]
The multi-factor auth configuration on the current tenant. Here is the caller graph for this function:
recaptchaConfig()
get Tenant::recaptchaConfig () [inline]
The recaptcha config auth configuration of the current tenant. Here is the caller graph for this function:
toJSON()
Tenant::toJSON () [inline]
Returns a JSON-serializable representation of this object.
Returns
A JSON-serializable representation of this object.
References deep_copy_1, emailSignInConfig(), json, multiFactorConfig(), and recaptchaConfig().
validate()
static Tenant::validate (request, createRequest) [inline], [static]
Validates a tenant options object. Throws an error on failure.
Parameters
request - The tenant options object to validate.
createRequest - Whether this is a create request.
References $, a, auth_config_1, emailSignInConfig(), empty, error_1, is, multiFactorConfig(), not, recaptchaConfig(), request, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/tenant.js