YargsInstance Class Reference
Public Member Functions
constructor (processArgs=[], cwd, parentRequire, shim)
addHelpOpt (opt, msg)
help (opt, msg)
addShowHiddenOpt (opt, msg)
showHidden (opt, msg)
alias (key, value)
array (keys)
boolean (keys)
check (f, global)
choices (key, value)
coerce (keys, value)
conflicts (key1, key2)
config (key='config', msg, parseFn)
completion (cmd, desc, fn)
command (cmd, description, builder, handler, middlewares, deprecated)
commands (cmd, description, builder, handler, middlewares, deprecated)
commandDir (dir, opts)
count (keys)
default (key, value, defaultDescription)
defaults (key, value, defaultDescription)
demandCommand (min=1, max, minMsg, maxMsg)
demand (keys, max, msg)
demandOption (keys, msg)
deprecateOption (option, message)
describe (keys, description)
detectLocale (detect)
env (prefix)
epilogue (msg)
epilog (msg)
example (cmd, description)
exit (code, err)
exitProcess (enabled=true)
fail (f)
getAliases ()
async getCompletion (args, done)
getDemandedOptions ()
getDemandedCommands ()
getDeprecatedOptions ()
getDetectLocale ()
getExitProcess ()
getGroups ()
getHelp ()
getOptions ()
getStrict ()
getStrictCommands ()
getStrictOptions ()
global (globals, global)
group (opts, groupName)
hide (key)
implies (key, value)
locale (locale)
middleware (callback, applyBeforeValidation, global)
nargs (key, value)
normalize (keys)
number (keys)
option (key, opt)
options (key, opt)
parse (args, shortCircuit, _parseFn)
parseAsync (args, shortCircuit, _parseFn)
parseSync (args, shortCircuit, _parseFn)
parserConfiguration (config)
pkgConf (key, rootPath)
positional (key, opts)
recommendCommands (recommend=true)
required (keys, max, msg)
require (keys, max, msg)
requiresArg (keys)
showCompletionScript ($0, cmd)
showHelp (level)
scriptName (scriptName)
showHelpOnFail (enabled, message)
showVersion (level)
skipValidation (keys)
strict (enabled)
strictCommands (enabled)
strictOptions (enabled)
string (keys)
terminalWidth ()
updateLocale (obj)
updateStrings (obj)
usage (msg, description, builder, handler)
usageConfiguration (config)
version (opt, msg, ver)
wrap (cols)
catch (_err)
Public Attributes
argv
try
return argv
optionKey
warning
type
Member Function Documentation
addHelpOpt()
YargsInstance::addHelpOpt (opt, msg) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_helpOpt, _YargsInstance_usage, argsert(), boolean(), describe(), kDeleteFromParserHintObject, msg, and undefined.
addShowHiddenOpt()
YargsInstance::addShowHiddenOpt (opt, msg) [inline]
References __classPrivateFieldGet, _YargsInstance_defaultShowHiddenOpt, _YargsInstance_options, _YargsInstance_usage, argsert(), boolean(), describe(), msg, and undefined.
alias()
YargsInstance::alias (key, value) [inline]
References alias(), argsert(), kPopulateParserHintArrayDictionary, and value.
array()
YargsInstance::array (keys) [inline]
References argsert(), keys, kPopulateParserHintArray, and kTrackManuallySetKeys.
boolean()
YargsInstance::boolean (keys) [inline]
References argsert(), keys, kPopulateParserHintArray, and kTrackManuallySetKeys.
catch()
YargsInstance::catch (_err) [inline]
check()
YargsInstance::check (f, global) [inline]
References __classPrivateFieldGet, _YargsInstance_shim, _YargsInstance_usage, argsert(), argv, f, global, maybeAsyncResult(), middleware, result, and y18n.
choices()
YargsInstance::choices (key, value) [inline]
References argsert(), choices(), kPopulateParserHintArrayDictionary, and value.
coerce()
YargsInstance::coerce (keys, value) [inline]
References __classPrivateFieldGet, _YargsInstance_globalMiddleware, _YargsInstance_options, alias(), argsert(), argv, Array, coerce, keys, maybeAsyncResult(), of, result, value, and yargs.
command()
YargsInstance::command (cmd, description, builder, handler, middlewares, deprecated) [inline]
References __classPrivateFieldGet, _YargsInstance_command, and argsert().
commandDir()
YargsInstance::commandDir (dir, opts) [inline]
References __classPrivateFieldGet, _YargsInstance_command, _YargsInstance_parentRequire, _YargsInstance_shim, argsert(), and req.
commands()
YargsInstance::commands (cmd, description, builder, handler, middlewares, deprecated) [inline]
References command().
completion()
YargsInstance::completion (cmd, desc, fn) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_completion, _YargsInstance_completionCommand, argsert(), command(), fn, and undefined.
config()
YargsInstance::config (key = 'config', msg, parseFn) [inline]
References __classPrivateFieldGet, _YargsInstance_cwd, _YargsInstance_options, _YargsInstance_shim, _YargsInstance_usage, applyExtends(), argsert(), Array, concat, describe(), k, kGetParserConfiguration, msg, and undefined.
conflicts()
YargsInstance::conflicts (key1, key2) [inline]
References __classPrivateFieldGet, _YargsInstance_validation, and argsert().
constructor()
YargsInstance::constructor (processArgs = [], cwd, parentRequire, shim) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_command, _YargsInstance_completion, _YargsInstance_completionCommand, _YargsInstance_context, _YargsInstance_cwd, _YargsInstance_defaultShowHiddenOpt, _YargsInstance_detectLocale, _YargsInstance_emittedWarnings, _YargsInstance_exitError, _YargsInstance_exitProcess, _YargsInstance_frozens, _YargsInstance_globalMiddleware, _YargsInstance_groups, _YargsInstance_hasOutput, _YargsInstance_helpOpt, _YargsInstance_isGlobalContext, _YargsInstance_logger, _YargsInstance_options, _YargsInstance_output, _YargsInstance_parentRequire, _YargsInstance_parseContext, _YargsInstance_parseFn, _YargsInstance_parserConfig, _YargsInstance_pkgs, _YargsInstance_preservedGroups, _YargsInstance_processArgs, _YargsInstance_recommendCommands, _YargsInstance_shim, _YargsInstance_strict, _YargsInstance_strictCommands, _YargsInstance_strictOptions, _YargsInstance_usage, _YargsInstance_usageConfig, _YargsInstance_validation, _YargsInstance_versionOpt, commands, cwd, kCreateLogger, kGetDollarZero, kReset, and shim.
count()
YargsInstance::count (keys) [inline]
References argsert(), keys, kPopulateParserHintArray, and kTrackManuallySetKeys.
default()
YargsInstance::default (key, value, defaultDescription) [inline]
References __classPrivateFieldGet, _YargsInstance_options, _YargsInstance_shim, _YargsInstance_usage, argsert(), assertSingleKey(), kPopulateParserHintSingleValueDictionary, and value.
defaults()
YargsInstance::defaults (key, value, defaultDescription) [inline]
References value.
demand()
YargsInstance::demand (keys, max, msg) [inline]
References __classPrivateFieldGet, _YargsInstance_shim, Array, assertNotStrictEqual(), demandCommand(), demandOption(), keys, max, and msg.
demandCommand()
YargsInstance::demandCommand (min = 1, max, minMsg, maxMsg) [inline]
References __classPrivateFieldGet, argsert(), global, max, and min.
demandOption()
YargsInstance::demandOption (keys, msg) [inline]
References argsert(), demandOption(), keys, kPopulateParserHintSingleValueDictionary, and msg.
deprecateOption()
YargsInstance::deprecateOption (option, message) [inline]
References __classPrivateFieldGet, _YargsInstance_options, argsert(), message, and option().
describe()
YargsInstance::describe (keys, description) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, argsert(), keys, and kSetKey.
detectLocale()
YargsInstance::detectLocale (detect) [inline]
References __classPrivateFieldSet, _YargsInstance_detectLocale, and argsert().
env()
YargsInstance::env (prefix) [inline]
References __classPrivateFieldGet, _YargsInstance_options, argsert(), and prefix.
epilog()
YargsInstance::epilog (msg) [inline]
References epilogue, and msg.
epilogue()
YargsInstance::epilogue (msg) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, argsert(), and msg.
example()
YargsInstance::example (cmd, description) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, argsert(), Array, and example().
exit()
YargsInstance::exit (code, err) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_exitError, _YargsInstance_exitProcess, _YargsInstance_hasOutput, and _YargsInstance_shim.
exitProcess()
YargsInstance::exitProcess (enabled = true) [inline]
References __classPrivateFieldSet, _YargsInstance_exitProcess, argsert(), and enabled.
fail()
YargsInstance::fail (f) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, argsert(), and f.
getAliases()
YargsInstance::getAliases () [inline]
getCompletion()
async YargsInstance::getCompletion (args, done) [inline]
References __classPrivateFieldGet, _YargsInstance_completion, args, argsert(), done, Promise, reject(), and resolve.
getDemandedCommands()
YargsInstance::getDemandedCommands () [inline]
References __classPrivateFieldGet, _YargsInstance_options, and argsert().
getDemandedOptions()
YargsInstance::getDemandedOptions () [inline]
References __classPrivateFieldGet, _YargsInstance_options, and argsert().
getDeprecatedOptions()
YargsInstance::getDeprecatedOptions () [inline]
References __classPrivateFieldGet, _YargsInstance_options, and argsert().
getDetectLocale()
YargsInstance::getDetectLocale () [inline]
References __classPrivateFieldGet, and _YargsInstance_detectLocale.
getExitProcess()
YargsInstance::getExitProcess () [inline]
References __classPrivateFieldGet, and _YargsInstance_exitProcess.
getGroups()
YargsInstance::getGroups () [inline]
References __classPrivateFieldGet, _YargsInstance_groups, and _YargsInstance_preservedGroups.
getHelp()
YargsInstance::getHelp () [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_command, _YargsInstance_hasOutput, _YargsInstance_processArgs, _YargsInstance_usage, help(), isPromise, kRunYargsParserAndExecuteCommands, parse, Promise, and undefined.
getOptions()
YargsInstance::getOptions () [inline]
References __classPrivateFieldGet, and _YargsInstance_options.
getStrict()
YargsInstance::getStrict () [inline]
References __classPrivateFieldGet, and _YargsInstance_strict.
getStrictCommands()
YargsInstance::getStrictCommands () [inline]
References __classPrivateFieldGet, and _YargsInstance_strictCommands.
getStrictOptions()
YargsInstance::getStrictOptions () [inline]
References __classPrivateFieldGet, and _YargsInstance_strictOptions.
global()
YargsInstance::global (globals, global) [inline]
References __classPrivateFieldGet, _YargsInstance_options, argsert(), g, global, and l.
group()
YargsInstance::group (opts, groupName) [inline]
References __classPrivateFieldGet, _YargsInstance_groups, _YargsInstance_preservedGroups, argsert(), and concat.
help()
YargsInstance::help (opt, msg) [inline]
References addHelpOpt(), and msg.
hide()
YargsInstance::hide (key) [inline]
References __classPrivateFieldGet, _YargsInstance_options, and argsert().
implies()
YargsInstance::implies (key, value) [inline]
References __classPrivateFieldGet, _YargsInstance_validation, argsert(), and value.
locale()
YargsInstance::locale (locale) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_detectLocale, _YargsInstance_shim, argsert(), kGuessLocale, locale, and undefined.
middleware()
YargsInstance::middleware (callback, applyBeforeValidation, global) [inline]
References __classPrivateFieldGet, _YargsInstance_globalMiddleware, callback, and global.
nargs()
YargsInstance::nargs (key, value) [inline]
References argsert(), kPopulateParserHintSingleValueDictionary, nargs(), and value.
normalize()
YargsInstance::normalize (keys) [inline]
References argsert(), keys, and kPopulateParserHintArray.
number()
YargsInstance::number (keys) [inline]
References argsert(), keys, kPopulateParserHintArray, and kTrackManuallySetKeys.
option()
YargsInstance::option (key, opt) [inline]
References __classPrivateFieldGet, _YargsInstance_options, _YargsInstance_usage, _YargsInstance_versionOpt, alias(), argsert(), array(), boolean(), choices(), coerce, config, conflicts(), count, demand(), demandOption(), deprecate, deprecateOption(), describe(), global, group(), hide, implies(), k, kEmitWarning, kTrackManuallySetKeys, nargs(), normalize, number(), options(), requiresArg(), skipValidation(), string, and undefined.
options()
YargsInstance::options (key, opt) [inline]
References option().
parse()
YargsInstance::parse (args, shortCircuit, _parseFn) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_completion, _YargsInstance_exitError, _YargsInstance_exitProcess, _YargsInstance_output, _YargsInstance_parseContext, _YargsInstance_parseFn, _YargsInstance_processArgs, args, argsert(), argv, isPromise, kFreeze, kRunYargsParserAndExecuteCommands, and kUnfreeze.
parseAsync()
YargsInstance::parseAsync (args, shortCircuit, _parseFn) [inline]
References args, isPromise, parse, and Promise.
parserConfiguration()
YargsInstance::parserConfiguration (config) [inline]
References __classPrivateFieldSet, _YargsInstance_parserConfig, argsert(), and config.
parseSync()
YargsInstance::parseSync (args, shortCircuit, _parseFn) [inline]
References args, isPromise, and parse.
pkgConf()
YargsInstance::pkgConf (key, rootPath) [inline]
References __classPrivateFieldGet, _YargsInstance_cwd, _YargsInstance_options, _YargsInstance_shim, applyExtends(), argsert(), concat, kGetParserConfiguration, kPkgUp, and obj.
positional()
YargsInstance::positional (key, opts) [inline]
References __classPrivateFieldGet, _YargsInstance_command, _YargsInstance_context, _YargsInstance_usage, alias(), argsert(), Array, array(), demand(), group(), includes, k, objectKeys, objFilter(), option(), and v.
recommendCommands()
YargsInstance::recommendCommands (recommend = true) [inline]
References __classPrivateFieldSet, _YargsInstance_recommendCommands, and argsert().
require()
YargsInstance::require (keys, max, msg) [inline]
References demand(), keys, max, and msg.
required()
YargsInstance::required (keys, max, msg) [inline]
References demand(), keys, max, and msg.
requiresArg()
YargsInstance::requiresArg (keys) [inline]
References __classPrivateFieldGet, _YargsInstance_options, argsert(), keys, kPopulateParserHintSingleValueDictionary, and requiresArg().
scriptName()
YargsInstance::scriptName (scriptName) [inline]
References scriptName().
showCompletionScript()
YargsInstance::showCompletionScript ($0, cmd) [inline]
References __classPrivateFieldGet, _YargsInstance_completion, _YargsInstance_completionCommand, _YargsInstance_logger, and argsert().
showHelp()
YargsInstance::showHelp (level) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_command, _YargsInstance_hasOutput, _YargsInstance_processArgs, _YargsInstance_usage, argsert(), isPromise, kRunYargsParserAndExecuteCommands, parse, and undefined.
showHelpOnFail()
YargsInstance::showHelpOnFail (enabled, message) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, argsert(), enabled, and message.
showHidden()
YargsInstance::showHidden (opt, msg) [inline]
References addShowHiddenOpt(), and msg.
showVersion()
YargsInstance::showVersion (level) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, and argsert().
skipValidation()
YargsInstance::skipValidation (keys) [inline]
References argsert(), keys, and kPopulateParserHintArray.
strict()
YargsInstance::strict (enabled) [inline]
References __classPrivateFieldSet, _YargsInstance_strict, argsert(), and enabled.
strictCommands()
YargsInstance::strictCommands (enabled) [inline]
References __classPrivateFieldSet, _YargsInstance_strictCommands, argsert(), and enabled.
strictOptions()
YargsInstance::strictOptions (enabled) [inline]
References __classPrivateFieldSet, _YargsInstance_strictOptions, argsert(), and enabled.
string()
YargsInstance::string (keys) [inline]
References argsert(), keys, kPopulateParserHintArray, and kTrackManuallySetKeys.
terminalWidth()
YargsInstance::terminalWidth () [inline]
References __classPrivateFieldGet, _YargsInstance_shim, and argsert().
updateLocale()
YargsInstance::updateLocale (obj) [inline]
References obj, and updateStrings().
updateStrings()
YargsInstance::updateStrings (obj) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_detectLocale, _YargsInstance_shim, argsert(), and obj.
usage()
YargsInstance::usage (msg, description, builder, handler) [inline]
References $, __classPrivateFieldGet, _YargsInstance_shim, _YargsInstance_usage, argsert(), assertNotStrictEqual(), command(), match, msg, and undefined.
usageConfiguration()
YargsInstance::usageConfiguration (config) [inline]
References __classPrivateFieldSet, _YargsInstance_usageConfig, argsert(), and config.
version()
YargsInstance::version (opt, msg, ver) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _YargsInstance_usage, _YargsInstance_versionOpt, argsert(), boolean(), describe(), kDeleteFromParserHintObject, kGuessVersion, msg, and undefined.
wrap()
YargsInstance::wrap (cols) [inline]
References __classPrivateFieldGet, _YargsInstance_usage, and argsert().
Member Data Documentation
argv [1/2]
YargsInstance::argv
Initial value:
{
        if (!argv._ || !argv['--'])
            return argv
argv [2/2]
return YargsInstance::argv
optionKey
YargsInstance::optionKey
Initial value:
{
        objectKeys(__classPrivateFieldGet(this, _YargsInstance_options, "f")).forEach((hintKey) => {
            if (((key) => key === 'configObjects')(hintKey))
                return;
            const hint = __classPrivateFieldGet(this, _YargsInstance_options, "f")[hintKey];
            if (Array.isArray(hint)) {
                if (hint.includes(optionKey))
                    hint.splice(hint.indexOf(optionKey), 1);
            }
            else if (typeof hint === 'object') {
                delete hint[optionKey];
            }
        })
try
YargsInstance::try
Initial value:
{
            delete argv['--']
type
YargsInstance::type
warning
YargsInstance::warning
The documentation for this class was generated from the following file:
backend/node_modules/yargs/build/lib/yargs-factory.js