ConnectableObservable Class Reference
Public Member Functions
constructor (source, subjectFactory)
_subscribe (subscriber)
getSubject ()
_teardown ()
connect ()
refCount ()
constructor (subscribe)
lift (operator)
subscribe (observerOrNext, error, complete)
_trySubscribe (sink)
forEach (next, promiseCtor)
pipe (...operations)
toPromise (promiseCtor)
Member Function Documentation
_subscribe()
ConnectableObservable::_subscribe (subscriber) [inline]
References getSubject().
_teardown()
ConnectableObservable::_teardown () [inline]
_trySubscribe()
Observable::_trySubscribe (sink) [inline], [inherited]
References Observable::_subscribe().
connect()
ConnectableObservable::connect () [inline]
References _teardown(), createOperatorSubscriber, getSubject(), source, Subscription, and undefined.
constructor() [1/2]
ConnectableObservable::constructor (source, subjectFactory) [inline]
References hasLift, Observable::lift(), and source.
constructor() [2/2]
Observable::constructor (subscribe) [inline], [inherited]
References Observable::_subscribe(), and Observable::subscribe().
forEach()
Observable::forEach (next, promiseCtor) [inline], [inherited]
References error, getPromiseCtor(), next(), reject(), resolve, SafeSubscriber, Observable::subscribe(), and value.
getSubject()
ConnectableObservable::getSubject () [inline]
lift()
Observable::lift (operator) [inline], [inherited]
References Observable, and observable.
pipe()
Observable::pipe (...) [inline], [inherited]
References pipeFromArray.
refCount()
ConnectableObservable::refCount () [inline]
subscribe()
Observable::subscribe (observerOrNext, error, complete) [inline], [inherited]
References Observable::_subscribe(), Observable::_trySubscribe(), call, error, errorContext, isSubscriber(), SafeSubscriber, and source.
toPromise()
Observable::toPromise (promiseCtor) [inline], [inherited]
References getPromiseCtor(), reject(), resolve, Observable::subscribe(), and value.
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/observable/ConnectableObservable.js