FlattenedEncrypt Class Reference
Public Member Functions
constructor (plaintext)
setKeyManagementParameters (parameters)
setProtectedHeader (protectedHeader)
setSharedUnprotectedHeader (sharedUnprotectedHeader)
setUnprotectedHeader (unprotectedHeader)
setAdditionalAuthenticatedData (aad)
setContentEncryptionKey (cek)
setInitializationVector (iv)
async encrypt (key, options)
constructor (plaintext)
setKeyManagementParameters (parameters)
setProtectedHeader (protectedHeader)
setSharedUnprotectedHeader (sharedUnprotectedHeader)
setUnprotectedHeader (unprotectedHeader)
setAdditionalAuthenticatedData (aad)
setContentEncryptionKey (cek)
setInitializationVector (iv)
async encrypt (key, options)
constructor (plaintext)
setKeyManagementParameters (parameters)
setProtectedHeader (protectedHeader)
setSharedUnprotectedHeader (sharedUnprotectedHeader)
setUnprotectedHeader (unprotectedHeader)
setAdditionalAuthenticatedData (aad)
setContentEncryptionKey (cek)
setInitializationVector (iv)
async encrypt (key, options)
Member Function Documentation
constructor() [1/3]
FlattenedEncrypt::constructor (plaintext) [inline]
constructor() [2/3]
FlattenedEncrypt::constructor (plaintext) [inline]
constructor() [3/3]
FlattenedEncrypt::constructor (plaintext) [inline]
encrypt() [1/3]
async FlattenedEncrypt::encrypt (key, options) [inline]
References base64url, concat, decoder, deflate, encoder, encrypt, encryptKeyManagement, isDisjoint, JOSENotSupported, JSON, JWEInvalid, Map, setProtectedHeader(), setUnprotectedHeader(), undefined, unprotected, and validateCrit.
encrypt() [2/3]
async FlattenedEncrypt::encrypt (key, options) [inline]
References base64url_js_1, buffer_utils_js_1, encrypt_js_1, encrypt_key_management_js_1, errors_js_1, exports, is_disjoint_js_1, iv_js_1, JSON, Map, setProtectedHeader(), setUnprotectedHeader(), undefined, validate_crit_js_1, and zlib_js_1.
encrypt() [3/3]
async FlattenedEncrypt::encrypt (key, options) [inline]
References base64url, concat, decoder, deflate, encoder, encrypt, encryptKeyManagement, isDisjoint, JOSENotSupported, JSON, JWEInvalid, Map, setProtectedHeader(), setUnprotectedHeader(), undefined, unprotected, and validateCrit.
setAdditionalAuthenticatedData() [1/3]
FlattenedEncrypt::setAdditionalAuthenticatedData (aad) [inline]
setAdditionalAuthenticatedData() [2/3]
FlattenedEncrypt::setAdditionalAuthenticatedData (aad) [inline]
setAdditionalAuthenticatedData() [3/3]
FlattenedEncrypt::setAdditionalAuthenticatedData (aad) [inline]
setContentEncryptionKey() [1/3]
FlattenedEncrypt::setContentEncryptionKey (cek) [inline]
setContentEncryptionKey() [2/3]
FlattenedEncrypt::setContentEncryptionKey (cek) [inline]
setContentEncryptionKey() [3/3]
FlattenedEncrypt::setContentEncryptionKey (cek) [inline]
setInitializationVector() [1/3]
FlattenedEncrypt::setInitializationVector (iv) [inline]
setInitializationVector() [2/3]
FlattenedEncrypt::setInitializationVector (iv) [inline]
setInitializationVector() [3/3]
FlattenedEncrypt::setInitializationVector (iv) [inline]
setKeyManagementParameters() [1/3]
FlattenedEncrypt::setKeyManagementParameters (parameters) [inline]
setKeyManagementParameters() [2/3]
FlattenedEncrypt::setKeyManagementParameters (parameters) [inline]
setKeyManagementParameters() [3/3]
FlattenedEncrypt::setKeyManagementParameters (parameters) [inline]
setProtectedHeader() [1/3]
FlattenedEncrypt::setProtectedHeader (protectedHeader) [inline]
setProtectedHeader() [2/3]
FlattenedEncrypt::setProtectedHeader (protectedHeader) [inline]
setProtectedHeader() [3/3]
FlattenedEncrypt::setProtectedHeader (protectedHeader) [inline]
setSharedUnprotectedHeader() [1/3]
FlattenedEncrypt::setSharedUnprotectedHeader (sharedUnprotectedHeader) [inline]
setSharedUnprotectedHeader() [2/3]
FlattenedEncrypt::setSharedUnprotectedHeader (sharedUnprotectedHeader) [inline]
setSharedUnprotectedHeader() [3/3]
FlattenedEncrypt::setSharedUnprotectedHeader (sharedUnprotectedHeader) [inline]
setUnprotectedHeader() [1/3]
FlattenedEncrypt::setUnprotectedHeader (unprotectedHeader) [inline]
setUnprotectedHeader() [2/3]
FlattenedEncrypt::setUnprotectedHeader (unprotectedHeader) [inline]
setUnprotectedHeader() [3/3]
FlattenedEncrypt::setUnprotectedHeader (unprotectedHeader) [inline]
The documentation for this class was generated from the following files:
backend/node_modules/jose/dist/browser/jwe/flattened/encrypt.js
backend/node_modules/jose/dist/node/cjs/jwe/flattened/encrypt.js
backend/node_modules/jose/dist/node/esm/jwe/flattened/encrypt.js