HashStreamValidator Class Reference
Public Member Functions
constructor (options={})
get crc32c ()
_flush (callback)
_transform (chunk, encoding, callback)
test (hash, sum)
constructor (options={})
get crc32c ()
_flush (callback)
_transform (chunk, encoding, callback)
test (hash, sum)
Member Function Documentation
_flush() [1/2]
HashStreamValidator::_flush (callback) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _HashStreamValidator_md5Digest, _HashStreamValidator_md5Hash, callback, digest, file_js_1, and test.
_flush() [2/2]
HashStreamValidator::_flush (callback) [inline]
References __classPrivateFieldGet, __classPrivateFieldSet, _HashStreamValidator_md5Digest, _HashStreamValidator_md5Hash, callback, digest, RequestError, and test.
_transform() [1/2]
HashStreamValidator::_transform (chunk, encoding, callback) [inline]
References __classPrivateFieldGet, _HashStreamValidator_crc32cHash, _HashStreamValidator_md5Hash, callback, chunk(), e, encoding, and push.
_transform() [2/2]
HashStreamValidator::_transform (chunk, encoding, callback) [inline]
References __classPrivateFieldGet, _HashStreamValidator_crc32cHash, _HashStreamValidator_md5Hash, callback, chunk(), e, encoding, and push.
constructor() [1/2]
HashStreamValidator::constructor (options = {}) [inline]
constructor() [2/2]
HashStreamValidator::constructor (options = {}) [inline]
crc32c() [1/2]
get HashStreamValidator::crc32c () [inline]
Return the current CRC32C value, if available.
References __classPrivateFieldGet, _a, and _HashStreamValidator_crc32cHash.
crc32c() [2/2]
get HashStreamValidator::crc32c () [inline]
Return the current CRC32C value, if available.
References __classPrivateFieldGet, _a, and _HashStreamValidator_crc32cHash.
test() [1/2]
HashStreamValidator::test (hash, sum) [inline]
References __classPrivateFieldGet, _HashStreamValidator_crc32cHash, _HashStreamValidator_md5Digest, _HashStreamValidator_md5Hash, check, hash(), and sum().
test() [2/2]
HashStreamValidator::test (hash, sum) [inline]
References __classPrivateFieldGet, _HashStreamValidator_crc32cHash, _HashStreamValidator_md5Digest, _HashStreamValidator_md5Hash, check, hash(), and sum().
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/hash-stream-validator.js
backend/node_modules/@google-cloud/storage/build/esm/src/hash-stream-validator.js