Timestamp Class Reference
Public Member Functions
constructor (seconds, nanoseconds)
get seconds ()
get nanoseconds ()
toDate ()
toMillis ()
isEqual (other)
valueOf ()
Static Public Member Functions
static now ()
static fromDate (date)
static fromMillis (milliseconds)
Private Member Functions
toProto ()
Static Private Member Functions
static fromProto (timestamp)
Detailed Description
A Timestamp represents a point in time independent of any time zone or calendar, represented as seconds and fractions of seconds at nanosecond resolution in UTC Epoch time. It is encoded using the Proleptic Gregorian Calendar which extends the Gregorian calendar backwards to year one. It is encoded assuming all minutes are 60 seconds long, i.e. leap seconds are "smeared" so that no leap second table is needed for interpretation. Range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z.
See also
 https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto
Member Function Documentation
constructor()
Timestamp::constructor (seconds, nanoseconds) [inline]
References MAX_SECONDS, MIN_SECONDS, nanoseconds(), seconds(), and validate_1.
fromDate()
static Timestamp::fromDate (date) [inline], [static]
References fromMillis().
fromMillis()
static Timestamp::fromMillis (milliseconds) [inline], [static]
References MS_TO_NANOS, seconds(), and Timestamp.
fromProto()
static Timestamp::fromProto (timestamp) [inline], [static], [private]
Generates a Timestamp object from a Timestamp proto.
References Timestamp, and timestamp.
isEqual()
Timestamp::isEqual (other) [inline]
References seconds().
nanoseconds()
get Timestamp::nanoseconds () [inline]
now()
static Timestamp::now () [inline], [static]
References fromMillis().
seconds()
get Timestamp::seconds () [inline]
toDate()
Timestamp::toDate () [inline]
References MS_TO_NANOS.
toMillis()
Timestamp::toMillis () [inline]
References MS_TO_NANOS.
toProto()
Timestamp::toProto () [inline], [private]
Generates the Protobuf Timestamp object for this timestamp.
References nanoseconds(), seconds(), and timestamp.
valueOf()
Timestamp::valueOf () [inline]
Converts this object to a primitive string, which allows Timestamp objects to be compared using the >, <=, >= and > operators.
Returns
{string} a string encoding of this object.
References MIN_SECONDS, nanoseconds(), and seconds().
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/timestamp.js