Sha1 Class Reference
Public Member Functions
reset ()
update (bytes, length)
digest ()
reset ()
update (bytes, length)
digest ()
reset ()
update (bytes, length)
digest ()
Private Member Functions
constructor ()
compress_ (buf, offset)
constructor ()
compress_ (buf, offset)
constructor ()
compress_ (buf, offset)
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. @fileoverview SHA-1 cryptographic hash. Variable names follow the notation in FIPS PUB 180-3: http://csrc.nist.gov/publications/fips/fips180-3/fips180-3_final.pdf.
Usage: var sha1 = new sha1(); sha1.update(bytes); var hash = sha1.digest();
Performance: Chrome 23: ~400 Mbit/s Firefox 16: ~250 Mbit/s SHA-1 cryptographic hash constructor.
The properties declared here are discussed in the above algorithm document. @constructor @final
Member Function Documentation
compress_() [1/3]
Sha1::compress_ (buf, offset) [inline], [private]
Internal compress helper function.
Parameters
buf Block to compress.
offset Offset of the block in the buffer.
References a, b, buf, c, d, e, f, i, k, and t.
compress_() [2/3]
Sha1::compress_ (buf, offset) [inline], [private]
Internal compress helper function.
Parameters
buf Block to compress.
offset Offset of the block in the buffer.
References a, b, buf, c, d, e, f, i, k, and t.
compress_() [3/3]
Sha1::compress_ (buf, offset) [inline], [private]
Internal compress helper function.
Parameters
buf Block to compress.
offset Offset of the block in the buffer.
References a, b, buf, c, d, e, f, i, k, and t.
constructor() [1/3]
Sha1::constructor () [inline], [private]
Holds the previous values of accumulated variables a-e in the compress_ function.
A buffer holding the partially computed hash result.
An array of 80 bytes, each a part of the message to be hashed. Referred to as the message schedule in the docs.
Contains data needed to pad messages less than 64 bytes.
{number}
{number}
References i, and reset().
constructor() [2/3]
Sha1::constructor () [inline], [private]
Holds the previous values of accumulated variables a-e in the compress_ function.
A buffer holding the partially computed hash result.
An array of 80 bytes, each a part of the message to be hashed. Referred to as the message schedule in the docs.
Contains data needed to pad messages less than 64 bytes.
{number}
{number}
References i, and reset().
constructor() [3/3]
Sha1::constructor () [inline], [private]
Holds the previous values of accumulated variables a-e in the compress_ function.
A buffer holding the partially computed hash result.
An array of 80 bytes, each a part of the message to be hashed. Referred to as the message schedule in the docs.
Contains data needed to pad messages less than 64 bytes.
{number}
{number}
References i, and reset().
digest() [1/3]
Sha1::digest () [inline]
@override
References compress_(), digest(), i, j, n, and update.
digest() [2/3]
Sha1::digest () [inline]
@override
References compress_(), digest(), i, j, n, and update.
digest() [3/3]
Sha1::digest () [inline]
@override
References compress_(), digest(), i, j, n, and update.
reset() [1/3]
Sha1::reset () [inline]
reset() [2/3]
Sha1::reset () [inline]
reset() [3/3]
Sha1::reset () [inline]
update() [1/3]
Sha1::update (bytes, length) [inline]
References buf, bytes, compress_(), length, n, and undefined.
update() [2/3]
Sha1::update (bytes, length) [inline]
References buf, bytes, compress_(), length, n, and undefined.
update() [3/3]
Sha1::update (bytes, length) [inline]
References buf, bytes, compress_(), length, n, and undefined.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/util/dist/index.cjs.js
backend/node_modules/@firebase/util/dist/index.esm2017.js
backend/node_modules/@firebase/util/dist/node-esm/index.node.esm.js