ChildChangeAccumulator Class Reference
Public Member Functions
constructor ()
trackChildChange (change)
getChanges ()
constructor ()
trackChildChange (change)
getChanges ()
constructor ()
trackChildChange (change)
getChanges ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Member Function Documentation
constructor() [1/3]
ChildChangeAccumulator::constructor () [inline]
References Map.
constructor() [2/3]
ChildChangeAccumulator::constructor () [inline]
References Map.
constructor() [3/3]
ChildChangeAccumulator::constructor () [inline]
References Map.
getChanges() [1/3]
ChildChangeAccumulator::getChanges () [inline]
References Array.
getChanges() [2/3]
ChildChangeAccumulator::getChanges () [inline]
References Array.
getChanges() [3/3]
ChildChangeAccumulator::getChanges () [inline]
References Array.
trackChildChange() [1/3]
ChildChangeAccumulator::trackChildChange (change) [inline]
References changeChildAdded(), changeChildChanged(), changeChildRemoved(), type, and util.
trackChildChange() [2/3]
ChildChangeAccumulator::trackChildChange (change) [inline]
References assert, assertionError, changeChildAdded(), changeChildChanged(), changeChildRemoved(), and type.
trackChildChange() [3/3]
ChildChangeAccumulator::trackChildChange (change) [inline]
References assert, assertionError, changeChildAdded(), changeChildChanged(), changeChildRemoved(), and type.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js