UI Class Reference
Public Member Functions
constructor (opts)
span (...args)
resetOutput ()
div (...args)
shouldApplyLayoutDSL (...args)
applyLayoutDSL (str)
colFromString (text)
measurePadding (str)
toString ()
rowToString (row, lines)
renderInline (source, previousLine)
rasterize (row)
negatePadding (col)
columnWidths (row)
Member Function Documentation
applyLayoutDSL()
UI::applyLayoutDSL (str) [inline]
References div, i, mixin, r, and str().
colFromString()
UI::colFromString (text) [inline]
References text.
columnWidths()
UI::columnWidths (row) [inline]
References _minWidth(), i, mixin, undefined, unset(), w, and wrap.
constructor()
UI::constructor (opts) [inline]
References _a, and wrap.
div()
UI::div (...) [inline]
References applyLayoutDSL(), args, colFromString(), div, shouldApplyLayoutDSL(), and wrap.
measurePadding()
UI::measurePadding (str) [inline]
References $, mixin, s, and str().
negatePadding()
UI::negatePadding (col) [inline]
References left, and right.
rasterize()
UI::rasterize (row) [inline]
References Array, bottom, c, i, mixin, r, repeat, str(), top, undefined, and wrap.
renderInline()
UI::renderInline (source, previousLine) [inline]
References match, mixin, source, and wrap.
resetOutput()
UI::resetOutput () [inline]
rowToString()
UI::rowToString (row, lines) [inline]
References $, addBorder(), align, c, fn, left, lines, mixin, r, right, str(), text, and wrap.
shouldApplyLayoutDSL()
UI::shouldApplyLayoutDSL (...) [inline]
References args.
span()
UI::span (...) [inline]
References args, and div.
toString()
UI::toString () [inline]
References lines.
The documentation for this class was generated from the following file:
backend/node_modules/cliui/build/lib/index.js