FirebaseInstallationsError Class Reference
Public Member Functions
constructor (info, message)
constructor (code, message, customData)
constructor (errorInfo)
get code ()
get message ()
toJSON ()
Detailed Description
Firebase Installations service error code structure. This extends FirebaseError.
Member Function Documentation
code()
get FirebaseError::code () [inline], [inherited]
Returns
The error code.
constructor() [1/3]
FirebaseError::constructor (code, message, customData) [inline], [inherited]
The custom name for all FirebaseErrors.
Parameters
code The error code for this error.
customData Custom data for this error.
References FirebaseError::code(), ErrorFactory::create(), ERROR_NAME, FirebaseError::message(), and name.
constructor() [2/3]
FirebaseError::constructor (errorInfo) [inline], [inherited]
Parameters
errorInfo - The error information (code and message). @constructor
constructor() [3/3]
FirebaseInstallationsError::constructor (info, message) [inline]
Parameters
info - The error code info.
message - The error message. This will override the default message if provided. @constructor
References FirebaseError::code(), and FirebaseError::message().
message()
get FirebaseError::message () [inline], [inherited]
Returns
The error message.
toJSON()
FirebaseError::toJSON () [inline], [inherited]
Returns
The object representation of the error.
References FirebaseError::code(), and FirebaseError::message().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/error.js