InternalChannel Class Reference
Public Member Functions
constructor (target, credentials, options)
getChannelzInfo ()
trace (text, verbosityOverride)
callRefTimerRef ()
callRefTimerUnref ()
removeConnectivityStateWatcher (watcherObject)
updateState (newState)
throttleKeepalive (newKeepaliveTime)
removeWrappedSubchannel (wrappedSubchannel)
doPick (metadata, extraPickInfo)
queueCallForPick (call)
getConfig (method, metadata)
queueCallForConfig (call)
enterIdle ()
startIdleTimeout (timeoutMs)
maybeStartIdleTimer ()
onCallStart ()
onCallEnd (status)
createLoadBalancingCall (callConfig, method, host, credentials, deadline)
createRetryingCall (callConfig, method, host, credentials, deadline)
createInnerCall (callConfig, method, host, credentials, deadline)
createResolvingCall (method, deadline, host, parentCall, propagateFlags)
close ()
getTarget ()
getConnectivityState (tryToConnect)
watchConnectivityState (currentState, deadline, callback)
getChannelzRef ()
createCall (method, deadline, host, parentCall, propagateFlags)
getOptions ()
Member Function Documentation
callRefTimerRef()
InternalChannel::callRefTimerRef () [inline]
References _a, _b, _c, _d, and trace.
callRefTimerUnref()
InternalChannel::callRefTimerUnref () [inline]
References _a, _b, and trace.
close()
InternalChannel::close () [inline]
References call, channelz_1, connectivity_state_1, constants_1, of, and updateState().
constructor()
InternalChannel::constructor (target, credentials, options) [inline]
Calls queued up to get a call config. Should only be populated before the first time the resolver returns a result, which includes the ConfigSelector.
This is the error from the name resolver if it failed most recently. It is only used to end calls that start while there is no config selector and the name resolver is in backoff, so it should be nulled if configSelector becomes set or the channel state becomes anything other than TRANSIENT_FAILURE.
Randomly generated ID to be passed to the config selector, for use by ring_hash in xDS. An integer distributed approximately uniformly between 0 and MAX_SAFE_INTEGER.
References _a, _b, _c, _d, _g, a, call, callRefTimerUnref(), channel_credentials_1, channelz_1, compression_filter_1, connectivity_state_1, constants_1, control_plane_status_1, credentials, DEFAULT_IDLE_TIMEOUT_MS, DEFAULT_PER_RPC_RETRY_BUFFER_SIZE_BYTES, DEFAULT_RETRY_BUFFER_SIZE_BYTES, error, filter_stack_1, find, getChannelzInfo(), getTarget(), http_proxy_1, JSON, logging_1, MAX_TIMEOUT_TIME, MIN_IDLE_TIMEOUT_MS, name, not, of, parse, picker_1, process, resolver_1, resolving_load_balancer_1, RETRY_THROTTLER_MAP, retrying_call_1, serviceConfig, Set, status, subchannel_pool_1, trace, undefined, updateState(), and uri_parser_1.
createCall()
InternalChannel::createCall (method, deadline, host, parentCall, propagateFlags) [inline]
References connectivity_state_1, createResolvingCall(), and method.
createInnerCall()
InternalChannel::createInnerCall (callConfig, method, host, credentials, deadline) [inline]
References createLoadBalancingCall(), createRetryingCall(), credentials, and method.
createLoadBalancingCall()
InternalChannel::createLoadBalancingCall (callConfig, method, host, credentials, deadline) [inline]
References call_number_1, credentials, load_balancing_call_1, method, and trace.
createResolvingCall()
InternalChannel::createResolvingCall (method, deadline, host, parentCall, propagateFlags) [inline]
References call, call_number_1, constants_1, deadline_1, method, onCallEnd(), onCallStart(), resolving_call_1, status, and trace.
createRetryingCall()
InternalChannel::createRetryingCall (callConfig, method, host, credentials, deadline) [inline]
References call_number_1, credentials, method, RETRY_THROTTLER_MAP, retrying_call_1, and trace.
doPick()
InternalChannel::doPick (metadata, extraPickInfo) [inline]
enterIdle()
InternalChannel::enterIdle () [inline]
References connectivity_state_1, picker_1, and updateState().
getChannelzInfo()
InternalChannel::getChannelzInfo () [inline]
References state(), and trace.
getChannelzRef()
InternalChannel::getChannelzRef () [inline]
Get the channelz reference object for this channel. The returned value is garbage if channelz is disabled for this channel.
Returns
getConfig()
InternalChannel::getConfig (method, metadata) [inline]
References config, connectivity_state_1, error, method, and type.
getConnectivityState()
InternalChannel::getConnectivityState (tryToConnect) [inline]
References maybeStartIdleTimer().
getOptions()
InternalChannel::getOptions () [inline]
getTarget()
InternalChannel::getTarget () [inline]
References uri_parser_1.
maybeStartIdleTimer()
InternalChannel::maybeStartIdleTimer () [inline]
References connectivity_state_1, and startIdleTimeout().
onCallEnd()
InternalChannel::onCallEnd (status) [inline]
References constants_1, maybeStartIdleTimer(), and status.
onCallStart()
InternalChannel::onCallStart () [inline]
queueCallForConfig()
InternalChannel::queueCallForConfig (call) [inline]
References call, and callRefTimerRef().
queueCallForPick()
InternalChannel::queueCallForPick (call) [inline]
References call, and callRefTimerRef().
removeConnectivityStateWatcher()
InternalChannel::removeConnectivityStateWatcher (watcherObject) [inline]
References value.
removeWrappedSubchannel()
InternalChannel::removeWrappedSubchannel (wrappedSubchannel) [inline]
startIdleTimeout()
InternalChannel::startIdleTimeout (timeoutMs) [inline]
References _a, _b, enterIdle(), now, startIdleTimeout(), and trace.
throttleKeepalive()
InternalChannel::throttleKeepalive (newKeepaliveTime) [inline]
References of.
trace()
InternalChannel::trace (text, verbosityOverride) [inline]
References constants_1, logging_1, text, and uri_parser_1.
updateState()
InternalChannel::updateState (newState) [inline]
References connectivity_state_1, constants_1, logging_1, of, removeConnectivityStateWatcher(), and uri_parser_1.
watchConnectivityState()
InternalChannel::watchConnectivityState (currentState, deadline, callback) [inline]
References callback, connectivity_state_1, now, process, removeConnectivityStateWatcher(), and timer.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/internal-channel.js