ResolvingCall Class Reference
Public Member Functions
constructor (channel, method, options, filterStackFactory, credentials, callNumber)
trace (text)
runDeadlineTimer ()
outputStatus (status)
sendMessageOnChild (context, message)
getConfig ()
reportResolverError (status)
cancelWithStatus (status, details)
getPeer ()
start (metadata, listener)
sendMessageWithContext (context, message)
startRead ()
halfClose ()
setCredentials (credentials)
addStatusWatcher (watcher)
getCallNumber ()
Member Function Documentation
addStatusWatcher()
ResolvingCall::addStatusWatcher (watcher) [inline]
cancelWithStatus()
ResolvingCall::cancelWithStatus (status, details) [inline]
References _a, metadata_1, outputStatus(), status, and trace.
constructor()
ResolvingCall::constructor (channel, method, options, filterStackFactory, credentials, callNumber) [inline]
References cancelWithStatus(), constants_1, credentials, deadline_1, method, runDeadlineTimer(), and trace.
getCallNumber()
ResolvingCall::getCallNumber () [inline]
getConfig()
ResolvingCall::getConfig () [inline]
References cancelWithStatus(), config, constants_1, control_plane_status_1, credentials, deadline_1, message, metadata_1, method, outputStatus(), Promise, runDeadlineTimer(), sendMessageOnChild(), status, and trace.
getPeer()
ResolvingCall::getPeer () [inline]
References _a, and _b.
halfClose()
ResolvingCall::halfClose () [inline]
References trace.
outputStatus()
ResolvingCall::outputStatus (status) [inline]
References _a, process, status, and trace.
reportResolverError()
ResolvingCall::reportResolverError (status) [inline]
References _a, outputStatus(), and status.
runDeadlineTimer()
ResolvingCall::runDeadlineTimer () [inline]
References $, after(), cancelWithStatus(), constants_1, deadline_1, name, process, timeout, and trace.
sendMessageOnChild()
ResolvingCall::sendMessageOnChild (context, message) [inline]
References cancelWithStatus(), context, Promise, and status.
sendMessageWithContext()
ResolvingCall::sendMessageWithContext (context, message) [inline]
References context, message, sendMessageOnChild(), and trace.
setCredentials()
ResolvingCall::setCredentials (credentials) [inline]
References credentials.
start()
ResolvingCall::start (metadata, listener) [inline]
References getConfig(), and trace.
startRead()
ResolvingCall::startRead () [inline]
References trace.
trace()
ResolvingCall::trace (text) [inline]
References constants_1, logging, text, and TRACER_NAME.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/resolving-call.js