ConditionEvaluator Class Reference
Public Member Functions
evaluateConditions (namedConditions, context)
evaluateCondition (condition, context, nestingLevel=0)
evaluateOrCondition (orCondition, context, nestingLevel)
evaluateAndCondition (andCondition, context, nestingLevel)
evaluatePercentCondition (percentCondition, context)
evaluateCustomSignalCondition (customSignalCondition, context)
Static Public Member Functions
static hashSeededRandomizationId (seededRandomizationId)
Detailed Description
Encapsulates condition evaluation logic to simplify organization and facilitate testing.
Member Function Documentation
evaluateAndCondition()
ConditionEvaluator::evaluateAndCondition (andCondition, context, nestingLevel) [inline]
References context, evaluateCondition(), of, and result.
evaluateCondition()
ConditionEvaluator::evaluateCondition (condition, context, nestingLevel = 0) [inline]
References context, evaluateAndCondition(), evaluateCustomSignalCondition(), evaluateOrCondition(), and evaluatePercentCondition().
evaluateConditions()
ConditionEvaluator::evaluateConditions (namedConditions, context) [inline]
References context, Map, and of.
evaluateCustomSignalCondition()
ConditionEvaluator::evaluateCustomSignalCondition (customSignalCondition, context) [inline]
References compareNumbers(), compareSemanticVersions(), compareStrings(), context, r, remote_config_api_1, test, and undefined.
evaluateOrCondition()
ConditionEvaluator::evaluateOrCondition (orCondition, context, nestingLevel) [inline]
References context, evaluateCondition(), of, and result.
evaluatePercentCondition()
ConditionEvaluator::evaluatePercentCondition (percentCondition, context) [inline]
References $, context, hash64, hashSeededRandomizationId(), and remote_config_api_1.
hashSeededRandomizationId()
static ConditionEvaluator::hashSeededRandomizationId (seededRandomizationId) [inline], [static]
References farmhash, and hash64.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/remote-config/condition-evaluator-internal.js