ExponentialBackoffPoller Class Reference
Public Member Functions
constructor (initialPollingDelayMillis=1000, maxPollingDelayMillis=10000, masterTimeoutMillis=60000)
poll (callback)
repoll ()
getPollingDelayMillis ()
markCompleted ()
Detailed Description
Class used for polling an endpoint with exponential backoff.
Example usage:
const poller = new ExponentialBackoffPoller();
poller
    .poll(() => {
      return myRequestToPoll()
          .then((responseData: any) => {
            if (!isValid(responseData)) {
              // Continue polling.
              return null;
            }
            // Polling complete. Resolve promise with final response data.
            return responseData;
          });
    })
    .then((responseData: any) => {
      console.log(Final response: ${responseData});
    });
Member Function Documentation
constructor()
ExponentialBackoffPoller::constructor (initialPollingDelayMillis = 1000, maxPollingDelayMillis = 10000, masterTimeoutMillis = 60000) [inline]
getPollingDelayMillis()
ExponentialBackoffPoller::getPollingDelayMillis () [inline]
markCompleted()
ExponentialBackoffPoller::markCompleted () [inline]
poll()
ExponentialBackoffPoller::poll (callback) [inline]
Poll the provided callback with exponential backoff.
Parameters
callback - The callback to be called for each poll. If the callback resolves to a falsey value, polling will continue. Otherwise, the truthy resolution will be used to resolve the promise returned by this method.
Returns
A Promise which resolves to the truthy value returned by the provided callback when polling is complete.
References callback, markCompleted(), on, Promise, reject(), repoll(), and resolve.
repoll()
ExponentialBackoffPoller::repoll () [inline]
References emit, getPollingDelayMillis(), markCompleted(), reject(), resolve, and result.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js