AsyncRequestCall Class Reference
Public Member Functions
constructor (configImpl)
getMultipartBoundary (headers)
handleMultipartResponse (response, respStream, boundary)
handleRegularResponse (response, respStream)
finalizeResponse (response)
rejectWithError (message, code, request, response)
enhanceAndReject (error, code, request, response)
enhanceError (error, code, request, response)
Detailed Description
A helper class for common functionality needed to send requests over the wire. It also wraps the callback API of the Node.js standard library in a more flexible Promise API.
Member Function Documentation
constructor()
AsyncRequestCall::constructor (configImpl) [inline]
enhanceAndReject()
AsyncRequestCall::enhanceAndReject (error, code, request, response) [inline]
References enhanceError(), error, reject(), request, and response.
enhanceError()
AsyncRequestCall::enhanceError (error, code, request, response) [inline]
Enhances the given error by adding more information to it. Specifically, the request config, the underlying request and response will be attached to the error.
References error, request, and response.
finalizeResponse()
AsyncRequestCall::finalizeResponse (response) [inline]
Finalizes the current request call in-flight by either resolving or rejecting the associated promise. In the event of an error, adds additional useful information to the returned error.
References rejectWithError(), resolve, and response.
getMultipartBoundary()
AsyncRequestCall::getMultipartBoundary (headers) [inline]
Extracts multipart boundary from the HTTP header. The content-type header of a multipart response has the form 'multipart/subtype; boundary=string'.
If the content-type header does not exist, or does not start with 'multipart/', then null will be returned.
References contentType, emptyObject, and headers.
handleMultipartResponse()
AsyncRequestCall::handleMultipartResponse (response, respStream, boundary) [inline]
References finalizeResponse(), require(), response, and undefined.
handleRegularResponse()
AsyncRequestCall::handleRegularResponse (response, respStream) [inline]
References chunk(), enhanceAndReject(), finalizeResponse(), req, and response.
rejectWithError()
AsyncRequestCall::rejectWithError (message, code, request, response) [inline]
Creates a new error from the given message, and enhances it with other information available. Then the promise associated with this request call is rejected with the resulting error.
References enhanceAndReject(), error, message, request, and response.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js