AppCheckTokenProvider Class Reference
Public Member Functions
constructor (appName_, appCheckProvider)
getToken (forceRefresh)
addTokenChangeListener (listener)
notifyForInvalidToken ()
constructor (appName_, appCheckProvider)
getToken (forceRefresh)
addTokenChangeListener (listener)
notifyForInvalidToken ()
constructor (appName_, appCheckProvider)
getToken (forceRefresh)
addTokenChangeListener (listener)
notifyForInvalidToken ()
Detailed Description
@license Copyright 2021 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Abstraction around AppCheck's token fetching capabilities.
Member Function Documentation
addTokenChangeListener() [1/3]
AppCheckTokenProvider::addTokenChangeListener (listener) [inline]
References _a.
addTokenChangeListener() [2/3]
AppCheckTokenProvider::addTokenChangeListener (listener) [inline]
References _a.
addTokenChangeListener() [3/3]
AppCheckTokenProvider::addTokenChangeListener (listener) [inline]
References _a.
constructor() [1/3]
AppCheckTokenProvider::constructor (appName_, appCheckProvider) [inline]
constructor() [2/3]
AppCheckTokenProvider::constructor (appName_, appCheckProvider) [inline]
constructor() [3/3]
AppCheckTokenProvider::constructor (appName_, appCheckProvider) [inline]
getToken() [1/3]
AppCheckTokenProvider::getToken (forceRefresh) [inline]
References getToken(), Promise, reject(), and resolve.
getToken() [2/3]
AppCheckTokenProvider::getToken (forceRefresh) [inline]
References getToken(), Promise, reject(), and resolve.
getToken() [3/3]
AppCheckTokenProvider::getToken (forceRefresh) [inline]
References getToken(), Promise, reject(), and resolve.
notifyForInvalidToken() [1/3]
AppCheckTokenProvider::notifyForInvalidToken () [inline]
References app, credentials, and warn.
notifyForInvalidToken() [2/3]
AppCheckTokenProvider::notifyForInvalidToken () [inline]
References app, credentials, and warn.
notifyForInvalidToken() [3/3]
AppCheckTokenProvider::notifyForInvalidToken () [inline]
References app, credentials, and warn.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js