PluggableAuthHandler Class Reference
Public Member Functions
constructor (options)
retrieveResponseFromExecutable (envMap)
async retrieveCachedResponse ()
Static Public Member Functions
static parseCommand (command)
Detailed Description
A handler used to retrieve 3rd party token responses from user defined executables and cached file output for the PluggableAuthClient class.
Member Function Documentation
constructor()
PluggableAuthHandler::constructor (options) [inline]
Instantiates a PluggableAuthHandler instance using the provided PluggableAuthHandlerOptions object.
References parseCommand().
parseCommand()
static PluggableAuthHandler::parseCommand (command) [inline], [static]
Parses given command string into component array, splitting on spaces unless spaces are between quotation marks.
References command(), g, i, not, s, and slice.
retrieveCachedResponse()
async PluggableAuthHandler::retrieveCachedResponse () [inline]
Checks user provided output file for response from previous run of executable and return the response if it exists, is formatted correctly, and is not expired.
References $, _a, an, encoding, error, executable_response_1, file, fs, invalid(), JSON, response, and undefined.
retrieveResponseFromExecutable()
PluggableAuthHandler::retrieveResponseFromExecutable (envMap) [inline]
Calls user provided executable to get a 3rd party subject token and returns the response.
Parameters
envMap a Map of additional Environment Variables required for the executable.
Returns
A promise that resolves with the executable response.
References $, an, childProcess, data, error, executable_response_1, invalid(), JSON, pluggable_auth_client_1, Promise, reject(), resolve, response, and timeout.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/pluggable-auth-handler.js