InterceptingCall Class Reference
Public Member Functions
constructor (nextCall, requester)
cancelWithStatus (status, details)
getPeer ()
processPendingMessage ()
processPendingHalfClose ()
start (metadata, interceptingListener)
sendMessageWithContext (context, message)
sendMessage (message)
startRead ()
halfClose ()
Member Function Documentation
cancelWithStatus()
InterceptingCall::cancelWithStatus (status, details) [inline]
References status.
constructor()
InterceptingCall::constructor (nextCall, requester) [inline]
Indicates that metadata has been passed to the requester's start method but it has not been passed to the corresponding next callback
Message context for a pending message that is waiting for
Indicates that a message has been passed to the requester's sendMessage method but it has not been passed to the corresponding next callback
Indicates that a status was received but could not be propagated because a message was still being processed.
References _a, _b, _c, _d, defaultRequester, halfClose(), sendMessage(), and start.
getPeer()
InterceptingCall::getPeer () [inline]
halfClose()
InterceptingCall::halfClose () [inline]
processPendingHalfClose()
InterceptingCall::processPendingHalfClose () [inline]
processPendingMessage()
InterceptingCall::processPendingMessage () [inline]
sendMessage()
InterceptingCall::sendMessage (message) [inline]
References message, and sendMessageWithContext().
sendMessageWithContext()
InterceptingCall::sendMessageWithContext (context, message) [inline]
References context, message, and processPendingHalfClose().
start()
InterceptingCall::start (metadata, interceptingListener) [inline]
References _a, _b, _c, _d, call_interface_1, defaultListener, md, message, processPendingHalfClose(), processPendingMessage(), and status.
startRead()
InterceptingCall::startRead () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/client-interceptors.js