KeyIndex Class Reference
Public Member Functions
compare (a, b)
isDefinedOn (node)
indexedValueChanged (oldNode, newNode)
minPost ()
maxPost ()
makePost (indexValue, name)
toString ()
compare (a, b)
isDefinedOn (node)
indexedValueChanged (oldNode, newNode)
minPost ()
maxPost ()
makePost (indexValue, name)
toString ()
compare (a, b)
isDefinedOn (node)
indexedValueChanged (oldNode, newNode)
minPost ()
maxPost ()
makePost (indexValue, name)
toString ()
getCompare ()
getCompare ()
getCompare ()
Static Public Member Functions
static get __EMPTY_NODE ()
static set __EMPTY_NODE (val)
static get __EMPTY_NODE ()
static set __EMPTY_NODE (val)
static get __EMPTY_NODE ()
static set __EMPTY_NODE (val)
Member Function Documentation
__EMPTY_NODE() [1/6]
static get KeyIndex::__EMPTY_NODE () [inline], [static]
References __EMPTY_NODE().
__EMPTY_NODE() [2/6]
static get KeyIndex::__EMPTY_NODE () [inline], [static]
References __EMPTY_NODE().
__EMPTY_NODE() [3/6]
static get KeyIndex::__EMPTY_NODE () [inline], [static]
References __EMPTY_NODE().
__EMPTY_NODE() [4/6]
static set KeyIndex::__EMPTY_NODE (val) [inline], [static]
References __EMPTY_NODE().
__EMPTY_NODE() [5/6]
static set KeyIndex::__EMPTY_NODE (val) [inline], [static]
References __EMPTY_NODE().
__EMPTY_NODE() [6/6]
static set KeyIndex::__EMPTY_NODE (val) [inline], [static]
References __EMPTY_NODE().
compare() [1/3]
KeyIndex::compare (a, b) [inline]
References a, b, and nameCompare.
compare() [2/3]
KeyIndex::compare (a, b) [inline]
References a, b, and nameCompare.
compare() [3/3]
KeyIndex::compare (a, b) [inline]
References a, b, and nameCompare.
getCompare() [1/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
getCompare() [2/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
getCompare() [3/3]
Index::getCompare () [inline], [inherited]
Returns
A standalone comparison function for this index
References compare.
indexedValueChanged() [1/3]
KeyIndex::indexedValueChanged (oldNode, newNode) [inline]
indexedValueChanged() [2/3]
KeyIndex::indexedValueChanged (oldNode, newNode) [inline]
indexedValueChanged() [3/3]
KeyIndex::indexedValueChanged (oldNode, newNode) [inline]
isDefinedOn() [1/3]
KeyIndex::isDefinedOn (node) [inline]
References util.
isDefinedOn() [2/3]
KeyIndex::isDefinedOn (node) [inline]
References assertionError.
isDefinedOn() [3/3]
KeyIndex::isDefinedOn (node) [inline]
References assertionError.
makePost() [1/3]
KeyIndex::makePost (indexValue, name) [inline]
References __EMPTY_NODE(), and util.
makePost() [2/3]
KeyIndex::makePost (indexValue, name) [inline]
References __EMPTY_NODE(), and assert.
makePost() [3/3]
KeyIndex::makePost (indexValue, name) [inline]
References __EMPTY_NODE(), and assert.
maxPost() [1/3]
KeyIndex::maxPost () [inline]
References __EMPTY_NODE(), and MAX_NAME.
maxPost() [2/3]
KeyIndex::maxPost () [inline]
References __EMPTY_NODE(), and MAX_NAME.
maxPost() [3/3]
KeyIndex::maxPost () [inline]
References __EMPTY_NODE(), and MAX_NAME.
minPost() [1/3]
KeyIndex::minPost () [inline]
minPost() [2/3]
KeyIndex::minPost () [inline]
minPost() [3/3]
KeyIndex::minPost () [inline]
toString() [1/3]
KeyIndex::toString () [inline]
Returns
String representation for inclusion in a query spec
toString() [2/3]
KeyIndex::toString () [inline]
Returns
String representation for inclusion in a query spec
toString() [3/3]
KeyIndex::toString () [inline]
Returns
String representation for inclusion in a query spec
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js