BaseRequestConfigImpl Class Reference
Public Member Functions
constructor (config)
get method ()
get url ()
get headers ()
get data ()
get timeout ()
buildEntity (headers)
buildUrl ()
urlWithProtocol ()
Detailed Description
An adapter class with common functionality needed to extract options and entity data from a RequestConfig.
Member Function Documentation
buildEntity()
BaseRequestConfigImpl::buildEntity (headers) [inline]
References data(), hasEntity(), headers(), isEntityEnclosingRequest(), JSON, and validator.
buildUrl()
BaseRequestConfigImpl::buildUrl () [inline]
References $, a, data(), hasEntity(), isEntityEnclosingRequest(), method(), url(), urlWithProtocol(), and validator.
constructor()
BaseRequestConfigImpl::constructor (config) [inline]
References config.
data()
get BaseRequestConfigImpl::data () [inline]
References config.
headers()
get BaseRequestConfigImpl::headers () [inline]
References config.
method()
get BaseRequestConfigImpl::method () [inline]
References config.
timeout()
get BaseRequestConfigImpl::timeout () [inline]
References config.
url()
get BaseRequestConfigImpl::url () [inline]
References config.
urlWithProtocol()
BaseRequestConfigImpl::urlWithProtocol () [inline]
References https, and url().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/api-request.js