Completion Class Reference
Public Member Functions
constructor (yargs, usage, command, shim)
defaultCompletion (args, argv, current, done)
commandCompletions (completions, args, current)
optionCompletions (completions, args, argv, current)
choicesFromOptionsCompletions (completions, args, argv, current)
choicesFromPositionalsCompletions (completions, args, argv, current)
getPreviousArgChoices (args)
previousArgHasChoices (args)
argsContainKey (args, key, negable)
completeOptionKey (key, completions, current, negable)
customCompletion (args, argv, current, done)
getCompletion (args, done)
generateCompletionScript ($0, cmd)
registerFunction (fn)
setParsed (parsed)
Member Function Documentation
argsContainKey()
Completion::argsContainKey (args, key, negable) [inline]
References $, alias(), args, of, and s.
choicesFromOptionsCompletions()
Completion::choicesFromOptionsCompletions (completions, args, argv, current) [inline]
References args, c, g, getPreviousArgChoices(), and previousArgHasChoices().
choicesFromPositionalsCompletions()
Completion::choicesFromPositionalsCompletions (completions, args, argv, current) [inline]
References args, g, of, usage(), and yargs.
commandCompletions()
Completion::commandCompletions (completions, args, current) [inline]
References args, g, parseCommand(), usage(), and yargs.
completeOptionKey()
Completion::completeOptionKey (key, completions, current, negable) [inline]
References $, _a, _b, _c, _d, alias(), g, n, r, s, test, undefined, and usage().
constructor()
Completion::constructor (yargs, usage, command, shim) [inline]
References _a, _b, _c, command(), shim, usage(), and yargs.
customCompletion()
Completion::customCompletion (args, argv, current, done) [inline]
References args, assertNotStrictEqual(), defaultCompletion(), done, isFallbackCompletionFunction(), isPromise, isSyncCompletionFunction(), result, shim, and undefined.
defaultCompletion()
Completion::defaultCompletion (args, argv, current, done) [inline]
References args, choicesFromOptionsCompletions(), choicesFromPositionalsCompletions(), command(), commandCompletions(), done, i, isCommandBuilderCallback(), optionCompletions(), y, and yargs.
generateCompletionScript()
Completion::generateCompletionScript ($0, cmd) [inline]
References $, g, name, and shim.
getCompletion()
Completion::getCompletion (args, done) [inline]
References args, customCompletion(), defaultCompletion(), done, isPromise, and yargs.
getPreviousArgChoices()
Completion::getPreviousArgChoices (args) [inline]
References args, Array, filter, of, and yargs.
optionCompletions()
Completion::optionCompletions (completions, args, argv, current) [inline]
References args, completeOptionKey(), usage(), and yargs.
previousArgHasChoices()
Completion::previousArgHasChoices (args) [inline]
References args, getPreviousArgChoices(), and undefined.
registerFunction()
Completion::registerFunction (fn) [inline]
References fn.
setParsed()
Completion::setParsed (parsed) [inline]
The documentation for this class was generated from the following file:
backend/node_modules/yargs/build/lib/completion.js