ProjectManagementRequestHandler Class Reference
Public Member Functions
constructor (app)
listAndroidApps (parentResourceName)
listIosApps (parentResourceName)
listAppMetadata (parentResourceName)
createAndroidApp (parentResourceName, packageName, displayName)
createIosApp (parentResourceName, bundleId, displayName)
setDisplayName (resourceName, newDisplayName)
getAndroidShaCertificates (parentResourceName)
addAndroidShaCertificate (parentResourceName, certificate)
getConfig (parentResourceName)
getResource (parentResourceName)
deleteResource (resourceName)
pollRemoteOperationWithExponentialBackoff (operationResourceName)
invokeRequestHandler (method, path, requestData, apiVersion='v1')
Static Public Member Functions
static wrapAndRethrowHttpError (errStatusCode, errText)
Detailed Description
Class that provides mechanism to send requests to the Firebase project management backend endpoints.
Member Function Documentation
addAndroidShaCertificate()
ProjectManagementRequestHandler::addAndroidShaCertificate (parentResourceName, certificate) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the Android app that you want to add the given SHA certificate to.
References $, CERT_TYPE_API_MAP, then, and undefined.
constructor()
ProjectManagementRequestHandler::constructor (app) [inline]
Parameters
app - The app used to fetch access tokens to sign API requests. @constructor
References api_request_1, app, and https.
createAndroidApp()
ProjectManagementRequestHandler::createAndroidApp (parentResourceName, packageName, displayName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the project that you want to create the Android app within.
References $, assertServerResponse, pollRemoteOperationWithExponentialBackoff(), then, and validator.
createIosApp()
ProjectManagementRequestHandler::createIosApp (parentResourceName, bundleId, displayName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the project that you want to create the iOS app within.
References $, assertServerResponse, pollRemoteOperationWithExponentialBackoff(), then, and validator.
deleteResource()
ProjectManagementRequestHandler::deleteResource (resourceName) [inline]
Parameters
resourceName - Fully-qualified resource name of the entity that you want to delete.
References undefined.
getAndroidShaCertificates()
ProjectManagementRequestHandler::getAndroidShaCertificates (parentResourceName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the Android app whose SHA certificates you want to get.
References $, and invokeRequestHandler().
getConfig()
ProjectManagementRequestHandler::getConfig (parentResourceName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the app whose config you want to get.
References $, config, and invokeRequestHandler().
getResource()
ProjectManagementRequestHandler::getResource (parentResourceName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the entity that you want to get.
References invokeRequestHandler().
invokeRequestHandler()
ProjectManagementRequestHandler::invokeRequestHandler (method, path, requestData, apiVersion = 'v1') [inline]
Invokes the request handler with the provided request data.
References $, api_request_1, data, headers, method, path, PROJECT_MANAGEMENT_HEADERS, PROJECT_MANAGEMENT_TIMEOUT_MILLIS, request, response, timeout, url, and wrapAndRethrowHttpError().
listAndroidApps()
ProjectManagementRequestHandler::listAndroidApps (parentResourceName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the project whose Android apps you want to list.
References $, invokeRequestHandler(), and LIST_APPS_MAX_PAGE_SIZE.
listAppMetadata()
ProjectManagementRequestHandler::listAppMetadata (parentResourceName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the project whose iOS apps you want to list.
References $, invokeRequestHandler(), and LIST_APPS_MAX_PAGE_SIZE.
listIosApps()
ProjectManagementRequestHandler::listIosApps (parentResourceName) [inline]
Parameters
parentResourceName - Fully-qualified resource name of the project whose iOS apps you want to list.
References $, invokeRequestHandler(), and LIST_APPS_MAX_PAGE_SIZE.
pollRemoteOperationWithExponentialBackoff()
ProjectManagementRequestHandler::pollRemoteOperationWithExponentialBackoff (operationResourceName) [inline]
References api_request_1, invokeRequestHandler(), JSON, and wrapAndRethrowHttpError().
setDisplayName()
ProjectManagementRequestHandler::setDisplayName (resourceName, newDisplayName) [inline]
Parameters
resourceName - Fully-qualified resource name of the entity whose display name you want to set.
References $, then, and undefined.
wrapAndRethrowHttpError()
static ProjectManagementRequestHandler::wrapAndRethrowHttpError (errStatusCode, errText) [inline], [static]
References $, error_1, response, server, and Status.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/project-management/project-management-api-request-internal.js