ProjectConfig Class Reference
Public Member Functions
get multiFactorConfig ()
get recaptchaConfig ()
constructor (response)
toJSON ()
Static Public Member Functions
static validate (request)
static buildServerRequest (configOptions)
Detailed Description
Represents a project configuration.
Member Function Documentation
buildServerRequest()
static ProjectConfig::buildServerRequest (configOptions) [inline], [static]
Build the corresponding server request for a UpdateProjectConfigRequest object.
Parameters
configOptions - The properties to convert to a server request.
Returns
The equivalent server request.
References auth_config_1, request, and validate().
constructor()
ProjectConfig::constructor (response) [inline]
The Project Config object constructor.
Parameters
response - The server side response used to initialize the Project Config object. @constructor
References auth_config_1, and response.
multiFactorConfig()
get ProjectConfig::multiFactorConfig () [inline]
The multi-factor auth configuration. Here is the caller graph for this function:
recaptchaConfig()
get ProjectConfig::recaptchaConfig () [inline]
The reCAPTCHA configuration. Here is the caller graph for this function:
toJSON()
ProjectConfig::toJSON () [inline]
Returns a JSON-serializable representation of this object.
Returns
A JSON-serializable representation of this object.
References deep_copy_1, json, multiFactorConfig(), and recaptchaConfig().
validate()
static ProjectConfig::validate (request) [inline], [static]
Validates a project config options object. Throws an error on failure.
Parameters
request - The project config options object to validate.
References a, auth_config_1, error_1, is, multiFactorConfig(), not, recaptchaConfig(), request, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/project-config.js