OngoingCallPromise Class Reference
Public Member Functions
constructor (callback)
cancel ()
call (func, argument)
Private Member Functions
constructor ()
Member Function Documentation
call()
OngoingCall::call (func, argument) [inline], [inherited]
Call calls the specified function. Result will be used to fulfill the promise.
Parameters
{SimpleCallbackFunction} func A function for an API call.
{Object} argument A request object.
References callback, func, googleError_1, next(), Promise, response, and setImmediate.
cancel()
OngoingCall::cancel () [inline], [inherited]
Cancels the ongoing promise.
References callback, error, googleError_1, and status_1.
constructor() [1/2]
OngoingCall::constructor (callback) [inline], [inherited]
References callback.
constructor() [2/2]
OngoingCallPromise::constructor () [inline], [private]
GaxPromise is GRPCCallbackWrapper, but it holds a promise when the API call finishes. @constructor
References callback, OngoingCall::cancel(), googleError_1, next(), Promise, reject(), resolve, response, and undefined.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/call.js