FirebaseMessagingError Class Reference
Public Member Functions
constructor (info, message)
constructor (codePrefix, code, message)
constructor (errorInfo)
hasCode (code)
get code ()
get message ()
toJSON ()
Static Public Member Functions
static fromServerError (serverErrorCode, message, rawServerResponse)
static fromTopicManagementServerError (serverErrorCode, message, rawServerResponse)
Detailed Description
Firebase Messaging error code structure. This extends PrefixedFirebaseError.
Member Function Documentation
code()
get FirebaseError::code () [inline], [inherited]
Returns
The error code.
constructor() [1/3]
FirebaseError::constructor (errorInfo) [inline], [inherited]
Parameters
errorInfo - The error information (code and message). @constructor
constructor() [2/3]
FirebaseMessagingError::constructor (info, message) [inline]
Parameters
info - The error code info.
message - The error message. This will override the default message if provided. @constructor
References FirebaseError::message().
constructor() [3/3]
PrefixedFirebaseError::constructor (codePrefix, code, message) [inline], [inherited]
Parameters
codePrefix - The prefix to apply to the error code.
code - The error code.
message - The error message. @constructor
References $, FirebaseError::code(), and FirebaseError::message().
fromServerError()
static FirebaseMessagingError::fromServerError (serverErrorCode, message, rawServerResponse) [inline], [static]
Creates the developer-facing error corresponding to the backend error code.
Parameters
serverErrorCode - The server error code.
[message] The error message. The default message is used if not provided.
[rawServerResponse] The error's raw server response.
Returns
The corresponding developer-facing error.
References deep_copy_1, e, error, FirebaseMessagingError, FirebaseError::message(), MESSAGING_SERVER_TO_CLIENT_CODE, response, and server.
fromTopicManagementServerError()
static FirebaseMessagingError::fromTopicManagementServerError (serverErrorCode, message, rawServerResponse) [inline], [static]
References deep_copy_1, e, error, FirebaseMessagingError, FirebaseError::message(), response, server, and TOPIC_MGT_SERVER_TO_CLIENT_CODE.
hasCode()
PrefixedFirebaseError::hasCode (code) [inline], [inherited]
Allows the error type to be checked without needing to know implementation details of the code prefixing.
Parameters
code - The non-prefixed error code to test against.
Returns
True if the code matches, false otherwise.
References $, and FirebaseError::code().
message()
get FirebaseError::message () [inline], [inherited]
Returns
The error message.
toJSON()
FirebaseError::toJSON () [inline], [inherited]
Returns
The object representation of the error.
References FirebaseError::code(), and FirebaseError::message().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/utils/error.js