EventEmitter Class Reference
Public Member Functions
constructor (allowedEvents_)
trigger (eventType,...varArgs)
on (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
constructor (allowedEvents_)
trigger (eventType,...varArgs)
on (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
constructor (allowedEvents_)
trigger (eventType,...varArgs)
on (eventType, callback, context)
off (eventType, callback, context)
validateEventType_ (eventType)
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Base class to be used if you want to emit events. Call the constructor with the set of allowed event names.
Member Function Documentation
constructor() [1/3]
EventEmitter::constructor (allowedEvents_) [inline]
References Array, and util.
constructor() [2/3]
EventEmitter::constructor (allowedEvents_) [inline]
References Array, and assert.
constructor() [3/3]
EventEmitter::constructor (allowedEvents_) [inline]
References Array, and assert.
off() [1/3]
EventEmitter::off (eventType, callback, context) [inline]
References callback, context, i, and validateEventType_().
off() [2/3]
EventEmitter::off (eventType, callback, context) [inline]
References callback, context, i, and validateEventType_().
off() [3/3]
EventEmitter::off (eventType, callback, context) [inline]
References callback, context, i, and validateEventType_().
on() [1/3]
EventEmitter::on (eventType, callback, context) [inline]
References callback, context, and validateEventType_().
on() [2/3]
EventEmitter::on (eventType, callback, context) [inline]
References callback, context, and validateEventType_().
on() [3/3]
EventEmitter::on (eventType, callback, context) [inline]
References callback, context, and validateEventType_().
trigger() [1/3]
EventEmitter::trigger (eventType, ...) [inline]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [2/3]
EventEmitter::trigger (eventType, ...) [inline]
To be called by derived classes to trigger events.
References Array, context, and i.
trigger() [3/3]
EventEmitter::trigger (eventType, ...) [inline]
To be called by derived classes to trigger events.
References Array, context, and i.
validateEventType_() [1/3]
EventEmitter::validateEventType_ (eventType) [inline]
References et, and util.
validateEventType_() [2/3]
EventEmitter::validateEventType_ (eventType) [inline]
References assert, and et.
validateEventType_() [3/3]
EventEmitter::validateEventType_ (eventType) [inline]
References assert, and et.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js