StringSource Class Reference
Public Member Functions
constructor (str)
readCh ()
readChAt (index)
readStr (n, from)
readUpto (stopStr)
readUptoCloseTag (stopStr)
readFromBuffer (n, updateIndex)
updateBufferBoundary (n=1)
canRead (n)
Member Function Documentation
canRead()
StringSource::canRead (n) [inline]
References buffer, n, and startIndex().
constructor()
StringSource::constructor (str) [inline]
References buffer, startIndex(), and str().
readCh()
StringSource::readCh () [inline]
References buffer, and startIndex().
readChAt()
StringSource::readChAt (index) [inline]
References buffer, index, and startIndex().
readFromBuffer()
StringSource::readFromBuffer (n, updateIndex) [inline]
References buffer, n, startIndex(), and updateBufferBoundary().
readStr()
StringSource::readStr (n, from) [inline]
References buffer, n, and startIndex().
readUpto()
StringSource::readUpto (stopStr) [inline]
References buffer, end, i, j, match, of, result, source, and startIndex().
readUptoCloseTag()
StringSource::readUptoCloseTag (stopStr) [inline]
References buffer, end, i, j, match, of, result, source, and startIndex().
updateBufferBoundary()
StringSource::updateBufferBoundary (n = 1) [inline]
References n, and startIndex().
The documentation for this class was generated from the following file:
backend/node_modules/fast-xml-parser/src/v5/inputSource/StringSource.js