DocumentSnapshot Class Reference
Public Member Functions
 DocumentSnapshot#exists
True if the document exists.
@type {boolean}
@readonly
get exists ()
 DocumentSnapshot#ref
A [DocumentReference]DocumentReference for the document stored in this snapshot.
@type {DocumentReference}
@readonly
get ref ()
 DocumentSnapshot#id
The ID of the document for which this DocumentSnapshot contains data.
@type {string}
@readonly
get id ()
 DocumentSnapshot#createTime
The time the document was created. Undefined for documents that don't exist.
@type {Timestamp|undefined}
@readonly
get createTime ()
 DocumentSnapshot#updateTime
The time the document was last updated (at the time the snapshot was generated). Undefined for documents that don't exist.
@type {Timestamp|undefined}
@readonly
get updateTime ()
Private Member Functions
constructor (ref, _fieldsProto, readTime, createTime, updateTime)
Static Private Member Functions
static fromObject (ref, obj)
static fromUpdateMap (ref, data)
DocumentSnapshot#readTime
The time this snapshot was read.
@type {Timestamp}
@readonly
protoField (field)
toWriteProto ()
toDocumentProto ()
get readTime ()
data ()
get (field)
isEqual (other)
Detailed Description
A DocumentSnapshot is an immutable representation for a document in a Firestore database. The data can be extracted with [data()]DocumentSnapshot#data or [get(fieldPath)]DocumentSnapshot#get to get a specific field.
For a DocumentSnapshot that points to a non-existing document, any data access will return 'undefined'. You can use the [exists]DocumentSnapshot#exists property to explicitly verify a document's existence.
Member Function Documentation
constructor()
DocumentSnapshot::constructor (ref, _fieldsProto, readTime, createTime, updateTime) [inline], [private]
References createTime(), readTime(), ref(), and updateTime().
createTime()
get DocumentSnapshot::createTime () [inline]
data()
DocumentSnapshot::data () [inline]
References createTime(), document_reference_1, obj, of, prop, QueryDocumentSnapshot, readTime(), ref(), types_1, undefined, and updateTime().
exists()
get DocumentSnapshot::exists () [inline]
References undefined.
fromObject()
static DocumentSnapshot::fromObject (ref, obj) [inline], [static], [private]
Creates a DocumentSnapshot from an object.
References DocumentSnapshot, obj, ref(), and serializer.
fromUpdateMap()
static DocumentSnapshot::fromUpdateMap (ref, data) [inline], [static], [private]
Creates a DocumentSnapshot from an UpdateMap.
This methods expands the top-level field paths in a JavaScript map and turns { foo.bar : foobar } into { foo { bar : foobar }} Merges 'value' at the field path specified by the path array into 'target'.
References assert, data(), DocumentSnapshot, field_value_1, merge, of, path, ref(), res, serializer, undefined, util_1, and value.
get()
DocumentSnapshot::get (field) [inline]
References path_1, protoField(), and undefined.
id()
get DocumentSnapshot::id () [inline]
isEqual()
DocumentSnapshot::isEqual (other) [inline]
Returns true if the document's data and path in this DocumentSnapshot is equal to the provided value.
Parameters
{*} other The value to compare against.
Returns
{boolean} true if this DocumentSnapshot is equal to the provided value.
References deepEqual, and isEqual().
protoField()
DocumentSnapshot::protoField (field) [inline], [private]
Retrieves the field specified by 'fieldPath' in its Protobuf JS representation.
References path_1, and undefined.
readTime()
get DocumentSnapshot::readTime () [inline]
References undefined.
ref()
get DocumentSnapshot::ref () [inline]
toDocumentProto()
DocumentSnapshot::toDocumentProto () [inline], [private]
Convert a document snapshot to the Firestore 'Document' proto.
References _a, _b, createTime(), name, and updateTime().
toWriteProto()
DocumentSnapshot::toWriteProto () [inline], [private]
Convert a document snapshot to the Firestore 'Write' proto.
References name, and update.
updateTime()
get DocumentSnapshot::updateTime () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/document.js