QueryUtil Class Reference
Public Member Functions
_getResponse (query, transactionOrReadTime, retryWithCursor=true, explainOptions)
_isPermanentRpcError (err, methodName)
_hasRetryTimedOut (methodName, startTime)
stream (query)
_stream (query, transactionOrReadTime, retryWithCursor=true, explainOptions)
Private Member Functions
constructor (_firestore, _queryOptions, _serializer)
Member Function Documentation
_getResponse()
QueryUtil::_getResponse (query, transactionOrReadTime, retryWithCursor = true, explainOptions) [inline]
References _stream(), data, on, Promise, query, reject(), resolve, result, types_1, undefined, and util_1.
_hasRetryTimedOut()
QueryUtil::_hasRetryTimedOut (methodName, startTime) [inline]
References util_1.
_isPermanentRpcError()
QueryUtil::_isPermanentRpcError (err, methodName) [inline]
References util_1.
_stream()
QueryUtil::_stream (query, transactionOrReadTime, retryWithCursor = true, explainOptions) [inline]
References $, _a, _firestore, async, callback, constants_1, document_1, error, if(), logger_1, objectMode, or, proto, query, query_profile_1, request, retryable, stream, stream_1, timestamp_1, trace_util_1, transform, undefined, and util_1.
constructor()
QueryUtil::constructor (_firestore, _queryOptions, _serializer) [inline], [private]
References _firestore.
stream()
QueryUtil::stream (query) [inline]
References callback, chunk(), e, encoding, objectMode, query, stream_1, transform, types_1, and undefined.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/reference/query-util.js