DeferredValueProvider Class Reference
Public Member Functions
constructor (syncTree, path)
getImmediateChild (childName)
node ()
constructor (syncTree, path)
getImmediateChild (childName)
node ()
constructor (syncTree, path)
getImmediateChild (childName)
node ()
Member Function Documentation
constructor() [1/3]
DeferredValueProvider::constructor (syncTree, path) [inline]
References path.
constructor() [2/3]
DeferredValueProvider::constructor (syncTree, path) [inline]
References path.
constructor() [3/3]
DeferredValueProvider::constructor (syncTree, path) [inline]
References path.
getImmediateChild() [1/3]
DeferredValueProvider::getImmediateChild (childName) [inline]
References pathChild().
getImmediateChild() [2/3]
DeferredValueProvider::getImmediateChild (childName) [inline]
References pathChild().
getImmediateChild() [3/3]
DeferredValueProvider::getImmediateChild (childName) [inline]
References pathChild().
node() [1/3]
DeferredValueProvider::node () [inline]
References syncTreeCalcCompleteEventCache().
node() [2/3]
DeferredValueProvider::node () [inline]
References syncTreeCalcCompleteEventCache().
node() [3/3]
DeferredValueProvider::node () [inline]
References syncTreeCalcCompleteEventCache().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js