WebSocketConnection Class Reference
Public Member Functions
constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId)
open (onMessage, onDisconnect)
start ()
markConnectionHealthy ()
appendFrame_ (data)
handleNewFrameCount_ (frameCount)
extractFrameCount_ (data)
handleIncomingFrame (mess)
send (data)
shutdown_ ()
onClosed_ ()
close ()
resetKeepAlive ()
sendString_ (str)
constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId)
open (onMessage, onDisconnect)
start ()
markConnectionHealthy ()
appendFrame_ (data)
handleNewFrameCount_ (frameCount)
extractFrameCount_ (data)
handleIncomingFrame (mess)
send (data)
shutdown_ ()
onClosed_ ()
close ()
resetKeepAlive ()
sendString_ (str)
constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId)
open (onMessage, onDisconnect)
start ()
markConnectionHealthy ()
appendFrame_ (data)
handleNewFrameCount_ (frameCount)
extractFrameCount_ (data)
handleIncomingFrame (mess)
send (data)
shutdown_ ()
onClosed_ ()
close ()
resetKeepAlive ()
sendString_ (str)
Static Public Member Functions
static connectionURL_ (repoInfo, transportSessionId, lastSessionId, appCheckToken, applicationId)
static forceDisallow ()
static isAvailable ()
static previouslyFailed ()
static connectionURL_ (repoInfo, transportSessionId, lastSessionId, appCheckToken, applicationId)
static forceDisallow ()
static isAvailable ()
static previouslyFailed ()
static connectionURL_ (repoInfo, transportSessionId, lastSessionId, appCheckToken, applicationId)
static forceDisallow ()
static isAvailable ()
static previouslyFailed ()
Detailed Description
Create a new websocket connection with the given callbacks.
Member Function Documentation
appendFrame_() [1/3]
WebSocketConnection::appendFrame_ (data) [inline]
References data, and util.
appendFrame_() [2/3]
WebSocketConnection::appendFrame_ (data) [inline]
References data, and jsonEval.
appendFrame_() [3/3]
WebSocketConnection::appendFrame_ (data) [inline]
References data, and jsonEval.
close() [1/3]
WebSocketConnection::close () [inline]
External-facing close handler. Close the websocket and kill the connection.
References shutdown_().
close() [2/3]
WebSocketConnection::close () [inline]
External-facing close handler. Close the websocket and kill the connection.
References shutdown_().
close() [3/3]
WebSocketConnection::close () [inline]
External-facing close handler. Close the websocket and kill the connection.
References shutdown_().
connectionURL_() [1/3]
static WebSocketConnection::connectionURL_ (repoInfo, transportSessionId, lastSessionId, appCheckToken, applicationId) [inline], [static]
Parameters
repoInfo - The info for the websocket endpoint.
transportSessionId - Optional transportSessionId if this is connecting to an existing transport session
lastSessionId - Optional lastSessionId if there was a previous connection
Returns
connection url
References APP_CHECK_TOKEN_PARAM, APPLICATION_ID_PARAM, FORGE_DOMAIN_RE, FORGE_REF, LAST_SESSION_PARAM, location, PROTOCOL_VERSION, REFERER_PARAM, repoInfoConnectionURL(), TRANSPORT_SESSION_PARAM, util, VERSION_PARAM, and WEBSOCKET.
connectionURL_() [2/3]
static WebSocketConnection::connectionURL_ (repoInfo, transportSessionId, lastSessionId, appCheckToken, applicationId) [inline], [static]
Parameters
repoInfo - The info for the websocket endpoint.
transportSessionId - Optional transportSessionId if this is connecting to an existing transport session
lastSessionId - Optional lastSessionId if there was a previous connection
Returns
connection url
References APP_CHECK_TOKEN_PARAM, APPLICATION_ID_PARAM, FORGE_DOMAIN_RE, FORGE_REF, isNodeSdk, LAST_SESSION_PARAM, location, PROTOCOL_VERSION, REFERER_PARAM, repoInfoConnectionURL(), TRANSPORT_SESSION_PARAM, VERSION_PARAM, and WEBSOCKET.
connectionURL_() [3/3]
static WebSocketConnection::connectionURL_ (repoInfo, transportSessionId, lastSessionId, appCheckToken, applicationId) [inline], [static]
Parameters
repoInfo - The info for the websocket endpoint.
transportSessionId - Optional transportSessionId if this is connecting to an existing transport session
lastSessionId - Optional lastSessionId if there was a previous connection
Returns
connection url
References APP_CHECK_TOKEN_PARAM, APPLICATION_ID_PARAM, FORGE_DOMAIN_RE, FORGE_REF, isNodeSdk, LAST_SESSION_PARAM, location, PROTOCOL_VERSION, REFERER_PARAM, repoInfoConnectionURL(), TRANSPORT_SESSION_PARAM, VERSION_PARAM, and WEBSOCKET.
constructor() [1/3]
WebSocketConnection::constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId) [inline]
Parameters
connId identifier for this transport
repoInfo The info for the websocket endpoint.
applicationId The Firebase App ID for this project.
appCheckToken The App Check Token for this client.
authToken The Auth Token for this client.
transportSessionId Optional transportSessionId if this is connecting to an existing transport session
lastSessionId Optional lastSessionId if there was a previous connection
References connectionURL_(), logWrapper, and statsManagerGetCollection().
constructor() [2/3]
WebSocketConnection::constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId) [inline]
Parameters
connId identifier for this transport
repoInfo The info for the websocket endpoint.
applicationId The Firebase App ID for this project.
appCheckToken The App Check Token for this client.
authToken The Auth Token for this client.
transportSessionId Optional transportSessionId if this is connecting to an existing transport session
lastSessionId Optional lastSessionId if there was a previous connection
References connectionURL_(), logWrapper, and statsManagerGetCollection().
constructor() [3/3]
WebSocketConnection::constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId) [inline]
Parameters
connId identifier for this transport
repoInfo The info for the websocket endpoint.
applicationId The Firebase App ID for this project.
appCheckToken The App Check Token for this client.
authToken The Auth Token for this client.
transportSessionId Optional transportSessionId if this is connecting to an existing transport session
lastSessionId Optional lastSessionId if there was a previous connection
References connectionURL_(), logWrapper, and statsManagerGetCollection().
extractFrameCount_() [1/3]
WebSocketConnection::extractFrameCount_ (data) [inline]
Attempts to parse a frame count out of some text. If it can't, assumes a value of 1
Returns
Any remaining data to be process, or null if there is none
References data, handleNewFrameCount_(), isNaN, and util.
extractFrameCount_() [2/3]
WebSocketConnection::extractFrameCount_ (data) [inline]
Attempts to parse a frame count out of some text. If it can't, assumes a value of 1
Returns
Any remaining data to be process, or null if there is none
References assert, data, handleNewFrameCount_(), and isNaN.
extractFrameCount_() [3/3]
WebSocketConnection::extractFrameCount_ (data) [inline]
Attempts to parse a frame count out of some text. If it can't, assumes a value of 1
Returns
Any remaining data to be process, or null if there is none
References assert, data, handleNewFrameCount_(), and isNaN.
forceDisallow() [1/3]
static WebSocketConnection::forceDisallow () [inline], [static]
forceDisallow() [2/3]
static WebSocketConnection::forceDisallow () [inline], [static]
forceDisallow() [3/3]
static WebSocketConnection::forceDisallow () [inline], [static]
handleIncomingFrame() [1/3]
WebSocketConnection::handleIncomingFrame (mess) [inline]
Process a websocket frame that has arrived from the server.
Parameters
mess - The frame data
References appendFrame_(), data, extractFrameCount_(), and resetKeepAlive().
handleIncomingFrame() [2/3]
WebSocketConnection::handleIncomingFrame (mess) [inline]
Process a websocket frame that has arrived from the server.
Parameters
mess - The frame data
References appendFrame_(), data, extractFrameCount_(), and resetKeepAlive().
handleIncomingFrame() [3/3]
WebSocketConnection::handleIncomingFrame (mess) [inline]
Process a websocket frame that has arrived from the server.
Parameters
mess - The frame data
References appendFrame_(), data, extractFrameCount_(), and resetKeepAlive().
handleNewFrameCount_() [1/3]
WebSocketConnection::handleNewFrameCount_ (frameCount) [inline]
Parameters
frameCount - The number of frames we are expecting from the server
handleNewFrameCount_() [2/3]
WebSocketConnection::handleNewFrameCount_ (frameCount) [inline]
Parameters
frameCount - The number of frames we are expecting from the server
handleNewFrameCount_() [3/3]
WebSocketConnection::handleNewFrameCount_ (frameCount) [inline]
Parameters
frameCount - The number of frames we are expecting from the server
isAvailable() [1/3]
static WebSocketConnection::isAvailable () [inline], [static]
References WebSocketImpl.
isAvailable() [2/3]
static WebSocketConnection::isAvailable () [inline], [static]
References WebSocketImpl.
isAvailable() [3/3]
static WebSocketConnection::isAvailable () [inline], [static]
References WebSocketImpl.
markConnectionHealthy() [1/3]
WebSocketConnection::markConnectionHealthy () [inline]
References PersistentStorage.
markConnectionHealthy() [2/3]
WebSocketConnection::markConnectionHealthy () [inline]
References PersistentStorage.
markConnectionHealthy() [3/3]
WebSocketConnection::markConnectionHealthy () [inline]
References PersistentStorage.
onClosed_() [1/3]
WebSocketConnection::onClosed_ () [inline]
References shutdown_().
onClosed_() [2/3]
WebSocketConnection::onClosed_ () [inline]
References shutdown_().
onClosed_() [3/3]
WebSocketConnection::onClosed_ () [inline]
References shutdown_().
open() [1/3]
WebSocketConnection::open (onMessage, onDisconnect) [inline]
Parameters
onMessage - Callback when messages arrive
onDisconnect - Callback with connection lost.
References $, e, env, error, handleIncomingFrame(), headers, m, onClosed_(), PersistentStorage, process, PROTOCOL_VERSION, proxy, SDK_VERSION, util, and WebSocketImpl.
open() [2/3]
WebSocketConnection::open (onMessage, onDisconnect) [inline]
Parameters
onMessage - Callback when messages arrive
onDisconnect - Callback with connection lost.
References $, e, env, error, handleIncomingFrame(), headers, isNodeSdk, m, onClosed_(), PersistentStorage, process, PROTOCOL_VERSION, proxy, SDK_VERSION, and WebSocketImpl.
open() [3/3]
WebSocketConnection::open (onMessage, onDisconnect) [inline]
Parameters
onMessage - Callback when messages arrive
onDisconnect - Callback with connection lost.
References $, e, env, error, handleIncomingFrame(), headers, isNodeSdk, m, onClosed_(), PersistentStorage, process, PROTOCOL_VERSION, proxy, SDK_VERSION, and WebSocketImpl.
previouslyFailed() [1/3]
static WebSocketConnection::previouslyFailed () [inline], [static]
Returns true if we previously failed to connect with this transport.
References PersistentStorage.
previouslyFailed() [2/3]
static WebSocketConnection::previouslyFailed () [inline], [static]
Returns true if we previously failed to connect with this transport.
References PersistentStorage.
previouslyFailed() [3/3]
static WebSocketConnection::previouslyFailed () [inline], [static]
Returns true if we previously failed to connect with this transport.
References PersistentStorage.
resetKeepAlive() [1/3]
WebSocketConnection::resetKeepAlive () [inline]
Kill the current keepalive timer and start a new one, to ensure that it always fires N seconds after the last activity.
References resetKeepAlive(), sendString_(), and WEBSOCKET_KEEPALIVE_INTERVAL.
resetKeepAlive() [2/3]
WebSocketConnection::resetKeepAlive () [inline]
Kill the current keepalive timer and start a new one, to ensure that it always fires N seconds after the last activity.
References resetKeepAlive(), sendString_(), and WEBSOCKET_KEEPALIVE_INTERVAL.
resetKeepAlive() [3/3]
WebSocketConnection::resetKeepAlive () [inline]
Kill the current keepalive timer and start a new one, to ensure that it always fires N seconds after the last activity.
References resetKeepAlive(), sendString_(), and WEBSOCKET_KEEPALIVE_INTERVAL.
send() [1/3]
WebSocketConnection::send (data) [inline]
Send a message to the server
Parameters
data - The JSON object to transmit
References data, dataStr, i, resetKeepAlive(), sendString_(), splitStringBySize, and WEBSOCKET_MAX_FRAME_SIZE.
send() [2/3]
WebSocketConnection::send (data) [inline]
Send a message to the server
Parameters
data - The JSON object to transmit
References data, dataStr, i, resetKeepAlive(), sendString_(), splitStringBySize, stringify, and WEBSOCKET_MAX_FRAME_SIZE.
send() [3/3]
WebSocketConnection::send (data) [inline]
Send a message to the server
Parameters
data - The JSON object to transmit
References data, dataStr, i, resetKeepAlive(), sendString_(), splitStringBySize, stringify, and WEBSOCKET_MAX_FRAME_SIZE.
sendString_() [1/3]
WebSocketConnection::sendString_ (str) [inline]
Send a string over the websocket.
Parameters
str - String to send.
References e, onClosed_(), and str().
sendString_() [2/3]
WebSocketConnection::sendString_ (str) [inline]
Send a string over the websocket.
Parameters
str - String to send.
References e, onClosed_(), and str().
sendString_() [3/3]
WebSocketConnection::sendString_ (str) [inline]
Send a string over the websocket.
Parameters
str - String to send.
References e, onClosed_(), and str().
shutdown_() [1/3]
WebSocketConnection::shutdown_ () [inline]
shutdown_() [2/3]
WebSocketConnection::shutdown_ () [inline]
shutdown_() [3/3]
WebSocketConnection::shutdown_ () [inline]
start() [1/3]
WebSocketConnection::start () [inline]
No-op for websockets, we don't need to do anything once the connection is confirmed as open
start() [2/3]
WebSocketConnection::start () [inline]
No-op for websockets, we don't need to do anything once the connection is confirmed as open
start() [3/3]
WebSocketConnection::start () [inline]
No-op for websockets, we don't need to do anything once the connection is confirmed as open
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js