TreeContainer Class Reference
Public Member Functions
constructor (t=function(t, e) { if(t< e) return -1;if(t > e) return 1;return 0;}, e=false)
R (t, e)
K (t, e)
L (t, e)
k (t, e)
P (t)
S (t)
U (t)
j (t)
q (t, e, s)
H (t, e)
clear ()
updateKeyByIterator (t, e)
eraseElementByPos (t)
eraseElementByKey (t)
eraseElementByIterator (t)
getHeight ()
constructor ()
get length ()
size ()
empty ()
Member Function Documentation
clear()
TreeContainer::clear () [inline]
References C, m, undefined, and v.
constructor() [1/2]
Base::constructor () [inline], [inherited]
References m.
constructor() [2/2]
TreeContainer::constructor (t = function(t, e) { if (t < e) return -1; if (t > e) return 1; return 0; }, e = false) [inline]
References e, and t.
empty()
Base::empty () [inline], [inherited]
References m.
eraseElementByIterator()
TreeContainer::eraseElementByIterator (t) [inline]
References C, e, i, S, s, t, throwIteratorAccessError(), and undefined.
eraseElementByKey()
TreeContainer::eraseElementByKey (t) [inline]
References C, e, H(), m, S, t, and v.
eraseElementByPos()
TreeContainer::eraseElementByPos (t) [inline]
References e, m, S, t, and U.
getHeight()
TreeContainer::getHeight () [inline]
References m, t, and v.
H()
TreeContainer::H (t, e) [inline]
References A(), C, e, s, and t.
j()
TreeContainer::j (t) [inline]
References C, e, i, s, t, and v.
K()
TreeContainer::K (t, e) [inline]
References A(), C, e, i, s, and t.
k()
TreeContainer::k (t, e) [inline]
References A(), C, e, i, s, and t.
L()
TreeContainer::L (t, e) [inline]
References A(), C, e, i, s, and t.
length()
get Base::length () [inline], [inherited]
References m.
P()
TreeContainer::P (t) [inline]
References C, e, s, t, and v.
q()
TreeContainer::q (t, e, s) [inline]
References A(), C, e, i, j, m, n, r, s, t, undefined, and v.
R()
TreeContainer::R (t, e) [inline]
References A(), C, e, i, s, and t.
S()
TreeContainer::S (t) [inline]
References C, clear(), e, i, m, P, s, t, undefined, and v.
size()
Base::size () [inline], [inherited]
References m.
U()
TreeContainer::U (t) [inline]
References e, h, i, n, r, s, t, undefined, and v.
updateKeyByIterator()
TreeContainer::updateKeyByIterator (t, e) [inline]
References A(), C, e, i, m, r, s, t, and throwIteratorAccessError().
The documentation for this class was generated from the following file:
backend/node_modules/@js-sdsl/ordered-map/dist/cjs/index.js