Client Class Reference
Public Member Functions
constructor (address, credentials, options={})
close ()
getChannel ()
waitForReady (deadline, callback)
checkOptionalUnaryResponseArguments (arg1, arg2, arg3)
makeUnaryRequest (method, serialize, deserialize, argument, metadata, options, callback)
makeClientStreamRequest (method, serialize, deserialize, metadata, options, callback)
checkMetadataAndOptions (arg1, arg2)
makeServerStreamRequest (method, serialize, deserialize, argument, metadata, options)
makeBidiStreamRequest (method, serialize, deserialize, metadata, options)
Detailed Description
A generic gRPC client. Primarily useful as a base class for all generated clients.
Member Function Documentation
checkMetadataAndOptions()
Client::checkMetadataAndOptions (arg1, arg2) [inline]
References metadata_1.
checkOptionalUnaryResponseArguments()
Client::checkOptionalUnaryResponseArguments (arg1, arg2, arg3) [inline]
References callback, isFunction, and metadata_1.
close()
Client::close () [inline]
References CHANNEL_SYMBOL.
constructor()
Client::constructor (address, credentials, options = {}) [inline]
getChannel()
Client::getChannel () [inline]
References CHANNEL_SYMBOL.
makeBidiStreamRequest()
Client::makeBidiStreamRequest (method, serialize, deserialize, metadata, options) [inline]
References _a, _b, call, call_1, CALL_INVOCATION_TRANSFORMER_SYMBOL, CHANNEL_SYMBOL, client_interceptors_1, constants_1, getErrorStackString(), INTERCEPTOR_PROVIDER_SYMBOL, INTERCEPTOR_SYMBOL, message, method, path, serialize, status, and stream.
makeClientStreamRequest()
Client::makeClientStreamRequest (method, serialize, deserialize, metadata, options, callback) [inline]
References _a, _b, call, call_1, CALL_INVOCATION_TRANSFORMER_SYMBOL, callback, CHANNEL_SYMBOL, client_interceptors_1, constants_1, getErrorStackString(), INTERCEPTOR_PROVIDER_SYMBOL, INTERCEPTOR_SYMBOL, message, method, path, serialize, and status.
makeServerStreamRequest()
Client::makeServerStreamRequest (method, serialize, deserialize, argument, metadata, options) [inline]
References _a, _b, call, call_1, CALL_INVOCATION_TRANSFORMER_SYMBOL, CHANNEL_SYMBOL, client_interceptors_1, constants_1, getErrorStackString(), INTERCEPTOR_PROVIDER_SYMBOL, INTERCEPTOR_SYMBOL, message, method, path, serialize, status, and stream.
makeUnaryRequest()
Client::makeUnaryRequest (method, serialize, deserialize, argument, metadata, options, callback) [inline]
References _a, _b, call, call_1, CALL_INVOCATION_TRANSFORMER_SYMBOL, callback, CHANNEL_SYMBOL, checkOptionalUnaryResponseArguments(), client_interceptors_1, constants_1, getErrorStackString(), INTERCEPTOR_PROVIDER_SYMBOL, INTERCEPTOR_SYMBOL, message, method, path, serialize, and status.
waitForReady()
Client::waitForReady (deadline, callback) [inline]
References callback, CHANNEL_SYMBOL, connectivity_state_1, e, and setImmediate.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/client.js