Merge Class Reference
Public Member Functions
constructor (source, path, children)
operationForChild (childName)
toString ()
constructor (source, path, children)
operationForChild (childName)
toString ()
constructor (source, path, children)
operationForChild (childName)
toString ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Member Function Documentation
constructor() [1/3]
Merge::constructor (source, path, children) [inline]
@inheritDoc
Parameters
source @inheritDoc
path @inheritDoc
children @inheritDoc
References path, source, and type.
constructor() [2/3]
Merge::constructor (source, path, children) [inline]
@inheritDoc
Parameters
source @inheritDoc
path @inheritDoc
children @inheritDoc
References path, source, and type.
constructor() [3/3]
Merge::constructor (source, path, children) [inline]
@inheritDoc
Parameters
source @inheritDoc
path @inheritDoc
children @inheritDoc
References path, source, and type.
operationForChild() [1/3]
Merge::operationForChild (childName) [inline]
References newEmptyPath(), path, pathGetFront(), pathIsEmpty(), pathPopFront(), source, and util.
operationForChild() [2/3]
Merge::operationForChild (childName) [inline]
References assert, newEmptyPath(), path, pathGetFront(), pathIsEmpty(), pathPopFront(), and source.
operationForChild() [3/3]
Merge::operationForChild (childName) [inline]
References assert, newEmptyPath(), path, pathGetFront(), pathIsEmpty(), pathPopFront(), and source.
toString() [1/3]
Merge::toString () [inline]
References path, and source.
toString() [2/3]
Merge::toString () [inline]
References path, and source.
toString() [3/3]
Merge::toString () [inline]
References path, and source.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js