FirebaseApp Class Reference
Public Member Functions
constructor (options, name, appStore)
get name ()
get options ()
getOrInitService (name, init)
delete ()
ensureService_ (serviceName, initializer)
checkDestroyed_ ()
Detailed Description
Global context object for a collection of services using a shared authentication state.
Member Function Documentation
checkDestroyed_()
FirebaseApp::checkDestroyed_ () [inline]
Throws an Error if the FirebaseApp instance has already been deleted.
References app, error_1, and has.
constructor()
FirebaseApp::constructor (options, name, appStore) [inline]
References a, an, app, credential, credential_internal_1, deep_copy_1, error_1, FirebaseAppInternals, INTERNAL, name(), options(), property, and validator.
delete()
FirebaseApp::delete () [inline]
Deletes the FirebaseApp instance.
Returns
An empty Promise fulfilled once the FirebaseApp instance is deleted.
References checkDestroyed_(), name(), and Promise.
ensureService_()
FirebaseApp::ensureService_ (serviceName, initializer) [inline]
getOrInitService()
FirebaseApp::getOrInitService (name, init) [inline]
References ensureService_(), init, and name().
name()
get FirebaseApp::name () [inline]
Returns the name of the FirebaseApp instance.
Returns
The name of the FirebaseApp instance.
References checkDestroyed_().
options()
get FirebaseApp::options () [inline]
Returns the options for the FirebaseApp instance.
Returns
The options for the FirebaseApp instance.
References checkDestroyed_(), and deep_copy_1.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/app/firebase-app.js