IndexedFilter Class Reference
Public Member Functions
constructor (index_)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
constructor (index_)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
constructor (index_)
updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator)
updateFullNode (oldSnap, newSnap, optChangeAccumulator)
updatePriority (oldSnap, newPriority)
filtersNodes ()
getIndexedFilter ()
getIndex ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Doesn't really filter nodes but applies an index to the node and keeps track of any changes
Member Function Documentation
constructor() [1/3]
IndexedFilter::constructor (index_) [inline]
constructor() [2/3]
IndexedFilter::constructor (index_) [inline]
constructor() [3/3]
IndexedFilter::constructor (index_) [inline]
filtersNodes() [1/3]
IndexedFilter::filtersNodes () [inline]
filtersNodes() [2/3]
IndexedFilter::filtersNodes () [inline]
filtersNodes() [3/3]
IndexedFilter::filtersNodes () [inline]
getIndex() [1/3]
IndexedFilter::getIndex () [inline]
getIndex() [2/3]
IndexedFilter::getIndex () [inline]
getIndex() [3/3]
IndexedFilter::getIndex () [inline]
getIndexedFilter() [1/3]
IndexedFilter::getIndexedFilter () [inline]
getIndexedFilter() [2/3]
IndexedFilter::getIndexedFilter () [inline]
getIndexedFilter() [3/3]
IndexedFilter::getIndexedFilter () [inline]
updateChild() [1/3]
IndexedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References changeChildAdded(), changeChildChanged(), changeChildRemoved(), and util.
updateChild() [2/3]
IndexedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References assert, changeChildAdded(), changeChildChanged(), and changeChildRemoved().
updateChild() [3/3]
IndexedFilter::updateChild (snap, key, newChild, affectedPath, source, optChangeAccumulator) [inline]
References assert, changeChildAdded(), changeChildChanged(), and changeChildRemoved().
updateFullNode() [1/3]
IndexedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References changeChildAdded(), changeChildChanged(), changeChildRemoved(), and PRIORITY_INDEX.
updateFullNode() [2/3]
IndexedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References changeChildAdded(), changeChildChanged(), changeChildRemoved(), and PRIORITY_INDEX.
updateFullNode() [3/3]
IndexedFilter::updateFullNode (oldSnap, newSnap, optChangeAccumulator) [inline]
References changeChildAdded(), changeChildChanged(), changeChildRemoved(), and PRIORITY_INDEX.
updatePriority() [1/3]
IndexedFilter::updatePriority (oldSnap, newPriority) [inline]
References ChildrenNode::EMPTY_NODE().
updatePriority() [2/3]
IndexedFilter::updatePriority (oldSnap, newPriority) [inline]
References ChildrenNode::EMPTY_NODE().
updatePriority() [3/3]
IndexedFilter::updatePriority (oldSnap, newPriority) [inline]
References ChildrenNode::EMPTY_NODE().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js