RecursiveDelete Class Reference
Public Member Functions
run ()
incrementErrorCount (err)
Private Member Functions
constructor (firestore, writer, ref, maxLimit, minLimit)
setupStream ()
getAllDescendants (ref)
onQueryEnd ()
deleteRef (docRef)
Detailed Description
Class used to store state required for running a recursive delete operation. Each recursive delete call should use a new instance of the class.
Member Function Documentation
constructor()
RecursiveDelete::constructor (firestore, writer, ref, maxLimit, minLimit) [inline], [private]
Parameters
firestore The Firestore instance to use.
writer The BulkWriter instance to use for delete operations.
ref The document or collection reference to recursively delete.
maxLimit The query limit to use when fetching descendants
minLimit The number of pending BulkWriter operations at which RecursiveDelete starts the next limit query to fetch descendants.
The number of deletes that failed with a permanent error.
Whether there are still documents to delete that still need to be fetched.
Whether run() has been called.
A deferred promise that resolves when the recursive delete operation is completed.
Whether a query stream is currently in progress. Only one stream can be run at a time.
The number of pending BulkWriter operations. Used to determine when the next query can be run.
References firestore, and util_1.
deleteRef()
RecursiveDelete::deleteRef (docRef) [inline], [private]
Deletes the provided reference and starts the next stream if conditions are met.
References incrementErrorCount(), setupStream(), and then.
getAllDescendants()
RecursiveDelete::getAllDescendants (ref) [inline], [private]
Retrieves all descendant documents nested under the provided reference.
Parameters
ref The reference to fetch all descendants for.
References _1, exports, firestore, query, and query_options_1.
incrementErrorCount()
RecursiveDelete::incrementErrorCount (err) [inline]
onQueryEnd()
RecursiveDelete::onQueryEnd () [inline], [private]
Called when all descendants of the provided reference have been streamed or if a permanent error occurs during the stream. Deletes the developer provided reference and wraps any errors that occurred.
References $, _1, _a, async, error, incrementErrorCount(), require(), undefined, and util_1.
run()
RecursiveDelete::run () [inline]
Recursively deletes the reference provided in the class constructor. Returns a promise that resolves when all descendants have been deleted, or if an error occurs.
References assert, and setupStream().
setupStream()
RecursiveDelete::setupStream () [inline], [private]
Creates a query stream and attaches event handlers to it.
References _1, deleteRef(), getAllDescendants(), on, onQueryEnd(), setupStream(), and stream.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/recursive-delete.js