DocumentChange Class Reference
Public Member Functions
 DocumentChange#type
The type of change ('added', 'modified', or 'removed').
@type {string}
@readonly
get type ()
 DocumentChange#doc
The document affected by this change.
@type {QueryDocumentSnapshot}
@readonly
get doc ()
 DocumentChange#oldIndex
The index of the changed document in the result set immediately prior to this DocumentChange (i.e. supposing that all prior DocumentChange objects have been applied). Is -1 for 'added' events.
@type {number}
@readonly
get oldIndex ()
 DocumentChange#newIndex
The index of the changed document in the result set immediately after this DocumentChange (i.e. supposing that all prior DocumentChange objects and the current DocumentChange object have been applied). Is -1 for 'removed' events.
@type {number}
@readonly
get newIndex ()
isEqual (other)
Private Member Functions
constructor (type, document, oldIndex, newIndex)
Detailed Description
A DocumentChange represents a change to the documents matching a query. It contains the document affected and the type of change that occurred.
Member Function Documentation
constructor()
DocumentChange::constructor (type, document, oldIndex, newIndex) [inline], [private]
Parameters
{string} type 'added' | 'removed' | 'modified'.
{QueryDocumentSnapshot} document The document.
{number} oldIndex The index in the documents array prior to this change.
{number} newIndex The index in the documents array after this change.
References newIndex(), oldIndex(), and type().
doc()
get DocumentChange::doc () [inline]
isEqual()
DocumentChange::isEqual (other) [inline]
Returns true if the data in this DocumentChange is equal to the provided value.
Parameters
{*} other The value to compare against.
Returns
true if this DocumentChange is equal to the provided value.
References isEqual().
newIndex()
get DocumentChange::newIndex () [inline]
oldIndex()
get DocumentChange::oldIndex () [inline]
type()
get DocumentChange::type () [inline]
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/document-change.js