WriteBatch Class Reference
Public Member Functions
create (documentRef, data)
delete (documentRef, precondition)
set (documentRef, data, options)
update (documentRef, dataOrField,...preconditionOrValues)
commit ()
Private Member Functions
get _opCount ()
constructor (firestore)
get isEmpty ()
verifyNotCommitted ()
async _commit (commitOptions)
_reset ()
Detailed Description
A Firestore WriteBatch that can be used to atomically commit multiple write operations at once.
Member Function Documentation
_commit()
async WriteBatch::_commit (commitOptions) [inline], [private]
Commit method that takes an optional transaction ID.
References _a, _firestore, database, logger_1, request, and util_1.
_opCount()
get WriteBatch::_opCount () [inline], [private]
The number of writes in this batch. Here is the caller graph for this function:
_reset()
WriteBatch::_reset () [inline], [private]
Resets the WriteBatch and dequeues all pending operations.
commit()
WriteBatch::commit () [inline]
References _commit(), _firestore, _opCount(), async, response, then, timestamp_1, trace_util_1, util_1, and WriteResult.
constructor()
WriteBatch::constructor (firestore) [inline], [private]
An array of document paths and the corresponding write operations that are executed as part of the commit. The resulting api.IWrite will be sent to the backend.
References _firestore, firestore, and serializer_1.
create()
WriteBatch::create (documentRef, data) [inline]
References data, document_1, helpers_1, transform, validateDocumentData, verifyNotCommitted(), and write.
delete()
WriteBatch::delete (documentRef, precondition) [inline]
References document_1, helpers_1, validateDeletePrecondition(), verifyNotCommitted(), and write.
isEmpty()
get WriteBatch::isEmpty () [inline], [private]
Checks if this write batch has any pending operations.
set()
WriteBatch::set (documentRef, data, options) [inline]
References data, document_1, helpers_1, transform, validateDocumentData, validateSetOptions, verifyNotCommitted(), and write.
update()
WriteBatch::update (documentRef, dataOrField, ...) [inline]
References $, document_1, helpers_1, i, logger_1, Map, path_1, transform, undefined, validate_1, validateFieldValue, validateNoConflictingFields(), validateUpdateMap(), validateUpdatePrecondition(), value, verifyNotCommitted(), and write.
verifyNotCommitted()
WriteBatch::verifyNotCommitted () [inline], [private]
Throws an error if this batch has already been committed. Here is the caller graph for this function:
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/write-batch.js