Agent Class Reference
Public Member Functions
constructor (opts)
isSecureEndpoint (options)
incrementSockets (name)
decrementSockets (name, socket)
getName (options)
createSocket (req, options, cb)
createConnection ()
get defaultPort ()
set defaultPort (v)
get protocol ()
set protocol (v)
Member Function Documentation
constructor()
Agent::constructor (opts) [inline]
References INTERNAL.
createConnection()
Agent::createConnection () [inline]
References INTERNAL, and undefined.
createSocket()
Agent::createSocket (req, options, cb) [inline]
References connect, decrementSockets(), getName(), http, incrementSockets(), INTERNAL, isSecureEndpoint(), name, Promise, and req.
decrementSockets()
Agent::decrementSockets (name, socket) [inline]
References index, and name.
defaultPort() [1/2]
get Agent::defaultPort () [inline]
References defaultPort(), INTERNAL, and protocol().
defaultPort() [2/2]
set Agent::defaultPort (v) [inline]
References INTERNAL, and v.
getName()
Agent::getName (options) [inline]
References https_1, and isSecureEndpoint().
incrementSockets()
Agent::incrementSockets (name) [inline]
References name, net, and writable.
isSecureEndpoint()
Agent::isSecureEndpoint (options) [inline]
Determine whether this is an http or https request.
References l.
protocol() [1/2]
get Agent::protocol () [inline]
References INTERNAL, isSecureEndpoint(), and protocol().
protocol() [2/2]
set Agent::protocol (v) [inline]
References INTERNAL, and v.
The documentation for this class was generated from the following file:
backend/node_modules/agent-base/dist/index.js