PersistentConnection Class Reference
Public Member Functions
constructor (repoInfo_, applicationId_, onDataUpdate_, onConnectStatus_, onServerInfoUpdate_, authTokenProvider_, appCheckTokenProvider_, authOverride_)
sendRequest (action, body, onResponse)
get (query)
listen (query, currentHashFn, tag, onComplete)
sendGet_ (index)
sendListen_ (listenSpec)
refreshAuthToken (token)
reduceReconnectDelayIfAdminCredential_ (credential)
refreshAppCheckToken (token)
tryAuth ()
tryAppCheck ()
constructor (repoInfo_, applicationId_, onDataUpdate_, onConnectStatus_, onServerInfoUpdate_, authTokenProvider_, appCheckTokenProvider_, authOverride_)
sendRequest (action, body, onResponse)
get (query)
listen (query, currentHashFn, tag, onComplete)
sendGet_ (index)
sendListen_ (listenSpec)
refreshAuthToken (token)
reduceReconnectDelayIfAdminCredential_ (credential)
refreshAppCheckToken (token)
tryAuth ()
tryAppCheck ()
constructor (repoInfo_, applicationId_, onDataUpdate_, onConnectStatus_, onServerInfoUpdate_, authTokenProvider_, appCheckTokenProvider_, authOverride_)
sendRequest (action, body, onResponse)
get (query)
listen (query, currentHashFn, tag, onComplete)
sendGet_ (index)
sendListen_ (listenSpec)
refreshAuthToken (token)
reduceReconnectDelayIfAdminCredential_ (credential)
refreshAppCheckToken (token)
tryAuth ()
tryAppCheck ()
put (pathString, data, onComplete, hash)
put (pathString, data, onComplete, hash)
put (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
onDisconnectPut (pathString, data, onComplete)
onDisconnectPut (pathString, data, onComplete)
onDisconnectPut (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectCancel (pathString, onComplete)
onDisconnectCancel (pathString, onComplete)
onDisconnectCancel (pathString, onComplete)
reportStats (stats)
reportStats (stats)
reportStats (stats)
Static Public Member Functions
static warnOnListenWarnings_ (payload, query)
static warnOnListenWarnings_ (payload, query)
static warnOnListenWarnings_ (payload, query)
Detailed Description
Firebase connection. Abstracts wire protocol and handles reconnecting.
NOTE: All JSON objects sent to the realtime connection must have property names enclosed in quotes to make sure the closure compiler does not minify them.
Member Function Documentation
constructor() [1/3]
PersistentConnection::constructor (repoInfo_, applicationId_, onDataUpdate_, onConnectStatus_, onServerInfoUpdate_, authTokenProvider_, appCheckTokenProvider_, authOverride_) [inline]
Parameters
repoInfo_ - Data about the namespace we are connecting to
applicationId_ - The Firebase App ID for this project
onDataUpdate_ - A callback for new data from the server
References OnlineMonitor::getInstance(), VisibilityMonitor::getInstance(), logWrapper, Map, onOnline_(), onVisible_(), RECONNECT_MAX_DELAY_DEFAULT, RECONNECT_MIN_DELAY, and util.
constructor() [2/3]
PersistentConnection::constructor (repoInfo_, applicationId_, onDataUpdate_, onConnectStatus_, onServerInfoUpdate_, authTokenProvider_, appCheckTokenProvider_, authOverride_) [inline]
Parameters
repoInfo_ - Data about the namespace we are connecting to
applicationId_ - The Firebase App ID for this project
onDataUpdate_ - A callback for new data from the server
References OnlineMonitor::getInstance(), VisibilityMonitor::getInstance(), isNodeSdk, logWrapper, Map, onOnline_(), onVisible_(), RECONNECT_MAX_DELAY_DEFAULT, and RECONNECT_MIN_DELAY.
constructor() [3/3]
PersistentConnection::constructor (repoInfo_, applicationId_, onDataUpdate_, onConnectStatus_, onServerInfoUpdate_, authTokenProvider_, appCheckTokenProvider_, authOverride_) [inline]
Parameters
repoInfo_ - Data about the namespace we are connecting to
applicationId_ - The Firebase App ID for this project
onDataUpdate_ - A callback for new data from the server
References OnlineMonitor::getInstance(), VisibilityMonitor::getInstance(), isNodeSdk, logWrapper, Map, onOnline_(), onVisible_(), RECONNECT_MAX_DELAY_DEFAULT, and RECONNECT_MIN_DELAY.
get() [1/3]
PersistentConnection::get (query) [inline]
References deferred, index, initConnection_(), message, p, q, query, request, and sendGet_().
get() [2/3]
PersistentConnection::get (query) [inline]
References Deferred, deferred, index, initConnection_(), message, p, q, query, request, and sendGet_().
get() [3/3]
PersistentConnection::get (query) [inline]
References Deferred, deferred, index, initConnection_(), message, p, q, query, request, and sendGet_().
listen() [1/3]
PersistentConnection::listen (query, currentHashFn, tag, onComplete) [inline]
References initConnection_(), listen, Map, path, query, sendListen_(), and util.
listen() [2/3]
PersistentConnection::listen (query, currentHashFn, tag, onComplete) [inline]
References assert, initConnection_(), listen, Map, path, query, and sendListen_().
listen() [3/3]
PersistentConnection::listen (query, currentHashFn, tag, onComplete) [inline]
References assert, initConnection_(), listen, Map, path, query, and sendListen_().
merge() [1/3]
ServerActions::merge (pathString, data, onComplete, hash) [inline], [inherited]
merge() [2/3]
ServerActions::merge (pathString, data, onComplete, hash) [inline], [inherited]
merge() [3/3]
ServerActions::merge (pathString, data, onComplete, hash) [inline], [inherited]
onDisconnectCancel() [1/3]
ServerActions::onDisconnectCancel (pathString, onComplete) [inline], [inherited]
onDisconnectCancel() [2/3]
ServerActions::onDisconnectCancel (pathString, onComplete) [inline], [inherited]
onDisconnectCancel() [3/3]
ServerActions::onDisconnectCancel (pathString, onComplete) [inline], [inherited]
onDisconnectMerge() [1/3]
ServerActions::onDisconnectMerge (pathString, data, onComplete) [inline], [inherited]
onDisconnectMerge() [2/3]
ServerActions::onDisconnectMerge (pathString, data, onComplete) [inline], [inherited]
onDisconnectMerge() [3/3]
ServerActions::onDisconnectMerge (pathString, data, onComplete) [inline], [inherited]
onDisconnectPut() [1/3]
ServerActions::onDisconnectPut (pathString, data, onComplete) [inline], [inherited]
onDisconnectPut() [2/3]
ServerActions::onDisconnectPut (pathString, data, onComplete) [inline], [inherited]
onDisconnectPut() [3/3]
ServerActions::onDisconnectPut (pathString, data, onComplete) [inline], [inherited]
put() [1/3]
ServerActions::put (pathString, data, onComplete, hash) [inline], [inherited]
put() [2/3]
ServerActions::put (pathString, data, onComplete, hash) [inline], [inherited]
put() [3/3]
ServerActions::put (pathString, data, onComplete, hash) [inline], [inherited]
reduceReconnectDelayIfAdminCredential_() [1/3]
PersistentConnection::reduceReconnectDelayIfAdminCredential_ (credential) [inline]
References credential, RECONNECT_MAX_DELAY_FOR_ADMINS, and util.
reduceReconnectDelayIfAdminCredential_() [2/3]
PersistentConnection::reduceReconnectDelayIfAdminCredential_ (credential) [inline]
References credential, isAdmin, and RECONNECT_MAX_DELAY_FOR_ADMINS.
reduceReconnectDelayIfAdminCredential_() [3/3]
PersistentConnection::reduceReconnectDelayIfAdminCredential_ (credential) [inline]
References credential, isAdmin, and RECONNECT_MAX_DELAY_FOR_ADMINS.
refreshAppCheckToken() [1/3]
PersistentConnection::refreshAppCheckToken (token) [inline]
References sendRequest(), token, and tryAppCheck().
refreshAppCheckToken() [2/3]
PersistentConnection::refreshAppCheckToken (token) [inline]
References sendRequest(), token, and tryAppCheck().
refreshAppCheckToken() [3/3]
PersistentConnection::refreshAppCheckToken (token) [inline]
References sendRequest(), token, and tryAppCheck().
refreshAuthToken() [1/3]
PersistentConnection::refreshAuthToken (token) [inline]
References reduceReconnectDelayIfAdminCredential_(), sendRequest(), token, and tryAuth().
refreshAuthToken() [2/3]
PersistentConnection::refreshAuthToken (token) [inline]
References reduceReconnectDelayIfAdminCredential_(), sendRequest(), token, and tryAuth().
refreshAuthToken() [3/3]
PersistentConnection::refreshAuthToken (token) [inline]
References reduceReconnectDelayIfAdminCredential_(), sendRequest(), token, and tryAuth().
reportStats() [1/3]
ServerActions::reportStats (stats) [inline], [inherited]
reportStats() [2/3]
ServerActions::reportStats (stats) [inline], [inherited]
reportStats() [3/3]
ServerActions::reportStats (stats) [inline], [inherited]
sendGet_() [1/3]
PersistentConnection::sendGet_ (index) [inline]
References index, message, request, and sendRequest().
sendGet_() [2/3]
PersistentConnection::sendGet_ (index) [inline]
References index, message, request, and sendRequest().
sendGet_() [3/3]
PersistentConnection::sendGet_ (index) [inline]
References index, message, request, and sendRequest().
sendListen_() [1/3]
PersistentConnection::sendListen_ (listenSpec) [inline]
References message, p, query, removeListen_(), req, sendRequest(), status, and warnOnListenWarnings_().
sendListen_() [2/3]
PersistentConnection::sendListen_ (listenSpec) [inline]
References message, p, query, removeListen_(), req, sendRequest(), status, and warnOnListenWarnings_().
sendListen_() [3/3]
PersistentConnection::sendListen_ (listenSpec) [inline]
References message, p, query, removeListen_(), req, sendRequest(), status, and warnOnListenWarnings_().
sendRequest() [1/3]
PersistentConnection::sendRequest (action, body, onResponse) [inline]
References a, b, msg, r, and util.
sendRequest() [2/3]
PersistentConnection::sendRequest (action, body, onResponse) [inline]
References a, assert, b, msg, r, and stringify.
sendRequest() [3/3]
PersistentConnection::sendRequest (action, body, onResponse) [inline]
References a, assert, b, msg, r, and stringify.
tryAppCheck() [1/3]
PersistentConnection::tryAppCheck () [inline]
Attempts to authenticate with the given token. If the authentication attempt fails, it's triggered like the token was revoked (the connection is closed).
References data, onAppCheckRevoked_(), res, sendRequest(), and status.
tryAppCheck() [2/3]
PersistentConnection::tryAppCheck () [inline]
Attempts to authenticate with the given token. If the authentication attempt fails, it's triggered like the token was revoked (the connection is closed).
References data, onAppCheckRevoked_(), res, sendRequest(), and status.
tryAppCheck() [3/3]
PersistentConnection::tryAppCheck () [inline]
Attempts to authenticate with the given token. If the authentication attempt fails, it's triggered like the token was revoked (the connection is closed).
References data, onAppCheckRevoked_(), res, sendRequest(), and status.
tryAuth() [1/3]
PersistentConnection::tryAuth () [inline]
Attempts to authenticate with the given credentials. If the authentication attempt fails, it's triggered like a auth revoked (the connection is closed).
References data, onAuthRevoked_(), res, sendRequest(), status, token, and util.
tryAuth() [2/3]
PersistentConnection::tryAuth () [inline]
Attempts to authenticate with the given credentials. If the authentication attempt fails, it's triggered like a auth revoked (the connection is closed).
References data, isValidFormat, onAuthRevoked_(), res, sendRequest(), status, and token.
tryAuth() [3/3]
PersistentConnection::tryAuth () [inline]
Attempts to authenticate with the given credentials. If the authentication attempt fails, it's triggered like a auth revoked (the connection is closed).
References data, isValidFormat, onAuthRevoked_(), res, sendRequest(), status, and token.
warnOnListenWarnings_() [1/3]
static PersistentConnection::warnOnListenWarnings_ (payload, query) [inline], [static]
References $, an, and, Array, at, client, data, index, on, query, util, and warn.
warnOnListenWarnings_() [2/3]
static PersistentConnection::warnOnListenWarnings_ (payload, query) [inline], [static]
References $, an, and, Array, at, client, contains, data, index, on, query, safeGet, and warn.
warnOnListenWarnings_() [3/3]
static PersistentConnection::warnOnListenWarnings_ (payload, query) [inline], [static]
References $, an, and, Array, at, client, contains, data, index, on, query, safeGet, and warn.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js