Firestore Class Reference
Public Member Functions
settings (settings)
validateAndApplySettings (settings)
newTraceUtilInstance (settings)
get databaseId ()
doc (documentPath)
collection (collectionPath)
collectionGroup (collectionId)
batch ()
bulkWriter (options)
bundle (name)
runTransaction (updateFunction, transactionOptions)
listCollections ()
getAll (...documentRefsOrReadOptions)
recursiveDelete (ref, bulkWriter)
terminate ()
toJSON ()
Private Member Functions
getBulkWriter ()
constructor (settings)
get projectId ()
get formattedName ()
snapshot_ (documentOrName, readTime, encoding)
registerListener ()
unregisterListener ()
_incrementBulkWritersCount ()
_decrementBulkWritersCount ()
_recursiveDelete (ref, maxPendingOps, minPendingOps, bulkWriter)
async initializeIfNeeded (requestTag)
createCallOptions (methodName, retryCodes)
async _retry (methodName, requestTag, func)
_initializeStream (backendStream, lifetime, requestTag, request)
request (methodName, request, requestTag, retryCodes)
requestStream (methodName, bidrectional, request, requestTag)
Detailed Description
Examples
/Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/firestore/build/src/field-value.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/firestore/build/src/geo-point.js, /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/firestore/build/src/timestamp.js, and Import.
Member Function Documentation
_decrementBulkWritersCount()
Firestore::_decrementBulkWritersCount () [inline], [private]
Decrements the number of open BulkWriter instances. This is used to verify that all pending operations are complete when terminate() is called.
_incrementBulkWritersCount()
Firestore::_incrementBulkWritersCount () [inline], [private]
Increments the number of open BulkWriter instances. This is used to verify that all pending operations are complete when terminate() is called.
_initializeStream()
Firestore::_initializeStream (backendStream, lifetime, requestTag, request) [inline], [private]
Waits for the provided stream to become active and returns a paused but healthy stream. If an error occurs before the first byte is read, the method rejects the returned Promise. Whether we have resolved the Promise and returned the stream to the caller.
References logger_1, objectMode, Promise, reject(), request, requestTag, resolve, setImmediate, and stream_1.
_recursiveDelete()
Firestore::_recursiveDelete (ref, maxPendingOps, minPendingOps, bulkWriter) [inline], [private]
This overload is not private in order to test the query resumption with startAfter() once the RecursiveDelete instance has MAX_PENDING_OPS pending.
References recursive_delete_1.
_retry()
async Firestore::_retry (methodName, requestTag, func) [inline], [private]
A function returning a Promise that can be retried. Helper method that retries failed Promises.
If 'delayMs' is specified, waits 'delayMs' between invocations. Otherwise, schedules the first attempt immediately, and then waits 100 milliseconds for further attempts.
References attempt, backoff_1, exports, func, logger_1, Promise, requestTag, undefined, and util_1.
batch()
Firestore::batch () [inline]
References write_batch_1.
bulkWriter()
Firestore::bulkWriter (options) [inline]
References bulk_writer_1.
bundle()
Firestore::bundle (name) [inline]
Creates a new BundleBuilder instance to package selected Firestore data into a bundle.
Parameters
bundleId. The id of the bundle. When loaded on clients, client SDKs use this id and the timestamp associated with the built bundle to tell if it has been loaded already. If not specified, a random identifier will be used.
References bundle_1, name, and util_1.
collection()
Firestore::collection (collectionPath) [inline]
References a, an, collection_reference_1, not, of, path, and path_1.
collectionGroup()
Firestore::collectionGroup (collectionId) [inline]
References collection_group_1, not, and undefined.
constructor()
Firestore::constructor (settings) [inline], [private]
Parameters
{Object=} settings Configuration object.
{string=} settings.projectId The project ID from the Google Developer's Console, e.g. 'grape-spaceship-123'. We will also check the environment variable GCLOUD_PROJECT for your project ID. Can be omitted in environments that support Application Default Credentials
{string=} settings.keyFilename Local file containing the Service Account credentials as downloaded from the Google Developers Console. Can be omitted in environments that support Application Default Credentials. To configure Firestore with custom credentials, use settings.credentials and provide the client_email and private_key of your service account.
{{client_email:string=,private_key:string=}=} settings.credentials The client_email and private_key properties of the service account to use with your Firestore project. Can be omitted in environments that support Application Default Credentials. If your credentials are stored in a JSON file, you can specify a keyFilename instead.
{string=} settings.host The host to connect to.
{boolean=} settings.ssl Whether to use SSL when connecting.
{number=} settings.maxIdleChannels The maximum number of idle GRPC channels to keep. A smaller number of idle channels reduces memory usage but increases request latency for clients with fluctuating request rates. If set to 0, shuts down all GRPC channels when the client becomes idle. Defaults to 1.
{boolean=} settings.ignoreUndefinedProperties Whether to skip nested properties that are set to undefined during object serialization. If set to true, these properties are skipped and not written to Firestore. If set false or omitted, the SDK throws an exception when it encounters properties of type undefined.
{boolean=} settings.preferRest Whether to force the use of HTTP/1.1 REST transport until a method that requires gRPC is called. When a method requires gRPC, this Firestore client will load dependent gRPC libraries and then use gRPC transport for communication from that point forward. Currently the only operation that requires gRPC is creating a snapshot listener with the method DocumentReference<T>.onSnapshot(), CollectionReference<T>.onSnapshot(), or Query<T>.onSnapshot(). If specified, this setting value will take precedent over the environment variable FIRESTORE_PREFER_REST. If not specified, the SDK will use the value specified in the environment variable FIRESTORE_PREFER_REST. Valid values of FIRESTORE_PREFER_REST are true ('1') or false (0). Values are not case-sensitive. Any other value for the environment variable will be ignored and a warning will be logged to the console.
The configuration options for the GAPIC client.
Whether the initialization settings can still be changed by invoking settings().
The serializer to use for the Protobuf transformation.
The project ID for this client.
The project ID is auto-detected during the first request unless a project ID is passed to the constructor (or provided via .settings()).
The database ID provided via .settings().
Count of listeners that have been registered on the client.
The client can only be terminated when there are no pending writes or registered listeners.
Number of pending operations on the client.
The client can only be terminated when there are no pending writes or registered listeners.
References _a, client, DEFAULT_MAX_IDLE_CHANNELS, fallback, false, gax, libVersion, logger_1, MAX_CONCURRENT_REQUESTS_PER_CLIENT, module, newTraceUtilInstance(), pool_1, require(), serviceConfig, settings(), undefined, and validateAndApplySettings().
createCallOptions()
Firestore::createCallOptions (methodName, retryCodes) [inline], [private]
Returns GAX call options that set the cloud resource header.
References _a, CLOUD_RESOURCE_HEADER, headers, require(), and util_1.
databaseId()
get Firestore::databaseId () [inline]
Returns the Database ID for this Firestore instance.
References path_1.
doc()
Firestore::doc (documentPath) [inline]
References a, an, document_reference_1, not, of, path, and path_1.
formattedName()
get Firestore::formattedName () [inline], [private]
Returns the root path of the database. Validates that initializeIfNeeded() was called before.
References $.
getAll()
Firestore::getAll (...) [inline]
References document_reader_1, trace_util_1, transaction_1, and util_1.
getBulkWriter()
Firestore::getBulkWriter () [inline], [private]
Lazy-load the Firestore's default BulkWriter.
References bulkWriter().
initializeIfNeeded()
async Firestore::initializeIfNeeded (requestTag) [inline], [private]
Initializes the client if it is not already initialized. All methods in the SDK can be used after this method completes.
References logger_1, Promise, requestTag, and undefined.
listCollections()
Firestore::listCollections () [inline]
References document_reference_1, and path_1.
newTraceUtilInstance()
Firestore::newTraceUtilInstance (settings) [inline]
References _a, disabled_trace_util_1, enabled_trace_util_1, and process.
projectId()
get Firestore::projectId () [inline], [private]
Returns the Project ID for this Firestore instance. Validates that initializeIfNeeded() was called before.
References undefined.
recursiveDelete()
Firestore::recursiveDelete (ref, bulkWriter) [inline]
References recursive_delete_1.
registerListener()
Firestore::registerListener () [inline], [private]
Registers a listener on this client, incrementing the listener count. This is used to verify that all listeners are unsubscribed when terminate() is called.
request()
Firestore::request (methodName, request, requestTag, retryCodes) [inline], [private]
A funnel for all non-streaming API requests, assigning a project ID where necessary within the request options.
References async, logger_1, Promise, request, requestTag, and result.
requestStream()
Firestore::requestStream (methodName, bidrectional, request, requestTag) [inline], [private]
A funnel for streaming API requests, assigning a project ID where necessary within the request options.
The stream is returned in paused state and needs to be resumed once all listeners are attached.
References $, async, callback, chunk(), e, encoding, logger_1, objectMode, request, requestTag, response, result, stream, stream_1, transform, undefined, and util_1.
runTransaction()
Firestore::runTransaction (updateFunction, transactionOptions) [inline]
References transaction_1, util_1, and validate_1.
settings()
Firestore::settings (settings) [inline]
Specifies custom settings to be used to configure the Firestore instance. Can only be invoked once and before any other Firestore method.
If settings are provided via both settings() and the Firestore constructor, both settings objects are merged and any settings provided via settings() take precedence.
Parameters
{object} settings The settings to use for all Firestore operations.
References settings(), validate_1, and validateAndApplySettings().
snapshot_()
Firestore::snapshot_ (documentOrName, readTime, encoding) [inline], [private]
References convert_1, data, document_1, document_reference_1, encoding, path_1, timestamp_1, and undefined.
terminate()
Firestore::terminate () [inline]
Terminates the Firestore client and closes all open streams.
Returns
A Promise that resolves when the client is terminated.
References $, and, instances, and Promise.
toJSON()
Firestore::toJSON () [inline]
Returns the Project ID to serve as the JSON representation of this Firestore instance.
Returns
An object that contains the project ID (or undefined if not yet available).
unregisterListener()
Firestore::unregisterListener () [inline], [private]
Unregisters a listener on this client, decrementing the listener count. This is used to verify that all listeners are unsubscribed when terminate() is called.
validateAndApplySettings()
Firestore::validateAndApplySettings (settings) [inline]
References $, _a, http, if(), match, not, process, settings(), undefined, url, url_1, util_1, and validate_1.
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/index.js