ChannelzTrace Class Reference
Public Member Functions
constructor ()
addTrace (severity, description, child)
getTraceMessage ()
Member Function Documentation
addTrace()
ChannelzTrace::addTrace (severity, description, child) [inline]
References TARGET_RETAINED_TRACES, timestamp, and undefined.
constructor()
ChannelzTrace::constructor () [inline]
getTraceMessage()
ChannelzTrace::getTraceMessage () [inline]
References channelRefToMessage(), dateToProtoTimestamp(), event, subchannelRefToMessage(), and timestamp.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/channelz.js