Connection Class Reference
Public Member Functions
constructor (id, repoInfo_, applicationId_, appCheckToken_, authToken_, onMessage_, onReady_, onDisconnect_, onKill_, lastSessionId)
start_ ()
nextTransportId_ ()
disconnReceiver_ (conn)
connReceiver_ (conn)
sendRequest (dataMsg)
tryCleanupConnection ()
onSecondaryControl_ (controlData)
onSecondaryMessageReceived_ (parsedData)
upgradeIfSecondaryHealthy_ ()
proceedWithUpgrade_ ()
onPrimaryMessageReceived_ (parsedData)
onDataMessage_ (message)
onPrimaryResponse_ ()
onControl_ (controlData)
onHandshake_ (handshake)
tryStartUpgrade_ ()
startUpgrade_ (conn)
onReset_ (host)
onConnectionEstablished_ (conn, timestamp)
sendPingOnPrimaryIfNecessary_ ()
onSecondaryConnectionLost_ ()
onConnectionLost_ (everConnected)
onConnectionShutdown_ (reason)
sendData_ (data)
close ()
closeConnections_ ()
constructor (id, repoInfo_, applicationId_, appCheckToken_, authToken_, onMessage_, onReady_, onDisconnect_, onKill_, lastSessionId)
start_ ()
nextTransportId_ ()
disconnReceiver_ (conn)
connReceiver_ (conn)
sendRequest (dataMsg)
tryCleanupConnection ()
onSecondaryControl_ (controlData)
onSecondaryMessageReceived_ (parsedData)
upgradeIfSecondaryHealthy_ ()
proceedWithUpgrade_ ()
onPrimaryMessageReceived_ (parsedData)
onDataMessage_ (message)
onPrimaryResponse_ ()
onControl_ (controlData)
onHandshake_ (handshake)
tryStartUpgrade_ ()
startUpgrade_ (conn)
onReset_ (host)
onConnectionEstablished_ (conn, timestamp)
sendPingOnPrimaryIfNecessary_ ()
onSecondaryConnectionLost_ ()
onConnectionLost_ (everConnected)
onConnectionShutdown_ (reason)
sendData_ (data)
close ()
closeConnections_ ()
constructor (id, repoInfo_, applicationId_, appCheckToken_, authToken_, onMessage_, onReady_, onDisconnect_, onKill_, lastSessionId)
start_ ()
nextTransportId_ ()
disconnReceiver_ (conn)
connReceiver_ (conn)
sendRequest (dataMsg)
tryCleanupConnection ()
onSecondaryControl_ (controlData)
onSecondaryMessageReceived_ (parsedData)
upgradeIfSecondaryHealthy_ ()
proceedWithUpgrade_ ()
onPrimaryMessageReceived_ (parsedData)
onDataMessage_ (message)
onPrimaryResponse_ ()
onControl_ (controlData)
onHandshake_ (handshake)
tryStartUpgrade_ ()
startUpgrade_ (conn)
onReset_ (host)
onConnectionEstablished_ (conn, timestamp)
sendPingOnPrimaryIfNecessary_ ()
onSecondaryConnectionLost_ ()
onConnectionLost_ (everConnected)
onConnectionShutdown_ (reason)
sendData_ (data)
close ()
closeConnections_ ()
Detailed Description
Creates a new real-time connection to the server using whichever method works best in the current browser.
Member Function Documentation
close() [1/3]
Connection::close () [inline]
Cleans up this connection, calling the appropriate callbacks
References closeConnections_().
close() [2/3]
Connection::close () [inline]
Cleans up this connection, calling the appropriate callbacks
References closeConnections_().
close() [3/3]
Connection::close () [inline]
Cleans up this connection, calling the appropriate callbacks
References closeConnections_().
closeConnections_() [1/3]
Connection::closeConnections_ () [inline]
closeConnections_() [2/3]
Connection::closeConnections_ () [inline]
closeConnections_() [3/3]
Connection::closeConnections_ () [inline]
connReceiver_() [1/3]
Connection::connReceiver_ (conn) [inline]
References message, onPrimaryMessageReceived_(), and onSecondaryMessageReceived_().
connReceiver_() [2/3]
Connection::connReceiver_ (conn) [inline]
References message, onPrimaryMessageReceived_(), and onSecondaryMessageReceived_().
connReceiver_() [3/3]
Connection::connReceiver_ (conn) [inline]
References message, onPrimaryMessageReceived_(), and onSecondaryMessageReceived_().
constructor() [1/3]
Connection::constructor (id, repoInfo_, applicationId_, appCheckToken_, authToken_, onMessage_, onReady_, onDisconnect_, onKill_, lastSessionId) [inline]
Parameters
id - an id for this connection
repoInfo_ - the info for the endpoint to connect to
applicationId_ - the Firebase App ID for this project
appCheckToken_ - The App Check Token for this device.
authToken_ - The auth token for this session.
onMessage_ - the callback to be triggered when a server-push message arrives
onReady_ - the callback to be triggered when this connection is ready to send messages.
onDisconnect_ - the callback to be triggered when a connection was lost
onKill_ - the callback to be triggered when this connection has permanently shut down.
lastSessionId - last session id in persistent connection. is used to clean up old session in real-time server
References logWrapper, onReady_(), and start_().
constructor() [2/3]
Connection::constructor (id, repoInfo_, applicationId_, appCheckToken_, authToken_, onMessage_, onReady_, onDisconnect_, onKill_, lastSessionId) [inline]
Parameters
id - an id for this connection
repoInfo_ - the info for the endpoint to connect to
applicationId_ - the Firebase App ID for this project
appCheckToken_ - The App Check Token for this device.
authToken_ - The auth token for this session.
onMessage_ - the callback to be triggered when a server-push message arrives
onReady_ - the callback to be triggered when this connection is ready to send messages.
onDisconnect_ - the callback to be triggered when a connection was lost
onKill_ - the callback to be triggered when this connection has permanently shut down.
lastSessionId - last session id in persistent connection. is used to clean up old session in real-time server
References logWrapper, onReady_(), and start_().
constructor() [3/3]
Connection::constructor (id, repoInfo_, applicationId_, appCheckToken_, authToken_, onMessage_, onReady_, onDisconnect_, onKill_, lastSessionId) [inline]
Parameters
id - an id for this connection
repoInfo_ - the info for the endpoint to connect to
applicationId_ - the Firebase App ID for this project
appCheckToken_ - The App Check Token for this device.
authToken_ - The auth token for this session.
onMessage_ - the callback to be triggered when a server-push message arrives
onReady_ - the callback to be triggered when this connection is ready to send messages.
onDisconnect_ - the callback to be triggered when a connection was lost
onKill_ - the callback to be triggered when this connection has permanently shut down.
lastSessionId - last session id in persistent connection. is used to clean up old session in real-time server
References logWrapper, onReady_(), and start_().
disconnReceiver_() [1/3]
Connection::disconnReceiver_ (conn) [inline]
References onConnectionLost_(), and onSecondaryConnectionLost_().
disconnReceiver_() [2/3]
Connection::disconnReceiver_ (conn) [inline]
References onConnectionLost_(), and onSecondaryConnectionLost_().
disconnReceiver_() [3/3]
Connection::disconnReceiver_ (conn) [inline]
References onConnectionLost_(), and onSecondaryConnectionLost_().
nextTransportId_() [1/3]
Connection::nextTransportId_ () [inline]
nextTransportId_() [2/3]
Connection::nextTransportId_ () [inline]
nextTransportId_() [3/3]
Connection::nextTransportId_ () [inline]
onConnectionEstablished_() [1/3]
Connection::onConnectionEstablished_ (conn, timestamp) [inline]
References DELAY_BEFORE_SENDING_EXTRA_REQUESTS, onReady_(), sendPingOnPrimaryIfNecessary_(), setTimeoutNonBlocking, and timestamp.
onConnectionEstablished_() [2/3]
Connection::onConnectionEstablished_ (conn, timestamp) [inline]
References DELAY_BEFORE_SENDING_EXTRA_REQUESTS, onReady_(), sendPingOnPrimaryIfNecessary_(), setTimeoutNonBlocking, and timestamp.
onConnectionEstablished_() [3/3]
Connection::onConnectionEstablished_ (conn, timestamp) [inline]
References DELAY_BEFORE_SENDING_EXTRA_REQUESTS, onReady_(), sendPingOnPrimaryIfNecessary_(), setTimeoutNonBlocking, and timestamp.
onConnectionLost_() [1/3]
Connection::onConnectionLost_ (everConnected) [inline]
Parameters
everConnected - Whether or not the connection ever reached a server. Used to determine if we should flush the host cache
References close(), and PersistentStorage.
onConnectionLost_() [2/3]
Connection::onConnectionLost_ (everConnected) [inline]
Parameters
everConnected - Whether or not the connection ever reached a server. Used to determine if we should flush the host cache
References close(), and PersistentStorage.
onConnectionLost_() [3/3]
Connection::onConnectionLost_ (everConnected) [inline]
Parameters
everConnected - Whether or not the connection ever reached a server. Used to determine if we should flush the host cache
References close(), and PersistentStorage.
onConnectionShutdown_() [1/3]
Connection::onConnectionShutdown_ (reason) [inline]
References close(), and reason.
onConnectionShutdown_() [2/3]
Connection::onConnectionShutdown_ (reason) [inline]
References close(), and reason.
onConnectionShutdown_() [3/3]
Connection::onConnectionShutdown_ (reason) [inline]
References close(), and reason.
onControl_() [1/3]
Connection::onControl_ (controlData) [inline]
References CONTROL_ERROR, CONTROL_PONG, CONTROL_RESET, CONTROL_SHUTDOWN, END_TRANSMISSION, error, i, MESSAGE_DATA, MESSAGE_TYPE, onConnectionShutdown_(), onDataMessage_(), onHandshake_(), onPrimaryResponse_(), onReset_(), requireKey, sendPingOnPrimaryIfNecessary_(), SERVER_HELLO, and tryCleanupConnection().
onControl_() [2/3]
Connection::onControl_ (controlData) [inline]
References CONTROL_ERROR, CONTROL_PONG, CONTROL_RESET, CONTROL_SHUTDOWN, END_TRANSMISSION, error, i, MESSAGE_DATA, MESSAGE_TYPE, onConnectionShutdown_(), onDataMessage_(), onHandshake_(), onPrimaryResponse_(), onReset_(), requireKey, sendPingOnPrimaryIfNecessary_(), SERVER_HELLO, and tryCleanupConnection().
onControl_() [3/3]
Connection::onControl_ (controlData) [inline]
References CONTROL_ERROR, CONTROL_PONG, CONTROL_RESET, CONTROL_SHUTDOWN, END_TRANSMISSION, error, i, MESSAGE_DATA, MESSAGE_TYPE, onConnectionShutdown_(), onDataMessage_(), onHandshake_(), onPrimaryResponse_(), onReset_(), requireKey, sendPingOnPrimaryIfNecessary_(), SERVER_HELLO, and tryCleanupConnection().
onDataMessage_() [1/3]
Connection::onDataMessage_ (message) [inline]
References message, and onPrimaryResponse_().
onDataMessage_() [2/3]
Connection::onDataMessage_ (message) [inline]
References message, and onPrimaryResponse_().
onDataMessage_() [3/3]
Connection::onDataMessage_ (message) [inline]
References message, and onPrimaryResponse_().
onHandshake_() [1/3]
Connection::onHandshake_ (handshake) [inline]
Parameters
handshake - The handshake data returned from the server
References onConnectionEstablished_(), PROTOCOL_VERSION, timestamp, tryStartUpgrade_(), version, and warn.
onHandshake_() [2/3]
Connection::onHandshake_ (handshake) [inline]
Parameters
handshake - The handshake data returned from the server
References onConnectionEstablished_(), PROTOCOL_VERSION, timestamp, tryStartUpgrade_(), version, and warn.
onHandshake_() [3/3]
Connection::onHandshake_ (handshake) [inline]
Parameters
handshake - The handshake data returned from the server
References onConnectionEstablished_(), PROTOCOL_VERSION, timestamp, tryStartUpgrade_(), version, and warn.
onPrimaryMessageReceived_() [1/3]
Connection::onPrimaryMessageReceived_ (parsedData) [inline]
References data, onControl_(), onDataMessage_(), and requireKey.
onPrimaryMessageReceived_() [2/3]
Connection::onPrimaryMessageReceived_ (parsedData) [inline]
References data, onControl_(), onDataMessage_(), and requireKey.
onPrimaryMessageReceived_() [3/3]
Connection::onPrimaryMessageReceived_ (parsedData) [inline]
References data, onControl_(), onDataMessage_(), and requireKey.
onPrimaryResponse_() [1/3]
Connection::onPrimaryResponse_ () [inline]
onPrimaryResponse_() [2/3]
Connection::onPrimaryResponse_ () [inline]
onPrimaryResponse_() [3/3]
Connection::onPrimaryResponse_ () [inline]
onReset_() [1/3]
Connection::onReset_ (host) [inline]
References close(), closeConnections_(), and start_().
onReset_() [2/3]
Connection::onReset_ (host) [inline]
References close(), closeConnections_(), and start_().
onReset_() [3/3]
Connection::onReset_ (host) [inline]
References close(), closeConnections_(), and start_().
onSecondaryConnectionLost_() [1/3]
Connection::onSecondaryConnectionLost_ () [inline]
References close().
onSecondaryConnectionLost_() [2/3]
Connection::onSecondaryConnectionLost_ () [inline]
References close().
onSecondaryConnectionLost_() [3/3]
Connection::onSecondaryConnectionLost_ () [inline]
References close().
onSecondaryControl_() [1/3]
Connection::onSecondaryControl_ (controlData) [inline]
References close(), CONTROL_PONG, CONTROL_RESET, MESSAGE_TYPE, SWITCH_ACK, and upgradeIfSecondaryHealthy_().
onSecondaryControl_() [2/3]
Connection::onSecondaryControl_ (controlData) [inline]
References close(), CONTROL_PONG, CONTROL_RESET, MESSAGE_TYPE, SWITCH_ACK, and upgradeIfSecondaryHealthy_().
onSecondaryControl_() [3/3]
Connection::onSecondaryControl_ (controlData) [inline]
References close(), CONTROL_PONG, CONTROL_RESET, MESSAGE_TYPE, SWITCH_ACK, and upgradeIfSecondaryHealthy_().
onSecondaryMessageReceived_() [1/3]
Connection::onSecondaryMessageReceived_ (parsedData) [inline]
References data, onSecondaryControl_(), and requireKey.
onSecondaryMessageReceived_() [2/3]
Connection::onSecondaryMessageReceived_ (parsedData) [inline]
References data, onSecondaryControl_(), and requireKey.
onSecondaryMessageReceived_() [3/3]
Connection::onSecondaryMessageReceived_ (parsedData) [inline]
References data, onSecondaryControl_(), and requireKey.
proceedWithUpgrade_() [1/3]
Connection::proceedWithUpgrade_ () [inline]
References d, END_TRANSMISSION, SWITCH_ACK, t, and tryCleanupConnection().
proceedWithUpgrade_() [2/3]
Connection::proceedWithUpgrade_ () [inline]
References d, END_TRANSMISSION, SWITCH_ACK, t, and tryCleanupConnection().
proceedWithUpgrade_() [3/3]
Connection::proceedWithUpgrade_ () [inline]
References d, END_TRANSMISSION, SWITCH_ACK, t, and tryCleanupConnection().
sendData_() [1/3]
Connection::sendData_ (data) [inline]
References data.
sendData_() [2/3]
Connection::sendData_ (data) [inline]
References data.
sendData_() [3/3]
Connection::sendData_ (data) [inline]
References data.
sendPingOnPrimaryIfNecessary_() [1/3]
Connection::sendPingOnPrimaryIfNecessary_ () [inline]
References d, PING, sendData_(), and t.
sendPingOnPrimaryIfNecessary_() [2/3]
Connection::sendPingOnPrimaryIfNecessary_ () [inline]
References d, PING, sendData_(), and t.
sendPingOnPrimaryIfNecessary_() [3/3]
Connection::sendPingOnPrimaryIfNecessary_ () [inline]
References d, PING, sendData_(), and t.
sendRequest() [1/3]
Connection::sendRequest (dataMsg) [inline]
Parameters
dataMsg - An arbitrary data message to be sent to the server
References d, msg, sendData_(), and t.
sendRequest() [2/3]
Connection::sendRequest (dataMsg) [inline]
Parameters
dataMsg - An arbitrary data message to be sent to the server
References d, msg, sendData_(), and t.
sendRequest() [3/3]
Connection::sendRequest (dataMsg) [inline]
Parameters
dataMsg - An arbitrary data message to be sent to the server
References d, msg, sendData_(), and t.
start_() [1/3]
Connection::start_ () [inline]
Starts a connection attempt
References BYTES_RECEIVED_HEALTHY_OVERRIDE, BYTES_SENT_HEALTHY_OVERRIDE, close(), connReceiver_(), disconnReceiver_(), nextTransportId_(), and setTimeoutNonBlocking.
start_() [2/3]
Connection::start_ () [inline]
Starts a connection attempt
References BYTES_RECEIVED_HEALTHY_OVERRIDE, BYTES_SENT_HEALTHY_OVERRIDE, close(), connReceiver_(), disconnReceiver_(), nextTransportId_(), and setTimeoutNonBlocking.
start_() [3/3]
Connection::start_ () [inline]
Starts a connection attempt
References BYTES_RECEIVED_HEALTHY_OVERRIDE, BYTES_SENT_HEALTHY_OVERRIDE, close(), connReceiver_(), disconnReceiver_(), nextTransportId_(), and setTimeoutNonBlocking.
startUpgrade_() [1/3]
Connection::startUpgrade_ (conn) [inline]
References connReceiver_(), disconnReceiver_(), nextTransportId_(), setTimeoutNonBlocking, and UPGRADE_TIMEOUT.
startUpgrade_() [2/3]
Connection::startUpgrade_ (conn) [inline]
References connReceiver_(), disconnReceiver_(), nextTransportId_(), setTimeoutNonBlocking, and UPGRADE_TIMEOUT.
startUpgrade_() [3/3]
Connection::startUpgrade_ (conn) [inline]
References connReceiver_(), disconnReceiver_(), nextTransportId_(), setTimeoutNonBlocking, and UPGRADE_TIMEOUT.
tryCleanupConnection() [1/3]
Connection::tryCleanupConnection () [inline]
tryCleanupConnection() [2/3]
Connection::tryCleanupConnection () [inline]
tryCleanupConnection() [3/3]
Connection::tryCleanupConnection () [inline]
tryStartUpgrade_() [1/3]
Connection::tryStartUpgrade_ () [inline]
References startUpgrade_().
tryStartUpgrade_() [2/3]
Connection::tryStartUpgrade_ () [inline]
References startUpgrade_().
tryStartUpgrade_() [3/3]
Connection::tryStartUpgrade_ () [inline]
References startUpgrade_().
upgradeIfSecondaryHealthy_() [1/3]
Connection::upgradeIfSecondaryHealthy_ () [inline]
References d, PING, proceedWithUpgrade_(), and t.
upgradeIfSecondaryHealthy_() [2/3]
Connection::upgradeIfSecondaryHealthy_ () [inline]
References d, PING, proceedWithUpgrade_(), and t.
upgradeIfSecondaryHealthy_() [3/3]
Connection::upgradeIfSecondaryHealthy_ () [inline]
References d, PING, proceedWithUpgrade_(), and t.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js