Observable Class Reference
Public Member Functions
constructor (subscribe)
lift (operator)
subscribe (observerOrNext, error, complete)
_trySubscribe (sink)
forEach (next, promiseCtor)
_subscribe (subscriber)
pipe (...operations)
toPromise (promiseCtor)
Member Function Documentation
_subscribe()
Observable::_subscribe (subscriber) [inline]
References _a, and source.
_trySubscribe()
Observable::_trySubscribe (sink) [inline]
References _subscribe().
constructor()
Observable::constructor (subscribe) [inline]
References _subscribe(), and subscribe().
forEach()
Observable::forEach (next, promiseCtor) [inline]
References error, getPromiseCtor(), next(), reject(), resolve, SafeSubscriber, subscribe(), and value.
lift()
Observable::lift (operator) [inline]
References Observable, and observable.
pipe()
Observable::pipe (...) [inline]
References pipeFromArray.
subscribe()
Observable::subscribe (observerOrNext, error, complete) [inline]
References _subscribe(), _trySubscribe(), call, error, errorContext, isSubscriber(), SafeSubscriber, and source.
toPromise()
Observable::toPromise (promiseCtor) [inline]
References getPromiseCtor(), reject(), resolve, subscribe(), and value.
The documentation for this class was generated from the following file:
backend/node_modules/rxjs/dist/esm/internal/Observable.js