BrowserPollConnection Class Reference
Public Member Functions
constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId)
open (onMessage, onDisconnect)
start ()
markConnectionHealthy ()
shutdown_ ()
onClosed_ ()
close ()
send (data)
addDisconnectPingFrame (id, pw)
incrementIncomingBytes_ (args)
constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId)
open (onMessage, onDisconnect)
start ()
markConnectionHealthy ()
shutdown_ ()
onClosed_ ()
close ()
send (data)
addDisconnectPingFrame (id, pw)
incrementIncomingBytes_ (args)
constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId)
open (onMessage, onDisconnect)
start ()
markConnectionHealthy ()
shutdown_ ()
onClosed_ ()
close ()
send (data)
addDisconnectPingFrame (id, pw)
incrementIncomingBytes_ (args)
Static Public Member Functions
static forceAllow ()
static forceDisallow ()
static isAvailable ()
static forceAllow ()
static forceDisallow ()
static isAvailable ()
static forceAllow ()
static forceDisallow ()
static isAvailable ()
Detailed Description
This class manages a single long-polling connection.
Member Function Documentation
addDisconnectPingFrame() [1/3]
BrowserPollConnection::addDisconnectPingFrame (id, pw) [inline]
This is how we notify the server that we're leaving. We aren't able to send requests with DHTML on a window close event, but we can trigger XHR requests in some browsers (everything but Opera basically).
References FIREBASE_LONGPOLL_DISCONN_FRAME_REQUEST_PARAM, FIREBASE_LONGPOLL_ID_PARAM, FIREBASE_LONGPOLL_PW_PARAM, and util.
addDisconnectPingFrame() [2/3]
BrowserPollConnection::addDisconnectPingFrame (id, pw) [inline]
This is how we notify the server that we're leaving. We aren't able to send requests with DHTML on a window close event, but we can trigger XHR requests in some browsers (everything but Opera basically).
References FIREBASE_LONGPOLL_DISCONN_FRAME_REQUEST_PARAM, FIREBASE_LONGPOLL_ID_PARAM, FIREBASE_LONGPOLL_PW_PARAM, and isNodeSdk.
addDisconnectPingFrame() [3/3]
BrowserPollConnection::addDisconnectPingFrame (id, pw) [inline]
This is how we notify the server that we're leaving. We aren't able to send requests with DHTML on a window close event, but we can trigger XHR requests in some browsers (everything but Opera basically).
References FIREBASE_LONGPOLL_DISCONN_FRAME_REQUEST_PARAM, FIREBASE_LONGPOLL_ID_PARAM, FIREBASE_LONGPOLL_PW_PARAM, and isNodeSdk.
close() [1/3]
BrowserPollConnection::close () [inline]
External-facing close handler. RealTime has requested we shut down. Kill our connection and tell the server that we've left.
References shutdown_().
close() [2/3]
BrowserPollConnection::close () [inline]
External-facing close handler. RealTime has requested we shut down. Kill our connection and tell the server that we've left.
References shutdown_().
close() [3/3]
BrowserPollConnection::close () [inline]
External-facing close handler. RealTime has requested we shut down. Kill our connection and tell the server that we've left.
References shutdown_().
constructor() [1/3]
BrowserPollConnection::constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId) [inline]
Parameters
connId An identifier for this connection, used for logging
repoInfo The info for the endpoint to send data to.
applicationId The Firebase App ID for this project.
appCheckToken The AppCheck token for this client.
authToken The AuthToken to use for this connection.
transportSessionId Optional transportSessionid if we are reconnecting for an existing transport session
lastSessionId Optional lastSessionId if the PersistentConnection has already created a connection previously
References APP_CHECK_TOKEN_PARAM, logWrapper, LONG_POLLING, repoInfoConnectionURL(), and statsManagerGetCollection().
constructor() [2/3]
BrowserPollConnection::constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId) [inline]
Parameters
connId An identifier for this connection, used for logging
repoInfo The info for the endpoint to send data to.
applicationId The Firebase App ID for this project.
appCheckToken The AppCheck token for this client.
authToken The AuthToken to use for this connection.
transportSessionId Optional transportSessionid if we are reconnecting for an existing transport session
lastSessionId Optional lastSessionId if the PersistentConnection has already created a connection previously
References APP_CHECK_TOKEN_PARAM, logWrapper, LONG_POLLING, repoInfoConnectionURL(), and statsManagerGetCollection().
constructor() [3/3]
BrowserPollConnection::constructor (connId, repoInfo, applicationId, appCheckToken, authToken, transportSessionId, lastSessionId) [inline]
Parameters
connId An identifier for this connection, used for logging
repoInfo The info for the endpoint to send data to.
applicationId The Firebase App ID for this project.
appCheckToken The AppCheck token for this client.
authToken The AuthToken to use for this connection.
transportSessionId Optional transportSessionid if we are reconnecting for an existing transport session
lastSessionId Optional lastSessionId if the PersistentConnection has already created a connection previously
References APP_CHECK_TOKEN_PARAM, logWrapper, LONG_POLLING, repoInfoConnectionURL(), and statsManagerGetCollection().
forceAllow() [1/3]
static BrowserPollConnection::forceAllow () [inline], [static]
Forces long polling to be considered as a potential transport
forceAllow() [2/3]
static BrowserPollConnection::forceAllow () [inline], [static]
Forces long polling to be considered as a potential transport
forceAllow() [3/3]
static BrowserPollConnection::forceAllow () [inline], [static]
Forces long polling to be considered as a potential transport
forceDisallow() [1/3]
static BrowserPollConnection::forceDisallow () [inline], [static]
Forces longpolling to not be considered as a potential transport
forceDisallow() [2/3]
static BrowserPollConnection::forceDisallow () [inline], [static]
Forces longpolling to not be considered as a potential transport
forceDisallow() [3/3]
static BrowserPollConnection::forceDisallow () [inline], [static]
Forces longpolling to not be considered as a potential transport
incrementIncomingBytes_() [1/3]
BrowserPollConnection::incrementIncomingBytes_ (args) [inline]
Used to track the bytes received by this client
References args, and util.
incrementIncomingBytes_() [2/3]
BrowserPollConnection::incrementIncomingBytes_ (args) [inline]
Used to track the bytes received by this client
References args, and stringify.
incrementIncomingBytes_() [3/3]
BrowserPollConnection::incrementIncomingBytes_ (args) [inline]
Used to track the bytes received by this client
References args, and stringify.
isAvailable() [1/3]
static BrowserPollConnection::isAvailable () [inline], [static]
References isChromeExtensionContentScript, isWindowsStoreApp, and util.
isAvailable() [2/3]
static BrowserPollConnection::isAvailable () [inline], [static]
References isChromeExtensionContentScript, isNodeSdk, and isWindowsStoreApp.
isAvailable() [3/3]
static BrowserPollConnection::isAvailable () [inline], [static]
References isChromeExtensionContentScript, isNodeSdk, and isWindowsStoreApp.
markConnectionHealthy() [1/3]
BrowserPollConnection::markConnectionHealthy () [inline]
No-op for polling
markConnectionHealthy() [2/3]
BrowserPollConnection::markConnectionHealthy () [inline]
No-op for polling
markConnectionHealthy() [3/3]
BrowserPollConnection::markConnectionHealthy () [inline]
No-op for polling
onClosed_() [1/3]
BrowserPollConnection::onClosed_ () [inline]
Triggered when this transport is closed
References shutdown_().
onClosed_() [2/3]
BrowserPollConnection::onClosed_ () [inline]
Triggered when this transport is closed
References shutdown_().
onClosed_() [3/3]
BrowserPollConnection::onClosed_ () [inline]
Triggered when this transport is closed
References shutdown_().
open() [1/3]
BrowserPollConnection::open (onMessage, onDisconnect) [inline]
Parameters
onMessage - Callback when messages arrive
onDisconnect - Callback with connection lost.
References APP_CHECK_TOKEN_PARAM, APPLICATION_ID_PARAM, args, command(), data, executeWhenDOMReady, FIREBASE_LONGPOLL_CALLBACK_ID_PARAM, FIREBASE_LONGPOLL_CLOSE_COMMAND, FIREBASE_LONGPOLL_SERIAL_PARAM, FIREBASE_LONGPOLL_START_PARAM, FirebaseIFrameScriptHolder, FORGE_DOMAIN_RE, FORGE_REF, incrementIncomingBytes_(), LAST_SESSION_PARAM, location, LP_CONNECT_TIMEOUT, onClosed_(), PacketReceiver, PROTOCOL_VERSION, REFERER_PARAM, TRANSPORT_SESSION_PARAM, and VERSION_PARAM.
open() [2/3]
BrowserPollConnection::open (onMessage, onDisconnect) [inline]
Parameters
onMessage - Callback when messages arrive
onDisconnect - Callback with connection lost.
References APP_CHECK_TOKEN_PARAM, APPLICATION_ID_PARAM, args, command(), data, executeWhenDOMReady, FIREBASE_LONGPOLL_CALLBACK_ID_PARAM, FIREBASE_LONGPOLL_CLOSE_COMMAND, FIREBASE_LONGPOLL_SERIAL_PARAM, FIREBASE_LONGPOLL_START_PARAM, FirebaseIFrameScriptHolder, FORGE_DOMAIN_RE, FORGE_REF, incrementIncomingBytes_(), LAST_SESSION_PARAM, location, LP_CONNECT_TIMEOUT, onClosed_(), PacketReceiver, PROTOCOL_VERSION, REFERER_PARAM, TRANSPORT_SESSION_PARAM, and VERSION_PARAM.
open() [3/3]
BrowserPollConnection::open (onMessage, onDisconnect) [inline]
Parameters
onMessage - Callback when messages arrive
onDisconnect - Callback with connection lost.
References APP_CHECK_TOKEN_PARAM, APPLICATION_ID_PARAM, args, command(), data, executeWhenDOMReady, FIREBASE_LONGPOLL_CALLBACK_ID_PARAM, FIREBASE_LONGPOLL_CLOSE_COMMAND, FIREBASE_LONGPOLL_SERIAL_PARAM, FIREBASE_LONGPOLL_START_PARAM, FirebaseIFrameScriptHolder, FORGE_DOMAIN_RE, FORGE_REF, incrementIncomingBytes_(), LAST_SESSION_PARAM, location, LP_CONNECT_TIMEOUT, onClosed_(), PacketReceiver, PROTOCOL_VERSION, REFERER_PARAM, TRANSPORT_SESSION_PARAM, and VERSION_PARAM.
send() [1/3]
BrowserPollConnection::send (data) [inline]
Send the JSON object down to the server. It will need to be stringified, base64 encoded, and then broken into chunks (since URLs have a small maximum length).
Parameters
data - The JSON data to transmit.
References data, dataStr, i, MAX_PAYLOAD_SIZE, splitStringBySize, and util.
send() [2/3]
BrowserPollConnection::send (data) [inline]
Send the JSON object down to the server. It will need to be stringified, base64 encoded, and then broken into chunks (since URLs have a small maximum length).
Parameters
data - The JSON data to transmit.
References base64Encode, data, dataStr, i, MAX_PAYLOAD_SIZE, splitStringBySize, and stringify.
send() [3/3]
BrowserPollConnection::send (data) [inline]
Send the JSON object down to the server. It will need to be stringified, base64 encoded, and then broken into chunks (since URLs have a small maximum length).
Parameters
data - The JSON data to transmit.
References base64Encode, data, dataStr, i, MAX_PAYLOAD_SIZE, splitStringBySize, and stringify.
shutdown_() [1/3]
BrowserPollConnection::shutdown_ () [inline]
Stops polling and cleans up the iframe Here is the caller graph for this function:
shutdown_() [2/3]
BrowserPollConnection::shutdown_ () [inline]
Stops polling and cleans up the iframe
shutdown_() [3/3]
BrowserPollConnection::shutdown_ () [inline]
Stops polling and cleans up the iframe
start() [1/3]
BrowserPollConnection::start () [inline]
Call this when a handshake has completed successfully and we want to consider the connection established
References addDisconnectPingFrame().
start() [2/3]
BrowserPollConnection::start () [inline]
Call this when a handshake has completed successfully and we want to consider the connection established
References addDisconnectPingFrame().
start() [3/3]
BrowserPollConnection::start () [inline]
Call this when a handshake has completed successfully and we want to consider the connection established
References addDisconnectPingFrame().
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js