BundleBuilder Class Reference
Public Member Functions
constructor (bundleId)
add (documentOrName, querySnapshot)
addBundledDocument (snap, queryName)
addNamedQuery (name, querySnap)
build ()
Private Member Functions
elementToLengthPrefixedBuffer (bundleElement)
Detailed Description
Builds a Firestore data bundle with results from the given document and query snapshots.
Member Function Documentation
add()
BundleBuilder::add (documentOrName, querySnapshot) [inline]
References addBundledDocument(), addNamedQuery(), validate_1, validateDocumentSnapshot(), and validateQuerySnapshot().
addBundledDocument()
BundleBuilder::addBundledDocument (snap, queryName) [inline]
References timestamp_1.
addNamedQuery()
BundleBuilder::addNamedQuery (name, querySnap) [inline]
References $, has, name, and of.
build()
BundleBuilder::build () [inline]
References BUNDLE_VERSION, of, and version.
constructor()
BundleBuilder::constructor (bundleId) [inline]
References Map, and timestamp_1.
elementToLengthPrefixedBuffer()
BundleBuilder::elementToLengthPrefixedBuffer (bundleElement) [inline], [private]
Converts a IBundleElement to a Buffer whose content is the length prefixed JSON representation of the element.
References buffer, JSON, message, and require().
The documentation for this class was generated from the following file:
backend/node_modules/@google-cloud/firestore/build/src/bundle.js