CommandInstance Class Reference
Public Member Functions
constructor (usage, validation, globalMiddleware, shim)
addDirectory (dir, req, callerFile, opts)
addHandler (cmd, description, builder, handler, commandMiddleware, deprecated)
getCommandHandlers ()
getCommands ()
hasDefaultCommand ()
runCommand (command, yargs, parsed, commandIndex, helpOnly, helpOrVersionSet)
applyBuilderUpdateUsageAndParse (isDefaultCommand, commandHandler, yargs, aliases, parentCommands, commandIndex, helpOnly, helpOrVersionSet)
parseAndUpdateUsage (isDefaultCommand, commandHandler, innerYargs, parentCommands, commandIndex, helpOnly)
shouldUpdateUsage (yargs)
usageFromParentCommandsCommandHandler (parentCommands, commandHandler)
handleValidationAndGetResult (isDefaultCommand, commandHandler, innerArgv, currentContext, aliases, yargs, middlewares, positionalMap)
applyMiddlewareAndGetResult (isDefaultCommand, commandHandler, innerArgv, currentContext, helpOnly, aliases, yargs)
populatePositionals (commandHandler, argv, context, yargs)
populatePositional (positional, argv, positionalMap)
cmdToParseOptions (cmdString)
postProcessPositionals (argv, positionalMap, parseOptions, yargs)
isDefaulted (yargs, key)
isInConfigs (yargs, key)
runDefaultBuilderOn (yargs)
moduleName (obj)
commandFromFilename (filename)
extractDesc ({ describe, description, desc })
freeze ()
unfreeze ()
reset ()
Member Function Documentation
addDirectory()
CommandInstance::addDirectory (dir, req, callerFile, opts) [inline]
References addHandler(), Array, filename, o, obj, req, require(), and shim.
addHandler()
CommandInstance::addHandler (cmd, description, builder, handler, commandMiddleware, deprecated) [inline]
References addHandler(), alias(), Array, c, command(), commandMiddlewareFactory(), concat, DEFAULT_MARKER, extractDesc(), isCommandAndAliases(), isCommandBuilderDefinition(), isCommandHandlerDefinition(), moduleName(), of, parseCommand(), and usage().
applyBuilderUpdateUsageAndParse()
CommandInstance::applyBuilderUpdateUsageAndParse (isDefaultCommand, commandHandler, yargs, aliases, parentCommands, commandIndex, helpOnly, helpOrVersionSet) [inline]
References isCommandBuilderCallback(), isCommandBuilderOptionDefinitions(), isPromise, isYargsInstance(), parseAndUpdateUsage(), and yargs.
applyMiddlewareAndGetResult()
CommandInstance::applyMiddlewareAndGetResult (isDefaultCommand, commandHandler, innerArgv, currentContext, helpOnly, aliases, yargs) [inline]
References applyMiddleware(), handleValidationAndGetResult(), isPromise, populatePositionals(), and yargs.
cmdToParseOptions()
CommandInstance::cmdToParseOptions (cmdString) [inline]
References alias(), d, o, and parseCommand().
commandFromFilename()
CommandInstance::commandFromFilename (filename) [inline]
References filename, and shim.
constructor()
CommandInstance::constructor (usage, validation, globalMiddleware, shim) [inline]
References Set, shim, usage(), and validation().
extractDesc()
CommandInstance::extractDesc ({ describe, description, desc }) [inline]
References describe().
freeze()
CommandInstance::freeze () [inline]
getCommandHandlers()
CommandInstance::getCommandHandlers () [inline]
getCommands()
CommandInstance::getCommands () [inline]
handleValidationAndGetResult()
CommandInstance::handleValidationAndGetResult (isDefaultCommand, commandHandler, innerArgv, currentContext, aliases, yargs, middlewares, positionalMap) [inline]
References applyMiddleware(), error, isPromise, maybeAsyncResult(), result, validation(), and yargs.
hasDefaultCommand()
CommandInstance::hasDefaultCommand () [inline]
isDefaulted()
CommandInstance::isDefaulted (yargs, key) [inline]
References defaults, and yargs.
isInConfigs()
CommandInstance::isInConfigs (yargs, key) [inline]
References c, and yargs.
moduleName()
CommandInstance::moduleName (obj) [inline]
References $, command(), commandFromFilename(), mod, module, name, obj, shim, and whichModule().
parseAndUpdateUsage()
CommandInstance::parseAndUpdateUsage (isDefaultCommand, commandHandler, innerYargs, parentCommands, commandIndex, helpOnly) [inline]
References isPromise, shouldUpdateUsage(), undefined, and usageFromParentCommandsCommandHandler().
populatePositional()
CommandInstance::populatePositional (positional, argv, positionalMap) [inline]
populatePositionals()
CommandInstance::populatePositionals (commandHandler, argv, context, yargs) [inline]
References a, cmdToParseOptions(), context, populatePositional(), postProcessPositionals(), validation(), and yargs.
postProcessPositionals()
CommandInstance::postProcessPositionals (argv, positionalMap, parseOptions, yargs) [inline]
References $, Array, concat, config, isDefaulted(), isInConfigs(), of, shim, value, and yargs.
reset()
CommandInstance::reset () [inline]
References Set, and undefined.
runCommand()
CommandInstance::runCommand (command, yargs, parsed, commandIndex, helpOnly, helpOrVersionSet) [inline]
References applyBuilderUpdateUsageAndParse(), applyMiddlewareAndGetResult(), command(), isPromise, result, and yargs.
runDefaultBuilderOn()
CommandInstance::runDefaultBuilderOn (yargs) [inline]
References DEFAULT_MARKER, isCommandBuilderCallback(), isCommandBuilderDefinition(), shouldUpdateUsage(), undefined, and yargs.
shouldUpdateUsage()
CommandInstance::shouldUpdateUsage (yargs) [inline]
References yargs.
unfreeze()
CommandInstance::unfreeze () [inline]
References assertNotStrictEqual(), shim, and undefined.
usageFromParentCommandsCommandHandler()
CommandInstance::usageFromParentCommandsCommandHandler (parentCommands, commandHandler) [inline]
References $, c, and DEFAULT_MARKER.
The documentation for this class was generated from the following file:
backend/node_modules/yargs/build/lib/command.js