PickFirstLoadBalancer Class Reference
Public Member Functions
constructor (channelControlHelper, credentials, options)
allChildrenHaveReportedTF ()
resetChildrenReportedTF ()
calculateAndReportNewState ()
requestReresolution ()
maybeEnterStickyTransientFailureMode ()
removeCurrentPick ()
onSubchannelStateUpdate (subchannel, previousState, newState, errorMessage)
startNextSubchannelConnecting (startIndex)
startConnecting (subchannelIndex)
pickSubchannel (subchannel)
updateState (newState, picker)
resetSubchannelList ()
connectToAddressList (addressList)
updateAddressList (endpointList, lbConfig)
exitIdle ()
resetBackoff ()
destroy ()
getTypeName ()
Member Function Documentation
allChildrenHaveReportedTF()
PickFirstLoadBalancer::allChildrenHaveReportedTF () [inline]
calculateAndReportNewState()
PickFirstLoadBalancer::calculateAndReportNewState () [inline]
References connectivity_state_1, is, picker_1, and updateState().
connectToAddressList()
PickFirstLoadBalancer::connectToAddressList (addressList) [inline]
References connectivity_state_1, of, subchannel_address_1, and trace.
constructor()
PickFirstLoadBalancer::constructor (channelControlHelper, credentials, options) [inline]
Load balancer that attempts to connect to each backend in the address list in order, and picks the first one that connects, using it for every request.
Parameters
channelControlHelper ChannelControlHelper instance provided by this load balancer's owner.
The list of subchannels this load balancer is currently attempting to connect to.
The current connectivity state of the load balancer.
The index within the subchannels array of the subchannel with the most recently started connection attempt.
The currently picked subchannel used for making calls. Populated if and only if the load balancer's current state is READY. In that case, the subchannel's current state is also READY.
Listener callback attached to each subchannel in the subchannels list while establishing a connection.
The LB policy enters sticky TRANSIENT_FAILURE mode when all subchannels have failed to connect at least once, and it stays in that mode until a connection attempt is successful. While in sticky TF mode, the LB policy continuously attempts to connect to all of its subchannels.
The most recent error reported by any subchannel as it transitioned to TRANSIENT_FAILURE.
References calculateAndReportNewState(), connectivity_state_1, onSubchannelStateUpdate(), and REPORT_HEALTH_STATUS_OPTION_NAME.
destroy()
PickFirstLoadBalancer::destroy () [inline]
exitIdle()
PickFirstLoadBalancer::exitIdle () [inline]
References connectivity_state_1.
getTypeName()
PickFirstLoadBalancer::getTypeName () [inline]
References TYPE_NAME.
maybeEnterStickyTransientFailureMode()
PickFirstLoadBalancer::maybeEnterStickyTransientFailureMode () [inline]
References of.
onSubchannelStateUpdate()
PickFirstLoadBalancer::onSubchannelStateUpdate (subchannel, previousState, newState, errorMessage) [inline]
References _a, connectivity_state_1, index, and of.
pickSubchannel()
PickFirstLoadBalancer::pickSubchannel (subchannel) [inline]
Declare that the specified subchannel should be used to make requests. This functions the same independent of whether subchannel is a member of this.children and whether it is equal to this.currentPick. Prerequisite: subchannel.getConnectivityState() === READY.
Parameters
subchannel
References trace.
removeCurrentPick()
PickFirstLoadBalancer::removeCurrentPick () [inline]
requestReresolution()
PickFirstLoadBalancer::requestReresolution () [inline]
resetBackoff()
PickFirstLoadBalancer::resetBackoff () [inline]
resetChildrenReportedTF()
PickFirstLoadBalancer::resetChildrenReportedTF () [inline]
resetSubchannelList()
PickFirstLoadBalancer::resetSubchannelList () [inline]
References of.
startConnecting()
PickFirstLoadBalancer::startConnecting (subchannelIndex) [inline]
Have a single subchannel in the subchannels list start connecting.
Parameters
subchannelIndex The index into the subchannels list.
References _a, _b, CONNECTION_DELAY_INTERVAL_MS, connectivity_state_1, process, and trace.
startNextSubchannelConnecting()
PickFirstLoadBalancer::startNextSubchannelConnecting (startIndex) [inline]
References connectivity_state_1, index, of, and startIndex().
updateAddressList()
PickFirstLoadBalancer::updateAddressList (endpointList, lbConfig) [inline]
References interleaveAddressFamilies(), shuffled, subchannel_address_1, and trace.
updateState()
PickFirstLoadBalancer::updateState (newState, picker) [inline]
References connectivity_state_1, and trace.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js