FirebaseTokenVerifier Class Reference
Public Member Functions
constructor (clientCertUrl, issuer, tokenInfo, app)
verifyJWT (jwtToken, isEmulator=false)
_verifyAuthBlockingToken (jwtToken, isEmulator, audience)
ensureProjectId ()
decodeAndVerify (token, projectId, isEmulator, audience)
safeDecode (jwtToken)
verifyContent (fullDecodedToken, projectId, isEmulator, audience)
verifySignature (jwtToken, isEmulator)
mapJwtErrorToAuthError (error)
Detailed Description
Class for verifying general purpose Firebase JWTs. This verifies ID tokens and session cookies.
Member Function Documentation
_verifyAuthBlockingToken()
FirebaseTokenVerifier::_verifyAuthBlockingToken (jwtToken, isEmulator, audience) [inline]
@alpha
References $, a, decodeAndVerify(), ensureProjectId(), error_1, then, and validator.
constructor()
FirebaseTokenVerifier::constructor (clientCertUrl, issuer, tokenInfo, app) [inline]
References app, error_1, i, jwt_1, and validator.
decodeAndVerify()
FirebaseTokenVerifier::decodeAndVerify (token, projectId, isEmulator, audience) [inline]
References safeDecode(), token, verifyContent(), and verifySignature().
ensureProjectId()
FirebaseTokenVerifier::ensureProjectId () [inline]
References $, app, call, error_1, Promise, util, and validator.
mapJwtErrorToAuthError()
FirebaseTokenVerifier::mapJwtErrorToAuthError (error) [inline]
Maps JwtError to FirebaseAuthError
Parameters
error - JwtError to be mapped.
Returns
FirebaseAuthError or Error instance.
safeDecode()
FirebaseTokenVerifier::safeDecode (jwtToken) [inline]
References $, error_1, jwt_1, and on.
verifyContent()
FirebaseTokenVerifier::verifyContent (fullDecodedToken, projectId, isEmulator, audience) [inline]
Verifies the content of a Firebase Auth JWT.
Parameters
fullDecodedToken - The decoded JWT.
projectId - The Firebase Project Id.
isEmulator - Whether the token is an Emulator token.
References $, a, custom, FIREBASE_AUDIENCE, has, jwt_1, on, and token.
verifyJWT()
FirebaseTokenVerifier::verifyJWT (jwtToken, isEmulator = false) [inline]
Verifies the format and signature of a Firebase Auth JWT token.
Parameters
jwtToken - The Firebase Auth JWT token to verify.
isEmulator - Whether to accept Auth Emulator tokens.
Returns
A promise fulfilled with the decoded claims of the Firebase Auth ID token.
References $, a, decodeAndVerify(), ensureProjectId(), error_1, then, and validator.
verifySignature()
FirebaseTokenVerifier::verifySignature (jwtToken, isEmulator) [inline]
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/auth/token-verifier.js