DOMStorageWrapper Class Reference
Public Member Functions
constructor (domStorage_)
set (key, value)
get (key)
remove (key)
prefixedName_ (name)
toString ()
constructor (domStorage_)
set (key, value)
get (key)
remove (key)
prefixedName_ (name)
toString ()
constructor (domStorage_)
set (key, value)
get (key)
remove (key)
prefixedName_ (name)
toString ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Wraps a DOM Storage object and:
automatically encode objects as JSON strings before storing them to allow us to store arbitrary types.
prefixes names with "firebase:" to avoid collisions with app data.
We automatically (see storage.js) create two such wrappers, one for sessionStorage, and one for localStorage.
Member Function Documentation
constructor() [1/3]
DOMStorageWrapper::constructor (domStorage_) [inline]
Parameters
domStorage_ - The underlying storage object (e.g. localStorage or sessionStorage)
constructor() [2/3]
DOMStorageWrapper::constructor (domStorage_) [inline]
Parameters
domStorage_ - The underlying storage object (e.g. localStorage or sessionStorage)
constructor() [3/3]
DOMStorageWrapper::constructor (domStorage_) [inline]
Parameters
domStorage_ - The underlying storage object (e.g. localStorage or sessionStorage)
get() [1/3]
DOMStorageWrapper::get (key) [inline]
Returns
The value that was stored under this key, or null
References prefixedName_(), and util.
get() [2/3]
DOMStorageWrapper::get (key) [inline]
Returns
The value that was stored under this key, or null
References jsonEval, and prefixedName_().
get() [3/3]
DOMStorageWrapper::get (key) [inline]
Returns
The value that was stored under this key, or null
References jsonEval, and prefixedName_().
prefixedName_() [1/3]
DOMStorageWrapper::prefixedName_ (name) [inline]
References name.
prefixedName_() [2/3]
DOMStorageWrapper::prefixedName_ (name) [inline]
References name.
prefixedName_() [3/3]
DOMStorageWrapper::prefixedName_ (name) [inline]
References name.
remove() [1/3]
DOMStorageWrapper::remove (key) [inline]
References prefixedName_().
remove() [2/3]
DOMStorageWrapper::remove (key) [inline]
References prefixedName_().
remove() [3/3]
DOMStorageWrapper::remove (key) [inline]
References prefixedName_().
set() [1/3]
DOMStorageWrapper::set (key, value) [inline]
Parameters
key - The key to save the value under
value - The value being stored, or null to remove the key.
References prefixedName_(), util, and value.
set() [2/3]
DOMStorageWrapper::set (key, value) [inline]
Parameters
key - The key to save the value under
value - The value being stored, or null to remove the key.
References prefixedName_(), stringify, and value.
set() [3/3]
DOMStorageWrapper::set (key, value) [inline]
Parameters
key - The key to save the value under
value - The value being stored, or null to remove the key.
References prefixedName_(), stringify, and value.
toString() [1/3]
DOMStorageWrapper::toString () [inline]
toString() [2/3]
DOMStorageWrapper::toString () [inline]
toString() [3/3]
DOMStorageWrapper::toString () [inline]
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js