RoundRobinLoadBalancer Class Reference
Public Member Functions
constructor (channelControlHelper, credentials, options)
countChildrenWithState (state)
calculateAndUpdateState ()
updateState (newState, picker)
resetSubchannelList ()
updateAddressList (endpointList, lbConfig)
exitIdle ()
resetBackoff ()
destroy ()
getTypeName ()
Member Function Documentation
calculateAndUpdateState()
RoundRobinLoadBalancer::calculateAndUpdateState () [inline]
References connectivity_state_1, countChildrenWithState(), index, picker_1, subchannel_address_1, and updateState().
constructor()
RoundRobinLoadBalancer::constructor (channelControlHelper, credentials, options) [inline]
References calculateAndUpdateState(), connectivity_state_1, credentials, load_balancer_1, and updateState().
countChildrenWithState()
RoundRobinLoadBalancer::countChildrenWithState (state) [inline]
References state().
destroy()
RoundRobinLoadBalancer::destroy () [inline]
exitIdle()
RoundRobinLoadBalancer::exitIdle () [inline]
getTypeName()
RoundRobinLoadBalancer::getTypeName () [inline]
References TYPE_NAME.
resetBackoff()
RoundRobinLoadBalancer::resetBackoff () [inline]
resetSubchannelList()
RoundRobinLoadBalancer::resetSubchannelList () [inline]
References of.
updateAddressList()
RoundRobinLoadBalancer::updateAddressList (endpointList, lbConfig) [inline]
References load_balancer_pick_first_1, of, subchannel_address_1, and trace.
updateState()
RoundRobinLoadBalancer::updateState (newState, picker) [inline]
References connectivity_state_1, and trace.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/load-balancer-round-robin.js