MachineLearningApiClient Class Reference
Public Member Functions
constructor (app)
createModel (model)
updateModel (modelId, model, updateMask)
getModel (modelId)
getOperation (operationName)
listModels (options={})
deleteModel (modelId)
handleOperation (op, options)
pollOperationWithExponentialBackoff (opName, options)
getResourceWithShortName (name)
getResourceWithFullName (fullName)
sendRequest (request)
toFirebaseError (err)
getProjectUrl ()
getProjectIdPrefix ()
getModelName (modelId)
Detailed Description
Class that facilitates sending requests to the Firebase ML backend API.
Member Function Documentation
constructor()
MachineLearningApiClient::constructor (app) [inline]
References api_request_1, app, machine_learning_utils_1, and validator.
createModel()
MachineLearningApiClient::createModel (model) [inline]
References $, data, getProjectUrl(), machine_learning_utils_1, method, models, Promise, request, sendRequest(), url, and validator.
deleteModel()
MachineLearningApiClient::deleteModel (modelId) [inline]
References $, getModelName(), getProjectUrl(), method, request, sendRequest(), and url.
getModel()
MachineLearningApiClient::getModel (modelId) [inline]
References getModelName(), getResourceWithShortName(), Promise, and then.
getModelName()
MachineLearningApiClient::getModelName (modelId) [inline]
References $, machine_learning_utils_1, models, and validator.
getOperation()
MachineLearningApiClient::getOperation (operationName) [inline]
References getResourceWithFullName(), and Promise.
getProjectIdPrefix()
MachineLearningApiClient::getProjectIdPrefix () [inline]
References $, app, machine_learning_utils_1, Promise, utils, and validator.
getProjectUrl()
MachineLearningApiClient::getProjectUrl () [inline]
References $, getProjectIdPrefix(), and ML_V1BETA2_API.
getResourceWithFullName()
MachineLearningApiClient::getResourceWithFullName (fullName) [inline]
Gets the specified resource from the ML API. Resource names must be the full names including project number prefix.
Parameters
fullName - Full resource name of the resource to get. e.g. projects/123465/operations/987654
Returns
{Promise<T>} A promise that fulfulls with the resource.
References $, method, ML_V1BETA2_API, request, sendRequest(), and url.
getResourceWithShortName()
MachineLearningApiClient::getResourceWithShortName (name) [inline]
Gets the specified resource from the ML API. Resource names must be the short names without project ID prefix (e.g. models/123456789).
Parameters
{string} name Short name of the resource to get. e.g. 'models/12345'
Returns
{Promise<T>} A promise that fulfills with the resource.
References $, getProjectUrl(), method, name, request, sendRequest(), and url.
handleOperation()
MachineLearningApiClient::handleOperation (op, options) [inline]
Handles a Long Running Operation coming back from the server.
Parameters
op - The operation to handle
options - The options for polling
References $, extractModelId(), getModel(), JSON, machine_learning_utils_1, pollOperationWithExponentialBackoff(), Promise, and type.
listModels()
MachineLearningApiClient::listModels (options = {}) [inline]
pollOperationWithExponentialBackoff()
MachineLearningApiClient::pollOperationWithExponentialBackoff (opName, options) [inline]
References api_request_1, getOperation(), machine_learning_utils_1, POLL_BASE_WAIT_TIME_MILLISECONDS, POLL_DEFAULT_MAX_TIME_MILLISECONDS, and POLL_MAX_WAIT_TIME_MILLISECONDS.
sendRequest()
MachineLearningApiClient::sendRequest (request) [inline]
References request, and toFirebaseError().
toFirebaseError()
MachineLearningApiClient::toFirebaseError (err) [inline]
References $, and, error, error_1, ERROR_CODE_MAPPING, machine_learning_utils_1, message, response, server, and status.
updateModel()
MachineLearningApiClient::updateModel (modelId, model, updateMask) [inline]
References $, data, getProjectUrl(), machine_learning_utils_1, method, models, Promise, request, sendRequest(), url, and validator.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/machine-learning/machine-learning-api-client.js