Request Class Reference
Public Member Functions
constructor (input)
get method ()
get url ()
get headers ()
get redirect ()
get signal ()
clone ()
constructor (input)
get method ()
get url ()
get headers ()
get redirect ()
get signal ()
clone ()
Detailed Description
Request class
Parameters
Mixed input Url or Request instance
Object init Custom options
Returns
Void
Member Function Documentation
clone() [1/2]
Request::clone () [inline]
Clone this request
Returns
Request
References Request.
clone() [2/2]
Request::clone () [inline]
Clone this request
Returns
Request
References Request.
constructor() [1/2]
Request::constructor (input) [inline]
References $, Body(), clone(), compress(), contentType, extractContentType(), Headers, headers(), init, INTERNALS$2, isAbortSignal(), isRequest, method(), parseURL, redirect(), signal(), size, timeout, and undefined.
constructor() [2/2]
Request::constructor (input) [inline]
References $, Body(), clone(), compress(), contentType, extractContentType(), Headers, headers(), init, INTERNALS$2, isAbortSignal(), isRequest, method(), parseURL, redirect(), signal(), size, timeout, and undefined.
headers() [1/2]
get Request::headers () [inline]
References INTERNALS$2.
headers() [2/2]
get Request::headers () [inline]
References INTERNALS$2.
method() [1/2]
get Request::method () [inline]
References INTERNALS$2.
method() [2/2]
get Request::method () [inline]
References INTERNALS$2.
redirect() [1/2]
get Request::redirect () [inline]
References INTERNALS$2.
redirect() [2/2]
get Request::redirect () [inline]
References INTERNALS$2.
signal() [1/2]
get Request::signal () [inline]
References INTERNALS$2.
signal() [2/2]
get Request::signal () [inline]
References INTERNALS$2.
url() [1/2]
get Request::url () [inline]
References format_url, and INTERNALS$2.
url() [2/2]
get Request::url () [inline]
References format_url, and INTERNALS$2.
The documentation for this class was generated from the following files:
backend/node_modules/node-fetch/lib/index.es.js
backend/node_modules/node-fetch/lib/index.js