SnapshotHolder Class Reference
Public Member Functions
constructor ()
getNode (path)
updateSnapshot (path, newSnapshotNode)
constructor ()
getNode (path)
updateSnapshot (path, newSnapshotNode)
constructor ()
getNode (path)
updateSnapshot (path, newSnapshotNode)
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Mutable object which basically just stores a reference to the "latest" immutable snapshot.
Member Function Documentation
constructor() [1/3]
SnapshotHolder::constructor () [inline]
References ChildrenNode::EMPTY_NODE().
constructor() [2/3]
SnapshotHolder::constructor () [inline]
References ChildrenNode::EMPTY_NODE().
constructor() [3/3]
SnapshotHolder::constructor () [inline]
References ChildrenNode::EMPTY_NODE().
getNode() [1/3]
SnapshotHolder::getNode (path) [inline]
References path.
getNode() [2/3]
SnapshotHolder::getNode (path) [inline]
References path.
getNode() [3/3]
SnapshotHolder::getNode (path) [inline]
References path.
updateSnapshot() [1/3]
SnapshotHolder::updateSnapshot (path, newSnapshotNode) [inline]
References path.
updateSnapshot() [2/3]
SnapshotHolder::updateSnapshot (path, newSnapshotNode) [inline]
References path.
updateSnapshot() [3/3]
SnapshotHolder::updateSnapshot (path, newSnapshotNode) [inline]
References path.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js