FirebaseAuthTokenProvider Class Reference
Public Member Functions
constructor (appName_, firebaseOptions_, authProvider_)
getToken (forceRefresh)
addTokenChangeListener (listener)
removeTokenChangeListener (listener)
notifyForInvalidToken ()
constructor (appName_, firebaseOptions_, authProvider_)
getToken (forceRefresh)
addTokenChangeListener (listener)
removeTokenChangeListener (listener)
notifyForInvalidToken ()
constructor (appName_, firebaseOptions_, authProvider_)
getToken (forceRefresh)
addTokenChangeListener (listener)
removeTokenChangeListener (listener)
notifyForInvalidToken ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Abstraction around FirebaseApp's token fetching capabilities.
Member Function Documentation
addTokenChangeListener() [1/3]
FirebaseAuthTokenProvider::addTokenChangeListener (listener) [inline]
References auth.
addTokenChangeListener() [2/3]
FirebaseAuthTokenProvider::addTokenChangeListener (listener) [inline]
References auth.
addTokenChangeListener() [3/3]
FirebaseAuthTokenProvider::addTokenChangeListener (listener) [inline]
References auth.
constructor() [1/3]
FirebaseAuthTokenProvider::constructor (appName_, firebaseOptions_, authProvider_) [inline]
References auth.
constructor() [2/3]
FirebaseAuthTokenProvider::constructor (appName_, firebaseOptions_, authProvider_) [inline]
References auth.
constructor() [3/3]
FirebaseAuthTokenProvider::constructor (appName_, firebaseOptions_, authProvider_) [inline]
References auth.
getToken() [1/3]
FirebaseAuthTokenProvider::getToken (forceRefresh) [inline]
References error, getToken(), log, Promise, reject(), and resolve.
getToken() [2/3]
FirebaseAuthTokenProvider::getToken (forceRefresh) [inline]
References error, getToken(), log, Promise, reject(), and resolve.
getToken() [3/3]
FirebaseAuthTokenProvider::getToken (forceRefresh) [inline]
References error, getToken(), log, Promise, reject(), and resolve.
notifyForInvalidToken() [1/3]
FirebaseAuthTokenProvider::notifyForInvalidToken () [inline]
References warn.
notifyForInvalidToken() [2/3]
FirebaseAuthTokenProvider::notifyForInvalidToken () [inline]
References warn.
notifyForInvalidToken() [3/3]
FirebaseAuthTokenProvider::notifyForInvalidToken () [inline]
References warn.
removeTokenChangeListener() [1/3]
FirebaseAuthTokenProvider::removeTokenChangeListener (listener) [inline]
References auth.
removeTokenChangeListener() [2/3]
FirebaseAuthTokenProvider::removeTokenChangeListener (listener) [inline]
References auth.
removeTokenChangeListener() [3/3]
FirebaseAuthTokenProvider::removeTokenChangeListener (listener) [inline]
References auth.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database/dist/index.cjs.js
backend/node_modules/@firebase/database/dist/index.esm2017.js
backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js