ContextAPI Class Reference
Public Member Functions
constructor ()
setGlobalContextManager (contextManager)
active ()
with (context, fn, thisArg,...args)
bind (context, target)
_getContextManager ()
disable ()
constructor ()
setGlobalContextManager (contextManager)
active ()
with (context, fn, thisArg,...args)
bind (context, target)
_getContextManager ()
disable ()
Static Public Member Functions
static getInstance ()
static getInstance ()
Detailed Description
Singleton object which represents the entry point to the OpenTelemetry Context API
Member Function Documentation
_getContextManager() [1/2]
ContextAPI::_getContextManager () [inline]
References API_NAME, getGlobal, and NOOP_CONTEXT_MANAGER.
_getContextManager() [2/2]
ContextAPI::_getContextManager () [inline]
References API_NAME, global_utils_1, and NOOP_CONTEXT_MANAGER.
active() [1/2]
ContextAPI::active () [inline]
Get the currently active context
References _getContextManager().
active() [2/2]
ContextAPI::active () [inline]
Get the currently active context
References _getContextManager().
bind() [1/2]
ContextAPI::bind (context, target) [inline]
Bind a context to a target function or event emitter
Parameters
context context to bind to the event emitter or function. Defaults to the currently active context
target function or event emitter to bind
References _getContextManager(), and context.
bind() [2/2]
ContextAPI::bind (context, target) [inline]
Bind a context to a target function or event emitter
Parameters
context context to bind to the event emitter or function. Defaults to the currently active context
target function or event emitter to bind
References _getContextManager(), and context.
constructor() [1/2]
ContextAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
constructor() [2/2]
ContextAPI::constructor () [inline]
Empty private constructor prevents end users from constructing a new instance of the API
disable() [1/2]
ContextAPI::disable () [inline]
Disable and remove the global context manager
References _getContextManager(), API_NAME, DiagAPI::instance(), and unregisterGlobal.
disable() [2/2]
ContextAPI::disable () [inline]
Disable and remove the global context manager
References _getContextManager(), API_NAME, diag_1, and global_utils_1.
getInstance() [1/2]
static ContextAPI::getInstance () [inline], [static]
Get the singleton instance of the Context API
References ContextAPI.
getInstance() [2/2]
static ContextAPI::getInstance () [inline], [static]
Get the singleton instance of the Context API
References ContextAPI.
setGlobalContextManager() [1/2]
ContextAPI::setGlobalContextManager (contextManager) [inline]
Set the current context manager.
Returns
true if the context manager was successfully registered, else false
References API_NAME, DiagAPI::instance(), and registerGlobal.
setGlobalContextManager() [2/2]
ContextAPI::setGlobalContextManager (contextManager) [inline]
Set the current context manager.
Returns
true if the context manager was successfully registered, else false
References API_NAME, diag_1, and global_utils_1.
with() [1/2]
ContextAPI::with (context, fn, thisArg, ...) [inline]
Execute a function with an active context
Parameters
context context to be active during function execution
fn function to execute in a context
thisArg optional receiver to be used for calling fn
args optional arguments forwarded to fn
References _getContextManager(), args, context, and fn.
with() [2/2]
ContextAPI::with (context, fn, thisArg, ...) [inline]
Execute a function with an active context
Parameters
context context to be active during function execution
fn function to execute in a context
thisArg optional receiver to be used for calling fn
args optional arguments forwarded to fn
References _getContextManager(), args, context, and fn.
The documentation for this class was generated from the following files:
backend/node_modules/@opentelemetry/api/build/esnext/api/context.js
backend/node_modules/@opentelemetry/api/build/src/api/context.js