CertificateProviderChannelCredentialsImpl Class Reference
Public Member Functions
constructor (caCertificateProvider, identityCertificateProvider, verifyOptions)
compose (callCredentials)
_getConnectionOptions ()
_isSecure ()
_equals (other)
_ref ()
_unref ()
handleCaCertificateUpdate (update)
handleIdentityCertitificateUpdate (update)
constructor (callCredentials)
_getCallCredentials ()
Static Public Member Functions
static createSsl (rootCerts, privateKey, certChain, verifyOptions)
static createFromSecureContext (secureContext, verifyOptions)
static createInsecure ()
Member Function Documentation
_equals()
CertificateProviderChannelCredentialsImpl::_equals (other) [inline]
References _a, and _b.
_getCallCredentials()
ChannelCredentials::_getCallCredentials () [inline], [inherited]
Gets the set of per-call credentials associated with this instance.
_getConnectionOptions()
CertificateProviderChannelCredentialsImpl::_getConnectionOptions () [inline]
References _a, _b, _c, cert, ciphers, tls_1, and tls_helpers_1.
_isSecure()
CertificateProviderChannelCredentialsImpl::_isSecure () [inline]
_ref()
CertificateProviderChannelCredentialsImpl::_ref () [inline]
References _a.
_unref()
CertificateProviderChannelCredentialsImpl::_unref () [inline]
References _a.
compose()
CertificateProviderChannelCredentialsImpl::compose (callCredentials) [inline]
constructor() [1/2]
CertificateProviderChannelCredentialsImpl::constructor (caCertificateProvider, identityCertificateProvider, verifyOptions) [inline]
References handleCaCertificateUpdate(), and handleIdentityCertitificateUpdate().
constructor() [2/2]
ChannelCredentials::constructor (callCredentials) [inline], [inherited]
References call_credentials_1.
createFromSecureContext()
static ChannelCredentials::createFromSecureContext (secureContext, verifyOptions) [inline], [static], [inherited]
Return a new ChannelCredentials instance with credentials created using the provided secureContext. The resulting instances can be used to construct a Channel that communicates over TLS. gRPC will not override anything in the provided secureContext, so the environment variables GRPC_SSL_CIPHER_SUITES and GRPC_DEFAULT_SSL_ROOTS_FILE_PATH will not be applied.
Parameters
secureContext The return value of tls.createSecureContext()
verifyOptions Additional options to modify certificate verification
createInsecure()
static ChannelCredentials::createInsecure () [inline], [static], [inherited]
Return a new ChannelCredentials instance with no credentials.
createSsl()
static ChannelCredentials::createSsl (rootCerts, privateKey, certChain, verifyOptions) [inline], [static], [inherited]
Return a new ChannelCredentials instance with a given set of credentials. The resulting instance can be used to construct a Channel that communicates over TLS.
Parameters
rootCerts The root certificate data.
privateKey The client certificate private key, if available.
certChain The client certificate key chain, if available.
verifyOptions Additional options to modify certificate verification
References _a, cert, ciphers, tls_1, tls_helpers_1, undefined, and verifyIsBufferOrNull().
handleCaCertificateUpdate()
CertificateProviderChannelCredentialsImpl::handleCaCertificateUpdate (update) [inline]
References update.
handleIdentityCertitificateUpdate()
CertificateProviderChannelCredentialsImpl::handleIdentityCertitificateUpdate (update) [inline]
References update.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/channel-credentials.js