Operation Class Reference
Public Member Functions
constructor (grpcOp, longrunningDescriptor, backoffSettings, callOptions)
cancel ()
getOperation (callback)
_unpackResponse (op, callback)
promise ()
Private Member Functions
_listenForEvents ()
startPolling_ ()
Member Function Documentation
_listenForEvents()
Operation::_listenForEvents () [inline], [private]
Begin listening for events on the operation. This method keeps track of how many "complete" listeners are registered and removed, making sure polling is handled automatically.
As long as there is one active "complete" listener, the connection is open. When there are no more listeners, the polling stops.
References event, on, and startPolling_().
_unpackResponse()
Operation::_unpackResponse (op, callback) [inline]
References callback, done, error, googleError_1, response, and result.
cancel()
Operation::cancel () [inline]
Cancels current polling api call and cancels the operation.
Returns
{Promise} the promise of the OperationsClient::cancelOperation api request.
References operationProtos, and operationsClient.
constructor()
Operation::constructor (grpcOp, longrunningDescriptor, backoffSettings, callOptions) [inline]
Wrapper for a google.longrunnung.Operation.
@constructor
Parameters
{google.longrunning.Operation} grpcOp - The operation to be wrapped.
{LongRunningDescriptor} longrunningDescriptor - This defines the operations service client and unpacking mechanisms for the operation.
{BackoffSettings} backoffSettings - The backoff settings used in in polling the operation.
{CallOptions} callOptions - CallOptions used in making get operation requests.
References _listenForEvents(), _unpackResponse(), done, error, name, and result.
getOperation()
Operation::getOperation (callback) [inline]
References _unpackResponse(), callback, error, googleError_1, operationProtos, operationsClient, Promise, reject(), request, resolve, and result.
promise()
Operation::promise () [inline]
Wraps the complete and error events in a Promise.
Returns
{promise} - Promise that resolves on operation completion and rejects on operation error.
References EventEmitter::on(), on, Promise, reject(), resolve, and result.
startPolling_()
Operation::startPolling_ () [inline], [private]
Poll getOperation to check the operation's status. This runs a loop to ping using the backoff strategy specified at initialization.
Note: This method is automatically called once a "complete" event handler is registered on the operation.
References a, args, b, delay, emit, error, event, googleError_1, i, now, result, retry, setImmediate, and status_1.
The documentation for this class was generated from the following file:
backend/node_modules/google-gax/build/src/longRunningCalls/longrunning.js