OutlierDetectionLoadBalancingConfig Class Reference
Public Member Functions
constructor (intervalMs, baseEjectionTimeMs, maxEjectionTimeMs, maxEjectionPercent, successRateEjection, failurePercentageEjection, childPolicy)
getLoadBalancerName ()
toJsonObject ()
getIntervalMs ()
getBaseEjectionTimeMs ()
getMaxEjectionTimeMs ()
getMaxEjectionPercent ()
getSuccessRateEjectionConfig ()
getFailurePercentageEjectionConfig ()
getChildPolicy ()
Static Public Member Functions
static createFromJson (obj)
Member Function Documentation
constructor()
OutlierDetectionLoadBalancingConfig::constructor (intervalMs, baseEjectionTimeMs, maxEjectionTimeMs, maxEjectionPercent, successRateEjection, failurePercentageEjection, childPolicy) [inline]
References defaultFailurePercentageEjectionConfig, and defaultSuccessRateEjectionConfig.
createFromJson()
static OutlierDetectionLoadBalancingConfig::createFromJson (obj) [inline], [static]
References _a, Array, duration_1, load_balancer_1, obj, OutlierDetectionLoadBalancingConfig, undefined, validateFieldType(), validatePercentage(), and validatePositiveDuration().
getBaseEjectionTimeMs()
OutlierDetectionLoadBalancingConfig::getBaseEjectionTimeMs () [inline]
getChildPolicy()
OutlierDetectionLoadBalancingConfig::getChildPolicy () [inline]
getFailurePercentageEjectionConfig()
OutlierDetectionLoadBalancingConfig::getFailurePercentageEjectionConfig () [inline]
getIntervalMs()
OutlierDetectionLoadBalancingConfig::getIntervalMs () [inline]
getLoadBalancerName()
OutlierDetectionLoadBalancingConfig::getLoadBalancerName () [inline]
References TYPE_NAME.
getMaxEjectionPercent()
OutlierDetectionLoadBalancingConfig::getMaxEjectionPercent () [inline]
getMaxEjectionTimeMs()
OutlierDetectionLoadBalancingConfig::getMaxEjectionTimeMs () [inline]
getSuccessRateEjectionConfig()
OutlierDetectionLoadBalancingConfig::getSuccessRateEjectionConfig () [inline]
toJsonObject()
OutlierDetectionLoadBalancingConfig::toJsonObject () [inline]
References _a, _b, duration_1, interval, and undefined.
The documentation for this class was generated from the following file:
backend/node_modules/@grpc/grpc-js/build/src/load-balancer-outlier-detection.js