Gaxios Class Reference
Public Member Functions
constructor (defaults)
async request (opts={})
async _defaultAdapter (opts)
async _request (opts={})
async getResponseData (opts, res)
validateStatus (status)
paramsSerializer (params)
translateResponse (opts, res, data)
async getResponseDataFromContentType (response)
async * getMultipartRequest (multipartOptions, boundary)
Public Attributes
else
Member Function Documentation
_defaultAdapter()
async Gaxios::_defaultAdapter (opts) [inline]
References data, fetch, getResponseData(), res, and translateResponse().
_request()
async Gaxios::_request (opts = {}) [inline]
Internal, retryable version of the request method.
Parameters
opts Set of HTTP options that will be used for this HTTP request.
constructor()
Gaxios::constructor (defaults) [inline]
The Gaxios class is responsible for making HTTP requests.
Parameters
defaults The default set of options to be used for this instance.
References _Gaxios_instances, defaults, interceptor_1, Map, request, and response.
getMultipartRequest()
async * Gaxios::getMultipartRequest (multipartOptions, boundary) [inline]
Creates an async generator that yields the pieces of a multipart/related request body. This implementation follows the spec: https://www.ietf.org/rfc/rfc2387.txt. However, recursive multipart/related requests are not currently supported.
Parameters
{GaxioMultipartOptions[]} multipartOptions the pieces to turn into a multipart/related body.
{string} boundary the boundary string to be placed between each part.
References $, of, and Type.
getResponseData()
async Gaxios::getResponseData (opts, res) [inline]
References _b, data, getResponseDataFromContentType(), JSON, and res.
getResponseDataFromContentType()
async Gaxios::getResponseDataFromContentType (response) [inline]
Attempts to parse a response by looking at the Content-Type header.
Parameters
{FetchResponse} response the HTTP response.
Returns
{Promise<any>} a promise that resolves to the response data.
References _b, contentType, data, JSON, response, and text.
paramsSerializer()
Gaxios::paramsSerializer (params) [inline]
Encode a set of key/value pars into a querystring format (?foo=bar&baz=boo)
Parameters
params key value pars to encode
References querystring_1.
request()
async Gaxios::request (opts = {}) [inline]
Perform an HTTP request with the given options.
Parameters
opts Set of HTTP options that will be used for this HTTP request.
translateResponse()
Gaxios::translateResponse (opts, res, data) [inline]
References config, data, headers, request, res, status, and value.
validateStatus()
Gaxios::validateStatus (status) [inline]
By default, throw for any non-2xx status code
Parameters
status status code from the HTTP response
References status.
Member Data Documentation
else
Gaxios::else
Initial value:
{
            
            return response.blob()
The documentation for this class was generated from the following file:
backend/node_modules/gaxios/build/src/gaxios.js