FirebaseMessagingRequestHandler Class Reference
Public Member Functions
constructor (app)
invokeRequestHandler (host, path, requestData)
invokeHttpRequestHandlerForSendResponse (host, path, requestData)
invokeHttp2RequestHandlerForSendResponse (host, path, requestData, http2SessionHandler)
sendBatchRequest (requests)
buildSendResponse (response)
buildSendResponseFromError (err)
Detailed Description
Class that provides a mechanism to send requests to the Firebase Cloud Messaging backend.
Member Function Documentation
buildSendResponse()
FirebaseMessagingRequestHandler::buildSendResponse (response) [inline]
References api_request_1, messaging_errors_internal_1, response, result, and success.
buildSendResponseFromError()
FirebaseMessagingRequestHandler::buildSendResponseFromError (err) [inline]
References error, messaging_errors_internal_1, and success.
constructor()
FirebaseMessagingRequestHandler::constructor (app) [inline]
Parameters
app - The app used to fetch access tokens to sign API requests. @constructor
References api_request_1, app, batch_request_internal_1, FIREBASE_MESSAGING_BATCH_URL, and FIREBASE_MESSAGING_HEADERS.
invokeHttp2RequestHandlerForSendResponse()
FirebaseMessagingRequestHandler::invokeHttp2RequestHandlerForSendResponse (host, path, requestData, http2SessionHandler) [inline]
Invokes the HTTP/2 request handler with the provided request data.
Parameters
host - The host to which to send the request.
path - The path to which to send the request.
requestData - The request data.
Returns
A promise that resolves with the SendResponse.
References api_request_1, buildSendResponse(), buildSendResponseFromError(), data, FIREBASE_MESSAGING_TIMEOUT, headers, https, LEGACY_FIREBASE_MESSAGING_HEADERS, method, request, response, timeout, and url.
invokeHttpRequestHandlerForSendResponse()
FirebaseMessagingRequestHandler::invokeHttpRequestHandlerForSendResponse (host, path, requestData) [inline]
Invokes the HTTP/1.1 request handler with the provided request data.
Parameters
host - The host to which to send the request.
path - The path to which to send the request.
requestData - The request data.
Returns
A promise that resolves with the SendResponse.
References api_request_1, buildSendResponse(), buildSendResponseFromError(), data, FIREBASE_MESSAGING_TIMEOUT, headers, https, LEGACY_FIREBASE_MESSAGING_HEADERS, method, request, response, timeout, and url.
invokeRequestHandler()
FirebaseMessagingRequestHandler::invokeRequestHandler (host, path, requestData) [inline]
Invokes the request handler with the provided request data.
Parameters
host - The host to which to send the request.
path - The path to which to send the request.
requestData - The request data.
Returns
A promise that resolves with the response.
References api_request_1, data, FIREBASE_MESSAGING_TIMEOUT, headers, https, LEGACY_FIREBASE_MESSAGING_HEADERS, messaging_errors_internal_1, method, request, response, timeout, and url.
sendBatchRequest()
FirebaseMessagingRequestHandler::sendBatchRequest (requests) [inline]
Sends the given array of sub requests as a single batch to FCM, and parses the result into a BatchResponse object.
Parameters
requests - An array of sub requests to send.
Returns
A promise that resolves when the send operation is complete.
References api_request_1, buildSendResponse(), messaging_errors_internal_1, and then.
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/messaging/messaging-api-request-internal.js