Provider Class Reference
Public Member Functions
constructor (name, container)
get (identifier)
getImmediate (options)
getComponent ()
setComponent (component)
clearInstance (identifier=DEFAULT_ENTRY_NAME)
async delete ()
isComponentSet ()
isInitialized (identifier=DEFAULT_ENTRY_NAME)
getOptions (identifier=DEFAULT_ENTRY_NAME)
initialize (opts={})
onInit (callback, identifier)
invokeOnInitCallbacks (instance, identifier)
getOrInitializeService ({ instanceIdentifier, options={} })
normalizeInstanceIdentifier (identifier=DEFAULT_ENTRY_NAME)
shouldAutoInitialize ()
Detailed Description
@license Copyright 2019 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Provider for instance for service name T, e.g. 'auth', 'auth-internal' NameServiceMapping[T] is an alias for the type of the instance
Member Function Documentation
clearInstance()
Provider::clearInstance (identifier = DEFAULT_ENTRY_NAME) [inline]
References instances.
constructor()
Provider::constructor (name, container) [inline]
References component, instances, Map, and name.
delete()
async Provider::delete () [inline]
References Array, filter, instances, map, and Promise.
get()
Provider::get (identifier) [inline]
Parameters
identifier A provider can provide multiple instances of a service if this.component.multipleInstances is true.
References Deferred, deferred, e, getOrInitializeService(), instance, isInitialized(), normalizeInstanceIdentifier(), and shouldAutoInitialize().
getComponent()
Provider::getComponent () [inline]
References component.
getImmediate()
Provider::getImmediate (options) [inline]
References $, _a, e, getOrInitializeService(), is, isInitialized(), name, normalizeInstanceIdentifier(), not, and shouldAutoInitialize().
getOptions()
Provider::getOptions (identifier = DEFAULT_ENTRY_NAME) [inline]
getOrInitializeService()
Provider::getOrInitializeService ({ instanceIdentifier, options={} }) [inline]
Invoke onInit listeners. Note this.component.onInstanceCreated is different, which is used by the component creator, while onInit listeners are registered by consumers of the provider.
Order is important onInstanceCreated() should be called after this.instances.set(instanceIdentifier, instance); which makes isInitialized() return true.Here is the caller graph for this function:
initialize()
Provider::initialize (opts = {}) [inline]
invokeOnInitCallbacks()
Provider::invokeOnInitCallbacks (instance, identifier) [inline]
Invoke onInit callbacks synchronously
Parameters
instance the service instance
References _a, callback, instance, and of.
isComponentSet()
Provider::isComponentSet () [inline]
References component.
isInitialized()
Provider::isInitialized (identifier = DEFAULT_ENTRY_NAME) [inline]
References instances.
normalizeInstanceIdentifier()
Provider::normalizeInstanceIdentifier (identifier = DEFAULT_ENTRY_NAME) [inline]
References component, and DEFAULT_ENTRY_NAME.
onInit()
Provider::onInit (callback, identifier) [inline]
Parameters
callback - a function that will be invoked after the provider has been initialized by calling provider.initialize(). The function is invoked SYNCHRONOUSLY, so it should not execute any longrunning tasks in order to not block the program.
identifier An optional instance identifier
Returns
a function to unregister the callback
References _a, callback, instances, normalizeInstanceIdentifier(), and Set.
setComponent()
Provider::setComponent (component) [inline]
References $, component, DEFAULT_ENTRY_NAME, e, getOrInitializeService(), has, instance, isComponentEager(), name, normalizeInstanceIdentifier(), of, and shouldAutoInitialize().
shouldAutoInitialize()
Provider::shouldAutoInitialize () [inline]
References component.
The documentation for this class was generated from the following file:
backend/node_modules/@firebase/component/dist/esm/index.esm2017.js