Headers Class Reference
Public Member Functions
constructor ()
get (name)
forEach (callback)
set (name, value)
append (name, value)
has (name)
delete (name)
raw ()
keys ()
values ()
constructor ()
get (name)
forEach (callback)
set (name, value)
append (name, value)
has (name)
delete (name)
raw ()
keys ()
values ()
Member Function Documentation
append() [1/2]
Headers::append (name, value) [inline]
Append a value onto existing header
Parameters
String name Header name
String value Header value
Returns
Void
References $, find, MAP, name, undefined, validateName(), validateValue, and value.
append() [2/2]
Headers::append (name, value) [inline]
Append a value onto existing header
Parameters
String name Header name
String value Header value
Returns
Void
References $, find, MAP, name, undefined, validateName(), validateValue, and value.
constructor() [1/2]
Headers::constructor () [inline]
Headers class
Parameters
Object headers Response headers
Returns
Void
References append, Array, init, method, of, pairs, Symbol, and value.
constructor() [2/2]
Headers::constructor () [inline]
Headers class
Parameters
Object headers Response headers
Returns
Void
References append, Array, init, method, of, pairs, Symbol, and value.
delete() [1/2]
Headers::delete (name) [inline]
Delete all header values given name
Parameters
String name Header name
Returns
Void
References $, find, MAP, name, undefined, and validateName().
delete() [2/2]
Headers::delete (name) [inline]
Delete all header values given name
Parameters
String name Header name
Returns
Void
References $, find, MAP, name, undefined, and validateName().
forEach() [1/2]
Headers::forEach (callback) [inline]
Iterate over all headers
Parameters
Function callback Executed for each item with parameters (value, name, thisArg)
Boolean thisArg this context for callback function
Returns
Void
References callback, getHeaders, i, name, pairs, undefined, and value.
forEach() [2/2]
Headers::forEach (callback) [inline]
Iterate over all headers
Parameters
Function callback Executed for each item with parameters (value, name, thisArg)
Boolean thisArg this context for callback function
Returns
Void
References callback, getHeaders, i, name, pairs, undefined, and value.
get() [1/2]
Headers::get (name) [inline]
Return combined header value given name
Parameters
String name Header name
Returns
Mixed
References $, find, MAP, name, undefined, and validateName().
get() [2/2]
Headers::get (name) [inline]
Return combined header value given name
Parameters
String name Header name
Returns
Mixed
References $, find, MAP, name, undefined, and validateName().
has() [1/2]
Headers::has (name) [inline]
Check for header name existence
Parameters
String name Header name
Returns
Boolean
References $, find, MAP, name, undefined, and validateName().
has() [2/2]
Headers::has (name) [inline]
Check for header name existence
Parameters
String name Header name
Returns
Boolean
References $, find, MAP, name, undefined, and validateName().
keys() [1/2]
Headers::keys () [inline]
Get an iterator on keys.
Returns
Iterator
References createHeadersIterator().
keys() [2/2]
Headers::keys () [inline]
Get an iterator on keys.
Returns
Iterator
References createHeadersIterator().
raw() [1/2]
Headers::raw () [inline]
Return raw headers (non-spec api)
Returns
Object
References MAP.
raw() [2/2]
Headers::raw () [inline]
Return raw headers (non-spec api)
Returns
Object
References MAP.
set() [1/2]
Headers::set (name, value) [inline]
Overwrite header values given name
Parameters
String name Header name
String value Header value
Returns
Void
References $, find, MAP, name, undefined, validateName(), validateValue, and value.
set() [2/2]
Headers::set (name, value) [inline]
Overwrite header values given name
Parameters
String name Header name
String value Header value
Returns
Void
References $, find, MAP, name, undefined, validateName(), validateValue, and value.
values() [1/2]
Headers::values () [inline]
Get an iterator on values.
Returns
Iterator
References createHeadersIterator().
values() [2/2]
Headers::values () [inline]
Get an iterator on values.
Returns
Iterator
References createHeadersIterator().
The documentation for this class was generated from the following files:
backend/node_modules/node-fetch/lib/index.es.js
backend/node_modules/node-fetch/lib/index.js