Xml2JsParser Class Reference
Public Member Functions
constructor (options)
parse (strData)
parseBytesArr (data)
parseXml ()
readClosingTag ()
validateClosingTag (tagName)
readOpeningTag ()
readSpecialTag (startCh)
Member Function Documentation
constructor()
Xml2JsParser::constructor (options) [inline]
References EntitiesParser, i, and TagPath.
parse()
Xml2JsParser::parse (strData) [inline]
References parseXml(), source, and StringSource.
parseBytesArr()
Xml2JsParser::parseBytesArr (data) [inline]
References BufferSource, data, parseXml(), and source.
parseXml()
Xml2JsParser::parseXml () [inline]
References readClosingTag(), readOpeningTag(), readSpecialTag(), root, and source.
readClosingTag()
Xml2JsParser::readClosingTag () [inline]
read closing paired tag. Set parent tag in scope. skip a node on user's choice
References readClosingTagName(), source, and validateClosingTag().
readOpeningTag()
Xml2JsParser::readOpeningTag () [inline]
Read paired, unpaired, self-closing, stop and special tags. Create a new node Push paired tag in stack.
References $, isStopNode(), readTagExp(), and source.
readSpecialTag()
Xml2JsParser::readSpecialTag (startCh) [inline]
References $, at, readCdata(), readComment(), readDocType, readPiTag(), source, and undefined.
validateClosingTag()
Xml2JsParser::validateClosingTag (tagName) [inline]
References isStopNode().
The documentation for this class was generated from the following file:
backend/node_modules/fast-xml-parser/src/v5/Xml2JsParser.js