DownscopedClient Class Reference
Public Member Functions
constructor (authClient, credentialAccessBoundary, additionalOptions, quotaProjectId)
setCredentials (credentials)
async getAccessToken ()
async getRequestHeaders ()
request (opts, callback)
async requestAsync (opts, reAuthRetried=false)
async refreshAccessTokenAsync ()
isExpired (downscopedAccessToken)
Detailed Description
Defines a set of Google credentials that are downscoped from an existing set of Google OAuth2 credentials. This is useful to restrict the Identity and Access Management (IAM) permissions that a short-lived credential can use. The common pattern of usage is to have a token broker with elevated access generate these downscoped credentials from higher access source credentials and pass the downscoped short-lived access tokens to a token consumer via some secure authenticated channel for limited access to Google Cloud Storage resources.
Member Function Documentation
constructor()
DownscopedClient::constructor (authClient, credentialAccessBoundary, additionalOptions, quotaProjectId) [inline]
Instantiates a downscoped client object using the provided source AuthClient and credential access boundary rules. To downscope permissions of a source AuthClient, a Credential Access Boundary that specifies which resources the new credential can access, as well as an upper bound on the permissions that are available on each resource, has to be defined. A downscoped client can then be instantiated using the source AuthClient and the Credential Access Boundary.
Parameters
authClient The source AuthClient to be downscoped based on the provided Credential Access Boundary rules.
credentialAccessBoundary The Credential Access Boundary which contains a list of access boundary rules. Each rule contains information on the resource that the rule applies to, the upper bound of the permissions that are available on that resource and an optional condition to further restrict permissions.
additionalOptions DEPRECATED, set this in the provided authClient. Optional additional behavior customization options.
quotaProjectId DEPRECATED, set this in the provided authClient. Optional quota project id for setting up in the x-goog-user-project header.
References $, exports, https, of, and sts.
getAccessToken()
async DownscopedClient::getAccessToken () [inline]
References isExpired(), refreshAccessTokenAsync(), res, and token.
getRequestHeaders()
async DownscopedClient::getRequestHeaders () [inline]
The main authentication interface. It takes an optional url which when present is the endpoint being accessed, and returns a Promise which resolves with authorization header fields.
The result has the form: { Authorization: 'Bearer <access_token_value>' }
References $, getAccessToken(), and headers.
isExpired()
DownscopedClient::isExpired (downscopedAccessToken) [inline]
Returns whether the provided credentials are expired or not. If there is no expiry time, assumes the token is not expired or expiring.
Parameters
downscopedAccessToken The credentials to check for expiration.
Returns
Whether the credentials are expired or not.
References now.
refreshAccessTokenAsync()
async DownscopedClient::refreshAccessTokenAsync () [inline]
Forces token refresh, even if unexpired tokens are currently cached. GCP access tokens are retrieved from authclient object/source credential. Then GCP access tokens are exchanged for downscoped access tokens via the token exchange endpoint.
Returns
A promise that resolves with the fresh downscoped access token.
The STS endpoint will only return the expiration time for the downscoped access token if the original access token represents a service account. The downscoped token's expiration time will always match the source credential expiration. When no expires_in is returned, we can copy the source credential's expiration time.
References _a, credentials, emit, res, STS_GRANT_TYPE, STS_REQUEST_TOKEN_TYPE, STS_SUBJECT_TOKEN_TYPE, and undefined.
request()
DownscopedClient::request (opts, callback) [inline]
References callback, e, r, and requestAsync().
requestAsync()
async DownscopedClient::requestAsync (opts, reAuthRetried = false) [inline]
Authenticates the provided HTTP request, processes it and resolves with the returned response.
Parameters
opts The HTTP request options.
reAuthRetried Whether the current attempt is a retry after a failed attempt due to an auth failure
Returns
A promise that resolves with the successful response.
References e, getRequestHeaders(), isReadableStream(), refreshAccessTokenAsync(), requestAsync(), res, response, and stream.
setCredentials()
DownscopedClient::setCredentials (credentials) [inline]
Provides a mechanism to inject Downscoped access tokens directly. The expiry_date field is required to facilitate determination of the token expiration which would make it easier for the token consumer to handle.
Parameters
credentials The Credentials object to set on the current client.
References credentials.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/auth/downscopedclient.js