BrowserCrypto Class Reference
Public Member Functions
constructor ()
async sha256DigestBase64 (str)
randomBytesBase64 (count)
async verify (pubkey, data, signature)
async sign (privateKey, data)
decodeBase64StringUtf8 (base64)
encodeBase64StringUtf8 (text)
async sha256DigestHex (str)
async signWithHmacSha256 (key, msg)
Static Public Member Functions
static padBase64 (base64)
Member Function Documentation
constructor()
BrowserCrypto::constructor () [inline]
References undefined, and window.
decodeBase64StringUtf8()
BrowserCrypto::decodeBase64StringUtf8 (base64) [inline]
References base64, base64js, padBase64(), and result.
encodeBase64StringUtf8()
BrowserCrypto::encodeBase64StringUtf8 (text) [inline]
References base64js, result, and text.
padBase64()
static BrowserCrypto::padBase64 (base64) [inline], [static]
References base64.
randomBytesBase64()
BrowserCrypto::randomBytesBase64 (count) [inline]
References base64js, count, Uint8Array, and window.
sha256DigestBase64()
async BrowserCrypto::sha256DigestBase64 (str) [inline]
References base64js, str(), Uint8Array, and window.
sha256DigestHex()
async BrowserCrypto::sha256DigestHex (str) [inline]
Computes the SHA-256 hash of the provided string.
Parameters
str The plain text string to hash.
Returns
A promise that resolves with the SHA-256 hash of the provided string in hexadecimal encoding.
References crypto_1, str(), and window.
sign()
async BrowserCrypto::sign (privateKey, data) [inline]
References base64js, data, hash(), name, result, Uint8Array, and window.
signWithHmacSha256()
async BrowserCrypto::signWithHmacSha256 (key, msg) [inline]
Computes the HMAC hash of a message using the provided crypto key and the SHA-256 algorithm.
Parameters
key The secret crypto key in utf-8 or ArrayBuffer format.
msg The plain text message.
Returns
A promise that resolves with the HMAC-SHA256 hash in ArrayBuffer format.
References window.
verify()
async BrowserCrypto::verify (pubkey, data, signature) [inline]
References base64js, data, hash(), name, padBase64(), result, signature, and window.
The documentation for this class was generated from the following file:
backend/node_modules/google-auth-library/build/src/crypto/browser/crypto.js