Logger Class Reference
Public Member Functions
constructor (name)
get logLevel ()
set logLevel (val)
setLogLevel (val)
get logHandler ()
set logHandler (val)
get userLogHandler ()
set userLogHandler (val)
debug (...args)
log (...args)
info (...args)
warn (...args)
error (...args)
constructor ({ hide, prefixFormat, commandLength, raw=false, timestampFormat, })
toggleColors (on)
shortenText (text)
getPrefixesFor (command)
getPrefixContent (command)
getPrefix (command)
setPrefixLength (length)
colorText (command, text)
logCommandEvent (text, command)
logCommandText (text, command)
logGlobalEvent (text)
logTable (tableContents)
log (prefix, text, command)
emit (command, text)
Public Attributes
hide
raw
prefixFormat
commandLength
dateFormatter
chalk = defaultChalk
prefixLength = 0
lastWrite
output = new Rx.Subject()
Member Function Documentation
colorText()
Logger::colorText (command, text) [inline]
References chalk, command(), defaults, lodash_1, and text.
constructor() [1/2]
Logger::constructor (name) [inline]
Gives you an instance of a Logger to capture messages according to Firebase's logging scheme.
Parameters
name The name that the logs will be associated with
The log level of the given Logger instance.
The main (internal) log handler for the Logger instance. Can be set to a new function in internal package code but not by user.
The optional, additional, user-defined log handler for the Logger instance.
Capture the current instance for later use
References defaultLogHandler, defaultLogLevel, instances, and name.
constructor() [2/2]
Logger::constructor ({ hide, prefixFormat, commandLength, raw=false, timestampFormat, }) [inline]
References commandLength, hide, prefixFormat, raw, and timestampFormat.
debug()
Logger::debug (...) [inline]
The functions below are all based on the console interface
References LogLevel.
emit()
Logger::emit (command, text) [inline]
References command(), and text.
error()
Logger::error (...) [inline]
References LogLevel.
getPrefix()
Logger::getPrefix (command) [inline]
References $, command(), and prefixLength.
getPrefixContent()
Logger::getPrefixContent (command) [inline]
References command(), getPrefixesFor(), lodash_1, prefix, prefixFormat, type, and value.
getPrefixesFor()
Logger::getPrefixesFor (command) [inline]
References command(), dateFormatter, index, name, and shortenText().
info()
Logger::info (...) [inline]
References LogLevel.
log() [1/2]
Logger::log (...) [inline]
References LogLevel.
log() [2/2]
Logger::log (prefix, text, command) [inline]
References command(), emit, g, i, prefix, raw, and text.
logCommandEvent()
Logger::logCommandEvent (text, command) [inline]
Logs an event for a command (e.g. start, stop).
If raw mode is on, then nothing is logged.
References chalk, command(), prefix, raw, and text.
logCommandText()
Logger::logCommandText (text, command) [inline]
References command(), hide, log, prefix, and text.
logGlobalEvent()
Logger::logGlobalEvent (text) [inline]
Logs a global event (e.g. sending signals to processes).
If raw mode is on, then nothing is logged.
References chalk, log, raw, and text.
logHandler() [1/2]
get Logger::logHandler () [inline]
logHandler() [2/2]
set Logger::logHandler (val) [inline]
logLevel() [1/2]
get Logger::logLevel () [inline]
logLevel() [2/2]
set Logger::logLevel (val) [inline]
References LogLevel, logLevel(), and value.
logTable()
Logger::logTable (tableContents) [inline]
Logs a table from an input object array, like console.table.
Each row is a single input item, and they are presented in the input order.
References $, Array, headers, index, length, padEnd(), and raw.
setLogLevel()
Logger::setLogLevel (val) [inline]
References levelStringToEnum.
setPrefixLength()
Logger::setPrefixLength (length) [inline]
References length, and prefixLength.
shortenText()
Logger::shortenText (text) [inline]
References commandLength, end, prefixLength, and text.
toggleColors()
Logger::toggleColors (on) [inline]
Toggles colors on/off globally.
References chalk, defaultChalk, noColorChalk, and on.
userLogHandler() [1/2]
get Logger::userLogHandler () [inline]
userLogHandler() [2/2]
set Logger::userLogHandler (val) [inline]
warn()
Logger::warn (...) [inline]
References LogLevel.
Member Data Documentation
chalk
Logger::chalk = defaultChalk
commandLength
Logger::commandLength
dateFormatter
Logger::dateFormatter
hide
Logger::hide
lastWrite
Logger::lastWrite
Last character emitted, and from which command. If undefined, then nothing has been logged yet.
output
Logger::output = new Rx.Subject()
Observable that emits when there's been output logged. If command is is undefined, then the log is for a global event.
prefixFormat
Logger::prefixFormat
prefixLength
Logger::prefixLength = 0
How many characters should a prefix have. Prefixes shorter than this will be padded with spaces to the right.
raw
Logger::raw
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/logger/dist/esm/index.esm2017.js
backend/node_modules/concurrently/dist/src/logger.js