JwksClient Class Reference
Public Member Functions
constructor (options)
async getKeys ()
async getSigningKeys ()
async getSigningKey (kid)
Member Function Documentation
constructor()
JwksClient::constructor (options) [inline]
References callbackSupport, getKeysInterceptor(), getSigningKey(), and timeout.
getKeys()
async JwksClient::getKeys () [inline]
References headers, JwksError, keys, logger, request, res, and timeout.
getSigningKey()
async JwksClient::getSigningKey (kid) [inline]
References a, find, getSigningKeys(), k, keys, logger, matches, SigningKeyNotFoundError, and undefined.
getSigningKeys()
async JwksClient::getSigningKeys () [inline]
References getKeys(), JwksError, keys, logger, and retrieveSigningKeys.
The documentation for this class was generated from the following file:
backend/node_modules/jwks-rsa/src/JwksClient.js