Response Class Reference
Public Member Functions
constructor ()
get url ()
get status ()
get ok ()
get redirected ()
get statusText ()
get headers ()
clone ()
constructor ()
get url ()
get status ()
get ok ()
get redirected ()
get statusText ()
get headers ()
clone ()
Detailed Description
Response class
Parameters
Stream body Readable stream
Object opts Response options
Returns
Void
Member Function Documentation
clone() [1/2]
Response::clone () [inline]
Clone this response
Returns
Response
References clone(), headers(), ok(), redirected(), Response, status(), statusText(), and url().
clone() [2/2]
Response::clone () [inline]
Clone this response
Returns
Response
References clone(), headers(), ok(), redirected(), Response, status(), statusText(), and url().
constructor() [1/2]
Response::constructor () [inline]
References Body(), contentType, extractContentType(), Headers, headers(), INTERNALS$1, status(), STATUS_CODES, statusText(), undefined, and url().
constructor() [2/2]
Response::constructor () [inline]
References Body(), contentType, extractContentType(), Headers, headers(), INTERNALS$1, status(), STATUS_CODES, statusText(), undefined, and url().
headers() [1/2]
get Response::headers () [inline]
References INTERNALS$1.
headers() [2/2]
get Response::headers () [inline]
References INTERNALS$1.
ok() [1/2]
get Response::ok () [inline]
Convenience property representing if the request ended normally
References INTERNALS$1.
ok() [2/2]
get Response::ok () [inline]
Convenience property representing if the request ended normally
References INTERNALS$1.
redirected() [1/2]
get Response::redirected () [inline]
References INTERNALS$1.
redirected() [2/2]
get Response::redirected () [inline]
References INTERNALS$1.
status() [1/2]
get Response::status () [inline]
References INTERNALS$1.
status() [2/2]
get Response::status () [inline]
References INTERNALS$1.
statusText() [1/2]
get Response::statusText () [inline]
References INTERNALS$1.
statusText() [2/2]
get Response::statusText () [inline]
References INTERNALS$1.
url() [1/2]
get Response::url () [inline]
References INTERNALS$1.
url() [2/2]
get Response::url () [inline]
References INTERNALS$1.
The documentation for this class was generated from the following files:
backend/node_modules/node-fetch/lib/index.es.js
backend/node_modules/node-fetch/lib/index.js