Database Class Reference
Public Member Functions
constructor (_delegate, app)
useEmulator (host, port, options={})
ref (path)
refFromURL (url)
goOffline ()
goOnline ()
constructor (_delegate, app)
useEmulator (host, port, options={})
ref (path)
refFromURL (url)
goOffline ()
goOnline ()
Detailed Description
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Class representing a firebase database.
Member Function Documentation
constructor() [1/2]
Database::constructor (_delegate, app) [inline]
The constructor should not be called by users of our public API.
References app, and INTERNAL.
constructor() [2/2]
Database::constructor (_delegate, app) [inline]
The constructor should not be called by users of our public API.
References app, and INTERNAL.
goOffline() [1/2]
Database::goOffline () [inline]
References goOffline(), and validateArgCount.
goOffline() [2/2]
Database::goOffline () [inline]
References goOffline(), and validateArgCount.
goOnline() [1/2]
Database::goOnline () [inline]
References goOnline(), and validateArgCount.
goOnline() [2/2]
Database::goOnline () [inline]
References goOnline(), and validateArgCount.
ref() [1/2]
Database::ref (path) [inline]
References path, ref(), Reference, refFromURL(), and validateArgCount.
ref() [2/2]
Database::ref (path) [inline]
References path, ref(), Reference, refFromURL(), and validateArgCount.
refFromURL() [1/2]
Database::refFromURL (url) [inline]
Returns a reference to the root or the path specified in url. We throw a exception if the url is not in the same domain as the current repo.
Returns
Firebase reference.
References Reference, refFromURL(), url, and validateArgCount.
refFromURL() [2/2]
Database::refFromURL (url) [inline]
Returns a reference to the root or the path specified in url. We throw a exception if the url is not in the same domain as the current repo.
Returns
Firebase reference.
References Reference, refFromURL(), url, and validateArgCount.
useEmulator() [1/2]
Database::useEmulator (host, port, options = {}) [inline]
Modify this instance to communicate with the Realtime Database emulator.
Note: This method must be called before performing any other operation.
Parameters
host - the emulator host (ex: localhost)
port - the emulator port (ex: 8080)
options.mockUserToken - the mock auth token to use for unit testing Security Rules
useEmulator() [2/2]
Database::useEmulator (host, port, options = {}) [inline]
Modify this instance to communicate with the Realtime Database emulator.
Note: This method must be called before performing any other operation.
Parameters
host - the emulator host (ex: localhost)
port - the emulator port (ex: 8080)
options.mockUserToken - the mock auth token to use for unit testing Security Rules
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/database-compat/dist/index.esm2017.js
backend/node_modules/@firebase/database-compat/dist/node-esm/index.js