ObserverProxy Class Reference
Public Member Functions
constructor (executor, onNoObservers)
next (value)
error (error)
complete ()
subscribe (nextOrObserver, error, complete)
unsubscribeOne (i)
forEachObserver (fn)
sendOne (i, fn)
close (err)
constructor (executor, onNoObservers)
next (value)
error (error)
complete ()
subscribe (nextOrObserver, error, complete)
unsubscribeOne (i)
forEachObserver (fn)
sendOne (i, fn)
close (err)
constructor (executor, onNoObservers)
next (value)
error (error)
complete ()
subscribe (nextOrObserver, error, complete)
unsubscribeOne (i)
forEachObserver (fn)
sendOne (i, fn)
close (err)
Detailed Description
Implement fan-out for any number of Observers attached via a subscribe function.
Member Function Documentation
close() [1/3]
ObserverProxy::close (err) [inline]
References undefined.
close() [2/3]
ObserverProxy::close (err) [inline]
References undefined.
close() [3/3]
ObserverProxy::close (err) [inline]
References undefined.
complete() [1/3]
ObserverProxy::complete () [inline]
References close, and forEachObserver().
complete() [2/3]
ObserverProxy::complete () [inline]
References close, and forEachObserver().
complete() [3/3]
ObserverProxy::complete () [inline]
References close, and forEachObserver().
constructor() [1/3]
ObserverProxy::constructor (executor, onNoObservers) [inline]
Parameters
executor Function which can make calls to a single Observer as a proxy.
onNoObservers Callback when count of Observers goes to zero.
References e, error, and Promise.
constructor() [2/3]
ObserverProxy::constructor (executor, onNoObservers) [inline]
Parameters
executor Function which can make calls to a single Observer as a proxy.
onNoObservers Callback when count of Observers goes to zero.
References e, error, and Promise.
constructor() [3/3]
ObserverProxy::constructor (executor, onNoObservers) [inline]
Parameters
executor Function which can make calls to a single Observer as a proxy.
onNoObservers Callback when count of Observers goes to zero.
References e, error, and Promise.
error() [1/3]
ObserverProxy::error (error) [inline]
References close, error, and forEachObserver().
error() [2/3]
ObserverProxy::error (error) [inline]
References close, error, and forEachObserver().
error() [3/3]
ObserverProxy::error (error) [inline]
References close, error, and forEachObserver().
forEachObserver() [1/3]
ObserverProxy::forEachObserver (fn) [inline]
References fn, i, and sendOne().
forEachObserver() [2/3]
ObserverProxy::forEachObserver (fn) [inline]
References fn, i, and sendOne().
forEachObserver() [3/3]
ObserverProxy::forEachObserver (fn) [inline]
References fn, i, and sendOne().
next() [1/3]
ObserverProxy::next (value) [inline]
References forEachObserver(), and value.
next() [2/3]
ObserverProxy::next (value) [inline]
References forEachObserver(), and value.
next() [3/3]
ObserverProxy::next (value) [inline]
References forEachObserver(), and value.
sendOne() [1/3]
ObserverProxy::sendOne (i, fn) [inline]
References e, fn, i, and undefined.
sendOne() [2/3]
ObserverProxy::sendOne (i, fn) [inline]
References e, fn, i, and undefined.
sendOne() [3/3]
ObserverProxy::sendOne (i, fn) [inline]
References e, fn, i, and undefined.
subscribe() [1/3]
ObserverProxy::subscribe (nextOrObserver, error, complete) [inline]
Subscribe function that can be used to add an Observer to the fan-out list.
We require that no event is sent to a subscriber synchronously to their call to subscribe().
References complete(), e, error, implementsAnyMethods(), next(), noop(), undefined, and unsubscribeOne().
subscribe() [2/3]
ObserverProxy::subscribe (nextOrObserver, error, complete) [inline]
Subscribe function that can be used to add an Observer to the fan-out list.
We require that no event is sent to a subscriber synchronously to their call to subscribe().
References complete(), e, error, implementsAnyMethods(), next(), noop(), undefined, and unsubscribeOne().
subscribe() [3/3]
ObserverProxy::subscribe (nextOrObserver, error, complete) [inline]
Subscribe function that can be used to add an Observer to the fan-out list.
We require that no event is sent to a subscriber synchronously to their call to subscribe().
References complete(), e, error, implementsAnyMethods(), next(), noop(), undefined, and unsubscribeOne().
unsubscribeOne() [1/3]
ObserverProxy::unsubscribeOne (i) [inline]
References i, and undefined.
unsubscribeOne() [2/3]
ObserverProxy::unsubscribeOne (i) [inline]
References i, and undefined.
unsubscribeOne() [3/3]
ObserverProxy::unsubscribeOne (i) [inline]
References i, and undefined.
The documentation for this class was generated from the following files:
backend/node_modules/@firebase/util/dist/index.cjs.js
backend/node_modules/@firebase/util/dist/index.esm2017.js
backend/node_modules/@firebase/util/dist/node-esm/index.node.esm.js