DatabaseService Class Reference
Public Member Functions
constructor (app)
get firebaseApp ()
delete ()
get app ()
getDatabase (url)
onTokenChange (_)
scheduleTokenRefresh (delayMillis)
ensureUrl (url)
Member Function Documentation
app()
get DatabaseService::app () [inline]
Returns the app associated with this DatabaseService instance.
Returns
The app associated with this DatabaseService instance.
constructor()
DatabaseService::constructor (app) [inline]
References app(), error_1, message, and validator.
delete()
DatabaseService::delete () [inline]
References db, firebaseApp(), of, and Promise.
ensureUrl()
DatabaseService::ensureUrl (url) [inline]
References error_1, message, and url.
firebaseApp()
get DatabaseService::firebaseApp () [inline]
References app().
getDatabase()
DatabaseService::getDatabase (url) [inline]
References app(), db, ensureUrl(), error_1, firebaseApp(), index_1, message, onTokenChange(), require(), source, url, and validator.
onTokenChange()
DatabaseService::onTokenChange (_) [inline]
References firebaseApp(), scheduleTokenRefresh(), token, and TOKEN_REFRESH_THRESHOLD_MILLIS.
scheduleTokenRefresh()
DatabaseService::scheduleTokenRefresh (delayMillis) [inline]
References firebaseApp().
The documentation for this class was generated from the following file:
backend/node_modules/firebase-admin/lib/database/database.js