Acl Class Reference
Public Member Functions
constructor (options)
add (options, callback)
delete (options, callback)
get (optionsOrCallback, cb)
update (options, callback)
constructor (options)
add (options, callback)
delete (options, callback)
get (optionsOrCallback, cb)
update (options, callback)
 Acl#writers
_assignAccessMethods (role)
_assignAccessMethods (role)
Private Member Functions
makeAclObject_ (accessControlObject)
request (reqOpts, callback)
makeAclObject_ (accessControlObject)
request (reqOpts, callback)
Detailed Description
Cloud Storage uses access control lists (ACLs) to manage object and bucket access. ACLs are the mechanism you use to share objects with other users and allow other users to access your buckets and objects.
An ACL consists of one or more entries, where each entry grants permissions to an entity. Permissions define the actions that can be performed against an object or bucket (for example, READ or WRITE); the entity defines who the permission applies to (for example, a specific user or group of users).
Where an entity value is accepted, we follow the format the Cloud Storage API expects.
Refer to https://cloud.google.com/storage/docs/json_api/v1/defaultObjectAccessControls for the most up-to-date values.
user-userId
user-email
group-groupId
group-email
domain-domain
project-team-projectId
allUsers
allAuthenticatedUsers
Examples:
The user "liz@example.com" would be user-liz@example.com.
The group "example@googlegroups.com" would be group-example@googlegroups.com.
To refer to all members of the Google Apps for Business domain "example.com", the entity would be domain-example.com.
For more detailed information, see About Access Control Lists.
@constructor Acl @mixin
Parameters
{object} options Configuration options.
Member Function Documentation
_assignAccessMethods() [1/2]
AclRoleAccessorMethods::_assignAccessMethods (role) [inline], [inherited]
References accessMethods, args, callback, entities, and method.
_assignAccessMethods() [2/2]
AclRoleAccessorMethods::_assignAccessMethods (role) [inline], [inherited]
References accessMethods, args, callback, entities, and method.
add() [1/2]
Acl::add (options, callback) [inline]
References callback, json, makeAclObject_(), method, qs, query, and request.
add() [2/2]
Acl::add (options, callback) [inline]
References callback, json, makeAclObject_(), method, qs, query, and request.
constructor() [1/2]
Acl::constructor (options) [inline]
constructor() [2/2]
Acl::constructor (options) [inline]
delete() [1/2]
Acl::delete (options, callback) [inline]
References callback, method, qs, query, and request.
delete() [2/2]
Acl::delete (options, callback) [inline]
References callback, method, qs, query, and request.
get() [1/2]
Acl::get (optionsOrCallback, cb) [inline]
References callback, makeAclObject_(), path, qs, query, and request.
get() [2/2]
Acl::get (optionsOrCallback, cb) [inline]
References callback, makeAclObject_(), path, qs, query, and request.
makeAclObject_() [1/2]
Acl::makeAclObject_ (accessControlObject) [inline], [private]
Transform API responses to a consistent object format.
References obj.
makeAclObject_() [2/2]
Acl::makeAclObject_ (accessControlObject) [inline], [private]
Transform API responses to a consistent object format.
References obj.
request() [1/2]
Acl::request (reqOpts, callback) [inline], [private]
Patch requests up to the bucket's request object.
Parameters
{string} method Action.
{string} path Request path.
{*} query Request query object.
{*} body Request body contents.
{function} callback Callback function.
References callback.
request() [2/2]
Acl::request (reqOpts, callback) [inline], [private]
Patch requests up to the bucket's request object.
Parameters
{string} method Action.
{string} path Request path.
{*} query Request query object.
{*} body Request body contents.
{function} callback Callback function.
References callback.
update() [1/2]
Acl::update (options, callback) [inline]
References callback, json, makeAclObject_(), method, qs, query, and request.
update() [2/2]
Acl::update (options, callback) [inline]
References callback, json, makeAclObject_(), method, qs, query, and request.
The documentation for this class was generated from the following files:
backend/node_modules/@google-cloud/storage/build/cjs/src/acl.js
backend/node_modules/@google-cloud/storage/build/esm/src/acl.js