backend/node_modules/@grpc/grpc-js/build/src/client-interceptors.js File Reference
Classes
class InterceptorConfigurationError
class ListenerBuilder
class RequesterBuilder
class InterceptingCall
class BaseInterceptingCall
class BaseUnaryInterceptingCall
class BaseStreamingInterceptingCall
Functions
function getCall (channel, path, options)
function getBottomInterceptingCall (channel, options, methodDefinition)
function getInterceptingCall (interceptorArgs, methodDefinition, options, channel)
Variables
use strict
exports getInterceptingCall = exports.InterceptingCall = exports.RequesterBuilder = exports.ListenerBuilder = exports.InterceptorConfigurationError = void 0
const metadata_1 = require("./metadata")
const call_interface_1 = require("./call-interface")
const constants_1 = require("./constants")
const error_1 = require("./error")
exports InterceptorConfigurationError = InterceptorConfigurationError
exports ListenerBuilder = ListenerBuilder
exports RequesterBuilder = RequesterBuilder
const defaultListener
const defaultRequester
exports InterceptingCall = InterceptingCall
Function Documentation
getBottomInterceptingCall()
function getBottomInterceptingCall (channel, options, methodDefinition)
References call, and getCall().
getCall()
function getCall (channel, path, options)
References _a, _b, call, credentials, parent, and path.
getInterceptingCall()
function getInterceptingCall (interceptorArgs, methodDefinition, options, channel)
References getBottomInterceptingCall(), getCall(), and InterceptorConfigurationError.
Variable Documentation
call_interface_1
const call_interface_1 = require("./call-interface")
constants_1
const constants_1 = require("./constants")
defaultListener
const defaultListener
Initial value:
= {
    onReceiveMetadata: (metadata, next) => {
        next(metadata);
    },
    onReceiveMessage: (message, next) => {
        next(message);
    },
    onReceiveStatus: (status, next) => {
        next(status);
    },
}
A Listener with a default pass-through implementation of each method. Used for filling out Listeners with some methods omitted.
defaultRequester
const defaultRequester
Initial value:
= {
    start: (metadata, listener, next) => {
        next(metadata, listener);
    },
    sendMessage: (message, next) => {
        next(message);
    },
    halfClose: next => {
        next();
    },
    cancel: next => {
        next();
    },
}
A Requester with a default pass-through implementation of each method. Used for filling out Requesters with some methods omitted.
error_1
const error_1 = require("./error")
getInterceptingCall
exports getInterceptingCall = exports.InterceptingCall = exports.RequesterBuilder = exports.ListenerBuilder = exports.InterceptorConfigurationError = void 0
InterceptingCall
exports InterceptingCall = InterceptingCall
InterceptorConfigurationError
exports InterceptorConfigurationError = InterceptorConfigurationError
ListenerBuilder
exports ListenerBuilder = ListenerBuilder
metadata_1
const metadata_1 = require("./metadata")
RequesterBuilder
exports RequesterBuilder = RequesterBuilder
strict
use strict