backend/node_modules/cliui/build/lib/index.js File Reference
Classes
class UI
Functions
function addBorder (col, ts, style)
function _minWidth (col)
function getWindowWidth ()
function alignRight (str, width)
function alignCenter (str, width)
function export cliui (opts, _mixin)
Variables
use strict
const align
const top = 0
const right = 1
const bottom = 2
const left = 3
let mixin
Function Documentation
_minWidth()
function _minWidth (col)
References left, and right.
addBorder()
function addBorder (col, ts, style)
References test.
alignCenter()
function alignCenter (str, width)
References mixin, and str().
alignRight()
function alignRight (str, width)
References mixin, and str().
cliui()
function export cliui (opts, _mixin)
References getWindowWidth(), mixin, and wrap.
getWindowWidth()
function getWindowWidth ()
References process.
Variable Documentation
align
const align
Initial value:
= {
    right: alignRight,
    center: alignCenter
}
bottom
const bottom = 2
left
const left = 3
mixin
let mixin
right
const right = 1
strict
use strict
top
const top = 0