backend/node_modules/cors/lib/index.js File Reference
Functions
function isString (s)
function isOriginAllowed (origin, allowedOrigin)
function configureOrigin (options, req)
function configureMethods (options)
function configureCredentials (options)
function configureAllowedHeaders (options, req)
function configureExposedHeaders (options)
function configureMaxAge (options)
function applyHeaders (headers, res)
function cors (options, req, res, next)
function middlewareWrapper (o)
Variables
var assign = require('object-assign')
var vary = require('vary')
var defaults
module exports = middlewareWrapper
Function Documentation
applyHeaders()
function applyHeaders (headers, res)
References applyHeaders(), Array, headers, i, n, res, and vary.
configureAllowedHeaders()
function configureAllowedHeaders (options, req)
References headers, req, and value.
configureCredentials()
function configureCredentials (options)
References value.
configureExposedHeaders()
function configureExposedHeaders (options)
References headers, and value.
configureMaxAge()
function configureMaxAge (options)
References value.
configureMethods()
function configureMethods (options)
References methods, and value.
configureOrigin()
function configureOrigin (options, req)
References headers, isOriginAllowed(), isString, req, and value.
cors()
function cors (options, req, res, next)
References applyHeaders(), configureAllowedHeaders(), configureCredentials(), configureExposedHeaders(), configureMaxAge(), configureMethods(), configureOrigin(), headers, method, next(), req, and res.
isOriginAllowed()
function isOriginAllowed (origin, allowedOrigin)
References Array, i, isOriginAllowed(), and isString.
isString()
function isString (s)
References s.
middlewareWrapper()
function middlewareWrapper (o)
References assign, cors, defaults, next(), o, req, and res.
Variable Documentation
assign
var assign = require('object-assign')
defaults
var defaults
Initial value:
= {
    origin: '*',
    methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
    preflightContinue: false,
    optionsSuccessStatus: 204
  }
exports
module exports = middlewareWrapper
vary
res vary = require('vary')
Add field to Vary. If already present in the Vary set, then this call is simply ignored.
Parameters
{Array|String} field
Returns
{ServerResponse} for chaining