backend/node_modules/firebase-admin/lib/app/credential-internal.js File Reference
Classes
class ServiceAccountCredential
class ServiceAccount
class ComputeEngineCredential
class RefreshTokenCredential
class RefreshToken
class ImpersonatedServiceAccountCredential
class ImpersonatedServiceAccount
Functions
function isApplicationDefault (credential)
function getApplicationDefault (httpAgent)
function copyAttr (to, from, key, alt)
function requestAccessToken (client, request)
function requestIDToken (client, request)
function getErrorMessage (err)
function getDetailFromResponse (response)
function credentialFromFile (filePath, httpAgent, ignoreMissing)
function readCredentialFile (filePath, ignoreMissing)
Variables
use strict
exports getApplicationDefault = exports.isApplicationDefault = exports.ImpersonatedServiceAccountCredential = exports.RefreshTokenCredential = exports.ComputeEngineCredential = exports.ServiceAccountCredential = void 0
const fs = require("fs")
const os = require("os")
const path = require("path")
const error_1 = require("../utils/error")
const api_request_1 = require("../utils/api-request")
const util = require("../utils/validator")
const GOOGLE_TOKEN_AUDIENCE
const GOOGLE_AUTH_TOKEN_PATH = '/o/oauth2/token'
const GOOGLE_METADATA_SERVICE_HOST = 'metadata.google.internal'
const GOOGLE_METADATA_SERVICE_TOKEN_PATH = '/computeMetadata/v1/instance/service-accounts/default/token'
const GOOGLE_METADATA_SERVICE_IDENTITY_PATH = '/computeMetadata/v1/instance/service-accounts/default/identity'
const GOOGLE_METADATA_SERVICE_PROJECT_ID_PATH = '/computeMetadata/v1/project/project-id'
const GOOGLE_METADATA_SERVICE_ACCOUNT_ID_PATH = '/computeMetadata/v1/instance/service-accounts/default/email'
const configDir
const GCLOUD_CREDENTIAL_SUFFIX = 'gcloud/application_default_credentials.json'
const GCLOUD_CREDENTIAL_PATH = configDir && path.resolve(configDir, GCLOUD_CREDENTIAL_SUFFIX)
const REFRESH_TOKEN_HOST = 'www.googleapis.com'
const REFRESH_TOKEN_PATH = '/oauth2/v4/token'
const ONE_HOUR_IN_SECONDS = 60 * 60
const JWT_ALGORITHM = 'RS256'
exports ServiceAccountCredential = ServiceAccountCredential
exports ComputeEngineCredential = ComputeEngineCredential
exports RefreshTokenCredential = RefreshTokenCredential
exports ImpersonatedServiceAccountCredential = ImpersonatedServiceAccountCredential
exports isApplicationDefault = isApplicationDefault
Function Documentation
copyAttr()
function copyAttr (to, from, key, alt)
Copies the specified property from one object to another.
If no property exists by the given "key", looks for a property identified by "alt", and copies it instead. This can be used to implement behaviors such as "copy property myKey or my_key".
Parameters
to - Target object to copy the property into.
from - Source object to copy the property from.
key - Name of the property to copy.
alt - Alternative name of the property to copy.
credentialFromFile()
function credentialFromFile (filePath, httpAgent, ignoreMissing)
References error_1, ImpersonatedServiceAccountCredential, readCredentialFile(), RefreshTokenCredential, and ServiceAccountCredential.
getApplicationDefault()
function getApplicationDefault (httpAgent)
References ComputeEngineCredential, credential, credentialFromFile(), GCLOUD_CREDENTIAL_PATH, and process.
getDetailFromResponse()
function getDetailFromResponse (response)
Extracts details from the given HTTP error response, and returns a human-readable description. If the response is JSON-formatted, looks up the error and error_description fields sent by the Google Auth servers. Otherwise returns the entire response payload as the error detail.
References response.
getErrorMessage()
function getErrorMessage (err)
Constructs a human-readable error message from the given Error.
References $, api_request_1, getDetailFromResponse(), and token.
isApplicationDefault()
function isApplicationDefault (credential)
Checks if the given credential was loaded via the application default credentials mechanism. This includes all ComputeEngineCredential instances, and the ServiceAccountCredential and RefreshTokenCredential instances that were loaded from well-known files or environment variables, rather than being explicitly instantiated.
Parameters
credential - The credential instance to check.
References credential.
readCredentialFile()
function readCredentialFile (filePath, ignoreMissing)
References $, credentials, error, error_1, file, fs, JSON, and read.
requestAccessToken()
function requestAccessToken (client, request)
Obtain a new OAuth2 token by making a remote service call.
References $, client, error_1, getErrorMessage, json, request, response, and token.
requestIDToken()
function requestIDToken (client, request)
Obtain a new OIDC token by making a remote service call.
References client, error_1, getErrorMessage, and request.
Variable Documentation
api_request_1
const api_request_1 = require("../utils/api-request")
ComputeEngineCredential
exports ComputeEngineCredential = ComputeEngineCredential
configDir
const configDir
Initial value:
= (() => {
    
    const sys = os.platform();
    if (sys && sys.length >= 3 && sys.substring(0, 3).toLowerCase() === 'win') {
        return process.env.APPDATA;
    }
    
    return process.env.HOME && path.resolve(process.env.HOME, '.config');
})()
error_1
const error_1 = require("../utils/error")
fs
const fs = require("fs")
GCLOUD_CREDENTIAL_PATH
const GCLOUD_CREDENTIAL_PATH = configDir && path.resolve(configDir, GCLOUD_CREDENTIAL_SUFFIX)
GCLOUD_CREDENTIAL_SUFFIX
const GCLOUD_CREDENTIAL_SUFFIX = 'gcloud/application_default_credentials.json'
getApplicationDefault
exports getApplicationDefault = exports.isApplicationDefault = exports.ImpersonatedServiceAccountCredential = exports.RefreshTokenCredential = exports.ComputeEngineCredential = exports.ServiceAccountCredential = void 0
GOOGLE_AUTH_TOKEN_PATH
const GOOGLE_AUTH_TOKEN_PATH = '/o/oauth2/token'
GOOGLE_METADATA_SERVICE_ACCOUNT_ID_PATH
const GOOGLE_METADATA_SERVICE_ACCOUNT_ID_PATH = '/computeMetadata/v1/instance/service-accounts/default/email'
GOOGLE_METADATA_SERVICE_HOST
const GOOGLE_METADATA_SERVICE_HOST = 'metadata.google.internal'
GOOGLE_METADATA_SERVICE_IDENTITY_PATH
const GOOGLE_METADATA_SERVICE_IDENTITY_PATH = '/computeMetadata/v1/instance/service-accounts/default/identity'
GOOGLE_METADATA_SERVICE_PROJECT_ID_PATH
const GOOGLE_METADATA_SERVICE_PROJECT_ID_PATH = '/computeMetadata/v1/project/project-id'
GOOGLE_METADATA_SERVICE_TOKEN_PATH
const GOOGLE_METADATA_SERVICE_TOKEN_PATH = '/computeMetadata/v1/instance/service-accounts/default/token'
GOOGLE_TOKEN_AUDIENCE
const GOOGLE_TOKEN_AUDIENCE
Initial value:
= 'https:
const GOOGLE_AUTH_TOKEN_HOST = 'accounts.google.com'
ImpersonatedServiceAccountCredential
exports ImpersonatedServiceAccountCredential = ImpersonatedServiceAccountCredential
isApplicationDefault
exports isApplicationDefault = isApplicationDefault
JWT_ALGORITHM
const JWT_ALGORITHM = 'RS256'
ONE_HOUR_IN_SECONDS
const ONE_HOUR_IN_SECONDS = 60 * 60
os
const os = require("os")
path
const path = require("path")
REFRESH_TOKEN_HOST
const REFRESH_TOKEN_HOST = 'www.googleapis.com'
REFRESH_TOKEN_PATH
const REFRESH_TOKEN_PATH = '/oauth2/v4/token'
RefreshTokenCredential
exports RefreshTokenCredential = RefreshTokenCredential
ServiceAccountCredential
exports ServiceAccountCredential = ServiceAccountCredential
strict
use strict
firebase-admin v12.7.0
util
const util = require("../utils/validator")