backend/node_modules/@firebase/database/dist/node-esm/index.node.esm.js File Reference
Classes
class DOMStorageWrapper
class MemoryStorage
class RepoInfo
class StatsCollection
class WebSocketConnection
class AppCheckTokenProvider
class FirebaseAuthTokenProvider
class EmulatorTokenProvider
class PacketReceiver
class BrowserPollConnection
class FirebaseIFrameScriptHolder
class TransportManager
class Connection
class ServerActions
class EventEmitter
class OnlineMonitor
class Path
class ValidationPath
class VisibilityMonitor
class PersistentConnection
class NamedNode
class Index
class KeyIndex
class SortedMapIterator
class LLRBNode
class LLRBEmptyNode
class SortedMap
class LeafNode
class PriorityIndex
class Base12Num
class IndexMap
class ChildrenNode
class MaxNode
class PathIndex
class ValueIndex
class IndexedFilter
class RangedFilter
class LimitedFilter
class QueryParams
class ReadonlyRestClient
class SnapshotHolder
class StatsListener
class StatsReporter
class AckUserWrite
class ListenComplete
class Overwrite
class Merge
class CacheNode
class EventGenerator
class ImmutableTree
class CompoundWrite
class ChildChangeAccumulator
class NoCompleteChildSource_
class WriteTreeCompleteChildSource
class View
class SyncPoint
class SyncTree
class ExistingValueProvider
class DeferredValueProvider
class Tree
Functions
function each (obj, fn)
function errorForServerCode (code, query)
function repoInfoNeedsQueryParam (repoInfo)
function repoInfoConnectionURL (repoInfo, type, params)
function statsManagerGetCollection (repoInfo)
function statsManagerGetOrCreateReporter (repoInfo, creatorFunction)
function setSDKVersion (version)
if (typeof MozWebSocket !=='undefined')
function setWebSocketImpl (impl)
function newEmptyPath ()
function pathGetFront (path)
function pathGetLength (path)
function pathPopFront (path)
function pathGetBack (path)
function pathToUrlEncodedString (path)
function pathSlice (path, begin=0)
function pathParent (path)
function pathChild (path, childPathObj)
function pathIsEmpty (path)
function newRelativePath (outerPath, innerPath)
function pathCompare (left, right)
function pathEquals (path, other)
function pathContains (path, other)
function validationPathPush (validationPath, child)
function validationPathPop (validationPath)
function validationPathCheckValid (validationPath)
function validationPathToErrorString (validationPath)
unlisten (query, tag)
sendUnlisten_ (pathString, queryId, queryObj, tag)
onDisconnectPut (pathString, data, onComplete)
onDisconnectMerge (pathString, data, onComplete)
onDisconnectCancel (pathString, onComplete)
sendOnDisconnect_ (action, pathString, data, onComplete)
put (pathString, data, onComplete, hash)
merge (pathString, data, onComplete, hash)
putInternal (action, pathString, data, onComplete, hash)
sendPut_ (index)
reportStats (stats)
onDataMessage_ (message)
onDataPush_ (action, body)
onReady_ (timestamp, sessionId)
scheduleConnect_ (timeout)
initConnection_ ()
onVisible_ (visible)
onOnline_ (online)
onRealtimeDisconnect_ ()
async establishConnection_ ()
interrupt (reason)
resume (reason)
handleTimestamp_ (timestamp)
cancelSentTransactions_ ()
onListenRevoked_ (pathString, query)
removeListen_ (pathString, queryId)
onAuthRevoked_ (statusCode, explanation)
onAppCheckRevoked_ (statusCode, explanation)
onSecurityDebugPacket_ (body)
restoreState_ ()
sendConnectStats_ ()
shouldReconnect_ ()
function NAME_ONLY_COMPARATOR (left, right)
function NAME_COMPARATOR (left, right)
function setMaxNode$1 (val)
function setNodeFromJSON (val)
function setMaxNode (val)
function nodeFromJSON (json, priority=null)
function changeValue (snapshotNode)
function changeChildAdded (childName, snapshotNode)
function changeChildRemoved (childName, snapshotNode)
function changeChildChanged (childName, snapshotNode, oldSnap)
function changeChildMoved (childName, snapshotNode)
function queryParamsGetNodeFilter (queryParams)
function queryParamsLimitToFirst (queryParams, newLimit)
function queryParamsLimitToLast (queryParams, newLimit)
function queryParamsStartAt (queryParams, indexValue, key)
function queryParamsStartAfter (queryParams, indexValue, key)
function queryParamsEndAt (queryParams, indexValue, key)
function queryParamsEndBefore (queryParams, indexValue, key)
function queryParamsOrderBy (queryParams, index)
function queryParamsToRestQueryStringParameters (queryParams)
function queryParamsGetQueryObject (queryParams)
function newSparseSnapshotTree ()
function sparseSnapshotTreeRemember (sparseSnapshotTree, path, data)
function sparseSnapshotTreeForget (sparseSnapshotTree, path)
function sparseSnapshotTreeForEachTree (sparseSnapshotTree, prefixPath, func)
function sparseSnapshotTreeForEachChild (sparseSnapshotTree, func)
function newOperationSourceUser ()
function newOperationSourceServer ()
function newOperationSourceServerTaggedQuery (queryId)
function eventGeneratorGenerateEventsForChanges (eventGenerator, changes, eventCache, eventRegistrations)
function eventGeneratorGenerateEventsForType (eventGenerator, events, eventType, changes, registrations, eventCache)
function eventGeneratorMaterializeSingleChange (eventGenerator, change, eventCache)
function eventGeneratorCompareChanges (eventGenerator, a, b)
function newViewCache (eventCache, serverCache)
function viewCacheUpdateEventSnap (viewCache, eventSnap, complete, filtered)
function viewCacheUpdateServerSnap (viewCache, serverSnap, complete, filtered)
function viewCacheGetCompleteEventSnap (viewCache)
function viewCacheGetCompleteServerSnap (viewCache)
function compoundWriteAddWrite (compoundWrite, path, node)
function compoundWriteAddWrites (compoundWrite, path, updates)
function compoundWriteRemoveWrite (compoundWrite, path)
function compoundWriteHasCompleteWrite (compoundWrite, path)
function compoundWriteGetCompleteNode (compoundWrite, path)
function compoundWriteGetCompleteChildren (compoundWrite)
function compoundWriteChildCompoundWrite (compoundWrite, path)
function compoundWriteIsEmpty (compoundWrite)
function compoundWriteApply (compoundWrite, node)
function applySubtreeWrite (relativePath, writeTree, node)
function writeTreeChildWrites (writeTree, path)
function writeTreeAddOverwrite (writeTree, path, snap, writeId, visible)
function writeTreeAddMerge (writeTree, path, changedChildren, writeId)
function writeTreeGetWrite (writeTree, writeId)
function writeTreeRemoveWrite (writeTree, writeId)
function writeTreeRecordContainsPath_ (writeRecord, path)
function writeTreeResetTree_ (writeTree)
function writeTreeDefaultFilter_ (write)
function writeTreeLayerTree_ (writes, filter, treeRoot)
function writeTreeCalcCompleteEventCache (writeTree, treePath, completeServerCache, writeIdsToExclude, includeHiddenWrites)
function writeTreeCalcCompleteEventChildren (writeTree, treePath, completeServerChildren)
function writeTreeCalcEventCacheAfterServerOverwrite (writeTree, treePath, childPath, existingEventSnap, existingServerSnap)
function writeTreeCalcCompleteChild (writeTree, treePath, childKey, existingServerSnap)
function writeTreeShadowingWrite (writeTree, path)
function writeTreeCalcIndexedSlice (writeTree, treePath, completeServerData, startPost, count, reverse, index)
function newWriteTree ()
function writeTreeRefCalcCompleteEventCache (writeTreeRef, completeServerCache, writeIdsToExclude, includeHiddenWrites)
function writeTreeRefCalcCompleteEventChildren (writeTreeRef, completeServerChildren)
function writeTreeRefCalcEventCacheAfterServerOverwrite (writeTreeRef, path, existingEventSnap, existingServerSnap)
function writeTreeRefShadowingWrite (writeTreeRef, path)
function writeTreeRefCalcIndexedSlice (writeTreeRef, completeServerData, startPost, count, reverse, index)
function writeTreeRefCalcCompleteChild (writeTreeRef, childKey, existingServerCache)
function writeTreeRefChild (writeTreeRef, childName)
function newWriteTreeRef (path, writeTree)
function newViewProcessor (filter)
function viewProcessorAssertIndexed (viewProcessor, viewCache)
function viewProcessorApplyOperation (viewProcessor, oldViewCache, operation, writesCache, completeCache)
function viewProcessorMaybeAddValueEvent (oldViewCache, newViewCache, accumulator)
function viewProcessorGenerateEventCacheAfterServerEvent (viewProcessor, viewCache, changePath, writesCache, source, accumulator)
function viewProcessorApplyServerOverwrite (viewProcessor, oldViewCache, changePath, changedSnap, writesCache, completeCache, filterServerNode, accumulator)
function viewProcessorApplyUserOverwrite (viewProcessor, oldViewCache, changePath, changedSnap, writesCache, completeCache, accumulator)
function viewProcessorCacheHasChild (viewCache, childKey)
function viewProcessorApplyUserMerge (viewProcessor, viewCache, path, changedChildren, writesCache, serverCache, accumulator)
function viewProcessorApplyMerge (viewProcessor, node, merge)
function viewProcessorApplyServerMerge (viewProcessor, viewCache, path, changedChildren, writesCache, serverCache, filterServerNode, accumulator)
function viewProcessorAckUserWrite (viewProcessor, viewCache, ackPath, affectedTree, writesCache, completeCache, accumulator)
function viewProcessorListenComplete (viewProcessor, viewCache, path, writesCache, accumulator)
function viewProcessorRevertUserWrite (viewProcessor, viewCache, path, writesCache, completeServerCache, accumulator)
function viewGetServerCache (view)
function viewGetCompleteNode (view)
function viewGetCompleteServerCache (view, path)
function viewIsEmpty (view)
function viewAddEventRegistration (view, eventRegistration)
function viewRemoveEventRegistration (view, eventRegistration, cancelError)
function viewApplyOperation (view, operation, writesCache, completeServerCache)
function viewGetInitialEvents (view, registration)
function viewGenerateEventsForChanges_ (view, changes, eventCache, eventRegistration)
function syncPointSetReferenceConstructor (val)
function syncPointGetReferenceConstructor ()
function syncPointIsEmpty (syncPoint)
function syncPointApplyOperation (syncPoint, operation, writesCache, optCompleteServerCache)
function syncPointGetView (syncPoint, query, writesCache, serverCache, serverCacheComplete)
function syncPointAddEventRegistration (syncPoint, query, eventRegistration, writesCache, serverCache, serverCacheComplete)
function syncPointRemoveEventRegistration (syncPoint, query, eventRegistration, cancelError)
function syncPointGetQueryViews (syncPoint)
function syncPointGetCompleteServerCache (syncPoint, path)
function syncPointViewForQuery (syncPoint, query)
function syncPointViewExistsForQuery (syncPoint, query)
function syncPointHasCompleteView (syncPoint)
function syncPointGetCompleteView (syncPoint)
function syncTreeSetReferenceConstructor (val)
function syncTreeGetReferenceConstructor ()
function syncTreeApplyUserOverwrite (syncTree, path, newData, writeId, visible)
function syncTreeApplyUserMerge (syncTree, path, changedChildren, writeId)
function syncTreeAckUserWrite (syncTree, writeId, revert=false)
function syncTreeApplyServerOverwrite (syncTree, path, newData)
function syncTreeApplyServerMerge (syncTree, path, changedChildren)
function syncTreeApplyListenComplete (syncTree, path)
function syncTreeApplyTaggedListenComplete (syncTree, path, tag)
function syncTreeRemoveEventRegistration (syncTree, query, eventRegistration, cancelError, skipListenerDedup=false)
function syncTreeApplyTaggedQueryOverwrite (syncTree, path, snap, tag)
function syncTreeApplyTaggedQueryMerge (syncTree, path, changedChildren, tag)
function syncTreeAddEventRegistration (syncTree, query, eventRegistration, skipSetupListener=false)
function syncTreeCalcCompleteEventCache (syncTree, path, writeIdsToExclude)
function syncTreeGetServerValue (syncTree, query)
function syncTreeApplyOperationToSyncPoints_ (syncTree, operation)
function syncTreeApplyOperationHelper_ (operation, syncPointTree, serverCache, writesCache)
function syncTreeApplyOperationDescendantsHelper_ (operation, syncPointTree, serverCache, writesCache)
function syncTreeCreateListenerForView_ (syncTree, view)
function syncTreeTagForQuery (syncTree, query)
function syncTreeMakeQueryKey_ (query)
function syncTreeQueryKeyForTag_ (syncTree, tag)
function syncTreeParseQueryKey_ (queryKey)
function syncTreeApplyTaggedOperation_ (syncTree, queryPath, operation)
function syncTreeCollectDistinctViewsForSubTree_ (subtree)
function syncTreeQueryForListening_ (query)
function syncTreeRemoveTags_ (syncTree, queries)
function syncTreeGetNextQueryTag_ ()
function syncTreeSetupListener_ (syncTree, query, view)
function resolveDeferredValue (node, existingVal, serverValues)
function treeSubTree (tree, pathObj)
function treeGetValue (tree)
function treeSetValue (tree, value)
function treeHasChildren (tree)
function treeIsEmpty (tree)
function treeForEachChild (tree, action)
function treeForEachDescendant (tree, action, includeSelf, childrenFirst)
function treeForEachAncestor (tree, action, includeSelf)
function treeGetPath (tree)
function treeUpdateParents (tree)
function treeUpdateChild (tree, childName, child)
Variables
import Websocket from faye websocket
import { stringify, jsonEval, contains, assert, isNodeSdk, stringToByteArray, Sha1, base64, deepCopy, base64Encode, isMobileCordova, stringLength, Deferred, safeGet, isAdmin, isValidFormat, isEmpty, isReactNative, assertionError, map, querystring, errorPrefix, getModularInstance, getDefaultEmulatorHostnameAndPort, createMockUserToken } from '@firebase/util'
const PROTOCOL_VERSION = '5'
const VERSION_PARAM = 'v'
const TRANSPORT_SESSION_PARAM = 's'
const REFERER_PARAM = 'r'
const FORGE_REF = 'f'
const FORGE_DOMAIN_RE = /(console\.firebase|firebase-console-\w+\.corp|firebase\.corp)\.google\.com/
const LAST_SESSION_PARAM = 'ls'
const APPLICATION_ID_PARAM = 'p'
const APP_CHECK_TOKEN_PARAM = 'ac'
const WEBSOCKET = 'websocket'
const LONG_POLLING = 'long_polling'
const createStoragefor
const PersistentStorage = createStoragefor('localStorage')
const SessionStorage = createStoragefor('sessionStorage')
const logClient = new Logger('@firebase/database')
const LUIDGenerator
const sha1
const buildLogMessage_
let logger = null
let firstLog_ = true
const enableLogging$1
const log
const logWrapper
const error
const fatal
const warn
const warnIfPageIsSecure
const isInvalidJSONNumber
const executeWhenDOMReady
const MIN_NAME = '[MIN_NAME]'
const MAX_NAME = '[MAX_NAME]'
const nameCompare
const stringCompare
const requireKey
const ObjectToUniqueKey
const splitStringBySize
const doubleToIEEE754String
const isChromeExtensionContentScript
const isWindowsStoreApp
const INTEGER_REGEXP_ = new RegExp('^-?(0*)\\d{1,10}$')
const INTEGER_32_MIN = -2147483648
const INTEGER_32_MAX = 2147483647
const tryParseInt
const exceptionGuard
const beingCrawled
const setTimeoutNonBlocking
const collections = {}
const reporters = {}
let SDK_VERSION = ''
const WEBSOCKET_MAX_FRAME_SIZE = 16384
const WEBSOCKET_KEEPALIVE_INTERVAL = 45000
let WebSocketImpl = null
WebSocketConnection responsesRequiredToBeHealthy = 2
WebSocketConnection healthyTimeout = 30000
const name = "@firebase/database"
const version = "1.0.8"
EmulatorTokenProvider OWNER = 'owner'
const FIREBASE_LONGPOLL_START_PARAM = 'start'
const FIREBASE_LONGPOLL_CLOSE_COMMAND = 'close'
const FIREBASE_LONGPOLL_COMMAND_CB_NAME = 'pLPCommand'
const FIREBASE_LONGPOLL_DATA_CB_NAME = 'pRTLPCB'
const FIREBASE_LONGPOLL_ID_PARAM = 'id'
const FIREBASE_LONGPOLL_PW_PARAM = 'pw'
const FIREBASE_LONGPOLL_SERIAL_PARAM = 'ser'
const FIREBASE_LONGPOLL_CALLBACK_ID_PARAM = 'cb'
const FIREBASE_LONGPOLL_SEGMENT_NUM_PARAM = 'seg'
const FIREBASE_LONGPOLL_SEGMENTS_IN_PACKET = 'ts'
const FIREBASE_LONGPOLL_DATA_PARAM = 'd'
const FIREBASE_LONGPOLL_DISCONN_FRAME_REQUEST_PARAM = 'dframe'
const MAX_URL_DATA_SIZE = 1870
const SEG_HEADER_SIZE = 30
const MAX_PAYLOAD_SIZE = MAX_URL_DATA_SIZE - SEG_HEADER_SIZE
const KEEPALIVE_REQUEST_INTERVAL = 25000
const LP_CONNECT_TIMEOUT = 30000
TransportManager globalTransportInitialized_ = false
const UPGRADE_TIMEOUT = 60000
const DELAY_BEFORE_SENDING_EXTRA_REQUESTS = 5000
const BYTES_SENT_HEALTHY_OVERRIDE = 10 * 1024
const BYTES_RECEIVED_HEALTHY_OVERRIDE = 100 * 1024
const MESSAGE_TYPE = 't'
const MESSAGE_DATA = 'd'
const CONTROL_SHUTDOWN = 's'
const CONTROL_RESET = 'r'
const CONTROL_ERROR = 'e'
const CONTROL_PONG = 'o'
const SWITCH_ACK = 'a'
const END_TRANSMISSION = 'n'
const PING = 'p'
const SERVER_HELLO = 'h'
const MAX_PATH_DEPTH = 32
const MAX_PATH_LENGTH_BYTES = 768
const RECONNECT_MIN_DELAY = 1000
const RECONNECT_MAX_DELAY_DEFAULT = 60 * 5 * 1000
const RECONNECT_MAX_DELAY_FOR_ADMINS = 30 * 1000
const RECONNECT_DELAY_MULTIPLIER = 1.3
const RECONNECT_DELAY_RESET_TIMEOUT = 30000
const SERVER_KILL_INTERRUPT_REASON = 'server_kill'
const INVALID_TOKEN_THRESHOLD = 3
PersistentConnection nextPersistentConnectionId_ = 0
PersistentConnection nextConnectionId_ = 0
let __EMPTY_NODE = ChildrenNode.EMPTY_NODE
const KEY_INDEX = new KeyIndex()
LLRBNode RED = true
LLRBNode BLACK = false
SortedMap EMPTY_NODE = new LLRBEmptyNode()
let MAX_NODE$2
const priorityHashText
const validatePriorityNode
let __childrenNodeConstructor = ChildrenNode
LeafNode VALUE_TYPE_ORDER = ['object', 'boolean', 'number', 'string']
let nodeFromJSON$1
let MAX_NODE$1
const PRIORITY_INDEX = new PriorityIndex()
const LOG_2 = Math.log(2)
const buildChildSet
let _defaultIndexMap
const fallbackObject = {}
const MAX_NODE = new MaxNode()
const USE_HINZE = true
const VALUE_INDEX = new ValueIndex()
const FIRST_STATS_MIN_TIME = 10 * 1000
const FIRST_STATS_MAX_TIME = 30 * 1000
const REPORT_STATS_INTERVAL = 5 * 60 * 1000
var OperationType
let emptyChildrenSingleton
const EmptyChildren
const NO_COMPLETE_CHILD_SOURCE = new NoCompleteChildSource_()
let referenceConstructor$1
let referenceConstructor
let syncTreeNextQueryTag_ = 1
const generateWithValues
const resolveDeferredLeafValue
const resolveScalarDeferredValue
const resolveComplexDeferredValue
const resolveDeferredValueTree
const resolveDeferredValueSnapshot
const INVALID_KEY_REGEX_ = /[\[\].#$\/\u0000-\u001F\u007F]/
const INVALID_PATH_REGEX_ = /[\[\].#$\u0000-\u001F\u007F]/
const MAX_LEAF_SIZE_ = 10 * 1024 * 1024
const isValidKey
const isValidPathString
Function Documentation
applySubtreeWrite()
function applySubtreeWrite (relativePath, writeTree, node)
References applySubtreeWrite(), assert, node, and pathChild().
cancelSentTransactions_()
cancelSentTransactions_ ()
References i, and put.
changeChildAdded()
function changeChildAdded (childName, snapshotNode)
References type.
changeChildChanged()
function changeChildChanged (childName, snapshotNode, oldSnap)
References type.
changeChildMoved()
function changeChildMoved (childName, snapshotNode)
References type.
changeChildRemoved()
function changeChildRemoved (childName, snapshotNode)
References type.
changeValue()
function changeValue (snapshotNode)
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
References type.
compoundWriteAddWrite()
function compoundWriteAddWrite (compoundWrite, path, node)
References newRelativePath(), newWriteTree(), node, path, pathIsEmpty(), and value.
compoundWriteAddWrites()
function compoundWriteAddWrites (compoundWrite, path, updates)
References compoundWriteAddWrite(), each, node, path, and pathChild().
compoundWriteApply()
function compoundWriteApply (compoundWrite, node)
Applies this CompoundWrite to a node. The node is returned with all writes from this CompoundWrite applied to the node
Parameters
node - The node to apply this CompoundWrite to
Returns
The node with all writes applied
References applySubtreeWrite(), newEmptyPath(), and node.
compoundWriteChildCompoundWrite()
function compoundWriteChildCompoundWrite (compoundWrite, path)
References compoundWriteGetCompleteNode(), path, and pathIsEmpty().
compoundWriteGetCompleteChildren()
function compoundWriteGetCompleteChildren (compoundWrite)
Returns all children that are guaranteed to be a complete overwrite.
Parameters
compoundWrite - The CompoundWrite to get children from.
Returns
A list of all complete children.
References node, and PRIORITY_INDEX.
compoundWriteGetCompleteNode()
function compoundWriteGetCompleteNode (compoundWrite, path)
Returns a node for a path if and only if the node is a "complete" overwrite at that path. This will not aggregate writes from deeper paths, but will return child nodes from a more shallow path.
Parameters
compoundWrite - The CompoundWrite to get the node from.
path - The path to get a complete write
Returns
The node if complete at that path, or null otherwise.
References newRelativePath(), and path.
compoundWriteHasCompleteWrite()
function compoundWriteHasCompleteWrite (compoundWrite, path)
Returns whether this CompoundWrite will fully overwrite a node at a given location and can therefore be considered "complete".
Parameters
compoundWrite - The CompoundWrite to check.
path - The path to check for
Returns
Whether there is a complete write at that path
References compoundWriteGetCompleteNode(), and path.
compoundWriteIsEmpty()
function compoundWriteIsEmpty (compoundWrite)
Returns true if this CompoundWrite is empty and therefore does not modify any nodes.
Returns
Whether this CompoundWrite is empty
compoundWriteRemoveWrite()
function compoundWriteRemoveWrite (compoundWrite, path)
Will remove a write at the given path and deeper paths. This will not modify a write at a higher location, which must be removed by calling this method with that path.
Parameters
compoundWrite - The CompoundWrite to remove.
path - The path at which a write and all deeper writes should be removed
Returns
The new CompoundWrite with the removed path
References CompoundWrite::empty(), newWriteTree(), path, and pathIsEmpty().
each()
function each (obj, fn)
Apply a function to each (key, value) pair in an object or apply a function to each (index, value) pair in an array
Parameters
obj - The object or array to iterate over
fn - The function to apply
References fn, and obj.
errorForServerCode()
function errorForServerCode (code, query)
Converts a server error code to a JavaScript Error
References error, query, and reason.
establishConnection_()
async establishConnection_ ()
References assert, close, error, interrupt(), log, msg, onDataMessage_(), onReady_(), onRealtimeDisconnect_(), Promise, reason, PersistentConnection::sendRequest(), SERVER_KILL_INTERRUPT_REASON, shouldReconnect_(), and warn.
eventGeneratorCompareChanges()
function eventGeneratorCompareChanges (eventGenerator, a, b)
References a, assertionError, and b.
eventGeneratorGenerateEventsForChanges()
function eventGeneratorGenerateEventsForChanges (eventGenerator, changes, eventCache, eventRegistrations)
Given a set of raw changes (no moved events and prevName not specified yet), and a set of EventRegistrations that should be notified of these changes, generate the actual events to be raised.
Notes:
child_moved events will be synthesized at this time for any child_changed events that affect our index.
prevName will be calculated based on the index ordering.
References changeChildMoved(), and eventGeneratorGenerateEventsForType().
eventGeneratorGenerateEventsForType()
function eventGeneratorGenerateEventsForType (eventGenerator, events, eventType, changes, registrations, eventCache)
Given changes of a single change type, generate the corresponding events.
References a, b, eventGeneratorCompareChanges(), and eventGeneratorMaterializeSingleChange().
eventGeneratorMaterializeSingleChange()
function eventGeneratorMaterializeSingleChange (eventGenerator, change, eventCache)
handleTimestamp_()
handleTimestamp_ (timestamp)
References timestamp.
if()
if (typeof MozWebSocket ! = = 'undefined')
References WebSocketImpl.
initConnection_()
initConnection_ ()
References scheduleConnect_().
interrupt()
interrupt (reason)
References log, onRealtimeDisconnect_(), and reason.
merge()
merge (pathString, data, onComplete, hash)
References data, hash(), and putInternal().
NAME_COMPARATOR()
function NAME_COMPARATOR (left, right)
References left, nameCompare, and right.
NAME_ONLY_COMPARATOR()
function NAME_ONLY_COMPARATOR (left, right)
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
References left, nameCompare, and right.
newEmptyPath()
function newEmptyPath ()
newOperationSourceServer()
function newOperationSourceServer ()
newOperationSourceServerTaggedQuery()
function newOperationSourceServerTaggedQuery (queryId)
newOperationSourceUser()
function newOperationSourceUser ()
newRelativePath()
function newRelativePath (outerPath, innerPath)
Returns
The path from outerPath to innerPath
References newRelativePath(), pathGetFront(), and pathPopFront().
newSparseSnapshotTree()
function newSparseSnapshotTree ()
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
References Map, and value.
newViewCache()
function newViewCache (eventCache, serverCache)
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Here is the caller graph for this function:
newViewProcessor()
function newViewProcessor (filter)
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
References filter.
newWriteTree()
function newWriteTree ()
References CompoundWrite::empty().
newWriteTreeRef()
function newWriteTreeRef (path, writeTree)
References path.
nodeFromJSON()
function nodeFromJSON (json, priority = null)
Constructs a snapshot node representing the passed JSON and returns it.
Parameters
json - JSON to create a node for.
priority - Optional priority to use. This will be ignored if the passed JSON contains a .priority property.
References Array, assert, buildChildSet, contains, IndexMap::Default(), each, ChildrenNode::EMPTY_NODE(), json, NAME_COMPARATOR(), NAME_ONLY_COMPARATOR(), node, nodeFromJSON(), PRIORITY_INDEX, and USE_HINZE.
onAppCheckRevoked_()
onAppCheckRevoked_ (statusCode, explanation)
References INVALID_TOKEN_THRESHOLD, and log.
onAuthRevoked_()
onAuthRevoked_ (statusCode, explanation)
References INVALID_TOKEN_THRESHOLD, log, and RECONNECT_MAX_DELAY_FOR_ADMINS.
onDataMessage_()
onDataMessage_ (message)
References message, onDataPush_(), and stringify.
onDataPush_()
onDataPush_ (action, body)
References error, onAppCheckRevoked_(), onAuthRevoked_(), onListenRevoked_(), onSecurityDebugPacket_(), and stringify.
onDisconnectCancel()
onDisconnectCancel (pathString, onComplete)
References data, initConnection_(), and sendOnDisconnect_().
onDisconnectMerge()
onDisconnectMerge (pathString, data, onComplete)
References data, initConnection_(), and sendOnDisconnect_().
onDisconnectPut()
onDisconnectPut (pathString, data, onComplete)
References data, initConnection_(), and sendOnDisconnect_().
onListenRevoked_()
onListenRevoked_ (pathString, query)
References listen, ObjectToUniqueKey, q, query, and removeListen_().
onOnline_()
onOnline_ (online)
References RECONNECT_MIN_DELAY, and scheduleConnect_().
onReady_()
onReady_ (timestamp, sessionId)
References handleTimestamp_(), restoreState_(), sendConnectStats_(), and timestamp.
onRealtimeDisconnect_()
onRealtimeDisconnect_ ()
References cancelSentTransactions_(), RECONNECT_DELAY_MULTIPLIER, RECONNECT_DELAY_RESET_TIMEOUT, RECONNECT_MIN_DELAY, scheduleConnect_(), and shouldReconnect_().
onSecurityDebugPacket_()
onSecurityDebugPacket_ (body)
References replace.
onVisible_()
onVisible_ (visible)
References RECONNECT_MIN_DELAY, scheduleConnect_(), and visible.
pathChild()
function pathChild (path, childPathObj)
References i, length, and path.
pathCompare()
function pathCompare (left, right)
Returns
-1, 0, 1 if left is less, equal, or greater than the right.
References i, left, nameCompare, pathSlice(), and right.
pathContains()
function pathContains (path, other)
Returns
True if this path is a parent of (or the same as) other
References i, j, path, and pathGetLength().
pathEquals()
function pathEquals (path, other)
Returns
true if paths are the same.
References i, j, path, and pathGetLength().
pathGetBack()
function pathGetBack (path)
References path.
pathGetFront()
function pathGetFront (path)
References path.
pathGetLength()
function pathGetLength (path)
Returns
The number of segments in this path
References path.
pathIsEmpty()
function pathIsEmpty (path)
Returns
True if there are no segments in this path
References path.
pathParent()
function pathParent (path)
References i, and path.
pathPopFront()
function pathPopFront (path)
References path.
pathSlice()
function pathSlice (path, begin = 0)
Shallow copy of the parts of the path.
References begin, and path.
pathToUrlEncodedString()
function pathToUrlEncodedString (path)
References i, and path.
put()
put (pathString, data, onComplete, hash)
References data, hash(), and putInternal().
putInternal()
putInternal (action, pathString, data, onComplete, hash)
References d, data, hash(), index, initConnection_(), p, request, sendPut_(), and undefined.
queryParamsEndAt()
function queryParamsEndAt (queryParams, indexValue, key)
References undefined.
queryParamsEndBefore()
function queryParamsEndBefore (queryParams, indexValue, key)
References KEY_INDEX, MIN_NAME, and queryParamsEndAt().
queryParamsGetNodeFilter()
function queryParamsGetNodeFilter (queryParams)
queryParamsGetQueryObject()
function queryParamsGetQueryObject (queryParams)
References obj, and PRIORITY_INDEX.
queryParamsLimitToFirst()
function queryParamsLimitToFirst (queryParams, newLimit)
queryParamsLimitToLast()
function queryParamsLimitToLast (queryParams, newLimit)
queryParamsOrderBy()
function queryParamsOrderBy (queryParams, index)
References index.
queryParamsStartAfter()
function queryParamsStartAfter (queryParams, indexValue, key)
References KEY_INDEX, MAX_NAME, and queryParamsStartAt().
queryParamsStartAt()
function queryParamsStartAt (queryParams, indexValue, key)
References undefined.
queryParamsToRestQueryStringParameters()
function queryParamsToRestQueryStringParameters (queryParams)
Returns a set of REST query string parameters representing this query.
Returns
query string parameters
References assert, KEY_INDEX, orderBy(), PRIORITY_INDEX, qs, stringify, and VALUE_INDEX.
removeListen_()
removeListen_ (pathString, queryId)
References listen, map, Path::toString(), and undefined.
repoInfoConnectionURL()
function repoInfoConnectionURL (repoInfo, type, params)
Returns the websocket URL for this repo
Parameters
repoInfo - RepoInfo object
type - of connection
params - list
Returns
The URL for this repo
References assert, each, LONG_POLLING, pairs, repoInfoNeedsQueryParam(), type, value, and WEBSOCKET.
repoInfoNeedsQueryParam()
function repoInfoNeedsQueryParam (repoInfo)
reportStats()
reportStats (stats)
References c, request, result, PersistentConnection::sendRequest(), stats, and status.
resolveDeferredValue()
function resolveDeferredValue (node, existingVal, serverValues)
References node, nodeFromJSON(), PRIORITY_INDEX, resolveDeferredLeafValue, resolveDeferredValue(), and value.
restoreState_()
restoreState_ ()
References i, of, request, PersistentConnection::sendGet_(), PersistentConnection::sendListen_(), sendOnDisconnect_(), sendPut_(), PersistentConnection::tryAppCheck(), and PersistentConnection::tryAuth().
resume()
resume (reason)
References isEmpty, log, reason, RECONNECT_MIN_DELAY, and scheduleConnect_().
scheduleConnect_()
scheduleConnect_ (timeout)
References assert, establishConnection_(), and timeout.
sendConnectStats_()
sendConnectStats_ ()
Sends client stats for first connection
References g, isMobileCordova, isNodeSdk, isReactNative, ServerActions::reportStats(), SDK_VERSION, and stats.
sendOnDisconnect_()
sendOnDisconnect_ (action, pathString, data, onComplete)
References d, data, p, request, response, and PersistentConnection::sendRequest().
sendPut_()
sendPut_ (index)
References index, message, request, and PersistentConnection::sendRequest().
sendUnlisten_()
sendUnlisten_ (pathString, queryId, queryObj, tag)
References p, req, and PersistentConnection::sendRequest().
setMaxNode()
function setMaxNode (val)
References MAX_NODE$1.
setMaxNode$1()
function setMaxNode$1 (val)
References MAX_NODE$2.
setNodeFromJSON()
function setNodeFromJSON (val)
References nodeFromJSON$1.
setSDKVersion()
function setSDKVersion (version)
SDK_VERSION should be set before any database instance is created
References SDK_VERSION, and version.
setWebSocketImpl()
function setWebSocketImpl (impl)
References impl, and WebSocketImpl.
shouldReconnect_()
shouldReconnect_ ()
References OnlineMonitor::getInstance(), and isEmpty.
sparseSnapshotTreeForEachChild()
function sparseSnapshotTreeForEachChild (sparseSnapshotTree, func)
Iterates through each immediate child and triggers the callback. Only seems to be used in tests.
Parameters
func - The function to invoke for each child.
References func.
sparseSnapshotTreeForEachTree()
function sparseSnapshotTreeForEachTree (sparseSnapshotTree, prefixPath, func)
Recursively iterates through all of the stored tree and calls the callback on each one.
Parameters
prefixPath - Path to look up node for.
func - The function to invoke for each tree.
References func, path, sparseSnapshotTreeForEachChild(), and sparseSnapshotTreeForEachTree().
sparseSnapshotTreeForget()
function sparseSnapshotTreeForget (sparseSnapshotTree, path)
Purge the data at path from the cache.
Parameters
path - Path to look up snapshot for.
Returns
True if this node should now be removed.
References path, pathGetFront(), pathIsEmpty(), pathPopFront(), PRIORITY_INDEX, sparseSnapshotTreeForget(), sparseSnapshotTreeRemember(), and value.
sparseSnapshotTreeRemember()
function sparseSnapshotTreeRemember (sparseSnapshotTree, path, data)
Stores the given node at the specified path. If there is already a node at a shallower path, it merges the new data into that snapshot node.
Parameters
path - Path to look up snapshot for.
data - The new data, or null.
References data, newSparseSnapshotTree(), path, pathGetFront(), pathIsEmpty(), pathPopFront(), and sparseSnapshotTreeRemember().
statsManagerGetCollection()
function statsManagerGetCollection (repoInfo)
References collections, and StatsCollection.
statsManagerGetOrCreateReporter()
function statsManagerGetOrCreateReporter (repoInfo, creatorFunction)
References reporters.
syncPointAddEventRegistration()
function syncPointAddEventRegistration (syncPoint, query, eventRegistration, writesCache, serverCache, serverCacheComplete)
Add an event callback for the specified query.
Parameters
query
eventRegistration
writesCache
serverCache - Complete server cache, if we have it.
serverCacheComplete
Returns
Events to raise.
References query, syncPointGetView(), viewAddEventRegistration(), and viewGetInitialEvents().
syncPointApplyOperation()
function syncPointApplyOperation (syncPoint, operation, writesCache, optCompleteServerCache)
References assert, of, operation, and viewApplyOperation().
syncPointGetCompleteServerCache()
function syncPointGetCompleteServerCache (syncPoint, path)
Parameters
path - The path to the desired complete snapshot
Returns
A complete cache, if it exists
References of, path, and viewGetCompleteServerCache().
syncPointGetCompleteView()
function syncPointGetCompleteView (syncPoint)
References of.
syncPointGetQueryViews()
function syncPointGetQueryViews (syncPoint)
References of, and result.
syncPointGetReferenceConstructor()
function syncPointGetReferenceConstructor ()
References assert, and referenceConstructor$1.
syncPointGetView()
function syncPointGetView (syncPoint, query, writesCache, serverCache, serverCacheComplete)
Get a view for the specified query.
Parameters
query - The query to return a view for
writesCache
serverCache
serverCacheComplete
Returns
Events to raise.
References ChildrenNode::EMPTY_NODE(), newViewCache(), query, View, writeTreeRefCalcCompleteEventCache(), and writeTreeRefCalcCompleteEventChildren().
syncPointHasCompleteView()
function syncPointHasCompleteView (syncPoint)
References syncPointGetCompleteView().
syncPointIsEmpty()
function syncPointIsEmpty (syncPoint)
syncPointRemoveEventRegistration()
function syncPointRemoveEventRegistration (syncPoint, query, eventRegistration, cancelError)
Remove event callback(s). Return cancelEvents if a cancelError is specified.
If query is the default query, we'll check all views for the specified eventRegistration. If eventRegistration is null, we'll remove all callbacks for the specified view(s).
Parameters
eventRegistration - If null, remove all callbacks.
cancelError - If a cancelError is provided, appropriate cancel events will be returned.
Returns
removed queries and any cancel events
References of, query, syncPointGetReferenceConstructor(), syncPointHasCompleteView(), viewIsEmpty(), and viewRemoveEventRegistration().
syncPointSetReferenceConstructor()
function syncPointSetReferenceConstructor (val)
References assert, and referenceConstructor$1.
syncPointViewExistsForQuery()
function syncPointViewExistsForQuery (syncPoint, query)
References query, and syncPointViewForQuery().
syncPointViewForQuery()
function syncPointViewForQuery (syncPoint, query)
References query, and syncPointGetCompleteView().
syncTreeAckUserWrite()
function syncTreeAckUserWrite (syncTree, writeId, revert = false)
Acknowledge a pending user write that was previously registered with applyUserOverwrite() or applyUserMerge().
Parameters
revert - True if the given write failed and needs to be reverted
Returns
Events to raise.
References each, newEmptyPath(), revert, syncTreeApplyOperationToSyncPoints_(), write, writeTreeGetWrite(), and writeTreeRemoveWrite().
syncTreeAddEventRegistration()
function syncTreeAddEventRegistration (syncTree, query, eventRegistration, skipSetupListener = false)
Add an event callback for the specified query.
Returns
Events to raise.
References assert, ChildrenNode::EMPTY_NODE(), newEmptyPath(), newRelativePath(), path, query, syncPointAddEventRegistration(), syncPointGetCompleteServerCache(), syncPointHasCompleteView(), syncPointViewExistsForQuery(), syncPointViewForQuery(), syncTreeGetNextQueryTag_(), syncTreeMakeQueryKey_(), syncTreeSetupListener_(), and writeTreeChildWrites().
syncTreeApplyListenComplete()
function syncTreeApplyListenComplete (syncTree, path)
Apply a listen complete for a query
Returns
Events to raise.
References newOperationSourceServer(), path, and syncTreeApplyOperationToSyncPoints_().
syncTreeApplyOperationDescendantsHelper_()
function syncTreeApplyOperationDescendantsHelper_ (operation, syncPointTree, serverCache, writesCache)
Recursive helper for applyOperationToSyncPoints_
References newEmptyPath(), operation, syncPointApplyOperation(), syncPointGetCompleteServerCache(), syncTreeApplyOperationDescendantsHelper_(), and writeTreeRefChild().
syncTreeApplyOperationHelper_()
function syncTreeApplyOperationHelper_ (operation, syncPointTree, serverCache, writesCache)
Recursive helper for applyOperationToSyncPoints_
References newEmptyPath(), operation, pathGetFront(), pathIsEmpty(), syncPointApplyOperation(), syncPointGetCompleteServerCache(), syncTreeApplyOperationDescendantsHelper_(), syncTreeApplyOperationHelper_(), and writeTreeRefChild().
syncTreeApplyOperationToSyncPoints_()
function syncTreeApplyOperationToSyncPoints_ (syncTree, operation)
A helper method that visits all descendant and ancestor SyncPoints, applying the operation.
NOTES:
Descendant SyncPoints will be visited first (since we raise events depth-first).
We call applyOperation() on each SyncPoint passing three things:
A version of the Operation that has been made relative to the SyncPoint location.
A WriteTreeRef of any writes we have cached at the SyncPoint location.
A snapshot Node with cached server data, if we have it.
We concatenate all of the events returned by each SyncPoint and return the result.
References newEmptyPath(), operation, syncTreeApplyOperationHelper_(), and writeTreeChildWrites().
syncTreeApplyServerMerge()
function syncTreeApplyServerMerge (syncTree, path, changedChildren)
Apply new server data to be merged in at the specified path.
Returns
Events to raise.
References ImmutableTree::fromObject(), newOperationSourceServer(), path, and syncTreeApplyOperationToSyncPoints_().
syncTreeApplyServerOverwrite()
function syncTreeApplyServerOverwrite (syncTree, path, newData)
Apply new server data for the specified path..
Returns
Events to raise.
References newOperationSourceServer(), path, and syncTreeApplyOperationToSyncPoints_().
syncTreeApplyTaggedListenComplete()
function syncTreeApplyTaggedListenComplete (syncTree, path, tag)
Apply a listen complete for a tagged query
Returns
Events to raise.
References newOperationSourceServerTaggedQuery(), newRelativePath(), path, r, syncTreeApplyTaggedOperation_(), syncTreeParseQueryKey_(), and syncTreeQueryKeyForTag_().
syncTreeApplyTaggedOperation_()
function syncTreeApplyTaggedOperation_ (syncTree, queryPath, operation)
A helper method to apply tagged operations
References assert, operation, syncPointApplyOperation(), and writeTreeChildWrites().
syncTreeApplyTaggedQueryMerge()
function syncTreeApplyTaggedQueryMerge (syncTree, path, changedChildren, tag)
Apply server data to be merged in for the specified tagged query.
Returns
Events to raise.
References ImmutableTree::fromObject(), newOperationSourceServerTaggedQuery(), newRelativePath(), path, r, syncTreeApplyTaggedOperation_(), syncTreeParseQueryKey_(), and syncTreeQueryKeyForTag_().
syncTreeApplyTaggedQueryOverwrite()
function syncTreeApplyTaggedQueryOverwrite (syncTree, path, snap, tag)
Apply new server data for the specified tagged query.
Returns
Events to raise.
References newOperationSourceServerTaggedQuery(), newRelativePath(), path, r, syncTreeApplyTaggedOperation_(), syncTreeParseQueryKey_(), and syncTreeQueryKeyForTag_().
syncTreeApplyUserMerge()
function syncTreeApplyUserMerge (syncTree, path, changedChildren, writeId)
Apply the data from a user-generated update() call
Returns
Events to raise.
References ImmutableTree::fromObject(), newOperationSourceUser(), path, syncTreeApplyOperationToSyncPoints_(), and writeTreeAddMerge().
syncTreeApplyUserOverwrite()
function syncTreeApplyUserOverwrite (syncTree, path, newData, writeId, visible)
Apply the data changes for a user-generated set() or transaction() call.
Returns
Events to raise.
References newOperationSourceUser(), path, syncTreeApplyOperationToSyncPoints_(), visible, and writeTreeAddOverwrite().
syncTreeCalcCompleteEventCache()
function syncTreeCalcCompleteEventCache (syncTree, path, writeIdsToExclude)
Returns a complete cache, if we have one, of the data at a particular path. If the location does not have a listener above it, we will get a false "null". This shouldn't be a problem because transactions will always have a listener above, and atomic operations would correctly show a jitter of <increment value> -> <incremented total> as the write is applied locally and then acknowledged at the server.
Note: this method will include hidden writes from transaction with applyLocally set to false.
Parameters
path - The path to the data we want
writeIdsToExclude - A specific set to be excluded
References newRelativePath(), path, syncPointGetCompleteServerCache(), and writeTreeCalcCompleteEventCache().
syncTreeCollectDistinctViewsForSubTree_()
function syncTreeCollectDistinctViewsForSubTree_ (subtree)
This collapses multiple unfiltered views into a single view, since we only need a single listener for them.
References each, syncPointGetCompleteView(), syncPointGetQueryViews(), and syncPointHasCompleteView().
syncTreeCreateListenerForView_()
function syncTreeCreateListenerForView_ (syncTree, view)
References ChildrenNode::EMPTY_NODE(), error, errorForServerCode(), query, status, syncTreeApplyListenComplete(), syncTreeApplyTaggedListenComplete(), syncTreeRemoveEventRegistration(), syncTreeTagForQuery(), and viewGetServerCache().
syncTreeGetNextQueryTag_()
function syncTreeGetNextQueryTag_ ()
Static accessor for query tags.
References syncTreeNextQueryTag_.
syncTreeGetReferenceConstructor()
function syncTreeGetReferenceConstructor ()
References assert, and referenceConstructor.
syncTreeGetServerValue()
function syncTreeGetServerValue (syncTree, query)
References ChildrenNode::EMPTY_NODE(), newEmptyPath(), newRelativePath(), path, query, syncPointGetCompleteServerCache(), syncPointGetView(), viewGetCompleteNode(), and writeTreeChildWrites().
syncTreeMakeQueryKey_()
function syncTreeMakeQueryKey_ (query)
Given a query, computes a "queryKey" suitable for use in our queryToTagMap_.
References query.
syncTreeParseQueryKey_()
function syncTreeParseQueryKey_ (queryKey)
Given a queryKey (created by makeQueryKey), parse it back into a path and queryId.
References assert, and path.
syncTreeQueryForListening_()
function syncTreeQueryForListening_ (query)
Normalizes a query to a query we send the server for listening
Returns
The normalized query
References query, and syncTreeGetReferenceConstructor().
syncTreeQueryKeyForTag_()
function syncTreeQueryKeyForTag_ (syncTree, tag)
Return the query associated with the given tag, if we have one Here is the caller graph for this function:
syncTreeRemoveEventRegistration()
function syncTreeRemoveEventRegistration (syncTree, query, eventRegistration, cancelError, skipListenerDedup = false)
Remove event callback(s).
If query is the default query, we'll check all queries for the specified eventRegistration. If eventRegistration is null, we'll remove all callbacks for the specified query/queries.
Parameters
eventRegistration - If null, all callbacks are removed.
cancelError - If a cancelError is provided, appropriate cancel events will be returned.
skipListenerDedup - When performing a get(), we don't add any new listeners, so no deduping needs to take place. This flag allows toggling of that behavior
Returns
Cancel events, if cancelError was provided.
We may have just removed one of many listeners and can short-circuit this whole process We may also not have removed a default listener, in which case all of the descendant listeners should already be properly set up.
References i, path, query, syncPointHasCompleteView(), syncPointIsEmpty(), syncPointRemoveEventRegistration(), syncPointViewExistsForQuery(), syncTreeCollectDistinctViewsForSubTree_(), syncTreeCreateListenerForView_(), syncTreeMakeQueryKey_(), syncTreeQueryForListening_(), syncTreeRemoveTags_(), and syncTreeTagForQuery().
syncTreeRemoveTags_()
function syncTreeRemoveTags_ (syncTree, queries)
References j, and syncTreeMakeQueryKey_().
syncTreeSetReferenceConstructor()
function syncTreeSetReferenceConstructor (val)
References assert, and referenceConstructor.
syncTreeSetupListener_()
function syncTreeSetupListener_ (syncTree, query, view)
For a given new listen, manage the de-duplication of outstanding subscriptions.
Returns
This method can return events to support synchronous data sources
References assert, each, i, map, path, pathIsEmpty(), query, syncPointGetCompleteView(), syncPointGetQueryViews(), syncPointHasCompleteView(), syncTreeCreateListenerForView_(), syncTreeQueryForListening_(), and syncTreeTagForQuery().
syncTreeTagForQuery()
function syncTreeTagForQuery (syncTree, query)
Return the tag associated with the given query.
References query, and syncTreeMakeQueryKey_().
treeForEachAncestor()
function treeForEachAncestor (tree, action, includeSelf)
Calls action on each ancestor node.
Parameters
action - Action to be called on each parent; return true to abort.
includeSelf - Whether to call action on this node as well.
Returns
true if the action callback returned true.
References node.
treeForEachChild()
function treeForEachChild (tree, action)
Calls action for each child of this tree node.
Parameters
action - Action to be called for each child.
References each.
treeForEachDescendant()
function treeForEachDescendant (tree, action, includeSelf, childrenFirst)
Does a depth-first traversal of this node's descendants, calling action for each one.
Parameters
action - Action to be called for each child.
includeSelf - Whether to call action on this node as well. Defaults to false.
childrenFirst - Whether to call action on children before calling it on parent.
References treeForEachChild(), and treeForEachDescendant().
treeGetPath()
function treeGetPath (tree)
Returns
The path of this tree node, as a Path.
References treeGetPath().
treeGetValue()
function treeGetValue (tree)
Returns the data associated with this tree node.
Returns
The data or null if no data exists.
treeHasChildren()
function treeHasChildren (tree)
Returns
Whether the tree has any children.
treeIsEmpty()
function treeIsEmpty (tree)
Returns
Whether the tree is empty (no value or children).
References treeGetValue(), treeHasChildren(), and undefined.
treeSetValue()
function treeSetValue (tree, value)
Sets data to this tree node.
Parameters
value - Value to set.
References treeUpdateParents(), and value.
treeSubTree()
function treeSubTree (tree, pathObj)
Returns a sub-Tree for the given path.
Parameters
pathObj - Path to look up.
Returns
Tree for path.
References next(), path, pathGetFront(), pathPopFront(), and safeGet.
treeUpdateChild()
function treeUpdateChild (tree, childName, child)
Adds or removes the passed child to this tree node, depending on whether it's empty.
Parameters
childName - The name of the child to update.
child - The child to update.
References contains, treeIsEmpty(), and treeUpdateParents().
treeUpdateParents()
function treeUpdateParents (tree)
Adds or removes this child from its parent based on whether it's empty or not.
References treeUpdateChild().
unlisten()
unlisten (query, tag)
@inheritDoc
References assert, listen, query, removeListen_(), and sendUnlisten_().
validationPathCheckValid()
function validationPathCheckValid (validationPath)
References MAX_PATH_DEPTH, MAX_PATH_LENGTH_BYTES, and validationPathToErrorString().
validationPathPop()
function validationPathPop (validationPath)
References last, and stringLength.
validationPathPush()
function validationPathPush (validationPath, child)
References stringLength, and validationPathCheckValid().
validationPathToErrorString()
function validationPathToErrorString (validationPath)
String for use in error messages - uses '.' notation for path. Here is the caller graph for this function:
viewAddEventRegistration()
function viewAddEventRegistration (view, eventRegistration)
viewApplyOperation()
function viewApplyOperation (view, operation, writesCache, completeServerCache)
Applies the given Operation, updates our cache, and returns the appropriate events.
References assert, operation, OperationType, result, viewCacheGetCompleteEventSnap(), viewCacheGetCompleteServerSnap(), viewGenerateEventsForChanges_(), viewProcessorApplyOperation(), and viewProcessorAssertIndexed().
viewCacheGetCompleteEventSnap()
function viewCacheGetCompleteEventSnap (viewCache)
viewCacheGetCompleteServerSnap()
function viewCacheGetCompleteServerSnap (viewCache)
viewCacheUpdateEventSnap()
function viewCacheUpdateEventSnap (viewCache, eventSnap, complete, filtered)
References newViewCache().
viewCacheUpdateServerSnap()
function viewCacheUpdateServerSnap (viewCache, serverSnap, complete, filtered)
References newViewCache().
viewGenerateEventsForChanges_()
function viewGenerateEventsForChanges_ (view, changes, eventCache, eventRegistration)
References eventGeneratorGenerateEventsForChanges().
viewGetCompleteNode()
function viewGetCompleteNode (view)
References viewCacheGetCompleteEventSnap().
viewGetCompleteServerCache()
function viewGetCompleteServerCache (view, path)
References isEmpty, path, pathGetFront(), pathIsEmpty(), and viewCacheGetCompleteServerSnap().
viewGetInitialEvents()
function viewGetInitialEvents (view, registration)
References changeChildAdded(), changeValue(), PRIORITY_INDEX, and viewGenerateEventsForChanges_().
viewGetServerCache()
function viewGetServerCache (view)
viewIsEmpty()
function viewIsEmpty (view)
viewProcessorAckUserWrite()
function viewProcessorAckUserWrite (viewProcessor, viewCache, ackPath, affectedTree, writesCache, completeCache, accumulator)
References KEY_INDEX, name, node, pathChild(), pathIsEmpty(), value, viewProcessorApplyServerMerge(), viewProcessorApplyServerOverwrite(), and writeTreeRefShadowingWrite().
viewProcessorApplyMerge()
function viewProcessorApplyMerge (viewProcessor, node, merge)
References merge, and node.
viewProcessorApplyOperation()
function viewProcessorApplyOperation (viewProcessor, oldViewCache, operation, writesCache, completeCache)
References assert, assertionError, merge, newViewCache(), operation, OperationType, pathIsEmpty(), viewProcessorAckUserWrite(), viewProcessorApplyServerMerge(), viewProcessorApplyServerOverwrite(), viewProcessorApplyUserMerge(), viewProcessorApplyUserOverwrite(), viewProcessorListenComplete(), viewProcessorMaybeAddValueEvent(), and viewProcessorRevertUserWrite().
viewProcessorApplyServerMerge()
function viewProcessorApplyServerMerge (viewProcessor, viewCache, path, changedChildren, writesCache, serverCache, filterServerNode, accumulator)
References path, pathIsEmpty(), ImmutableTree::setTree(), viewProcessorApplyMerge(), and viewProcessorApplyServerOverwrite().
viewProcessorApplyServerOverwrite()
function viewProcessorApplyServerOverwrite (viewProcessor, oldViewCache, changePath, changedSnap, writesCache, completeCache, filterServerNode, accumulator)
References newViewCache(), NO_COMPLETE_CHILD_SOURCE, pathGetFront(), pathGetLength(), pathIsEmpty(), pathPopFront(), source, viewCacheUpdateServerSnap(), and viewProcessorGenerateEventCacheAfterServerEvent().
viewProcessorApplyUserMerge()
function viewProcessorApplyUserMerge (viewProcessor, viewCache, path, changedChildren, writesCache, serverCache, accumulator)
References path, pathChild(), pathGetFront(), viewProcessorApplyUserOverwrite(), and viewProcessorCacheHasChild().
viewProcessorApplyUserOverwrite()
function viewProcessorApplyUserOverwrite (viewProcessor, oldViewCache, changePath, changedSnap, writesCache, completeCache, accumulator)
References ChildrenNode::EMPTY_NODE(), isEmpty, newViewCache(), pathGetBack(), pathGetFront(), pathIsEmpty(), pathParent(), pathPopFront(), source, and viewCacheUpdateEventSnap().
viewProcessorAssertIndexed()
function viewProcessorAssertIndexed (viewProcessor, viewCache)
References assert.
viewProcessorCacheHasChild()
function viewProcessorCacheHasChild (viewCache, childKey)
viewProcessorGenerateEventCacheAfterServerEvent()
function viewProcessorGenerateEventCacheAfterServerEvent (viewProcessor, viewCache, changePath, writesCache, source, accumulator)
References assert, ChildrenNode::EMPTY_NODE(), pathGetFront(), pathGetLength(), pathIsEmpty(), pathPopFront(), source, viewCacheGetCompleteServerSnap(), viewCacheUpdateEventSnap(), writeTreeRefCalcCompleteChild(), writeTreeRefCalcCompleteEventCache(), writeTreeRefCalcCompleteEventChildren(), writeTreeRefCalcEventCacheAfterServerOverwrite(), and writeTreeRefShadowingWrite().
viewProcessorListenComplete()
function viewProcessorListenComplete (viewProcessor, viewCache, path, writesCache, accumulator)
References newViewCache(), NO_COMPLETE_CHILD_SOURCE, path, pathIsEmpty(), viewCacheUpdateServerSnap(), and viewProcessorGenerateEventCacheAfterServerEvent().
viewProcessorMaybeAddValueEvent()
function viewProcessorMaybeAddValueEvent (oldViewCache, newViewCache, accumulator)
References changeValue(), newViewCache(), and viewCacheGetCompleteEventSnap().
viewProcessorRevertUserWrite()
function viewProcessorRevertUserWrite (viewProcessor, viewCache, path, writesCache, completeServerCache, accumulator)
References assert, ChildrenNode::EMPTY_NODE(), newEmptyPath(), path, pathGetFront(), pathIsEmpty(), pathPopFront(), source, viewCacheGetCompleteServerSnap(), viewCacheUpdateEventSnap(), writeTreeRefCalcCompleteChild(), writeTreeRefCalcCompleteEventCache(), writeTreeRefCalcCompleteEventChildren(), and writeTreeRefShadowingWrite().
viewRemoveEventRegistration()
function viewRemoveEventRegistration (view, eventRegistration, cancelError)
Parameters
eventRegistration - If null, remove all callbacks.
cancelError - If a cancelError is provided, appropriate cancel events will be returned.
Returns
Cancel events, if cancelError was provided.
References assert, i, and path.
writeTreeAddMerge()
function writeTreeAddMerge (writeTree, path, changedChildren, writeId)
Record a new merge from user code.
References assert, compoundWriteAddWrites(), path, and visible.
writeTreeAddOverwrite()
function writeTreeAddOverwrite (writeTree, path, snap, writeId, visible)
Record a new overwrite from user code.
Parameters
visible - This is set to false by some transactions. It should be excluded from event caches
References assert, compoundWriteAddWrite(), path, undefined, and visible.
writeTreeCalcCompleteChild()
function writeTreeCalcCompleteChild (writeTree, treePath, childKey, existingServerSnap)
Returns a complete child for a given server snap after applying all user writes or null if there is no complete child for this ChildKey.
References compoundWriteApply(), compoundWriteChildCompoundWrite(), compoundWriteGetCompleteNode(), path, and pathChild().
writeTreeCalcCompleteEventCache()
function writeTreeCalcCompleteEventCache (writeTree, treePath, completeServerCache, writeIdsToExclude, includeHiddenWrites)
Given optional, underlying server data, and an optional set of constraints (exclude some sets, include hidden writes), attempt to calculate a complete snapshot for the given path
Parameters
writeIdsToExclude - An optional set to be excluded
includeHiddenWrites - Defaults to false, whether or not to layer on writes with visible set to false
References compoundWriteApply(), compoundWriteChildCompoundWrite(), compoundWriteGetCompleteNode(), compoundWriteHasCompleteWrite(), compoundWriteIsEmpty(), ChildrenNode::EMPTY_NODE(), filter, merge, newEmptyPath(), pathContains(), write, and writeTreeLayerTree_().
writeTreeCalcCompleteEventChildren()
function writeTreeCalcCompleteEventChildren (writeTree, treePath, completeServerChildren)
With optional, underlying server data, attempt to return a children node of children that we have complete data for. Used when creating new views, to pre-fill their complete event children snapshot.
References compoundWriteApply(), compoundWriteChildCompoundWrite(), compoundWriteGetCompleteChildren(), compoundWriteGetCompleteNode(), ChildrenNode::EMPTY_NODE(), merge, node, and PRIORITY_INDEX.
writeTreeCalcEventCacheAfterServerOverwrite()
function writeTreeCalcEventCacheAfterServerOverwrite (writeTree, treePath, childPath, existingEventSnap, existingServerSnap)
Given that the underlying server data has updated, determine what, if anything, needs to be applied to the event cache.
Possibilities:
No writes are shadowing. Events should be raised, the snap to be applied comes from the server data
Some write is completely shadowing. No events to be raised
Is partially shadowed. Events
Either existingEventSnap or existingServerSnap must exist
References assert, compoundWriteApply(), compoundWriteChildCompoundWrite(), compoundWriteHasCompleteWrite(), compoundWriteIsEmpty(), path, and pathChild().
writeTreeCalcIndexedSlice()
function writeTreeCalcIndexedSlice (writeTree, treePath, completeServerData, startPost, count, reverse, index)
This method is used when processing child remove events on a query. If we can, we pull in children that were outside the window, but may now be in the window.
References compoundWriteApply(), compoundWriteChildCompoundWrite(), compoundWriteGetCompleteNode(), count, index, merge, newEmptyPath(), next(), and reverse.
writeTreeChildWrites()
function writeTreeChildWrites (writeTree, path)
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Create a new WriteTreeRef for the given path. For use with a new sync point at the given path.
References newWriteTreeRef(), and path.
writeTreeDefaultFilter_()
function writeTreeDefaultFilter_ (write)
The default filter used when constructing the tree. Keep everything that's visible.
References write.
writeTreeGetWrite()
function writeTreeGetWrite (writeTree, writeId)
References i.
writeTreeLayerTree_()
function writeTreeLayerTree_ (writes, filter, treeRoot)
Static method. Given an array of WriteRecords, a filter for which ones to include, and a path, construct the tree of event data at that path.
References assertionError, compoundWriteAddWrite(), compoundWriteAddWrites(), else, CompoundWrite::empty(), filter, i, newEmptyPath(), newRelativePath(), pathContains(), pathGetFront(), pathIsEmpty(), pathPopFront(), safeGet, and write.
writeTreeRecordContainsPath_()
function writeTreeRecordContainsPath_ (writeRecord, path)
References path, pathChild(), and pathContains().
writeTreeRefCalcCompleteChild()
function writeTreeRefCalcCompleteChild (writeTreeRef, childKey, existingServerCache)
Returns a complete child for a given server snap after applying all user writes or null if there is no complete child for this ChildKey.
References writeTreeCalcCompleteChild().
writeTreeRefCalcCompleteEventCache()
function writeTreeRefCalcCompleteEventCache (writeTreeRef, completeServerCache, writeIdsToExclude, includeHiddenWrites)
If possible, returns a complete event cache, using the underlying server data if possible. In addition, can be used to get a cache that includes hidden writes, and excludes arbitrary writes. Note that customizing the returned node can lead to a more expensive calculation.
Parameters
writeIdsToExclude - Optional writes to exclude.
includeHiddenWrites - Defaults to false, whether or not to layer on writes with visible set to false
References writeTreeCalcCompleteEventCache().
writeTreeRefCalcCompleteEventChildren()
function writeTreeRefCalcCompleteEventChildren (writeTreeRef, completeServerChildren)
If possible, returns a children node containing all of the complete children we have data for. The returned data is a mix of the given server data and write data.
References writeTreeCalcCompleteEventChildren().
writeTreeRefCalcEventCacheAfterServerOverwrite()
function writeTreeRefCalcEventCacheAfterServerOverwrite (writeTreeRef, path, existingEventSnap, existingServerSnap)
Given that either the underlying server data has updated or the outstanding writes have updated, determine what, if anything, needs to be applied to the event cache.
Possibilities:
No writes are shadowing. Events should be raised, the snap to be applied comes from the server data
Some write is completely shadowing. No events to be raised
Is partially shadowed. Events should be raised
Either existingEventSnap or existingServerSnap must exist, this is validated via an assert
References path, and writeTreeCalcEventCacheAfterServerOverwrite().
writeTreeRefCalcIndexedSlice()
function writeTreeRefCalcIndexedSlice (writeTreeRef, completeServerData, startPost, count, reverse, index)
This method is used when processing child remove events on a query. If we can, we pull in children that were outside the window, but may now be in the window
References count, index, reverse, and writeTreeCalcIndexedSlice().
writeTreeRefChild()
function writeTreeRefChild (writeTreeRef, childName)
Return a WriteTreeRef for a child.
References newWriteTreeRef(), and pathChild().
writeTreeRefShadowingWrite()
function writeTreeRefShadowingWrite (writeTreeRef, path)
Returns a node if there is a complete overwrite for this path. More specifically, if there is a write at a higher path, this will return the child of that write relative to the write and this path. Returns null if there is no write at this path.
References path, pathChild(), and writeTreeShadowingWrite().
writeTreeRemoveWrite()
function writeTreeRemoveWrite (writeTree, writeId)
Remove a write (either an overwrite or merge) that has been successfully acknowledge by the server. Recalculates the tree if necessary. We return true if it may have been visible, meaning views need to reevaluate.
Returns
true if the write may have been visible (meaning we'll need to reevaluate / raise events as a result).
References assert, compoundWriteRemoveWrite(), each, i, pathChild(), pathContains(), s, writeTreeRecordContainsPath_(), and writeTreeResetTree_().
writeTreeResetTree_()
function writeTreeResetTree_ (writeTree)
Re-layer the writes and merges into a tree so we can efficiently calculate event snapshots
References newEmptyPath(), writeTreeDefaultFilter_(), and writeTreeLayerTree_().
writeTreeShadowingWrite()
function writeTreeShadowingWrite (writeTree, path)
Returns a node if there is a complete overwrite for this path. More specifically, if there is a write at a higher path, this will return the child of that write relative to the write and this path. Returns null if there is no write at this path.
References compoundWriteGetCompleteNode(), and path.
Variable Documentation
__childrenNodeConstructor
LeafNode __childrenNodeConstructor = ChildrenNode
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
__EMPTY_NODE
KeyIndex __EMPTY_NODE = ChildrenNode.EMPTY_NODE
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Reference Extensions
_defaultIndexMap
let _defaultIndexMap
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
APP_CHECK_TOKEN_PARAM
const APP_CHECK_TOKEN_PARAM = 'ac'
APPLICATION_ID_PARAM
const APPLICATION_ID_PARAM = 'p'
beingCrawled
const beingCrawled
Initial value:
= function () {
    const userAgent = (typeof window === 'object' &&
        window['navigator'] &&
        window['navigator']['userAgent']) ||
        '';
    
    
    
    
    return (userAgent.search(/googlebot|google webmaster tools|bingbot|yahoo! slurp|baiduspider|yandexbot|duckduckbot/i) >= 0);
}
Returns
{boolean} true if we think we're currently being crawled.
BLACK
LLRBNode BLACK = false
buildChildSet
const buildChildSet
Takes a list of child nodes and constructs a SortedSet using the given comparison function
Uses the algorithm described in the paper linked here: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.46.1458
Parameters
childList - Unsorted list of children
cmp - The comparison method to be used
keyFn - An optional function to extract K from a node wrapper, if K's type is not NamedNode
mapSortFn - An optional override for comparator used by the generated sorted map
buildLogMessage_
const buildLogMessage_
Initial value:
= function (...varArgs) {
    let message = '';
    for (let i = 0; i < varArgs.length; i++) {
        const arg = varArgs[i];
        if (Array.isArray(arg) ||
            (arg &&
                typeof arg === 'object' &&
                
                typeof arg.length === 'number')) {
            message += buildLogMessage_.apply(null, arg);
        }
        else if (typeof arg === 'object') {
            message += stringify(arg);
        }
        else {
            message += arg;
        }
        message += ' ';
    }
    return message;
}
BYTES_RECEIVED_HEALTHY_OVERRIDE
const BYTES_RECEIVED_HEALTHY_OVERRIDE = 100 * 1024
BYTES_SENT_HEALTHY_OVERRIDE
const BYTES_SENT_HEALTHY_OVERRIDE = 10 * 1024
collections
const collections = {}
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
CONTROL_ERROR
const CONTROL_ERROR = 'e'
CONTROL_PONG
const CONTROL_PONG = 'o'
CONTROL_RESET
const CONTROL_RESET = 'r'
CONTROL_SHUTDOWN
const CONTROL_SHUTDOWN = 's'
createStoragefor
const createStoragefor
Initial value:
= function (domStorageName) {
    try {
        
        
        if (typeof window !== 'undefined' &&
            typeof window[domStorageName] !== 'undefined') {
            
            const domStorage = window[domStorageName];
            domStorage.setItem('firebase:sentinel', 'cache');
            domStorage.removeItem('firebase:sentinel');
            return new DOMStorageWrapper(domStorage);
        }
    }
    catch (e) { }
    
    
    return new MemoryStorage();
}
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Helper to create a DOMStorageWrapper or else fall back to MemoryStorage. TODO: Once MemoryStorage and DOMStorageWrapper have a shared interface this method annotation should change to reflect this type
Parameters
domStorageName - Name of the underlying storage object (e.g. 'localStorage' or 'sessionStorage').
Returns
Turning off type information until a common interface is defined.
DELAY_BEFORE_SENDING_EXTRA_REQUESTS
const DELAY_BEFORE_SENDING_EXTRA_REQUESTS = 5000
doubleToIEEE754String
const doubleToIEEE754String
Borrowed from http://hg.secondlife.com/llsd/src/tip/js/typedarray.js (MIT License) I made one modification at the end and removed the NaN / Infinity handling (since it seemed broken [caused an overflow] and we don't need it). See MJL comments.
Parameters
v - A double
EMPTY_NODE
let EMPTY_NODE = new LLRBEmptyNode()
Always use the same empty node, to reduce memory.
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
EmptyChildren
const EmptyChildren
Initial value:
= () => {
    if (!emptyChildrenSingleton) {
        emptyChildrenSingleton = new SortedMap(stringCompare);
    }
    return emptyChildrenSingleton;
}
Singleton empty children collection.
emptyChildrenSingleton
let emptyChildrenSingleton
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
enableLogging$1
const enableLogging$1
Initial value:
= function (logger_, persistent) {
    assert(!persistent || logger_ === true || logger_ === false, "Can't turn on custom loggers persistently.");
    if (logger_ === true) {
        logClient.logLevel = LogLevel.VERBOSE;
        logger = logClient.log.bind(logClient);
        if (persistent) {
            SessionStorage.set('logging_enabled', true);
        }
    }
    else if (typeof logger_ === 'function') {
        logger = logger_;
    }
    else {
        logger = null;
        SessionStorage.remove('logging_enabled');
    }
}
The implementation of Firebase.enableLogging (defined here to break dependencies)
Parameters
logger_ - A flag to turn on logging, or a custom logger
persistent - Whether or not to persist logging settings across refreshes
END_TRANSMISSION
const END_TRANSMISSION = 'n'
error
const error
Initial value:
= function (...varArgs) {
    const message = 'FIREBASE INTERNAL ERROR: ' + buildLogMessage_(...varArgs);
    logClient.error(message);
}
exceptionGuard
const exceptionGuard
Initial value:
= function (fn) {
    try {
        fn();
    }
    catch (e) {
        
        setTimeout(() => {
            
            
            
            
            const stack = e.stack || '';
            warn('Exception was thrown by user callback.', stack);
            throw e;
        }, Math.floor(0));
    }
}
Helper to run some code but catch any exceptions and re-throw them later. Useful for preventing user callbacks from breaking internal code.
Re-throwing the exception from a setTimeout is a little evil, but it's very convenient (we don't have to try to figure out when is a safe point to re-throw it), and the behavior seems reasonable:
If you aren't pausing on exceptions, you get an error in the console with the correct stack trace.
If you're pausing on all exceptions, the debugger will pause on your exception and then again when we rethrow it.
If you're only pausing on uncaught exceptions, the debugger will only pause on us re-throwing it.
Parameters
fn - The code to guard.
executeWhenDOMReady
const executeWhenDOMReady
fallbackObject
const fallbackObject = {}
fatal
const fatal
Initial value:
= function (...varArgs) {
    const message = FIREBASE FATAL ERROR: ${buildLogMessage_(...varArgs)};
    logClient.error(message);
    throw new Error(message);
}
FIREBASE_LONGPOLL_CALLBACK_ID_PARAM
const FIREBASE_LONGPOLL_CALLBACK_ID_PARAM = 'cb'
FIREBASE_LONGPOLL_CLOSE_COMMAND
const FIREBASE_LONGPOLL_CLOSE_COMMAND = 'close'
FIREBASE_LONGPOLL_COMMAND_CB_NAME
const FIREBASE_LONGPOLL_COMMAND_CB_NAME = 'pLPCommand'
FIREBASE_LONGPOLL_DATA_CB_NAME
const FIREBASE_LONGPOLL_DATA_CB_NAME = 'pRTLPCB'
FIREBASE_LONGPOLL_DATA_PARAM
const FIREBASE_LONGPOLL_DATA_PARAM = 'd'
FIREBASE_LONGPOLL_DISCONN_FRAME_REQUEST_PARAM
const FIREBASE_LONGPOLL_DISCONN_FRAME_REQUEST_PARAM = 'dframe'
FIREBASE_LONGPOLL_ID_PARAM
const FIREBASE_LONGPOLL_ID_PARAM = 'id'
FIREBASE_LONGPOLL_PW_PARAM
const FIREBASE_LONGPOLL_PW_PARAM = 'pw'
FIREBASE_LONGPOLL_SEGMENT_NUM_PARAM
const FIREBASE_LONGPOLL_SEGMENT_NUM_PARAM = 'seg'
FIREBASE_LONGPOLL_SEGMENTS_IN_PACKET
const FIREBASE_LONGPOLL_SEGMENTS_IN_PACKET = 'ts'
FIREBASE_LONGPOLL_SERIAL_PARAM
const FIREBASE_LONGPOLL_SERIAL_PARAM = 'ser'
FIREBASE_LONGPOLL_START_PARAM
const FIREBASE_LONGPOLL_START_PARAM = 'start'
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
FIRST_STATS_MAX_TIME
const FIRST_STATS_MAX_TIME = 30 * 1000
FIRST_STATS_MIN_TIME
const FIRST_STATS_MIN_TIME = 10 * 1000
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
firstLog_
let firstLog_ = true
Flag to check for log availability on first log message
FORGE_DOMAIN_RE
const FORGE_DOMAIN_RE = /(console\.firebase|firebase-console-\w+\.corp|firebase\.corp)\.google\.com/
FORGE_REF
const FORGE_REF = 'f'
generateWithValues
const generateWithValues
Initial value:
= function (values) {
    values = values || {};
    values['timestamp'] = values['timestamp'] || new Date().getTime();
    return values;
}
Generate placeholders for deferred values.
globalTransportInitialized_
TransportManager globalTransportInitialized_ = false
healthyTimeout
WebSocketConnection healthyTimeout = 30000
Time to wait for the connection te become healthy before giving up.
import
import { stringify, jsonEval, contains, assert, isNodeSdk, stringToByteArray, Sha1, base64, deepCopy, base64Encode, isMobileCordova, stringLength, Deferred, safeGet, isAdmin, isValidFormat, isEmpty, isReactNative, assertionError, map, querystring, errorPrefix, getModularInstance, getDefaultEmulatorHostnameAndPort, createMockUserToken } from '@firebase/util'
INTEGER_32_MAX
const INTEGER_32_MAX = 2147483647
For use in keys, the maximum possible 32-bit integer.
INTEGER_32_MIN
const INTEGER_32_MIN = -2147483648
For use in keys, the minimum possible 32-bit integer.
INTEGER_REGEXP_
ChildrenNode INTEGER_REGEXP_ = new RegExp('^-?(0*)\\d{1,10}$')
Used to test for integer-looking strings
INVALID_KEY_REGEX_
const INVALID_KEY_REGEX_ = /[\[\].#$\/\u0000-\u001F\u007F]/
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. True for invalid Firebase keys
INVALID_PATH_REGEX_
const INVALID_PATH_REGEX_ = /[\[\].#$\u0000-\u001F\u007F]/
True for invalid Firebase paths. Allows '/' in paths.
INVALID_TOKEN_THRESHOLD
const INVALID_TOKEN_THRESHOLD = 3
isChromeExtensionContentScript
const isChromeExtensionContentScript
Initial value:
= function () {
    return !!(typeof window === 'object' &&
        window['chrome'] &&
        window['chrome']['extension'] &&
        !/^chrome/.test(window.location.href));
}
Used to detect if we're in a Chrome content script (which executes in an isolated environment where long-polling doesn't work).
isInvalidJSONNumber
const isInvalidJSONNumber
Initial value:
= function (data) {
    return (typeof data === 'number' &&
        (data !== data ||
            data === Number.POSITIVE_INFINITY ||
            data === Number.NEGATIVE_INFINITY));
}
Returns true if data is NaN, or +/- Infinity.
isValidKey
const isValidKey
Initial value:
= function (key) {
    return (typeof key === 'string' && key.length !== 0 && !INVALID_KEY_REGEX_.test(key));
}
isValidPathString
const isValidPathString
Initial value:
= function (pathString) {
    return (typeof pathString === 'string' &&
        pathString.length !== 0 &&
        !INVALID_PATH_REGEX_.test(pathString));
}
isWindowsStoreApp
const isWindowsStoreApp
Initial value:
= function () {
    
    return typeof Windows === 'object' && typeof Windows.UI === 'object';
}
Used to detect if we're in a Windows 8 Store app.
KEEPALIVE_REQUEST_INTERVAL
const KEEPALIVE_REQUEST_INTERVAL = 25000
Keepalive period send a fresh request at minimum every 25 seconds. Opera has a maximum request length of 30 seconds that we can't exceed.
KEY_INDEX
const KEY_INDEX = new KeyIndex()
LAST_SESSION_PARAM
const LAST_SESSION_PARAM = 'ls'
log
const log
Initial value:
= function (...varArgs) {
    if (firstLog_ === true) {
        firstLog_ = false;
        if (logger === null && SessionStorage.get('logging_enabled') === true) {
            enableLogging$1(true);
        }
    }
    if (logger) {
        const message = buildLogMessage_.apply(null, varArgs);
        logger(message);
    }
}
LOG_2
const LOG_2 = Math.log(2)
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
logClient
const logClient = new Logger('@firebase/database')
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
logger
let logger = null
Use this for all debug messages in Firebase.
logWrapper
const logWrapper
Initial value:
= function (prefix) {
    return function (...varArgs) {
        log(prefix, ...varArgs);
    };
}
LONG_POLLING
const LONG_POLLING = 'long_polling'
LP_CONNECT_TIMEOUT
const LP_CONNECT_TIMEOUT = 30000
How long to wait before aborting a long-polling connection attempt.
LUIDGenerator
const LUIDGenerator
Initial value:
= (function () {
    let id = 1;
    return function () {
        return id++;
    };
})()
Returns a locally-unique ID (generated by just incrementing up from 0 each time its called).
MAX_LEAF_SIZE_
const MAX_LEAF_SIZE_ = 10 * 1024 * 1024
Maximum number of characters to allow in leaf value
MAX_NAME
const MAX_NAME = '[MAX_NAME]'
Maximum key name. Invalid for actual data, used as a marker to sort above any valid names
MAX_NODE
const MAX_NODE = new MaxNode()
Marker that will sort higher than any other snapshot.
MAX_NODE$1
let MAX_NODE$1
MAX_NODE$2
let MAX_NODE$2
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
MAX_PATH_DEPTH
const MAX_PATH_DEPTH = 32
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. Maximum key depth.
MAX_PATH_LENGTH_BYTES
const MAX_PATH_LENGTH_BYTES = 768
Maximum number of (UTF8) bytes in a Firebase path.
MAX_PAYLOAD_SIZE
const MAX_PAYLOAD_SIZE = MAX_URL_DATA_SIZE - SEG_HEADER_SIZE
MAX_URL_DATA_SIZE
const MAX_URL_DATA_SIZE = 1870
MESSAGE_DATA
const MESSAGE_DATA = 'd'
MESSAGE_TYPE
const MESSAGE_TYPE = 't'
MIN_NAME
const MIN_NAME = '[MIN_NAME]'
Minimum key name. Invalid for actual data, used as a marker to sort before any valid names
name
const name = "@firebase/database"
nameCompare
const nameCompare
Initial value:
= function (a, b) {
    if (a === b) {
        return 0;
    }
    else if (a === MIN_NAME || b === MAX_NAME) {
        return -1;
    }
    else if (b === MIN_NAME || a === MAX_NAME) {
        return 1;
    }
    else {
        const aAsInt = tryParseInt(a), bAsInt = tryParseInt(b);
        if (aAsInt !== null) {
            if (bAsInt !== null) {
                return aAsInt - bAsInt === 0 ? a.length - b.length : aAsInt - bAsInt;
            }
            else {
                return -1;
            }
        }
        else if (bAsInt !== null) {
            return 1;
        }
        else {
            return a < b ? -1 : 1;
        }
    }
}
Compares valid Firebase key names, plus min and max name
nextConnectionId_
PersistentConnection nextConnectionId_ = 0
Counter for number of connections created. Mainly used for tagging in the logs
nextPersistentConnectionId_
PersistentConnection nextPersistentConnectionId_ = 0
NO_COMPLETE_CHILD_SOURCE
const NO_COMPLETE_CHILD_SOURCE = new NoCompleteChildSource_()
Singleton instance.
nodeFromJSON$1
let nodeFromJSON$1
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
ObjectToUniqueKey
const ObjectToUniqueKey
Initial value:
= function (obj) {
    if (typeof obj !== 'object' || obj === null) {
        return stringify(obj);
    }
    const keys = [];
    
    for (const k in obj) {
        keys.push(k);
    }
    
    keys.sort();
    let key = '{';
    for (let i = 0; i < keys.length; i++) {
        if (i !== 0) {
            key += ',';
        }
        key += stringify(keys[i]);
        key += ':';
        key += ObjectToUniqueKey(obj[keys[i]]);
    }
    key += '}';
    return key;
}
OperationType
OperationType[OperationType["LISTEN_COMPLETE"]=3]
Initial value:
{
    OperationType[OperationType["OVERWRITE"] = 0] = "OVERWRITE"
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
OWNER
EmulatorTokenProvider OWNER = 'owner'
A string that is treated as an admin access token by the RTDB emulator. Used by Admin SDK.
PersistentStorage
const PersistentStorage = createStoragefor('localStorage')
A storage object that lasts across sessions
PING
const PING = 'p'
PRIORITY_INDEX
const PRIORITY_INDEX = new PriorityIndex()
priorityHashText
const priorityHashText
Initial value:
= function (priority) {
    if (typeof priority === 'number') {
        return 'number:' + doubleToIEEE754String(priority);
    }
    else {
        return 'string:' + priority;
    }
}
PROTOCOL_VERSION
const PROTOCOL_VERSION = '5'
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
RECONNECT_DELAY_MULTIPLIER
const RECONNECT_DELAY_MULTIPLIER = 1.3
RECONNECT_DELAY_RESET_TIMEOUT
const RECONNECT_DELAY_RESET_TIMEOUT = 30000
RECONNECT_MAX_DELAY_DEFAULT
const RECONNECT_MAX_DELAY_DEFAULT = 60 * 5 * 1000
RECONNECT_MAX_DELAY_FOR_ADMINS
const RECONNECT_MAX_DELAY_FOR_ADMINS = 30 * 1000
RECONNECT_MIN_DELAY
const RECONNECT_MIN_DELAY = 1000
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
RED
LLRBNode RED = true
referenceConstructor
let referenceConstructor
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
referenceConstructor$1
let referenceConstructor$1
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
REFERER_PARAM
const REFERER_PARAM = 'r'
REPORT_STATS_INTERVAL
const REPORT_STATS_INTERVAL = 5 * 60 * 1000
reporters
const reporters = {}
requireKey
const requireKey
Initial value:
= function (key, obj) {
    if (obj && key in obj) {
        return obj[key];
    }
    else {
        throw new Error('Missing required key (' + key + ') in object: ' + stringify(obj));
    }
}
resolveComplexDeferredValue
const resolveComplexDeferredValue
Initial value:
= function (op, existing, unused) {
    if (!op.hasOwnProperty('increment')) {
        assert(false, 'Unexpected server value: ' + JSON.stringify(op, null, 2));
    }
    const delta = op['increment'];
    if (typeof delta !== 'number') {
        assert(false, 'Unexpected increment value: ' + delta);
    }
    const existingNode = existing.node();
    assert(existingNode !== null && typeof existingNode !== 'undefined', 'Expected ChildrenNode.EMPTY_NODE for nulls');
    
    if (!existingNode.isLeafNode()) {
        return delta;
    }
    const leaf = existingNode;
    const existingVal = leaf.getValue();
    if (typeof existingVal !== 'number') {
        return delta;
    }
    
    return existingVal + delta;
}
resolveDeferredLeafValue
const resolveDeferredLeafValue
Initial value:
= function (value, existingVal, serverValues) {
    if (!value || typeof value !== 'object') {
        return value;
    }
    assert('.sv' in value, 'Unexpected leaf node or priority contents');
    if (typeof value['.sv'] === 'string') {
        return resolveScalarDeferredValue(value['.sv'], existingVal, serverValues);
    }
    else if (typeof value['.sv'] === 'object') {
        return resolveComplexDeferredValue(value['.sv'], existingVal);
    }
    else {
        assert(false, 'Unexpected server value: ' + JSON.stringify(value, null, 2));
    }
}
Value to use when firing local events. When writing server values, fire local events with an approximate value, otherwise return value as-is.
resolveDeferredValueSnapshot
const resolveDeferredValueSnapshot
Initial value:
= function (node, existing, serverValues) {
    return resolveDeferredValue(node, new ExistingValueProvider(existing), serverValues);
}
Recursively replace all deferred values and priorities in the node with the specified generated replacement values. If there are no server values in the node, it'll be returned as-is.
resolveDeferredValueTree
const resolveDeferredValueTree
Initial value:
= function (path, node, syncTree, serverValues) {
    return resolveDeferredValue(node, new DeferredValueProvider(syncTree, path), serverValues);
}
Recursively replace all deferred values and priorities in the tree with the specified generated replacement values.
Parameters
path - path to which write is relative
node - new data written at path
syncTree - current data
resolveScalarDeferredValue
const resolveScalarDeferredValue
Initial value:
= function (op, existing, serverValues) {
    switch (op) {
        case 'timestamp':
            return serverValues['timestamp'];
        default:
            assert(false, 'Unexpected server value: ' + op);
    }
}
responsesRequiredToBeHealthy
WebSocketConnection responsesRequiredToBeHealthy = 2
Number of response before we consider the connection "healthy."
SDK_VERSION
let SDK_VERSION = ''
@license Copyright 2019 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. The semver (www.semver.org) version of the SDK.
SEG_HEADER_SIZE
const SEG_HEADER_SIZE = 30
SERVER_HELLO
const SERVER_HELLO = 'h'
SERVER_KILL_INTERRUPT_REASON
const SERVER_KILL_INTERRUPT_REASON = 'server_kill'
SessionStorage
const SessionStorage = createStoragefor('sessionStorage')
A storage object that only lasts one session
setTimeoutNonBlocking
const setTimeoutNonBlocking
Initial value:
= function (fn, time) {
    const timeout = setTimeout(fn, time);
    
    if (typeof timeout === 'number' &&
        
        typeof Deno !== 'undefined' &&
        
        Deno['unrefTimer']) {
        
        Deno.unrefTimer(timeout);
        
    }
    else if (typeof timeout === 'object' && timeout['unref']) {
        
        timeout['unref']();
    }
    return timeout;
}
Same as setTimeout() except on Node.JS it will /not/ prevent the process from exiting.
It is removed with clearTimeout() as normal.
Parameters
fn - Function to run.
time - Milliseconds to wait before running.
Returns
The setTimeout() return value.
sha1
const sha1
Initial value:
= function (str) {
    const utf8Bytes = stringToByteArray(str);
    const sha1 = new Sha1();
    sha1.update(utf8Bytes);
    const sha1Bytes = sha1.digest();
    return base64.encodeByteArray(sha1Bytes);
}
Sha1 hash of the input string
Parameters
str - The string to hash
Returns
{!string} The resulting hash
splitStringBySize
const splitStringBySize
Initial value:
= function (str, segsize) {
    const len = str.length;
    if (len <= segsize) {
        return [str];
    }
    const dataSegs = [];
    for (let c = 0; c < len; c += segsize) {
        if (c + segsize > len) {
            dataSegs.push(str.substring(c, len));
        }
        else {
            dataSegs.push(str.substring(c, c + segsize));
        }
    }
    return dataSegs;
}
Splits a string into a number of smaller segments of maximum size
Parameters
str - The string
segsize - The maximum number of chars in the string.
Returns
The string, split into appropriately-sized chunks
stringCompare
const stringCompare
Initial value:
= function (a, b) {
    if (a === b) {
        return 0;
    }
    else if (a < b) {
        return -1;
    }
    else {
        return 1;
    }
}
Returns
{!number} comparison result.
SWITCH_ACK
const SWITCH_ACK = 'a'
syncTreeNextQueryTag_
let syncTreeNextQueryTag_ = 1
Static tracker for next query tag.
TRANSPORT_SESSION_PARAM
const TRANSPORT_SESSION_PARAM = 's'
tryParseInt
const tryParseInt
Initial value:
= function (str) {
    if (INTEGER_REGEXP_.test(str)) {
        const intVal = Number(str);
        if (intVal >= INTEGER_32_MIN && intVal <= INTEGER_32_MAX) {
            return intVal;
        }
    }
    return null;
}
If the string contains a 32-bit integer, return it. Else return null.
UPGRADE_TIMEOUT
const UPGRADE_TIMEOUT = 60000
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
USE_HINZE
const USE_HINZE = true
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
validatePriorityNode
const validatePriorityNode
Initial value:
= function (priorityNode) {
    if (priorityNode.isLeafNode()) {
        const val = priorityNode.val();
        assert(typeof val === 'string' ||
            typeof val === 'number' ||
            (typeof val === 'object' && contains(val, '.sv')), 'Priority must be a string or number.');
    }
    else {
        assert(priorityNode === MAX_NODE$2 || priorityNode.isEmpty(), 'priority of unexpected type.');
    }
    
    assert(priorityNode === MAX_NODE$2 || priorityNode.getPriority().isEmpty(), "Priority nodes can't have a priority of their own.");
}
Validates that a priority snapshot Node is valid.
VALUE_INDEX
const VALUE_INDEX = new ValueIndex()
VALUE_TYPE_ORDER
LeafNode VALUE_TYPE_ORDER = ['object', 'boolean', 'number', 'string']
The sort order for comparing leaf nodes of different types. If two leaf nodes have the same type, the comparison falls back to their value
version
const version = "1.0.8"
VERSION_PARAM
const VERSION_PARAM = 'v'
warn
const warn
Initial value:
= function (...varArgs) {
    const message = 'FIREBASE WARNING: ' + buildLogMessage_(...varArgs);
    logClient.warn(message);
}
warnIfPageIsSecure
const warnIfPageIsSecure
Initial value:
= function () {
    
    if (typeof window !== 'undefined' &&
        window.location &&
        window.location.protocol &&
        window.location.protocol.indexOf('https:') !== -1) {
        warn('Insecure Firebase access from a secure page. ' +
            'Please use https in calls to new Firebase().');
    }
}
Logs a warning if the containing page uses https. Called when a call to new Firebase does not use https.
WEBSOCKET
const WEBSOCKET = 'websocket'
websocket
import Websocket from faye websocket
WEBSOCKET_KEEPALIVE_INTERVAL
const WEBSOCKET_KEEPALIVE_INTERVAL = 45000
WEBSOCKET_MAX_FRAME_SIZE
const WEBSOCKET_MAX_FRAME_SIZE = 16384
@license Copyright 2017 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
WebSocketImpl
let WebSocketImpl = null