backend/node_modules/concurrently/dist/src/date-format.js File Reference
Classes
class DateFormatter
Functions
function getLocale (options)
function makeTokenFn (options, type, fallback)
function startOfWeek (date, options)
function getWeekYear (date, options)
function getWeek (date, options)
function getWeekOfMonth (date, options)
function getDayOfYear (date)
function pad (length, val)
Variables
use strict
exports DateFormatter = void 0
const tokens
let locale
Function Documentation
getDayOfYear()
function getDayOfYear (date)
References i.
getLocale()
function getLocale (options)
References locale.
getWeek()
function getWeek (date, options)
References diff, getLocale(), getWeekYear(), locale, and startOfWeek().
getWeekOfMonth()
function getWeekOfMonth (date, options)
References startOfWeek().
getWeekYear()
function getWeekYear (date, options)
References getLocale(), locale, startOfWeek(), and year.
makeTokenFn()
function makeTokenFn (options, type, fallback)
Creates a token formatting function that returns the value of the chosen part type, using the current locale's settings.
If the date/formatter settings doesn't include the requested part type, the fallback function is invoked, if specified. If none has been specified, returns an empty string.
References fallback, p, and type.
pad()
function pad (length, val)
References length.
startOfWeek()
function startOfWeek (date, options)
References day, diff, getLocale(), and locale.
Variable Documentation
DateFormatter
exports DateFormatter = void 0
locale
let locale
strict
use strict
tokens
const tokens
A map of token to its implementations by length. If an index is undefined, then that token length is unsupported.