backend/node_modules/debug/src/debug.js File Reference
Functions
function selectColor (namespace)
function createDebug (namespace)
function enable (namespaces)
function enabled (name)
function coerce (val)
Variables
exports = module.exports = createDebug.debug = createDebug['default'] = createDebug
exports coerce = coerce
exports disable = disable
exports enable = enable
exports enabled = enabled
exports humanize = require('ms')
exports names = []
exports skips = []
exports formatters = {}
var prevTime
Function Documentation
coerce()
function coerce (val)
Coerce val.
Parameters
{Mixed} val
Returns
{Mixed} @api private
createDebug()
function createDebug (namespace)
Create a debugger with the given namespace.
Parameters
{String} namespace
Returns
{Function} @api public
References a, args, Array, debug, exports, format, g, i, index, match, ms, prevTime, selectColor(), and Z().
enable()
function enable (namespaces)
Enables a debug mode by namespaces. This can include modes separated by a colon and wildcards.
Parameters
{String} namespaces @api public
References exports, g, i, s, and split().
enabled()
function enabled (name)
Returns true if the given mode name is enabled, false otherwise.
Parameters
{String} name
Returns
{Boolean} @api public
References exports, i, and name.
selectColor()
function selectColor (namespace)
Select a color.
Parameters
{String} namespace
Returns
{Number} @api private
References charCodeAt, exports, hash(), and i.
Variable Documentation
coerce
exports coerce = coerce
disable
function disable () = disable
Disable debug output.
@api public
enable
exports enable = enable
An options object to configure throttling on BulkWriter.
Whether to disable or configure throttling. By default, throttling is enabled. throttling can be set to either a boolean or a config object. Setting it to true will use default values. You can override the defaults by setting it to false to disable throttling, or by setting the config values to enable throttling with the provided values.
throttling. Throttling is enabled by default, if the field is set to true or if any custom throttling options are provided. { initialOpsPerSecond: number } sets the initial maximum number of operations per second allowed by the throttler. If initialOpsPerSecond is not set, the default is 500 operations per second. { maxOpsPerSecond: number } sets the maximum number of operations per second allowed by the throttler. If maxOpsPerSecond is not set, no maximum is enforced.
enabled
exports enabled = enabled
exports
exports = module.exports = createDebug.debug = createDebug['default'] = createDebug
This is the common logic for both the Node.js and web browser implementations of debug().
Expose debug() as the module.
formatters
exports formatters = {}
Map of special "%n" handling functions, for the debug "format" argument.
Valid key names are a single, lower or upper-case letter, i.e. "n" and "N".
humanize
exports humanize = require('ms')
names
exports names = []
The currently active debug mode names, and names to skip.
prevTime
var prevTime
Previous log timestamp.
skips
exports skips = []