backend/node_modules/readable-stream/lib/internal/streams/destroy.js File Reference
Functions
function destroy (err, cb)
function emitErrorAndCloseNT (self, err)
function emitCloseNT (self)
function undestroy ()
function emitErrorNT (self, err)
function errorOrDestroy (stream, err)
Variables
use strict
module exports
Function Documentation
destroy()
function destroy (err, cb)
References _destroy, emitCloseNT(), emitErrorAndCloseNT(), emitErrorNT(), and process.
emitCloseNT()
function emitCloseNT (self)
emitErrorAndCloseNT()
function emitErrorAndCloseNT (self, err)
References emitCloseNT(), and emitErrorNT().
emitErrorNT()
function emitErrorNT (self, err)
errorOrDestroy()
function errorOrDestroy (stream, err)
References stream.
undestroy()
function undestroy ()
Variable Documentation
exports
module exports
Initial value:
= {
  destroy: destroy,
  undestroy: undestroy,
  errorOrDestroy: errorOrDestroy
}
strict
use strict