backend/node_modules/ecdsa-sig-formatter/src/ecdsa-sig-formatter.js File Reference
Functions
function base64Url (base64)
function signatureAsBuffer (signature)
function derToJose (signature, alg)
function countPadding (buf, start, stop)
function joseToDer (signature, alg)
Variables
use strict
var Buffer = require('safe-buffer').Buffer
var getParamBytesForAlg = require('./param-bytes-for-alg')
var MAX_OCTET = 0x80
var CLASS_UNIVERSAL = 0
var PRIMITIVE_BIT = 0x20
var TAG_SEQ = 0x10
var TAG_INT = 0x02
var ENCODED_TAG_SEQ = (TAG_SEQ | PRIMITIVE_BIT) | (CLASS_UNIVERSAL << 6)
var ENCODED_TAG_INT = TAG_INT | (CLASS_UNIVERSAL << 6)
module exports
Function Documentation
base64Url()
function base64Url (base64)
References base64, and g.
countPadding()
function countPadding (buf, start, stop)
References buf, MAX_OCTET, and start.
derToJose()
function derToJose (signature, alg)
References base64Url(), ENCODED_TAG_INT, ENCODED_TAG_SEQ, getParamBytesForAlg, MAX_OCTET, o, signature, and signatureAsBuffer().
joseToDer()
function joseToDer (signature, alg)
References countPadding(), ENCODED_TAG_INT, ENCODED_TAG_SEQ, getParamBytesForAlg, MAX_OCTET, signature, and signatureAsBuffer().
signatureAsBuffer()
function signatureAsBuffer (signature)
References signature.
Variable Documentation
Buffer
var Buffer = require('safe-buffer').Buffer
CLASS_UNIVERSAL
var CLASS_UNIVERSAL = 0
ENCODED_TAG_INT
var ENCODED_TAG_INT = TAG_INT | (CLASS_UNIVERSAL << 6)
ENCODED_TAG_SEQ
var ENCODED_TAG_SEQ = (TAG_SEQ | PRIMITIVE_BIT) | (CLASS_UNIVERSAL << 6)
exports
module exports
Initial value:
= {
    derToJose: derToJose,
    joseToDer: joseToDer
}
getParamBytesForAlg
var getParamBytesForAlg = require('./param-bytes-for-alg')
MAX_OCTET
var MAX_OCTET = 0x80
PRIMITIVE_BIT
var PRIMITIVE_BIT = 0x20
strict
use strict
TAG_INT
var TAG_INT = 0x02
TAG_SEQ
var TAG_SEQ = 0x10