backend/node_modules/node-forge/lib/ed25519.js File Reference
Functions
if (typeof BigInteger==='undefined')
function messageToNativeBuffer (options)
function sha512 (msg, msgLen)
function crypto_sign_keypair (pk, sk)
function crypto_sign (sm, m, n, sk)
function crypto_sign_open (m, sm, n, pk)
function modL (r, x)
function reduce (r)
function add (p, q)
function cswap (p, q, b)
function pack (r, p)
function pack25519 (o, n)
function unpackneg (r, p)
function unpack25519 (o, n)
function pow2523 (o, i)
function neq25519 (a, b)
function crypto_verify_32 (x, xi, y, yi)
function vn (x, xi, y, yi, n)
function par25519 (a)
function scalarmult (p, q, s)
function scalarbase (p, s)
function set25519 (r, a)
function inv25519 (o, i)
function car25519 (o)
function sel25519 (p, q, b)
function gf (init)
function A (o, a, b)
function Z (o, a, b)
function S (o, a)
function M (o, a, b)
Variables
var forge = require('./forge')
var asn1Validator = require('./asn1-validator')
var publicKeyValidator = asn1Validator.publicKeyValidator
var privateKeyValidator = asn1Validator.privateKeyValidator
var ByteBuffer = forge.util.ByteBuffer
var NativeBuffer = typeof Buffer === 'undefined' ? Uint8Array : Buffer
forge pki = forge.pki || {}
module exports = forge.pki.ed25519 = forge.ed25519 = forge.ed25519 || {}
var ed25519 = forge.ed25519
ed25519 constants = {}
ed25519 constants PUBLIC_KEY_BYTE_LENGTH = 32
ed25519 constants PRIVATE_KEY_BYTE_LENGTH = 64
ed25519 constants SEED_BYTE_LENGTH = 32
ed25519 constants SIGN_BYTE_LENGTH = 64
ed25519 constants HASH_BYTE_LENGTH = 64
ed25519 generateKeyPair
ed25519 privateKeyFromAsn1
ed25519 publicKeyFromAsn1
ed25519 publicKeyFromPrivateKey
ed25519 sign
ed25519 verify
var gf0 = gf()
var gf1 = gf([1])
var D
var D2
var X
var Y
var L
var I
Function Documentation
A()
function A (o, a, b)
References a, b, i, and o.
add()
function add (p, q)
References A(), a, b, c, d, D2, e, f, g, gf(), h, M, p, q, t, and Z().
car25519()
function car25519 (o)
References c, i, o, and v.
crypto_sign()
function crypto_sign (sm, m, n, sk)
References d, Float64Array, gf(), h, i, j, m, modL(), n, p, pack(), r, reduce, scalarbase(), and sha512.
crypto_sign_keypair()
function crypto_sign_keypair (pk, sk)
References d, gf(), i, p, pack(), scalarbase(), and sha512.
crypto_sign_open()
function crypto_sign_open (m, sm, n, pk)
References add, crypto_verify_32(), gf(), h, i, m, n, NativeBuffer, p, pack(), q, reduce, scalarbase(), scalarmult(), sha512, t, and unpackneg().
crypto_verify_32()
function crypto_verify_32 (x, xi, y, yi)
References vn, and y.
cswap()
function cswap (p, q, b)
References b, i, p, q, and sel25519().
gf()
function gf (init)
References Float64Array, i, init, and r.
if()
if (typeof BigInteger = == 'undefined')
References BigInteger, and forge.
inv25519()
function inv25519 (o, i)
References a, c, gf(), i, M, o, and S.
M()
function M (o, a, b)
References a, b, c, o, and v.
messageToNativeBuffer()
function messageToNativeBuffer (options)
References buffer, ByteBuffer, encoding, i, message, NativeBuffer, and undefined.
modL()
function modL (r, x)
References i, j, k, L, and r.
neq25519()
function neq25519 (a, b)
References a, b, c, crypto_verify_32(), d, NativeBuffer, and pack25519().
pack()
function pack (r, p)
References gf(), inv25519(), M, p, pack25519(), par25519(), and r.
pack25519()
function pack25519 (o, n)
References b, car25519(), gf(), i, j, m, n, o, sel25519(), and t.
par25519()
function par25519 (a)
References a, d, NativeBuffer, and pack25519().
pow2523()
function pow2523 (o, i)
References a, c, gf(), i, M, o, and S.
reduce()
function reduce (r)
References Float64Array, i, modL(), and r.
S()
function S (o, a)
References a, M, and o.
scalarbase()
function scalarbase (p, s)
References gf(), gf1, M, p, q, s, scalarmult(), set25519(), X, and Y.
scalarmult()
function scalarmult (p, q, s)
References add, b, cswap(), gf0, gf1, i, p, q, s, and set25519().
sel25519()
function sel25519 (p, q, b)
References b, c, i, p, q, and t.
set25519()
function set25519 (r, a)
References a, i, and r.
sha512()
function sha512 (msg, msgLen)
References buffer, ByteBuffer, ed25519, forge, hash(), i, md, msg, and NativeBuffer.
unpack25519()
function unpack25519 (o, n)
References i, n, and o.
unpackneg()
function unpackneg (r, p)
References A(), D, gf(), gf0, gf1, I, M, neq25519(), p, par25519(), pow2523(), r, S, set25519(), t, unpack25519(), and Z().
vn()
function vn (x, xi, y, yi, n)
References d, i, n, and y.
Z()
function Z (o, a, b)
References a, b, i, and o.
Variable Documentation
asn1Validator
var asn1Validator = require('./asn1-validator')
ByteBuffer
var ByteBuffer = forge.util.ByteBuffer
constants
ed25519 constants = {}
D
var D
Initial value:
= gf([
  0x78a3, 0x1359, 0x4dca, 0x75eb, 0xd8ab, 0x4141, 0x0a4d, 0x0070,
  0xe898, 0x7779, 0x4079, 0x8cc7, 0xfe73, 0x2b6f, 0x6cee, 0x5203])
D2
var D2
Initial value:
= gf([
  0xf159, 0x26b2, 0x9b94, 0xebd6, 0xb156, 0x8283, 0x149a, 0x00e0,
  0xd130, 0xeef3, 0x80f2, 0x198e, 0xfce7, 0x56df, 0xd9dc, 0x2406])
ed25519
var ed25519 = forge.ed25519
exports
module exports = forge.pki.ed25519 = forge.ed25519 = forge.ed25519 || {}
forge
var forge = require('./forge')
JavaScript implementation of Ed25519.
Copyright (c) 2017-2019 Digital Bazaar, Inc.
This implementation is based on the most excellent TweetNaCl which is in the public domain. Many thanks to its contributors:
 https://github.com/dchest/tweetnacl-js
generateKeyPair
ed25519 generateKeyPair
Initial value:
= function(options) {
  options = options || {};
  var seed = options.seed;
  if(seed === undefined) {
    
    seed = forge.random.getBytesSync(ed25519.constants.SEED_BYTE_LENGTH);
  } else if(typeof seed === 'string') {
    if(seed.length !== ed25519.constants.SEED_BYTE_LENGTH) {
      throw new TypeError(
        '"seed" must be ' + ed25519.constants.SEED_BYTE_LENGTH +
        ' bytes in length.');
    }
  } else if(!(seed instanceof Uint8Array)) {
    throw new TypeError(
      '"seed" must be a node.js Buffer, Uint8Array, or a binary string.');
  }
  seed = messageToNativeBuffer({message: seed, encoding: 'binary'});
  var pk = new NativeBuffer(ed25519.constants.PUBLIC_KEY_BYTE_LENGTH);
  var sk = new NativeBuffer(ed25519.constants.PRIVATE_KEY_BYTE_LENGTH);
  for(var i = 0; i < 32; ++i) {
    sk[i] = seed[i];
  }
  crypto_sign_keypair(pk, sk);
  return {publicKey: pk, privateKey: sk};
}
gf0
var gf0 = gf()
gf1
var gf1 = gf([1])
HASH_BYTE_LENGTH
ed25519 constants HASH_BYTE_LENGTH = 64
I
var I
Initial value:
= gf([
  0xa0b0, 0x4a0e, 0x1b27, 0xc4ee, 0xe478, 0xad2f, 0x1806, 0x2f43,
  0xd7a7, 0x3dfb, 0x0099, 0x2b4d, 0xdf0b, 0x4fc1, 0x2480, 0x2b83])
L
var L
Initial value:
= new Float64Array([
  0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58,
  0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10])
NativeBuffer
var NativeBuffer = typeof Buffer === 'undefined' ? Uint8Array : Buffer
pki
var pki = forge.pki || {}
PRIVATE_KEY_BYTE_LENGTH
ed25519 constants PRIVATE_KEY_BYTE_LENGTH = 64
privateKeyFromAsn1
ed25519 privateKeyFromAsn1
Initial value:
= function(obj) {
  var capture = {};
  var errors = [];
  var valid = forge.asn1.validate(obj, privateKeyValidator, capture, errors);
  if(!valid) {
    var error = new Error('Invalid Key.');
    error.errors = errors;
    throw error;
  }
  var oid = forge.asn1.derToOid(capture.privateKeyOid);
  var ed25519Oid = forge.oids.EdDSA25519;
  if(oid !== ed25519Oid) {
    throw new Error('Invalid OID "' + oid + '"; OID must be "' +
      ed25519Oid + '".');
  }
  var privateKey = capture.privateKey;
  
  
  var privateKeyBytes = messageToNativeBuffer({
    message: forge.asn1.fromDer(privateKey).value,
    encoding: 'binary'
  });
  
  
  
  return {privateKeyBytes: privateKeyBytes};
}
Converts a private key from a RFC8410 ASN.1 encoding.
Parameters
obj - The asn1 representation of a private key.
Returns
{Object} keyInfo - The key information.
{Buffer|Uint8Array} keyInfo.privateKeyBytes - 32 private key bytes.
privateKeyValidator
var privateKeyValidator = asn1Validator.privateKeyValidator
PUBLIC_KEY_BYTE_LENGTH
ed25519 constants PUBLIC_KEY_BYTE_LENGTH = 32
publicKeyFromAsn1
ed25519 publicKeyFromAsn1
Initial value:
= function(obj) {
  
  var capture = {};
  var errors = [];
  var valid = forge.asn1.validate(obj, publicKeyValidator, capture, errors);
  if(!valid) {
    var error = new Error('Invalid Key.');
    error.errors = errors;
    throw error;
  }
  var oid = forge.asn1.derToOid(capture.publicKeyOid);
  var ed25519Oid = forge.oids.EdDSA25519;
  if(oid !== ed25519Oid) {
    throw new Error('Invalid OID "' + oid + '"; OID must be "' +
      ed25519Oid + '".');
  }
  var publicKeyBytes = capture.ed25519PublicKey;
  if(publicKeyBytes.length !== ed25519.constants.PUBLIC_KEY_BYTE_LENGTH) {
    throw new Error('Key length is invalid.');
  }
  return messageToNativeBuffer({
    message: publicKeyBytes,
    encoding: 'binary'
  });
}
Converts a public key from a RFC8410 ASN.1 encoding.
Parameters
obj - The asn1 representation of a public key.
Returns
{Buffer|Uint8Array} - 32 public key bytes.
publicKeyFromPrivateKey
ed25519 publicKeyFromPrivateKey
Initial value:
= function(options) {
  options = options || {};
  var privateKey = messageToNativeBuffer({
    message: options.privateKey, encoding: 'binary'
  });
  if(privateKey.length !== ed25519.constants.PRIVATE_KEY_BYTE_LENGTH) {
    throw new TypeError(
      '"options.privateKey" must have a byte length of ' +
      ed25519.constants.PRIVATE_KEY_BYTE_LENGTH);
  }
  var pk = new NativeBuffer(ed25519.constants.PUBLIC_KEY_BYTE_LENGTH);
  for(var i = 0; i < pk.length; ++i) {
    pk[i] = privateKey[32 + i];
  }
  return pk;
}
publicKeyValidator
var publicKeyValidator = asn1Validator.publicKeyValidator
SEED_BYTE_LENGTH
ed25519 constants SEED_BYTE_LENGTH = 32
sign
ed25519 sign
Initial value:
= function(options) {
  options = options || {};
  var msg = messageToNativeBuffer(options);
  var privateKey = messageToNativeBuffer({
    message: options.privateKey,
    encoding: 'binary'
  });
  if(privateKey.length === ed25519.constants.SEED_BYTE_LENGTH) {
    var keyPair = ed25519.generateKeyPair({seed: privateKey});
    privateKey = keyPair.privateKey;
  } else if(privateKey.length !== ed25519.constants.PRIVATE_KEY_BYTE_LENGTH) {
    throw new TypeError(
      '"options.privateKey" must have a byte length of ' +
      ed25519.constants.SEED_BYTE_LENGTH + ' or ' +
      ed25519.constants.PRIVATE_KEY_BYTE_LENGTH);
  }
  var signedMsg = new NativeBuffer(
    ed25519.constants.SIGN_BYTE_LENGTH + msg.length);
  crypto_sign(signedMsg, msg, msg.length, privateKey);
  var sig = new NativeBuffer(ed25519.constants.SIGN_BYTE_LENGTH);
  for(var i = 0; i < sig.length; ++i) {
    sig[i] = signedMsg[i];
  }
  return sig;
}
SIGN_BYTE_LENGTH
ed25519 constants SIGN_BYTE_LENGTH = 64
verify
ed25519 verify
X
var X
Initial value:
= gf([
  0xd51a, 0x8f25, 0x2d60, 0xc956, 0xa7b2, 0x9525, 0xc760, 0x692c,
  0xdc5c, 0xfdd6, 0xe231, 0xc0a4, 0x53fe, 0xcd6e, 0x36d3, 0x2169])
Y
var Y
Initial value:
= gf([
  0x6658, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666,
  0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666])