backend/node_modules/negotiator/lib/encoding.js File Reference
Functions
function parseAcceptEncoding (accept)
function parseEncoding (str, i)
function getEncodingPriority (encoding, accepted, index)
function specify (encoding, spec, index)
function preferredEncodings (accept, provided)
function compareSpecs (a, b)
function getFullEncoding (spec)
function isQuality (spec)
Variables
use strict
module exports = preferredEncodings
module exports preferredEncodings = preferredEncodings
var simpleEncodingRegExp = /^\s*([^\s;]+)\s*(?:;(.*))?$/
Function Documentation
compareSpecs()
function compareSpecs (a, b) [private]
Compare two specs.
References a, and b.
getEncodingPriority()
function getEncodingPriority (encoding, accepted, index) [private]
Get the priority of an encoding.
References encoding, i, index, o, q, s, and specify().
getFullEncoding()
function getFullEncoding (spec) [private]
Get full encoding string. Here is the caller graph for this function:
isQuality()
function isQuality (spec) [private]
Check if a spec has any quality. Here is the caller graph for this function:
parseAcceptEncoding()
function parseAcceptEncoding (accept) [private]
Parse the Accept-Encoding header.
References accepts, encoding, i, j, parseEncoding(), q, specify(), and trim().
parseEncoding()
function parseEncoding (str, i) [private]
Parse an encoding from the Accept-Encoding header.
References encoding, i, j, match, p, q, simpleEncodingRegExp, and str().
preferredEncodings()
function preferredEncodings (accept, provided)
Get the preferred encodings from an Accept-Encoding header.
References accepts, compareSpecs(), getEncodingPriority(), getFullEncoding(), index, isQuality(), parseAcceptEncoding(), and type.
specify()
function specify (encoding, spec, index) [private]
Get the specificity of the encoding.
References encoding, i, index, o, q, and s.
Variable Documentation
exports
module exports = preferredEncodings
Module exports.
preferredEncodings
module exports preferredEncodings = preferredEncodings
simpleEncodingRegExp
var simpleEncodingRegExp = /^\s*([^\s;]+)\s*(?:;(.*))?$/ [private]
Module variables.
strict
use strict
negotiator Copyright(c) 2012 Isaac Z. Schlueter Copyright(c) 2014 Federico Romero Copyright(c) 2014-2015 Douglas Christopher Wilson MIT Licensed