backend/node_modules/google-auth-library/build/src/auth/envDetect.js File Reference
Functions
function async getEnvMemoized ()
function isAppEngine ()
function isCloudFunction ()
function isCloudRun ()
function async isKubernetesEngine ()
function async isComputeEngine ()
Variables
use strict
exports GCPEnv = void 0
exports clear = clear
exports getEnv = getEnv
const gcpMetadata = require("gcp-metadata")
let envPromise
Function Documentation
getEnvMemoized()
function async getEnvMemoized ()
References env, GCPEnv, isAppEngine(), isCloudFunction(), isCloudRun(), isComputeEngine(), and isKubernetesEngine().
isAppEngine()
function isAppEngine ()
References process.
isCloudFunction()
function isCloudFunction ()
References process.
isCloudRun()
function isCloudRun ()
This check only verifies that the environment is running knative. This must be run after checking for Kubernetes, otherwise it will return a false positive.
References process.
isComputeEngine()
function async isComputeEngine ()
References gcpMetadata.
isKubernetesEngine()
function async isKubernetesEngine ()
References e, and gcpMetadata.
Variable Documentation
clear
exports clear = clear
envPromise
let envPromise
GCPEnv
function GCPEnv = void 0
gcpMetadata
const gcpMetadata = require("gcp-metadata")
getEnv
function async getEnv = getEnv
strict
use strict