backend/node_modules/readable-stream/errors-browser.js File Reference
Functions
function _inheritsLoose (subClass, superClass)
function createErrorType (code, message, Base)
function oneOf (expected, thing)
function startsWith (str, search, pos)
function endsWith (str, search, this_len)
function includes (str, search, start)
Variables
use strict
var codes = {}
Function Documentation
_inheritsLoose()
function _inheritsLoose (subClass, superClass)
createErrorType()
function createErrorType (code, message, Base)
References _inheritsLoose(), Base, codes, and message.
endsWith()
function endsWith (str, search, this_len)
References str(), and undefined.
includes()
function includes (str, search, start)
References start, and str().
oneOf()
function oneOf (expected, thing)
References Array, expected, and i.
startsWith()
function startsWith (str, search, pos)
References str().
Variable Documentation
codes
module exports codes = {}
strict
use strict