backend/node_modules/rxjs/dist/esm5/internal/ajax/ajax.js File Reference
Functions
function ajaxGet (url, headers)
function ajaxPost (url, body, headers)
function ajaxDelete (url, headers)
function ajaxPut (url, body, headers)
function ajaxPatch (url, body, headers)
function ajaxGetJSON (url, headers)
function export fromAjax (init)
function extractContentTypeAndMaybeSerializeBody (body, headers)
function toStringCheck (obj, name)
function isArrayBuffer (body)
function isFile (body)
function isBlob (body)
function isArrayBufferView (body)
function isFormData (body)
function isURLSearchParams (body)
function isReadableStream (body)
Variables
import { __assign } from "tslib"
var mapResponse = map(function (x) { return x.response; })
var export ajax
var UPLOAD = 'upload'
var DOWNLOAD = 'download'
var LOADSTART = 'loadstart'
var PROGRESS = 'progress'
var LOAD = 'load'
var _toString = Object.prototype.toString
Function Documentation
ajaxDelete()
function ajaxDelete (url, headers)
References ajax, headers, method, and url.
ajaxGet()
function ajaxGet (url, headers)
References ajax, headers, method, and url.
ajaxGetJSON()
function ajaxGetJSON (url, headers)
References ajax, headers, mapResponse, method, and url.
ajaxPatch()
function ajaxPatch (url, body, headers)
References ajax, headers, method, and url.
ajaxPost()
function ajaxPost (url, body, headers)
References ajax, headers, method, and url.
ajaxPut()
function ajaxPut (url, body, headers)
References ajax, headers, method, and url.
extractContentTypeAndMaybeSerializeBody()
function extractContentTypeAndMaybeSerializeBody (body, headers)
References _a, headers, isArrayBuffer, isArrayBufferView, isBlob(), isFile(), isFormData(), isReadableStream(), isURLSearchParams(), and JSON.
fromAjax()
function export fromAjax (init)
References __assign, _a, _b, _c, _d, AjaxError, AjaxResponse, AjaxTimeoutError, async, config, DOWNLOAD, e, error, event, extractContentTypeAndMaybeSerializeBody(), false, headers, init, LOAD, LOADSTART, method, msg, Observable, PROGRESS, response, status, timeout, type, UPLOAD, url, value, and xhr.
isArrayBuffer()
function isArrayBuffer (body)
References toStringCheck().
isArrayBufferView()
function isArrayBufferView (body)
isBlob()
function isBlob (body)
References toStringCheck().
isFile()
function isFile (body)
References toStringCheck().
isFormData()
function isFormData (body)
References FormData().
isReadableStream()
function isReadableStream (body)
isURLSearchParams()
function isURLSearchParams (body)
toStringCheck()
function toStringCheck (obj, name)
References _toString, name, and obj.
Variable Documentation
_toString
var _toString = Object.prototype.toString
ajax
var export ajax
Initial value:
= (function () {
    var create = function (urlOrConfig) {
        var config = typeof urlOrConfig === 'string'
            ? {
                url: urlOrConfig,
            }
            : urlOrConfig;
        return fromAjax(config);
    };
    create.get = ajaxGet;
    create.post = ajaxPost;
    create.delete = ajaxDelete;
    create.put = ajaxPut;
    create.patch = ajaxPatch;
    create.getJSON = ajaxGetJSON;
    return create;
})()
DOWNLOAD
var DOWNLOAD = 'download'
import
import { __assign } from "tslib"
LOAD
var LOAD = 'load'
LOADSTART
var LOADSTART = 'loadstart'
mapResponse
var mapResponse = map(function (x) { return x.response; })
PROGRESS
var PROGRESS = 'progress'
UPLOAD
var UPLOAD = 'upload'