backend/node_modules/rxjs/dist/esm5/internal/observable/fromEvent.js File Reference
Functions
function export fromEvent (target, eventName, options, resultSelector)
function toCommonHandlerRegistry (target, eventName)
function isNodeStyleEventEmitter (target)
function isJQueryStyleEventEmitter (target)
function isEventTarget (target)
Variables
import { __read } from "tslib"
var nodeEventEmitterMethods = ['addListener', 'removeListener']
var eventTargetMethods = ['addEventListener', 'removeEventListener']
var jqueryMethods = ['on', 'off']
Function Documentation
fromEvent()
function export fromEvent (target, eventName, options, resultSelector)
References __read, _a, add, args, eventTargetMethods, fromEvent, innerFrom, isArrayLike, isEventTarget(), isFunction, isJQueryStyleEventEmitter(), isNodeStyleEventEmitter(), jqueryMethods, mapOneOrManyArgs, mergeMap, nodeEventEmitterMethods, Observable, toCommonHandlerRegistry(), and undefined.
isEventTarget()
function isEventTarget (target)
References isFunction.
isJQueryStyleEventEmitter()
function isJQueryStyleEventEmitter (target)
References isFunction.
isNodeStyleEventEmitter()
function isNodeStyleEventEmitter (target)
References isFunction.
toCommonHandlerRegistry()
function toCommonHandlerRegistry (target, eventName)
Variable Documentation
eventTargetMethods
var eventTargetMethods = ['addEventListener', 'removeEventListener']
import
import { __read } from "tslib"
jqueryMethods
var jqueryMethods = ['on', 'off']
nodeEventEmitterMethods
var nodeEventEmitterMethods = ['addListener', 'removeListener']