backend/node_modules/event-target-shim/dist/event-target-shim.js File Reference
Functions
function pd (event)
function setCancelFlag (data)
function Event (eventTarget, event)
if (typeof window !=="undefined" &&typeof window.Event !=="undefined")
function defineRedirectDescriptor (key)
function defineCallDescriptor (key)
function defineWrapper (BaseEvent, proto)
function getWrapper (proto)
function wrapEvent (eventTarget, event)
function isStopped (event)
function setEventPhase (event, eventPhase)
function setCurrentTarget (event, currentTarget)
function setPassiveListener (event, passiveListener)
function isObject (x)
function getListeners (eventTarget)
function defineEventAttributeDescriptor (eventName)
function defineEventAttribute (eventTargetPrototype, eventName)
function defineCustomEventTarget (eventNames)
Variables
use strict
const privateData = new WeakMap()
const wrappers = new WeakMap()
Event prototype
const listenersMap = new WeakMap()
const CAPTURE = 1
const BUBBLE = 2
const ATTRIBUTE = 3
exports defineEventAttribute = defineEventAttribute
exports EventTarget = EventTarget
exports default = EventTarget
Function Documentation
defineCallDescriptor()
function defineCallDescriptor (key) [private]
Get the property descriptor to call a given method property.
Parameters
{string} key Property name to define property descriptor.
Returns
{PropertyDescriptor} The property descriptor to call the method property.
References event, pd(), and value.
defineCustomEventTarget()
function defineCustomEventTarget (eventNames) [private]
Define a custom EventTarget with event attributes.
Parameters
{string[]} eventNames Event names for event attributes.
Returns
{EventTarget} The custom EventTarget.
CustomEventTarget
References EventTarget.
defineEventAttribute()
function defineEventAttribute (eventTargetPrototype, eventName)
Define an event attribute (e.g. eventTarget.onclick).
Parameters
{Object} eventTargetPrototype The event target prototype to define an event attrbite.
{string} eventName The event name to define.
Returns
{void}
References defineEventAttributeDescriptor().
defineEventAttributeDescriptor()
function defineEventAttributeDescriptor (eventName) [private]
Get the property descriptor for the event attribute of a given event.
Parameters
{string} eventName The event name to get property descriptor.
Returns
{PropertyDescriptor} The property descriptor.
References ATTRIBUTE, getListeners(), isObject, next(), node, and once.
defineRedirectDescriptor()
function defineRedirectDescriptor (key) [private]
Get the property descriptor to redirect a given property.
Parameters
{string} key Property name to define property descriptor.
Returns
{PropertyDescriptor} The property descriptor to redirect the property.
References pd(), and value.
defineWrapper()
function defineWrapper (BaseEvent, proto) [private]
Define new wrapper class.
Parameters
{Function} BaseEvent The base wrapper class.
{Object} proto The prototype of the original event.
Returns
{Function} The defined wrapper class.
CustomEvent
References event, keys, and proto.
Event()
function Event (eventTarget, event) [private]
See also
 https://dom.spec.whatwg.org/#interface-event The event wrapper. @constructor
Parameters
{EventTarget} eventTarget The event target of this dispatching.
{Event|{type:string}} event The original event to wrap.
References defineRedirectDescriptor(), event, i, keys, privateData, and value.
getListeners()
function getListeners (eventTarget) [private]
Get listeners.
Parameters
{EventTarget} eventTarget The event target to get.
Returns
{Map<string, ListenerNode>} The listeners.
References listenersMap.
getWrapper()
function getWrapper (proto) [private]
Get the wrapper class of a given prototype.
Parameters
{Object} proto The prototype of the original event to get its wrapper.
Returns
{Function} The wrapper class.
References defineWrapper(), Event, getWrapper(), proto, and wrappers.
if()
if (typeof window ! = = "undefined" && typeof window.Event !== "undefined")
References Event, window, and wrappers.
isObject()
function isObject (x)
Check whether a given value is an object or not.
Parameters
{any} x The value to check.
Returns
{boolean} true if the value is an object.
isStopped()
function isStopped (event) [private]
Get the immediateStopped flag of a given event.
Parameters
{Event} event The event to get.
Returns
{boolean} The flag to stop propagation immediately.
References event, and pd().
pd()
function pd (event) [private]
Get private data.
Parameters
{Event} event The event object to get private data.
Returns
{PrivateData} The private data of the event.
References event, and privateData.
setCancelFlag()
function setCancelFlag (data)
 https://dom.spec.whatwg.org/#set-the-canceled-flag
Parameters
data {PrivateData} private data.
References data.
setCurrentTarget()
function setCurrentTarget (event, currentTarget) [private]
Set the current target of a given event.
Parameters
{Event} event The event to set current target.
{EventTarget|null} currentTarget New current target.
Returns
{void}
References event, and pd().
setEventPhase()
function setEventPhase (event, eventPhase) [private]
Set the current event phase of a given event.
Parameters
{Event} event The event to set current target.
{number} eventPhase New event phase.
Returns
{void}
References event, and pd().
setPassiveListener()
function setPassiveListener (event, passiveListener) [private]
Set a passive listener of a given event.
Parameters
{Event} event The event to set current target.
{Function|null} passiveListener New passive listener.
Returns
{void}
References event, and pd().
wrapEvent()
function wrapEvent (eventTarget, event) [private]
Wrap a given event to management a dispatching.
Parameters
{EventTarget} eventTarget The event target of this dispatching.
{Object} event The event to wrap.
Returns
{Event} The wrapper instance.
References event, and getWrapper().
Variable Documentation
ATTRIBUTE
const ATTRIBUTE = 3
BUBBLE
const BUBBLE = 2
CAPTURE
const CAPTURE = 1
default
exports default = EventTarget
defineEventAttribute
exports defineEventAttribute = defineEventAttribute
EventTarget
exports EventTarget () = EventTarget
EventTarget.
This is constructor if no arguments.
This is a function which returns a CustomEventTarget constructor if there are arguments.
For example:
class A extends EventTarget {}
class B extends EventTarget("message") {}
class C extends EventTarget("message", "error") {}
class D extends EventTarget(["message", "error"]) {}
listenersMap
const listenersMap = new WeakMap() [private]
@type {WeakMap<object, Map<string, ListenerNode>>}
privateData
const privateData = new WeakMap() [private]
Private data for event wrappers. @type {WeakMap<Event, PrivateData>}
prototype
EventTarget prototype
strict
use strict
Author
Toru Nagashima https://github.com/mysticatea
Copyright
2015 Toru Nagashima. All rights reserved. See LICENSE file in root directory for full license.
wrappers
const wrappers = new WeakMap() [private]
Cache for wrapper classes. @type {WeakMap<Object, Function>}