backend/node_modules/farmhash-modern/lib/index.js File Reference
Functions
function asBuffer (input)
function asUnsigned32BitNumber (input)
function asUnsigned64BitNumber (input)
function export fingerprint32 (input)
function export fingerprint64 (input)
function export bigqueryFingerprint (input)
function export hash32 (input)
function export hash32WithSeed (input, seed)
function export hash64 (input)
function export hash64WithSeed (input, seed)
Variables
import *as farmhash from bin nodejs farmhash_modern js
Function Documentation
asBuffer()
function asBuffer (input)
asUnsigned32BitNumber()
function asUnsigned32BitNumber (input)
References $, and a.
asUnsigned64BitNumber()
function asUnsigned64BitNumber (input)
References $, a, and n.
bigqueryFingerprint()
function export bigqueryFingerprint (input)
Create a new farmhash based i64 for a string or an array of bytes. Fingerprint value should be portable and stable across library versions and platforms.
This matches the format used by BigQuery's FARM_FINGERPRINT function.
References asBuffer(), and farmhash.
fingerprint32()
function export fingerprint32 (input)
Create a new farmhash based u32 for a string or an array of bytes. Fingerprint value should be portable and stable across library versions and platforms.
References asBuffer(), and farmhash.
fingerprint64()
function export fingerprint64 (input)
Create a new farmhash based u64 for a string or an array of bytes. Fingerprint value should be portable and stable across library versions and platforms.
References asBuffer(), and farmhash.
hash32()
function export hash32 (input)
Create a new farmhash based u32 for an array of bytes. Hash value may vary with library version.
References asBuffer(), and farmhash.
hash32WithSeed()
function export hash32WithSeed (input, seed)
Create a new farmhash based u32 for an array of bytes with a given seed. Hash value may vary with library version.
References asBuffer(), asUnsigned32BitNumber(), and farmhash.
hash64()
function export hash64 (input)
Create a new farmhash based u64 for an array of bytes. Hash value may vary with library version.
References asBuffer(), and farmhash.
hash64WithSeed()
function export hash64WithSeed (input, seed)
Create a new farmhash based u64 for an array of bytes with a given seed. Hash value may vary with library version.
References asBuffer(), asUnsigned64BitNumber(), and farmhash.
Variable Documentation
js
import* as farmhash from bin nodejs farmhash_modern js