backend/node_modules/farmhash-modern/bin/bundler/farmhash_modern_bg.js File Reference
Functions
function export __wbg_set_wasm (val)
function getObject (idx)
function dropObject (idx)
function takeObject (idx)
function getUint8Memory0 ()
function passArray8ToWasm0 (arg, malloc)
function export fingerprint32 (input)
function export fingerprint64 (input)
function export bigquery_fingerprint (input)
function export hash32 (input)
function export hash32_with_seed (input, seed)
function export hash64 (input)
function export hash64_with_seed (input, seed)
function getStringFromWasm0 (ptr, len)
function addHeapObject (obj)
function passStringToWasm0 (arg, malloc, realloc)
function getInt32Memory0 ()
function export __wbg_new_abda76e883ba8a5f ()
function export __wbg_stack_658279fe44541cf6 (arg0, arg1)
function export __wbg_error_f851667af71bcfc6 (arg0, arg1)
function export __wbindgen_object_drop_ref (arg0)
Variables
let wasm
const heap = new Array(128).fill(undefined)
let heap_next = heap.length
let cachedUint8Memory0 = null
let WASM_VECTOR_LEN = 0
const lTextDecoder = typeof TextDecoder === 'undefined' ? (0, module.require)('util').TextDecoder : TextDecoder
let cachedTextDecoder = new lTextDecoder('utf-8', { ignoreBOM: true, fatal: true })
const lTextEncoder = typeof TextEncoder === 'undefined' ? (0, module.require)('util').TextEncoder : TextEncoder
let cachedTextEncoder = new lTextEncoder('utf-8')
const encodeString
let cachedInt32Memory0 = null
Function Documentation
__wbg_error_f851667af71bcfc6()
function export __wbg_error_f851667af71bcfc6 (arg0, arg1)
References getStringFromWasm0(), and wasm.
__wbg_new_abda76e883ba8a5f()
function export __wbg_new_abda76e883ba8a5f ()
References addHeapObject().
__wbg_set_wasm()
function export __wbg_set_wasm (val)
References wasm.
__wbg_stack_658279fe44541cf6()
function export __wbg_stack_658279fe44541cf6 (arg0, arg1)
References getInt32Memory0(), getObject(), passStringToWasm0(), wasm, and WASM_VECTOR_LEN.
__wbindgen_object_drop_ref()
function export __wbindgen_object_drop_ref (arg0)
References takeObject().
addHeapObject()
function addHeapObject (obj)
References heap, heap_next, and obj.
bigquery_fingerprint()
function export bigquery_fingerprint (input)
Parameters
{Uint8Array} input
Returns
{bigint}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
dropObject()
function dropObject (idx)
References heap, and heap_next.
fingerprint32()
function export fingerprint32 (input)
Parameters
{Uint8Array} input
Returns
{number}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
fingerprint64()
function export fingerprint64 (input)
Parameters
{Uint8Array} input
Returns
{bigint}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
getInt32Memory0()
function getInt32Memory0 ()
References cachedInt32Memory0, and wasm.
getObject()
function getObject (idx)
References heap.
getStringFromWasm0()
function getStringFromWasm0 (ptr, len)
References cachedTextDecoder, and getUint8Memory0().
getUint8Memory0()
function getUint8Memory0 ()
References cachedUint8Memory0, Uint8Array, and wasm.
hash32()
function export hash32 (input)
Parameters
{Uint8Array} input
Returns
{number}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
hash32_with_seed()
function export hash32_with_seed (input, seed)
Parameters
{Uint8Array} input
{number} seed
Returns
{number}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
hash64()
function export hash64 (input)
Parameters
{Uint8Array} input
Returns
{bigint}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
hash64_with_seed()
function export hash64_with_seed (input, seed)
Parameters
{Uint8Array} input
{bigint} seed
Returns
{bigint}
References passArray8ToWasm0(), wasm, and WASM_VECTOR_LEN.
passArray8ToWasm0()
function passArray8ToWasm0 (arg, malloc)
References getUint8Memory0(), and WASM_VECTOR_LEN.
passStringToWasm0()
function passStringToWasm0 (arg, malloc, realloc)
References buf, cachedTextEncoder, encodeString, getUint8Memory0(), undefined, and WASM_VECTOR_LEN.
takeObject()
function takeObject (idx)
References dropObject(), and getObject().
Variable Documentation
cachedInt32Memory0
let cachedInt32Memory0 = null
cachedTextDecoder
let cachedTextDecoder = new lTextDecoder('utf-8', { ignoreBOM: true, fatal: true })
cachedTextEncoder
let cachedTextEncoder = new lTextEncoder('utf-8')
cachedUint8Memory0
let cachedUint8Memory0 = null
encodeString
const encodeString
Initial value:
= (typeof cachedTextEncoder.encodeInto === 'function'
    ? function (arg, view) {
    return cachedTextEncoder.encodeInto(arg, view);
}
    : function (arg, view) {
    const buf = cachedTextEncoder.encode(arg);
    view.set(buf);
    return {
        read: arg.length,
        written: buf.length
    };
})
heap
const heap = new Array(128).fill(undefined)
heap_next
let heap_next = heap.length
lTextDecoder
const lTextDecoder = typeof TextDecoder === 'undefined' ? (0, module.require)('util').TextDecoder : TextDecoder
lTextEncoder
const lTextEncoder = typeof TextEncoder === 'undefined' ? (0, module.require)('util').TextEncoder : TextEncoder
wasm
let wasm
WASM_VECTOR_LEN
let WASM_VECTOR_LEN = 0