backend/node_modules/gaxios/build/src/retry.js File Reference
Functions
function async getRetryConfig (err)
function shouldRetryRequest (err)
function getConfig (err)
function getNextRetryDelay (config)
Variables
use strict
exports getRetryConfig = getRetryConfig
Function Documentation
getConfig()
function getConfig (err)
Acquire the raxConfig object from an GaxiosError if available.
Parameters
err The Gaxios error with a config object.
getNextRetryDelay()
function getNextRetryDelay (config)
Gets the delay to wait before the next retry.
Parameters
{RetryConfig} config The current set of retry options
Returns
{number} the amount of ms to wait before the next retry attempt.
References _a, and config.
getRetryConfig()
function async getRetryConfig (err)
References config, delay, getConfig(), getNextRetryDelay, Promise, resolve, shouldRetryRequest(), and undefined.
shouldRetryRequest()
function shouldRetryRequest (err)
Determine based on config if we should retry the request.
Parameters
err The GaxiosError passed to the interceptor.
References _a, config, getConfig(), max, min, of, and status.
Variable Documentation
getRetryConfig
exports getRetryConfig = getRetryConfig
strict
use strict