backend/node_modules/gaxios/node_modules/uuid/dist/v35.js File Reference
Functions
function _interopRequireDefault (obj)
function stringToBytes (str)
function v35 (name, version, hashfunc)
Variables
use strict
exports URL = exports.DNS = void 0
exports default = v35
var _stringify = require("./stringify.js")
var _parse = _interopRequireDefault(require("./parse.js"))
const DNS = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
Function Documentation
_interopRequireDefault()
function _interopRequireDefault (obj)
References obj.
stringToBytes()
function stringToBytes (str)
References bytes, i, str(), and unescape().
v35()
function v35 (name, version, hashfunc)
References _stringify, buf, bytes, DNS, i, length, name, stringToBytes(), Uint8Array, URL, value, and version.
Variable Documentation
_parse
var _parse = _interopRequireDefault(require("./parse.js"))
_stringify
var _stringify = require("./stringify.js")
default
exports default = v35
DNS
exports DNS = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
strict
use strict
URL
exports URL = exports.DNS = void 0