backend/node_modules/gaxios/node_modules/uuid/dist/esm-browser/v35.js File Reference
Functions
function stringToBytes (str)
function default v35 (name, version, hashfunc)
Variables
import { unsafeStringify } from './stringify.js'
import parse from parse js
export const DNS = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
export const URL = '6ba7b811-9dad-11d1-80b4-00c04fd430c8'
Function Documentation
stringToBytes()
function stringToBytes (str)
References bytes, i, str(), and unescape().
v35()
function default v35 (name, version, hashfunc)
References buf, bytes, DNS, i, length, name, stringToBytes(), Uint8Array, unsafeStringify, URL, value, and version.
Variable Documentation
DNS
export const DNS = '6ba7b810-9dad-11d1-80b4-00c04fd430c8'
import
import { unsafeStringify } from './stringify.js'
js
import parse from parse js
URL
export const URL = '6ba7b811-9dad-11d1-80b4-00c04fd430c8'