backend/node_modules/gcp-metadata/build/src/index.js File Reference
Functions
function getBaseUrl (baseUrl)
function validate (options)
function async metadataAccessor (type, options={}, noResponseRetries=3, fastFail=false)
function async fastFailMetadataRequest (options)
function instance (options)
function project (options)
function universe (options)
function async bulk (properties)
function detectGCPAvailableRetries ()
function setGCPResidency (value=null)
Variables
use strict
var __createBinding
var __exportStar
exports requestTimeout = exports.setGCPResidency = exports.getGCPResidency = exports.gcpResidencyCache = exports.resetIsAvailableCache = exports.isAvailable = exports.bulk = exports.universe = exports.project = exports.instance = exports.METADATA_SERVER_DETECTION = exports.HEADERS = exports.HEADER_VALUE = exports.HEADER_NAME = exports.SECONDARY_HOST_ADDRESS = exports.HOST_ADDRESS = exports.BASE_PATH = void 0
const gaxios_1 = require("gaxios")
const jsonBigint = require("json-bigint")
const gcp_residency_1 = require("./gcp-residency")
exports BASE_PATH = '/computeMetadata/v1'
exports HOST_ADDRESS
exports HEADER_VALUE = 'Google'
exports HEADERS = Object.freeze({ [exports.HEADER_NAME]: exports.HEADER_VALUE })
exports METADATA_SERVER_DETECTION
exports instance = instance
exports project = project
exports universe = universe
exports bulk = bulk
let cachedIsAvailableResponse
exports isAvailable = isAvailable
exports resetIsAvailableCache = resetIsAvailableCache
exports gcpResidencyCache = null
exports getGCPResidency = getGCPResidency
exports setGCPResidency = setGCPResidency
Function Documentation
bulk()
function async bulk (properties)
References Promise, and r.
detectGCPAvailableRetries()
function detectGCPAvailableRetries ()
References process.
fastFailMetadataRequest()
function async fastFailMetadataRequest (options)
References exports, gaxios_1, getBaseUrl(), Promise, res, and url.
getBaseUrl()
function getBaseUrl (baseUrl)
Returns the base URL while taking into account the GCE_METADATA_HOST environment variable if it exists.
Returns
The base URL, e.g., http://169.254.169.254/computeMetadata/v1.
References exports, http, https, and process.
instance()
function instance (options)
References metadataAccessor().
metadataAccessor()
function async metadataAccessor (type, options = {}, noResponseRetries = 3, fastFail = false)
project()
function project (options)
References metadataAccessor().
setGCPResidency()
function setGCPResidency (value = null)
Sets the detected GCP Residency. Useful for forcing metadata server detection behavior.
Set null to autodetect the environment (default behavior).
See also
getGCPResidency for getting
References exports, gcp_residency_1, and value.
universe()
function universe (options)
References metadataAccessor().
validate()
function validate (options)
References a, is, and not.
Variable Documentation
__createBinding
var __createBinding
Initial value:
= (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}))
Copyright 2018 Google LLC
Distributed under MIT license. See file LICENSE for detail or copy at https://opensource.org/licenses/MIT
__exportStar
var __exportStar
Initial value:
= (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
}
BASE_PATH
exports BASE_PATH = '/computeMetadata/v1'
bulk
exports bulk = bulk
cachedIsAvailableResponse
let cachedIsAvailableResponse
gaxios_1
const gaxios_1 = require("gaxios")
gcp_residency_1
const gcp_residency_1 = require("./gcp-residency")
gcpResidencyCache
exports gcpResidencyCache = null
A cache for the detected GCP Residency.
getGCPResidency
function getGCPResidency () = getGCPResidency
Detects GCP Residency. Caches results to reduce costs for subsequent calls.
See also
setGCPResidency for setting
HEADER_VALUE
exports HEADER_VALUE = 'Google'
HEADERS
exports HEADERS = Object.freeze({ [exports.HEADER_NAME]: exports.HEADER_VALUE })
HOST_ADDRESS
exports HOST_ADDRESS
Initial value:
= 'http:
exports.SECONDARY_HOST_ADDRESS = 'http:
exports.HEADER_NAME = 'Metadata-Flavor'
instance
exports instance = instance
isAvailable
function async isAvailable () = isAvailable
Determine if the metadata server is currently available.
jsonBigint
const jsonBigint = require("json-bigint")
METADATA_SERVER_DETECTION
exports METADATA_SERVER_DETECTION
Initial value:
= Object.freeze({
    'assume-present': "don't try to ping the metadata server, but assume it's present",
    none: "don't try to ping the metadata server, but don't try to use it either",
    'bios-only': "treat the result of a BIOS probe as canonical (don't fall back to pinging)",
    'ping-only': 'skip the BIOS probe, and go straight to pinging',
})
Metadata server detection override options.
Available via process.env.METADATA_SERVER_DETECTION.
project
exports project = project
requestTimeout
exports requestTimeout () = exports.setGCPResidency = exports.getGCPResidency = exports.gcpResidencyCache = exports.resetIsAvailableCache = exports.isAvailable = exports.bulk = exports.universe = exports.project = exports.instance = exports.METADATA_SERVER_DETECTION = exports.HEADERS = exports.HEADER_VALUE = exports.HEADER_NAME = exports.SECONDARY_HOST_ADDRESS = exports.HOST_ADDRESS = exports.BASE_PATH = void 0
Obtain the timeout for requests to the metadata server.
In certain environments and conditions requests can take longer than the default timeout to complete. This function will determine the appropriate timeout based on the environment.
Returns
{number} a request timeout duration in milliseconds.
resetIsAvailableCache
function resetIsAvailableCache () = resetIsAvailableCache
reset the memoized isAvailable() lookup.
setGCPResidency
exports setGCPResidency = setGCPResidency
strict
use strict
universe
exports universe = universe