backend/node_modules/google-gax/build/src/util.js File Reference
Functions
function words (str, normalize=false)
function lowercase (str)
function camelToSnakeCase (str)
function capitalize (str)
function toCamelCase (str)
function toLowerCamelCase (str)
Variables
use strict
exports camelToSnakeCase = camelToSnakeCase
exports toCamelCase = toCamelCase
exports toLowerCamelCase = toLowerCamelCase
exports makeUUID = makeUUID
const uuid_1 = require("uuid")
Function Documentation
camelToSnakeCase()
function camelToSnakeCase (str)
Converts a given string from camelCase (used by protobuf.js and in JSON) to snake_case (normally used in proto definitions).
References lowercase(), result, str(), and words.
capitalize()
function capitalize (str)
Capitalizes the first character of the given string.
References str().
lowercase()
function lowercase (str)
Converts the first character of the given string to lower case.
References str().
toCamelCase()
function toCamelCase (str)
Converts a given string from snake_case (normally used in proto definitions) or PascalCase (also used in proto definitions) to camelCase (used by protobuf.js). Preserves capitalization of the first character.
References capitalize, result, str(), w, and words.
toLowerCamelCase()
function toLowerCamelCase (str)
Converts a given string to lower camel case (forcing the first character to be in lower case).
References camelCase, str(), and toCamelCase.
words()
function words (str, normalize = false)
References g, index, normalize, str(), w, and Z().
Variable Documentation
camelToSnakeCase
exports camelToSnakeCase = camelToSnakeCase
makeUUID
function makeUUID () = makeUUID
Converts a given string to lower camel case (forcing the first character to be in lower case).
strict
use strict
toCamelCase
exports toCamelCase = toCamelCase
toLowerCamelCase
exports toLowerCamelCase = toLowerCamelCase
uuid_1
const uuid_1 = require("uuid")
Copyright 2020 Google LLC
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.