backend/node_modules/google-gax/build/src/grpc.js File Reference
Classes
class ClientStub
class GrpcClient
class GoogleProtoFilesRoot
Functions
function async readFileAsync (path)
function async execFileAsync (command, args)
Variables
use strict
exports GoogleProtoFilesRoot = exports.GrpcClient = exports.ClientStub = void 0
const grpcProtoLoader = require("@grpc/proto-loader")
const child_process_1 = require("child_process")
const fs = require("fs")
const google_auth_library_1 = require("google-auth-library")
const grpc = require("@grpc/grpc-js")
const os = require("os")
const path_1 = require("path")
const path = require("path")
const protobuf = require("protobufjs")
const objectHash = require("object-hash")
const gax = require("./gax")
const googleProtoFilesDir = path.join(__dirname, '..', '..', 'build', 'protos')
const INCLUDE_DIRS = []
const commonProtoFiles = require("./protosList.json")
const COMMON_PROTO_FILES = commonProtoFiles.map(file => file.replace(/[/\\]/g, path.sep))
exports ClientStub = ClientStub
exports GrpcClient = GrpcClient
GrpcClient protoCache = new Map()
Function Documentation
execFileAsync()
function async execFileAsync (command, args)
References args, child_process_1, command(), Promise, reject(), and resolve.
readFileAsync()
function async readFileAsync (path)
References fs, path, Promise, reject(), and resolve.
Variable Documentation
child_process_1
const child_process_1 = require("child_process")
ClientStub
exports ClientStub = ClientStub
COMMON_PROTO_FILES
const COMMON_PROTO_FILES = commonProtoFiles.map(file => file.replace(/[/\\]/g, path.sep))
commonProtoFiles
const commonProtoFiles = require("./protosList.json")
fs
const fs = require("fs")
gax
const gax = require("./gax")
google_auth_library_1
const google_auth_library_1 = require("google-auth-library")
googleProtoFilesDir
const googleProtoFilesDir = path.join(__dirname, '..', '..', 'build', 'protos')
GoogleProtoFilesRoot
exports GoogleProtoFilesRoot = exports.GrpcClient = exports.ClientStub = void 0
grpc
exports grpc = require("@grpc/grpc-js")
GrpcClient
exports GrpcClient = GrpcClient
grpcProtoLoader
const grpcProtoLoader = require("@grpc/proto-loader")
INCLUDE_DIRS
const INCLUDE_DIRS = []
objectHash
const objectHash = require("object-hash")
os
const os = require("os")
path
const path = require("path")
path_1
const path_1 = require("path")
protobuf
const protobuf = require("protobufjs")
protoCache
GrpcClient protoCache = new Map()
strict
use strict