backend/node_modules/@grpc/grpc-js/build/src/http_proxy.js File Reference
Functions
function trace (text)
function getProxyInfo ()
function getNoProxyHostList ()
function mapProxyName (target, options)
function getProxiedConnection (address, channelOptions, connectionOptions)
Variables
use strict
exports getProxiedConnection = exports.mapProxyName = void 0
const logging_1 = require("./logging")
const constants_1 = require("./constants")
const resolver_1 = require("./resolver")
const http = require("http")
const tls = require("tls")
const logging = require("./logging")
const subchannel_address_1 = require("./subchannel-address")
const uri_parser_1 = require("./uri-parser")
const url_1 = require("url")
const resolver_dns_1 = require("./resolver-dns")
const TRACER_NAME = 'proxy'
exports mapProxyName = mapProxyName
Function Documentation
getNoProxyHostList()
function getNoProxyHostList ()
References process, and trace.
getProxiedConnection()
function getProxiedConnection (address, channelOptions, connectionOptions)
References $, _a, constants_1, error, head, headers, http, logging_1, method, path, Promise, reject(), request, res, resolve, resolver_1, resolver_dns_1, subchannel_address_1, tls, trace, and uri_parser_1.
getProxyInfo()
function getProxyInfo ()
References $, constants_1, e, env, logging_1, not, of, parse, process, proxy, result, trace, url_1, and value.
mapProxyName()
function mapProxyName (target, options)
References _a, getNoProxyHostList(), getProxyInfo(), of, path, trace, and uri_parser_1.
trace()
function trace (text)
References constants_1, logging, text, and TRACER_NAME.
Variable Documentation
constants_1
const constants_1 = require("./constants")
getProxiedConnection
exports getProxiedConnection = exports.mapProxyName = void 0
http
const http = require("http")
logging
const logging = require("./logging")
logging_1
const logging_1 = require("./logging")
mapProxyName
exports mapProxyName = mapProxyName
resolver_1
const resolver_1 = require("./resolver")
resolver_dns_1
const resolver_dns_1 = require("./resolver-dns")
strict
use strict
subchannel_address_1
const subchannel_address_1 = require("./subchannel-address")
tls
const tls = require("tls")
TRACER_NAME
const TRACER_NAME = 'proxy'
uri_parser_1
const uri_parser_1 = require("./uri-parser")
url_1
const url_1 = require("url")