backend/node_modules/jose/dist/browser/runtime/asn1.js File Reference
Functions
function getElement (seq)
function parseElement (bytes)
function spkiFromX509 (buf)
function getSPKI (x509)
Variables
import crypto
import import invalidKeyInput from lib invalid_key_input js { isCryptoKey } from './webcrypto.js'
import { encodeBase64, decodeBase64 } from './base64url.js'
const genericExport
export const toSPKI
export const toPKCS8
const findOid
const getNamedCurve
const genericImport
export const fromPKCS8
export const fromSPKI
export const fromX509
Function Documentation
getElement()
function getElement (seq)
References next(), parseElement(), and result.
getSPKI()
function getSPKI (x509)
References decodeBase64, g, pem, raw, s, and spkiFromX509().
parseElement()
function parseElement (bytes)
References bytes, i, length, and raw.
spkiFromX509()
function spkiFromX509 (buf)
References buf, encodeBase64, getElement(), parseElement(), and raw.
Variable Documentation
crypto
import crypto
findOid
const findOid
Initial value:
= (keyData, oid, from = 0) => {
    if (from === 0) {
        oid.unshift(oid.length);
        oid.unshift(0x06);
    }
    let i = keyData.indexOf(oid[0], from);
    if (i === -1)
        return false;
    const sub = keyData.subarray(i, i + oid.length);
    if (sub.length !== oid.length)
        return false;
    return sub.every((value, index) => value === oid[index]) || findOid(keyData, oid, i + 1);
}
fromPKCS8
export const fromPKCS8
Initial value:
= (pem, alg, options) => {
    return genericImport(/(?:-----(?:BEGIN|END) PRIVATE KEY-----|\s)/g, 'pkcs8', pem, alg, options);
}
fromSPKI
export const fromSPKI
Initial value:
= (pem, alg, options) => {
    return genericImport(/(?:-----(?:BEGIN|END) PUBLIC KEY-----|\s)/g, 'spki', pem, alg, options);
}
fromX509
export const fromX509
Initial value:
= (pem, alg, options) => {
    let spki;
    try {
        spki = getSPKI(pem);
    }
    catch (cause) {
        throw new TypeError('Failed to parse the X.509 certificate', { cause });
    }
    return fromSPKI(spki, alg, options);
}
genericExport
const genericExport
Initial value:
= async (keyType, keyFormat, key) => {
    if (!isCryptoKey(key)) {
        throw new TypeError(invalidKeyInput(key, ...types));
    }
    if (!key.extractable) {
        throw new TypeError('CryptoKey is not extractable');
    }
    if (key.type !== keyType) {
        throw new TypeError(key is not a ${keyType} key);
    }
    return formatPEM(encodeBase64(new Uint8Array(await crypto.subtle.exportKey(keyFormat, key))), ${keyType.toUpperCase()} KEY);
}
genericImport
const genericImport
getNamedCurve
export default getNamedCurve
Initial value:
= (keyData) => {
    switch (true) {
        case findOid(keyData, [0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07]):
            return 'P-256';
        case findOid(keyData, [0x2b, 0x81, 0x04, 0x00, 0x22]):
            return 'P-384';
        case findOid(keyData, [0x2b, 0x81, 0x04, 0x00, 0x23]):
            return 'P-521';
        case findOid(keyData, [0x2b, 0x65, 0x6e]):
            return 'X25519';
        case findOid(keyData, [0x2b, 0x65, 0x6f]):
            return 'X448';
        case findOid(keyData, [0x2b, 0x65, 0x70]):
            return 'Ed25519';
        case findOid(keyData, [0x2b, 0x65, 0x71]):
            return 'Ed448';
        default:
            throw new JOSENotSupported('Invalid or unsupported EC Key Curve or OKP Key Sub Type');
    }
}
import
import { encodeBase64, decodeBase64 } from './base64url.js'
js
import formatPEM from lib format_pem js { isCryptoKey } from './webcrypto.js'
toPKCS8
exports toPKCS8
Initial value:
= (key) => {
    return genericExport('private', 'pkcs8', key);
}
toSPKI
exports toSPKI
Initial value:
= (key) => {
    return genericExport('public', 'spki', key);
}