backend/node_modules/jose/dist/browser/runtime/generate.js File Reference
Functions
function async generateSecret (alg, options)
function getModulusLengthOption (options)
function async generateKeyPair (alg, options)
Variables
import crypto from webcrypto js
import { JOSENotSupported } from '../util/errors.js'
Function Documentation
generateKeyPair()
function async generateKeyPair (alg, options)
References $, _a, _b, _c, crypto, getModulusLengthOption(), hash(), JOSENotSupported, name, parseInt(), and Uint8Array.
generateSecret()
function async generateSecret (alg, options)
References $, _a, crypto, hash(), JOSENotSupported, length, name, parseInt(), random(), and Uint8Array.
getModulusLengthOption()
function getModulusLengthOption (options)
References _a, and JOSENotSupported.
Variable Documentation
import
import { JOSENotSupported } from '../util/errors.js'
js
import random from random js