backend/node_modules/node-forge/lib/jsbn.js File Reference
Functions
function BigInteger (a, b, c)
function nbi ()
function am1 (i, x, w, j, c, n)
function am2 (i, x, w, j, c, n)
function am3 (i, x, w, j, c, n)
if (typeof(navigator)==='undefined')
else if (j_lm &&(navigator.appName=="Microsoft Internet Explorer"))
else if (j_lm &&(navigator.appName !="Netscape"))
function int2char (n)
function intAt (s, i)
function bnpCopyTo (r)
function bnpFromInt (x)
function nbv (i)
function bnpFromString (s, b)
function bnpClamp ()
function bnToString (b)
function bnNegate ()
function bnAbs ()
function bnCompareTo (a)
function nbits (x)
function bnBitLength ()
function bnpDLShiftTo (n, r)
function bnpDRShiftTo (n, r)
function bnpLShiftTo (n, r)
function bnpRShiftTo (n, r)
function bnpSubTo (a, r)
function bnpMultiplyTo (a, r)
function bnpSquareTo (r)
function bnpDivRemTo (m, q, r)
function bnMod (a)
function Classic (m)
function cConvert (x)
function cRevert (x)
function cReduce (x)
function cMulTo (x, y, r)
function cSqrTo (x, r)
function bnpInvDigit ()
function Montgomery (m)
function montConvert (x)
function montRevert (x)
function montReduce (x)
function montSqrTo (x, r)
function montMulTo (x, y, r)
function bnpIsEven ()
function bnpExp (e, z)
function bnModPowInt (e, m)
function bnClone ()
function bnIntValue ()
function bnByteValue ()
function bnShortValue ()
function bnpChunkSize (r)
function bnSigNum ()
function bnpToRadix (b)
function bnpFromRadix (s, b)
function bnpFromNumber (a, b, c)
function bnToByteArray ()
function bnEquals (a)
function bnMin (a)
function bnMax (a)
function bnpBitwiseTo (a, op, r)
function op_and (x, y)
function bnAnd (a)
function op_or (x, y)
function bnOr (a)
function op_xor (x, y)
function bnXor (a)
function op_andnot (x, y)
function bnAndNot (a)
function bnNot ()
function bnShiftLeft (n)
function bnShiftRight (n)
function lbit (x)
function bnGetLowestSetBit ()
function cbit (x)
function bnBitCount ()
function bnTestBit (n)
function bnpChangeBit (n, op)
function bnSetBit (n)
function bnClearBit (n)
function bnFlipBit (n)
function bnpAddTo (a, r)
function bnAdd (a)
function bnSubtract (a)
function bnMultiply (a)
function bnDivide (a)
function bnRemainder (a)
function bnDivideAndRemainder (a)
function bnpDMultiply (n)
function bnpDAddOffset (n, w)
function NullExp ()
function nNop (x)
function nMulTo (x, y, r)
function nSqrTo (x, r)
function bnPow (e)
function bnpMultiplyLowerTo (a, n, r)
function bnpMultiplyUpperTo (a, n, r)
function Barrett (m)
function barrettConvert (x)
function barrettRevert (x)
function barrettReduce (x)
function barrettSqrTo (x, r)
function barrettMulTo (x, y, r)
function bnModPow (e, m)
function bnGCD (a)
function bnpModInt (n)
function bnModInverse (m)
function bnIsProbablePrime (t)
function bnpMillerRabin (t)
function bnGetPrng ()
Variables
var forge = require('./forge')
module exports = forge.jsbn = forge.jsbn || {}
var dbits = 28
var canary = 0xdeadbeefcafe
var j_lm = ((canary&0xffffff)==0xefcafe)
forge jsbn BigInteger = BigInteger
else
BigInteger prototype DB = dbits
BigInteger prototype DM = ((1<<dbits)-1)
BigInteger prototype DV = (1<<dbits)
var BI_FP = 52
BigInteger prototype FV = Math.pow(2,BI_FP)
BigInteger prototype F1 = BI_FP-dbits
BigInteger prototype F2 = 2*dbits-BI_FP
var BI_RM = "0123456789abcdefghijklmnopqrstuvwxyz"
var BI_RC = new Array()
var rr = "0".charCodeAt(0)
var vv
Classic prototype convert = cConvert
Classic prototype revert = cRevert
Classic prototype reduce = cReduce
Classic prototype mulTo = cMulTo
Classic prototype sqrTo = cSqrTo
BigInteger prototype copyTo = bnpCopyTo
BigInteger prototype fromInt = bnpFromInt
BigInteger prototype fromString = bnpFromString
BigInteger prototype clamp = bnpClamp
BigInteger prototype dlShiftTo = bnpDLShiftTo
BigInteger prototype drShiftTo = bnpDRShiftTo
BigInteger prototype lShiftTo = bnpLShiftTo
BigInteger prototype rShiftTo = bnpRShiftTo
BigInteger prototype subTo = bnpSubTo
BigInteger prototype multiplyTo = bnpMultiplyTo
BigInteger prototype squareTo = bnpSquareTo
BigInteger prototype divRemTo = bnpDivRemTo
BigInteger prototype invDigit = bnpInvDigit
BigInteger prototype isEven = bnpIsEven
BigInteger prototype exp = bnpExp
BigInteger prototype toString = bnToString
BigInteger prototype negate = bnNegate
BigInteger prototype abs = bnAbs
BigInteger prototype compareTo = bnCompareTo
BigInteger prototype bitLength = bnBitLength
BigInteger prototype mod = bnMod
BigInteger prototype modPowInt = bnModPowInt
BigInteger ZERO = nbv(0)
BigInteger ONE = nbv(1)
var lowprimes = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509]
var lplim = (1<<26)/lowprimes[lowprimes.length-1]
BigInteger prototype chunkSize = bnpChunkSize
BigInteger prototype toRadix = bnpToRadix
BigInteger prototype fromRadix = bnpFromRadix
BigInteger prototype fromNumber = bnpFromNumber
BigInteger prototype bitwiseTo = bnpBitwiseTo
BigInteger prototype changeBit = bnpChangeBit
BigInteger prototype addTo = bnpAddTo
BigInteger prototype dMultiply = bnpDMultiply
BigInteger prototype dAddOffset = bnpDAddOffset
BigInteger prototype multiplyLowerTo = bnpMultiplyLowerTo
BigInteger prototype multiplyUpperTo = bnpMultiplyUpperTo
BigInteger prototype modInt = bnpModInt
BigInteger prototype millerRabin = bnpMillerRabin
BigInteger prototype clone = bnClone
BigInteger prototype intValue = bnIntValue
BigInteger prototype byteValue = bnByteValue
BigInteger prototype shortValue = bnShortValue
BigInteger prototype signum = bnSigNum
BigInteger prototype toByteArray = bnToByteArray
BigInteger prototype equals = bnEquals
BigInteger prototype min = bnMin
BigInteger prototype max = bnMax
BigInteger prototype and = bnAnd
BigInteger prototype or = bnOr
BigInteger prototype xor = bnXor
BigInteger prototype andNot = bnAndNot
BigInteger prototype not = bnNot
BigInteger prototype shiftLeft = bnShiftLeft
BigInteger prototype shiftRight = bnShiftRight
BigInteger prototype getLowestSetBit = bnGetLowestSetBit
BigInteger prototype bitCount = bnBitCount
BigInteger prototype testBit = bnTestBit
BigInteger prototype setBit = bnSetBit
BigInteger prototype clearBit = bnClearBit
BigInteger prototype flipBit = bnFlipBit
BigInteger prototype add = bnAdd
BigInteger prototype subtract = bnSubtract
BigInteger prototype multiply = bnMultiply
BigInteger prototype divide = bnDivide
BigInteger prototype remainder = bnRemainder
BigInteger prototype divideAndRemainder = bnDivideAndRemainder
BigInteger prototype modPow = bnModPow
BigInteger prototype modInverse = bnModInverse
BigInteger prototype pow = bnPow
BigInteger prototype gcd = bnGCD
BigInteger prototype isProbablePrime = bnIsProbablePrime
Function Documentation
am1()
function am1 (i, x, w, j, c, n)
References c, data, i, j, n, v, and w.
am2()
function am2 (i, x, w, j, c, n)
References c, data, h, i, j, l, m, n, and w.
am3()
function am3 (i, x, w, j, c, n)
References c, data, h, i, j, l, m, n, and w.
Barrett()
function Barrett (m)
References BigInteger, m, and nbi().
barrettConvert()
function barrettConvert (x)
References m, nbi(), r, and reduce.
barrettMulTo()
function barrettMulTo (x, y, r)
References r, reduce, and y.
barrettReduce()
function barrettReduce (x)
References m.
barrettRevert()
function barrettRevert (x)
barrettSqrTo()
function barrettSqrTo (x, r)
References r, and reduce.
BigInteger()
function BigInteger (a, b, c)
References a, b, c, data, fromNumber, and fromString.
bnAbs()
function bnAbs ()
References negate, and s.
bnAdd()
function bnAdd (a)
References a, addTo, nbi(), and r.
bnAnd()
function bnAnd (a)
References a, bitwiseTo, nbi(), op_and(), and r.
bnAndNot()
function bnAndNot (a)
References a, bitwiseTo, nbi(), op_andnot(), and r.
bnBitCount()
function bnBitCount ()
References cbit(), data, DM, i, r, s, and t.
bnBitLength()
function bnBitLength ()
References data, DB, DM, nbits(), s, and t.
bnByteValue()
function bnByteValue ()
References data, s, and t.
bnClearBit()
function bnClearBit (n)
References changeBit, n, and op_andnot().
bnClone()
function bnClone ()
References copyTo, nbi(), and r.
bnCompareTo()
function bnCompareTo (a)
References a, data, i, r, s, and t.
bnDivide()
function bnDivide (a)
References a, divRemTo, nbi(), and r.
bnDivideAndRemainder()
function bnDivideAndRemainder (a)
References a, Array, divRemTo, nbi(), q, and r.
bnEquals()
function bnEquals (a)
References a, and compareTo.
bnFlipBit()
function bnFlipBit (n)
References changeBit, n, and op_xor().
bnGCD()
function bnGCD (a)
References a, clone, g, i, negate, s, t, and y.
bnGetLowestSetBit()
function bnGetLowestSetBit ()
References data, DB, i, lbit(), s, and t.
bnGetPrng()
function bnGetPrng ()
References i.
bnIntValue()
function bnIntValue ()
References data, DB, DV, s, and t.
bnIsProbablePrime()
function bnIsProbablePrime (t)
References abs, i, j, lowprimes, lplim, m, and t.
bnMax()
function bnMax (a)
References a, and compareTo.
bnMin()
function bnMin (a)
References a, and compareTo.
bnMod()
function bnMod (a)
References a, abs, BigInteger, nbi(), r, and s.
bnModInverse()
function bnModInverse (m)
References a, b, BigInteger, c, clone, d, isEven, m, nbv(), u, and v.
bnModPow()
function bnModPow (e, m)
References Array, Barrett(), Classic(), DB, e, g, i, j, k, m, Montgomery(), n, nbi(), nbits(), nbv(), r, t, and w.
bnModPowInt()
function bnModPowInt (e, m)
References Classic(), e, exp, m, and Montgomery().
bnMultiply()
function bnMultiply (a)
References a, multiplyTo, nbi(), and r.
bnNegate()
function bnNegate ()
References BigInteger, nbi(), and r.
bnNot()
function bnNot ()
References i, nbi(), r, and t.
bnOr()
function bnOr (a)
References a, bitwiseTo, nbi(), op_or, and r.
bnpAddTo()
function bnpAddTo (a, r)
References a, c, data, DB, DM, DV, i, m, r, s, and t.
bnpBitwiseTo()
function bnpBitwiseTo (a, op, r)
References a, data, DM, f, i, m, r, s, and t.
bnpChangeBit()
function bnpChangeBit (n, op)
References BigInteger, bitwiseTo, n, and r.
bnpChunkSize()
function bnpChunkSize (r)
References r.
bnpClamp()
function bnpClamp ()
References c, data, DM, s, and t.
bnpCopyTo()
function bnpCopyTo (r)
References i, r, s, and t.
bnpDAddOffset()
function bnpDAddOffset (n, w)
References data, DV, n, t, and w.
bnpDivRemTo()
function bnpDivRemTo (m, q, r)
References abs, BigInteger, copyTo, DB, DM, e, F1, F2, FV, i, j, m, ms, nbi(), nbits(), pt, q, r, s, t, y, and yt.
bnpDLShiftTo()
function bnpDLShiftTo (n, r)
References i, n, r, s, and t.
bnpDMultiply()
function bnpDMultiply (n)
References clamp, data, n, and t.
bnpDRShiftTo()
function bnpDRShiftTo (n, r)
References i, n, r, s, and t.
bnpExp()
function bnpExp (e, z)
References BigInteger, e, g, i, nbi(), nbits(), r, and t.
bnpFromInt()
function bnpFromInt (x)
References data, DV, s, and t.
bnpFromNumber()
function bnpFromNumber (a, b, c)
References a, Array, b, BigInteger, bitLength, bitwiseTo, c, dAddOffset, fromInt, fromNumber, fromString, isEven, isProbablePrime, op_or, subTo, t, and testBit.
bnpFromRadix()
function bnpFromRadix (s, b)
References b, BigInteger, chunkSize, d, dAddOffset, dMultiply, fromInt, i, intAt(), j, s, and w.
bnpFromString()
function bnpFromString (s, b)
References b, BigInteger, clamp, data, DB, fromRadix, i, intAt(), k, s, and t.
bnpInvDigit()
function bnpInvDigit ()
References data, DV, t, and y.
bnpIsEven()
function bnpIsEven ()
References data, s, and t.
bnpLShiftTo()
function bnpLShiftTo (n, r)
References c, data, DB, DM, i, n, r, s, and t.
bnpMillerRabin()
function bnpMillerRabin (t)
References a, BigInteger, bitLength, bnGetPrng(), i, j, k, prng, r, subtract, t, and y.
bnpModInt()
function bnpModInt (n)
References d, data, DV, i, n, r, s, and t.
bnpMultiplyLowerTo()
function bnpMultiplyLowerTo (a, n, r)
References a, i, j, n, r, and t.
bnpMultiplyTo()
function bnpMultiplyTo (a, r)
References a, abs, BigInteger, i, r, s, and y.
bnpMultiplyUpperTo()
function bnpMultiplyUpperTo (a, n, r)
References a, i, n, r, and t.
bnPow()
function bnPow (e)
References e, exp, and NullExp().
bnpRShiftTo()
function bnpRShiftTo (n, r)
References data, DB, i, n, r, s, and t.
bnpSquareTo()
function bnpSquareTo (r)
References abs, c, i, and r.
bnpSubTo()
function bnpSubTo (a, r)
References a, c, data, DB, DM, DV, i, m, r, s, and t.
bnpToRadix()
function bnpToRadix (b)
References a, b, chunkSize, d, divRemTo, nbi(), nbv(), r, signum, and y.
bnRemainder()
function bnRemainder (a)
References a, divRemTo, nbi(), and r.
bnSetBit()
function bnSetBit (n)
References changeBit, n, and op_or.
bnShiftLeft()
function bnShiftLeft (n)
References lShiftTo, n, nbi(), r, and rShiftTo.
bnShiftRight()
function bnShiftRight (n)
References lShiftTo, n, nbi(), r, and rShiftTo.
bnShortValue()
function bnShortValue ()
References data, s, and t.
bnSigNum()
function bnSigNum ()
References data, s, and t.
bnSubtract()
function bnSubtract (a)
References a, nbi(), r, and subTo.
bnTestBit()
function bnTestBit (n)
References data, DB, j, n, s, and t.
bnToByteArray()
function bnToByteArray ()
References Array, d, data, DB, DM, i, k, p, r, s, and t.
bnToString()
function bnToString (b)
References b, d, data, DB, i, int2char(), k, m, negate, p, r, s, t, and toRadix.
bnXor()
function bnXor (a)
References a, bitwiseTo, nbi(), op_xor(), and r.
cbit()
function cbit (x)
References r.
cConvert()
function cConvert (x)
References m.
Classic()
function Classic (m)
References m.
cMulTo()
function cMulTo (x, y, r)
References r, reduce, and y.
cReduce()
function cReduce (x)
References m.
cRevert()
function cRevert (x)
cSqrTo()
function cSqrTo (x, r)
References r, and reduce.
if() [1/3]
else if (j_lm &&navigator.appName !="Netscape")
if() [2/3]
else if (j_lm &&navigator.appName=="Microsoft Internet Explorer")
if() [3/3]
if (typeof(navigator) = == 'undefined')
References am3(), BigInteger, and dbits.
int2char()
function int2char (n)
References BI_RM, and n.
intAt()
function intAt (s, i)
References BI_RC, c, i, and s.
lbit()
function lbit (x)
References r.
montConvert()
function montConvert (x)
References BigInteger, m, nbi(), and r.
Montgomery()
function Montgomery (m)
References m.
montMulTo()
function montMulTo (x, y, r)
References r, reduce, and y.
montReduce()
function montReduce (x)
References i, j, and m.
montRevert()
function montRevert (x)
References nbi(), r, and reduce.
montSqrTo()
function montSqrTo (x, r)
References r, and reduce.
nbi()
function nbi ()
References BigInteger.
nbits()
function nbits (x)
References r, and t.
nbv()
function nbv (i)
References i, nbi(), and r.
nMulTo()
function nMulTo (x, y, r)
References r, and y.
nNop()
function nNop (x)
nSqrTo()
function nSqrTo (x, r)
References r.
NullExp()
function NullExp ()
op_and()
function op_and (x, y)
References y.
op_andnot()
function op_andnot (x, y)
op_or()
function op_or (x, y)
References y.
op_xor()
function op_xor (x, y)
References y.
Variable Documentation
abs
BigInteger prototype abs = bnAbs
add
BigInteger prototype add = bnAdd
addTo
BigInteger prototype addTo = bnpAddTo
and
BigInteger prototype and = bnAnd
andNot
BigInteger prototype andNot = bnAndNot
BI_FP
var BI_FP = 52
BI_RC
var BI_RC = new Array()
BI_RM
var BI_RM = "0123456789abcdefghijklmnopqrstuvwxyz"
BigInteger
forge jsbn BigInteger = BigInteger
bitCount
BigInteger prototype bitCount = bnBitCount
bitLength
BigInteger prototype bitLength = bnBitLength
bitwiseTo
BigInteger prototype bitwiseTo = bnpBitwiseTo
byteValue
BigInteger prototype byteValue = bnByteValue
canary
var canary = 0xdeadbeefcafe
changeBit
BigInteger prototype changeBit = bnpChangeBit
chunkSize
BigInteger prototype chunkSize = bnpChunkSize
clamp
BigInteger prototype clamp = bnpClamp
clearBit
BigInteger prototype clearBit = bnClearBit
clone
BigInteger prototype clone = bnClone
compareTo
BigInteger prototype compareTo = bnCompareTo
convert
Barrett prototype convert = cConvert
copyTo
BigInteger prototype copyTo = bnpCopyTo
dAddOffset
BigInteger prototype dAddOffset = bnpDAddOffset
DB
BigInteger prototype DB = dbits
dbits
dbits = 28
divide
BigInteger prototype divide = bnDivide
divideAndRemainder
BigInteger prototype divideAndRemainder = bnDivideAndRemainder
divRemTo
BigInteger prototype divRemTo = bnpDivRemTo
dlShiftTo
BigInteger prototype dlShiftTo = bnpDLShiftTo
DM
BigInteger prototype DM = ((1<<dbits)-1)
dMultiply
BigInteger prototype dMultiply = bnpDMultiply
drShiftTo
BigInteger prototype drShiftTo = bnpDRShiftTo
DV
BigInteger prototype DV = (1<<dbits)
else
else
Initial value:
{
  BigInteger.prototype.am = am3
equals
BigInteger prototype equals = bnEquals
exp
BigInteger prototype exp = bnpExp
exports
module exports = forge.jsbn = forge.jsbn || {}
F1
BigInteger prototype F1 = BI_FP-dbits
F2
BigInteger prototype F2 = 2*dbits-BI_FP
flipBit
BigInteger prototype flipBit = bnFlipBit
forge
var forge = require('./forge')
fromInt
BigInteger prototype fromInt = bnpFromInt
fromNumber
BigInteger prototype fromNumber = bnpFromNumber
fromRadix
BigInteger prototype fromRadix = bnpFromRadix
fromString
BigInteger prototype fromString = bnpFromString
FV
BigInteger prototype FV = Math.pow(2,BI_FP)
gcd
BigInteger prototype gcd = bnGCD
getLowestSetBit
BigInteger prototype getLowestSetBit = bnGetLowestSetBit
intValue
BigInteger prototype intValue = bnIntValue
invDigit
BigInteger prototype invDigit = bnpInvDigit
isEven
BigInteger prototype isEven = bnpIsEven
isProbablePrime
BigInteger prototype isProbablePrime = bnIsProbablePrime
j_lm
var j_lm = ((canary&0xffffff)==0xefcafe)
lowprimes
var lowprimes = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509]
lplim
var lplim = (1<<26)/lowprimes[lowprimes.length-1]
lShiftTo
BigInteger prototype lShiftTo = bnpLShiftTo
max
BigInteger prototype max = bnMax
millerRabin
BigInteger prototype millerRabin = bnpMillerRabin
min
BigInteger prototype min = bnMin
mod
BigInteger prototype mod = bnMod
modInt
BigInteger prototype modInt = bnpModInt
modInverse
BigInteger prototype modInverse = bnModInverse
modPow
BigInteger prototype modPow = bnModPow
modPowInt
BigInteger prototype modPowInt = bnModPowInt
multiply
BigInteger prototype multiply = bnMultiply
multiplyLowerTo
BigInteger prototype multiplyLowerTo = bnpMultiplyLowerTo
multiplyTo
BigInteger prototype multiplyTo = bnpMultiplyTo
multiplyUpperTo
BigInteger prototype multiplyUpperTo = bnpMultiplyUpperTo
mulTo
Barrett prototype mulTo = cMulTo
negate
BigInteger prototype negate = bnNegate
not
BigInteger prototype not = bnNot
ONE
BigInteger ONE = nbv(1)
or
BigInteger prototype or = bnOr
pow
BigInteger prototype pow = bnPow
reduce
Barrett prototype reduce = cReduce
remainder
BigInteger prototype remainder = bnRemainder
revert
Barrett prototype revert = cRevert
rr
rr = "0".charCodeAt(0)
rShiftTo
BigInteger prototype rShiftTo = bnpRShiftTo
setBit
BigInteger prototype setBit = bnSetBit
shiftLeft
BigInteger prototype shiftLeft = bnShiftLeft
shiftRight
BigInteger prototype shiftRight = bnShiftRight
shortValue
BigInteger prototype shortValue = bnShortValue
signum
BigInteger prototype signum = bnSigNum
sqrTo
Barrett prototype sqrTo = cSqrTo
squareTo
BigInteger prototype squareTo = bnpSquareTo
subTo
BigInteger prototype subTo = bnpSubTo
subtract
BigInteger prototype subtract = bnSubtract
testBit
BigInteger prototype testBit = bnTestBit
toByteArray
BigInteger prototype toByteArray = bnToByteArray
toRadix
BigInteger prototype toRadix = bnpToRadix
toString
BigInteger prototype toString = bnToString
vv
var vv
xor
BigInteger prototype xor = bnXor
ZERO
BigInteger ZERO = nbv(0)