backend/node_modules/jsonwebtoken/node_modules/jws/lib/verify-stream.js File Reference
Functions
function isObject (thing)
function safeJsonParse (thing)
function headerFromJWS (jwsSig)
function securedInputFromJWS (jwsSig)
function signatureFromJWS (jwsSig)
function payloadFromJWS (jwsSig, encoding)
function isValidJws (string)
function jwsVerify (jwsSig, algorithm, secretOrKey)
function jwsDecode (jwsSig, opts)
function VerifyStream (opts)
Variables
var Buffer = require('safe-buffer').Buffer
var DataStream = require('./data-stream')
var jwa = require('jwa')
var Stream = require('stream')
var toString = require('./tostring')
var util = require('util')
var JWS_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/
VerifyStream prototype verify
VerifyStream decode = jwsDecode
VerifyStream isValid = isValidJws
module exports = VerifyStream
Function Documentation
headerFromJWS()
function headerFromJWS (jwsSig)
References safeJsonParse().
isObject()
function isObject (thing)
isValidJws()
function isValidJws (string)
References headerFromJWS(), and JWS_REGEX.
jwsDecode()
function jwsDecode (jwsSig, opts)
References headerFromJWS(), isValidJws(), JSON, payloadFromJWS(), signature, signatureFromJWS(), and toString.
jwsVerify()
function jwsVerify (jwsSig, algorithm, secretOrKey)
References jwa, securedInputFromJWS(), signature, signatureFromJWS(), and toString.
payloadFromJWS()
function payloadFromJWS (jwsSig, encoding)
References encoding.
safeJsonParse()
function safeJsonParse (thing)
References e, isObject, JSON, and undefined.
securedInputFromJWS()
function securedInputFromJWS (jwsSig)
signatureFromJWS()
function signatureFromJWS (jwsSig)
VerifyStream()
function VerifyStream (opts)
References DataStream, encoding, readable, signature, and verify.
Variable Documentation
Buffer
var Buffer = require('safe-buffer').Buffer
DataStream
var DataStream = require('./data-stream')
decode
VerifyStream decode = jwsDecode
exports
module exports = VerifyStream
isValid
VerifyStream isValid = isValidJws
jwa
var jwa = require('jwa')
JWS_REGEX
var JWS_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/
Stream
var Stream = require('stream')
toString
var toString = require('./tostring')
util
var util = require('util')
verify
VerifyStream verify
Initial value:
= function verify() {
  try {
    var valid = jwsVerify(this.signature.buffer, this.algorithm, this.key.buffer);
    var obj = jwsDecode(this.signature.buffer, this.encoding);
    this.emit('done', valid, obj);
    this.emit('data', valid);
    this.emit('end');
    this.readable = false;
    return valid;
  } catch (e) {
    this.readable = false;
    this.emit('error', e);
    this.emit('close');
  }
}