backend/node_modules/jwa/index.js File Reference
Functions
if (supportsKeyObjects)
function checkIsPublicKey (key)
function checkIsPrivateKey (key)
function checkIsSecretKey (key)
function fromBase64 (base64)
function toBase64 (base64url)
function typeError (template)
function bufferOrString (obj)
function normalizeInput (thing)
function createHmacSigner (bits)
function createHmacVerifier (bits)
function createKeySigner (bits)
function createKeyVerifier (bits)
function createPSSKeySigner (bits)
function createPSSKeyVerifier (bits)
function createECDSASigner (bits)
function createECDSAVerifer (bits)
function createNoneSigner ()
function createNoneVerifier ()
Variables
var bufferEqual = require('buffer-equal-constant-time')
var Buffer = require('safe-buffer').Buffer
var crypto = require('crypto')
var formatEcdsa = require('ecdsa-sig-formatter')
var util = require('util')
var MSG_INVALID_ALGORITHM = '"%s" is not a valid algorithm.\n Supported algorithms are:\n "HS256"
var HS384
var HS512
var RS256
var RS384
var RS512
var PS256
var PS384
var PS512
var ES256
var ES384
var none MSG_INVALID_SECRET = 'secret must be a string or buffer'
var MSG_INVALID_VERIFIER_KEY = 'key must be a string or a buffer'
var MSG_INVALID_SIGNER_KEY = 'key must be a string
var a buffer or an object
var supportsKeyObjects = typeof crypto.createPublicKey === 'function'
module exports
Function Documentation
bufferOrString()
function bufferOrString (obj)
References obj.
checkIsPrivateKey()
function checkIsPrivateKey (key)
References MSG_INVALID_SIGNER_KEY, and typeError().
checkIsPublicKey()
function checkIsPublicKey (key)
References MSG_INVALID_VERIFIER_KEY, supportsKeyObjects, and typeError().
checkIsSecretKey()
function checkIsSecretKey (key)
References MSG_INVALID_SECRET, supportsKeyObjects, and typeError().
createECDSASigner()
function createECDSASigner (bits)
References createKeySigner(), formatEcdsa, sign, and signature.
createECDSAVerifer()
function createECDSAVerifer (bits)
References createKeyVerifier(), formatEcdsa, result, signature, and verify.
createHmacSigner()
function createHmacSigner (bits)
References checkIsSecretKey(), crypto, fromBase64(), hmac, normalizeInput(), and sign.
createHmacVerifier()
function createHmacVerifier (bits)
References bufferEqual, createHmacSigner(), signature, and verify.
createKeySigner()
function createKeySigner (bits)
References checkIsPrivateKey(), crypto, fromBase64(), normalizeInput(), and sign.
createKeyVerifier()
function createKeyVerifier (bits)
References checkIsPublicKey(), crypto, normalizeInput(), signature, toBase64(), verifier, and verify.
createNoneSigner()
function createNoneSigner ()
References sign.
createNoneVerifier()
function createNoneVerifier ()
References signature, and verify.
createPSSKeySigner()
function createPSSKeySigner (bits)
References checkIsPrivateKey(), crypto, fromBase64(), normalizeInput(), and sign.
createPSSKeyVerifier()
function createPSSKeyVerifier (bits)
References checkIsPublicKey(), crypto, normalizeInput(), signature, toBase64(), verifier, and verify.
fromBase64()
function fromBase64 (base64)
References base64, and g.
if()
if (supportsKeyObjects)
References MSG_INVALID_SECRET, and MSG_INVALID_VERIFIER_KEY.
normalizeInput()
function normalizeInput (thing)
References bufferOrString(), and JSON.
toBase64()
function toBase64 (base64url)
References _, base64url, g, and i.
typeError()
function typeError (template)
References args, and util.
Variable Documentation
Buffer
var Buffer = require('safe-buffer').Buffer
bufferEqual
var bufferEqual = require('buffer-equal-constant-time')
crypto
var crypto = require('crypto')
ES256
var ES256
ES384
var ES384
exports
module exports
Initial value:
= function jwa(algorithm) {
  var signerFactories = {
    hs: createHmacSigner,
    rs: createKeySigner,
    ps: createPSSKeySigner,
    es: createECDSASigner,
    none: createNoneSigner,
  }
  var verifierFactories = {
    hs: createHmacVerifier,
    rs: createKeyVerifier,
    ps: createPSSKeyVerifier,
    es: createECDSAVerifer,
    none: createNoneVerifier,
  }
  var match = algorithm.match(/^(RS|PS|ES|HS)(256|384|512)$|^(none)$/);
  if (!match)
    throw typeError(MSG_INVALID_ALGORITHM, algorithm);
  var algo = (match[1] || match[3]).toLowerCase();
  var bits = match[2];
  return {
    sign: signerFactories[algo](bits),
    verify: verifierFactories[algo](bits),
  }
}
formatEcdsa
var formatEcdsa = require('ecdsa-sig-formatter')
HS384
var HS384
HS512
var HS512
MSG_INVALID_ALGORITHM
var MSG_INVALID_ALGORITHM = '"%s" is not a valid algorithm.\n Supported algorithms are:\n "HS256"
MSG_INVALID_SECRET
var none MSG_INVALID_SECRET = 'secret must be a string or buffer'
MSG_INVALID_SIGNER_KEY
var MSG_INVALID_SIGNER_KEY = 'key must be a string
MSG_INVALID_VERIFIER_KEY
var MSG_INVALID_VERIFIER_KEY = 'key must be a string or a buffer'
object
var a buffer or an object
PS256
var PS256
PS384
var PS384
PS512
var PS512
RS256
var RS256
RS384
var RS384
RS512
var RS512
supportsKeyObjects
var supportsKeyObjects = typeof crypto.createPublicKey === 'function'
util
var util = require('util')