backend/node_modules/negotiator/lib/language.js File Reference
Functions
function parseAcceptLanguage (accept)
function parseLanguage (str, i)
function getLanguagePriority (language, accepted, index)
function specify (language, spec, index)
function preferredLanguages (accept, provided)
function compareSpecs (a, b)
function getFullLanguage (spec)
function isQuality (spec)
Variables
use strict
module exports = preferredLanguages
module exports preferredLanguages = preferredLanguages
var simpleLanguageRegExp = /^\s*([^\s\-;]+)(?:-([^\s;]+))?\s*(?:;(.*))?$/
Function Documentation
compareSpecs()
function compareSpecs (a, b) [private]
Compare two specs.
References a, and b.
getFullLanguage()
function getFullLanguage (spec) [private]
Get full language string. Here is the caller graph for this function:
getLanguagePriority()
function getLanguagePriority (language, accepted, index) [private]
Get the priority of a language.
References i, index, language, o, q, s, and specify().
isQuality()
function isQuality (spec) [private]
Check if a spec has any quality. Here is the caller graph for this function:
parseAcceptLanguage()
function parseAcceptLanguage (accept) [private]
Parse the Accept-Language header.
References accepts, i, j, language, parseLanguage(), and trim().
parseLanguage()
function parseLanguage (str, i) [private]
Parse a language from the Accept-Language header.
References i, j, match, p, prefix, q, simpleLanguageRegExp, and str().
preferredLanguages()
function preferredLanguages (accept, provided)
Get the preferred languages from an Accept-Language header.
References accepts, compareSpecs(), getFullLanguage(), getLanguagePriority(), index, isQuality(), parseAcceptLanguage(), type, and undefined.
specify()
function specify (language, spec, index) [private]
Get the specificity of the language.
References i, index, language, o, p, parseLanguage(), q, and s.
Variable Documentation
exports
module exports = preferredLanguages
Module exports.
preferredLanguages
module exports preferredLanguages = preferredLanguages
simpleLanguageRegExp
var simpleLanguageRegExp = /^\s*([^\s\-;]+)(?:-([^\s;]+))?\s*(?:;(.*))?$/ [private]
Module variables.
strict
use strict
negotiator Copyright(c) 2012 Isaac Z. Schlueter Copyright(c) 2014 Federico Romero Copyright(c) 2014-2015 Douglas Christopher Wilson MIT Licensed