backend/node_modules/@grpc/grpc-js/build/src/make-client.js File Reference
Functions
function isPrototypePolluted (key)
function makeClientConstructor (methods, serviceName, classOptions)
function partial (fn, path, serialize, deserialize)
function isProtobufTypeDefinition (obj)
function loadPackageDefinition (packageDef)
Variables
use strict
exports loadPackageDefinition = exports.makeClientConstructor = void 0
const client_1 = require("./client")
const requesterFuncs
exports makeClientConstructor = makeClientConstructor
Function Documentation
isProtobufTypeDefinition()
function isProtobufTypeDefinition (obj)
References obj.
isPrototypePolluted()
function isPrototypePolluted (key)
Returns true, if given key is included in the blacklisted keys.
Parameters
key key for check, string.
loadPackageDefinition()
function loadPackageDefinition (packageDef)
Load a gRPC package definition as a gRPC object hierarchy.
Parameters
packageDef The package definition object.
Returns
The resulting gRPC object.
References comp, isProtobufTypeDefinition(), isPrototypePolluted(), makeClientConstructor, of, and result.
makeClientConstructor()
function makeClientConstructor (methods, serviceName, classOptions)
Creates a constructor for a client with the given methods, as specified in the methods argument. The resulting class will have an instance method for each method in the service, which is a partial application of one of the [Client]grpc.Client request methods, depending on requestSerialize and responseSerialize, with the method, serialize, and deserialize arguments predefined.
Parameters
methods An object mapping method names to method attributes
serviceName The fully qualified name of the service
classOptions An options object.
Returns
New client constructor, which is a subclass of grpc.Client, and has the same arguments as that constructor.
References client_1, isPrototypePolluted(), methods, name, partial, requesterFuncs, and serialize.
partial()
function partial (fn, path, serialize, deserialize)
References args, fn, path, and serialize.
Variable Documentation
client_1
const client_1 = require("./client")
loadPackageDefinition
exports loadPackageDefinition = exports.makeClientConstructor = void 0
makeClientConstructor
exports makeClientConstructor = makeClientConstructor
requesterFuncs
const requesterFuncs [private]
Initial value:
= {
    unary: client_1.Client.prototype.makeUnaryRequest,
    server_stream: client_1.Client.prototype.makeServerStreamRequest,
    client_stream: client_1.Client.prototype.makeClientStreamRequest,
    bidi: client_1.Client.prototype.makeBidiStreamRequest,
}
Map with short names for each of the requester maker functions. Used in makeClientConstructor
strict
use strict