backend/node_modules/negotiator/lib/mediaType.js File Reference
Functions
function parseAccept (accept)
function parseMediaType (str, i)
function getMediaTypePriority (type, accepted, index)
function specify (type, spec, index)
function preferredMediaTypes (accept, provided)
function compareSpecs (a, b)
function getFullType (spec)
function isQuality (spec)
function quoteCount (string)
function splitKeyValuePair (str)
function splitMediaTypes (accept)
function splitParameters (str)
Variables
use strict
module exports = preferredMediaTypes
module exports preferredMediaTypes = preferredMediaTypes
var simpleMediaTypeRegExp = /^\s*([^\s\/;]+)\/([^;\s]+)\s*(?:;(.*))?$/
Function Documentation
compareSpecs()
function compareSpecs (a, b) [private]
Compare two specs.
References a, and b.
getFullType()
function getFullType (spec) [private]
Get full type string. Here is the caller graph for this function:
getMediaTypePriority()
function getMediaTypePriority (type, accepted, index) [private]
Get the priority of a media type.
References i, index, o, q, s, specify(), and type.
isQuality()
function isQuality (spec) [private]
Check if a spec has any quality. Here is the caller graph for this function:
parseAccept()
function parseAccept (accept) [private]
Parse the Accept header.
References accepts, i, j, mediaType, parseMediaType(), splitMediaTypes(), and trim().
parseMediaType()
function parseMediaType (str, i) [private]
Parse a media type from the Accept header.
References i, j, match, q, simpleMediaTypeRegExp, splitKeyValuePair(), splitParameters(), str(), type, and value.
preferredMediaTypes()
function preferredMediaTypes (accept, provided)
Get the preferred media types from an Accept header.
References accepts, compareSpecs(), getFullType(), getMediaTypePriority(), getType, index, isQuality(), parseAccept(), type, and undefined.
quoteCount()
function quoteCount (string) [private]
Count the number of quotes in a string.
References count, index, and indexOf.
specify()
function specify (type, spec, index) [private]
Get the specificity of the media type.
References i, index, k, keys, o, p, parseMediaType(), q, s, and type.
splitKeyValuePair()
function splitKeyValuePair (str) [private]
Split a key value pair.
References index, and str().
splitMediaTypes()
function splitMediaTypes (accept) [private]
Split an Accept header into media types.
References accepts, i, j, and quoteCount().
splitParameters()
function splitParameters (str) [private]
Split a string of parameters.
References i, j, quoteCount(), and str().
Variable Documentation
exports
module exports = preferredMediaTypes
Module exports.
preferredMediaTypes
module exports preferredMediaTypes = preferredMediaTypes
simpleMediaTypeRegExp
var simpleMediaTypeRegExp = /^\s*([^\s\/;]+)\/([^;\s]+)\s*(?:;(.*))?$/ [private]
Module variables.
strict
use strict
negotiator Copyright(c) 2012 Isaac Z. Schlueter Copyright(c) 2014 Federico Romero Copyright(c) 2014-2015 Douglas Christopher Wilson MIT Licensed