backend/node_modules/firebase-admin/lib/messaging/messaging-internal.js File Reference
Functions
function validateMessage (message)
function validateStringMap (map, label)
function validateWebpushConfig (config)
function validateApnsConfig (config)
function validateApnsFcmOptions (fcmOptions)
function validateFcmOptions (fcmOptions)
function validateNotification (notification)
function validateApnsPayload (payload)
function validateAps (aps)
function validateApsSound (sound)
function validateApsAlert (alert)
function validateAndroidConfig (config)
function validateAndroidNotification (notification)
function validateLightSettings (lightSettings)
function validateAndroidFcmOptions (fcmOptions)
Variables
use strict
exports validateMessage = exports.BLACKLISTED_OPTIONS_KEYS = exports.BLACKLISTED_DATA_PAYLOAD_KEYS = void 0
const index_1 = require("../utils/index")
const error_1 = require("../utils/error")
const validator = require("../utils/validator")
exports BLACKLISTED_DATA_PAYLOAD_KEYS = ['from']
exports BLACKLISTED_OPTIONS_KEYS
Function Documentation
validateAndroidConfig()
function validateAndroidConfig (config)
Checks if the given AndroidConfig object is valid. The object must have valid ttl, data, and notification fields. If successful, transforms the input object by renaming keys to valid Android keys. Also transforms the ttl value to the format expected by FCM service.
Parameters
config - An object to be validated.
References config, error_1, index_1, validateAndroidFcmOptions(), validateAndroidNotification(), validateStringMap(), and validator.
validateAndroidFcmOptions()
function validateAndroidFcmOptions (fcmOptions)
Checks if the given AndroidFcmOptions object is valid.
Parameters
{AndroidFcmOptions} fcmOptions An object to be validated.
References error_1, and validator.
validateAndroidNotification()
function validateAndroidNotification (notification)
Checks if the given AndroidNotification object is valid. The object must have valid color and localization parameters. If successful, transforms the input object by renaming keys to valid Android keys.
Parameters
{AndroidNotification} notification An object to be validated.
References $, a, error_1, F, index_1, validateLightSettings(), validator, and value.
validateApnsConfig()
function validateApnsConfig (config)
Checks if the given ApnsConfig object is valid. The object must have valid headers and a payload.
Parameters
{ApnsConfig} config An object to be validated.
References config, error_1, validateApnsFcmOptions(), validateApnsPayload(), validateStringMap(), and validator.
validateApnsFcmOptions()
function validateApnsFcmOptions (fcmOptions)
Checks if the given ApnsFcmOptions object is valid.
Parameters
{ApnsFcmOptions} fcmOptions An object to be validated.
References $, error_1, index_1, and validator.
validateApnsPayload()
function validateApnsPayload (payload)
Checks if the given ApnsPayload object is valid. The object must have a valid aps value.
Parameters
{ApnsPayload} payload An object to be validated.
References error_1, validateAps(), and validator.
validateAps()
function validateAps (aps)
Checks if the given Aps object is valid. The object must have a valid alert. If the validation is successful, transforms the input object by renaming the keys to valid APNS payload keys.
Parameters
{Aps} aps An object to be validated.
References $, error_1, index_1, validateApsAlert(), validateApsSound(), and validator.
validateApsAlert()
function validateApsAlert (alert)
Checks if the given alert object is valid. Alert could be a string or a complex object. If specified as an object, it must have valid localization parameters. If successful, transforms the input object by renaming the keys to valid APNS payload keys.
Parameters
{string | ApsAlert} alert An alert string or an object to be validated.
References error_1, index_1, and validator.
validateApsSound()
function validateApsSound (sound)
References error_1, and validator.
validateFcmOptions()
function validateFcmOptions (fcmOptions)
Checks if the given FcmOptions object is valid.
Parameters
{FcmOptions} fcmOptions An object to be validated.
References error_1, and validator.
validateLightSettings()
function validateLightSettings (lightSettings)
Checks if the given LightSettings object is valid. The object must have valid color and light on/off duration parameters. If successful, transforms the input object by renaming keys to valid Android keys.
Parameters
{LightSettings} lightSettings An object to be validated.
References $, a, error_1, F, i, index_1, parseInt(), rgb, and validator.
validateMessage()
function validateMessage (message)
Checks if the given Message object is valid. Recursively validates all the child objects included in the message (android, apns, data etc.). If successful, transforms the message in place by renaming the keys to what's expected by the remote FCM service.
Parameters
{Message} Message An object to be validated.
References $, _, a, error_1, message, v, validateAndroidConfig(), validateApnsConfig(), validateFcmOptions(), validateNotification(), validateStringMap(), validateWebpushConfig(), and validator.
validateNotification()
function validateNotification (notification)
Checks if the given Notification object is valid.
Parameters
{Notification} notification An object to be validated.
References $, error_1, index_1, and validator.
validateStringMap()
function validateStringMap (map, label)
Checks if the given object only contains strings as child values.
Parameters
{object} map An object to be validated.
{string} label A label to be included in the errors thrown.
References $, a, error_1, map, validator, and values.
validateWebpushConfig()
function validateWebpushConfig (config)
Checks if the given WebpushConfig object is valid. The object must have valid headers and data.
Parameters
{WebpushConfig} config An object to be validated.
References config, error_1, validateStringMap(), and validator.
Variable Documentation
BLACKLISTED_DATA_PAYLOAD_KEYS
exports BLACKLISTED_DATA_PAYLOAD_KEYS = ['from']
BLACKLISTED_OPTIONS_KEYS
exports BLACKLISTED_OPTIONS_KEYS
Initial value:
= [
    'condition', 'data', 'notification', 'registrationIds', 'registration_ids', 'to',
]
error_1
const error_1 = require("../utils/error")
index_1
const index_1 = require("../utils/index")
strict
use strict
firebase-admin v12.7.0
validateMessage
exports validateMessage = exports.BLACKLISTED_OPTIONS_KEYS = exports.BLACKLISTED_DATA_PAYLOAD_KEYS = void 0
validator
const validator = require("../utils/validator")