backend/node_modules/@grpc/grpc-js/build/src/metadata.js File Reference
Classes
class Metadata
Functions
function isLegalKey (key)
function isLegalNonBinaryValue (value)
function isBinaryKey (key)
function isCustomMetadata (key)
function normalizeKey (key)
function validate (key, value)
Variables
use strict
exports Metadata = void 0
const logging_1 = require("./logging")
const constants_1 = require("./constants")
const error_1 = require("./error")
const LEGAL_KEY_REGEX = /^[0-9a-z_.-]+$/
const LEGAL_NON_BINARY_VALUE_REGEX = /^[ -~]*$/
const bufToString
Function Documentation
isBinaryKey()
function isBinaryKey (key)
isCustomMetadata()
function isCustomMetadata (key)
isLegalKey()
function isLegalKey (key)
References LEGAL_KEY_REGEX.
isLegalNonBinaryValue()
function isLegalNonBinaryValue (value)
References LEGAL_NON_BINARY_VALUE_REGEX, and value.
normalizeKey()
function normalizeKey (key)
validate()
function validate (key, value)
References isBinaryKey(), isLegalKey(), isLegalNonBinaryValue(), undefined, and value.
Variable Documentation
bufToString
const bufToString
Initial value:
= (val) => {
    return Buffer.isBuffer(val) ? val.toString('base64') : val;
}
constants_1
const constants_1 = require("./constants")
error_1
const error_1 = require("./error")
LEGAL_KEY_REGEX
const LEGAL_KEY_REGEX = /^[0-9a-z_.-]+$/
LEGAL_NON_BINARY_VALUE_REGEX
const LEGAL_NON_BINARY_VALUE_REGEX = /^[ -~]*$/
logging_1
const logging_1 = require("./logging")
Metadata
exports Metadata = void 0
along with the operation.
strict
use strict