backend/node_modules/jose/dist/node/esm/lib/crypto_key.js File Reference
Functions
function unusable (name, prop='algorithm.name')
function isAlgorithm (algorithm, name)
function getHashLength (hash)
function getNamedCurve (alg)
function checkUsage (key, usages)
function export checkSigCryptoKey (key, alg,...usages)
function export checkEncCryptoKey (key, alg,...usages)
Function Documentation
checkEncCryptoKey()
function export checkEncCryptoKey (key, alg, ...)
References $, checkUsage(), expected, getHashLength(), isAlgorithm(), parseInt(), and unusable().
checkSigCryptoKey()
function export checkSigCryptoKey (key, alg, ...)
References $, checkUsage(), expected, getHashLength(), getNamedCurve, isAlgorithm(), parseInt(), and unusable().
checkUsage()
function checkUsage (key, usages)
References $, expected, last, msg, of, and or.
getHashLength()
function getHashLength (hash)
References hash(), and parseInt().
getNamedCurve()
function getNamedCurve (alg)
isAlgorithm()
function isAlgorithm (algorithm, name)
References name.
unusable()
function unusable (name, prop = 'algorithm.name')
References $, name, not, operation, and prop.