backend/node_modules/jose/dist/node/cjs/lib/decrypt_key_management.js File Reference
Functions
function async decryptKeyManagement (alg, key, encryptedKey, joseHeader, options)
Variables
use strict
const aeskw_js_1 = require("../runtime/aeskw.js")
const ECDH = require("../runtime/ecdhes.js")
const pbes2kw_js_1 = require("../runtime/pbes2kw.js")
const rsaes_js_1 = require("../runtime/rsaes.js")
const base64url_js_1 = require("../runtime/base64url.js")
const errors_js_1 = require("../util/errors.js")
const cek_js_1 = require("../lib/cek.js")
const import_js_1 = require("../key/import.js")
const check_key_type_js_1 = require("./check_key_type.js")
const is_object_js_1 = require("./is_object.js")
const aesgcmkw_js_1 = require("./aesgcmkw.js")
exports default = decryptKeyManagement
Function Documentation
decryptKeyManagement()
function async decryptKeyManagement (alg, key, encryptedKey, joseHeader, options)
References aesgcmkw_js_1, aeskw_js_1, base64url_js_1, cek_js_1, check_key_type_js_1, ECDH, errors_js_1, import_js_1, invalid(), is, is_object_js_1, missing(), of, or, p2s, parseInt(), pbes2kw_js_1, rsaes_js_1, and undefined.
Variable Documentation
aesgcmkw_js_1
const aesgcmkw_js_1 = require("./aesgcmkw.js")
aeskw_js_1
const aeskw_js_1 = require("../runtime/aeskw.js")
base64url_js_1
const base64url_js_1 = require("../runtime/base64url.js")
cek_js_1
const cek_js_1 = require("../lib/cek.js")
check_key_type_js_1
const check_key_type_js_1 = require("./check_key_type.js")
default
exports default = decryptKeyManagement
ECDH
const ECDH = require("../runtime/ecdhes.js")
errors_js_1
const errors_js_1 = require("../util/errors.js")
import_js_1
const import_js_1 = require("../key/import.js")
is_object_js_1
const is_object_js_1 = require("./is_object.js")
pbes2kw_js_1
const pbes2kw_js_1 = require("../runtime/pbes2kw.js")
rsaes_js_1
const rsaes_js_1 = require("../runtime/rsaes.js")
strict
use strict