backend/node_modules/jose/dist/node/esm/runtime/encrypt.js File Reference
Functions
function cbcEncrypt (enc, plaintext, cek, iv, aad)
function gcmEncrypt (enc, plaintext, cek, iv, aad)
Variables
import { createCipheriv, KeyObject } from 'crypto'
import checkIvLength from lib check_iv_length js
const encrypt
Function Documentation
cbcEncrypt()
function cbcEncrypt (enc, plaintext, cek, iv, aad)
References $, cbc, cbcTag(), cipher, concat, is, JOSENotSupported, not, and parseInt().
gcmEncrypt()
function gcmEncrypt (enc, plaintext, cek, iv, aad)
References $, cipher, gcm, is, JOSENotSupported, not, and parseInt().
Variable Documentation
encrypt
export default encrypt
Initial value:
= (enc, plaintext, cek, iv, aad) => {
    let key;
    if (isCryptoKey(cek)) {
        checkEncCryptoKey(cek, enc, 'encrypt');
        key = KeyObject.from(cek);
    }
    else if (cek instanceof Uint8Array || isKeyObject(cek)) {
        key = cek;
    }
    else {
        throw new TypeError(invalidKeyInput(cek, ...types, 'Uint8Array'));
    }
    checkCekLength(enc, key);
    checkIvLength(enc, iv);
    switch (enc) {
        case 'A128CBC-HS256':
        case 'A192CBC-HS384':
        case 'A256CBC-HS512':
            return cbcEncrypt(enc, plaintext, key, iv, aad);
        case 'A128GCM':
        case 'A192GCM':
        case 'A256GCM':
            return gcmEncrypt(enc, plaintext, key, iv, aad);
        default:
            throw new JOSENotSupported('Unsupported JWE Content Encryption Algorithm');
    }
}
import
import { createCipheriv, KeyObject } from 'crypto'
js
import supported from ciphers js