backend/node_modules/farmhash-modern/bin/nodejs/farmhash_modern.js File Reference
Functions
function getObject (idx)
function dropObject (idx)
function takeObject (idx)
function getUint8Memory0 ()
function passArray8ToWasm0 (arg, malloc)
function getStringFromWasm0 (ptr, len)
function addHeapObject (obj)
function passStringToWasm0 (arg, malloc, realloc)
function getInt32Memory0 ()
Variables
let imports = {}
let wasm = wasmInstance.exports
const { TextDecoder, TextEncoder } = require(util)
const heap = new Array(128).fill(undefined)
let heap_next = heap.length
let cachedUint8Memory0 = null
let WASM_VECTOR_LEN = 0
module exports fingerprint32
module exports fingerprint64
module exports bigquery_fingerprint
module exports hash32
module exports hash32_with_seed
module exports hash64
module exports hash64_with_seed
let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true })
let cachedTextEncoder = new TextEncoder('utf-8')
const encodeString
let cachedInt32Memory0 = null
module exports __wbg_new_abda76e883ba8a5f
module exports __wbg_stack_658279fe44541cf6
module exports __wbg_error_f851667af71bcfc6
module exports __wbindgen_object_drop_ref
const path = require('path').join(__dirname, 'farmhash_modern_bg.wasm')
const bytes = require('fs').readFileSync(path)
const wasmModule = new WebAssembly.Module(bytes)
const wasmInstance = new WebAssembly.Instance(wasmModule, imports)
module exports __wasm = wasm
Function Documentation
addHeapObject()
function addHeapObject (obj)
References heap, heap_next, and obj.
dropObject()
function dropObject (idx)
References heap, and heap_next.
getInt32Memory0()
function getInt32Memory0 ()
References cachedInt32Memory0, and wasm.
getObject()
function getObject (idx)
References heap.
getStringFromWasm0()
function getStringFromWasm0 (ptr, len)
References cachedTextDecoder, and getUint8Memory0().
getUint8Memory0()
function getUint8Memory0 ()
References cachedUint8Memory0, Uint8Array, and wasm.
passArray8ToWasm0()
function passArray8ToWasm0 (arg, malloc)
References getUint8Memory0(), and WASM_VECTOR_LEN.
passStringToWasm0()
function passStringToWasm0 (arg, malloc, realloc)
References buf, cachedTextEncoder, encodeString, getUint8Memory0(), undefined, and WASM_VECTOR_LEN.
takeObject()
function takeObject (idx)
References dropObject(), and getObject().
Variable Documentation
__wasm
module exports __wasm = wasm
__wbg_error_f851667af71bcfc6
module exports __wbg_error_f851667af71bcfc6
Initial value:
= function(arg0, arg1) {
    let deferred0_0;
    let deferred0_1;
    try {
        deferred0_0 = arg0;
        deferred0_1 = arg1;
        console.error(getStringFromWasm0(arg0, arg1));
    } finally {
        wasm.__wbindgen_free(deferred0_0, deferred0_1, 1);
    }
}
__wbg_new_abda76e883ba8a5f
module exports __wbg_new_abda76e883ba8a5f
Initial value:
= function() {
    const ret = new Error();
    return addHeapObject(ret);
}
__wbg_stack_658279fe44541cf6
module exports __wbg_stack_658279fe44541cf6
Initial value:
= function(arg0, arg1) {
    const ret = getObject(arg1).stack;
    const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    const len1 = WASM_VECTOR_LEN;
    getInt32Memory0()[arg0 / 4 + 1] = len1;
    getInt32Memory0()[arg0 / 4 + 0] = ptr1;
}
__wbindgen_object_drop_ref
module exports __wbindgen_object_drop_ref
Initial value:
= function(arg0) {
    takeObject(arg0);
}
bigquery_fingerprint
module exports bigquery_fingerprint
Initial value:
= function(input) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.bigquery_fingerprint(ptr0, len0);
    return ret;
}
Parameters
{Uint8Array} input
Returns
{bigint}
bytes
util DataBuffer prototype bytes = require('fs').readFileSync(path)
Gets a binary encoded string of the bytes from this buffer without modifying the read pointer.
Parameters
count the number of bytes to get, omit to get all.
Returns
a string full of binary encoded characters.
cachedInt32Memory0
let cachedInt32Memory0 = null
cachedTextDecoder
let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true })
cachedTextEncoder
let cachedTextEncoder = new TextEncoder('utf-8')
cachedUint8Memory0
let cachedUint8Memory0 = null
const
const { TextDecoder, TextEncoder } = require(util)
encodeString
const encodeString
Initial value:
= (typeof cachedTextEncoder.encodeInto === 'function'
    ? function (arg, view) {
    return cachedTextEncoder.encodeInto(arg, view);
}
    : function (arg, view) {
    const buf = cachedTextEncoder.encode(arg);
    view.set(buf);
    return {
        read: arg.length,
        written: buf.length
    };
})
fingerprint32
module exports fingerprint32
Initial value:
= function(input) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.fingerprint32(ptr0, len0);
    return ret >>> 0;
}
Parameters
{Uint8Array} input
Returns
{number}
fingerprint64
module exports fingerprint64
Initial value:
= function(input) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.bigquery_fingerprint(ptr0, len0);
    return BigInt.asUintN(64, ret);
}
Parameters
{Uint8Array} input
Returns
{bigint}
hash32
module exports hash32
Initial value:
= function(input) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.hash32(ptr0, len0);
    return ret >>> 0;
}
Parameters
{Uint8Array} input
Returns
{number}
hash32_with_seed
module exports hash32_with_seed
Initial value:
= function(input, seed) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.hash32_with_seed(ptr0, len0, seed);
    return ret >>> 0;
}
Parameters
{Uint8Array} input
{number} seed
Returns
{number}
hash64
module exports hash64
Initial value:
= function(input) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.hash64(ptr0, len0);
    return BigInt.asUintN(64, ret);
}
Parameters
{Uint8Array} input
Returns
{bigint}
hash64_with_seed
module exports hash64_with_seed
Initial value:
= function(input, seed) {
    const ptr0 = passArray8ToWasm0(input, wasm.__wbindgen_malloc);
    const len0 = WASM_VECTOR_LEN;
    const ret = wasm.hash64_with_seed(ptr0, len0, seed);
    return BigInt.asUintN(64, ret);
}
Parameters
{Uint8Array} input
{bigint} seed
Returns
{bigint}
heap
const heap = new Array(128).fill(undefined)
heap_next
let heap_next = heap.length
imports
imports[ '__wbindgen_placeholder__'] = {}
path
const path = require('path').join(__dirname, 'farmhash_modern_bg.wasm')
wasm
wasm = wasmInstance.exports
WASM_VECTOR_LEN
let WASM_VECTOR_LEN = 0
wasmInstance
const wasmInstance = new WebAssembly.Instance(wasmModule, imports)
wasmModule
const wasmModule = new WebAssembly.Module(bytes)