backend/node_modules/jose/dist/node/cjs/lib/crypto_key.js File Reference
Functions
function unusable (name, prop='algorithm.name')
function isAlgorithm (algorithm, name)
function getHashLength (hash)
function getNamedCurve (alg)
function checkUsage (key, usages)
function checkSigCryptoKey (key, alg,...usages)
function checkEncCryptoKey (key, alg,...usages)
Variables
use strict
exports checkEncCryptoKey = exports.checkSigCryptoKey = void 0
exports checkSigCryptoKey = checkSigCryptoKey
Function Documentation
checkEncCryptoKey()
function checkEncCryptoKey (key, alg, ...)
References $, checkUsage(), expected, getHashLength(), isAlgorithm(), parseInt(), and unusable().
checkSigCryptoKey()
function checkSigCryptoKey (key, alg, ...)
References $, checkUsage(), expected, getHashLength(), getNamedCurve, isAlgorithm(), parseInt(), and unusable().
checkUsage()
function checkUsage (key, usages)
References $, expected, last, msg, of, and or.
getHashLength()
function getHashLength (hash)
References hash(), and parseInt().
getNamedCurve()
function getNamedCurve (alg)
isAlgorithm()
function isAlgorithm (algorithm, name)
References name.
unusable()
function unusable (name, prop = 'algorithm.name')
References $, name, not, operation, and prop.
Variable Documentation
checkEncCryptoKey
exports checkEncCryptoKey = exports.checkSigCryptoKey = void 0
checkSigCryptoKey
exports checkSigCryptoKey = checkSigCryptoKey
strict
use strict