backend/node_modules/node-fetch/lib/index.js File Reference
Classes
class Blob
class Headers
class Response
class Request
Functions
function _interopDefault (ex)
function FetchError (message, type, systemError)
catch (e)
function Body (body)
function consumeBody ()
function convertBody (buffer, headers)
function isURLSearchParams (obj)
function isBlob (obj)
function clone (instance)
function extractContentType (body)
function getTotalBytes (instance)
function writeToStream (dest, instance)
function validateName (name)
function validateValue (value)
function find (map, name)
function getHeaders (headers)
function createHeadersIterator (target, kind)
function exportNodeCompatibleHeaders (headers)
function createHeadersLenient (obj)
function parseURL (urlStr)
function isRequest (input)
function isAbortSignal (signal)
function getNodeRequestOptions (request)
Variables
use strict
var Stream = _interopDefault(require('stream'))
var http = _interopDefault(require('http'))
var Url = _interopDefault(require('url'))
var whatwgUrl = _interopDefault(require('whatwg-url'))
var https = _interopDefault(require('https'))
var zlib = _interopDefault(require('zlib'))
const Readable = Stream.Readable
const BUFFER = Symbol('buffer')
const TYPE = Symbol('type')
FetchError prototype = Object.create(Error.prototype)
FetchError prototype constructor = FetchError
FetchError prototype name = 'FetchError'
let convert
try
const INTERNALS = Symbol('Body internals')
const PassThrough = Stream.PassThrough
Body mixIn
Body Promise = global.Promise
const invalidTokenRegex = /[^\^_a-zA-Z\-0-9!#$%&'*+.|~]/
const invalidHeaderCharRegex = /[^\t\x20-\x7e\x80-\xff]/
const MAP = Symbol('map')
Headers prototype entries = Headers.prototype[Symbol.iterator]
const INTERNAL = Symbol('internal')
const HeadersIteratorPrototype
const INTERNALS$1 = Symbol('Response internals')
const STATUS_CODES = http.STATUS_CODES
const INTERNALS$2 = Symbol('Request internals')
const URL = Url.URL || whatwgUrl.URL
const parse_url = Url.parse
const format_url = Url.format
const streamDestructionSupported = 'destroy' in Stream.Readable.prototype
Function Documentation
_interopDefault()
function _interopDefault (ex)
Body()
function Body (body)
Body mixin
Ref: https://fetch.spec.whatwg.org/#body
Parameters
Stream body Readable stream
Object opts Response options
Returns
Void
References $, error, fetch, FetchError(), INTERNALS, isBlob(), isURLSearchParams(), response, size, Stream, timeout, and undefined.
catch()
catch (e)
clone()
function clone (instance)
Clone body given Res/Req instance
Parameters
Mixed instance Response or Request instance
Returns
Mixed
References instance, INTERNALS, PassThrough, and Stream.
consumeBody()
function consumeBody ()
Consume and convert an entire Body to a Buffer.
Ref: https://fetch.spec.whatwg.org/#concept-body-consume-body
Returns
Promise
References $, abort, at, Body(), chunk(), create, error, fetch, FetchError(), INTERNALS, isBlob(), limit, ms, not, over, reject(), resolve, response, size, Stream, timeout, and url.
convertBody()
function convertBody (buffer, headers)
Detect buffer encoding and convert to target encoding ref: http://www.w3.org/TR/2011/WD-html5-20110113/parsing.html#determining-the-character-encoding
Parameters
Buffer buffer Incoming buffer
String encoding Target encoding
Returns
String
References buffer, charset, convert, ct, headers, i, res, s, and str().
createHeadersIterator()
function createHeadersIterator (target, kind)
References HeadersIteratorPrototype, index, INTERNAL, and iterator.
createHeadersLenient()
function createHeadersLenient (obj)
Create a Headers object from an object of headers, ignoring those that do not conform to HTTP grammar productions.
Parameters
Object obj Object of headers
Returns
Headers
References Array, Headers, headers, invalidHeaderCharRegex, invalidTokenRegex, MAP, name, obj, of, and undefined.
exportNodeCompatibleHeaders()
function exportNodeCompatibleHeaders (headers)
Export the Headers object in a form that Node.js can consume.
Parameters
Headers headers
Returns
Object
References find, headers, MAP, obj, and undefined.
extractContentType()
function extractContentType (body)
Performs the operation "extract a Content-Type value from |object|" as specified in the specification: https://fetch.spec.whatwg.org/#concept-bodyinit-extract
This function assumes that instance.body is present.
Parameters
Mixed instance Any options.body input
References $, data, form, isBlob(), isURLSearchParams(), and Stream.
FetchError()
function FetchError (message, type, systemError)
fetch-error.js
FetchError interface for operational errors Create FetchError instance
Parameters
String message Error message for human
String type Error type for machine
String systemError For Node.js system error
Returns
FetchError
References constructor, message, and type.
find()
function find (map, name)
Find the key in the map object given a header name.
Returns undefined if not found.
Parameters
String name Header name
Returns
String|Undefined
getHeaders()
function getHeaders (headers)
References headers, k, Headers::keys(), keys, MAP, and undefined.
getNodeRequestOptions()
function getNodeRequestOptions (request)
Convert a Request to Node.js http request options.
Parameters
Request A Request instance
Returns
Object The options object to be passed to http.request
Create AbortError instance
Parameters
String message Error message for human
Returns
AbortError
isSameProtocol reports whether the two provided URLs use the same protocol.
Both domains must already be in canonical form.
Parameters
{string|URL} original
{string|URL} destination
Fetch function
Parameters
Mixed url Absolute url or Request instance
Object opts Fetch options
Returns
Promise
Redirect code matching
Parameters
Number code Status code
Returns
Boolean
References $, exportNodeCompatibleHeaders(), getTotalBytes(), Headers, headers, https, i, INTERNALS$2, method, request, Stream, streamDestructionSupported, and test.
getTotalBytes()
function getTotalBytes (instance)
The Fetch Standard treats this as if "total bytes" is a property on the body. For us, we have to explicitly get it with a function.
ref: https://fetch.spec.whatwg.org/#concept-body-total-bytes
Parameters
Body instance Instance of Body
Returns
Number? Number of bytes, or null if not possible
References instance, and isBlob().
isAbortSignal()
function isAbortSignal (signal)
References proto, and signal.
isBlob()
function isBlob (obj)
Check if obj is a W3C Blob object (which File inherits from)
Parameters
{*} obj
Returns
{boolean}
References $, File, obj, Symbol, and test.
isRequest()
function isRequest (input)
Check if a value is an instance of Request.
Parameters
Mixed input
Returns
Boolean
References INTERNALS$2.
isURLSearchParams()
function isURLSearchParams (obj)
Detect a URLSearchParams object ref: https://github.com/bitinn/node-fetch/issues/296#issuecomment-307598143
Parameters
Object obj Object to detect by type or brand
Returns
String
References obj.
parseURL()
function parseURL (urlStr)
Wrapper around new URL to handle arbitrary URLs
Parameters
{string} urlStr
Returns
{void}
References a, d, exec, parse_url, URL, and Z().
validateName()
function validateName (name)
validateValue()
function validateValue (value)
writeToStream()
function writeToStream (dest, instance)
Write a Body to a Node.js WritableStream (e.g. http.Request) object.
Parameters
Body instance Instance of Body
Returns
Void
References instance, and isBlob().
Variable Documentation
BUFFER
const BUFFER = Symbol('buffer')
constructor
FetchError prototype constructor = FetchError
convert
let convert
entries
Headers prototype entries = Headers.prototype[Symbol.iterator]
format_url
const format_url = Url.format
HeadersIteratorPrototype
const HeadersIteratorPrototype
Initial value:
= Object.setPrototypeOf({
    next() {
        
        if (!this || Object.getPrototypeOf(this) !== HeadersIteratorPrototype) {
            throw new TypeError('Value of this` is not a HeadersIterator');
        }
        var _INTERNAL = this[INTERNAL];
        const target = _INTERNAL.target,
              kind = _INTERNAL.kind,
              index = _INTERNAL.index;
        const values = getHeaders(target, kind);
        const len = values.length;
        if (index >= len) {
            return {
                value: undefined,
                done: true
            };
        }
        this[INTERNAL].index = index + 1;
        return {
            value: values[index],
            done: false
        };
    }
}, Object.getPrototypeOf(Object.getPrototypeOf([][Symbol.iterator]())))
http
var http = _interopDefault(require('http'))
https
var https = _interopDefault(require('https'))
INTERNAL
const INTERNAL = Symbol('internal')
INTERNALS
const INTERNALS = Symbol('Body internals')
INTERNALS$1
const INTERNALS$1 = Symbol('Response internals')
INTERNALS$2
const INTERNALS$2 = Symbol('Request internals')
invalidHeaderCharRegex
const invalidHeaderCharRegex = /[^\t\x20-\x7e\x80-\xff]/
invalidTokenRegex
const invalidTokenRegex = /[^\^_a-zA-Z\-0-9!#$%&'*+.|~]/
headers.js
Headers class offers convenient helpers
MAP
const MAP = Symbol('map')
mixIn
Body mixIn
Initial value:
= function (proto) {
    for (const name of Object.getOwnPropertyNames(Body.prototype)) {
        
        if (!(name in proto)) {
            const desc = Object.getOwnPropertyDescriptor(Body.prototype, name);
            Object.defineProperty(proto, name, desc);
        }
    }
}
name
FetchError prototype name = 'FetchError'
parse_url
const parse_url = Url.parse
PassThrough
const PassThrough = Stream.PassThrough
Promise
Body Promise = global.Promise
prototype
Body prototype = Object.create(Error.prototype)
Readable
const Readable = Stream.Readable
STATUS_CODES
const STATUS_CODES = http.STATUS_CODES
Stream
var Stream = _interopDefault(require('stream'))
streamDestructionSupported
const streamDestructionSupported = 'destroy' in Stream.Readable.prototype
strict
use strict
try
try
Initial value:
{
    convert = require('encoding').convert
TYPE
const TYPE = Symbol('type')
URL
const URL = Url.URL || whatwgUrl.URL
Url
var Url = _interopDefault(require('url'))
whatwgUrl
var whatwgUrl = _interopDefault(require('whatwg-url'))
zlib
var zlib = _interopDefault(require('zlib'))