backend/node_modules/jose/dist/node/esm/runtime/decrypt.js File Reference
Functions
function cbcDecrypt (enc, cek, ciphertext, iv, tag, aad)
function gcmDecrypt (enc, cek, ciphertext, iv, tag, aad)
Variables
import { createDecipheriv, KeyObject } from 'crypto'
import checkIvLength from lib check_iv_length js
const decrypt
Function Documentation
cbcDecrypt()
function cbcDecrypt (enc, cek, ciphertext, iv, tag, aad)
References $, cbc, cbcTag(), concat, is, JOSENotSupported, JWEDecryptionFailed, not, parseInt(), and timingSafeEqual.
gcmDecrypt()
function gcmDecrypt (enc, cek, ciphertext, iv, tag, aad)
References $, gcm, is, JOSENotSupported, JWEDecryptionFailed, not, and parseInt().
Variable Documentation
decrypt
export default decrypt
Initial value:
= (enc, cek, ciphertext, iv, tag, aad) => {
    let key;
    if (isCryptoKey(cek)) {
        checkEncCryptoKey(cek, enc, 'decrypt');
        key = KeyObject.from(cek);
    }
    else if (cek instanceof Uint8Array || isKeyObject(cek)) {
        key = cek;
    }
    else {
        throw new TypeError(invalidKeyInput(cek, ...types, 'Uint8Array'));
    }
    checkCekLength(enc, key);
    checkIvLength(enc, iv);
    switch (enc) {
        case 'A128CBC-HS256':
        case 'A192CBC-HS384':
        case 'A256CBC-HS512':
            return cbcDecrypt(enc, key, ciphertext, iv, tag, aad);
        case 'A128GCM':
        case 'A192GCM':
        case 'A256GCM':
            return gcmDecrypt(enc, key, ciphertext, iv, tag, aad);
        default:
            throw new JOSENotSupported('Unsupported JWE Content Encryption Algorithm');
    }
}
import
import { createDecipheriv, KeyObject } from 'crypto'
js
import supported from ciphers js