backend/node_modules/fast-xml-parser/src/xmlparser/node2json.js File Reference
Functions
function prettify (node, options)
function compress (arr, options, jPath)
function propName (obj)
function assignAttributes (obj, attrMap, jpath, options)
function isLeafTag (obj, options)
Variables
use strict
exports prettify = prettify
Function Documentation
assignAttributes()
function assignAttributes (obj, attrMap, jpath, options)
References i, keys, and obj.
compress()
function compress (arr, options, jPath)
Parameters
{array} arr
{object} options
{string} jPath
Returns
object
References Array, assignAttributes(), compress(), i, isLeafTag(), property, propName(), text, and undefined.
isLeafTag()
function isLeafTag (obj, options)
References obj.
prettify()
function prettify (node, options)
Parameters
{array} node
{any} options
Returns
References compress(), and node.
propName()
function propName (obj)
References i, keys, and obj.
Variable Documentation
prettify
exports prettify = prettify
strict
use strict