backend/node_modules/object-hash/index.js File Reference
Functions
function objectHash (object, options)
function applyDefaults (object, sourceOptions)
function isNativeFunction (f)
function hash (object, options)
function typeHasher (options, writeTo, context)
function PassThrough ()
Variables
use strict
var crypto = require('crypto')
exports = module.exports = objectHash
exports sha1
exports keys
exports MD5
exports keysMD5
var hashes = crypto.getHashes ? crypto.getHashes().slice() : ['sha1', 'md5']
var encodings = ['buffer', 'hex', 'binary', 'base64']
exports writeToStream
Function Documentation
applyDefaults()
function applyDefaults (object, sourceOptions)
References encodings, false, hashes, i, and undefined.
hash()
function hash (object, options)
References buf, crypto, PassThrough, typeHasher(), and undefined.
isNativeFunction()
function isNativeFunction (f)
Check if the given function is a native function
References $, exp, f, i, s, and w.
objectHash()
function objectHash (object, options)
References applyDefaults(), and hash().
PassThrough()
function PassThrough ()
References b, buf, end, read, and write.
typeHasher()
function typeHasher (options, writeTo, context)
References _error, Array, bool, context, dispatch, entries, file, fn, i, isNativeFunction(), keys, length, map, object, PassThrough, str(), string, toString, type, typeHasher(), Uint8Array, url, value, and write.
Variable Documentation
crypto
var crypto = require('crypto')
encodings
var encodings = ['buffer', 'hex', 'binary', 'base64']
exports
exports = module.exports = objectHash
Exported function
Options:
algorithm hash algo to be used by this instance: *'sha1', 'md5'
excludeValues {true|*false} hash object keys, values ignored
encoding hash encoding, supports 'buffer', '*hex', 'binary', 'base64'
ignoreUnknown {true|*false} ignore unknown object types
replacer optional function that replaces values before hashing
respectFunctionProperties {*true|false} consider function properties when hashing
respectFunctionNames {*true|false} consider 'name' property of functions for hashing
respectType {*true|false} Respect special properties (prototype, constructor) when hashing to distinguish between types
unorderedArrays {true|*false} Sort all arrays before hashing
unorderedSets {*true|false} Sort Set and Map instances before hashing
= default
Parameters
{object} object value to hash
{object} options hashing options
Returns
{string} hash value @api public
hashes
var hashes = crypto.getHashes ? crypto.getHashes().slice() : ['sha1', 'md5']
keys
exports keys
Initial value:
= function(object){
  return objectHash(object, {excludeValues: true, algorithm: 'sha1', encoding: 'hex'});
}
keysMD5
exports keysMD5
Initial value:
= function(object){
  return objectHash(object, {algorithm: 'md5', encoding: 'hex', excludeValues: true});
}
MD5
exports MD5
Initial value:
= function(object){
  return objectHash(object, {algorithm: 'md5', encoding: 'hex'});
}
sha1
exports sha1
Initial value:
= function(object){
  return objectHash(object);
}
Exported sugar methods
Parameters
{object} object value to hash
Returns
{string} hash value @api public
strict
use strict
writeToStream
exports writeToStream
Initial value:
= function(object, options, stream) {
  if (typeof stream === 'undefined') {
    stream = options;
    options = {};
  }
  options = applyDefaults(object, options);
  return typeHasher(options, stream).dispatch(object);
}
Expose streaming API
Parameters
{object} object Value to serialize
{object} options Options, as for hash()
{object} stream A stream to write the serializiation to @api public