backend/node_modules/@google-cloud/firestore/build/src/order.js File Reference
Functions
function typeOrder (val)
function primitiveComparator (left, right)
function compareNumbers (left, right)
function compareNumberProtos (left, right)
function compareTimestamps (left, right)
function compareBlobs (left, right)
function compareReferenceProtos (left, right)
function compareGeoPoints (left, right)
function compareArrays (left, right)
function compareObjects (left, right)
function compareVectors (left, right)
function compare (left, right)
Variables
use strict
exports primitiveComparator = primitiveComparator
exports compareArrays = compareArrays
exports compare = compare
const convert_1 = require("./convert")
const path_1 = require("./path")
var TypeOrder
Function Documentation
compare()
function compare (left, right) [private]
References $, compareArrays, compareBlobs(), compareGeoPoints(), compareNumberProtos(), compareObjects(), compareReferenceProtos(), compareTimestamps(), compareVectors(), left, primitiveComparator, right, type, TypeOrder, and typeOrder().
compareArrays()
function compareArrays (left, right) [private]
References compare, i, left, primitiveComparator, and right.
compareBlobs()
function compareBlobs (left, right) [private]
References left, and right.
compareGeoPoints()
function compareGeoPoints (left, right) [private]
References left, primitiveComparator, and right.
compareNumberProtos()
function compareNumberProtos (left, right) [private]
References compareNumbers(), left, right, and undefined.
compareNumbers()
function compareNumbers (left, right) [private]
Utility function to compare doubles (using Firestore semantics for NaN).
References isNaN, left, and right.
compareObjects()
function compareObjects (left, right) [private]
References compare, i, left, primitiveComparator, and right.
compareReferenceProtos()
function compareReferenceProtos (left, right) [private]
References left, path_1, and right.
compareTimestamps()
function compareTimestamps (left, right) [private]
References left, primitiveComparator, and right.
compareVectors()
function compareVectors (left, right) [private]
References _a, _b, _c, _d, compareArrays, left, primitiveComparator, and right.
primitiveComparator()
function primitiveComparator (left, right) [private]
References left, and right.
typeOrder()
function typeOrder (val) [private]
References convert_1, and TypeOrder.
Variable Documentation
compare
exports compare = compare
compareArrays
exports compareArrays = compareArrays
convert_1
const convert_1 = require("./convert")
path_1
const path_1 = require("./path")
primitiveComparator
exports primitiveComparator = primitiveComparator
strict
use strict
TypeOrder
function TypeOrder
Initial value:
{
    TypeOrder[TypeOrder["NULL"] = 0] = "NULL"
The type order as defined by the backend.