backend/node_modules/fast-xml-parser/src/xmlbuilder/orderedJs2Xml.js File Reference
Functions
function toXml (jArray, options)
function arrToStr (arr, options, jPath, indentation)
function propName (obj)
function attr_to_str (attrMap, options)
function isStopNode (jPath, options)
function replaceEntitiesValue (textValue, options)
Variables
const EOL = "\n"
module exports = toXml
Function Documentation
arrToStr()
function arrToStr (arr, options, jPath, indentation)
References $, arrToStr(), attr_to_str(), i, isStopNode(), propName(), replaceEntitiesValue(), and undefined.
attr_to_str()
function attr_to_str (attrMap, options)
References $, and replaceEntitiesValue().
isStopNode()
function isStopNode (jPath, options)
References index.
propName()
function propName (obj)
References i, keys, and obj.
replaceEntitiesValue()
function replaceEntitiesValue (textValue, options)
References i.
toXml()
function toXml (jArray, options)
Parameters
{array} jArray
{any} options
Returns
References arrToStr(), and EOL.
Variable Documentation
EOL
const EOL = "\n"
exports
module exports = toXml