backend/node_modules/readable-stream/lib/internal/streams/pipeline.js File Reference
Functions
function once (callback)
function noop (err)
function isRequest (stream)
function destroyer (stream, reading, writing, callback)
function call (fn)
function pipe (from, to)
function popCallback (streams)
function pipeline ()
Variables
use strict
var eos
var _require$codes = require('../../../errors').codes
var ERR_MISSING_ARGS = _require$codes.ERR_MISSING_ARGS
var ERR_STREAM_DESTROYED = _require$codes.ERR_STREAM_DESTROYED
module exports = pipeline
Function Documentation
call()
function call (fn)
References fn.
destroyer()
function destroyer (stream, reading, writing, callback)
References callback, eos, ERR_STREAM_DESTROYED, isRequest, once, readable, require(), stream, undefined, and writable.
isRequest()
function isRequest (stream)
References stream.
noop()
function noop (err)
once()
function once (callback)
References callback.
pipe()
function pipe (from, to)
pipeline()
function pipeline ()
References Array, call, callback, destroyer(), ERR_MISSING_ARGS, error, i, pipe, popCallback(), stream, and streams.
popCallback()
function popCallback (streams)
References noop, and streams.
Variable Documentation
_require$codes
var _require$codes = require('../../../errors').codes
eos
var eos
ERR_MISSING_ARGS
var ERR_MISSING_ARGS = _require$codes.ERR_MISSING_ARGS
ERR_STREAM_DESTROYED
var ERR_STREAM_DESTROYED = _require$codes.ERR_STREAM_DESTROYED
exports
module exports = pipeline
strict
use strict