backend/node_modules/node-forge/lib/pkcs12.js File Reference
Functions
function _getBagsByAttribute (safeContents, attrName, attrValue, bagType)
function _decodePkcs7Data (data)
function _decodeAuthenticatedSafe (pfx, authSafe, strict, password)
function _decryptSafeContents (data, password)
function _decodeSafeContents (safeContents, strict, password)
function _decodeBagAttributes (attributes)
Variables
var forge = require('./forge')
var asn1 = forge.asn1
var pki = forge.pki
var p12 = module.exports = forge.pkcs12 = forge.pkcs12 || {}
var contentInfoValidator
var pfxValidator
var safeBagValidator
var attributeValidator
var certBagValidator
p12 pkcs12FromAsn1
p12 toPkcs12Asn1
p12 generateKey = forge.pbe.generatePkcs12Key
Function Documentation
_decodeAuthenticatedSafe()
function _decodeAuthenticatedSafe (pfx, authSafe, strict, password)
Decode PKCS#12 AuthenticatedSafe (BER encoded) into PFX object.
The AuthenticatedSafe is a BER-encoded SEQUENCE OF ContentInfo.
Parameters
pfx The PKCS#12 PFX object to fill.
{String} authSafe BER-encoded AuthenticatedSafe.
strict true to use strict DER decoding, false not to.
{String} password Password to decrypt with (optional).
References _decodePkcs7Data(), _decodeSafeContents(), _decryptSafeContents(), asn1, contentInfoValidator, data, error, errors, i, obj, pki, and strict.
_decodeBagAttributes()
function _decodeBagAttributes (attributes)
Decode PKCS#12 SET OF PKCS12Attribute into JavaScript object.
Parameters
attributes SET OF PKCS12Attribute (ASN.1 object).
Returns
the decoded attributes.
References asn1, attributeValidator, error, errors, i, j, pki, and undefined.
_decodePkcs7Data()
function _decodePkcs7Data (data)
Decodes PKCS#7 Data. PKCS#7 (RFC 2315) defines "Data" as an OCTET STRING, but it is sometimes an OCTET STRING that is composed/constructed of chunks, each its own OCTET STRING. This is BER-encoding vs. DER-encoding. This function transforms this corner-case into the usual simple, non-composed/constructed OCTET STRING.
This function may be moved to ASN.1 at some point to better deal with more BER-encoding issues, should they arise.
Parameters
data the ASN.1 Data object to transform.
References data, forge, i, and value.
_decodeSafeContents()
function _decodeSafeContents (safeContents, strict, password)
Decode PKCS#12 SafeContents (BER-encoded) into array of Bag objects.
The safeContents is a BER-encoded SEQUENCE OF SafeBag.
Parameters
{String} safeContents BER-encoded safeContents.
strict true to use strict DER decoding, false not to.
{String} password Password to decrypt with (optional).
Returns
{Array} Array of Bag objects.
References _decodeBagAttributes(), asn1, certBagValidator, decoder, e, error, errors, i, pki, res, safeBagValidator, strict, type, undefined, and validator.
_decryptSafeContents()
function _decryptSafeContents (data, password)
Decrypt PKCS#7 EncryptedData structure.
Parameters
data ASN.1 encoded EncryptedContentInfo object.
password The user-provided password.
Returns
The decrypted SafeContents (ASN.1 object).
References _decodePkcs7Data(), asn1, cipher, data, error, errors, forge, and pki.
_getBagsByAttribute()
function _getBagsByAttribute (safeContents, attrName, attrValue, bagType)
Search SafeContents structure for bags with matching attributes.
The search can optionally be narrowed by a certain bag type.
Parameters
safeContents the SafeContents structure to search in.
attrName the name of the attribute to compare against.
attrValue the attribute value to search for.
[bagType] bag type to narrow search by.
Returns
an array of matching bags.
References i, j, result, and undefined.
Variable Documentation
asn1
var asn1 = forge.asn1
attributeValidator
var attributeValidator
Initial value:
= {
  name: 'Attribute',
  tagClass: asn1.Class.UNIVERSAL,
  type: asn1.Type.SEQUENCE,
  constructed: true,
  value: [{
    name: 'Attribute.attrId',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.OID,
    constructed: false,
    capture: 'oid'
  }, {
    name: 'Attribute.attrValues',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.SET,
    constructed: true,
    capture: 'values'
  }]
}
certBagValidator
var certBagValidator
Initial value:
= {
  name: 'CertBag',
  tagClass: asn1.Class.UNIVERSAL,
  type: asn1.Type.SEQUENCE,
  constructed: true,
  value: [{
    name: 'CertBag.certId',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.OID,
    constructed: false,
    capture: 'certId'
  }, {
    name: 'CertBag.certValue',
    tagClass: asn1.Class.CONTEXT_SPECIFIC,
    constructed: true,
    
    value: [{
      name: 'CertBag.certValue[0]',
      tagClass: asn1.Class.UNIVERSAL,
      type: asn1.Class.OCTETSTRING,
      constructed: false,
      capture: 'cert'
    }]
  }]
}
contentInfoValidator
p7v contentInfoValidator
Initial value:
= {
  name: 'ContentInfo',
  tagClass: asn1.Class.UNIVERSAL,
  type: asn1.Type.SEQUENCE,
  constructed: true,
  value: [{
    name: 'ContentInfo.contentType',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.OID,
    constructed: false,
    capture: 'contentType'
  }, {
    name: 'ContentInfo.content',
    tagClass: asn1.Class.CONTEXT_SPECIFIC,
    constructed: true,
    captureAsn1: 'content'
  }]
}
forge
var forge = require('./forge')
Javascript implementation of PKCS#12.
Author
Dave Longley
Stefan Siegl stesie@brokenpipe.de
Copyright (c) 2010-2014 Digital Bazaar, Inc. Copyright (c) 2012 Stefan Siegl stesie@brokenpipe.de
The ASN.1 representation of PKCS#12 is as follows (see ftp://ftp.rsasecurity.com/pub/pkcs/pkcs-12/pkcs-12-tc1.pdf for details)
PFX ::= SEQUENCE { version INTEGER {v3(3)}(v3,...), authSafe ContentInfo, macData MacData OPTIONAL }
MacData ::= SEQUENCE { mac DigestInfo, macSalt OCTET STRING, iterations INTEGER DEFAULT 1 } Note: The iterations default is for historical reasons and its use is deprecated. A higher value, like 1024, is recommended.
DigestInfo is defined in PKCS#7 as follows:
DigestInfo ::= SEQUENCE { digestAlgorithm DigestAlgorithmIdentifier, digest Digest }
DigestAlgorithmIdentifier ::= AlgorithmIdentifier
The AlgorithmIdentifier contains an Object Identifier (OID) and parameters for the algorithm, if any. In the case of SHA1 there is none.
AlgorithmIdentifer ::= SEQUENCE { algorithm OBJECT IDENTIFIER, parameters ANY DEFINED BY algorithm OPTIONAL }
Digest ::= OCTET STRING
ContentInfo ::= SEQUENCE { contentType ContentType, content [0] EXPLICIT ANY DEFINED BY contentType OPTIONAL }
ContentType ::= OBJECT IDENTIFIER
AuthenticatedSafe ::= SEQUENCE OF ContentInfo -- Data if unencrypted -- EncryptedData if password-encrypted -- EnvelopedData if public key-encrypted
SafeContents ::= SEQUENCE OF SafeBag
SafeBag ::= SEQUENCE { bagId BAG-TYPE.&id ({PKCS12BagSet}) bagValue [0] EXPLICIT BAG-TYPE.&Type({PKCS12BagSet}{@bagId}), bagAttributes SET OF PKCS12Attribute OPTIONAL }
PKCS12Attribute ::= SEQUENCE { attrId ATTRIBUTE.&id ({PKCS12AttrSet}), attrValues SET OF ATTRIBUTE.&Type ({PKCS12AttrSet}{@attrId}) } -- This type is compatible with the X.500 type 'Attribute'
PKCS12AttrSet ATTRIBUTE ::= { friendlyName | -- from PKCS #9 localKeyId, -- from PKCS #9 ... -- Other attributes are allowed }
CertBag ::= SEQUENCE { certId BAG-TYPE.&id ({CertTypes}), certValue [0] EXPLICIT BAG-TYPE.&Type ({CertTypes}{@certId}) }
x509Certificate BAG-TYPE ::= {OCTET STRING IDENTIFIED BY {certTypes 1}} -- DER-encoded X.509 certificate stored in OCTET STRING
sdsiCertificate BAG-TYPE ::= {IA5String IDENTIFIED BY {certTypes 2}} -- Base64-encoded SDSI certificate stored in IA5String
CertTypes BAG-TYPE ::= { x509Certificate | sdsiCertificate, ... -- For future extensions }
generateKey
p12 generateKey = forge.pbe.generatePkcs12Key
Derives a PKCS#12 key.
Parameters
password the password to derive the key material from, null or undefined for none.
salt the salt, as a ByteBuffer, to use.
id the PKCS#12 ID byte (1 = key material, 2 = IV, 3 = MAC).
iter the iteration count.
n the number of bytes to derive from the password.
md the message digest to use, defaults to SHA-1.
Returns
a ByteBuffer with the bytes derived from the password.
p12
var p12 = module.exports = forge.pkcs12 = forge.pkcs12 || {}
pfxValidator
var pfxValidator
pkcs12FromAsn1
p12 pkcs12FromAsn1
Converts a PKCS#12 PFX in ASN.1 notation into a PFX object.
Parameters
obj The PKCS#12 PFX in ASN.1 notation.
strict true to use strict DER decoding, false not to (default: true).
{String} password Password to decrypt with (optional).
Returns
PKCS#12 PFX object.
pki
var pki = forge.pki
safeBagValidator
var safeBagValidator
Initial value:
= {
  name: 'SafeBag',
  tagClass: asn1.Class.UNIVERSAL,
  type: asn1.Type.SEQUENCE,
  constructed: true,
  value: [{
    name: 'SafeBag.bagId',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.OID,
    constructed: false,
    capture: 'bagId'
  }, {
    name: 'SafeBag.bagValue',
    tagClass: asn1.Class.CONTEXT_SPECIFIC,
    constructed: true,
    captureAsn1: 'bagValue'
  }, {
    name: 'SafeBag.bagAttributes',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.SET,
    constructed: true,
    optional: true,
    capture: 'bagAttributes'
  }]
}
toPkcs12Asn1
p12 toPkcs12Asn1
Wraps a private key and certificate in a PKCS#12 PFX wrapper. If a password is provided then the private key will be encrypted.
An entire certificate chain may also be included. To do this, pass an array for the "cert" parameter where the first certificate is the one that is paired with the private key and each subsequent one verifies the previous one. The certificates may be in PEM format or have been already parsed by Forge.
Todo
Todo implement password-based-encryption for the whole package
Parameters
key the private key.
cert the certificate (may be an array of certificates in order to specify a certificate chain).
password the password to use, null for none.
options algorithm the encryption algorithm to use ('aes128', 'aes192', 'aes256', '3des'), defaults to 'aes128'. count the iteration count to use. saltSize the salt size to use. useMac true to include a MAC, false not to, defaults to true. localKeyId the local key ID to use, in hex. friendlyName the friendly name to use. generateLocalKeyId true to generate a random local key ID, false not to, defaults to true.
Returns
the PKCS#12 PFX ASN.1 object.