backend/node_modules/node-forge/lib/pkcs7.js File Reference
Functions
function _recipientFromAsn1 (obj)
function _recipientToAsn1 (obj)
function _recipientsFromAsn1 (infos)
function _recipientsToAsn1 (recipients)
function _signerFromAsn1 (obj)
function _signerToAsn1 (obj)
function _signersFromAsn1 (signerInfoAsn1s)
function _signersToAsn1 (signers)
function _attributeToAsn1 (attr)
function _encryptedContentToAsn1 (ec)
function _fromAsn1 (msg, obj, validator)
function _decryptContent (msg)
Variables
var forge = require('./forge')
var asn1 = forge.asn1
var p7 = module.exports = forge.pkcs7 = forge.pkcs7 || {}
p7 messageFromPem
p7 messageToPem
p7 messageFromAsn1
p7 createSignedData
p7 createEncryptedData
p7 createEnvelopedData
Function Documentation
_attributeToAsn1()
function _attributeToAsn1 (attr)
Convert an attribute object to an ASN.1 Attribute.
Parameters
attr the attribute object.
Returns
the ASN.1 Attribute.
References asn1, forge, isNaN, jan_1_1950, jan_1_2050, timestamp, and value.
_decryptContent()
function _decryptContent (msg)
Decrypt the symmetrically encrypted content block of the PKCS#7 message.
Decryption is skipped in case the PKCS#7 message object already has a (decrypted) content attribute. The algorithm, key and cipher parameters (probably the iv) are taken from the encryptedContent attribute of the message object.
Parameters
The PKCS#7 message object.
References forge, msg, and undefined.
_encryptedContentToAsn1()
function _encryptedContentToAsn1 (ec)
Map messages encrypted content to ASN.1 objects.
Parameters
ec The encryptedContent object of the message.
Returns
ASN.1 representation of the encryptedContent object (SEQUENCE).
References asn1, forge, and undefined.
_fromAsn1()
function _fromAsn1 (msg, obj, validator)
Reads the "common part" of an PKCS#7 content block (in ASN.1 format)
This function reads the "common part" of the PKCS#7 content blocks EncryptedData and EnvelopedData, i.e. version number and symmetrically encrypted content block.
The result of the ASN.1 validate and capture process is returned to allow the caller to extract further data, e.g. the list of recipients in case of a EnvelopedData object.
Parameters
msg the PKCS#7 object to read the data to.
obj the ASN.1 representation of the content block.
validator the ASN.1 structure validator object to use.
Returns
the value map captured by validator object.
References asn1, contentType, error, errors, forge, i, msg, obj, and validator.
_recipientFromAsn1()
function _recipientFromAsn1 (obj)
Converts a single recipient from an ASN.1 object.
Parameters
obj the ASN.1 RecipientInfo.
Returns
the recipient object.
References asn1, error, errors, forge, obj, p7, undefined, and version.
_recipientsFromAsn1()
function _recipientsFromAsn1 (infos)
Map a set of RecipientInfo ASN.1 objects to recipient objects.
Parameters
infos an array of ASN.1 representations RecipientInfo (i.e. SET OF).
Returns
an array of recipient objects.
References _recipientFromAsn1(), and i.
_recipientsToAsn1()
function _recipientsToAsn1 (recipients)
Map an array of recipient objects to ASN.1 RecipientInfo objects.
Parameters
recipients an array of recipientInfo objects.
Returns
an array of ASN.1 RecipientInfos.
References _recipientToAsn1(), and i.
_recipientToAsn1()
function _recipientToAsn1 (obj)
Converts a single recipient object to an ASN.1 object.
Parameters
obj the recipient object.
Returns
the ASN.1 RecipientInfo.
References asn1, forge, and obj.
_signerFromAsn1()
function _signerFromAsn1 (obj)
Converts a single signer from an ASN.1 object.
Parameters
obj the ASN.1 representation of a SignerInfo.
Returns
the signer object.
References asn1, error, errors, forge, obj, p7, signature, and version.
_signersFromAsn1()
function _signersFromAsn1 (signerInfoAsn1s)
Map a set of SignerInfo ASN.1 objects to an array of signer objects.
Parameters
signerInfoAsn1s an array of ASN.1 SignerInfos (i.e. SET OF).
Returns
an array of signers objects.
References _signerFromAsn1(), and i.
_signersToAsn1()
function _signersToAsn1 (signers)
Map an array of signer objects to ASN.1 objects.
Parameters
signers an array of signer objects.
Returns
an array of ASN.1 SignerInfos.
References _signerToAsn1(), and i.
_signerToAsn1()
function _signerToAsn1 (obj)
Converts a single signerInfo object to an ASN.1 object.
Parameters
obj the signerInfo object.
Returns
the ASN.1 representation of a SignerInfo.
References _attributeToAsn1(), asn1, forge, i, and obj.
Variable Documentation
asn1
var asn1 = forge.asn1
createEncryptedData
p7 createEncryptedData
Initial value:
= function() {
  var msg = null;
  msg = {
    type: forge.pki.oids.encryptedData,
    version: 0,
    encryptedContent: {
      algorithm: forge.pki.oids['aes256-CBC']
    },
    
    fromAsn1: function(obj) {
      
      _fromAsn1(msg, obj, p7.asn1.encryptedDataValidator);
    },
    
    decrypt: function(key) {
      if(key !== undefined) {
        msg.encryptedContent.key = key;
      }
      _decryptContent(msg);
    }
  };
  return msg;
}
Creates an empty PKCS#7 message of type EncryptedData.
Returns
the message.
createEnvelopedData
p7 createEnvelopedData
Creates an empty PKCS#7 message of type EnvelopedData.
Returns
the message.
createSignedData
p7 createSignedData
forge
var forge = require('./forge')
Javascript implementation of PKCS#7 v1.5.
Author
Stefan Siegl
Dave Longley
Copyright (c) 2012 Stefan Siegl stesie@brokenpipe.de Copyright (c) 2012-2015 Digital Bazaar, Inc.
Currently this implementation only supports ContentType of EnvelopedData, EncryptedData, or SignedData at the root level. The top level elements may contain only a ContentInfo of ContentType Data, i.e. plain data. Further nesting is not (yet) supported.
The Forge validators for PKCS #7's ASN.1 structures are available from a separate file pkcs7asn1.js, since those are referenced from other PKCS standards like PKCS #12.
messageFromAsn1
p7 messageFromAsn1
Converts a PKCS#7 message from an ASN.1 object.
Parameters
obj the ASN.1 representation of a ContentInfo.
Returns
the PKCS#7 message.
messageFromPem
p7 messageFromPem
Initial value:
= function(pem) {
  var msg = forge.pem.decode(pem)[0];
  if(msg.type !== 'PKCS7') {
    var error = new Error('Could not convert PKCS#7 message from PEM; PEM ' +
      'header type is not "PKCS#7".');
    error.headerType = msg.type;
    throw error;
  }
  if(msg.procType && msg.procType.type === 'ENCRYPTED') {
    throw new Error('Could not convert PKCS#7 message from PEM; PEM is encrypted.');
  }
  
  var obj = asn1.fromDer(msg.body);
  return p7.messageFromAsn1(obj);
}
Converts a PKCS#7 message from PEM format.
Parameters
pem the PEM-formatted PKCS#7 message.
Returns
the PKCS#7 message.
messageToPem
p7 messageToPem
Initial value:
= function(msg, maxline) {
  
  var pemObj = {
    type: 'PKCS7',
    body: asn1.toDer(msg.toAsn1()).getBytes()
  };
  return forge.pem.encode(pemObj, {maxline: maxline});
}
Converts a PKCS#7 message to PEM format.
Parameters
msg The PKCS#7 message object
maxline The maximum characters per line, defaults to 64.
Returns
The PEM-formatted PKCS#7 message.
p7
var p7 = module.exports = forge.pkcs7 = forge.pkcs7 || {}