backend/node_modules/concurrently/dist/src/prefix-color-selector.js File Reference
Classes
class PrefixColorSelector
Functions
function getConsoleColorsWithoutCustomColors (customColors)
function * createColorGenerator (customColors)
Variables
use strict
exports PrefixColorSelector = void 0
Function Documentation
createColorGenerator()
function * createColorGenerator (customColors)
Creates a generator that yields an infinite stream of colors.
References PrefixColorSelector::ACCEPTABLE_CONSOLE_COLORS(), getConsoleColorsWithoutCustomColors(), and of.
getConsoleColorsWithoutCustomColors()
function getConsoleColorsWithoutCustomColors (customColors)
References PrefixColorSelector::ACCEPTABLE_CONSOLE_COLORS().
Variable Documentation
PrefixColorSelector
exports PrefixColorSelector = void 0
strict
use strict