backend/node_modules/node-forge/lib/prime.worker.js File Reference
Functions
function findPrime (data)
function isProbablePrime (n)
function runMillerRabin (n)
function getPrng ()
function _getMillerRabinTests (bits)
Variables
var forge = require('./forge')
var LOW_PRIMES = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997]
var LP_LIMIT = (1 << 26) / LOW_PRIMES[LOW_PRIMES.length - 1]
var BigInteger = forge.jsbn.BigInteger
var BIG_TWO = new BigInteger(null)
var GCD_30_DELTA = [6, 4, 2, 4, 2, 4, 6, 2]
Function Documentation
_getMillerRabinTests()
function _getMillerRabinTests (bits)
Returns the required number of Miller-Rabin tests to generate a prime with an error probability of (1/2)^80.
See Handbook of Applied Cryptography Chapter 4, Table 4.4.
Parameters
bits the bit size.
Returns
the required number of iterations.
findPrime()
function findPrime (data)
References BigInteger, data, GCD_30_DELTA, i, and isProbablePrime.
getPrng()
function getPrng ()
References i.
isProbablePrime()
function isProbablePrime (n)
References i, j, LOW_PRIMES, LP_LIMIT, m, n, and runMillerRabin().
runMillerRabin()
function runMillerRabin (n)
References _getMillerRabinTests(), a, BigInteger, d, getPrng(), i, j, k, n, prng, and s.
Variable Documentation
BIG_TWO
var BIG_TWO = new BigInteger(null)
BigInteger
var BigInteger = forge.jsbn.BigInteger
forge
var forge = require('./forge')
RSA Key Generation Worker.
Author
Dave Longley
Copyright (c) 2013 Digital Bazaar, Inc.
GCD_30_DELTA
var GCD_30_DELTA = [6, 4, 2, 4, 2, 4, 6, 2]
LOW_PRIMES
var LOW_PRIMES = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997]
LP_LIMIT
var LP_LIMIT = (1 << 26) / LOW_PRIMES[LOW_PRIMES.length - 1]