backend/node_modules/node-forge/lib/prime.js File Reference
Functions
function primeincFindPrime (bits, rng, options, callback)
function primeincFindPrimeWithoutWorkers (bits, rng, options, callback)
function _primeinc (num, bits, rng, deltaIdx, mrTests, maxBlockTime, callback)
function primeincFindPrimeWithWorkers (bits, rng, options, callback)
function generateRandom (bits, rng)
function getMillerRabinTests (bits)
Variables
var forge = require('./forge')
var BigInteger = forge.jsbn.BigInteger
var GCD_30_DELTA = [6, 4, 2, 4, 2, 4, 6, 2]
var THIRTY = new BigInteger(null)
var op_or = function(x, y) {return x|y;}
prime generateProbablePrime
Function Documentation
_primeinc()
function _primeinc (num, bits, rng, deltaIdx, mrTests, maxBlockTime, callback)
References _primeinc(), callback, forge, GCD_30_DELTA, generateRandom(), rng(), and start.
generateRandom()
function generateRandom (bits, rng)
Generates a random number using the given number of bits and RNG.
Parameters
bits the number of bits for the number.
rng the random number generator to use.
Returns
the random number.
References BigInteger, op_or, rng(), and THIRTY.
getMillerRabinTests()
function getMillerRabinTests (bits)
Returns the required number of Miller-Rabin tests to generate a prime with an error probability of (1/2)^80.
See Handbook of Applied Cryptography Chapter 4, Table 4.4.
Parameters
bits the bit size.
Returns
the required number of iterations.
primeincFindPrime()
function primeincFindPrime (bits, rng, options, callback)
References callback, primeincFindPrimeWithoutWorkers(), primeincFindPrimeWithWorkers(), and rng().
primeincFindPrimeWithoutWorkers()
function primeincFindPrimeWithoutWorkers (bits, rng, options, callback)
References _primeinc(), callback, generateRandom(), getMillerRabinTests(), and rng().
primeincFindPrimeWithWorkers()
function primeincFindPrimeWithWorkers (bits, rng, options, callback)
References BigInteger, callback, data, e, forge, generate, generateRandom(), hex, i, primeincFindPrimeWithoutWorkers(), range, and rng().
Variable Documentation
BigInteger
var BigInteger = forge.jsbn.BigInteger
forge
var forge = require('./forge')
Prime number generation API.
Author
Dave Longley
Copyright (c) 2014 Digital Bazaar, Inc.
GCD_30_DELTA
var GCD_30_DELTA = [6, 4, 2, 4, 2, 4, 6, 2]
generateProbablePrime
prime generateProbablePrime
Generates a random probable prime with the given number of bits.
Alternative algorithms can be specified by name as a string or as an object with custom options like so:
{ name: 'PRIMEINC', options: { maxBlockTime: <the maximum amount of time to block the main thread before allowing I/O other JS to run>, millerRabinTests: <the number of miller-rabin tests to run>, workerScript: <the worker script URL>, workers: <the number of web workers (if supported) to use, -1 to use estimated cores minus one>. workLoad: the size of the work load, ie: number of possible prime numbers for each web worker to check per work assignment, (default: 100). } }
Parameters
bits the number of bits for the prime number.
options the options to use. [algorithm] the algorithm to use (default: 'PRIMEINC'). [prng] a custom crypto-secure pseudo-random number generator to use, that must define "getBytesSync".
Returns
callback(err, num) called once the operation completes.
op_or
var op_or = function(x, y) {return x|y;}
THIRTY
var THIRTY = new BigInteger(null)