backend/node_modules/yargs/build/lib/utils/process-argv.js File Reference
Functions
function getProcessArgvBinIndex ()
function isBundledElectronApp ()
function isElectronApp ()
function export hideBin (argv)
function export getProcessArgvBin ()
Function Documentation
getProcessArgvBin()
function export getProcessArgvBin ()
References getProcessArgvBinIndex(), and process.
getProcessArgvBinIndex()
function getProcessArgvBinIndex ()
References isBundledElectronApp().
hideBin()
function export hideBin (argv)
References getProcessArgvBinIndex().
isBundledElectronApp()
function isBundledElectronApp ()
References isElectronApp(), and process.
isElectronApp()
function isElectronApp ()
References process.