backend/node_modules/protobufjs/src/parse.js File Reference
Functions
function parse (source, root, options)
Variables
use strict
module exports = parse
parse filename = null
parse defaults = { keepCase: false }
var tokenize = require("./tokenize")
var Root = require("./root")
var Type = require("./type")
var Field = require("./field")
var MapField = require("./mapfield")
var OneOf = require("./oneof")
var Enum = require("./enum")
var Service = require("./service")
var Method = require("./method")
var types = require("./types")
var util = require("./util")
var base10Re = /^[1-9][0-9]*$/
var base10NegRe = /^-?[1-9][0-9]*$/
var base16Re = /^0[x][0-9a-fA-F]+$/
var base16NegRe = /^-?0[x][0-9a-fA-F]+$/
var base8Re = /^0[0-7]+$/
var base8NegRe = /^-?0[0-7]+$/
var numberRe = /^(?![eE])[0-9]*(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?$/
var nameRe = /^[a-zA-Z_][a-zA-Z_0-9]*$/
var typeRefRe = /^(?:\.?[a-zA-Z_][a-zA-Z_0-9]*)(?:\.[a-zA-Z_][a-zA-Z_0-9]*)*$/
var fqTypeRefRe = /^(?:\.[a-zA-Z_][a-zA-Z_0-9]*)+$/
Function Documentation
parse()
function parse (source, root, options)
References base10NegRe, base10Re, base16NegRe, base16Re, base8NegRe, base8Re, cmnt(), e, Enum, extend, Field, filename, fqTypeRefRe, head, imports, MapField, Method, method, name, nameRe, next(), numberRe, obj, OneOf, parent, parse, parseInt(), peek, pkg, propName(), push, Root, root, Service, setOption, setParsedOption, sign, skip, source, start, startsWith(), token, tokenize, Type, type, typeRefRe, types, undefined, util, value, and values.
Variable Documentation
base10NegRe
var base10NegRe = /^-?[1-9][0-9]*$/
base10Re
var base10Re = /^[1-9][0-9]*$/
base16NegRe
var base16NegRe = /^-?0[x][0-9a-fA-F]+$/
base16Re
var base16Re = /^0[x][0-9a-fA-F]+$/
base8NegRe
var base8NegRe = /^-?0[0-7]+$/
base8Re
var base8Re = /^0[0-7]+$/
defaults
parse defaults = { keepCase: false }
Enum
var Enum = require("./enum")
exports
module exports = parse
Field
var Field = require("./field")
filename
parse filename = null
fqTypeRefRe
var fqTypeRefRe = /^(?:\.[a-zA-Z_][a-zA-Z_0-9]*)+$/
MapField
var MapField = require("./mapfield")
Method
var Method = require("./method")
nameRe
var nameRe = /^[a-zA-Z_][a-zA-Z_0-9]*$/
numberRe
var numberRe = /^(?![eE])[0-9]*(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?$/
OneOf
var OneOf = require("./oneof")
Root
var Root = require("./root")
Service
var Service = require("./service")
strict
use strict
tokenize
var tokenize = require("./tokenize")
Type
var Type = require("./type")
typeRefRe
var typeRefRe = /^(?:\.?[a-zA-Z_][a-zA-Z_0-9]*)(?:\.[a-zA-Z_][a-zA-Z_0-9]*)*$/
types
var types = require("./types")
util
var util = require("./util")