backend/node_modules/protobufjs/dist/light/protobuf.js File Reference
Functions
function prelude (modules, cache, entries)
Variables
function undefined {"use strict"
util ucFirst
var camelCaseRe = /_([a-z])/g
util camelCase
util compareFieldsById
util decorateType
var decorateEnumIndex = 0
util decorateEnum
util setProperty
Function Documentation
prelude()
function prelude (modules, cache, entries)
References $, add, addJSON, alloc, args, Array, arrayToJSON, asPromise, b, b64, base64, buf, buffer, bytes, c, callback, charCodeAt, chunk(), clearCache(), codegen, comments, configure, converter, create, decode, decodeDelimited, decoder, define, e, emit, encode, encodeDelimited, encoder, end, entries, Enum, EventEmitter, exports, extend, factory, fetch, Field, filename, Float32Array, Float64Array, fn, fromJSON, fromObject, fs, g, genTypePartial(), genValuePartial_fromObject(), genValuePartial_toObject(), getEnum, i, index, inquire, invalidEncoding, isAbsolute, isNaN, isReservedId, isReservedName, j, JSON, keys, le, length, load, loadSync, Long, lookup, lookupEnum, lookupService, lookupType, lookupTypeOrEnum, map, MapField, MAX, Message, message, Method, missing(), mod, module, modules, n, name, names, Namespace, normalize, obj, object, EventEmitter::off(), off, EventEmitter::on(), on, OneOf, p, parent, path, pending, pool, prefix, prelude(), Promise, prop, protobuf, prototype, push, readUintBE(), readUintLE(), ReflectionObject, reject(), replace, require(), reserved, resolve, resolveAll, resolved, root, ruleRe, s64, Service, setOption, sign, size, slice, source, start, t, test, toJSON, toJSONOptions, toObject, toString, Type, type, types, Uint8Array, undefined, utf8, util, value, values, verify, w, writeUintBE(), writeUintLE(), and xhr.
Variable Documentation
camelCase
util camelCase
Initial value:
= function camelCase(str) {
    return str.substring(0, 1)
         + str.substring(1)
               .replace(camelCaseRe, function($0, $1) { return $1.toUpperCase(); });
}
Converts a string to camel case.
Parameters
{string} str String to convert
Returns
{string} Converted string
camelCaseRe
var camelCaseRe = /_([a-z])/g
compareFieldsById
util compareFieldsById
Initial value:
= function compareFieldsById(a, b) {
    return a.id - b.id;
}
Compares reflected fields by id.
Parameters
{Field} a First field
{Field} b Second field
Returns
{number} Comparison value
decorateEnum
util decorateEnum
Initial value:
= function decorateEnum(object) {
    
    if (object.$type)
        return object.$type;
    
    if (!Enum)
        Enum = require(14);
    var enm = new Enum("Enum" + decorateEnumIndex++, object);
    util.decorateRoot.add(enm);
    Object.defineProperty(object, "$type", { value: enm, enumerable: false });
    return enm;
}
Decorator helper for enums (TypeScript).
Parameters
{Object} object Enum object
Returns
{Enum} Reflected enum
decorateEnumIndex
var decorateEnumIndex = 0
decorateType
util decorateType
Initial value:
= function decorateType(ctor, typeName) {
    
    if (ctor.$type) {
        if (typeName && ctor.$type.name !== typeName) {
            util.decorateRoot.remove(ctor.$type);
            ctor.$type.name = typeName;
            util.decorateRoot.add(ctor.$type);
        }
        return ctor.$type;
    }
    
    if (!Type)
        Type = require(31);
    var type = new Type(typeName || ctor.name);
    util.decorateRoot.add(type);
    type.ctor = ctor;
    Object.defineProperty(ctor, "$type", { value: type, enumerable: false });
    Object.defineProperty(ctor.prototype, "$type", { value: type, enumerable: false });
    return type;
}
setProperty
util setProperty
Initial value:
= function setProperty(dst, path, value) {
    function setProp(dst, path, value) {
        var part = path.shift();
        if (part === "__proto__" || part === "prototype") {
          return dst;
        }
        if (path.length > 0) {
            dst[part] = setProp(dst[part] || {}, path, value);
        } else {
            var prevValue = dst[part];
            if (prevValue)
                value = [].concat(prevValue).concat(value);
            dst[part] = value;
        }
        return dst;
    }
    if (typeof dst !== "object")
        throw TypeError("dst must be an object");
    if (!path)
        throw TypeError("path must be specified");
    path = path.split(".");
    return setProp(dst, path, value);
}
Sets the value of a property by property path. If a value already exists, it is turned to an array
Parameters
{Object.<string,*>} dst Destination object
{string} path dot '.' delimited path of the property to set
{Object} value the value to set
Returns
{Object.<string,*>} Destination object
ucFirst
util ucFirst
Initial value:
= function ucFirst(str) {
    return str.charAt(0).toUpperCase() + str.substring(1);
}
Converts the first character of a string to upper case.
Parameters
{string} str String to convert
Returns
{string} Converted string
undefined
function undefined {"use strict"
protobuf.js v7.4.0 (c) 2016, daniel wirtz compiled thu, 22 aug 2024 20:30:39 utc licensed under the bsd-3-clause license see: https://github.com/dcodeio/protobuf.js for details