backend/node_modules/protobufjs/ext/descriptor/index.js File Reference
Functions
function Root_toDescriptorRecursive (ns, files, syntax)
function fromDescriptorType (type)
function packableDescriptorType (type)
function toDescriptorType (type, resolvedType)
function fromDescriptorOptions (options, type)
function toDescriptorOptions (options, type)
function shortname (from, to)
function underScore (str)
Variables
use strict
var $protobuf = require("../..")
module exports = exports = $protobuf.descriptor = $protobuf.Root.fromJSON(require("../../google/protobuf/descriptor.json")).lookup(".google.protobuf")
var Namespace = $protobuf.Namespace
var Root = $protobuf.Root
var Enum = $protobuf.Enum
var Type = $protobuf.Type
var Field = $protobuf.Field
var MapField = $protobuf.MapField
var OneOf = $protobuf.OneOf
var Service = $protobuf.Service
var Method = $protobuf.Method
Root fromDescriptor
Root prototype toDescriptor
var unnamedMessageIndex = 0
var numberRe = /^(?![eE])[0-9]*(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?$/
var unnamedEnumIndex = 0
var unnamedOneofIndex = 0
var unnamedServiceIndex = 0
var unnamedMethodIndex = 0
Function Documentation
fromDescriptorOptions()
function fromDescriptorOptions (options, type)
References $protobuf, Enum, i, type, undefined, and underScore().
fromDescriptorType()
function fromDescriptorType (type)
References type.
packableDescriptorType()
function packableDescriptorType (type)
References type.
Root_toDescriptorRecursive()
function Root_toDescriptorRecursive (ns, files, syntax)
References Enum, exports, Field, file, g, i, name, Namespace, replace, Root, Root_toDescriptorRecursive(), toDescriptorOptions(), and Type.
shortname()
function shortname (from, to)
References i, j, k, Namespace, Root, and toPath().
toDescriptorOptions()
function toDescriptorOptions (options, type)
References $protobuf, i, type, and undefined.
toDescriptorType()
function toDescriptorType (type, resolvedType)
References Enum, Type, and type.
underScore()
function underScore (str)
References $, a, g, str(), and Z().
Variable Documentation
$protobuf
var $protobuf = require("../..")
Enum
var Enum = $protobuf.Enum
exports
module exports = exports = $protobuf.descriptor = $protobuf.Root.fromJSON(require("../../google/protobuf/descriptor.json")).lookup(".google.protobuf")
Field
var Field = $protobuf.Field
fromDescriptor
Method fromDescriptor
Creates a root from a descriptor set.
Parameters
{IFileDescriptorSet|Reader|Uint8Array} descriptor Descriptor
Returns
{Root} Root instance
Creates a type from a descriptor.
Parameters
{IDescriptorProto|Reader|Uint8Array} descriptor Descriptor
{string} [syntax="proto2"] Syntax
Returns
{Type} Type instance
Creates a field from a descriptor.
Parameters
{IFieldDescriptorProto|Reader|Uint8Array} descriptor Descriptor
{string} [syntax="proto2"] Syntax
Returns
{Field} Field instance
Creates an enum from a descriptor.
Parameters
{IEnumDescriptorProto|Reader|Uint8Array} descriptor Descriptor
Returns
{Enum} Enum instance
Creates a oneof from a descriptor.
Parameters
{IOneofDescriptorProto|Reader|Uint8Array} descriptor Descriptor
Returns
{OneOf} OneOf instance
Creates a service from a descriptor.
Parameters
{IServiceDescriptorProto|Reader|Uint8Array} descriptor Descriptor
Returns
{Service} Service instance
Creates a method from a descriptor.
Parameters
{IMethodDescriptorProto|Reader|Uint8Array} descriptor Descriptor
Returns
{Method} Reflected method instance
MapField
var MapField = $protobuf.MapField
Method
var Method = $protobuf.Method
Namespace
var Namespace = $protobuf.Namespace
numberRe
var numberRe = /^(?![eE])[0-9]*(?:\.[0-9]*)?(?:[eE][+-]?[0-9]+)?$/
OneOf
var OneOf = $protobuf.OneOf
Root
var Root = $protobuf.Root
Examples
/Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/firestore/build/src/reference/document-reference.js, and /Users/nicoletiokhin/Desktop/Software Semester 3/Gamified-Programming-1/backend/node_modules/@google-cloud/firestore/build/src/reference/query.js.
Service
var Service = $protobuf.Service
strict
use strict
toDescriptor
Method prototype toDescriptor
Initial value:
= function toDescriptor(syntax) {
    var set = exports.FileDescriptorSet.create();
    Root_toDescriptorRecursive(this, set.file, syntax);
    return set;
}
Converts a root to a descriptor set.
Returns
{Message<IFileDescriptorSet>} Descriptor
Parameters
{string} [syntax="proto2"] Syntax
Converts a type to a descriptor.
Returns
{Message<IDescriptorProto>} Descriptor
Parameters
{string} [syntax="proto2"] Syntax
Converts a field to a descriptor.
Returns
{Message<IFieldDescriptorProto>} Descriptor
Parameters
{string} [syntax="proto2"] Syntax
Converts an enum to a descriptor.
Returns
{Message<IEnumDescriptorProto>} Descriptor
Converts a oneof to a descriptor.
Returns
{Message<IOneofDescriptorProto>} Descriptor
Converts a service to a descriptor.
Returns
{Message<IServiceDescriptorProto>} Descriptor
Converts a method to a descriptor.
Returns
{Message<IMethodDescriptorProto>} Descriptor
Type
var Type = $protobuf.Type
unnamedEnumIndex
var unnamedEnumIndex = 0
unnamedMessageIndex
var unnamedMessageIndex = 0
unnamedMethodIndex
var unnamedMethodIndex = 0
unnamedOneofIndex
var unnamedOneofIndex = 0
unnamedServiceIndex
var unnamedServiceIndex = 0