backend/node_modules/@grpc/proto-loader/build/bin/proto-loader-gen-types.js File Reference
Classes
class TextFormatter
Functions
function compareName (x, y)
function isNamespaceBase (obj)
function stripLeadingPeriod (name)
function getImportPath (to)
function getPath (to)
function getPathToRoot (from)
function getRelativeImportPath (from, to)
function getTypeInterfaceName (type)
function getImportLine (dependency, from, options)
function getChildMessagesAndEnums (namespace)
function formatComment (formatter, comment, options)
Variables
use strict
const fs = require("fs")
const path = require("path")
const Protobuf = require("protobufjs")
const yargs = require("yargs")
const camelCase = require("lodash.camelcase")
const util_1 = require("../src/util")
const templateStr = "%s"
const useNameFmter
Function Documentation
compareName()
function compareName (x, y)
References y.
formatComment()
function formatComment (formatter, comment, options)
This is a list of methods that are exist in the generic Client class in the gRPC libraries. TypeScript has a problem with methods in subclasses with the same names as methods in the superclass, but with mismatched APIs. So, we avoid generating methods with these names in the service client interfaces. We always generate two service client methods per service method: one camel cased, and one with the original casing. So we will still generate one service client method for any conflicting name.
Technically, at runtime conflicting name in the service client method actually shadows the original method, but TypeScript does not have a good way to represent that. So this change is not 100% accurate, but it gets the generated code to compile.
This is just a list of the methods in the Client class definitions in grpc@1.24.11 and @grpc/grpc-js@1.4.0.
getChildMessagesAndEnums()
function getChildMessagesAndEnums (namespace)
References getChildMessagesAndEnums(), isNamespaceBase(), of, and Protobuf.
getImportLine()
function getImportLine (dependency, from, options)
References $, Client, getImportPath(), getRelativeImportPath(), getTypeInterfaceName(), Protobuf, type, undefined, and useNameFmter.
getImportPath()
function getImportPath (to)
References g, getImportPath(), Protobuf, and stripLeadingPeriod().
getPath()
function getPath (to)
References g, and stripLeadingPeriod().
getPathToRoot()
function getPathToRoot (from)
References i, path, and stripLeadingPeriod().
getRelativeImportPath()
function getRelativeImportPath (from, to)
References getImportPath(), and getPathToRoot().
getTypeInterfaceName()
function getTypeInterfaceName (type)
References g, and type.
isNamespaceBase()
function isNamespaceBase (obj)
References Array, and obj.
stripLeadingPeriod()
function stripLeadingPeriod (name)
References name.
Variable Documentation
camelCase
const camelCase = require("lodash.camelcase")
fs
const fs = require("fs")
path
const path = require("path")
Protobuf
const Protobuf = require("protobufjs")
strict
use strict
templateStr
const templateStr = "%s"
useNameFmter
const useNameFmter
Initial value:
= ({ outputTemplate, inputTemplate }) => {
    if (outputTemplate === inputTemplate) {
        throw new Error('inputTemplate and outputTemplate must differ');
    }
    return {
        outputName: (n) => outputTemplate.replace(templateStr, n),
        inputName: (n) => inputTemplate.replace(templateStr, n)
    };
}
util_1
const util_1 = require("../src/util")
yargs
const yargs = require("yargs")