backend/node_modules/protobufjs/src/reader.js File Reference
Functions
function indexOutOfRange (reader, writeLength)
function Reader (buffer)
function readLongVarint ()
Variables
use strict
module exports = Reader
var util = require("./util/minimal")
var BufferReader
var LongBits = util.LongBits
var utf8 = util.utf8
var create_array
var create
Reader prototype _slice = util.Array.prototype.subarray || util.Array.prototype.slice
Reader prototype uint32
Reader prototype int32
Reader prototype sint32
 Reader#sfixed64
Reads zig-zag encoded fixed 64 bits.
@function
Returns
{Long} Value read
Reader prototype float
Reader prototype double
Reader prototype bytes
Reader prototype string
Reader prototype skip
Reader prototype skipType
Reader _configure
Reader#sint64
Reads a zig-zag encoded varint as a signed 64 bit value.
@function
Returns
{Long} Value read
Reader prototype bool
Reader prototype fixed32
Reader prototype sfixed32
function readFixed32_end (buf, end)
function readFixed64 ()
Function Documentation
indexOutOfRange()
function indexOutOfRange (reader, writeLength)
Reader()
function Reader (buffer)
Constructs a new reader instance using the specified buffer. @classdesc Wire format reader using Uint8Array if available, otherwise Array. @constructor
Parameters
{Uint8Array} buffer Buffer to read from
Read buffer. @type {Uint8Array}
Read buffer position. @type {number}
Read buffer length. @type {number}
References buf, and buffer.
readFixed32_end()
function readFixed32_end (buf, end)
References buf, and end.
readFixed64()
function readFixed64 ()
References buf, indexOutOfRange(), LongBits, and readFixed32_end().
readLongVarint()
function readLongVarint ()
References buf, i, indexOutOfRange(), and LongBits.
Variable Documentation
_configure
Reader _configure
Initial value:
= function(BufferReader_) {
    BufferReader = BufferReader_;
    Reader.create = create();
    BufferReader._configure();
    var fn = util.Long ? "toLong" : "toNumber";
    util.merge(Reader.prototype, {
        int64: function read_int64() {
            return readLongVarint.call(this)[fn](false);
        },
        uint64: function read_uint64() {
            return readLongVarint.call(this)[fn](true);
        },
        sint64: function read_sint64() {
            return readLongVarint.call(this).zzDecode()[fn](false);
        },
        fixed64: function read_fixed64() {
            return readFixed64.call(this)[fn](true);
        },
        sfixed64: function read_sfixed64() {
            return readFixed64.call(this)[fn](false);
        }
    });
}
_slice
Reader prototype _slice = util.Array.prototype.subarray || util.Array.prototype.slice
bool
Reader prototype bool
Initial value:
= function read_bool() {
    return this.uint32() !== 0;
}
Reads a varint as a boolean.
Returns
{boolean} Value read
BufferReader
var BufferReader
bytes
Reader prototype bytes
Initial value:
= function read_bytes() {
    var length = this.uint32(),
        start = this.pos,
        end = this.pos + length;
    
    if (end > this.len)
        throw indexOutOfRange(this, length);
    this.pos += length;
    if (Array.isArray(this.buf))
        return this.buf.slice(start, end);
    if (start === end) {
        var nativeBuffer = util.Buffer;
        return nativeBuffer
            ? nativeBuffer.alloc(0)
            : new this.buf.constructor(0);
    }
    return this._slice.call(this.buf, start, end);
}
Reads a sequence of bytes preceeded by its length as a varint.
Returns
{Uint8Array} Value read
create
Reader create
Initial value:
= function create() {
    return util.Buffer
        ? function create_buffer_setup(buffer) {
            return (Reader.create = function create_buffer(buffer) {
                return util.Buffer.isBuffer(buffer)
                    ? new BufferReader(buffer)
                    
                    : create_array(buffer);
            })(buffer);
        }
        
        : create_array;
}
Creates a new reader using the specified buffer. @function
Parameters
{Uint8Array|Buffer} buffer Buffer to read from
Returns
{Reader|BufferReader} A BufferReader if buffer is a Buffer, otherwise a Reader
Exceptions
{Error} If buffer is not a valid buffer
create_array
var create_array
Initial value:
= typeof Uint8Array !== "undefined"
    ? function create_typed_array(buffer) {
        if (buffer instanceof Uint8Array || Array.isArray(buffer))
            return new Reader(buffer);
        throw Error("illegal buffer");
    }
    
    : function create_array(buffer) {
        if (Array.isArray(buffer))
            return new Reader(buffer);
        throw Error("illegal buffer");
    }
double
Reader prototype double
Initial value:
= function read_double() {
    
    if (this.pos + 8 > this.len)
        throw indexOutOfRange(this, 4);
    var value = util.float.readDoubleLE(this.buf, this.pos);
    this.pos += 8;
    return value;
}
Reads a double (64 bit float) as a number. @function
Returns
{number} Value read
exports
module exports = Reader
fixed32
Reader prototype fixed32
Initial value:
= function read_fixed32() {
    
    if (this.pos + 4 > this.len)
        throw indexOutOfRange(this, 4);
    return readFixed32_end(this.buf, this.pos += 4);
}
Reads fixed 32 bits as an unsigned 32 bit integer.
Returns
{number} Value read
float
Reader prototype float
Initial value:
= function read_float() {
    
    if (this.pos + 4 > this.len)
        throw indexOutOfRange(this, 4);
    var value = util.float.readFloatLE(this.buf, this.pos);
    this.pos += 4;
    return value;
}
Reads a float (32 bit) as a number. @function
Returns
{number} Value read
int32
Reader prototype int32
Initial value:
= function read_int32() {
    return this.uint32() | 0;
}
Reads a varint as a signed 32 bit value.
Returns
{number} Value read
LongBits
var LongBits = util.LongBits
sfixed32
Reader prototype sfixed32
Initial value:
= function read_sfixed32() {
    
    if (this.pos + 4 > this.len)
        throw indexOutOfRange(this, 4);
    return readFixed32_end(this.buf, this.pos += 4) | 0;
}
Reads fixed 32 bits as a signed 32 bit integer.
Returns
{number} Value read
sint32
Reader prototype sint32
Initial value:
= function read_sint32() {
    var value = this.uint32();
    return value >>> 1 ^ -(value & 1) | 0;
}
Reads a zig-zag encoded varint as a signed 32 bit value.
Returns
{number} Value read
skip
exports skip
Initial value:
= function skip(length) {
    if (typeof length === "number") {
        
        if (this.pos + length > this.len)
            throw indexOutOfRange(this, length);
        this.pos += length;
    } else {
        do {
            
            if (this.pos >= this.len)
                throw indexOutOfRange(this);
        } while (this.buf[this.pos++] & 128);
    }
    return this;
}
Skips the specified number of bytes if specified, otherwise skips a varint.
Parameters
{number} [length] Length if known, otherwise a varint is assumed
Returns
{Reader} this
skipType
Reader prototype skipType
Initial value:
= function(wireType) {
    switch (wireType) {
        case 0:
            this.skip();
            break;
        case 1:
            this.skip(8);
            break;
        case 2:
            this.skip(this.uint32());
            break;
        case 3:
            while ((wireType = this.uint32() & 7) !== 4) {
                this.skipType(wireType);
            }
            break;
        case 5:
            this.skip(4);
            break;
        
        default:
            throw Error("invalid wire type " + wireType + " at offset " + this.pos);
    }
    return this;
}
Skips the next element of the specified wire type.
Parameters
{number} wireType Wire type received
Returns
{Reader} this
strict
use strict
string
Reader prototype string
Initial value:
= function read_string() {
    var bytes = this.bytes();
    return utf8.read(bytes, 0, bytes.length);
}
Reads a string preceeded by its byte length as a varint.
Returns
{string} Value read
uint32
Reader prototype uint32
Initial value:
= (function read_uint32_setup() {
    var value = 4294967295;
    return function read_uint32() {
        value = (this.buf[this.pos] & 127) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 127) << 7) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 127) << 14) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 127) << 21) >>> 0; if (this.buf[this.pos++] < 128) return value;
        value = (value | (this.buf[this.pos] & 15) << 28) >>> 0; if (this.buf[this.pos++] < 128) return value;
        
        if ((this.pos += 5) > this.len) {
            this.pos = this.len;
            throw indexOutOfRange(this, 10);
        }
        return value;
    };
})()
Reads a varint as an unsigned 32 bit value. @function
Returns
{number} Value read
utf8
var utf8 = util.utf8
util
var util = require("./util/minimal")