backend/node_modules/readable-stream/errors.js File Reference
Functions
function createErrorType (code, message, Base)
function oneOf (expected, thing)
function startsWith (str, search, pos)
function endsWith (str, search, this_len)
function includes (str, search, start)
Variables
use strict
const codes = {}
Function Documentation
createErrorType()
function createErrorType (code, message, Base)
References codes, Base::constructor(), and message.
endsWith()
function endsWith (str, search, this_len)
References str(), and undefined.
includes()
function includes (str, search, start)
References start, and str().
oneOf()
function oneOf (expected, thing)
References $, Array, expected, i, of, and or.
startsWith()
function startsWith (str, search, pos)
References str().
Variable Documentation
codes
module exports codes = {}
strict
use strict