backend/node_modules/readable-stream/lib/internal/streams/from.js File Reference
Functions
function asyncGeneratorStep (gen, resolve, reject, _next, _throw, key, arg)
function _asyncToGenerator (fn)
function ownKeys (object, enumerableOnly)
function _objectSpread (target)
function _defineProperty (obj, key, value)
function _toPropertyKey (arg)
function _toPrimitive (input, hint)
function from (Readable, iterable, opts)
Variables
use strict
var ERR_INVALID_ARG_TYPE = require('../../../errors').codes.ERR_INVALID_ARG_TYPE
module exports = from
Function Documentation
_asyncToGenerator()
function _asyncToGenerator (fn)
References args, asyncGeneratorStep(), fn, Promise, reject(), resolve, undefined, and value.
_defineProperty()
function _defineProperty (obj, key, value)
References _toPropertyKey(), obj, value, and writable.
_objectSpread()
function _objectSpread (target)
References _defineProperty(), i, ownKeys, and source.
_toPrimitive()
function _toPrimitive (input, hint)
References res, Symbol, and undefined.
_toPropertyKey()
function _toPropertyKey (arg)
References _toPrimitive().
asyncGeneratorStep()
function asyncGeneratorStep (gen, resolve, reject, _next, _throw, key, arg)
References error, Promise, reject(), resolve, and value.
from()
function from (Readable, iterable, opts)
References _asyncToGenerator(), _objectSpread(), done, ERR_INVALID_ARG_TYPE, iterator, next(), objectMode, Readable, readable, Symbol, and value.
ownKeys()
function ownKeys (object, enumerableOnly)
References keys.
Variable Documentation
ERR_INVALID_ARG_TYPE
var ERR_INVALID_ARG_TYPE = require('../../../errors').codes.ERR_INVALID_ARG_TYPE
exports
module exports = from
strict
use strict