backend/node_modules/asynckit/lib/readable_asynckit.js File Reference
Functions
function ReadableAsyncKit ()
function destroy ()
function _start ()
function _read ()
Variables
var streamify = require('./streamify.js')
var defer = require('./defer.js')
module exports = ReadableAsyncKit
Function Documentation
_read()
function _read () [private]
Implement _read to comply with Readable streams Doesn't really make sense for flowing object mode Here is the caller graph for this function:
_start()
function _start () [private]
Starts provided jobs in async manner
References args, Array, defer, streamify, and terminator.
destroy()
function destroy ()
Destroys readable stream, by aborting outstanding jobs
Returns
{void}
References terminator.
ReadableAsyncKit()
function ReadableAsyncKit ()
Base constructor for all streams used to hold properties/methods
References _read(), _start(), destroy(), and ReadableAsyncKit().
Variable Documentation
defer
var defer = require('./defer.js')
exports
module exports = ReadableAsyncKit
streamify
var streamify = require('./streamify.js')