backend/node_modules/node-forge/lib/rsa.js File Reference
Functions
if (typeof BigInteger==='undefined')
function _encodePkcs1_v1_5 (m, key, bt)
function _decodePkcs1_v1_5 (em, key, pub, ml)
function _generateKeyPair (state, options, callback)
function _bnToBytes (b)
function _getMillerRabinTests (bits)
function _detectNodeCrypto (fn)
function _detectSubtleCrypto (fn)
function _detectSubtleMsCrypto (fn)
function _intToUint8Array (x)
function _privateKeyFromJwk (jwk)
function _publicKeyFromJwk (jwk)
function _base64ToBigInt (b64)
Variables
var forge = require('./forge')
var _crypto = forge.util.isNodejs ? require('crypto') : null
var asn1 = forge.asn1
var util = forge.util
forge pki = forge.pki || {}
module exports = forge.pki.rsa = forge.rsa = forge.rsa || {}
var GCD_30_DELTA = [6, 4, 2, 4, 2, 4, 6, 2]
var privateKeyValidator
var rsaPrivateKeyValidator
var rsaPublicKeyValidator
var publicKeyValidator
var digestInfoValidator
var emsaPkcs1v15encode
var _modPow
pki rsa encrypt
pki rsa decrypt
pki rsa createKeyPairGenerationState
pki rsa stepKeyPairGenerationState
pki rsa generateKeyPair
pki setRsaPublicKey
pki setRsaPrivateKey
pki wrapRsaPrivateKey
pki privateKeyFromAsn1
pki privateKeyToAsn1
pki publicKeyFromAsn1
pki publicKeyToAsn1
pki publicKeyToRSAPublicKey
Function Documentation
_base64ToBigInt()
function _base64ToBigInt (b64)
References b64, BigInteger, and forge.
_bnToBytes()
function _bnToBytes (b)
Converts a positive BigInteger into 2's-complement big-endian bytes.
Parameters
b the big integer to convert.
Returns
the bytes.
References b, bytes, forge, and hex.
_decodePkcs1_v1_5()
function _decodePkcs1_v1_5 (em, key, pub, ml)
Decodes a message using PKCS#1 v1.5 padding.
Parameters
em the message to decode.
key the RSA key to use.
pub true if the key is a public key, false if it is private.
ml the message length, if specified.
Returns
the decoded bytes.
References bt, first, forge, i, k, and zero.
_detectNodeCrypto()
function _detectNodeCrypto (fn)
Performs feature detection on the Node crypto interface.
Parameters
fn the feature (function) to detect.
Returns
true if detected, false if not.
References _crypto, fn, and forge.
_detectSubtleCrypto()
function _detectSubtleCrypto (fn)
Performs feature detection on the SubtleCrypto interface.
Parameters
fn the feature (function) to detect.
Returns
true if detected, false if not.
References fn, and util.
_detectSubtleMsCrypto()
function _detectSubtleMsCrypto (fn)
Performs feature detection on the deprecated Microsoft Internet Explorer outdated SubtleCrypto interface. This function should only be used after checking for the modern, standard SubtleCrypto interface.
Parameters
fn the feature (function) to detect.
Returns
true if detected, false if not.
References fn, and util.
_encodePkcs1_v1_5()
function _encodePkcs1_v1_5 (m, key, bt)
Encodes a message using PKCS#1 v1.5 padding.
Parameters
m the message to encode.
key the RSA key to use.
bt the block type to use, i.e. either 0x01 (for signing) or 0x02 (for encryption).
Returns
the padded byte buffer.
References bt, error, forge, i, k, and m.
_generateKeyPair()
function _generateKeyPair (state, options, callback)
Runs the key-generation algorithm asynchronously, either in the background via Web Workers, or using the main thread and setImmediate.
Parameters
state the key-pair generation state.
[options] options for key-pair generation: workerScript the worker script URL. workers the number of web workers (if supported) to use, (default: 2, -1 to use estimated cores minus one). workLoad the size of the work load, ie: number of possible prime numbers for each web worker to check per work assignment, (default: 100).
callback(err,keypair) called once the operation completes.
References callback, finish, generate, name, and state().
_getMillerRabinTests()
function _getMillerRabinTests (bits)
Returns the required number of Miller-Rabin tests to generate a prime with an error probability of (1/2)^80.
See Handbook of Applied Cryptography Chapter 4, Table 4.4.
Parameters
bits the bit size.
Returns
the required number of iterations.
_intToUint8Array()
function _intToUint8Array (x)
References buffer, bytes, forge, i, and Uint8Array.
_privateKeyFromJwk()
function _privateKeyFromJwk (jwk)
References _base64ToBigInt(), and pki.
_publicKeyFromJwk()
function _publicKeyFromJwk (jwk)
References _base64ToBigInt(), and pki.
if()
if (typeof BigInteger = == 'undefined')
References BigInteger, and forge.
Variable Documentation
_crypto
var _crypto = forge.util.isNodejs ? require('crypto') : null
_modPow
var _modPow
Performs x^c mod n (RSA encryption or decryption operation).
Parameters
x the number to raise and mod.
key the key to use.
pub true if the key is public, false if private.
Returns
the result of x^c mod n.
asn1
var asn1 = forge.asn1
createKeyPairGenerationState
pki rsa createKeyPairGenerationState
Creates an RSA key-pair generation state object. It is used to allow key-generation to be performed in steps. It also allows for a UI to display progress updates.
Parameters
bits the size for the private key in bits, defaults to 2048.
e the public exponent to use, defaults to 65537 (0x10001).
[options] the options to use. prng a custom crypto-secure pseudo-random number generator to use, that must define "getBytesSync". algorithm the algorithm to use (default: 'PRIMEINC').
Returns
the state object to use to generate the key-pair.
decrypt
pki rsa decrypt
NOTE: THIS METHOD IS DEPRECATED, use 'decrypt' on a private key object or 'verify' on a public key object instead.
Performs RSA decryption.
The parameter ml controls whether to apply PKCS#1 v1.5 padding or not. Set ml = false to disable padding removal completely (in order to handle e.g. EMSA-PSS later on) and simply pass back the RSA encryption block.
Parameters
ed the encrypted data to decrypt in as a byte string.
key the RSA key to use.
pub true for a public key operation, false for private.
ml the message length, if known, false to disable padding.
Returns
the decrypted message as a byte string.
digestInfoValidator
var digestInfoValidator
emsaPkcs1v15encode
var emsaPkcs1v15encode
Initial value:
= function(md) {
  
  var oid;
  if(md.algorithm in pki.oids) {
    oid = pki.oids[md.algorithm];
  } else {
    var error = new Error('Unknown message digest algorithm.');
    error.algorithm = md.algorithm;
    throw error;
  }
  var oidBytes = asn1.oidToDer(oid).getBytes();
  
  var digestInfo = asn1.create(
    asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, []);
  var digestAlgorithm = asn1.create(
    asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, []);
  digestAlgorithm.value.push(asn1.create(
    asn1.Class.UNIVERSAL, asn1.Type.OID, false, oidBytes));
  digestAlgorithm.value.push(asn1.create(
    asn1.Class.UNIVERSAL, asn1.Type.NULL, false, ''));
  var digest = asn1.create(
    asn1.Class.UNIVERSAL, asn1.Type.OCTETSTRING,
    false, md.digest().getBytes());
  digestInfo.value.push(digestAlgorithm);
  digestInfo.value.push(digest);
  
  return asn1.toDer(digestInfo).getBytes();
}
Wrap digest in DigestInfo object.
This function implements EMSA-PKCS1-v1_5-ENCODE as per RFC 3447.
DigestInfo ::= SEQUENCE { digestAlgorithm DigestAlgorithmIdentifier, digest Digest }
DigestAlgorithmIdentifier ::= AlgorithmIdentifier Digest ::= OCTET STRING
Parameters
md the message digest object with the hash to sign.
Returns
the encoded message (ready for RSA encrytion)
encrypt
pki rsa encrypt
NOTE: THIS METHOD IS DEPRECATED, use 'sign' on a private key object or 'encrypt' on a public key object instead.
Performs RSA encryption.
The parameter bt controls whether to put padding bytes before the message passed in. Set bt to either true or false to disable padding completely (in order to handle e.g. EMSA-PSS encoding seperately before), signaling whether the encryption operation is a public key operation (i.e. encrypting data) or not, i.e. private key operation (data signing).
For PKCS#1 v1.5 padding pass in the block type to use, i.e. either 0x01 (for signing) or 0x02 (for encryption). The key operation mode (private or public) is derived from this flag in that case).
Parameters
m the message to encrypt as a byte string.
key the RSA key to use.
bt for PKCS#1 v1.5 padding, the block type to use (0x01 for private key, 0x02 for public), to disable padding: true = public key, false = private key.
Returns
the encrypted bytes as a string.
exports
module exports = forge.pki.rsa = forge.rsa = forge.rsa || {}
forge
var forge = require('./forge')
Javascript implementation of basic RSA algorithms.
Author
Dave Longley
Copyright (c) 2010-2014 Digital Bazaar, Inc.
The only algorithm currently supported for PKI is RSA.
An RSA key is often stored in ASN.1 DER format. The SubjectPublicKeyInfo ASN.1 structure is composed of an algorithm of type AlgorithmIdentifier and a subjectPublicKey of type bit string.
The AlgorithmIdentifier contains an Object Identifier (OID) and parameters for the algorithm, if any. In the case of RSA, there aren't any.
SubjectPublicKeyInfo ::= SEQUENCE { algorithm AlgorithmIdentifier, subjectPublicKey BIT STRING }
AlgorithmIdentifer ::= SEQUENCE { algorithm OBJECT IDENTIFIER, parameters ANY DEFINED BY algorithm OPTIONAL }
For an RSA public key, the subjectPublicKey is:
RSAPublicKey ::= SEQUENCE { modulus INTEGER, -- n publicExponent INTEGER -- e }
PrivateKeyInfo ::= SEQUENCE { version Version, privateKeyAlgorithm PrivateKeyAlgorithmIdentifier, privateKey PrivateKey, attributes [0] IMPLICIT Attributes OPTIONAL }
Version ::= INTEGER PrivateKeyAlgorithmIdentifier ::= AlgorithmIdentifier PrivateKey ::= OCTET STRING Attributes ::= SET OF Attribute
An RSA private key as the following structure:
RSAPrivateKey ::= SEQUENCE { version Version, modulus INTEGER, -- n publicExponent INTEGER, -- e privateExponent INTEGER, -- d prime1 INTEGER, -- p prime2 INTEGER, -- q exponent1 INTEGER, -- d mod (p-1) exponent2 INTEGER, -- d mod (q-1) coefficient INTEGER -- (inverse of q) mod p }
Version ::= INTEGER
The OID for the RSA key algorithm is: 1.2.840.113549.1.1.1
GCD_30_DELTA
var GCD_30_DELTA = [6, 4, 2, 4, 2, 4, 6, 2]
generateKeyPair
pki rsa generateKeyPair
Generates an RSA public-private key pair in a single call.
To generate a key-pair in steps (to allow for progress updates and to prevent blocking or warnings in slow browsers) then use the key-pair generation state functions.
To generate a key-pair asynchronously (either through web-workers, if available, or by breaking up the work on the main thread), pass a callback function.
Parameters
[bits] the size for the private key in bits, defaults to 2048.
[e] the public exponent to use, defaults to 65537.
[options] options for key-pair generation, if given then 'bits' and 'e' must not be given: bits the size for the private key in bits, (default: 2048). e the public exponent to use, (default: 65537 (0x10001)). workerScript the worker script URL. workers the number of web workers (if supported) to use, (default: 2). workLoad the size of the work load, ie: number of possible prime numbers for each web worker to check per work assignment, (default: 100). prng a custom crypto-secure pseudo-random number generator to use, that must define "getBytesSync". Disables use of native APIs. algorithm the algorithm to use (default: 'PRIMEINC').
[callback(err,keypair)] called once the operation completes.
Returns
an object with privateKey and publicKey properties.
pki
var pki = forge.pki || {}
privateKeyFromAsn1
pki privateKeyFromAsn1
Converts a private key from an ASN.1 object.
Parameters
obj the ASN.1 representation of a PrivateKeyInfo containing an RSAPrivateKey or an RSAPrivateKey.
Returns
the private key.
privateKeyToAsn1
pki privateKeyToAsn1
Converts a private key to an ASN.1 RSAPrivateKey.
Parameters
key the private key.
Returns
the ASN.1 representation of an RSAPrivateKey.
privateKeyValidator
var privateKeyValidator
publicKeyFromAsn1
pki publicKeyFromAsn1
Converts a public key from an ASN.1 SubjectPublicKeyInfo or RSAPublicKey.
Parameters
obj the asn1 representation of a SubjectPublicKeyInfo or RSAPublicKey.
Returns
the public key.
publicKeyToAsn1
pki publicKeyToAsn1
Initial value:
= pki.publicKeyToSubjectPublicKeyInfo = function(key) {
  
  return asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
      
      asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OID, false,
        asn1.oidToDer(pki.oids.rsaEncryption).getBytes()),
      
      asn1.create(asn1.Class.UNIVERSAL, asn1.Type.NULL, false, '')
    ]),
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.BITSTRING, false, [
      pki.publicKeyToRSAPublicKey(key)
    ])
  ]);
}
Converts a public key to an ASN.1 SubjectPublicKeyInfo.
Parameters
key the public key.
Returns
the asn1 representation of a SubjectPublicKeyInfo.
publicKeyToRSAPublicKey
pki publicKeyToRSAPublicKey
Initial value:
= function(key) {
  
  return asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.INTEGER, false,
      _bnToBytes(key.n)),
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.INTEGER, false,
      _bnToBytes(key.e))
  ]);
}
Converts a public key to an ASN.1 RSAPublicKey.
Parameters
key the public key.
Returns
the asn1 representation of a RSAPublicKey.
publicKeyValidator
var publicKeyValidator
rsaPrivateKeyValidator
var rsaPrivateKeyValidator
rsaPublicKeyValidator
var rsaPublicKeyValidator
Initial value:
= {
  
  name: 'RSAPublicKey',
  tagClass: asn1.Class.UNIVERSAL,
  type: asn1.Type.SEQUENCE,
  constructed: true,
  value: [{
    
    name: 'RSAPublicKey.modulus',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.INTEGER,
    constructed: false,
    capture: 'publicKeyModulus'
  }, {
    
    name: 'RSAPublicKey.exponent',
    tagClass: asn1.Class.UNIVERSAL,
    type: asn1.Type.INTEGER,
    constructed: false,
    capture: 'publicKeyExponent'
  }]
}
setRsaPrivateKey
pki setRsaPrivateKey
Sets an RSA private key from BigIntegers modulus, exponent, primes, prime exponents, and modular multiplicative inverse.
Parameters
n the modulus.
e the public exponent.
d the private exponent ((inverse of e) mod n).
p the first prime.
q the second prime.
dP exponent1 (d mod (p-1)).
dQ exponent2 (d mod (q-1)).
qInv ((inverse of q) mod p)
Returns
the private key.
setRsaPublicKey
pki setRsaPublicKey
Sets an RSA public key from BigIntegers modulus and exponent.
Parameters
n the modulus.
e the exponent.
Returns
the public key.
stepKeyPairGenerationState
pki rsa stepKeyPairGenerationState
Attempts to runs the key-generation algorithm for at most n seconds (approximately) using the given state. When key-generation has completed, the keys will be stored in state.keys.
To use this function to update a UI while generating a key or to prevent causing browser lockups/warnings, set "n" to a value other than 0. A simple pattern for generating a key and showing a progress indicator is:
var state = pki.rsa.createKeyPairGenerationState(2048); var step = function() { // step key-generation, run algorithm for 100 ms, repeat if(!forge.pki.rsa.stepKeyPairGenerationState(state, 100)) { setTimeout(step, 1); } else { // key-generation complete // TODO: turn off progress indicator here // TODO: use the generated key-pair in "state.keys" } }; // TODO: turn on progress indicator here setTimeout(step, 0);
Parameters
state the state to use.
n the maximum number of milliseconds to run the algorithm for, 0 to run the algorithm to completion.
Returns
true if the key-generation completed, false if not.
util
var util = forge.util
wrapRsaPrivateKey
pki wrapRsaPrivateKey
Initial value:
= function(rsaKey) {
  
  return asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.INTEGER, false,
      asn1.integerToDer(0).getBytes()),
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.SEQUENCE, true, [
      asn1.create(
        asn1.Class.UNIVERSAL, asn1.Type.OID, false,
        asn1.oidToDer(pki.oids.rsaEncryption).getBytes()),
      asn1.create(asn1.Class.UNIVERSAL, asn1.Type.NULL, false, '')
    ]),
    
    asn1.create(asn1.Class.UNIVERSAL, asn1.Type.OCTETSTRING, false,
      asn1.toDer(rsaKey).getBytes())
  ]);
}
Wraps an RSAPrivateKey ASN.1 object in an ASN.1 PrivateKeyInfo object.
Parameters
rsaKey the ASN.1 RSAPrivateKey.
Returns
the ASN.1 PrivateKeyInfo.