backend/node_modules/rxjs/dist/bundles/rxjs.umd.js File Reference
Functions
function __extends (d, b)
function __rest (s, e)
function __awaiter (thisArg, _arguments, P, generator)
function __generator (thisArg, body)
function __values (o)
function __read (o, n)
function __spreadArray (to, from, pack)
function __await (v)
function __asyncGenerator (thisArg, _arguments, generator)
function __asyncValues (o)
function isFunction (value)
function createErrorClass (createImpl)
function arrRemove (arr, item)
function isSubscription (value)
function execFinalizer (finalizer)
function reportUnhandledError (err)
function noop ()
function errorNotification (error)
function nextNotification (value)
function createNotification (kind, value, error)
function errorContext (cb)
function captureError (err)
function bind (fn, thisArg)
function handleUnhandledError (error)
function defaultErrorHandler (err)
function handleStoppedNotification (notification, subscriber)
function identity (x)
function pipe ()
function pipeFromArray (fns)
function getPromiseCtor (promiseCtor)
function isObserver (value)
function isSubscriber (value)
function hasLift (source)
function operate (init)
function createOperatorSubscriber (destination, onNext, onComplete, onError, onFinalize)
function refCount ()
function animationFrames (timestampProvider)
function animationFramesFactory (timestampProvider)
function findAndClearHandle (handle)
function empty (scheduler)
function emptyScheduled (scheduler)
function isScheduler (value)
function last (arr)
function popResultSelector (args)
function popScheduler (args)
function popNumber (args, defaultValue)
function isPromise (value)
function isInteropObservable (input)
function isAsyncIterable (obj)
function createInvalidObservableTypeError (input)
Variables
function global
function factory
this
function exports { 'use strict'
var extendStatics
var __assign
var UnsubscriptionError
var Subscription
var EMPTY_SUBSCRIPTION = Subscription.EMPTY
var config
var timeoutProvider
var COMPLETE_NOTIFICATION = (function () { return createNotification('C', undefined, undefined); })()
var context = null
var Subscriber
var _bind = Function.prototype.bind
var ConsumerObserver
var SafeSubscriber
var EMPTY_OBSERVER
var observable = (function () { return (typeof Symbol === 'function' && Symbol.observable) || '@@observable'; })()
var Observable
var OperatorSubscriber
var ConnectableObservable
var performanceTimestampProvider
var animationFrameProvider
var DEFAULT_ANIMATION_FRAMES = animationFramesFactory()
var ObjectUnsubscribedError
var Subject
var AnonymousSubject
var BehaviorSubject
var dateTimestampProvider
var ReplaySubject
var AsyncSubject
var Action
var intervalProvider
var AsyncAction
var nextHandle = 1
var resolved
var activeHandles = {}
var Immediate
var setImmediate = Immediate.setImmediate
var clearImmediate = Immediate.clearImmediate
var immediateProvider
var AsapAction
var Scheduler
var AsyncScheduler
var AsapScheduler
var asapScheduler = new AsapScheduler(AsapAction)
var asap = asapScheduler
var asyncScheduler = new AsyncScheduler(AsyncAction)
var async = asyncScheduler
var QueueAction
var QueueScheduler
var queueScheduler = new QueueScheduler(QueueAction)
var queue = queueScheduler
var AnimationFrameAction
var AnimationFrameScheduler
var animationFrameScheduler = new AnimationFrameScheduler(AnimationFrameAction)
var animationFrame = animationFrameScheduler
var VirtualTimeScheduler
var VirtualAction
var EMPTY = new Observable(function (subscriber) { return subscriber.complete(); })
var isArrayLike = (function (x) { return x && typeof x.length === 'number' && typeof x !== 'function'; })
Function Documentation
__asyncGenerator()
function __asyncGenerator (thisArg, _arguments, generator)
References __await, a, b, e, f, g, i, n, Promise, q, r, reject(), resume, Symbol, v, and value.
__asyncValues()
function __asyncValues (o)
References __values, d, done, i, m, n, o, Promise, reject(), resolve, Symbol, v, and value.
__await()
function __await (v)
References __await, and v.
__awaiter()
function __awaiter (thisArg, _arguments, P, generator)
References e, P, Promise, reject(), resolve, result, and value.
__extends()
function __extends (d, b)
References __, b, constructor, d, and extendStatics.
__generator()
function __generator (thisArg, body)
References _, done, e, f, g, n, next(), Symbol, t, v, value, and y.
__read()
function __read (o, n)
References e, error, i, m, n, o, r, and Symbol.
__rest()
function __rest (s, e)
References e, i, p, s, and t.
__spreadArray()
function __spreadArray (to, from, pack)
References Array, i, l, and pack().
__values()
function __values (o)
References done, i, m, next(), o, s, Symbol, and value.
animationFrames()
function animationFrames (timestampProvider)
References animationFramesFactory(), and DEFAULT_ANIMATION_FRAMES.
animationFramesFactory()
function animationFramesFactory (timestampProvider)
References animationFrameProvider, now, Observable, performanceTimestampProvider, run(), start, and timestamp.
arrRemove()
function arrRemove (arr, item)
References index.
bind()
function bind (fn, thisArg)
References _bind, and fn.
captureError()
function captureError (err)
References config, and context.
createErrorClass()
function createErrorClass (createImpl)
References instance.
createInvalidObservableTypeError()
function createInvalidObservableTypeError (input)
createNotification()
function createNotification (kind, value, error)
References error, and value.
createOperatorSubscriber()
function createOperatorSubscriber (destination, onNext, onComplete, onError, onFinalize)
References OperatorSubscriber.
defaultErrorHandler()
function defaultErrorHandler (err)
empty()
function empty (scheduler)
References EMPTY, and emptyScheduled().
emptyScheduled()
function emptyScheduled (scheduler)
References Observable.
errorContext()
function errorContext (cb)
References _a, config, context, and error.
errorNotification()
function errorNotification (error)
References createNotification, error, and undefined.
execFinalizer()
function execFinalizer (finalizer)
References isFunction.
findAndClearHandle()
function findAndClearHandle (handle)
References activeHandles, and handle.
getPromiseCtor()
function getPromiseCtor (promiseCtor)
References _a, config, and Promise.
handleStoppedNotification()
function handleStoppedNotification (notification, subscriber)
References config, and timeoutProvider.
handleUnhandledError()
function handleUnhandledError (error)
References captureError, config, error, and reportUnhandledError.
hasLift()
function hasLift (source)
References isFunction, and source.
identity()
function identity (x)
isAsyncIterable()
function isAsyncIterable (obj)
References isFunction, obj, and Symbol.
isFunction()
function isFunction (value)
References value.
isInteropObservable()
function isInteropObservable (input)
References isFunction.
isObserver()
function isObserver (value)
References isFunction, and value.
isPromise()
function isPromise (value)
References isFunction, and value.
isScheduler()
function isScheduler (value)
References isFunction, and value.
isSubscriber()
function isSubscriber (value)
References isObserver(), isSubscription, and value.
isSubscription()
function isSubscription (value)
References isFunction, and value.
last()
function last (arr)
nextNotification()
function nextNotification (value)
References createNotification, undefined, and value.
noop()
function noop ()
operate()
function operate (init)
References error, hasLift, init, and source.
pipe()
function pipe ()
References pipeFromArray.
pipeFromArray()
function pipeFromArray (fns)
References fn, and identity.
popNumber()
function popNumber (args, defaultValue)
References args, and last.
popResultSelector()
function popResultSelector (args)
References args, isFunction, last, and undefined.
popScheduler()
function popScheduler (args)
References args, isScheduler, last, and undefined.
refCount()
function refCount ()
References createOperatorSubscriber, operate, source, and undefined.
reportUnhandledError()
function reportUnhandledError (err)
References config, and timeoutProvider.
Variable Documentation
__assign
var __assign
Initial value:
= function() {
        __assign = Object.assign || function __assign(t) {
            for (var s, i = 1, n = arguments.length; i < n; i++) {
                s = arguments[i];
                for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p)) t[p] = s[p];
            }
            return t;
        };
        return __assign.apply(this, arguments);
    }
_bind
var _bind = Function.prototype.bind
Action
exports Action
Initial value:
= (function (_super) {
        __extends(Action, _super);
        function Action(scheduler, work) {
            return _super.call(this) || this;
        }
        Action.prototype.schedule = function (state, delay) {
            if (delay === void 0) { delay = 0; }
            return this;
        };
        return Action;
    }(Subscription))
activeHandles
var activeHandles = {}
animationFrame
animationFrameScheduler from scheduler animationFrame = animationFrameScheduler
AnimationFrameAction
exports AnimationFrameAction
animationFrameProvider
exports animationFrameProvider
AnimationFrameScheduler
exports AnimationFrameScheduler
Initial value:
= (function (_super) {
        __extends(AnimationFrameScheduler, _super);
        function AnimationFrameScheduler() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        AnimationFrameScheduler.prototype.flush = function (action) {
            this._active = true;
            var flushId = this._scheduled;
            this._scheduled = undefined;
            var actions = this.actions;
            var error;
            action = action || actions.shift();
            do {
                if ((error = action.execute(action.state, action.delay))) {
                    break;
                }
            } while ((action = actions[0]) && action.id === flushId && actions.shift());
            this._active = false;
            if (error) {
                while ((action = actions[0]) && action.id === flushId && actions.shift()) {
                    action.unsubscribe();
                }
                throw error;
            }
        };
        return AnimationFrameScheduler;
    }(AsyncScheduler))
animationFrameScheduler
var animationFrameScheduler = new AnimationFrameScheduler(AnimationFrameAction)
AnonymousSubject
exports AnonymousSubject
Initial value:
= (function (_super) {
        __extends(AnonymousSubject, _super);
        function AnonymousSubject(destination, source) {
            var _this = _super.call(this) || this;
            _this.destination = destination;
            _this.source = source;
            return _this;
        }
        AnonymousSubject.prototype.next = function (value) {
            var _a, _b;
            (_b = (_a = this.destination) === null || _a === void 0 ? void 0 : _a.next) === null || _b === void 0 ? void 0 : _b.call(_a, value);
        };
        AnonymousSubject.prototype.error = function (err) {
            var _a, _b;
            (_b = (_a = this.destination) === null || _a === void 0 ? void 0 : _a.error) === null || _b === void 0 ? void 0 : _b.call(_a, err);
        };
        AnonymousSubject.prototype.complete = function () {
            var _a, _b;
            (_b = (_a = this.destination) === null || _a === void 0 ? void 0 : _a.complete) === null || _b === void 0 ? void 0 : _b.call(_a);
        };
        AnonymousSubject.prototype._subscribe = function (subscriber) {
            var _a, _b;
            return (_b = (_a = this.source) === null || _a === void 0 ? void 0 : _a.subscribe(subscriber)) !== null && _b !== void 0 ? _b : EMPTY_SUBSCRIPTION;
        };
        return AnonymousSubject;
    }(Subject))
asap
asapScheduler from scheduler asap = asapScheduler
AsapAction
exports AsapAction
AsapScheduler
exports AsapScheduler
Initial value:
= (function (_super) {
        __extends(AsapScheduler, _super);
        function AsapScheduler() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        AsapScheduler.prototype.flush = function (action) {
            this._active = true;
            var flushId = this._scheduled;
            this._scheduled = undefined;
            var actions = this.actions;
            var error;
            action = action || actions.shift();
            do {
                if ((error = action.execute(action.state, action.delay))) {
                    break;
                }
            } while ((action = actions[0]) && action.id === flushId && actions.shift());
            this._active = false;
            if (error) {
                while ((action = actions[0]) && action.id === flushId && actions.shift()) {
                    action.unsubscribe();
                }
                throw error;
            }
        };
        return AsapScheduler;
    }(AsyncScheduler))
asapScheduler
var asapScheduler = new AsapScheduler(AsapAction)
async
var async = asyncScheduler
AsyncAction
exports AsyncAction
AsyncScheduler
exports AsyncScheduler
asyncScheduler
var asyncScheduler = new AsyncScheduler(AsyncAction)
AsyncSubject
exports AsyncSubject
BehaviorSubject
exports BehaviorSubject
clearImmediate
var clearImmediate = Immediate.clearImmediate
COMPLETE_NOTIFICATION
var COMPLETE_NOTIFICATION = (function () { return createNotification('C', undefined, undefined); })()
config
exports config
Initial value:
= {
        onUnhandledError: null,
        onStoppedNotification: null,
        Promise: undefined,
        useDeprecatedSynchronousErrorHandling: false,
        useDeprecatedNextContext: false,
    }
ConnectableObservable
exports ConnectableObservable
ConsumerObserver
var ConsumerObserver
context
var context = null
dateTimestampProvider
exports dateTimestampProvider
Initial value:
= {
        now: function () {
            return (dateTimestampProvider.delegate || Date).now();
        },
        delegate: undefined,
    }
DEFAULT_ANIMATION_FRAMES
var DEFAULT_ANIMATION_FRAMES = animationFramesFactory()
EMPTY
var EMPTY = new Observable(function (subscriber) { return subscriber.complete(); })
EMPTY_OBSERVER
exports EMPTY_OBSERVER
Initial value:
= {
        closed: true,
        next: noop,
        error: defaultErrorHandler,
        complete: noop,
    }
EMPTY_SUBSCRIPTION
var EMPTY_SUBSCRIPTION = Subscription.EMPTY
exports
function exports { 'use strict'
extendStatics
var extendStatics
Initial value:
= function(d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    }
0
 Copyright (c) Microsoft Corporation.
Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
factory
function factory
Initial value:
{
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define('rxjs', ['exports'], factory) :
    (factory((global.rxjs = {})))
global
function global
@license Apache License Version 2.0, January 2004 http://www.apache.org/licenses/
TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
Definitions.
"License" shall mean the terms and conditions for use, reproduction, and distribution as defined by Sections 1 through 9 of this document.
"Licensor" shall mean the copyright owner or entity authorized by the copyright owner that is granting the License.
"Legal Entity" shall mean the union of the acting entity and all other entities that control, are controlled by, or are under common control with that entity. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
"You" (or "Your") shall mean an individual or Legal Entity exercising permissions granted by this License.
"Source" form shall mean the preferred form for making modifications, including but not limited to software source code, documentation source, and configuration files.
"Object" form shall mean any form resulting from mechanical transformation or translation of a Source form, including but not limited to compiled object code, generated documentation, and conversions to other media types.
"Work" shall mean the work of authorship, whether in Source or Object form, made available under the License, as indicated by a copyright notice that is included in or attached to the work (an example is provided in the Appendix below).
"Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.
"Contribution" shall mean any work of authorship, including the original version of the Work and any modifications or additions to that Work or Derivative Works thereof, that is intentionally submitted to Licensor for inclusion in the Work by the copyright owner or by an individual or Legal Entity authorized to submit on behalf of the copyright owner. For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to the Licensor or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, the Licensor for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by the copyright owner as "Not a Contribution."
"Contributor" shall mean Licensor and any individual or Legal Entity on behalf of whom a Contribution has been received by Licensor and subsequently incorporated within the Work.
Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.
Grant of Patent License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted. If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed.
Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
(a) You must give any other recipients of the Work or Derivative Works a copy of this License; and
(b) You must cause any modified files to carry prominent notices stating that You changed the files; and
(c) You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
(d) If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.
You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.
Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.
Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.
Disclaimer of Warranty. Unless required by applicable law or agreed to in writing, Licensor provides the Work (and each Contributor provides its Contributions) on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing the Work and assume any risks associated with Your exercise of permissions under this License.
Limitation of Liability. In no event and under no legal theory, whether in tort (including negligence), contract, or otherwise, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall any Contributor be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this License or out of the use or inability to use the Work (including but not limited to damages for loss of goodwill, work stoppage, computer failure or malfunction, or any and all other commercial damages or losses), even if such Contributor has been advised of the possibility of such damages.
Accepting Warranty or Additional Liability. While redistributing the Work or Derivative Works thereof, You may choose to offer, and charge a fee for, acceptance of support, warranty, indemnity, or other liability obligations and/or rights consistent with this License. However, in accepting such obligations, You may act only on Your own behalf and on Your sole responsibility, not on behalf of any other Contributor, and only if You agree to indemnify, defend, and hold each Contributor harmless for any liability incurred by, or claims asserted against, such Contributor by reason of your accepting any such warranty or additional liability.
END OF TERMS AND CONDITIONS
APPENDIX: How to apply the Apache License to your work.
To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!) The text should be enclosed in the appropriate comment syntax for the file format. We also recommend that a file or class name and description of purpose be included on the same "printed page" as the copyright notice for easier identification within third-party archives.
Copyright (c) 2015-2018 Google, Inc., Netflix, Inc., Microsoft Corp. and contributors
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. @license Apache License Version 2.0, January 2004 http://www.apache.org/licenses/
TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
Definitions.
"License" shall mean the terms and conditions for use, reproduction, and distribution as defined by Sections 1 through 9 of this document.
"Licensor" shall mean the copyright owner or entity authorized by the copyright owner that is granting the License.
"Legal Entity" shall mean the union of the acting entity and all other entities that control, are controlled by, or are under common control with that entity. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
"You" (or "Your") shall mean an individual or Legal Entity exercising permissions granted by this License.
"Source" form shall mean the preferred form for making modifications, including but not limited to software source code, documentation source, and configuration files.
"Object" form shall mean any form resulting from mechanical transformation or translation of a Source form, including but not limited to compiled object code, generated documentation, and conversions to other media types.
"Work" shall mean the work of authorship, whether in Source or Object form, made available under the License, as indicated by a copyright notice that is included in or attached to the work (an example is provided in the Appendix below).
"Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.
"Contribution" shall mean any work of authorship, including the original version of the Work and any modifications or additions to that Work or Derivative Works thereof, that is intentionally submitted to Licensor for inclusion in the Work by the copyright owner or by an individual or Legal Entity authorized to submit on behalf of the copyright owner. For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to the Licensor or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, the Licensor for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by the copyright owner as "Not a Contribution."
"Contributor" shall mean Licensor and any individual or Legal Entity on behalf of whom a Contribution has been received by Licensor and subsequently incorporated within the Work.
Grant of Copyright License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form.
Grant of Patent License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted. If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed.
Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:
(a) You must give any other recipients of the Work or Derivative Works a copy of this License; and
(b) You must cause any modified files to carry prominent notices stating that You changed the files; and
(c) You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
(d) If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.
You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.
Submission of Contributions. Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.
Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.
Disclaimer of Warranty. Unless required by applicable law or agreed to in writing, Licensor provides the Work (and each Contributor provides its Contributions) on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing the Work and assume any risks associated with Your exercise of permissions under this License.
Limitation of Liability. In no event and under no legal theory, whether in tort (including negligence), contract, or otherwise, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall any Contributor be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this License or out of the use or inability to use the Work (including but not limited to damages for loss of goodwill, work stoppage, computer failure or malfunction, or any and all other commercial damages or losses), even if such Contributor has been advised of the possibility of such damages.
Accepting Warranty or Additional Liability. While redistributing the Work or Derivative Works thereof, You may choose to offer, and charge a fee for, acceptance of support, warranty, indemnity, or other liability obligations and/or rights consistent with this License. However, in accepting such obligations, You may act only on Your own behalf and on Your sole responsibility, not on behalf of any other Contributor, and only if You agree to indemnify, defend, and hold each Contributor harmless for any liability incurred by, or claims asserted against, such Contributor by reason of your accepting any such warranty or additional liability.
END OF TERMS AND CONDITIONS
APPENDIX: How to apply the Apache License to your work.
To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!) The text should be enclosed in the appropriate comment syntax for the file format. We also recommend that a file or class name and description of purpose be included on the same "printed page" as the copyright notice for easier identification within third-party archives.
Copyright (c) 2015-2018 Google, Inc., Netflix, Inc., Microsoft Corp. and contributors
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Immediate
var Immediate
Initial value:
= {
        setImmediate: function (cb) {
            var handle = nextHandle++;
            activeHandles[handle] = true;
            if (!resolved) {
                resolved = Promise.resolve();
            }
            resolved.then(function () { return findAndClearHandle(handle) && cb(); });
            return handle;
        },
        clearImmediate: function (handle) {
            findAndClearHandle(handle);
        },
    }
immediateProvider
exports immediateProvider
Initial value:
= {
        setImmediate: function () {
            var args = [];
            for (var _i = 0; _i < arguments.length; _i++) {
                args[_i] = arguments[_i];
            }
            var delegate = immediateProvider.delegate;
            return ((delegate === null || delegate === void 0 ? void 0 : delegate.setImmediate) || setImmediate).apply(void 0, __spreadArray([], __read(args)));
        },
        clearImmediate: function (handle) {
            var delegate = immediateProvider.delegate;
            return ((delegate === null || delegate === void 0 ? void 0 : delegate.clearImmediate) || clearImmediate)(handle);
        },
        delegate: undefined,
    }
intervalProvider
exports intervalProvider
Initial value:
= {
        setInterval: function (handler, timeout) {
            var args = [];
            for (var _i = 2; _i < arguments.length; _i++) {
                args[_i - 2] = arguments[_i];
            }
            var delegate = intervalProvider.delegate;
            if (delegate === null || delegate === void 0 ? void 0 : delegate.setInterval) {
                return delegate.setInterval.apply(delegate, __spreadArray([handler, timeout], __read(args)));
            }
            return setInterval.apply(void 0, __spreadArray([handler, timeout], __read(args)));
        },
        clearInterval: function (handle) {
            var delegate = intervalProvider.delegate;
            return ((delegate === null || delegate === void 0 ? void 0 : delegate.clearInterval) || clearInterval)(handle);
        },
        delegate: undefined,
    }
isArrayLike
var isArrayLike = (function (x) { return x && typeof x.length === 'number' && typeof x !== 'function'; })
nextHandle
var nextHandle = 1
ObjectUnsubscribedError
exports ObjectUnsubscribedError
Initial value:
= createErrorClass(function (_super) {
        return function ObjectUnsubscribedErrorImpl() {
            _super(this);
            this.name = 'ObjectUnsubscribedError';
            this.message = 'object unsubscribed';
        };
    })
Observable
exports Observable
observable
exports observable = (function () { return (typeof Symbol === 'function' && Symbol.observable) || '@@observable'; })()
OperatorSubscriber
exports OperatorSubscriber
performanceTimestampProvider
exports performanceTimestampProvider
Initial value:
= {
        now: function () {
            return (performanceTimestampProvider.delegate || performance).now();
        },
        delegate: undefined,
    }
queue
var queue = queueScheduler
QueueAction
exports QueueAction
QueueScheduler
exports QueueScheduler
Initial value:
= (function (_super) {
        __extends(QueueScheduler, _super);
        function QueueScheduler() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        return QueueScheduler;
    }(AsyncScheduler))
queueScheduler
var queueScheduler = new QueueScheduler(QueueAction)
ReplaySubject
exports ReplaySubject
resolved
var resolved
SafeSubscriber
exports SafeSubscriber
Scheduler
exports Scheduler
Initial value:
= (function () {
        function Scheduler(schedulerActionCtor, now) {
            if (now === void 0) { now = Scheduler.now; }
            this.schedulerActionCtor = schedulerActionCtor;
            this.now = now;
        }
        Scheduler.prototype.schedule = function (work, delay, state) {
            if (delay === void 0) { delay = 0; }
            return new this.schedulerActionCtor(this, work).schedule(state, delay);
        };
        Scheduler.now = dateTimestampProvider.now;
        return Scheduler;
    }())
setImmediate
var setImmediate = Immediate.setImmediate
Subject
exports Subject
Subscriber
exports Subscriber
Subscription
exports Subscription
this
this
timeoutProvider
exports timeoutProvider
Initial value:
= {
        setTimeout: function (handler, timeout) {
            var args = [];
            for (var _i = 2; _i < arguments.length; _i++) {
                args[_i - 2] = arguments[_i];
            }
            var delegate = timeoutProvider.delegate;
            if (delegate === null || delegate === void 0 ? void 0 : delegate.setTimeout) {
                return delegate.setTimeout.apply(delegate, __spreadArray([handler, timeout], __read(args)));
            }
            return setTimeout.apply(void 0, __spreadArray([handler, timeout], __read(args)));
        },
        clearTimeout: function (handle) {
            var delegate = timeoutProvider.delegate;
            return ((delegate === null || delegate === void 0 ? void 0 : delegate.clearTimeout) || clearTimeout)(handle);
        },
        delegate: undefined,
    }
UnsubscriptionError
exports UnsubscriptionError
Initial value:
= createErrorClass(function (_super) {
        return function UnsubscriptionErrorImpl(errors) {
            _super(this);
            this.message = errors
                ? errors.length + " errors occurred during unsubscription:\n" + errors.map(function (err, i) { return i + 1 + ") " + err.toString(); }).join('\n ')
                : '';
            this.name = 'UnsubscriptionError';
            this.errors = errors;
        };
    })
VirtualAction
exports VirtualAction
VirtualTimeScheduler
VirtualAction from scheduler VirtualTimeScheduler