backend/node_modules/@grpc/grpc-js/build/src/service-config.js File Reference
Functions
function validateName (obj)
function validateRetryPolicy (obj)
function validateHedgingPolicy (obj)
function validateMethodConfig (obj)
function validateRetryThrottling (obj)
function validateLoadBalancingConfig (obj)
function validateServiceConfig (obj)
function validateCanaryConfig (obj)
function validateAndSelectCanaryConfig (obj, percentage)
function extractAndSelectServiceConfig (txtRecord, percentage)
Variables
use strict
exports extractAndSelectServiceConfig = exports.validateServiceConfig = exports.validateRetryThrottling = void 0
const os = require("os")
const constants_1 = require("./constants")
const DURATION_REGEX = /^\d+(\.\d{1,9})?s$/
const CLIENT_LANGUAGE_STRING = 'node'
exports validateRetryThrottling = validateRetryThrottling
exports validateServiceConfig = validateServiceConfig
Function Documentation
extractAndSelectServiceConfig()
function extractAndSelectServiceConfig (txtRecord, percentage)
Find the "grpc_config" record among the TXT records, parse its value as JSON, validate its contents, and select a service config with selection fields that all match this client. Most of these steps can fail with an error; the caller must handle any errors thrown this way.
Parameters
txtRecord The TXT record array that is output from a successful call to dns.resolveTxt
percentage A number chosen from the range [0, 100) that is used to select which config to use
Returns
The service configuration to use, given the percentage value, or null if the service config data has a valid format but none of the options match the current client.
References JSON, length, of, and validateAndSelectCanaryConfig().
validateAndSelectCanaryConfig()
function validateAndSelectCanaryConfig (obj, percentage)
References Array, CLIENT_LANGUAGE_STRING, config, language, obj, of, and validateCanaryConfig().
validateCanaryConfig()
function validateCanaryConfig (obj)
References $, Array, config, obj, of, result, serviceConfig, and validateServiceConfig.
validateHedgingPolicy()
function validateHedgingPolicy (obj)
References Array, constants_1, DURATION_REGEX, obj, of, result, and value.
validateLoadBalancingConfig()
function validateLoadBalancingConfig (obj)
References $, keys, obj, and type.
validateMethodConfig()
function validateMethodConfig (obj)
References _a, Array, DURATION_REGEX, name, obj, of, result, validateHedgingPolicy(), validateName(), and validateRetryPolicy().
validateName()
function validateName (obj)
References $, config, empty, expected, invalid(), method, name, obj, or, type, undefined, and unset().
validateRetryPolicy()
function validateRetryPolicy (obj)
References Array, constants_1, DURATION_REGEX, obj, of, and value.
validateRetryThrottling()
function validateRetryThrottling (obj)
References obj.
validateServiceConfig()
function validateServiceConfig (obj)
References $, Array, config, name, obj, of, result, validateLoadBalancingConfig(), validateMethodConfig(), and validateRetryThrottling.
Variable Documentation
CLIENT_LANGUAGE_STRING
const CLIENT_LANGUAGE_STRING = 'node'
Client language name used for determining whether this client matches a ServiceConfigCanaryConfig's clientLanguage list.
constants_1
const constants_1 = require("./constants")
DURATION_REGEX
const DURATION_REGEX = /^\d+(\.\d{1,9})?s$/
Recognizes a number with up to 9 digits after the decimal point, followed by an "s", representing a number of seconds.
extractAndSelectServiceConfig
exports extractAndSelectServiceConfig = exports.validateServiceConfig = exports.validateRetryThrottling = void 0
os
const os = require("os")
strict
use strict
validateRetryThrottling
exports validateRetryThrottling = validateRetryThrottling
validateServiceConfig
exports validateServiceConfig = validateServiceConfig