backend/node_modules/concurrently/dist/src/concurrently.js File Reference
Functions
function concurrently (baseCommands, baseOptions)
function mapToCommandInfo (command)
function parseCommand (command, parsers)
function maybeRunMore (commandsLeft, abortSignal)
Variables
use strict
var __importDefault
exports concurrently = void 0
const assert_1 = __importDefault(require("assert"))
const lodash_1 = __importDefault(require("lodash"))
const os_1 = require("os")
const tree_kill_1 = __importDefault(require("tree-kill"))
const command_1 = require("./command")
const expand_arguments_1 = require("./command-parser/expand-arguments")
const expand_npm_shortcut_1 = require("./command-parser/expand-npm-shortcut")
const expand_npm_wildcard_1 = require("./command-parser/expand-npm-wildcard")
const strip_quotes_1 = require("./command-parser/strip-quotes")
const completion_listener_1 = require("./completion-listener")
const output_writer_1 = require("./output-writer")
const prefix_color_selector_1 = require("./prefix-color-selector")
const spawn_1 = require("./spawn")
const defaults
Function Documentation
concurrently()
function concurrently (baseCommands, baseOptions)
Core concurrently functionality -- spawns the given commands concurrently and returns the commands themselves + the result according to the specified success condition.
See also
CompletionListener
References Array, assert_1, command(), command_1, commands, completion_listener_1, controller, cwd, defaults, env, expand_arguments_1, expand_npm_shortcut_1, expand_npm_wildcard_1, group(), hide, i, index, listen, lodash_1, map, mapToCommandInfo(), maxProcesses, maybeRunMore(), os_1, output_writer_1, parseCommand(), prefix_color_selector_1, Promise, result, spawn_1, strip_quotes_1, text, and value.
mapToCommandInfo()
function mapToCommandInfo (command)
References assert_1, command(), cwd, env, mapToCommandInfo(), name, and undefined.
maybeRunMore()
function maybeRunMore (commandsLeft, abortSignal)
References abortSignal(), command(), and maybeRunMore().
parseCommand()
function parseCommand (command, parsers)
References command(), commands, lodash_1, and parser.
Variable Documentation
__importDefault
var __importDefault
Initial value:
= (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
}
assert_1
const assert_1 = __importDefault(require("assert"))
command_1
const command_1 = require("./command")
completion_listener_1
const completion_listener_1 = require("./completion-listener")
concurrently
exports concurrently = void 0
defaults
const defaults
Initial value:
= {
    spawn: spawn_1.spawn,
    kill: tree_kill_1.default,
    raw: false,
    controllers: [],
    cwd: undefined,
}
expand_arguments_1
const expand_arguments_1 = require("./command-parser/expand-arguments")
expand_npm_shortcut_1
const expand_npm_shortcut_1 = require("./command-parser/expand-npm-shortcut")
expand_npm_wildcard_1
const expand_npm_wildcard_1 = require("./command-parser/expand-npm-wildcard")
lodash_1
const lodash_1 = __importDefault(require("lodash"))
os_1
const os_1 = require("os")
output_writer_1
const output_writer_1 = require("./output-writer")
prefix_color_selector_1
const prefix_color_selector_1 = require("./prefix-color-selector")
spawn_1
const spawn_1 = require("./spawn")
strict
use strict
strip_quotes_1
const strip_quotes_1 = require("./command-parser/strip-quotes")
tree_kill_1
const tree_kill_1 = __importDefault(require("tree-kill"))