backend/node_modules/asynckit/lib/streamify.js File Reference
Functions
function wrapIterator (iterator)
function wrapCallback (callback)
function wrapIteratorCallback (callback, key)
function streamer (error, output, callback)
function finisher (error, output, callback)
Variables
var async = require('./async.js')
module exports
Function Documentation
finisher()
function finisher (error, output, callback)
Stream wrapper for finishing callback
@this ReadableAsyncKit#
Parameters
{mixed} error - error response
{mixed} output - iterator output
{function} callback - callback that expects final results
References callback, error, and push.
streamer()
function streamer (error, output, callback)
Stream wrapper for iterator callback
@this ReadableAsyncKit#
Parameters
{mixed} error - error response
{mixed} output - iterator output
{function} callback - callback that expects iterator results
References callback, emit, error, pause, and push.
wrapCallback()
function wrapCallback (callback)
Wraps provided callback function allowing to execute snitch function before real callback
@this ReadableAsyncKit#
Parameters
{function} callback - function to wrap
Returns
{function} - wrapped function
References callback, error, finisher(), result, and stream.
wrapIterator()
function wrapIterator (iterator)
Wraps iterators with long signature
@this ReadableAsyncKit#
Parameters
{function} iterator - function to wrap
Returns
{function} - wrapped function
References async, iterator, stream, and wrapIteratorCallback().
wrapIteratorCallback()
function wrapIteratorCallback (callback, key)
Wraps provided iterator callback function makes sure snitch only called once, but passes secondary calls to the original callback
@this ReadableAsyncKit#
Parameters
{function} callback - callback to wrap
{number|string} key - iteration key
Returns
{function} wrapped callback
References callback, error, stream, streamer(), and value.
Variable Documentation
async
var async = require('./async.js')
exports
module exports
Initial value:
= {
  iterator: wrapIterator,
  callback: wrapCallback
}