backend/node_modules/string_decoder/lib/string_decoder.js File Reference
Functions
function _normalizeEncoding (enc)
function normalizeEncoding (enc)
function StringDecoder (encoding)
function utf8CheckByte (byte)
function utf8CheckIncomplete (self, buf, i)
function utf8CheckExtraBytes (self, buf, p)
function utf8FillLast (buf)
function utf8Text (buf, i)
function utf8End (buf)
function utf16Text (buf, i)
function utf16End (buf)
function base64Text (buf, i)
function base64End (buf)
function simpleWrite (buf)
function simpleEnd (buf)
Variables
use strict
var Buffer = require('safe-buffer').Buffer
var isEncoding
exports StringDecoder = StringDecoder
StringDecoder prototype write
StringDecoder prototype end = utf8End
StringDecoder prototype text = utf8Text
StringDecoder prototype fillLast
Function Documentation
_normalizeEncoding()
function _normalizeEncoding (enc)
base64End()
function base64End (buf)
References buf, r, and write.
base64Text()
function base64Text (buf, i)
References buf, i, and n.
normalizeEncoding()
function normalizeEncoding (enc)
References _normalizeEncoding(), and isEncoding.
simpleEnd()
function simpleEnd (buf)
References buf, and write.
simpleWrite()
function simpleWrite (buf)
References buf, and encoding.
StringDecoder()
function StringDecoder (encoding)
References base64End(), base64Text(), encoding, end, fillLast, normalizeEncoding(), simpleEnd(), simpleWrite(), text, utf16End(), utf16Text(), utf8FillLast(), and write.
utf16End()
function utf16End (buf)
References buf, end, r, and write.
utf16Text()
function utf16Text (buf, i)
References buf, c, i, and r.
utf8CheckByte()
function utf8CheckByte (byte)
utf8CheckExtraBytes()
function utf8CheckExtraBytes (self, buf, p)
References buf.
utf8CheckIncomplete()
function utf8CheckIncomplete (self, buf, i)
References buf, i, j, and utf8CheckByte().
utf8End()
function utf8End (buf)
References buf, r, and write.
utf8FillLast()
function utf8FillLast (buf)
References buf, encoding, p, r, undefined, and utf8CheckExtraBytes().
utf8Text()
function utf8Text (buf, i)
References buf, end, i, and utf8CheckIncomplete().
Variable Documentation
Buffer
var Buffer = require('safe-buffer').Buffer
end
StringDecoder prototype end = utf8End
fillLast
StringDecoder prototype fillLast
Initial value:
= function (buf) {
  if (this.lastNeed <= buf.length) {
    buf.copy(this.lastChar, this.lastTotal - this.lastNeed, 0, this.lastNeed);
    return this.lastChar.toString(this.encoding, 0, this.lastTotal);
  }
  buf.copy(this.lastChar, this.lastTotal - this.lastNeed, 0, buf.length);
  this.lastNeed -= buf.length;
}
isEncoding
var isEncoding
Initial value:
= Buffer.isEncoding || function (encoding) {
  encoding = '' + encoding;
  switch (encoding && encoding.toLowerCase()) {
    case 'hex':case 'utf8':case 'utf-8':case 'ascii':case 'binary':case 'base64':case 'ucs2':case 'ucs-2':case 'utf16le':case 'utf-16le':case 'raw':
      return true;
    default:
      return false;
  }
}
strict
use strict
StringDecoder
exports StringDecoder = StringDecoder
text
StringDecoder prototype text = utf8Text
write
StringDecoder prototype write
Initial value:
= function (buf) {
  if (buf.length === 0) return '';
  var r;
  var i;
  if (this.lastNeed) {
    r = this.fillLast(buf);
    if (r === undefined) return '';
    i = this.lastNeed;
    this.lastNeed = 0;
  } else {
    i = 0;
  }
  if (i < buf.length) return r ? r + this.text(buf, i) : this.text(buf, i);
  return r || '';
}