backend/node_modules/teeny-request/build/src/index.js File Reference
Classes
class RequestError
Functions
function requestToFetchOptions (reqOpts)
function fetchToRequestResponse (opts, res)
function createMultipartStream (boundary, multipart)
function teenyRequest (reqOpts, callback)
Variables
use strict
exports teenyRequest = exports.RequestError = void 0
const node_fetch_1 = require("node-fetch")
const stream_1 = require("stream")
const uuid = require("uuid")
const agents_1 = require("./agents")
const TeenyStatistics_1 = require("./TeenyStatistics")
const streamEvents = require('stream-events')
exports RequestError = RequestError
teenyRequest defaults
teenyRequest stats = new TeenyStatistics_1.TeenyStatistics()
teenyRequest resetStats
Function Documentation
createMultipartStream()
function createMultipartStream (boundary, multipart) [private]
Create POST body from two parts as multipart/related content-type
Parameters
boundary
multipart
References $, end, of, stream, stream_1, and Type.
fetchToRequestResponse()
function fetchToRequestResponse (opts, res) [private]
Convert a response from fetch to request format.
Parameters
opts The request options used to create the request.
res The Fetch response
Returns
A request response object
References request, res, response, and value.
requestToFetchOptions()
function requestToFetchOptions (reqOpts) [private]
Convert options from Request to Fetch format
Parameters
reqOpts Request options
References agents_1, JSON, method, qs, require(), and timeout.
teenyRequest()
function teenyRequest (reqOpts, callback)
References $, callback, createMultipartStream(), fetchToRequestResponse(), json, node_fetch_1, requestToFetchOptions(), res, response, stream_1, streamEvents, teenyRequest, text, undefined, and uuid.
Variable Documentation
agents_1
const agents_1 = require("./agents")
defaults
teenyRequest defaults
Initial value:
= (defaults) => {
    return (reqOpts, callback) => {
        const opts = { ...defaults, ...reqOpts };
        if (callback === undefined) {
            return teenyRequest(opts);
        }
        teenyRequest(opts, callback);
    };
}
node_fetch_1
const node_fetch_1 = require("node-fetch")
RequestError
exports RequestError = RequestError
resetStats
teenyRequest resetStats
Initial value:
= () => {
    teenyRequest.stats = new TeenyStatistics_1.TeenyStatistics(teenyRequest.stats.getOptions());
}
stats
teenyRequest stats = new TeenyStatistics_1.TeenyStatistics()
Single instance of an interface for keeping track of things.
stream_1
const stream_1 = require("stream")
streamEvents
const streamEvents = require('stream-events')
strict
use strict
teenyRequest
exports teenyRequest = exports.RequestError = void 0
TeenyStatistics_1
const TeenyStatistics_1 = require("./TeenyStatistics")
uuid
const uuid = require("uuid")