backend/node_modules/google-gax/build/src/transcoding.js File Reference
Functions
function getField (request, field, allowObjects=false)
function deepCopyWithoutMatchedFields (request, fieldsToSkip, fullNamePrefix='')
function deleteField (request, field)
function buildQueryStringComponents (request, prefix='')
function encodeWithSlashes (str)
function encodeWithoutSlashes (str)
function escapeRegExp (str)
function applyPattern (pattern, fieldValue)
function fieldToCamelCase (field)
function match (request, pattern)
* if (!match)
if (fieldValue===undefined)
function flattenObject (request)
function isProto3OptionalField (field)
function transcode (request, parsedOptions)
function overrideHttpRules (httpRules, protoJson)
Variables
use strict
exports getField = getField
exports deepCopyWithoutMatchedFields = deepCopyWithoutMatchedFields
exports deleteField = deleteField
exports buildQueryStringComponents = buildQueryStringComponents
exports encodeWithSlashes = encodeWithSlashes
exports encodeWithoutSlashes = encodeWithoutSlashes
exports applyPattern = applyPattern
exports match = match
exports flattenObject = flattenObject
exports isProto3OptionalField = isProto3OptionalField
exports transcode = transcode
exports overrideHttpRules = overrideHttpRules
const util_1 = require("./util")
const httpOptionName = '(google.api.http)'
const proto3OptionalName = 'proto3_optional'
const supportedHttpMethods = ['get', 'post', 'put', 'patch', 'delete']
const [, before, field, pattern, after] = match
const camelCasedField = fieldToCamelCase(field)
const fieldValue = getField(request, camelCasedField)
const appliedPattern = applyPattern(pattern, fieldValue === null ? 'null' : fieldValue.toString())
url = before + appliedPattern + after
return { matchedFields, url }
Function Documentation
applyPattern()
function applyPattern (pattern, fieldValue)
References encodeWithoutSlashes, encodeWithSlashes, escapeRegExp(), fieldValue, g, replace, and undefined.
buildQueryStringComponents()
function buildQueryStringComponents (request, prefix = '')
References $, Array, buildQueryStringComponents, encodeWithoutSlashes, of, prefix, request, toString, and value.
deepCopyWithoutMatchedFields()
function deepCopyWithoutMatchedFields (request, fieldsToSkip, fullNamePrefix = '')
References $, Array, copy, deepCopyWithoutMatchedFields, request, Set, and value.
deleteField()
function deleteField (request, field)
References request.
encodeWithoutSlashes()
function encodeWithoutSlashes (str)
References _, a, c, str(), and Z().
encodeWithSlashes()
function encodeWithSlashes (str)
References _, a, c, str(), and Z().
escapeRegExp()
function escapeRegExp (str)
References $, g, and str().
fieldToCamelCase()
function fieldToCamelCase (field)
References util_1.
flattenObject()
function flattenObject (request)
References $, Array, flattenObject, request, result, and undefined.
getField()
function getField (request, field, allowObjects = false)
References Array, of, request, undefined, and value.
if() [1/2]
* if (! match)
if() [2/2]
if (fieldValue = == undefined)
References undefined.
isProto3OptionalField()
function isProto3OptionalField (field)
References proto3OptionalName.
match()
function match (request, pattern)
References match, and url.
overrideHttpRules()
function overrideHttpRules (httpRules, protoJson)
References Array, httpOptionName, of, and rpc.
transcode()
function transcode (request, parsedOptions)
References Array, buildQueryStringComponents, data, deepCopyWithoutMatchedFields, deleteField, fieldToCamelCase(), getField, httpOptionName, match, of, request, Set, supportedHttpMethods, undefined, and url.
Variable Documentation
appliedPattern
const appliedPattern = applyPattern(pattern, fieldValue === null ? 'null' : fieldValue.toString())
applyPattern
exports applyPattern = applyPattern
buildQueryStringComponents
exports buildQueryStringComponents = buildQueryStringComponents
camelCasedField
const camelCasedField = fieldToCamelCase(field)
const
const[, before, field, pattern, after] = match
deepCopyWithoutMatchedFields
exports deepCopyWithoutMatchedFields = deepCopyWithoutMatchedFields
deleteField
exports deleteField = deleteField
encodeWithoutSlashes
exports encodeWithoutSlashes = encodeWithoutSlashes
encodeWithSlashes
exports encodeWithSlashes = encodeWithSlashes
fieldValue
const fieldValue = getField(request, camelCasedField)
flattenObject
exports flattenObject = flattenObject
getField
exports getField = getField
httpOptionName
const httpOptionName = '(google.api.http)'
isProto3OptionalField
exports isProto3OptionalField = isProto3OptionalField
match
exports match = match
overrideHttpRules
exports overrideHttpRules = overrideHttpRules
proto3OptionalName
const proto3OptionalName = 'proto3_optional'
return
return { matchedFields, url }
strict
use strict
supportedHttpMethods
const supportedHttpMethods = ['get', 'post', 'put', 'patch', 'delete']
transcode
exports transcode = transcode
url
url = before + appliedPattern + after
util_1
const util_1 = require("./util")