backend/node_modules/tree-kill/index.js File Reference
Functions
function killAll (tree, signal, callback)
function killPid (pid, signal)
function buildProcessTree (parentPid, tree, pidsToProcess, spawnChildProcessesList, cb)
Variables
use strict
var childProcess = require('child_process')
var spawn = childProcess.spawn
var exec = childProcess.exec
module exports
Function Documentation
buildProcessTree()
function buildProcessTree (parentPid, tree, pidsToProcess, spawnChildProcessesList, cb)
References buildProcessTree(), d, data, g, and parseInt().
killAll()
function killAll (tree, signal, callback)
References callback, killPid(), and signal.
killPid()
function killPid (pid, signal)
References parseInt(), process, and signal.
Variable Documentation
childProcess
var childProcess = require('child_process')
exec
var exec = childProcess.exec
exports
module exports
spawn
var spawn = childProcess.spawn
strict
use strict