backend/node_modules/tslib/tslib.es6.js File Reference
Functions
function export __extends (d, b)
function export __runInitializers (thisArg, initializers, value)
function export __propKey (x)
function export __setFunctionName (f, name, prefix)
function export __metadata (metadataKey, metadataValue)
function export __awaiter (thisArg, _arguments, P, generator)
function export __generator (thisArg, body)
function export __exportStar (m, o)
function export __values (o)
function export __read (o, n)
function export __spread ()
function export __spreadArrays ()
function export __spreadArray (to, from, pack)
function export __await (v)
function export __asyncGenerator (thisArg, _arguments, generator)
function export __asyncDelegator (o)
function export __asyncValues (o)
function export __makeTemplateObject (cooked, raw)
function export __importStar (mod)
function export __importDefault (mod)
function export __classPrivateFieldGet (receiver, state, kind, f)
function export __classPrivateFieldSet (receiver, state, value, kind, f)
function export __classPrivateFieldIn (state, receiver)
function export __addDisposableResource (env, value, async)
function export __disposeResources (env)
function export __rewriteRelativeImportExtension (path, preserveJsx)
Variables
var extendStatics
var export __assign
var export __createBinding
var __setModuleDefault
var _SuppressedError
return path
export default
Function Documentation
__addDisposableResource()
function export __addDisposableResource (env, value, async)
References async, e, env, Promise, Symbol, and value.
__asyncDelegator()
function export __asyncDelegator (o)
References __await, done, e, f, i, n, o, p, Symbol, v, and value.
__asyncGenerator()
function export __asyncGenerator (thisArg, _arguments, generator)
References __await, a, b, e, f, g, i, n, Promise, prototype, q, r, reject(), resume, Symbol, v, and value.
__asyncValues()
function export __asyncValues (o)
References __values, d, done, i, m, n, o, Promise, reject(), resolve, Symbol, v, and value.
__await()
function export __await (v)
References __await, and v.
__awaiter()
function export __awaiter (thisArg, _arguments, P, generator)
References e, P, Promise, reject(), resolve, result, and value.
__classPrivateFieldGet()
function export __classPrivateFieldGet (receiver, state, kind, f)
References f, and state().
__classPrivateFieldIn()
function export __classPrivateFieldIn (state, receiver)
References state().
__classPrivateFieldSet()
function export __classPrivateFieldSet (receiver, state, value, kind, f)
References f, state(), and value.
__disposeResources()
function export __disposeResources (env)
References _SuppressedError, e, env, fail, next(), Promise, r, result, and s.
__exportStar()
function export __exportStar (m, o)
References __createBinding, m, o, and p.
__extends()
function export __extends (d, b)
References __, b, constructor, d, and extendStatics.
__generator()
function export __generator (thisArg, body)
References _, done, e, f, g, n, prototype, Symbol, t, v, value, and y.
__importDefault()
function export __importDefault (mod)
References mod.
__importStar()
function export __importStar (mod)
References __createBinding, __setModuleDefault, k, mod, and result.
__makeTemplateObject()
function export __makeTemplateObject (cooked, raw)
References raw, and value.
__metadata()
function export __metadata (metadataKey, metadataValue)
__propKey()
function export __propKey (x)
__read()
function export __read (o, n)
References e, error, i, m, n, o, r, and Symbol.
__rewriteRelativeImportExtension()
function export __rewriteRelativeImportExtension (path, preserveJsx)
References $, d, ext, i, m, and path.
__runInitializers()
function export __runInitializers (thisArg, initializers, value)
References i, and value.
__setFunctionName()
function export __setFunctionName (f, name, prefix)
References f, name, prefix, and value.
__spread()
function export __spread ()
Deprecated
Deprecated
References __read, and i.
__spreadArray()
function export __spreadArray (to, from, pack)
References Array, i, l, and pack().
__spreadArrays()
function export __spreadArrays ()
Deprecated
Deprecated
References a, Array, i, j, k, r, and s.
__values()
function export __values (o)
References done, i, m, next(), o, s, Symbol, and value.
Variable Documentation
__assign
var export __assign
__createBinding
var export __createBinding
Initial value:
= Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
        desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
})
__setModuleDefault
var __setModuleDefault
Initial value:
= Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
}
_SuppressedError
var _SuppressedError
Initial value:
= typeof SuppressedError === "function" ? SuppressedError : function (error, suppressed, message) {
    var e = new Error(message);
    return e.name = "SuppressedError", e.error = error, e.suppressed = suppressed, e;
}
default
export default
extendStatics
var extendStatics
Initial value:
= function(d, b) {
    extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
    return extendStatics(d, b);
}
path
return path