backend/node_modules/whatwg-url/lib/url-state-machine.js File Reference
Functions
function countSymbols (str)
function at (input, idx)
function isASCIIDigit (c)
function isASCIIAlpha (c)
function isASCIIAlphanumeric (c)
function isASCIIHex (c)
function isSingleDot (buffer)
function isDoubleDot (buffer)
function isWindowsDriveLetterCodePoints (cp1, cp2)
function isWindowsDriveLetterString (string)
function isNormalizedWindowsDriveLetterString (string)
function containsForbiddenHostCodePoint (string)
function containsForbiddenHostCodePointExcludingPercent (string)
function isSpecialScheme (scheme)
function isSpecial (url)
function defaultPort (scheme)
function percentEncode (c)
function utf8PercentEncode (c)
function utf8PercentDecode (str)
function isC0ControlPercentEncode (c)
function isPathPercentEncode (c)
function isUserinfoPercentEncode (c)
function percentEncodeChar (c, encodeSetPredicate)
function parseIPv4Number (input)
function parseIPv4 (input)
function serializeIPv4 (address)
function parseIPv6 (input)
function serializeIPv6 (address)
function parseHost (input, isSpecialArg)
function parseOpaqueHost (input)
function findLongestZeroSequence (arr)
function serializeHost (host)
function trimControlChars (url)
function trimTabAndNewline (url)
function shortenPath (url)
function includesCredentials (url)
function cannotHaveAUsernamePasswordPort (url)
function isNormalizedWindowsDriveLetter (string)
function URLStateMachine (input, base, encodingOverride, url, stateOverride)
function serializeURL (url, excludeFragment)
function serializeOrigin (tuple)
Variables
use strict
const punycode = require("punycode")
const tr46 = require("tr46")
const specialSchemes
const failure = Symbol("failure")
const extraPathPercentEncodeSet = new Set([32, 34, 35, 60, 62, 63, 96, 123, 125])
const extraUserinfoPercentEncodeSet
URLStateMachine prototype ["parse scheme start"]
const fileOtherwiseCodePoints = new Set([47, 92, 63, 35])
module exports serializeURL = serializeURL
module exports serializeURLOrigin
module exports basicURLParse
module exports setTheUsername
module exports setThePassword
module exports serializeHost = serializeHost
module exports cannotHaveAUsernamePasswordPort = cannotHaveAUsernamePasswordPort
module exports serializeInteger
module exports parseURL
Function Documentation
at()
function at (input, idx)
References c, isNaN, and undefined.
cannotHaveAUsernamePasswordPort()
function cannotHaveAUsernamePasswordPort (url)
References url.
containsForbiddenHostCodePoint()
function containsForbiddenHostCodePoint (string)
containsForbiddenHostCodePointExcludingPercent()
function containsForbiddenHostCodePointExcludingPercent (string)
countSymbols()
function countSymbols (str)
References punycode, and str().
defaultPort()
function defaultPort (scheme)
References specialSchemes.
findLongestZeroSequence()
function findLongestZeroSequence (arr)
References i.
includesCredentials()
function includesCredentials (url)
References url.
isASCIIAlpha()
function isASCIIAlpha (c)
References c.
isASCIIAlphanumeric()
function isASCIIAlphanumeric (c)
References c, isASCIIAlpha(), and isASCIIDigit().
isASCIIDigit()
function isASCIIDigit (c)
References c.
isASCIIHex()
function isASCIIHex (c)
References c, and isASCIIDigit().
isC0ControlPercentEncode()
function isC0ControlPercentEncode (c)
References c.
isDoubleDot()
function isDoubleDot (buffer)
References buffer.
isNormalizedWindowsDriveLetter()
function isNormalizedWindowsDriveLetter (string)
References $.
isNormalizedWindowsDriveLetterString()
function isNormalizedWindowsDriveLetterString (string)
References isASCIIAlpha().
isPathPercentEncode()
function isPathPercentEncode (c)
References c, extraPathPercentEncodeSet, and isC0ControlPercentEncode().
isSingleDot()
function isSingleDot (buffer)
References buffer.
isSpecial()
function isSpecial (url)
References isSpecialScheme(), and url.
isSpecialScheme()
function isSpecialScheme (scheme)
References specialSchemes, and undefined.
isUserinfoPercentEncode()
function isUserinfoPercentEncode (c)
References c, extraUserinfoPercentEncodeSet, and isPathPercentEncode().
isWindowsDriveLetterCodePoints()
function isWindowsDriveLetterCodePoints (cp1, cp2)
References isASCIIAlpha().
isWindowsDriveLetterString()
function isWindowsDriveLetterString (string)
References isASCIIAlpha().
parseHost()
function parseHost (input, isSpecialArg)
References containsForbiddenHostCodePoint(), failure, parseIPv4(), parseIPv6(), parseOpaqueHost(), tr46, and utf8PercentDecode().
parseIPv4()
function parseIPv4 (input)
References failure, i, n, of, and parseIPv4Number().
parseIPv4Number()
function parseIPv4Number (input)
References f, failure, parseInt(), and R.
parseIPv6()
function parseIPv6 (input)
References at, compress(), failure, isASCIIDigit(), isASCIIHex(), length, parseInt(), punycode, undefined, and value.
parseOpaqueHost()
function parseOpaqueHost (input)
References containsForbiddenHostCodePointExcludingPercent(), failure, i, isC0ControlPercentEncode(), percentEncodeChar(), and punycode.
percentEncode()
function percentEncode (c)
References c, and hex.
percentEncodeChar()
function percentEncodeChar (c, encodeSetPredicate)
References c, and utf8PercentEncode().
serializeHost()
function serializeHost (host)
References Array, serializeIPv4(), and serializeIPv6().
serializeIPv4()
function serializeIPv4 (address)
References i, and n.
serializeIPv6()
function serializeIPv6 (address)
References compress(), and findLongestZeroSequence().
serializeOrigin()
function serializeOrigin (tuple)
References result, and serializeHost.
serializeURL()
function serializeURL (url, excludeFragment)
References of, serializeHost, string, and url.
shortenPath()
function shortenPath (url)
References isNormalizedWindowsDriveLetter(), path, and url.
trimControlChars()
function trimControlChars (url)
References $, g, and url.
trimTabAndNewline()
function trimTabAndNewline (url)
References g, and url.
URLStateMachine()
function URLStateMachine (input, base, encodingOverride, url, stateOverride)
References base, buffer, c, failure, isNaN, path, punycode, query, res, state(), trimControlChars(), trimTabAndNewline(), undefined, and url.
utf8PercentDecode()
function utf8PercentDecode (str)
References Buffer, i, isASCIIHex(), parseInt(), and str().
utf8PercentEncode()
function utf8PercentEncode (c)
References buf, Buffer, c, i, percentEncode(), and str().
Variable Documentation
basicURLParse
module exports basicURLParse
Initial value:
= function (input, options) {
  if (options === undefined) {
    options = {};
  }
  const usm = new URLStateMachine(input, options.baseURL, options.encodingOverride, options.url, options.stateOverride);
  if (usm.failure) {
    return "failure";
  }
  return usm.url;
}
cannotHaveAUsernamePasswordPort
module exports cannotHaveAUsernamePasswordPort = cannotHaveAUsernamePasswordPort
extraPathPercentEncodeSet
const extraPathPercentEncodeSet = new Set([32, 34, 35, 60, 62, 63, 96, 123, 125])
extraUserinfoPercentEncodeSet
const extraUserinfoPercentEncodeSet
Initial value:
=
  new Set([47, 58, 59, 61, 64, 91, 92, 93, 94, 124])
failure
const failure = Symbol("failure")
fileOtherwiseCodePoints
const fileOtherwiseCodePoints = new Set([47, 92, 63, 35])
parseURL
module exports parseURL
Initial value:
= function (input, options) {
  if (options === undefined) {
    options = {};
  }
  
  return module.exports.basicURLParse(input, { baseURL: options.baseURL, encodingOverride: options.encodingOverride });
}
prototype
URLStateMachine prototype["parse fragment"]
Initial value:
= function parseSchemeStart(c, cStr) {
  if (isASCIIAlpha(c)) {
    this.buffer += cStr.toLowerCase();
    this.state = "scheme";
  } else if (!this.stateOverride) {
    this.state = "no scheme";
    --this.pointer;
  } else {
    this.parseError = true;
    return failure;
  }
  return true;
}
punycode
const punycode = require("punycode")
serializeHost
module exports serializeHost = serializeHost
serializeInteger
module exports serializeInteger
Initial value:
= function (integer) {
  return String(integer);
}
serializeURL
module exports serializeURL = serializeURL
serializeURLOrigin
module exports serializeURLOrigin
Initial value:
= function (url) {
  
  switch (url.scheme) {
    case "blob":
      try {
        return module.exports.serializeURLOrigin(module.exports.parseURL(url.path[0]));
      } catch (e) {
        
        return "null";
      }
    case "ftp":
    case "gopher":
    case "http":
    case "https":
    case "ws":
    case "wss":
      return serializeOrigin({
        scheme: url.scheme,
        host: url.host,
        port: url.port
      });
    case "file":
      
      return "file://";
    default:
      
      return "null";
  }
}
setThePassword
module exports setThePassword
Initial value:
= function (url, password) {
  url.password = "";
  const decoded = punycode.ucs2.decode(password);
  for (let i = 0; i < decoded.length; ++i) {
    url.password += percentEncodeChar(decoded[i], isUserinfoPercentEncode);
  }
}
setTheUsername
module exports setTheUsername
Initial value:
= function (url, username) {
  url.username = "";
  const decoded = punycode.ucs2.decode(username);
  for (let i = 0; i < decoded.length; ++i) {
    url.username += percentEncodeChar(decoded[i], isUserinfoPercentEncode);
  }
}
specialSchemes
const specialSchemes
Initial value:
= {
  ftp: 21,
  file: null,
  gopher: 70,
  http: 80,
  https: 443,
  ws: 80,
  wss: 443
}
strict
use strict
tr46
const tr46 = require("tr46")