backend/node_modules/yargs/build/lib/usage.js File Reference
Functions
function isBoolean (fail)
function export usage (yargs, shim)
function isIndentedText (text)
function addIndentation (text, indent)
function getIndentation (text)
function getText (text)
Variables
import { objFilter } from './utils/obj-filter.js'
import setBlocking from utils set blocking js
Function Documentation
addIndentation()
function addIndentation (text, indent)
References isIndentedText(), and text.
getIndentation()
function getIndentation (text)
References isIndentedText(), and text.
getText()
function getText (text)
References isIndentedText(), and text.
isBoolean()
function isBoolean (fail)
References fail.
isIndentedText()
function isIndentedText (text)
References text.
usage()
function export usage (yargs, shim)
References $, __, a, addIndentation(), alias(), align, Array, b, command(), commands, context, describe(), e, emit, enabled, f, fail, filter, fn, g, getIndentation(), getText(), group(), i, isBoolean, JSON, k, keys, length, logger, map, message, msg, n, objFilter(), parseInt(), prefix, reset, s, setBlocking(), shim, str(), string, test, text, toString, type, u, undefined, usage(), v, value, values, version, wrap, and yargs.
Variable Documentation
import
import { objFilter } from './utils/obj-filter.js'
js
import setBlocking from utils set blocking js