backend/node_modules/protobufjs/src/verifier.js File Reference
Functions
function invalid (field, expected)
function genVerifyValue (gen, field, fieldIndex, ref)
function genVerifyKey (gen, field, ref)
function verifier (mtype)
Variables
use strict
module exports = verifier
var Enum = require("./enum")
var util = require("./util")
Function Documentation
genVerifyKey()
function genVerifyKey (gen, field, ref)
Generates a partial key verifier.
Parameters
{Codegen} gen Codegen instance
{Field} field Reflected field
{string} ref Variable reference
Returns
{Codegen} Codegen instance @ignore
References invalid().
genVerifyValue()
function genVerifyValue (gen, field, fieldIndex, ref)
Generates a partial value verifier.
Parameters
{Codegen} gen Codegen instance
{Field} field Reflected field
{number} fieldIndex Field index
{string} ref Variable reference
Returns
{Codegen} Codegen instance @ignore
References Enum, invalid(), j, and keys.
invalid()
function invalid (field, expected)
References expected.
verifier()
function verifier (mtype)
Generates a verifier specific to the specified message type.
Parameters
{Type} mtype Message type
Returns
{Codegen} Codegen instance
References genVerifyKey(), genVerifyValue(), i, invalid(), and util.
Variable Documentation
Enum
var Enum = require("./enum")
exports
module exports = verifier
strict
use strict
util
var util = require("./util")