backend/node_modules/protobufjs/src/writer.js File Reference
Functions
function Op (fn, len, val)
function noop ()
function Writer ()
function writeByte (val, buf, pos)
function writeVarint32 (val, buf, pos)
function VarintOp (len, val)
function writeVarint64 (val, buf, pos)
function writeFixed32 (val, buf, pos)
Variables
use strict
module exports = Writer
var util = require("./util/minimal")
var BufferWriter
var LongBits = util.LongBits
var base64 = util.base64
var utf8 = util.utf8
var create
Writer alloc
Writer prototype _push
VarintOp prototype = Object.create(Op.prototype)
VarintOp prototype fn = writeVarint32
Writer prototype uint32
Writer prototype int32
Writer prototype sint32
Writer prototype uint64
Writer prototype int64 = Writer.prototype.uint64
Writer prototype sint64
Writer prototype bool
Writer prototype fixed32
Writer prototype sfixed32 = Writer.prototype.fixed32
Writer prototype fixed64
Writer prototype sfixed64 = Writer.prototype.fixed64
Writer prototype float
Writer prototype double
var writeBytes
Writer prototype bytes
Writer prototype string
Writer prototype fork
Writer prototype reset
Writer prototype ldelim
Writer prototype finish
Writer _configure
Function Documentation
noop()
function noop ()
Op()
function Op (fn, len, val)
Constructs a new writer operation instance. @classdesc Scheduled writer operation. @constructor
Parameters
{function(*,Uint8Array,number)} fn Function to call
{number} len Value byte length
{*} val Value to write @ignore
Function to call. @type {function(Uint8Array, number, *)}
Value byte length. @type {number}
Next operation. @type {Writer.Op|undefined}
Value to write. @type {*}
References fn, next(), and undefined.
VarintOp()
function VarintOp (len, val)
Constructs a new varint writer operation instance. @classdesc Scheduled varint writer operation.
@constructor
Parameters
{number} len Value byte length
{number} val Value to write @ignore
References next(), and undefined.
writeByte()
function writeByte (val, buf, pos)
References buf.
writeFixed32()
function writeFixed32 (val, buf, pos)
References buf.
Writer()
function Writer ()
Constructs a new writer instance. @classdesc Wire format writer using Uint8Array if available, otherwise Array. @constructor Current length. @type {number}
Operations head. @type {Object}
Operations tail @type {Object}
Linked forked states. @type {Object|null}
References head, noop(), Op(), and tail().
writeVarint32()
function writeVarint32 (val, buf, pos)
References buf.
writeVarint64()
function writeVarint64 (val, buf, pos)
References buf.
Variable Documentation
_configure
Writer _configure
Initial value:
= function(BufferWriter_) {
    BufferWriter = BufferWriter_;
    Writer.create = create();
    BufferWriter._configure();
}
_push
Writer prototype _push [private]
Initial value:
= function push(fn, len, val) {
    this.tail = this.tail.next = new Op(fn, len, val);
    this.len += len;
    return this;
}
Pushes a new operation to the queue.
Parameters
{function(Uint8Array,number,*)} fn Function to call
{number} len Value byte length
{number} val Value to write
Returns
{Writer} this
alloc
Writer alloc
Initial value:
= function alloc(size) {
    return new util.Array(size);
}
Allocates a buffer of the specified size.
Parameters
{number} size Buffer size
Returns
{Uint8Array} Buffer
base64
var base64 = util.base64
bool
Writer prototype bool
Initial value:
= function write_bool(value) {
    return this._push(writeByte, 1, value ? 1 : 0);
}
Writes a boolish value as a varint.
Parameters
{boolean} value Value to write
Returns
{Writer} this
BufferWriter
var BufferWriter
bytes
Writer prototype bytes
Initial value:
= function write_bytes(value) {
    var len = value.length >>> 0;
    if (!len)
        return this._push(writeByte, 1, 0);
    if (util.isString(value)) {
        var buf = Writer.alloc(len = base64.length(value));
        base64.decode(value, buf, 0);
        value = buf;
    }
    return this.uint32(len)._push(writeBytes, len, value);
}
Writes a sequence of bytes.
Parameters
{Uint8Array|string} value Buffer or base64 encoded string to write
Returns
{Writer} this
create
Writer create
Initial value:
= function create() {
    return util.Buffer
        ? function create_buffer_setup() {
            return (Writer.create = function create_buffer() {
                return new BufferWriter();
            })();
        }
        
        : function create_array() {
            return new Writer();
        };
}
Creates a new writer. @function
Returns
{BufferWriter|Writer} A BufferWriter when Buffers are supported, otherwise a Writer
double
Writer prototype double
Initial value:
= function write_double(value) {
    return this._push(util.float.writeDoubleLE, 8, value);
}
Writes a double (64 bit float). @function
Parameters
{number} value Value to write
Returns
{Writer} this
exports
module exports = Writer
finish
Writer prototype finish
Initial value:
= function finish() {
    var head = this.head.next,
        buf = this.constructor.alloc(this.len),
        pos = 0;
    while (head) {
        head.fn(head.val, buf, pos);
        pos += head.len;
        head = head.next;
    }
    
    return buf;
}
Finishes the write operation.
Returns
{Uint8Array} Finished buffer
fixed32
Writer prototype fixed32
Initial value:
= function write_fixed32(value) {
    return this._push(writeFixed32, 4, value >>> 0);
}
Writes an unsigned 32 bit value as fixed 32 bits.
Parameters
{number} value Value to write
Returns
{Writer} this
fixed64
Writer prototype fixed64
Initial value:
= function write_fixed64(value) {
    var bits = LongBits.from(value);
    return this._push(writeFixed32, 4, bits.lo)._push(writeFixed32, 4, bits.hi);
}
Writes an unsigned 64 bit value as fixed 64 bits.
Parameters
{Long|number|string} value Value to write
Returns
{Writer} this
Exceptions
{TypeError} If value is a string and no long library is present.
float
Writer prototype float
Initial value:
= function write_float(value) {
    return this._push(util.float.writeFloatLE, 4, value);
}
Writes a float (32 bit). @function
Parameters
{number} value Value to write
Returns
{Writer} this
fn
VarintOp prototype fn = writeVarint32
fork
Writer prototype fork
Initial value:
= function fork() {
    this.states = new State(this);
    this.head = this.tail = new Op(noop, 0, 0);
    this.len = 0;
    return this;
}
Forks this writer's state by pushing it to a stack. Calling Writer#reset|reset or Writer#ldelim|ldelim resets the writer to the previous state.
Returns
{Writer} this
int32
Writer prototype int32
Initial value:
= function write_int32(value) {
    return value < 0
        ? this._push(writeVarint64, 10, LongBits.fromNumber(value))
        : this.uint32(value);
}
Writes a signed 32 bit value as a varint. @function
Parameters
{number} value Value to write
Returns
{Writer} this
int64
Writer prototype int64 = Writer.prototype.uint64
Writes a signed 64 bit value as a varint. @function
Parameters
{Long|number|string} value Value to write
Returns
{Writer} this
Exceptions
{TypeError} If value is a string and no long library is present.
ldelim
Writer prototype ldelim
Initial value:
= function ldelim() {
    var head = this.head,
        tail = this.tail,
        len = this.len;
    this.reset().uint32(len);
    if (len) {
        this.tail.next = head.next;
        this.tail = tail;
        this.len += len;
    }
    return this;
}
Resets to the last state and appends the fork state's current write length as a varint followed by its operations.
Returns
{Writer} this
LongBits
var LongBits = util.LongBits
prototype
VarintOp prototype = Object.create(Op.prototype)
reset
Writer prototype reset
Initial value:
= function reset() {
    if (this.states) {
        this.head = this.states.head;
        this.tail = this.states.tail;
        this.len = this.states.len;
        this.states = this.states.next;
    } else {
        this.head = this.tail = new Op(noop, 0, 0);
        this.len = 0;
    }
    return this;
}
Resets this instance to the last state.
Returns
{Writer} this
sfixed32
Writer prototype sfixed32 = Writer.prototype.fixed32
Writes a signed 32 bit value as fixed 32 bits. @function
Parameters
{number} value Value to write
Returns
{Writer} this
sfixed64
Writer prototype sfixed64 = Writer.prototype.fixed64
Writes a signed 64 bit value as fixed 64 bits. @function
Parameters
{Long|number|string} value Value to write
Returns
{Writer} this
Exceptions
{TypeError} If value is a string and no long library is present.
sint32
Writer prototype sint32
Initial value:
= function write_sint32(value) {
    return this.uint32((value << 1 ^ value >> 31) >>> 0);
}
Writes a 32 bit value as a varint, zig-zag encoded.
Parameters
{number} value Value to write
Returns
{Writer} this
sint64
Writer prototype sint64
Initial value:
= function write_sint64(value) {
    var bits = LongBits.from(value).zzEncode();
    return this._push(writeVarint64, bits.length(), bits);
}
Writes a signed 64 bit value as a varint, zig-zag encoded.
Parameters
{Long|number|string} value Value to write
Returns
{Writer} this
Exceptions
{TypeError} If value is a string and no long library is present.
strict
use strict
string
Writer prototype string
Initial value:
= function write_string(value) {
    var len = utf8.length(value);
    return len
        ? this.uint32(len)._push(utf8.write, len, value)
        : this._push(writeByte, 1, 0);
}
Writes a string.
Parameters
{string} value Value to write
Returns
{Writer} this
uint32
Writer prototype uint32
Initial value:
= function write_uint32(value) {
    
    
    this.len += (this.tail = this.tail.next = new VarintOp(
        (value = value >>> 0)
                < 128 ? 1
        : value < 16384 ? 2
        : value < 2097152 ? 3
        : value < 268435456 ? 4
        : 5,
    value)).len;
    return this;
}
Writes an unsigned 32 bit value as a varint.
Parameters
{number} value Value to write
Returns
{Writer} this
uint64
Writer prototype uint64
Initial value:
= function write_uint64(value) {
    var bits = LongBits.from(value);
    return this._push(writeVarint64, bits.length(), bits);
}
Writes an unsigned 64 bit value as a varint.
Parameters
{Long|number|string} value Value to write
Returns
{Writer} this
Exceptions
{TypeError} If value is a string and no long library is present.
utf8
var utf8 = util.utf8
util
var util = require("./util/minimal")
writeBytes
var writeBytes
Initial value:
= util.Array.prototype.set
    ? function writeBytes_set(val, buf, pos) {
        buf.set(val, pos);
    }
    
    : function writeBytes_for(val, buf, pos) {
        for (var i = 0; i < val.length; ++i)
            buf[pos + i] = val[i];
    }