backend/node_modules/yargs-parser/build/lib/string-utils.js File Reference
Functions
function export camelCase (str)
function export decamelize (str, joinString)
function export looksLikeNumber (x)
Function Documentation
camelCase()
function export camelCase (str)
@license Copyright (c) 2016, Contributors SPDX-License-Identifier: ISC
References i, length, and str().
decamelize()
function export decamelize (str, joinString)
References $, i, lowercase(), and str().
looksLikeNumber()
function export looksLikeNumber (x)
References $, a, d, e, f, i, test, and undefined.