var dir_67f40b57c9306405b278fbab719e7512 =
[
    [ "any.d.ts", "proto3-json-serializer_2build_2src_2any_8d_8ts.html", null ],
    [ "any.js", "proto3-json-serializer_2build_2src_2any_8js.html", "proto3-json-serializer_2build_2src_2any_8js" ],
    [ "bytes.d.ts", "bytes_8d_8ts.html", null ],
    [ "bytes.js", "bytes_8js.html", "bytes_8js" ],
    [ "duration.d.ts", "proto3-json-serializer_2build_2src_2duration_8d_8ts.html", null ],
    [ "duration.js", "proto3-json-serializer_2build_2src_2duration_8js.html", "proto3-json-serializer_2build_2src_2duration_8js" ],
    [ "enum.d.ts", "enum_8d_8ts.html", null ],
    [ "enum.js", "proto3-json-serializer_2build_2src_2enum_8js.html", "proto3-json-serializer_2build_2src_2enum_8js" ],
    [ "fieldmask.d.ts", "fieldmask_8d_8ts.html", null ],
    [ "fieldmask.js", "fieldmask_8js.html", "fieldmask_8js" ],
    [ "fromproto3json.d.ts", "fromproto3json_8d_8ts.html", null ],
    [ "fromproto3json.js", "fromproto3json_8js.html", "fromproto3json_8js" ],
    [ "index.d.ts", "proto3-json-serializer_2build_2src_2index_8d_8ts.html", null ],
    [ "index.js", "proto3-json-serializer_2build_2src_2index_8js.html", "proto3-json-serializer_2build_2src_2index_8js" ],
    [ "timestamp.d.ts", "proto3-json-serializer_2build_2src_2timestamp_8d_8ts.html", null ],
    [ "timestamp.js", "proto3-json-serializer_2build_2src_2timestamp_8js.html", "proto3-json-serializer_2build_2src_2timestamp_8js" ],
    [ "toproto3json.d.ts", "toproto3json_8d_8ts.html", null ],
    [ "toproto3json.js", "toproto3json_8js.html", "toproto3json_8js" ],
    [ "types.d.ts", "proto3-json-serializer_2build_2src_2types_8d_8ts.html", null ],
    [ "types.js", "proto3-json-serializer_2build_2src_2types_8js.html", "proto3-json-serializer_2build_2src_2types_8js" ],
    [ "util.d.ts", "proto3-json-serializer_2build_2src_2util_8d_8ts.html", null ],
    [ "util.js", "proto3-json-serializer_2build_2src_2util_8js.html", "proto3-json-serializer_2build_2src_2util_8js" ],
    [ "value.d.ts", "value_8d_8ts.html", null ],
    [ "value.js", "proto3-json-serializer_2build_2src_2value_8js.html", "proto3-json-serializer_2build_2src_2value_8js" ],
    [ "wrappers.d.ts", "wrappers_8d_8ts.html", null ],
    [ "wrappers.js", "proto3-json-serializer_2build_2src_2wrappers_8js.html", "proto3-json-serializer_2build_2src_2wrappers_8js" ]
];